- changelog.d/10113.feature
- synapse/logging/opentracing.py
- synapse/storage/database.py
This adds quite a lot of OpenTracing decoration for database activity. Specifically it adds tracing at four different levels:
* emit a span for each "interaction" - ie, the top level database function that we tend to call "transaction", but isn't really, because it can end up as multiple transactions.
* emit a span while we hold a database connection open
* emit a span for each database transaction - actual actual transaction.
* emit a span for each database query.
I'm aware this might be quite a lot of overhead, but even just running it on a local Synapse it looks really interesting, and I hope the overhead can be offset just by turning down the sampling frequency and finding other ways of tracing requests of interest (eg, the `force_tracing_for_users` setting).
> Add OpenTracing for database activity.

- changelog.d/10118.bugfix
- synapse/handlers/federation.py
> Limit number of events in a replication request

- changelog.d/10116.bugfix
- synapse/handlers/federation.py
If backfilling is slow then the client may time out and retry, causing Synapse to start a new `/backfill` before the existing backfill has finished, duplicating work.
> Don't try and backfill the same room in parallel.

- changelog.d/10124.misc
- synapse/handlers/sync.py
I hope this will improve #9564.
The current impl doesn't seem optimal. Here's what happens:
* sync arrives, we wait for a wakeup
* we get woken up by something random
* we run the to-device deletion.
* we ultimately decide it's not time to return yet
* we wait for another wakeup
* a to-device message arrives, which wakes us up
* we run the to-device deletion *again*.
* There cannot be anything to delete which we haven't already deleted, but the `last_deleted_stream_id` magic in `delete_messages_for_device` is confused by the new to-device message
* so we run a DELETE operation which will do nothing, but is surprisingly slow (something something handwave postgres deleted rows)
Hopefully, by doing the deletion right at the start, rather than after we get woken up, we can improve the latency …
> Delete delivered to-device messages earlier in /sync

- changelog.d/10105.misc
- synapse/rest/admin/__init__.py
- synapse/rest/admin/_base.py
- synapse/rest/admin/groups.py
- synapse/rest/admin/media.py
- synapse/rest/admin/users.py
> Add missing type hints to the admin API servlets

- changelog.d/10107.bugfix
- synapse/handlers/appservice.py
- tests/handlers/test_appservice.py
Fixes #1834.
`get_new_events_for_appservice` internally calls `get_events_as_list`, which will filter out any rejected events. If all returned events are filtered out, `_notify_interested_services` will return without updating the last handled stream position. If there are 100 consecutive such events, processing will halt altogether.
Breaking the loop is now done by checking whether we're up-to-date with `current_max` in the loop condition, instead of relying on an empty `events` list. …
> Always update AS last_pos, even on no events

- changelog.d/10132.doc
- docker/README.md
Looks like the README filename changed from `README.md` to `README.rst`
Or should the link go to this specific section of the README?
https://github.com/matrix-org/synapse/blob/develop/README.rst#help-synapse-is-slow-and-eats-all-my-ram-cpu
Signed-off-by: Chris Castle <chris@crc.io>
I receive the following error when I run the linter on `docker/README.md`
```
$ ./scripts-dev/lint.sh docker/README.md 
Linting these paths: docker/README.md
+ …
```
> Fix broken link to README at root of repo

- changelog.d/10135.misc
- synapse/logging/opentracing.py
- synapse/metrics/background_process_metrics.py
... otherwise we tend to get a namespace clash between the bg process and the functions that it calls.
> opentracing: use a consistent name for background processes

- changelog.d/10136.feature
- synapse/storage/database.py
Add a couple of extra logs/spans, to give a bit of a better idea.
follow-up to #10113.
> More database opentracing

- changelog.d/10013.misc
- docs/dev/git.md
- scripts-dev/release.py
With the prior format, 1.33.0 / 1.33.1 / 1.33.2 got separate branches:
release-v1.33.0
release-v1.33.1
release-v1.33.2
Under the new model, all three would share a common branch:
release-v1.33
As before, RCs and actual releases exist as tags on these branches.
This better reflects our support model, e.g., that the "1.33" series had
a formal release followed by two patches / updates.
> Name release branches just after major.minor

- changelog.d/10137.misc
- mypy.ini
- synapse/http/servlet.py
- synapse/rest/admin/rooms.py
- synapse/rest/client/v1/login.py
- synapse/rest/client/v1/room.py
- synapse/rest/consent/consent_resource.py
- synapse/rest/media/v1/upload_resource.py
Does a few things:
* Fixes the type hints added in #10048 which were incorrect in some situations.
* Adds a seperate `parse_bytes` method (which simplifies the above type hints dramatically).
* Enables mypy for the `servlet` file (which would have found the issues with #10048).
Each commit should be reviewable separately.
This is blocking #10080, as the type hints that are currently there conflict with that PR.
> Correct type hints for parse_string(s)_from_args.

- changelog.d/10141.feature
- synapse/storage/database.py
> Fix logging context when opening new DB connection

- changelog.d/10143.misc
- synapse/http/matrixfederationclient.py
- synapse/logging/opentracing.py
- synapse/replication/http/_base.py
A couple of changes here:
* remove the unused `inject_active_span_text_map` and `inject_active_span_twisted_headers` methods
* rename `inject_active_span_byte_dict` to `inject_header_dict`, and change the way `check_destination` works to make it a bit more intuitive.
Suggest reviewing individual commits.
> Clean up the interface for injecting opentracing over HTTP

- changelog.d/10144.misc
- synapse/handlers/e2e_keys.py
- synapse/rest/client/v2_alpha/keys.py
- tests/handlers/test_e2e_keys.py
A client bug caused many in-flight `/keys/query` requests to come from a single device, causing high load. We should limit the number allowed at a single time.
Most of this PR is indentation changes, so might want to look at it without whitespace changes.
> Limit the number of in-flight /keys/query requests from a single device.

- changelog.d/9359.feature
- synapse/handlers/room_list.py
- synapse/storage/databases/main/room.py
This PR implements the ["Changes regarding the Public Rooms Directory"](https://github.com/Sorunome/matrix-doc/blob/soru/knock/proposals/2403-knock.md#changes-regarding-the-public-rooms-directory) section of knocking MSC2403.
Specifically, it:
* Allows rooms with `join_rule` "knock" to be returned by the query behind the public rooms directory
* Adds the field `join_rule` to each room entry returned by a public rooms directory query, so clients can know whether to attempt a join or knock on a room
Based on #6739. Complement tests for this change: https://github.com/matrix-org/complement/pull/72
> Integrate knock rooms with the public rooms directory

- .github/workflows/tests.yml
- changelog.d/10155.misc
This PR updates the build tags that we perform Complement runs with to match our [buildkite pipeline](https://github.com/matrix-org/pipelines/blob/618b3e90bcae8efd1a71502ae95b7913e6e24665/synapse/pipeline.yml#L570), as well as adding `msc2403` (as it will be required once #9359 is merged). Build tags are what we use to determine which tests to run in Complement (really it determines which test files are compiled into the final binary).
I haven't put in a comment about updating the buildkite side here, as we've decided to migrate fully to GitHub Actions anyhow.
Requires: https://github.com/matrix-org/synapse/pull/9359
> Update Complement run with Synapse-supported MSC-related build tags

- changelog.d/10122.doc
- docs/sample_config.yaml
- synapse/config/repository.py
> Mention that you need to configure max upload size in reverse proxy as well

- changelog.d/10156.misc
- synapse/handlers/federation.py
Add metrics to track how often events are `soft_failed`
Spawned from missing messages we were seeing on `matrix.org` from a
federated Gitter bridged room, https://gitlab.com/gitterHQ/webapp/-/issues/2770.
The underlying issue in Synapse is tracked by https://github.com/matrix-org/synapse/issues/10066
where the message and join event race and the message is `soft_failed` before the
`join` event reaches the remote federated server.
Less soft_failed events = better and usually this should only trigger for events
where people are doing bad things and trying to fuzz and fake everything.
This metric does not track what situation causes the event to be `soft_failed` but could be used to know how many people roughly are potentially running into https://github.com/matrix-org/synapse/issues/10066. …
> Add metrics to track how often events are `soft_failed`

- changelog.d/10149.bugfix
- synapse/storage/databases/main/presence.py
- synapse/storage/util/id_generators.py
> Fix bug when running presence off master

- changelog.d/10154.bugfix
- synapse/app/admin_cmd.py
Fixes: https://github.com/matrix-org/synapse/issues/10128
This PR fixes an import in `synapse/app/admin_cmd.py` that broke in #9820. Interestingly none of our linting caught this, even though our linting tools pass over this file. I'm not quite sure why, but my thought is that as this file is technically a new entrypoint to the codebase, `flake8` (which would be the tool to catch this), isn't able to check `synapse.replication.slave.storage.presence.SlavedPresenceStore` actually exists.
While this PR does remove the import, nowhere do I see in `admin_cmd.py` nor in `hs.get_admin_handler().export_user_data()`, which this function calls, the usage of any methods from `SlavedPresenceStore`, now `PresenceStore`. So I'm not sure if it's necessary to replace the import with anything.
I'm also …
> Clean up a broken import in admin_cmd.py

- changelog.d/10163.bugfix
- synapse/handlers/presence.py
When using a federation sender we'd send out all local presence updates over
federation even when they shouldn't be.
Fixes #10153.
Introduced in #9819
> Fix sending presence over federation when using workers

- .github/workflows/tests.yml
- changelog.d/10160.misc
This is akin to matrix-org/pipelines#157, but using GitHub Actions.
> Manually pull the complement branch matching the current branch name.

- changelog.d/10165.bugfix
- synapse/handlers/presence.py
It turns out that we were sending the same presence state to a remote potentially multiple times.
In practice this is probably isn't causing too many issues, as each federation destination queue will dedupe presence updates. However, depending on caching, it is possible that we'd start a new transaction the first time the destination queue gets told about an update. This would cause us to send the presence update twice.
> Only send a presence state to a destination once

- changelog.d/10164.misc
- docs/development/database_schema.md
> Notes on boolean columns in database schemas.

- changelog.d/10157.misc
- synapse/replication/http/_base.py
- synapse/replication/http/membership.py
- synapse/util/caches/response_cache.py
- tests/util/caches/test_response_cache.py
This is the first of two PRs which seek to address #8518. This first PR lays the groundwork by extending `ResponseCache`; a second PR (#10158) will update the `SyncHandler` to actually use it, and fix the bug. The two PRs form an alternative to #9739.
The idea here is that we allow the callback given to `ResponseCache.wrap` to decide whether its result should be cached or not. We do that by (optionally) passing a `ResponseCacheContext` into it, which it can modify.
I think this is considerably simpler than the solution in #9739.
(The commits in this PR should be reviewable individually - the first three are just minor cleanups and refactoring; the meat happens in 63e6c20.)
Also fixes #9738
> Extend `ResponseCache` to pass a context object into the callback

- changelog.d/10145.misc
- synapse/storage/persist_events.py
some cleanup, pulled out of #10134.
> Refactor `EventPersistenceQueue`

- changelog.d/10167.feature
- synapse/api/constants.py
- synapse/api/room_versions.py
- synapse/config/experimental.py
- synapse/federation/federation_client.py
- synapse/federation/transport/client.py
- synapse/federation/transport/server.py
- synapse/handlers/federation.py
- synapse/handlers/room_member.py
- synapse/rest/__init__.py
- synapse/rest/client/v2_alpha/knock.py
- tests/federation/transport/test_knocking.py
- tests/rest/client/v2_alpha/test_sync.py
Should be reviewable commit-by-commit:
* Removes the experimental config flag.
* Uses stable:
* Room version
* Endpoints
* Prefixes
See matrix-org/complement#125 for complement updates.
> Remove the experimental flag for knocking and use stable prefixes / endpoints.

- changelog.d/10161.removal
- synapse/api/constants.py
- synapse/handlers/space_summary.py
This drops support for unstable prefixes for MSC1772 (`org.org.matrix.msc1772.space.*`). This will change to only support the `m.space.*` versions.
I think this is fine since current Element clients (which I believe are the only things to support spaces) only use the stable prefixes and we said very loudly from the beginning that the unstable prefixes would break.
The reality of this is that you would not be able to use the spaces summary on those anymore, but current Elements treat them as normal rooms anyway so it shouldn't matter.
Fixes #9929
> Remove support for unstable MSC1772 prefixes.

- changelog.d/10134.misc
- synapse/api/auth.py
- synapse/logging/opentracing.py
- synapse/storage/persist_events.py
Previously, because events were persisted by a separate background process, we wouldn't be able to see what was happening when we traced an event send request.
~~ Let's treat the persist operation as a child of the send request~~
~~There are a couple of preparatory refactors here: suggest reviewing commit-by-commit.~~ 
~~Now based on #10145.~~
Use the span references feature to link from the persist operation to the request, and back again.
> Make opentracing trace into event persistence

- changelog.d/10180.doc
- docs/admin_api/README.rst
- docs/admin_api/delete_group.md
- docs/admin_api/event_reports.md
- docs/admin_api/media_admin_api.md
- docs/admin_api/purge_history_api.md
- docs/admin_api/room_membership.md
- docs/admin_api/rooms.md
- docs/admin_api/statistics.md
- docs/admin_api/user_admin_api.md
- docs/consent_tracking.md
- docs/federate.md
- docs/message_retention_policies.md
- docs/metrics-howto.md
- docs/presence_router_module.md
- docs/reverse_proxy.md
- docs/sso_mapping_providers.md
- docs/systemd-with-workers/README.md
- docs/workers.md
Related to: #10086
A lot of 404 errors in new docs: https://matrix-org.github.io/synapse/develop/welcome_and_overview.html
> Fix broken links in documentation

- changelog.d/10175.bugfix
- synapse/rest/client/v2_alpha/openid.py
`expires_in` must be an integer according to the OpenAPI spec:
https://github.com/matrix-org/matrix-doc/blob/master/data/api/client-server/definitions/openid_token.yaml#L32
True division (`/`) returns a float instead (`"expires_in": 3600.0`).
Floor division (`//`) returns an integer, so the response is spec compliant.
> Fix requestOpenIdToken response: integer expires_in

- changelog.d/10184.bugfix
- docs/sample_config.yaml
- synapse/config/auth.py
- synapse/handlers/auth.py
- synapse/rest/client/v2_alpha/devices.py
- synapse/rest/client/v2_alpha/keys.py
This limits the UI auth grace period to:
* Deleting devices
* Uploading cross-signing keys
So it stops using it for (and thus always requires UI auth):
* Deactivating accounts
* Resetting passwords
* Adding 3PIDs
It should be easy to change the above list if people want to bikeshed it. (In particular adding 3PIDs I went back and forth on.)
This modifies behavior added in #8970 in a backwards-incompatible manner, but I think it is likely OK in this case as the security added outweighs backwards compatibility concerns.
Fixes #9754
> Only allow skipping UI auth for certain actions.

- changelog.d/10188.misc
- synapse/logging/_terse_json.py
Per conversation in #synapse-dev:matrix.org.
> Improve comments in the structured logging code.

- changelog.d/10193.misc
- synapse/storage/persist_events.py
Fixes a leak introduced in #10134.
> Fix persist_events to stop leaking opentracing contexts

- changelog.d/10168.misc
- synapse/handlers/federation.py
Add `room_id`, `mxid`, and `hs` fields to better debug where and who events are being `soft_failed`. We can do aggregations with Elasticsearch and Kibana on these fields.
Follow-up to https://github.com/matrix-org/synapse/pull/10156#discussion_r650292223
1. Enable structured logging in the Sytest Synapse homeserver config,
1. In the `formatters` property, add a `structured` key (this key could be named anything) that points to the `synapse.logging.TerseJsonFormatter` class, [`lib/SyTest/Homeserver.pm#L220-L224`)(https://github.com/matrix-org/sytest/blob/eedac420ae8c810f48200e7a4ba6a3bc85958f35/lib/SyTest/Homeserver.pm#L220-L224)
```diff
formatters => {
precise => {
format => "%(asctime)s - %(name)s - %(lineno)d - %(levelname)s - %(request)s - %(message)s"
},
+    structured => {
+ …
```
> Add fields to better debug where events are being `soft_failed`

- changelog.d/10195.bugfix
- synapse/storage/databases/main/roommember.py
Fixes https://github.com/matrix-org/synapse/issues/10030.
We were expecting milliseconds where we should have provided a value in seconds.
The impact of this bug isn't too bad. The code is intended to count the number of remote servers that the homeserver can see and report that as a metric. This metric is supposed to run initially 1 second after server startup, and every 60s as well. Instead, it ran 1,000 seconds after server startup, and every 60s after startup.
This fix allows for the correct metrics to be collected immediately, as well as preventing a random collection 1,000s in the future after startup.
> Fix incorrect time magnitude on delayed call

- changelog.d/10197.misc
- contrib/experiments/cursesio.py
- setup.py
- synapse/handlers/federation.py
- synapse/http/servlet.py
- synapse/replication/tcp/handler.py
- synapse/types.py
- tests/handlers/test_appservice.py
- tests/handlers/test_directory.py
- tests/handlers/test_profile.py
- tests/handlers/test_register.py
- tests/handlers/test_sync.py
- tests/rest/client/v1/test_events.py
- tests/rest/client/v1/test_presence.py
- tests/rest/client/v1/test_rooms.py
- tests/rest/client/v1/test_typing.py
- tests/storage/test_base.py
Reformat all files with the new version.
> update black to 21.6b0

- changelog.d/10190.misc
- synapse/app/_base.py
As I've written in various places in the past (#7113, #9865) I'm pretty sure this is doing nothing useful at all.
> Rip out the DNS lookup limiter

- changelog.d/10157.bugfix
- changelog.d/10157.misc
- changelog.d/10158.bugfix
- synapse/handlers/sync.py
- synapse/python_dependencies.py
- synapse/types.py
- tests/rest/client/v2_alpha/test_sync.py
- tests/server.py
Fixes #8518 by telling the `ResponseCache` not to cache the `/sync` response if the next_batch param is the same as the `since` token.
~~Based on #10157.~~
Note that actually enabling the sync cache timeout (ie, #3880) is left for a future task.
> Ensure that we do not cache empty sync responses after a timeout

- changelog.d/10189.misc
- synapse/api/constants.py
- synapse/handlers/event_auth.py
- synapse/handlers/space_summary.py
* Add a type field.
* Switch `space` -> `room_id`.
Complement changes: matrix-org/complement#129
> Update MSC3083 support per changes in the MSC.

- changelog.d/10199.misc
- synapse/federation/transport/server.py
- synapse/logging/opentracing.py
> Expose opentracing trace id in response headers

- changelog.d/10206.feature
- docs/modules.md
I've just realised that after merging #10062. The doc already says callbacks must be async but it's probably better to make it as obvious as possible.
> Describe callbacks signatures as async in new modules doc

- changelog.d/10208.bugfix
- synapse/handlers/space_summary.py
- tests/handlers/test_space_summary.py
* Adds a couple of unit tests.
* Fixes a missing `await` in the spaces summary API. (This was introduced in #10109.)
> Fix a missing await when in the spaces summary

- .github/workflows/docs.yaml
- changelog.d/10198.doc
This PR will run a new "Deploy release-specific documentation" job whenever a push to a branch name matching `release-v*` occurs. Doing so will create/add to a folder named `vX.Y` on the `gh-pages` branch. Doing so will allow us to build up `major.minor` releases of the docs as we release Synapse.
This is especially useful for having a mechanism for keeping around documentation of old/removed features (for those running older versions of Synapse), without needing to clutter the latest copy of the docs.
After a [discussion](https://matrix.to/#/!XaqDhxuTIlvldquJaV:matrix.org/$rKmkBmQle8OwTlGcoyu0BkcWXdnHW3_oap8BMgclwIY?via=matrix.org&via=vector.modular.im&via=envs.net) in #synapse-dev, we wanted to use tags to trigger the documentation deployments, which I agreed with. However, I soon …
> Deploy a documentation version for each new Synapse release

- changelog.d/10191.feature
- synapse/app/_base.py
- synapse/app/generic_worker.py
- synapse/app/homeserver.py
- synapse/config/logger.py
There is a class of exception that happens *after* setting up the logs, but *before* we start up the reactor (which has its own exception handling).
These end up hitting `sys.stderr`, and then one of two things happens:
* If stderr has been redirected to the logs, the error is written to the logs (one line at a time, which messes up structured logging and sentry), and nothing is written to the console (which is super misleading when running from a shell).
* If stdio redirection is disabled, the error is written to the console, and nothing is written to the logs. This is confusing when running synapse under a process supervisor (eg systemd), where it ies expected that all errors end up in the log (see also #1781).
It seems like the ideal would be for the errors to end up in *both* places; …
> Ensure that errors during startup are written to the logs and the console.

- changelog.d/10212.feature
- synapse/handlers/federation.py
An accidental mis-ordering of operations during #6739 technically allowed an incoming knock event over federation in before checking it against any configured Third Party Access Rules modules.
This PR corrects that by performing the TPAR check *before* persisting the event.
Thanks to @richvdh for catching it.
Uses the same changelog as #6739 as that has not yet been included in a release.
> Check third party rules before persisting knocks over federation

- changelog.d/10221.bugfix
- synapse/config/_base.pyi
- synapse/storage/databases/main/end_to_end_keys.py
We were repeatedly looking up a config option in a loop (using the
unclassed config style), which is expensive enough that it can cause
large CPU usage.
> Fix performance of responding to user key requests over federation

- changelog.d/10210.removal
- synapse/config/spam_checker.py
I forgot to do that in #10062 
So admins aren't surprised if things break when we remove this code in a couple of months.
> Warn users trying to use the deprecated spam checker interface

- changelog.d/10227.feature
- synapse/storage/schema/main/delta/59/11add_knock_members_to_stats.sql
Introduced in #6739
Fixes #10226
It doesn't look like anything is reading from these tables currently that care about `knocked_members`.
> Fix schema delta to not take as long on large servers

- changelog.d/10114.misc
- synapse/http/server.py
This change drops the `Origin` and `Accept` header names from the value of the `Access-Control-Allow-Headers` response header sent by Synapse. Per the CORS protocol, it’s not necessary or useful to include those header names.
---
Details:
Per-spec at https://fetch.spec.whatwg.org/#forbidden-header-name, `Origin` is a “forbidden header name” set by the browser and that frontend JavaScript code is never allowed to set.
So the value of `Access-Control-Allow-Headers` isn’t relevant to `Origin` or in general to other headers set by the browser itself — the browser never ever consults the `Access-Control-Allow-Headers` value to confirm that it’s OK for the request to include an `Origin` header.
And per-spec at https://fetch.spec.whatwg.org/#cors-safelisted-request-header, `Accept` is a …
> Drop Origin & Accept from Access-Control-Allow-Headers value

- changelog.d/10223.bugfix
- scripts-dev/complement.sh
- synapse/handlers/federation.py
ensure that events sent via `send_leave` and `send_knock` are sent on to the rest of the federation.
Fixes #10222.
> Send out invite rejections and knocks over federation

- changelog.d/10214.feature
- changelog.d/9919.feature
- synapse/rest/client/v2_alpha/sync.py
- tests/rest/client/v2_alpha/test_sync.py
- tests/server_notices/test_resource_limits_server_notices.py
Closes: https://github.com/matrix-org/synapse/issues/9941
Required some fixes due to merge conflicts with #6739, but nothing too hairy. The first commit is the same as the original (after merge conflict resolution) then two more for compatibility with the latest sync code.
cc @callahad
> Re-introduce "Leave out optional keys from /sync" change

- changelog.d/10238.removal
- synapse/events/spamcheck.py
- tests/handlers/test_register.py
> Fix wrapping of legacy check_registration_for_spam

- changelog.d/10239.misc
- scripts-dev/release.py
* rename major/minor into the right semver terminology minor/patch (since this was something that got me very confused the first couple of times I've used the script)
* name the release branch based on the new version, not the previous one
> Fixes to the release script

- changelog.d/10225.feature
- synapse/federation/federation_server.py
- synapse/federation/transport/server.py
- synapse/handlers/federation.py
- tests/handlers/test_federation.py
- tests/replication/test_federation_sender_shard.py
The idea here is to stop people sending things that aren't joins/leaves/knocks through these endpoints: previously you could send anything you liked through them. I wasn't able to find any security holes from doing so, but it doesn't sound like a good thing.
I've taken the opportunity to merge the three almost identical codepaths. Commits best reviewed separately.
> Improve validation for `send_{join,leave,knock}`

- changelog.d/10243.feature
- synapse/handlers/federation.py
- tests/federation/transport/test_knocking.py
Rather than persisting rejected events via `send_join` and friends, raise a 403 if someone tries to pull a fast one.
(~~Based on #10225~~)
> Return errors from `send_join` etc if the event is rejected

- index.html
Context: https://github.com/matrix-org/synapse/pull/10242
`index.html` will still be the welcome page (for now), but if we ever decide to change that in the future, we won't need to update this redirect page again.
Note that CI is not expected to pass.
> Modify docs root redirect to develop/index.html instead of a specific page

- .github/workflows/docs.yaml
- changelog.d/10242.doc
Currently when a new build of the docs is created, an `index.html` file does not exist. Typically this would be generated from a`docs/README.md` file - which we have - however we're currently using [docs/README.md](https://github.com/matrix-org/synapse/blob/394673055db4df49bfd58c2f6118834a6d928563/docs/README.md) to explain the docs and point to the website. It is not part of the content of the website. So we end up not having an `index.html` file, which will result in a 404 page if one tries to navigate to `https://matrix-org.github.io/synapse/<docs_version>/index.html`.
This isn't a really problem for the default version of the documentation (currently `develop`), as [navigating to the top-level root](https://matrix-org.github.io/synapse/) of the website (without specifying a version) …
> Create an index.html file when generating a docs build

- changelog.d/10263.feature
- synapse/federation/federation_base.py
Soft-failing spam which arrives over federation achieves two things:
* the content will not be served to the clients of local users
* spam events will not be used as prev-events for future events we generate.
The second point is useful in the following situation. Suppose we have three servers in a room: `spammy.com`, `speedy.com` and `slow.com`. `spammy` creates thousands of events and sends them out to the other servers. `speedy` accepts them all (possibly redacting them or similar measures) and starts generating its own events (possibly including things like server ACLs). `slow.com` can't keep up with the traffic from `spammy.com` so when it sees events from `speedy.com` it sees unknown events which it needs to backfill, so traffic from `speedy.com` to `slow.com` is severely impacted …
> Soft-fail spammy events received over federation

- changelog.d/10264.bugfix
- synapse/storage/databases/main/events_bg_updates.py
- synapse/storage/schema/__init__.py
- synapse/storage/schema/main/delta/60/01recreate_stream_ordering.sql.postgres
A set of background updates (mostly) to replace `events.stream_ordering` with a `BIGINT`.
Fixes at least part of #8255.
The general approach here is:
1. Add a new `BIGINT` column called `stream_ordering2`.
2. Add a Postgres rule to populate that column with the same value as `stream_ordering` for any new rows.
3. Run a bg update to back-populate the column for all *existing* rows.
4. Add an index on the new column.
5. In a single transaction:
* Double-check that we didn't miss any rows with a final `UPDATE`
* Drop the rule
* Drop the old column
* Rename the new column into place
I still need to check that we don't have any ints in other tables.
> Migrate stream_ordering to a bigint

- changelog.d/10267.bugfix
- synapse/storage/databases/main/events_bg_updates.py
It was possible for us not to find any rows in a batch, and hence conclude that
we had finished. Let's not do that.
> Fix `populate_stream_ordering2` background job

- changelog.d/10256.misc
- synapse/api/constants.py
- synapse/handlers/space_summary.py
- tests/handlers/test_space_summary.py
- tests/rest/client/v1/utils.py
This is the straightforward part of #10085 split out into a separate PR.
This only searches for `m.child.space` events in spaces, not all rooms.
Clients do not use this information anyway (since they do not show a normal room as a space) -- the [MSC was updated](https://github.com/matrix-org/matrix-doc/pull/2946/commits/797dda44c4158e83dcff017f1ef2f36d7c2c4f3c) with these changes.
My hope is that this will help servers which have a slow database (or are starved for CPU, maybe). There's been some reports of the endpoint being very slow.
> Do not recurse into non-spaces in the spaces summary.

- changelog.d/10269.misc
- synapse/app/generic_worker.py
- synapse/storage/databases/main/__init__.py
- synapse/storage/databases/main/lock.py
- synapse/storage/schema/main/delta/59/15locks.sql
- tests/storage/databases/main/test_lock.py
This adds a simple best effort locking mechanism that works cross workers.
> Add a distributed lock

- changelog.d/10272.bugfix
- synapse/federation/federation_server.py
- synapse/storage/databases/main/event_federation.py
- synapse/storage/schema/main/delta/59/16federation_inbound_staging.sql
- sytest-blacklist
Fixes #9490
Based on #10269
This will break a couple of SyTest that are expecting failures to be added to the response of a federation `/send`, which obviously doesn't happen now that things are asynchronous.
Two drawbacks:
1. Currently there is no logic to handle any events left in the staging area after restart, and so they'll only be handled on the next incoming event in that room. That can be fixed separately.
2. We now only process one event per room at a time. This can be fixed up further down the line.
> Handle inbound events from federation asynchronously

- changelog.d/10279.bugfix
- synapse/federation/federation_server.py
- synapse/storage/databases/main/event_federation.py
- synapse/storage/engines/_base.py
- synapse/storage/engines/postgres.py
- synapse/storage/engines/sqlite.py
This broke in #10272
Tracking issue for async federation follow up work: #10275
> Fix the inbound PDU metric

- changelog.d/10253.misc
- synapse/api/auth.py
- synapse/event_auth.py
- synapse/events/__init__.py
- synapse/events/builder.py
- synapse/handlers/message.py
Found this while updating the implementation for MSC3083. Seemed easiest to put up a separate PR for it.
In order to not have an "unused" attribute, I need to change from using `blah = attr.ib(type=Foo` to `blah: "Foo"`. I took it as an opportunity to use `auto_attribs`.
> Correct type hints for computing auth events.

- changelog.d/10282.bugfix
- synapse/storage/databases/main/events_bg_updates.py
- synapse/storage/schema/main/delta/60/01recreate_stream_ordering.sql.postgres
We need to rebuild *all* of the indexes that use the current `stream_ordering` column.
This PR updates the existing schema delta file; it will be fine for servers which have not yet run that delta, but those which have will need some sort of manual intervention.
(followup from #10264)
> Rebuild other indexes using `stream_ordering`

- changelog.d/10288.doc
- docs/presence_router_module.md
The presence router docs include some sample homeserver config. At some point we changed the name of the [config option](https://github.com/matrix-org/synapse/blob/859dc05b3692a3672c1a0db8deaaa9274b6aa6f5/docs/sample_config.yaml#L104-L113), but forgot to update the docs.
I've also added `presence.enabled: true` to the example, as that's the new way to enable presence (the `presence_enabled` option has been deprecated).
> Fix the homeserver config example in presence router docs

- changelog.d/10261.feature
- docs/admin_api/user_admin_api.md
- synapse/handlers/admin.py
- tests/rest/admin/test_user.py
> Add SSO `external_ids` to Query User Account admin API

- changelog.d/10292.misc
- sytest-blacklist
Now that we've fixed it in https://github.com/matrix-org/sytest/pull/1059
> Reenable 'Backfilled events whose prev_events...' sytest

- changelog.d/10291.bugfix
- synapse/storage/schema/main/delta/60/01recreate_stream_ordering.sql.postgres
this was a typo introduced in #10282. We don't want to end up doing the
`replace_stream_ordering_column` update after anything that comes up in
migration 60/03.
> fix ordering of bg update

- changelog.d/10302.doc
- docs/modules.md
Fix link in modules doc to point at instructions on registering a callback instead of ones on registering a web resource.
> Fix bad link in modules documentation

- changelog.d/10303.bugfix
- synapse/federation/federation_server.py
- synapse/storage/databases/main/event_federation.py
We might have events in the staging area if the service was restarted while there were unhandled events in the staging area.
Fixes #10295
---
Currently this works by starting up a background task when we see an incoming transaction. The reason for doing it that way is that we don't know what know which workers are handling the incoming federation traffic. The downside to this is that there will be a delay in beginning to process old events until we see a new incoming transaction.
An alternative would be to always handle on e.g. the worker configured to run background tasks?
> Handle old staged inbound events

- changelog.d/10290.feature
- debian/changelog
- debian/hash_password.1
- debian/hash_password.ronn
- debian/manpages
- debian/matrix-synapse-py3.links
- debian/register_new_matrix_user.1
- debian/register_new_matrix_user.ronn
- debian/synapse_port_db.1
- debian/synapse_port_db.ronn
- debian/synapse_review_recent_signups.1
- debian/synapse_review_recent_signups.ronn
- debian/synctl.1
- debian/synctl.ronn
- scripts/synapse_review_recent_signups
- synapse/_scripts/review_recent_signups.py
- synapse/storage/database.py
Usage:
```
$ ./scripts/synapse_review_recent_signups  --help
usage: synapse_review_recent_signups [-h] [-c CONFIG_FILE] [-s duration] [-e]
optional arguments:
-h, --help            show this help message and exit
-c CONFIG_FILE, --config-path CONFIG_FILE
The config files for Synapse.
-s duration, --since duration
Specify how far back to review user registrations for, defaults to 7d (i.e. 7 days).
-e, --exclude-emails  Exclude users that have validated email addresses
```
Sample output:
```
User ID: @anon-20210630_165107-115:localhost:8800
Created: 2021-06-30 17:52:05
Email: None
IPs: 127.0.0.1
Number joined public rooms: 0 
Number joined private rooms: 0
User ID: @anon-20210630_165107-122:localhost:8800
Created: 2021-06-30 17:52:09
Email: None
IPs: 127.0.0.1
Number joined public rooms: 1 …
```
> Add script for getting info about recently registered users

- changelog.d/10252.bugfix
- synapse/handlers/deactivate_account.py
- synapse/storage/databases/main/profile.py
- tests/rest/admin/test_user.py
Fixes: #10240
A user should also be deactivated and mark as erased if he has no profile.
> Fix deactivate a user if he does not have a profile

- changelog.d/10317.bugfix
- synapse/handlers/receipts.py
- synapse/handlers/typing.py
- tests/handlers/test_typing.py
We already ignore PDUs for rooms we're not in, but room-specific
EDUs (receipts and typing notifications) were still being processed
for rooms we had left.
> Ignore EDUs for rooms we're not in

- .github/workflows/docs.yaml
as well as running the job for master, I've reworked the logic for where we deploy to.
Firstly, we shouldn't deploy to `develop` unless we're actually building `develop` (as otherwise we can end up rewinding the develop docs to a release build).
Secondly, I've ripped out the RC logic. I wasn't at all convinced it was helpful. Consider a release cycle:
1. fork the release branch
2. land a release-blocking bugfix or two
3. cut an RC: bump the synapse version
4. cut the final release: bump the synapse version
It is odd to me that we will deploy the docs for the release branch ant steps 1, 2 and 4 but not step 3.
> build the docs for master

- changelog.d/10313.doc
- docs/admin_api/rooms.md
Approximating the documentation for rooms to that for users.
Simplify table of content of room admin API
> Simplify structure of room admin API docs

- changelog.d/10287.doc
- docs/sample_config.yaml
- docs/sample_log_config.yaml
- synapse/config/consent.py
- synapse/config/database.py
- synapse/config/jwt.py
- synapse/config/logger.py
- synapse/config/modules.py
- synapse/config/oidc.py
- synapse/config/password_auth_providers.py
- synapse/config/repository.py
- synapse/config/server.py
- synapse/config/spam_checker.py
- synapse/config/stats.py
- synapse/config/tracer.py
- synapse/config/user_directory.py
> Update links to documentation in sample config

- changelog.d/10316.misc
- synapse/handlers/message.py
Because modules might send extra state events when processing an event (e.g. https://github.com/matrix-org/synapse-dinsic/pull/100), and in some cases these extra events might get dropped if we don't recalculate the initial event's auth.
> Rebuild event auth when rebuilding an event after a call to a `ThirdPartyEventRules` module

- changelog.d/10324.misc
- synapse/storage/databases/main/metrics.py
Change 1: we use the clock as the source of time in _get_start_of_day, because otherwise in (WIP) tests, we end up in a situation where we're searching (real time) < ... <= (fake time), which typically yields no results, as real time is much bigger than fake time.
Change 2: Use `? <= last_seen AND last_seen < ?` instead of `? < last_seen AND last_seen <= ?`, because the latter ignores changes that occur in the same millisecond after the query is run (which is probably a bit pedantic for real life, but in tests, causes trouble).
> Minor changes to `user_daily_visits`

- changelog.d/10336.bugfix
- synapse/federation/federation_server.py
- synapse/storage/databases/main/lock.py
Hopefully fixes errors like: `Lock for (federation_inbound_pdu, <room_id>) dropped without being released`
(Sentry link: https://sentry.matrix.org/sentry/synapse-matrixorg/issues/224832/)
> Ensure we always drop the federation inbound lock

- changelog.d/10343.bugfix
- synapse/storage/databases/main/events.py
- synapse/storage/databases/main/purge_events.py
Occasionally, in combination with retention, redactions aren't deleted
from the database whenever they are due for deletion. The server will
eventually try to backfill the deleted events and trip over the already
existing redaction events.
Switching to an UPSERT for those events allows us to recover from there
situations. The retention code still needs fixing but that is outside of
my current comfort zone on this code base.
This is related to #8707 where the error was discussed already. …
> Upsert redactions in case they already exists

- changelog.d/10344.bugfix
- synapse/storage/databases/main/stats.py
> Fix the user directory becoming broken (and noisy errors being logged) when knocking and room statistics are in use.

- changelog.d/10345.misc
- sytest-blacklist
... now that it has been fixed in https://github.com/matrix-org/sytest/pull/1061.
> Re-enable room v6 sytest

- changelog.d/10355.bugfix
- synapse/storage/databases/main/event_federation.py
We should be reporting the age rather than absolute timestamp.
The metric as it stands is a bit useless, as it defaults to a timestamp of `0`, which makes the graphs and alerting rules complicated.
Introduced in #10284.
> Fix federation inbound age metric.

- changelog.d/10347.misc
- tests/config/test_load.py
- tests/handlers/test_profile.py
- tests/http/federation/test_matrix_federation_agent.py
- tests/http/test_fedclient.py
- tests/replication/_base.py
- tests/replication/test_multi_media_repo.py
- tests/replication/test_sharded_event_persister.py
- tests/rest/admin/test_admin.py
- tests/rest/admin/test_room.py
- tests/rest/client/v1/test_rooms.py
- tests/rest/client/v2_alpha/test_relations.py
- tests/rest/client/v2_alpha/test_report_event.py
- tests/rest/media/v1/test_media_storage.py
- tests/storage/test_directory.py
- tests/storage/test_profile.py
- tests/storage/test_purge.py
- tests/storage/test_room.py
- tests/test_types.py
- tests/unittest.py
This PR is tantamount to running 
```
pyupgrade --py36-plus --keep-percent-format `find tests/ -type f -name "*.py"`
```
Part of #9744
---
> [pyupgrade] `tests/`

- changelog.d/10350.misc
- tests/events/test_presence_router.py
- tests/module_api/test_api.py
- tests/replication/_base.py
- tests/replication/tcp/streams/test_events.py
- tests/replication/tcp/streams/test_receipts.py
- tests/replication/tcp/streams/test_typing.py
- tests/replication/test_multi_media_repo.py
- tests/rest/client/test_third_party_rules.py
- tests/rest/client/v1/test_login.py
- tests/server.py
- tests/storage/test_background_update.py
- tests/storage/test_id_generators.py
- tests/test_state.py
- tests/test_utils/html_parsers.py
- tests/unittest.py
- tests/util/caches/test_descriptors.py
- tests/util/test_itertools.py
This PR is tantamount to running 
```
python3.8 -m com2ann -v 6 tests/
```
(com2ann requires python 3.8 to run)
Part of #8351
(`com2ann` changes comment type annotations to inline type annotations, `name = ... # type:` to `name: type = ...`, this is possible since python 3.6, and standard across the python ecosystem.)
---
> Use inline type hints in `tests/`

- changelog.d/10367.bugfix
- synapse/rest/admin/rooms.py
> Bugfix `make_room_admin` fails for users that have left a private room

- changelog.d/10393.misc
- mypy.ini
- synapse/event_auth.py
- tests/test_event_auth.py
Makes #10254 slightly smaller by pulling out some unrelated changes.
> Add type hints and comments to some event auth code.

- .github/workflows/release-artifacts.yml
- .github/workflows/tests.yml
- changelog.d/10383.misc
A few things here:
* Build the debs for single distro for each PR, so that we can see if it breaks. Do the same for `develop`. Building all the debs ties up the GHA workers for *ages*.
* Stop building the debs for `release` branches. Again, it takes ages, and I don't think anyone is actually going to stop and look at them. We'll know they are working when we make an RC.
* Change the configs so that if we manually cancel a workflow, it actually does something.
> Make GHA config more efficient

- changelog.d/10391.misc
- docker/build_debian.sh
This is part of fixing https://github.com/matrix-org/synapse/issues/6116: we want to put RC debs into a different place than release debs, so reprepro has to be able to tell them apart.
> Set section for prerelease debs

- changelog.d/10368.doc
- docs/reverse_proxy.md
This PR can be seen as a mere suggestion. I can see the documentation getting a bit out of hand if one adds full examples of all of the reverse proxies out there. Dedicated guides on how to set up a specific reverse proxy could be better maybe.
But I also thought that it couldn't hurt to expand the bit of documentation and give admins looking into getting all information from one source the opportunity to not just choose nginx because it's _just_ all there for it already.
Perhaps there is a better place within the repository to document full example of a specific reverse proxy flavor which?
The documentation consists of information I gathered from these sources:
- CORS headers: https://matrix.org/docs/spec/client_server/latest#cors
- `Content-Type "application/json"`: …
> doc: Add delegation example to the caddy reverse proxy section

- changelog.d/10400.bugfix
- synapse/handlers/directory.py
- synapse/handlers/federation.py
- synapse/handlers/room_list.py
- synapse/http/matrixfederationclient.py
Each commit is reviewable independently.
> Fix a number of logged errors caused by remote servers being down.

- changelog.d/10360.feature
- synapse/http/proxyagent.py
- tests/http/test_proxyagent.py
Add support for http proxy authentication via `http_proxy`
Fixes: #9000 
Follow up: #9657
Related to: #9119
~~I am need some help.
I do not know how to create the test case.
The missing part is to wrap the HTTP request into the proxy tunnel.~~
https://github.com/matrix-org/synapse/blob/25c9e4c0b11d0480e4cd07f7bc1316eae05c3397/tests/http/test_proxyagent.py#L311-L319
> Allow providing credentials to `http_proxy`

- changelog.d/10353.doc
- docs/log_contexts.md
By referring to awaitables instead of deferreds.
> Update the logcontext doc

- changelog.d/10398.misc
- synapse/federation/sender/__init__.py
- synapse/federation/sender/per_destination_queue.py
- tests/events/test_presence_router.py
This is to help with performance, where trying to connect to thousands of hosts at once can consume a lot of CPU (due to TLS etc).
> Stagger send presence to remotes

- changelog.d/10399.doc
- docs/MSC1711_certificates_FAQ.md
- docs/admin_api/server_notices.md
- docs/consent_tracking.md
- docs/delegate.md
- docs/federate.md
- docs/replication.md
- docs/reverse_proxy.md
- docs/server_notices.md
- docs/setup/installation.md
- docs/systemd-with-workers/README.md
- docs/workers.md
Our documentation has a history of using a document's name as a way to link to it, such as "See [workers.md]() for details". This makes sense when you're traversing a directory of files, but less sense when the files are abstracted away - as they are on the documentation website.
This PR changes the links to various documentation pages to something that fits better into the surrounding sentence, as you would when making any hyperlink on the web.
> Docs: Use something other than the document name to describe a page

- changelog.d/10315.misc
- synapse/storage/databases/main/metrics.py
- tests/app/test_phone_stats_home.py
I'm working on adding a new variant of R30.
This PR first characterises the current behaviour of the current R30 metric, by adding unit tests.
> Add tests to characterise the current behaviour of R30 phone-home metrics

- changelog.d/10395.doc
- docs/spam_checker.md
> Make deprecation notice of the spam checker doc more obvious

- changelog.d/10404.bugfix
- synapse/events/__init__.py
- synapse/federation/federation_server.py
Currently the responses to `/make_{join,leave,knock}` requests include the `signatures` and `hashes` keys, these will become invalid once the joining/leaving/knocking server modifies the event (before calling `/send_{join,leave,knock}`).
In order to avoid invalid signatures being added to events, we should not return them. This seems to match the [concept of templated events in the spec](https://matrix.org/docs/spec/server_server/latest#get-matrix-federation-v1-make-join-roomid-userid), although the examples show a much smaller subset of returned fields.
I originally tried to have the `EventBuilder` know about whether the event is a "full" event or not, but then you cannot properly instantiate an `EventBase` object. It seemed simpler to strip out the unnecessary fields at the end, …
> Do not include signatures/hashes in make_{join,leave,knock} responses.

- changelog.d/10418.misc
- synapse/module_api/__init__.py
I thought this change would be a lot bigger, related to #8351, the last of com2ann conversions, this one is simply;
```
python3.8 -m com2ann -v 6 ./
```
---
> One last inline type hint (for the whole repo)

- changelog.d/10348.misc
- synapse/app/generic_worker.py
- synapse/app/homeserver.py
- synapse/config/appservice.py
- synapse/config/tls.py
- synapse/handlers/cas.py
- synapse/handlers/federation.py
- synapse/handlers/identity.py
- synapse/handlers/oidc.py
- synapse/handlers/register.py
- synapse/handlers/saml.py
- synapse/handlers/sync.py
- synapse/http/proxyagent.py
- synapse/http/site.py
- synapse/logging/opentracing.py
- synapse/metrics/_exposition.py
- synapse/metrics/background_process_metrics.py
- synapse/rest/client/v1/login.py
- synapse/rest/media/v1/__init__.py
- synapse/storage/database.py
- synapse/storage/databases/main/deviceinbox.py
- synapse/storage/databases/main/group_server.py
- synapse/storage/databases/main/roommember.py
- synapse/storage/prepare_database.py
- synapse/types.py
- synapse/util/caches/lrucache.py
- synapse/util/caches/treecache.py
- synapse/util/daemonize.py
- synapse/visibility.py
This PR is tantamount to running 
```
pyupgrade --py36-plus --keep-percent-format `find synapse/ -type f -name "*.py"`
```
Part of #9744
---
> [pyupgrade] `synapse/`

- changelog.d/10332.feature
- synapse/app/phone_stats_home.py
- synapse/storage/databases/main/metrics.py
- tests/app/test_phone_stats_home.py
- tests/rest/client/v1/utils.py
- tests/unittest.py
The old R30 metric can be tricked into thinking a user is 'retained' if, any point after 30 days of registration, they return even for just one 'day'. That said, a user which has been inactive for (e.g.) 6 months and opens up (e.g.) Element briefly (e.g. to check a new feature they heard about) can hardly be called 'retained'.
R30v2 instead counts users which have had at least 2 active days in the past 60 days, and where the earliest of these is at least 30 days earlier than the last. This more closely matches a sensible definition of 30-day retention.
This PR adds the R30v2 metric, some tests which characterise it, and plugs it into the phone-home statistics (which will be received by Panopticon).
> Add a new version of the R30 phone-home metric, which removes a false impression of retention given by the old R30 metric

- changelog.d/10427.feature
- changelog.d/10427.misc
- synapse/app/phone_stats_home.py
Rich seemed quite sad that this hadn't been done in the comments for #10332
> In phone_stats_home: Factorise `get_datastore` calls

- changelog.d/10414.bugfix
- synapse/handlers/room_list.py
I missed one in https://github.com/matrix-org/synapse/pull/10400
> Fix exception when failing to get remote room list

- changelog.d/10432.misc
- synapse/api/constants.py
- synapse/rest/client/v1/room.py
Switch to chunk events so we can auth via `power_levels` in https://github.com/matrix-org/synapse/pull/10245
Previously, we were using `content.chunk_id` to connect one
chunk to another. But these events can be from any `sender`
and we can't tell who should be able to send historical events.
We know we only want the application service to do it but these
events have the sender of a real historical message, not the
application service user ID as the sender. Other federated homeservers
also have no indicator which senders are an application service on
the originating homeserver.
So we want to auth all of the MSC2716 events (like `insertion`, `chunk`, `marker`) via `power_levels`
and have them be sent by the application service with proper
PL levels in the room.
Before | After
--- | --- …
> Switch to `chunk` events so we can auth via power_levels (MSC2716)

- changelog.d/10438.misc
- synapse/http/servlet.py
- synapse/rest/admin/users.py
- synapse/rest/client/v1/room.py
- synapse/rest/client/v2_alpha/keys.py
- synapse/rest/client/v2_alpha/relations.py
- synapse/rest/client/v2_alpha/sync.py
- synapse/rest/consent/consent_resource.py
- synapse/rest/media/v1/preview_url_resource.py
- synapse/storage/databases/main/__init__.py
- synapse/storage/databases/main/room.py
- synapse/storage/databases/main/stats.py
- synapse/streams/config.py
Related to #10437, this adds a return type to `parse_string` which had a lot of fallout of mypy being able to tell types of particular variables.
> Add a return type to parse_string.

- changelog.d/10426.feature
- synapse/config/emailconfig.py
- synapse/push/mailer.py
I debated about re-using `invite_from_person_to_room`, but passing in whether it was a room or a space, but that seemed less flexible.
> Update the notification email subject when invited to a space.

- .github/workflows/tests.yml
- changelog.d/10444.misc
Set the build to failed if any of the other jobs haven't succeeded. (previously it would be 'skipped' if they failed, which was apparently enough to make github's auto-merge happy.)
> Fix tests-done github actions status

- .github/workflows/release-artifacts.yml
- .github/workflows/tests.yml
- changelog.d/10451.misc
The idea here is that we only need the most recent `tests` or `release artifacts` workflow for each branch, and all the rest are just sucking up GHA worker time redundantly, so we may as well cancel them.
(docs at https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency)
> Cancel redundant GHA workflows

- changelog.d/10446.misc
- synapse/http/federation/matrix_federation_agent.py
- synapse/logging/context.py
- synapse/module_api/__init__.py
Two things here:
* In Twisted 21.7, `defer.ensureDeferred` is defined to take a `typing.Coroutine`. That is semantically identical to `types.CoroutineType`, so let's switch to keep mypy happy.
* Some of the annotations on our inlineGenerators functions weren't strictly correct, which again upsets Twisted 21.7.
> Fix a handful of type annotations.

- changelog.d/10442.misc
- synapse/storage/database.py
- synapse/storage/databases/main/devices.py
- synapse/storage/databases/main/monthly_active_users.py
- synapse/storage/databases/main/transactions.py
- synapse/storage/databases/main/user_directory.py
Now that we have `simple_upsert` that should be used in preference to
trying to insert and looking for an exception. The main benefit is that
we ERROR message don't get written to postgres logs.
We also have tidy up the return value on `simple_upsert`, rather than having a tri-state of inserted/not-inserted/unknown.
> Replace `or_ignore` in `simple_insert` with `simple_upsert`

- changelog.d/10448.feature
- docs/admin_api/user_admin_api.md
- synapse/rest/admin/users.py
- synapse/storage/databases/main/__init__.py
- synapse/storage/databases/main/stats.py
- tests/rest/admin/test_user.py
> Add `creation_ts` to list users admin API

- changelog.d/10463.misc
- scripts-dev/complement.sh
As discovered by @clokep, https://matrix.to/#/!oBWlVutBAdQYcYUsAc:sw1v.org/$Vc2b1LoiAiJlZjJflzsbb6-BnfLVIn0OoXlhj0qtDdY?via=jki.re&via=matrix.org&via=vector.modular.im
Disable msc2716 tests until both the Complement and Synapse PRs are merged.
Currently https://github.com/matrix-org/synapse/pull/10432 is merged but updates from https://github.com/matrix-org/complement/pull/168 is needed to make the tests pass with the new updates. Unfortunately, we would run into this situation if either side was merged first too.
- End with …
> Disable msc2716 until Complement update is merged

- .github/workflows/release-artifacts.yml
- changelog.d/10431.misc
- scripts-dev/build_debian_packages
This reduced the time spent building the packages from about 13 minutes to about 10 minutes (most of the rest is spent running the unit tests).
I'm not entirely sure this is the best approach. The images that we use to build the packages are pretty static, so another option would be just to build them once and host them on dockerhub or a private docker repository. Thoughts or comments welcome.
~~Based on #10429~~.
> Enable docker image caching for the deb build

- changelog.d/10482.misc
- synapse/state/__init__.py
- synapse/storage/databases/state/store.py
- synapse/storage/state.py
In particular this adds the `hs: "HomeServer"` types which cause a lot of the other type hints to work (since mypy now knows what all the other types are...)
Spun out of #10254
> Add type hints to state handler.

- changelog.d/10465.misc
- scripts-dev/release.py
We used to only do debs for full releases, but we're now doing them for RCs too, so we need to update the changelog.
> Change release script to update debian changelog for RCs

- changelog.d/10468.misc
- synapse/rest/media/v1/download_resource.py
IE11 doesn't support Content-Security-Policy but it has support for
a non-standard X-Content-Security-Policy header, which only supports the
sandbox directive. This prevents script execution, so it at least offers
some protection against media repo-based attacks.
Signed-off-by: Denis Kasak <dkasak@termina.org.uk>
> Mitigate media repo XSSs on IE11.

- .github/workflows/tests.yml
- changelog.d/10488.misc
- scripts-dev/complement.sh
CC @anoadragon453 
This is to match matrix-org/complement#171.
> Use the new test running syntax for complement.

- changelog.d/10485.bugfix
- synapse/api/constants.py
- synapse/handlers/sync.py
- synapse/storage/databases/main/end_to_end_keys.py
- tests/handlers/test_e2e_keys.py
Fixes https://github.com/matrix-org/synapse/issues/10484.
As far as I can tell from [the spec](https://spec.matrix.org/unstable/client-server-api/#device-keys), `signed_curve25519` is the only key algorithm employed for one-time keys at the moment. Thus this PR will by default return `{"signed_curve25519": 0}` for key counts. Only if there are any keys available will this count be something other than 0.
This affects both [`/sync` responses](https://matrix.org/docs/spec/client_server/r0.6.1#get-matrix-client-r0-sync), as well as the response to [`POST /_matrix/client/r0/keys/upload`](https://matrix.org/docs/spec/client_server/r0.6.1#post-matrix-client-r0-keys-upload) requests.
This isn't a complete solution to the problem (hence the included TODO) as we now over-communicates to the client …
> Always communicate device OTK counts to clients

- changelog.d/10486.bugfix
- synapse/app/phone_stats_home.py
Signed-off-by: Olivier Wilkinson (reivilibre) <olivier@librepush.net>
> Fix typo that causes R30v2 to actually be old R30

- changelog.d/10477.bugfix
- synapse/handlers/_base.py
Not sure from when, but trying to import the default configured SAML mapping provider crashes with circular imports.
Removed the imports `synapse.state` and `synapse.storage` which were caising the circular, and seem to have only been used for type hints, which were removed in https://github.com/matrix-org/synapse/commit/98aec1cc9da2bd6b8e34ffb282c85abf9b8b42ca
> Fix saml.DefaultSamlMappingProvider import

- changelog.d/10455.bugfix
- synapse/storage/databases/main/event_federation.py
If the staging area was empty we'd report an age of 51 years, which is
not true or helpful.
> Fix `oldest_pdu_in_federation_staging`

- CONTRIBUTING.md
- changelog.d/10483.doc
Document Complement dev usage
Also includes info on how to access the database for the homeserver after running Complement. Originally proposed in https://github.com/matrix-org/complement/pull/165
> Document Complement dev usage

- changelog.d/10489.feature
- synapse/events/utils.py
- tests/events/test_utils.py
Per [MSC3083](https://github.com/matrix-org/matrix-doc/pull/3083) and matrix-org/matrix-doc#3299.
> Restricted rooms (MSC3083) should not have their allow key redacted.

- changelog.d/10450.misc
- synapse/util/caches/cached_call.py
tighten up some of the typing in CachedCall, which is going to be needed when
Twisted 21.7 brings better typing on Deferred.
> improve typing annotations in CachedCall

- changelog.d/10490.misc
- synapse/http/client.py
- synapse/replication/tcp/client.py
- synapse/util/async_helpers.py
- synapse/util/caches/deferred_cache.py
- synapse/util/caches/descriptors.py
Mostly this involves decorating a few `Deferred` declarations with extra type hints. We wrap the types in quotes to avoid runtime errors when running against older versions of Twisted that don't have generics on `Deferred`.
> Fix up type hints for Twisted 21.7

- changelog.d/10491.misc
- synapse/notifier.py
- synapse/storage/persist_events.py
- synapse/util/async_helpers.py
Now that `Deferred` is a generic class, let's update `ObservableDeferred` to follow suit.
Based on #10490.
> Generics for `ObservableDeferred`

- changelog.d/10447.feature
- synapse/federation/federation_client.py
Based on the error handling in [MSC3083](https://github.com/matrix-org/matrix-doc/pull/3083).
~~Based on #10254.~~
This improves the failover logic for `/make_join` and `/send_join` such that errors of type `M_UNABLE_TO_AUTHORISE_JOIN` and `M_UNABLE_TO_GRANT_JOIN` cause trying another server instead of erroring back to the client.
See complement tests: matrix-org/complement#172.
> Improve failover logic for MSC3083 restricted rooms

- changelog.d/10415.misc
- synapse/_scripts/review_recent_signups.py
- synapse/app/admin_cmd.py
- synapse/app/appservice.py
- synapse/app/client_reader.py
- synapse/app/event_creator.py
- synapse/app/federation_reader.py
- synapse/app/federation_sender.py
- synapse/app/frontend_proxy.py
- synapse/app/generic_worker.py
- synapse/app/homeserver.py
- synapse/app/media_repository.py
- synapse/app/pusher.py
- synapse/app/synchrotron.py
- synapse/app/user_dir.py
- synapse/push/pusherpool.py
- synapse/util/versionstring.py
*This exists because rpmlint complained while packaging Synapse for Fedora.*
This PR removes the shebang lines from all files belonging to Python modules.
Afaict this does not remove functionality:
- For the files under `_script` the shebang can be removed as they are wrapped by a *real* script (with shebang).
- The files under `app` are actually meant to be called directly, but should not occur as cli tools. Without a shebang, they can still be called by their module name, e.g. `python3 -m synapse.app.homeserver`.
Tangential Suggestion: After reading into Python and scripts, using `entry_point` in `setup.py` would make those wrappers scripts unnecessary.
- Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." …
> Don’t have Scripts in Modules

- changelog.d/10500.misc
- docker/build_debian.sh
if we end up doing a 1.39.1, we'll want to make sure this lands on the release branch first.
> Fix deb build script to set prerelease flag correctly

- changelog.d/10440.feature
- docs/sample_config.yaml
- synapse/config/database.py
- synapse/storage/database.py
- tests/storage/test_txn_limit.py
- tests/utils.py
Setting the value will help PostgreSQL free up memory by recycling the connections in the connection pool.
I would not set a default value for now but allow testing this as an experimental feature.
Possibly fixes #9182
> Allow setting transaction limit for db connections

- changelog.d/10390.misc
- synapse/federation/federation_server.py
- synapse/storage/databases/main/event_federation.py
- tests/storage/test_event_federation.py
> Prune inbound federation queues if they get too long

- .github/workflows/tests.yml
- changelog.d/10512.misc
Try forcing a fail by setting the exit code
> Fix the `tests-done` github actions step, again

- changelog.d/10496.misc
- scripts-dev/release.py
- setup.py
This splits the release script into three subcommands:
```
./scripts-dev/release.py prepare
./scripts-dev/release.py tag
./scripts-dev/release.py publish
```
Reviewable commit by commit.
> Extend the release script to tag and create the releases.

- changelog.d/10515.feature
- docs/sample_log_config.yaml
- synapse/config/logger.py
(It doesn't exit if the process fails, causing the process to be kept alive.)
> Revert use of PeriodicallyFlushingMemoryHandler by default

- changelog.d/10517.bugfix
- synapse/logging/handlers.py
not tested (not immediately sure how to -- `synctl stop` used to already work)
> Fix PeriodicallyFlushingMemoryHandler inhibiting application shutdown

- changelog.d/10507.misc
- synapse/handlers/receipts.py
- synapse/handlers/typing.py
> Include room ID in ignored EDU log messages

- changelog.d/10513.feature
- docs/sample_config.yaml
- synapse/config/cache.py
- synapse/handlers/sync.py
> Make sync response cache time configurable.

- changelog.d/10504.misc
- synapse/storage/databases/main/end_to_end_keys.py
> Fix `could not serialize access` errors for `claim_e2e_one_time_keys`

- changelog.d/10119.misc
- synapse/events/__init__.py
- synapse/storage/databases/main/events_worker.py
- synapse/storage/databases/main/roommember.py
- tests/storage/databases/main/test_events_worker.py
This PR mainly does two things:
1. Ensure we only load an event from the DB once when the same event is requested multiple times at once.
2. Ensure that there is only one copy of any given event in memory at a time by using weak references.
> Improve event caching code

- changelog.d/10531.bugfix
- synapse/rest/client/v2_alpha/receipts.py
- tests/rest/client/v2_alpha/test_sync.py
Fixes a bug introduced in rc1 that would cause Synapse to 400 on read receipts requests with empty bodies.
Broken in https://github.com/matrix-org/synapse/pull/10413
> Don't fail on empty bodies when sending out read receipts

- .github/workflows/tests.yml
- changelog.d/10529.misc
We don't always run all jobs, e.g. we only run the newsfile lint on PRs,
which means that currently CI always fails on the develop branch.
> Don't fail CI when a job was skipped

- changelog.d/10443.doc
- docs/SUMMARY.md
- docs/setup/forward_proxy.md
Add some documentation.
This is for merging after #10411
> Add documentation for forward proxy

- CHANGES.md
- changelog.d/10532.bugfix
- synapse/handlers/appservice.py
- tests/handlers/test_appservice.py
Fixes #9694 
If there is no information to serve for a given protocol, we should prefer to omit that protocol rather than returning an empty object. The spec https://matrix.org/docs/spec/client_server/r0.6.0#get-matrix-client-r0-thirdparty-protocols mandates that protocols must contain at least a few fields to be valid.
> Check that an appservice protocol has at least one service providing it

- changelog.d/10527.misc
- synapse/federation/federation_client.py
- synapse/handlers/space_summary.py
- tests/handlers/test_space_summary.py
This is prep work related to #10495. I want to be able to use some of the same data structures, but the eventual format of the data returned is a bit different. Grouping the room + the children rooms together into the same data structure allows for this a bit more easily.
This also switches to using auto-attribs while I'm here.
> Prep work for the updated spaces summary

- changelog.d/10537.misc
- synapse/rest/client/v1/room.py
Mark all MSC2716 events as historical
Part of MSC2716: https://github.com/matrix-org/matrix-doc/pull/2716
> Mark all MSC2716 events as historical

- changelog.d/10546.feature
- docs/sample_config.yaml
- synapse/config/emailconfig.py
- synapse/handlers/send_email.py
- synapse/server.py
- tests/push/test_email.py
- tests/rest/client/v2_alpha/test_account.py
- tests/rest/client/v2_alpha/test_register.py
This is mostly useful in case the server offers TLS, but doesn't present a valid certificate.
Fixes #8046.
> Add a setting to disable TLS for sending email

- changelog.d/10530.misc
- synapse/handlers/space_summary.py
This has two discrete, but related changes:
* Sends both the `allowed_room_ids` and `allowed_spaces` keys from [MSC2946](https://github.com/matrix-org/matrix-doc/pull/2946) (we send both for backwards compatibility, but prefer `allowed_room_ids` if it exists).
* Only includes this field if we're generating a response for federation, this allows skipping some unnecessary database access.
This relates to both #10495 and  #10523.
~~Builds on #10527.~~
> Update the API response for spaces summary over federation

- changelog.d/10539.misc
- synapse/handlers/federation.py
- tests/test_federation.py
This is part of my work trying to sort out #9595. As a first step, this should be an (almost) non-functional change to try to make these code paths a little more understandable.
Reviewable commit by commit.
> Clean up federation event auth code

- changelog.d/10541.bugfix
- synapse/federation/federation_client.py
- synapse/handlers/room_list.py
- synapse/rest/client/v1/room.py
- tests/rest/client/v1/test_rooms.py
Fixes exceptions:
```
TimeoutError: User timeout caused connection failure.
File "synapse/http/matrixfederationclient.py", line 575, in _send_request
response = await request_deferred
File "twisted/internet/defer.py", line 1658, in _inlineCallbacks
cast(Failure, result).throwExceptionIntoGenerator, gen
File "twisted/python/failure.py", line 500, in throwExceptionIntoGenerator
return g.throw(self.type, self.value, self.tb)
File "synapse/http/federation/matrix_federation_agent.py", line 190, in request
self._agent.request(method, uri, request_headers, bodyProducer)
File "twisted/internet/defer.py", line 1658, in _inlineCallbacks
cast(Failure, result).throwExceptionIntoGenerator, gen
File "twisted/python/failure.py", line 500, in throwExceptionIntoGenerator
return g.throw(self.type, …
```
> Fix exceptions in logs when failing to get remote room list

- changelog.d/10449.bugfix
- changelog.d/10449.feature
- synapse/api/constants.py
- synapse/api/room_versions.py
- synapse/event_auth.py
- synapse/handlers/event_auth.py
- tests/events/test_utils.py
- tests/handlers/test_space_summary.py
- tests/test_event_auth.py
This adds support for [MSC3289](https://github.com/matrix-org/matrix-doc/pull/3289): room version 8. This is room version 7 + [MSC3083](https://github.com/matrix-org/matrix-doc/pull/3083).
~~Based on #10447. (Hence the draft.)~~
This should not be merged until MSC3289 is merged.
Also see matrix-org/sytest#1100 and matrix-org/complement#181.
> Support MSC3289: Room version 8

- changelog.d/10551.doc
- docs/reverse_proxy.md
Move the Synapse reverse proxy homeserver configuration documentation above the reverse proxy examples to highlight the importance of configuring the homeserver to be aware that it is being intentionally reverse proxied.
Documentation update recommended in #10492 
Signed-off-by: Drew Short <warrick@sothr.com>
> Moved homeserver documentation above reverse proxy examples

- changelog.d/10560.feature
- synapse/handlers/space_summary.py
- tests/handlers/test_space_summary.py
I split this out from the (upcoming) federation PR since it is a refactoring + unrelated bugfix.
* It is moved from inline to a separate method since it will be re-used with the updates to the spaces summary API (#10495).
* It fixes an edge-case when a room you're invited to is directly returned over federation.
> Fix an edge-case for being invited to a room for the spaces summary.

- changelog.d/10572.misc
- synapse/handlers/event_auth.py
This clarifies the error message when you attempt to join a restricted room (from MSC3083) that you do not have permission to join. It now mentions both "rooms" and "spaces".
Note that this is shown to users:
> Clarify error message when joining a restricted room.

- changelog.d/10574.feature
- synapse/handlers/space_summary.py
Part of step 4 of #10495.
This expires spaces summary pagination sessions after a period of time. This arbitrarily uses 5 minutes -- if a client hasn't come back to keep paginating after that I think we can safely get rid of the session.
There might be more clever things to do here (reusing sessions and such), but I think we at least want to ensure this doesn't grow forever before releasing.
> Expire old spaces summary pagination sessions.

- changelog.d/10580.bugfix
- synapse/handlers/space_summary.py
- tests/handlers/test_space_summary.py
I'm pretty sure that we should be allowing viewing of a `public` room when requested over the spaces summary. The MSC states:
> An HTTP response with a status code of 403 and an error code of `M_FORBIDDEN` should be returned if the user doesn't have permission to view/peek the root room. This should also be returned if that room does not exist, which matches the behavior of other room endpoints
This description essentially matches what MSC3173 says (stripped state is viewable by any potential joiner). The current checks ensure the user is in the room or it is world-readable, which does not take into account cases such as:
* A public room
* An invite-only room where the user is invited
CC @t3chguy
> Allow public spaces to be returned via the summary APIs.

- changelog.d/10579.feature
- synapse/handlers/space_summary.py
- tests/handlers/test_space_summary.py
And the conversation in matrix-org/matrix-doc#1898.
See matrix-org/complement#193 for updated tests.
Somewhat related to #10495.
> Update the pagination parameter name based on MSC2946 review.

- changelog.d/10592.bugfix
- synapse/federation/federation_server.py
(I'm not 100% sure the title is correct.)
This attempts to fix https://sentry.matrix.org/sentry/synapse-matrixorg/issues/225383/ by properly handling the return value from `get_next_staged_event_id_for_room`, but I'm not 100% sure it is doing the right thing. :)
> Handle the staged events queue being empty.

- changelog.d/10606.bugfix
- synapse/handlers/receipts.py
- tests/handlers/test_receipts.py
Fixes https://github.com/matrix-org/synapse/issues/10603
> Handle string read receipt data

- changelog.d/10569.feature
- synapse/federation/federation_client.py
- synapse/federation/transport/client.py
- synapse/federation/transport/server.py
- synapse/handlers/space_summary.py
- tests/handlers/test_space_summary.py
Adds federation APIs (and calls out to them) for the updated spaces summary API.
This should be reviewable commit-by-commit. Sorry for the size of it!
Step 3 in #10495.
~~Builds on #10549 and #10560.~~
See complement tests: matrix-org/complement#190.
> Support federation in the new spaces summary API (MSC2946)

- changelog.d/10591.misc
- synapse/events/__init__.py
- synapse/federation/federation_server.py
- synapse/handlers/federation.py
Various minor improvements to the logs. Should be reviewable commit-by-commit.
> Clean up some logging in the federation event handler

- changelog.d/10611.bugfix
- synapse/federation/transport/server/federation.py
- synapse/rest/client/v1/room.py
Fixes #10610 by adding validation. I don't think a `-1` is valid here so we just reject it up front instead of trying to handle it.
> Validate the max_rooms_per_space parameter to ensure it is non-negative

- changelog.d/10602.feature
- docs/manhole.md
- synapse/util/manhole.py
tested on a test homeserver:
```python
>>> async def hi(): 
...     return 4 
...  
>>> hi() 
<Deferred at 0x7f8023392bb0 current result: 4> 
>>> hs.get_datastore().get_event('$1416420717069yeQaw:matrix.org') 
<Deferred #0> 
Deferred #0 failed: '404: Could not find event $1416420717069yeQaw:matrix.org' 
>>> hs.get_datastore().get_users() 
<Deferred #1> 
Deferred #1 called back: []
```
> Manhole: wrap coroutines in `defer.ensureDeferred` automatically

- changelog.d/10598.feature
- docs/admin_api/user_admin_api.md
- synapse/rest/admin/users.py
- synapse/storage/databases/main/registration.py
- tests/rest/admin/test_user.py
Follow up: #10261
Fixes: #10251
> Allow to edit `external_ids` by Edit User admin API

- changelog.d/10623.bugfix
- synapse/rest/client/v2_alpha/sync.py
Fixes https://github.com/matrix-org/synapse/issues/10618
https://github.com/matrix-org/synapse/pull/9919 removed optional keys from `/sync`, though it was missed that `org.matrix.msc2732.device_unused_fallback_key_types` should always be included down `/sync` in accordance with [MSC2732](https://github.com/matrix-org/matrix-doc/blob/54255851f642f84a4f1aaf7bc063eebe3d76752b/proposals/2732-olm-fallback-keys.md).
This PR reintroduces the behaviour of always including the key.
> Always list fallback key types in /sync

- changelog.d/10518.feature
- docker/conf/log.config
- docs/sample_log_config.yaml
- synapse/config/logger.py
> Make `PeriodicallyFlushingMemoryHandler` (buffered logging handler which periodically flushes itself) the default logging handler.

- changelog.d/10614.misc
- synapse/handlers/federation.py
Marking things as outliers to inhibit pushes is a sledgehammer to crack a
nut. Move the test further down the stack so that we just inhibit the thing we
want.
> Stop setting the outlier flag for things that aren't

- changelog.d/10583.feature
- synapse/federation/federation_client.py
Adds a backwards compatibility path to the room hierarchy federation endpoint by using the `/spaces` endpoint and translating the results (and throwing some of it away).
The reasoning for wanting this is that the new `/hierarchy` federation endpoint will not be available on all servers initially, but we want the C-S endpoint to work as expected. This should allow clients to adopt the new endpoint quickly.
~~Builds on #10569.~~
Part of #10495.
I did some manual testing of this, but I'm not really sure how to make automated tests for this (as I had to manually run two different versions of Synapse, one which knew of the `/hierarchy` endpoint and one which did not).
> Query legacy spaces federation API if the hierarchy API is unavailable.

- changelog.d/10564.feature
- docs/workers.md
- synapse/rest/client/room.py
- synapse/storage/databases/main/room.py
Fixes https://github.com/matrix-org/synapse/issues/7867
As stated in the issue, `/createRoom` could only be run on the main process due to the `public_room_list_stream` only being writable by the main process. It turns out however that this stream was unused - meaning that we could simply rip it out. This unblocked moving `/createRoom` off the main process :tada: It potentially also unblocks moving the Delete Room Admin API - but that's the subject of another PR.
**This PR is based on https://github.com/matrix-org/synapse/pull/10565**, which removes `public_room_list_stream` (just reading/writing to the table - not the table itself, for now). This PR does the job of mounting the endpoint to workers and moving the database method `store_room` to the `RoomWorkerStore`.
> Allow /createRoom to be run on workers

- changelog.d/10638.feature
- synapse/module_api/__init__.py
By default the calls only ran on the worker configured to run background tasks.
Fixes #10635
> Allow modules to run looping call on all instances

- changelog.d/10630.misc
- synapse/handlers/sync.py
Converts the `attrs` classes used by the `SyncHandler` to use `auto_attribs`.
> Use auto-attribs for attrs classes for sync.

- changelog.d/10615.misc
- synapse/handlers/federation.py
This should be a completely non-functional refactor. I've constructed it as a series of tiny commits, to help show the logic behind it.
~~Based on #10614~~
> Refactor `on_receive_pdu` code

- changelog.d/10629.misc
- synapse/handlers/initial_sync.py
- synapse/handlers/sync.py
- synapse/storage/databases/main/roommember.py
- synapse/storage/databases/main/user_directory.py
- synapse/storage/roommember.py
- tests/replication/slave/storage/test_events.py
This converts the `namedtuples` to `attrs` classes for the storage classes used by the `RoomMemberStore`.
Each is converted as a separate commit.
The reasoning for this is:
* Better type hints
* Will be expanding one of these in the future
> Convert room members storage tuples to attrs.

- changelog.d/10627.misc
- docs/admin_api/user_admin_api.md
- synapse/rest/admin/users.py
- synapse/storage/databases/main/registration.py
- tests/rest/admin/test_user.py
Follow up: #10598 - https://github.com/matrix-org/synapse/pull/10598#discussion_r688582506
Update only changed threepids and not all.
Add type hints, update test.
> Remove not needed database updates in modify user admin API

- CHANGES.md
Ubuntu 20.10 was not an LTS release
Signed-off-by: John-Scott Atlakson <24574+jsma@users.noreply.github.com>
> Fix typo in release notes

- changelog.d/10644.bugfix
- mypy.ini
- synapse/handlers/sync.py
- synapse/storage/databases/main/roommember.py
- synapse/storage/roommember.py
- tests/handlers/test_sync.py
- tests/replication/slave/storage/test_events.py
This simply leaves the rooms out of the `/sync` response. The user needs to clear cache & reload (for Element Web at least) in order to get rid of the rooms locally.
I debated about trying to fake a leave or something, but that seemed more complicated than worth it.
Note that for incremental syncs the room is already ignored (since the events cannot be created due to having unknown room versions). The fix is really just for full syncs where the room is now completely ignored.
I tested this manually with the following:
1. Created three version 8 rooms with alice.
2. Joined one room with bob.
3. Invited bob to one room from alice.
4. Updated the join rules of the last room to `knock` as alice, then had bob knock on the room.
5. Shutdown the server
6. Comment out `RoomVersions.V8` from …
> Do not include rooms with an unknown room version in a sync response.

- changelog.d/10624.misc
- synapse/handlers/federation.py
This is a follow-up to #10615: it takes the code that constructs the state at a backwards extremity, and extracts it to a separate method.
Again, it's structured as a series of small commits, which may or may not help the reader.
~~Based on #10615~~
> Extract `_resolve_state_at_missing_prevs`

- changelog.d/10640.misc
- synapse/federation/federation_server.py
- synapse/handlers/federation.py
- tests/test_federation.py
Here we split `on_receive_pdu` into two functions (`on_receive_pdu` and `process_pulled_event`), rather than having both cases in the same method. There's a tiny bit of overlap, but not that much.
Based on #10624.
> Split `on_receive_pdu` in half

- changelog.d/10664.misc
- tests/rest/admin/test_device.py
> Simplify tests for device admin rest API

- .ci/patch_for_twisted_trunk.sh
- .ci/twisted_trunk_build_failed_issue_template.md
- .github/workflows/twisted_trunk.yml
- changelog.d/10651.misc
This creates a GHA workflow which runs at 8am every day, and runs `mypy`, `trial` and `sytest` against Twisted's current trunk. If any of the jobs fail, it opens an issue.
See https://github.com/matrix-org/synapse/actions/runs/1144688011 for an example of a successful run, and https://github.com/matrix-org/synapse/issues/10650 for what happens when the build fails.
Fixes: #10340.
> Run a nightly CI build against Twisted trunk.

- changelog.d/10662.misc
- synapse/federation/federation_client.py
This catches more "known" exceptions (generally network exceptions) and doesn't print out the entire stack trace when using `_try_destination_list`.
Fixes #10026
> Do not include stack traces for known exceptions when trying multiple federation destinations.

- changelog.d/10665.misc
- synapse/rest/client/account_validity.py
- synapse/rest/client/capabilities.py
- synapse/rest/client/directory.py
- synapse/rest/client/pusher.py
- synapse/rest/client/read_marker.py
- synapse/rest/client/room_upgrade_rest_servlet.py
- synapse/rest/client/shared_rooms.py
- synapse/rest/client/tags.py
- synapse/rest/client/thirdparty.py
- synapse/rest/client/tokenrefresh.py
- synapse/rest/client/user_directory.py
- synapse/rest/client/versions.py
- synapse/rest/client/voip.py
This adds some missing type hints to our REST servlets and fixes any mypy issues found. I don't think any of these were bugs, although there were a coulpe of variable re-use changes.
Should be reviewable commit-by-commit, most of the changes are fairly mechanical.
> Add type hints to REST servlets.

- changelog.d/10666.misc
- synapse/handlers/sync.py
- synapse/rest/client/sync.py
This adds some missing type hints to the sync REST servlets, which somewhat cascaded into wrong type hints in the sync handler.
There shouldn't be any behavior changes, but there are some additional assertions that could throw.
> Add type hints to sync REST servlet.

- .github/workflows/twisted_trunk.yml
- changelog.d/10672.misc
Setting `update_existing: true` in the `create-an-issue` GitHub Action
will avoid opening duplicate issues if an open issue already exists with
an identical title.
If no open issues match the title, then a new issue will be created.
This helps avoid spamming our issue tracker should there be a failure
when testing against Twisted's trunk.
This PR also pins the SHA of the `create-an-issue` action to mitigate
the risk of a malicious actor gaining access to JasonEtco's account.
See GitHub's page on security hardening third party actions for more:
https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions
- Be a short description of your change which makes sense to users. "Fixed a bug …
> Avoid duplicate issues from Twisted trunk failures

- changelog.d/10639.doc
- docs/openid.md
Having them as links broke the table-of-contents rendering in mdbook:
Plus there's not really much reason for only some of the provider titles to be links.
> Fix the titles in the OIDC documentation

- changelog.d/10654.bugfix
- synapse/handlers/room_member.py
Apply limit to per-room display names when setting them
Fixes issue #9236
> Apply limit to per-room display names when setting them

- changelog.d/10192.doc
- docs/openid.md
This PR adds an entry to the examples of OpenID providers.
It's possible to use synapse with users coming from a django's database using this module : https://github.com/jazzband/django-oauth-toolkit
I've tested it and it worked well but I've come across some issues with the configuration so I wanted to help future people wanting to do the same thing.
This is my first PR on the repo so please tell me if I'm missing something
> doc: add django-oauth-toolkit to oidc doc

- changelog.d/10677.bugfix
- synapse/handlers/register.py
- synapse/handlers/sso.py
- synapse/rest/client/login.py
Fix a bug where the prometheus metrics for SSO logins wouldn't be initialised
until the first user logged in with a given auth provider.
> Correctly initialise the `synapse_user_logins` metric.

- changelog.d/10684.bugfix
- synapse/rest/media/v1/thumbnail_resource.py
- tests/rest/media/v1/test_media_storage.py
> Fix error when selecting between thumbnails with the same quality

- changelog.d/10686.misc
- scripts-dev/complement.sh
This fixes a bug in the changes to `complement.sh` from #10039 -- currently either the `matrixdotorg/synapse` Docker image is built *or* the `matrixdotorg/synapse-workers` image is built via `complement.sh`, it should be that the `matrixdotorg/synapse` image is *always* built and we either build complement directly on it, or first build `matrixdotorg/synapse-workers` on it and then complement on that.
Vaguely related to matrix-org/synapse#10065.
> Ensure the base image is rebuilt when running complement with workers.

- changelog.d/10723.bugfix
- tests/rest/client/v2_alpha/test_groups.py
These were broken in an incorrect merge of GHSA-jj53-8fmw-f2w2 (cb35df940a828bc40b96daed997b5ad4c7842fd3)
> Fix up unit tests

- changelog.d/10707.misc
- synapse/rest/client/account_data.py
- synapse/rest/client/groups.py
- synapse/rest/client/receipts.py
- synapse/rest/client/register.py
- synapse/rest/client/relations.py
- synapse/rest/client/room.py
Follow-up to #10665/#10674 with more modules.
~~Built-on #10706.~~
> Additional type hints for client REST servlets (part 3)

- changelog.d/10714.feature
- docs/sample_config.yaml
- synapse/config/homeserver.py
- synapse/config/oembed.py
- synapse/res/providers.json
- synapse/rest/media/v1/oembed.py
- synapse/rest/media/v1/preview_url_resource.py
- tests/rest/media/v1/test_url_preview.py
Implements the first step of #2752 by embedding the providers.json inside of the Synapse package and parsing it, instead of using a hard-coded list. This can also read other *.json files to include additional oEmbed URLs.
Currently this is a trimmed down list of `providers.json` to *only* include the same Twitter URLs we were using, since there are probably some performance concerns with matching against the entire potential list of globs and I wanted to get the infrastructure in here first.
A follow-up steps to this would be to add the full providers.json file (and probably have a better way of matching globs -> URL endpoints), as well as remaining work in #2752.
Closes #10536, partially overlaps with #10392.
Commits should separately reviewable. The first is simple refactoring -- it …
> Allow configuration of the oEmbed URLs.

- changelog.d/10734.bugfix
- synapse/storage/databases/main/pusher.py
- tests/push/test_email.py
Fixes https://github.com/matrix-org/synapse/issues/10729, see issue for context.
We were originally iterating over `txn`, which can work, but as `txn` was being used to run a
simple_delete operation inside the loop, it was actually being redefined mid-loop.
Thus, this caused the background job that was intended to remove old pushers that were
associated with an unlinked email address to fail if there were any to remove.We were originally iterating over 'txn', which can work, but as 'txn' was being used to run a
simple_delete operation inside the loop, it was actually being redefined mid-loop.
Thus, this caused the background job that was intended to remove old pushers that were
associated with an unlinked email address to fail if there were any to remove.
> Fix iteration in _remove_deleted_email_pushers background job.

- changelog.d/10697.misc
- synapse/api/constants.py
- synapse/handlers/federation.py
- synapse/storage/databases/main/room.py
- synapse/storage/schema/main/delta/63/02populate-rooms-creator.sql
- tests/storage/databases/main/test_room.py
Populate `rooms.creator` field for easy lookup
Part of https://github.com/matrix-org/synapse/pull/10566 for [MSC2716](https://github.com/matrix-org/matrix-doc/pull/2716)
- Fill in creator whenever we insert into the rooms table
- Add background update to backfill any missing creator values
```sh
$ psql synapse
Table "public.rooms"
Column        |  Type   | Collation | Nullable | Default | Storage  | Stats target | Description
----------------------+---------+-----------+----------+---------+----------+--------------+-------------
room_id              | text    |           | not null |         | extended |              |
is_public            | boolean |           |          |         | plain    |              |
creator              | text    |           |          |         | extended | …
```
> Populate `rooms.creator` field for easy lookup

- changelog.d/10728.misc
- synapse/rest/client/account.py
- synapse/rest/client/knock.py
- synapse/rest/client/register.py
- synapse/rest/client/report_event.py
- synapse/rest/client/room_batch.py
- synapse/rest/client/room_keys.py
- synapse/rest/client/sendtodevice.py
- synapse/rest/client/sync.py
Follow-up to #10665/#10674/#10707 with more modules.
I think this will need 1 more PR and then we can enforce type hints on definitions in `synapse.rest.client`.
> Additional type hints for client REST servlets (part 4)

- changelog.d/10727.misc
- synapse/handlers/room_summary.py
- tests/handlers/test_room_summary.py
Fixes #10724
This is the same strategy we used for `/sync` where we just ignore the room and do not return it.
> Ignore rooms with unknown room versions in the spaces summary.

- changelog.d/10743.bugfix
- synapse/storage/databases/main/events.py
I don't think its possible for this to happen unless there are multiple out of band memberships in the room that were persisted in an older version of Synapse that didn't do auth chains.
Fixes #10739
> Fix bug with reusing 'txn' when persisting event.

- changelog.d/10736.misc
- mypy.ini
- synapse/http/servlet.py
- synapse/rest/admin/server_notice_servlet.py
- synapse/rest/client/_base.py
- synapse/rest/client/groups.py
- synapse/rest/client/push_rule.py
- synapse/rest/client/transactions.py
Follow-up to #10665/#10674/#10707/#10728 to finish of `synapse.rest.client` and enforce that all method signatures need type hints.
This is mostly the same, except the initial PR converts a freeform dictionary to attrs. Some of this is also a bit more abstract (and touches the decorators). I didn't think we needed to go crazy with those type hints, but we can try to make them stricter if people like.
> Additional type hints for client REST servlets (part 5)

- changelog.d/10738.misc
- synapse/handlers/room.py
This was an error I noticed when discussing how hard it would be to add another preset.
We could check this closer to the C-S API, but it seems that this code gets called from quite a few places, so thought it best to put here. I can add (or replace) this error checking though if people feel I should put it in the REST code.
> Raise an error if an unknown preset is passed from a client.

- changelog.d/10754.misc
- synapse/storage/database.py
`execute_values` is a faster version of `execute_batch`.
> Use `execute_values` more in PostgreSQL

- changelog.d/10748.misc
- scripts/synapse_port_db
- synapse/storage/databases/main/presence.py
- synapse/storage/schema/main/delta/63/04add_presence_stream_not_offline_index.sql
Based off findings here: https://github.com/matrix-org/synapse/issues/7968#issuecomment-911625270
Partially addresses #7968
> Add a partial index to `presence_stream` to speed up startups

- changelog.d/10747.feature
- synapse/api/room_versions.py
- synapse/events/utils.py
- tests/events/test_utils.py
Per [MSC3375](https://github.com/matrix-org/matrix-doc/pull/3375).
This needs to wait for that the MSC to be merged.
> Support MSC3375: room version 9.

- changelog.d/10752.misc
- mypy.ini
- tests/handlers/test_room.py
- tests/handlers/test_user_directory.py
Don't see why they're in user_directory?
> Pull out encrypted_by_default tests

- changelog.d/10744.misc
- synapse/api/constants.py
- synapse/handlers/_base.py
- synapse/handlers/federation_event.py
- synapse/handlers/message.py
- synapse/handlers/room.py
- synapse/handlers/room_list.py
- synapse/handlers/room_member.py
- synapse/handlers/stats.py
This is part of my ongoing war against `BaseHandler`. I've moved `kick_guest_users` into `RoomMemberHandler` (since it calls out to that handler anyway), and split `maybe_kick_guest_users` into the two places it is called.
> Move `maybe_kick_guest_users` out of `BaseHandler`

- changelog.d/10750.misc
- synapse/event_auth.py
I recall having a difficult time searching through our GitHub org and Synapse's codebase directly in order to find the origin of an 'event_id too large' error message. I eventually found it here are asking around.
Then today someone else ran through the exact same failure mode, and I had to help them out.
This small commit should put an end to that needless cycle, and is a good lesson on making error messages easy to search for in a codebase.
> Ease searching for M_TOO_LARGE-related error codes

- changelog.d/10757.bugfix
- synapse/storage/databases/main/directory.py
Fixes https://github.com/matrix-org/synapse/issues/10716
[/createRoom](https://spec.matrix.org/unstable/client-server-api/#post_matrixclientr0createroom) recently gained support for being [run on worker processes](https://github.com/matrix-org/synapse/pull/10564). Unfortunately, it went unnoticed that passing the `room_alias_name` parameter to `/createRoom` fails on workers.
The reason for this not being caught beforehand was that the endpoint was never routed to workers in [sytest](https://github.com/matrix-org/sytest), thus the tests never raised a failure. Thus a PR for Sytest ~~will be coming along soon~~ is at https://github.com/matrix-org/sytest/pull/1128 which tests both this PR, and raises any other errors which may be lurking.
> Allow `room_alias_name` parameter to be handled by /createRoom calls on workers

- changelog.d/10768.misc
- synapse/config/account_validity.py
- synapse/config/emailconfig.py
- synapse/config/sso.py
The deprecation itself happened in https://github.com/matrix-org/synapse/pull/10596 which shipped with Synapse v1.41.0. However, it doesn't seem fair to suddenly drop support for these settings in ~4-6w without being more vocal about said deprecation.
> Add a warning when using deprecated template_dir settings

- changelog.d/10704.bugfix
- synapse/handlers/sync.py
Add logging to help debug #9424
> Add logging to help debug #9424

- changelog.d/10760.bugfix
- synapse/handlers/room_summary.py
The spaces summary / hierarchy endpoints should only return the stripped state events (+ `origin_server_ts`), not the entire event, for the children events of a room.
This is somewhat related to #10523 in that we'll be doing a decent chunk less work here.
> Return stripped state events for the room summary.

- changelog.d/10771.misc
- synapse/handlers/federation_event.py
If we're persisting an event `E` which has `auth_event`s `A1`, `A2`, then we ought to make sure that we correctly auth and persist `A1` and `A2`, before we blindly accept `E`.
This PR does *part* of that - it persists the auth events first - but it does not fully solve the problem, because we still don't check that the auth events weren't rejected.
It's a bit of a refactorathon, but it should be reviewable commit-by-commit.
> Persist auth events before the events that rely on them

- changelog.d/10773.misc
- synapse/handlers/federation_event.py
I think I have finally teased apart the codepaths which handle outliers, and those that handle non-outliers. Let's add some assertions to demonstrate my newfound knowledge.
> Add some assertions about outliers

- changelog.d/10762.bugfix
- synapse/handlers/deactivate_account.py
- tests/handlers/test_user_directory.py
Pulled this out of larger WIP changes because it's small and relatively isolated from the other changes.
The problem here is that `handle_local_profile_change` checks the DB to ensure the user isn't deactivated before upserting a directory entry.. So we need to reactivate them before calling this function, otherwise it'll do nothing.
> Fix reactivated users not being added to directory

- changelog.d/10779.misc
- synapse/http/site.py
This used to be a comma and got accidentally changed to a period in https://github.com/matrix-org/synapse/pull/9654, but a pipe character is more easier to parse visually
```
{@ems_administrator:one-staging.ems.host,@eotestingcheckboxtest:one-staging.ems.host}
```
vs
```
{@ems_administrator:one-staging.ems.host|@eotestingcheckboxtest:one-staging.ems.host}
```
> Change logging of puppeted requests to better differentiate users

- changelog.d/10775.misc
- synapse/api/constants.py
- synapse/event_auth.py
- synapse/handlers/register.py
- synapse/handlers/room.py
- synapse/handlers/room_list.py
- synapse/handlers/stats.py
- synapse/storage/databases/main/stats.py
Adds a constant for `m.federate` to `EventContentFields` and uses it through our code.
> Add a constant for m.federate.

- changelog.d/10780.misc
- synapse/storage/databases/main/events.py
- tests/storage/test_event_push_actions.py
Outlier events don't ever have push actions associated with them, so we
can skip some expensive queries during event persistence.
> Skip handling of push actions for outlier events

- changelog.d/10778.misc
- scripts-dev/docker_update_debian_changelog.sh
- scripts-dev/update_debian_changelog.sh
When releasing 1.42.0 with @Azrenbeth and talking with @clokep yesterday I realised doing the `dch` incantations related to releasing Synapse wasn't trivial, so I thought I'd write a script to run in a Debian container to make things a bit easier.
> Add a script to update the debian changelog for non-Debian systems

- changelog.d/10783.bugfix
- docker/configure_workers_and_start.py
With the trailing comma, the output is:
```
('worker_main_http_uri: http://127.0.0.1:8080',)
```
whereas we really want:
```
worker_main_http_uri: http://127.0.0.1:8080
```
This manifests itself as the upload key endpoint failing with:
```
File "/usr/local/lib/python3.8/site-packages/synapse/app/generic_worker.py", line 208, in on_POST
self.main_uri + request.uri.decode("ascii"), body, headers=headers
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```
> Fix frontend_proxy jinja script in docker workers

- changelog.d/10772.feature
- synapse/api/room_versions.py
Per the discussion in #10747, this flips clients from preferring room version 8 to room version 9 when creating restricted rooms.
We believe that waiting a single release will give enough uptick across federation that most users will be on a Synapse that supports room version 9 (and wish to push it out a bit quickly since room version 8 is buggy).
> Prefer room v9 for restricted rooms.

- changelog.d/10784.misc
- synapse/storage/databases/main/events.py
We've already batched up the events previously, and assume in other
places in the events.py file that we have. Removing this makes it easier
to adjust the batch sizes in one place.
> Don't needlessly batch in `add_event_to_cache`

- changelog.d/10733.bugfix
- synapse/handlers/sso.py
- synapse/rest/synapse/client/new_user_consent.py
Fixes #10732
Signed-off-by: Andrew Ferrazzutti <fair@miscworks.net>
> Ask consent on SSO registration with default mxid

- .ci/worker-blacklist
- changelog.d/10788.misc
- sytest-blacklist
> Remove fixed and flakey tests from the sytest blacklist

- changelog.d/10789.misc
- docs/user_directory.md
- synapse/handlers/deactivate_account.py
- synapse/handlers/state_deltas.py
- synapse/handlers/user_directory.py
- synapse/storage/databases/main/roommember.py
- synapse/storage/databases/main/user_directory.py
- tests/handlers/test_user_directory.py
PRs #10695 and #10761 became unwieldy. It was particularly hard to review because they both mix functional changes with refactorings.
Let's take a slower approach. I've started with a bunch of straightfoward refactorings.
> Easy refactors of the user directory

- changelog.d/10774.bugfix
- synapse/handlers/room.py
- tests/rest/client/test_upgrade_room.py
This handles room upgrades for spaces by transferring the `room_type` field of the create event and copying any `m.space.child` events from the previous room.
Fixes #10207, per the comment in there the upgrade process is somewhat implementation specific, so I think this change is fine to make without corresponding spec changes.
Open questions:
* Should we be ignoring `m.space.child` events which have no content (and thus were rooms that were removed from the space)?
> Handle room upgrades for spaces

- changelog.d/10795.doc
- docs/log_contexts.md
Signed-off-by: Olivier Wilkinson (reivilibre) <olivier@librepush.net>
> Fix 2 typos in docs/log_contexts.md

- changelog.d/10799.misc
- synapse/logging/opentracing.py
- synapse/python_dependencies.py
Add a max version for the `jaeger-client` dependency for an incompatibility with the rust reporter.
Without this you get an error:
```
synapse/logging/opentracing.py:385: error: Argument 1 to "create_tracer" of "Config" has incompatible type "_WrappedRustReporter"; expected "BaseReporter"  [arg-type]
synapse/logging/opentracing.py:385: error: Argument 2 to "create_tracer" of "Config" has incompatible type "Optional[Sampler]"; expected "Sampler"  [arg-type]
```
> Use  the BaseReporter super-class for _WrappedRustReporter.

- changelog.d/10804.doc
- docs/sample_config.yaml
- synapse/config/auth.py
The comment refers to requiring a lowercase letter for the password whereas an uppercase letter is actually required.
> Docs: Fix copypaste errors in YAML-file

- changelog.d/10810.bugfix
- synapse/http/matrixfederationclient.py
In `MatrixFederationHttpClient._send_request()`, we make a HTTP request
using an `Agent`, wrap that request in a timeout and await the resulting
`Deferred`. On its own, the `Agent` performing the HTTP request
correctly stashes and restores the logging context while waiting.
The addition of the timeout introduces a path where the logging context
is not restored when execution resumes.
To address this, we wrap the timeout `Deferred` in a
`make_deferred_yieldable()` to stash the logging context and restore it
on completion of the `await`. However this is not sufficient, since by
the time we construct the timeout `Deferred`, the `Agent` has already
stashed and cleared the logging context when using
`make_deferred_yieldable()` to produce its `Deferred` for the request.
Hence, we wrap the …
> Prevent logging context going missing on federation request timeout

- changelog.d/10812.misc
- synapse/api/auth.py
- synapse/api/auth_blocking.py
- synapse/crypto/context_factory.py
- synapse/crypto/keyring.py
- synapse/federation/federation_server.py
- synapse/federation/sender/__init__.py
- synapse/handlers/initial_sync.py
- synapse/handlers/presence.py
- synapse/handlers/sync.py
- synapse/http/client.py
- synapse/push/httppusher.py
- synapse/push/mailer.py
- synapse/push/pusher.py
- synapse/push/pusherpool.py
- synapse/server.py
This builds on #10798 to move more references over.
The first commit is done with sed + black, the rest were done by inspection / grep.
> Use direct references for some configuration variables (part 2)

- changelog.d/10823.misc
- mypy.ini
- synapse/storage/databases/state/bg_updates.py
- synapse/storage/databases/state/store.py
- synapse/storage/state.py
- synapse/util/caches/dictionary_cache.py
Adds type hints to `synapse.storage.databases.state`.
This is an old branch I had started at some point... (hence the `-2`...)
> Add type hints to state database

- changelog.d/10828.bugfix
- synapse/handlers/sync.py
We added a bunch of spans in #10704, but this ended up adding a *lot* of
redundant spans for rooms where nothing changed, so instead we only
start the span if there might be something interesting going on.
Pro tip: Probably easiest to review by disabling showing of whitespace changes :)
> Cleanup opentracing logging for syncs

- changelog.d/10834.misc
- tests/replication/test_multi_media_repo.py
- tests/rest/admin/test_admin.py
- tests/rest/admin/test_media.py
- tests/rest/admin/test_statistics.py
- tests/rest/admin/test_user.py
- tests/rest/media/v1/test_media_storage.py
- tests/test_utils/__init__.py
From a review comment on https://github.com/matrix-org/synapse/pull/10814#discussion_r710113115, but seemed worth factoring out and using it in other places too.
This only touches tests so should be good to go if unit tests pass.
> Create a constant for a small png image in tests.

- changelog.d/10843.bugfix
- synapse/storage/database.py
- synapse/storage/databases/main/account_data.py
- synapse/storage/databases/main/events.py
- synapse/storage/databases/main/events_bg_updates.py
- synapse/storage/databases/main/pusher.py
- synapse/storage/databases/main/state.py
- synapse/storage/databases/main/ui_auth.py
- synapse/storage/databases/state/store.py
We iterate twice over the same Iterable, expecting it to be the
same size each time.
This is not valid; instead we should demand a Collection.
Fixes #10824.
Intended to be commit-by-commit friendly, if you like.
> Fix remove_stale_pushers job on SQLite.

- .github/workflows/tests.yml
- changelog.d/10659.misc
This should checkout the dmr/cross-repo-branches sytest branch and run that against this
Requires the bootstrap.sh in the docker container used for sytest to have this change: https://github.com/matrix-org/sytest/pull/1123
> GHA: reintroduce an env var for `$GITHUB_HEAD_REF`

- changelog.d/10835.misc
- tests/rest/client/test_third_party_rules.py
Test for #10830
Ideally the test would also make sure the new state event comes down sync, but this is probably good enough.
> Test that state events sent by modules correctly end up in the room's state

- changelog.d/10867.misc
- synapse/http/site.py
> Add types to http.site

- changelog.d/10856.misc
- synapse/handlers/account_data.py
- synapse/handlers/appservice.py
- synapse/handlers/initial_sync.py
- synapse/handlers/presence.py
- synapse/handlers/receipts.py
- synapse/handlers/room.py
- synapse/handlers/sync.py
- synapse/handlers/typing.py
- synapse/module_api/__init__.py
- synapse/notifier.py
- synapse/storage/databases/main/receipts.py
- synapse/streams/__init__.py
- synapse/streams/events.py
- tests/handlers/test_receipts.py
- tests/handlers/test_typing.py
- tests/rest/client/test_shadow_banned.py
- tests/rest/client/test_typing.py
This is a follow-on to #10831 (based on a request https://github.com/matrix-org/synapse/pull/10831#discussion_r709953784 to not use `kwargs: Any`).
It clarifies the type hints for the event streams so that mypy can tell what objects they are. From there we then fix the various type hint errors. Finally, we clarify the type hints for `get_new_events`.
> Add type hints to event streams.

- changelog.d/10829.misc
- synapse/util/caches/__init__.py
- synapse/util/caches/expiringcache.py
- synapse/util/caches/lrucache.py
So we can see how often we're evicting because the cache is too big or because
the cache entries haven't been recently used. Previously these weren't
distinguishable on Grafana.
> Track why we're evicting from caches

- changelog.d/10879.misc
- synapse/events/__init__.py
I meant to do this before, in #10591, but because I'm stupid I forgot to do it for V2 and V3 events.
I've factored the common code out to `EventBase` to save us having two copies of it.
This means that for `FrozenEvent` we replace `self.get("event_id", None)` with `self.event_id`, which I think is safe. `get()` is an alias for `self._dict.get()`, whereas `event_id()` is an `@property` method which looks up `self._event_id`, which is populated during construction from the same dict. We don't seem to rely on the fallback, because if the `event_id` key is absent from the dict then construction of the `EventBase` object will fail.
Long story short, the only way this could change behaviour is if `event_dict["event_id"]` is changed *after* the `EventBase` object is constructed without updating …
> Include outlier status in `str(event)` for V2/V3 events

- changelog.d/10833.misc
- synapse/module_api/__init__.py
- synapse/storage/databases/main/client_ips.py
- tests/module_api/test_api.py
> Extend ModuleApi with the methods we'll need to reject spam based on …IP - resolves #10832

- changelog.d/10826.misc
- synapse/storage/databases/main/roommember.py
- synapse/util/caches/deferred_cache.py
- synapse/util/caches/descriptors.py
- synapse/util/caches/lrucache.py
We'll still invalidate the cache as usual, and we'll still throw away entries if the cache gets too big. But we won't prematurely throw away entries just because they haven't been used in a while.
Might help with #10786.
> Opt out of cache expiry for `get_users_who_share_room_with_user`

- changelog.d/10865.doc
- docs/SUMMARY.md
- docs/development/experimental_features.md
Per our discussions of when to use experimental config flags.
> Add documentation for experimental features.

- changelog.d/10819.feature
- synapse/rest/media/v1/oembed.py
- synapse/rest/media/v1/preview_url_resource.py
- tests/rest/media/v1/test_url_preview.py
* Better titles (fall back to the author name if there's not title).
* Parse photo/video payloads.
* Include the original URL in the Open Graph response.
* Uses the proper expiration time (the cache age was not being converted from seconds to milliseconds).
~~Builds on #10814~~
Related to #2752, #9733
* Does it make sense to include YouTube in our list of default oEmbed providers included with Synapse?
* With this change, YouTube previews work when using oEmbed, but they aren't as good as parsing the HTML directly (you end up with no description). This is better than having no preview, as reported in #9733, but I've been unable to reproduce that.
* Based on response in #9733, I don't think it makes sense to.
Note the added title (`Matrix - Twitter`).
> Improve oEmbed previews

- changelog.d/10873.bugfix
- synapse/handlers/federation.py
> Ensure we mark sent knocks as outliers

- changelog.d/10875.bugfix
- synapse/storage/databases/main/end_to_end_keys.py
The invalidation was missing in `_claim_e2e_one_time_key_returning`, which is used on SQLite 3.24+ and Postgres. This could break e2ee if nothing else happened to invalidate the caches before the keys ran out. It was probably a regression in #10504, which was released in v1.41.0rc1.
Signed-off-by: Tulir Asokan <tulir@beeper.com>
> Fix invalidating OTK count cache after claim

- changelog.d/10883.misc
- synapse/events/snapshot.py
- synapse/handlers/federation.py
- synapse/handlers/federation_event.py
- synapse/state/__init__.py
Constructing an `EventContext` for an outlier is actually really simple, and there's no sense in going via an `async` method in the `StateHandler`.
This also means that we can resolve a bunch of FIXMEs.
> Factor out a separate `EventContext.for_outlier`

- changelog.d/10889.misc
- synapse/config/server.py
- synapse/federation/sender/per_destination_queue.py
- synapse/handlers/federation.py
- synapse/handlers/message.py
- synapse/handlers/receipts.py
- synapse/handlers/room.py
- synapse/handlers/room_summary.py
- synapse/handlers/typing.py
- synapse/http/matrixfederationclient.py
- synapse/rest/admin/rooms.py
- synapse/rest/client/devices.py
- synapse/rest/client/password_policy.py
- synapse/storage/databases/main/account_data.py
- synapse/storage/databases/main/deviceinbox.py
- synapse/storage/databases/main/events_worker.py
- synapse/storage/databases/main/state_deltas.py
- synapse/storage/databases/main/stream.py
- synapse/streams/config.py
- synapse/types.py
- tests/test_state.py
- tests/utils.py
I was fairly sure we had cleaned up all of these at some point in the past, but I found a few more while spelunking through old bits of the codebase. They annoyed me enough that I've now rooted them all out for good(?).
There weren't enough occurrences to mess about with `sed`. This is the result of just going through the 20 or so results and manually correcting them. Thus a quick look-over of each one would be best.
> Remove unnecessary parentheses around tuples returned from methods

- changelog.d/10880.misc
- contrib/grafana/synapse.json
> Break down cache expiry reasons in grafana

- changelog.d/10884.misc
- synapse/handlers/federation_event.py
Part of my quest to make this thing comprehensible.
> Factor out `_get_remote_auth_chain_for_event` from `_update_auth_events_and_context_for_auth`

- changelog.d/10887.bugfix
- synapse/rest/admin/registration_tokens.py
- tests/rest/admin/test_registration_tokens.py
See https://github.com/matrix-org/matrix-doc/pull/3231/commits/79939f955b34113404b5d363a981f790aa7ec0e7
Signed-off-by: Callum Brown <callum@calcuode.com>
> Allow `.` and `~` chars in registration tokens

- changelog.d/10690.bugfix
- synapse/storage/databases/main/purge_events.py
This change adds a check for row existence before accessing row element, this should fix issue #10669
Signed-off-by: Vasya Boytsov <vasiliy.boytsov@phystech.edu>
> In `_purge_history_txn`, ensure that txn.fetchall has elements before accessing rows

- changelog.d/10891.misc
- mypy.ini
- synapse/storage/databases/main/user_directory.py
- tests/handlers/test_user_directory.py
This makes the user_directory.py in storage pass most of mypy's
checks (including `no-untyped-defs`). Unfortunately that file is in the
tangled web of Store class inheritance so doesn't pass mypy at the moment.
Non-functional change.
The handlers directory has already been mypyed.
> Improve typing in user_directory files

- changelog.d/10881.bugfix
- synapse/api/auth_blocking.py
- tests/api/test_auth.py
If the MAU count had been reached, Synapse incorrectly blocked appservice users even though they've been explicitly configured not to be tracked (the default). This was due to bypassing the relevant if as it was chained behind another earlier hit if as an elif.
> Fix AuthBlocking check when requester is appservice

- changelog.d/10868.feature
- synapse/http/server.py
- synapse/http/site.py
- synapse/rest/key/v2/remote_key_resource.py
- synapse/rest/media/v1/_base.py
- synapse/rest/media/v1/config_resource.py
- synapse/rest/media/v1/download_resource.py
- synapse/rest/media/v1/media_repository.py
- synapse/rest/media/v1/preview_url_resource.py
- synapse/rest/media/v1/thumbnail_resource.py
- synapse/rest/media/v1/upload_resource.py
- tests/http/test_additional_resource.py
- tests/logging/test_terse_json.py
- tests/replication/test_multi_media_repo.py
- tests/rest/admin/test_admin.py
- tests/rest/admin/test_media.py
- tests/rest/admin/test_user.py
- tests/rest/client/test_account.py
- tests/rest/client/test_consent.py
- tests/rest/client/utils.py
- tests/rest/key/v2/test_remote_key_resource.py
- tests/rest/media/v1/test_media_storage.py
- tests/server.py
- tests/test_server.py
It's useful to be able to get the reactor from a request, c.f. #10844
Split out from #10844
> Add reactor to `SynapseRequest` and fix up types.

- changelog.d/10901.misc
- synapse/handlers/federation_event.py
Combine the two loops over the list of events, and hence get rid of `_NewEventInfo`. Also pass the event back from `prep` alongside the context, so that it's easier to process the result.
> Simplify `_auth_and_persist_fetched_events`

- changelog.d/10896.misc
- synapse/federation/federation_client.py
- synapse/handlers/federation_event.py
- tests/handlers/test_federation.py
We currently have two codepaths that are used for persisting fetched auth events:
* `_get_events_and_persist`, which is used to fetch the state events and auth events for a new backwards extremity.
* `_get_remote_auth_chain_for_event`, which is called when we are missing the auth events for any other regular event.
There is common code between the two paths which can be factored out.
Should be reviewable commit by commit. It's independent of #10901, but the similarity between the two codepaths might be clearer once that has landed.
> Factor out common code for persisting fetched auth events

- changelog.d/10907.bugfix
- synapse/handlers/federation_event.py
There are a couple of situations under which we will end up persisting a bunch of events as `outliers`:
* when we form a new backwards extremity (typically after backfilling a bunch of events), we need to record the state of the room at that backwards extremity, which in turn requires us to have all the state events that form that state (and, recursively, their auth events). In this case, we request each event we don't already have, and then auth/persist them all.
* when we receive a regular event which refers to auth events which we are missing. In this case, we request the "auth chain" for the event from the remote server, and then auth/persist any events in that auth chain we didn't already have.
In either case, we need to decide what to do when we *still* don't have some of the auth …
> Stop prematurely rejecting outlier events with missing auth_events

- changelog.d/10917.misc
- synapse/storage/schema/__init__.py
Document changes to schema version. Retroactively summarize `61` - `64`
As pointed out by @richvdh, https://github.com/matrix-org/synapse/pull/10838#discussion_r715424244
> Document changes to schema version 61 - 64

- changelog.d/10913.bugfix
- synapse/config/_base.py
- synapse/rest/media/v1/media_storage.py
- synapse/rest/media/v1/storage_provider.py
This ought to fix a couple of errors seen on matrix.org:
https://sentry.matrix.org/sentry/synapse-matrixorg/?query=is%3Aunresolved+FileExistsError
> Fix race conditions when creating media store and config directories

- changelog.d/10911.bugfix
- docs/upgrade.md
- synapse/rest/media/v1/filepath.py
- synapse/rest/media/v1/preview_url_resource.py
- synapse/rest/media/v1/storage_provider.py
- tests/rest/media/v1/test_url_preview.py
URL cache files are short-lived and it does not make sense to offload
them (eg. to the cloud) or back them up.
Fixes #10862
> Avoid storing URL cache files in storage providers

- changelog.d/10905.feature
- synapse/http/server.py
- synapse/push/emailpusher.py
- synapse/util/iterutils.py
This is the same as #10844, but with fewer commits.
> Encode JSON responses on a thread in C, mk2

- changelog.d/10931.bugfix
- docker/Dockerfile-dhvirtualenv
This was due to dh-virtualenv builds being broken due to Sphinx removing deprecated APIs.
> Fix debian package builds.

- changelog.d/10927.bugfix
- synapse/event_auth.py
Fixes #10923
The clause was being applied for rooms which don't support this feature. My hope is this will have minimal impact since the additional field shouldn't exist for non- v8/v9 rooms.
> Only do restricted join rules signature checks for room versions 8/9.

- changelog.d/10915.misc
- synapse/config/server.py
- synapse/handlers/pagination.py
This cleans up some of the classes / type hints in the server config file.
The first commit is necessary to continue in my quest to eradicate the magic in `RootConfig`, but the others were easy enough to do while I was there.
> Clean-up type hints in server config

- changelog.d/10932.feature
- synapse/http/server.py
Introduced in #10905
It's a bit icky, but a) matches what we do when we call `.finish()`, and b) there isn't a more specific exception class really as the problem is that it raises an `AttributeError`. The alternative is to check if `request.channel` is still set, but that seems a bit brittle
c.f. https://sentry.matrix.org/sentry/synapse-matrixorg/issues/231719/events/b3e541e6016d43f3a584f986d07bc132/
> Fix exception responding to request that has been closed

- changelog.d/10903.misc
- synapse/storage/databases/main/events.py
- synapse/storage/schema/__init__.py
Before Synapse 1.31 (#9411), we relied on `outlier` being stored in the `internal_metadata` column. We can now assume nobody will roll back their deployment that far and drop the legacy support.
Fixes #9670.
> Drop backwards-compatibility support for "outlier"

- changelog.d/10902.misc
- synapse/util/__init__.py
Background: some versions of frozendict contain a C implementation of frozendict that was incompatible with our code. This PR adds logic to catch and handle those cases. See also https://github.com/matrix-org/python-canonicaljson/issues/36 for more context.
> Update utility code to handle C implementations of frozendict

- changelog.d/10877.feature
- synapse/handlers/message.py
- synapse/rest/client/room_batch.py
- synapse/storage/databases/main/events.py
- synapse/storage/databases/main/room_batch.py
Ensure `(room_id, next_batch_id)` is unique across insertion events to avoid cross-talk/conflicts between batches. Currently does not stop duplicate insertion events over federation, see https://github.com/matrix-org/synapse/pull/10877#discussion_r715315789
Part of [MSC2716](https://github.com/matrix-org/matrix-doc/pull/2716)
Part of https://github.com/matrix-org/synapse/issues/10737
Complement changes in https://github.com/matrix-org/complement/pull/207
Briefly discussed at https://github.com/matrix-org/synapse/pull/10245#discussion_r669641879
`soft_failed` vs `rejected`?
- `rejected`: when an event doesn't pass event auth rules based on the auth events given and state at the event
- https://matrix.org/docs/spec/server_server/r0.1.4#rejection
- `soft_fail`: when an event doesn't pass the …
> Ensure `(room_id, next_batch_id)` is unique to avoid cross-talk/conflicts between batches (MSC2716)

- changelog.d/10924.bugfix
- synapse/rest/media/v1/preview_url_resource.py
- tests/rest/media/v1/test_url_preview.py
Fixes observation 4 in #10863.
When we get around to cleaning up the parents of the thumbnail directory, the thumbnail directory itself has already been deleted.  Instead of continuing with the deletion of the rest of the parent paths, we currently abort, which leaves empty directories lying around:
https://github.com/matrix-org/synapse/blob/f7768f62cbf7579a1a91e694f83d47d275373369/synapse/rest/media/v1/preview_url_resource.py#L565-L570
> Fix empty `url_cache_thumbnails/yyyy-mm-dd/` directories being left behind

- changelog.d/10934.misc
- synapse/events/builder.py
- synapse/handlers/federation.py
- synapse/handlers/message.py
- synapse/handlers/room.py
Various refactors to use `RoomVersion` objects instead of room version identifieers.
Should be reviewable commit-by-commit
> Use `RoomVersion` objects

- README.rst
- changelog.d/10919.doc
- docs/setup/installation.md
Various updates to the install docs.
It starts with switching a couple of the sections around so might be worth reviewing that first.
> Update installation instructions

- changelog.d/10922.bugfix
- synapse/rest/client/voip.py
`ttl` must be an integer according to the OpenAPI spec:
https://github.com/matrix-org/matrix-doc/blob/old_master/data/api/client-server/voip.yaml#L70
True division (`/`) returns a float instead (`"ttl": 7200.0`).
Floor division (`//`) returns an integer, so the response is spec compliant.
Like https://github.com/matrix-org/synapse/pull/10175
> Fix getTurnServer response: integer ttl

- changelog.d/10939.misc
- tests/appservice/test_scheduler.py
- tests/events/test_presence_router.py
- tests/federation/test_federation_sender.py
- tests/module_api/test_api.py
This fixes some errors that appear in the logs during tests (mostly of the "cannot await a Mock" sort of error). This generally happens in background processes or get caught, but we can do better.
Generally if the unit tests pass this should be OK.
There's definitely more than what's fixed here, but this makes it better.
> Fix logged errors from unit tests.

- changelog.d/10945.misc
- synapse/handlers/register.py
- tests/handlers/test_register.py
This has a couple non-functional changes and then attempts to have the `test_auto_create_auto_join_where_no_consent` test what the comments say.
* Mocks out some federation logic.
* Uses `override_config` in places.
* Update the config in `test_auto_create_auto_join_where_no_consent`  to have auto-join rooms, which then breaks the test. (The test wasn't setting `auto_join_rooms` properly so it wasn't attempting to join rooms ever.)
Open questions:
* There's a race in the consent logic that if another user registers before the first user registers & completes consent than the auto-join rooms will never be created. I wonder if it would be more robust to attempt to join the room if it exists, otherwise create it for every user?
See #4886 which tried to fix this previously.
> Clean-up registration tests

- changelog.d/10961.misc
- tests/replication/_base.py
- tests/rest/client/test_login.py
- tests/unittest.py
For better IDE completion. A small drive-by.
> type-hint `HomeserverTestcase.setup_test_homeserver`

- changelog.d/10968.bugfix
- synapse/storage/databases/main/client_ips.py
- tests/storage/test_client_ips.py
Fixes #10957, introduced in v1.44.0rc1
> Fix error in `get_user_ip_and_agents` when fetching from the database

- changelog.d/10959.misc
- synapse/handlers/auth.py
- synapse/handlers/identity.py
- synapse/handlers/profile.py
- synapse/handlers/register.py
- synapse/handlers/room_member.py
- synapse/handlers/ui_auth/checkers.py
- synapse/rest/admin/users.py
- synapse/rest/client/account.py
- synapse/rest/client/auth.py
- synapse/rest/client/capabilities.py
- synapse/rest/client/login.py
- synapse/rest/client/register.py
- synapse/rest/well_known.py
- synapse/storage/databases/main/registration.py
- synapse/util/threepids.py
- tests/config/test_load.py
- tests/handlers/test_profile.py
- tests/rest/admin/test_user.py
- tests/rest/client/test_account.py
- tests/rest/client/test_identity.py
- tests/rest/client/test_login.py
- tests/rest/client/test_register.py
- tests/unittest.py
Builds on #10798, #10812, #10885, #10893, #10897, and #10916.
Each commit was done with `sed` + `black`, then running the linters and fixing some type hints. Sorry that this one got a bit big.
~~Builds on #10945.~~
There's a few remaining instances after this that I had missed in previous PRs (or got added after this was all done?) I'll fix those in the final PR.
> Use direct references for configuration variables (part 7).

- changelog.d/10960.bugfix
- synapse/handlers/user_directory.py
- synapse/storage/databases/main/user_directory.py
- tests/handlers/test_user_directory.py
- tests/rest/client/test_login.py
- tests/storage/test_user_directory.py
- tests/unittest.py
Spun off from #10914, alongside #10891. Please review commit-by-commit.
Most of the effort here went into writing test cases. There's some duplication between testing the incremental updates and testing the complete rebuild.
In the rebuild functions I filter `users_with_profile` to exclude users early (rather than at the point of potentially putting them in the DB). That's because there was a code path that missed this check even before my changes. 
I think we could probably do a similar thing in the incremental update functions, but I didn't do that here to keep the changeset minimal.
> Consistently exclude from user_directory, round 2

- changelog.d/10983.misc
- synapse/logging/opentracing.py
Make it easier to track down where opentracing spans are going missing
by including stack traces in the logs.
> Log stack traces when a missing opentracing span is detected

- changelog.d/10991.doc
- docs/MSC1711_certificates_FAQ.md
- docs/usage/administration/admin_api/registration_tokens.md
> Fix broken links to MSC in documentation

- .github/workflows/tests.yml
- changelog.d/10992.misc
Python 3.10 was [released yesterday](https://www.python.org/downloads/release/python-3100/), and the `setup-python` action supports it [as of three hours ago](https://github.com/actions/python-versions/releases/tag/3.10.0-117470).
Postgres 14 was [released at the end of September](https://www.postgresql.org/docs/14/release-14.html) and the dockerhub container [is at least two hours old](https://hub.docker.com/layers/postgres/library/postgres/14.0/images/sha256-da98eb3d0ac42daede96c9cdf77ac57ef8e3c50614f48fcafe55e691b7d9a590?context=explore).
Bump the CI jobs that run on the latest versions of python and postgres to use these. (Should we use postgres:latest rather than pinning a specific number?)
Also include an explicit matrix job for trial under Python 3.10.
> Run CI with Python 3.10 and Postgres 14

- changelog.d/10988.misc
- synapse/handlers/federation_event.py
There's little point in doing a fancy state reconciliation dance if the event
itself is invalid.
Likewise, there's no point checking it again in `_check_for_soft_fail`.
> `_check_event_auth`: move event validation earlier

- changelog.d/10986.misc
- synapse/handlers/federation_event.py
`_check_event_auth` is only called in two places, and only one of those sets `send_on_behalf_of`. Warming the cache isn't really part of auth anyway, so moving it out makes a lot more sense.
> Hoist `cache_joined_hosts_for_event` to caller

- changelog.d/10956.bugfix
- synapse/event_auth.py
When we consider whether to accept events, we should not accept those which depend on rejected events for their auth events.
This (together with earlier changes such as https://github.com/matrix-org/synapse/pull/10771 and https://github.com/matrix-org/synapse/pull/10896) forms a partial fix to https://github.com/matrix-org/synapse/issues/9595. There still remain code paths where we do not check the `auth_events` at all.
Complement doesn't work with versions of synapse before 1.8.0 (it relies on send_join v2), but this bug seems to have existed since at least then.
> Ensure that we reject events which use rejected events for auth

- changelog.d/10962.bugfix
- synapse/handlers/federation_event.py
- synapse/storage/databases/main/events.py
Fix logic flaw preventing tracking of MSC2716 events in existing room versions
We correctly allowed using the MSC2716 batch endpoint for
the room creator in existing room versions but accidentally didn't track
the events because of a logic flaw.
This prevented you from connecting subsequent batches together because it would
throw the unknown batch ID error.
Complement tests: https://github.com/matrix-org/complement/pull/209
> Fix logic flaw preventing tracking of MSC2716 events in existing room versions

- changelog.d/10981.bugfix
- synapse/storage/databases/main/user_directory.py
- tests/storage/test_user_directory.py
The meat is in the first commit. The next two are small cleanups that I'd like to make, but don't have a functional impact and aren't necessary.
> Fix potential leak of per-room profiles when the user dir is rebuilt.

- changelog.d/10982.bugfix
- synapse/handlers/user_directory.py
- tests/handlers/test_stats.py
- tests/handlers/test_user_directory.py
- tests/storage/databases/main/test_room.py
- tests/storage/test_cleanup_extrems.py
- tests/storage/test_client_ips.py
- tests/storage/test_event_chain.py
- tests/storage/test_roommember.py
- tests/storage/test_user_directory.py
- tests/unittest.py
I spotted this when I was trying to do another refactor/tidy up of this code. Argh! Not sure if we ever hit this (I don't know the details of how `_handle_deltas` is hit---it presumably is sensitive to replication delays?).
Anyway, this squashes a bug and makes be feel better.
> Don't drop user dir deltas when server leaves room

- changelog.d/11004.misc
- mypy.ini
- synapse/state/__init__.py
- synapse/state/v1.py
- synapse/state/v2.py
Much smaller than I was expecting!
> `disallow-untyped-defs` for `synapse.state`

- changelog.d/11206.removal
- docs/modules/spam_checker_callbacks.md
- docs/upgrade.md
We realised `user_may_create_room_with_invites` is fairly useless as `user_may_invite` will be called later down the room creation process. This means any module wishing to implement different moderation rules on invites depending on whether they happen during a room's creation or not can't, since `user_may_invite` doesn't have this information. So if `user_may_create_room_with_invites` allows an invite to go through that should be denied outside of room creation, `user_may_invite` will stop it.
Instead, the preferred way is to infer how new the room is using the method introduced in https://github.com/matrix-org/synapse/pull/11204 from within `user_may_invite`.
> Deprecate `user_may_create_room_with_invites`

- changelog.d/11179.misc
- tests/storage/test_client_ips.py
Following on from a suggestion in https://github.com/matrix-org/synapse/pull/11112
> Test that `ClientIpStore` combines database and in-memory data correctly

- changelog.d/11178.feature
- synapse/app/_base.py
- synapse/metrics/__init__.py
- synapse/storage/database.py
>  Add metrics to the threadpools

- changelog.d/11097.feature
- synapse/rest/client/versions.py
Fixes https://github.com/matrix-org/synapse/issues/11064
I can't tell if any unstable features should be removed. It looks like `org.matrix.msc2432` is in the r0.6.1 changelog but Element only checks for the `org.matrix.msc2432` flag and not for r0.6.1 so maybe it isn't in r0.6.1.
> Support Client-Server API r0.6.1

- changelog.d/11209.docker
- docker/README.md
- docker/start.py
Two related changes
* When the image is run with a `generate` param to generate a new config file, don't try to change user ID for the generate step. I think this was introduced accidentally as part of #5970.
* When we are run as non-root (eg, with a `--user` param to docker, or via a different runtime like OpenShift which does so by default), don't try to change user unless a UID is explicitly given.
It was possible to work around this before by setting UID to match whatever userid we were being run as, but that was somewhat fiddly.
> Docker: avoid changing userid unnecessarily

- changelog.d/11128.doc
- docs/reverse_proxy.md
I ran into trouble getting federation working properly with the haproxy config specified here.  After some debugging, I discovered that many federation HTTP requests, including the ones sent by the [federation tester](https://federationtester.matrix.org/), include the port number in the HTTP Host header field.  For example, instead of `Host: matrix.example.com`, these federation requests look like `Host: matrix.example.com:443`.  At least on haproxy 2.3, the extra port information causes the `acl matrix-host hdr(host) -i matrix.example.com` match to fail, since this is looking for an exact string match by default according to the [haproxy docs](http://cbonte.github.io/haproxy-dconv/2.3/configuration.html#7.1).  This failure, in turn, causes haproxy to return error codes and causes …
> Add domain specific matching for haproxy config

- changelog.d/11217.bugfix
- synapse/federation/transport/client.py
Fixes  #11135, which appears to have been introduced in #9958. Prior to this change, when `ijson` parsed floats it returned a `Decimal`, which is incompatible with `canonicaljson` and caused an error wherein users were unable to join some rooms that returned a `send_join` response containing floats. I tested this solution by spinning up a homeserver,  reproducing the failed `send_join` to `#ghidra:matrix.org` (a room known to be prone to this error), making the below edits in the code used for the homeserver, restarting, and verifying that I could successfully join `ghidra:matrix.org`.
> Add `use_float=true` to ijson calls in Synapse

- changelog.d/11200.bugfix
- synapse/rest/media/v1/media_repository.py
- synapse/rest/media/v1/upload_resource.py
- tests/rest/media/v1/test_media_storage.py
Fixes issue #11044. Currently Synapse throws an error when fetching media without a `Content-Type` header. This PR adds logic to check for missing `Content-Type` headers when downloading remote media and default the `Content-Type` to `application/octet-stream` (per https://httpwg.org/specs/rfc7231.html#header.content-type) where that is the case. It also does the same for when media is being uploaded, and when media is pulled out of the local database.
> Handle missing Content-Type header when accessing remote media

- changelog.d/11229.misc
- synapse/util/async_helpers.py
- tests/util/caches/test_deferred_cache.py
- tests/util/test_async_helpers.py
It came as a bit of a surprise to me that `ObservableDeferred` *doesn't* run its registered observers in order. This has ramifications like meaning that, if we have two things waiting for a database lookup, we don't run them in a first come, first served order.
I'm not really sure that the existing behaviour breaks anything, but I think a bit more determinism is probably a good thing, as is doing what people expect.
> ObservableDeferred: run observers in order

- changelog.d/11099.feature
- docs/admin_api/rooms.md
- synapse/storage/databases/main/room.py
- tests/rest/admin/test_room.py
> Add search by room ID and room alias to List Room admin API

- changelog.d/11137.bugfix
- changelog.d/11137.misc
- synapse/handlers/appservice.py
- synapse/notifier.py
- synapse/storage/databases/main/devices.py
- synapse/storage/databases/main/presence.py
We typically figure out which EDUs to send to application services based the last stream token that appservice successfully received. This is true for read receipts and user presence, however for typing we always just send the last typing event. This process is started whenever a new read receipt, presence update or typing event is processed by the server. In that case, `notify_interested_services_ephemeral` will be called with the new event and its stream token (so we can check whether we need to send any other events to the appservice may have missed).
With all that in mind, I believe I've found a bug in the implementation. If a `RoomStreamToken` object was provided as the `new_token` argument to `_notify_app_services_ephemeral`, `new_token` would be set to `None`, before then being …
> Fix providing a `RoomStreamToken` instance to `_notify_app_services_ephemeral`

- changelog.d/11233.misc
- setup.py
We don't pin them as we execute them as commands, rather than use them
as libs.
> Add twine and towncrier as dev dependencies

- changelog.d/11239.misc
- tests/module_api/test_api.py
There was a leftover `print()` statement in one of the tests which I noticed. 😄
> Remove a debug statement from tests.

- changelog.d/11237.misc
- synapse/config/workers.py
- synapse/federation/federation_server.py
- synapse/handlers/typing.py
- synapse/replication/tcp/handler.py
- synapse/replication/tcp/streams/_base.py
- synapse/rest/client/room.py
- synapse/server.py
Small consistency tweak that makes the typing stream writer config match the other stream writers that only currently support a single worker.
Signed-off-by: Nick Barrett <nick@beeper.com>
> Enable passing typing stream writers as a list.

- changelog.d/11207.bugfix
- synapse/handlers/appservice.py
- tests/handlers/test_appservice.py
To close: https://github.com/matrix-org/synapse/issues/11195
Skipped the linearization for typing events as they're a special case and unaffected by this issue.
Signed-off-by: Nick Barrett <nick@beeper.com>
> Add a linearizer on (appservice, stream) when handling ephemeral events.

- changelog.d/11240.bugfix
- synapse/storage/databases/main/events_worker.py
When an event fetcher aborts due to an exception, `_event_fetch_ongoing`
must be decremented, otherwise the event fetcher would never be
replaced. If enough event fetchers were to fail, no more events would be
fetched and requests would get stuck waiting for events.
Fixes part of #11167
> Track ongoing event fetches correctly in the presence of failure

- changelog.d/11246.misc
- tests/util/caches/test_descriptors.py
I was trying to understand how `cachedList` works, and ended up writing this extra test. I figure we may as well keep it.
> Additional test for `cachedList`

- changelog.d/11255.bugfix
- synapse/storage/prepare_database.py
- tests/storage/test_rollback_worker.py
> Fix rolling back when using workers

- changelog.d/11257.doc
- docs/openid.md
We add some documentation about how to integrate a Synapse Homeserver
with LemonLDAP::NG (an OpenSource access management and identity
federation solution)
> Add doc to integrate synapse with LemonLDAP OIDC

- changelog.d/11262.bugfix
- synapse/federation/federation_server.py
- synapse/storage/databases/main/lock.py
If a worker handling inbound federation dies and gets restarted then the locks held when it got killed will still be considered valid when it starts up again (as the timeouts won't have expired yet). So when we check for staged events in the DB at start up we won't process any of those where the lock for the room was previously held, and then we won't check again until we get another event for that room or we restart, causing those events to get stuck even though the locks will time out.
We fix this in two ways:
1. We ignore locks that match our instance name that we don't actually hold; and
2. Add a periodic check for old staged events.
> Handle federation inbound instances being killed more gracefully

- docs/turn-howto.md
> Wrong DTLS port in TURN server "Troubleshooting" section.

- changelog.d/11210.feature
- docs/sample_config.yaml
- synapse/api/urls.py
- synapse/config/account_validity.py
- synapse/config/cas.py
- synapse/config/emailconfig.py
- synapse/config/oidc.py
- synapse/config/registration.py
- synapse/config/saml2.py
- synapse/config/server.py
- synapse/config/sso.py
- synapse/handlers/identity.py
- synapse/rest/well_known.py
- tests/push/test_email.py
- tests/rest/client/test_consent.py
- tests/rest/client/test_register.py
Having a working `public_baseurl` is required for many things in the codebase, and for common deployments, we can derive a working default from `server_name`. So, we might as well do that, to help admins out as much as we can.
One slight wrinkle is that setting `public_baseurl` currently changes some behavior: in particular, it affects whether we put the public_baseurl in the response to `/login`, which tells clients to redirect to that url. So, if we suddenly start returning a *wrong* url there instead of none at all, it could break existing, working deployments.
Also adds some validation for `public_baseurl` while I'm in the area.
> Default value for `public_baseurl`

- changelog.d/11244.misc
- synapse/handlers/message.py
- synapse/rest/client/room_batch.py
- synapse/storage/databases/main/room_batch.py
Rename to more clear `get_insertion_event_id_by_batch_id`
`get_insertion_event_by_batch_id` -> `get_insertion_event_id_by_batch_id`
Split out from https://github.com/matrix-org/synapse/pull/11114
> Rename to more clear `get_insertion_event_id_by_batch_id` (MSC2716)

- changelog.d/11234.bugfix
- synapse/handlers/e2e_keys.py
- tests/handlers/test_e2e_keys.py
When fetching remote devices for the first time, we did not correctly include the cross signing keys in the returned results. 
Reviewable commit by commit.
I think replaces #10912
cc #11159
> Include cross-signing signatures when syncing remote devices for the first time

- changelog.d/11278.misc
- synapse/rest/client/relations.py
So that it now reads: Relation type must be 'm.annotation'.
> Fix typo in `RelationAggregationPaginationServlet` error response

- changelog.d/11236.feature
- synapse/api/filtering.py
- synapse/handlers/pagination.py
- synapse/handlers/room.py
- synapse/handlers/search.py
- synapse/handlers/sync.py
- synapse/rest/admin/rooms.py
- synapse/rest/client/room.py
- synapse/rest/client/sync.py
- synapse/storage/databases/main/relations.py
- synapse/storage/databases/main/stream.py
- tests/api/test_filtering.py
- tests/handlers/test_sync.py
- tests/rest/client/test_rooms.py
- tests/storage/test_stream.py
Implements filtering via relations per[MSC3440](https://github.com/matrix-org/matrix-doc/pull/3440), specifically filtering for parent events which have:
* `relation_types`: Another event referring to them of particular relation type(s).
* `relation_senders`: Another event referring to them from particular sender(s).
This PR uses the unstable prefixes and required a bit of refactoring (I can split this work out to a separate PR if preferred):
* Updates the `filter_*` methods to be async
* Allow the `FIlter` to access the datastore (via `HomeServer`)
After that we can update the `Filter` implementation to take the additional filterings parameters and apply those in:
* The pagination infrastructure from the database.
* The manual checks against the event objects.
This should be reviewable …
> Support filtering by relations per MSC3440

- changelog.d/11228.feature
- docs/admin_api/rooms.md
- synapse/handlers/room.py
- synapse/rest/admin/rooms.py
- synapse/storage/databases/main/room.py
- tests/rest/admin/test_room.py
Wasn't thrilled with how this one turned out. The implementation and API shape feels icky.
The first three commits are doc fixups. The rest should be okay to review commit-by-commit.
> Allow admins to proactively block rooms

- changelog.d/11247.misc
- synapse/handlers/appservice.py
- synapse/handlers/devicemessage.py
- synapse/storage/databases/main/appservice.py
- synapse/storage/databases/main/deviceinbox.py
- tests/handlers/test_appservice.py
A lot of little clarifications and some fixes split out from #11215 to help reduce muddying of the new feature.
Most of the comment changes are just helping document what's already there. There are also a couple code changes included:
* Tightening up a type hint that didn't need to be optional.
* Preventing shadowing the `type` built-in by renaming a variable.
Recommended to review commit-by-commit.
> Clarifications and small fixes to to-device related code

- changelog.d/11285.misc
- mypy.ini
This seems to be from a conflict between #11282 and #11228.
Example failing run: https://github.com/matrix-org/synapse/runs/4154822727?check_suite_focus=true
> Ignore missing imports for parameterized.

- changelog.d/11242.misc
- synapse/federation/federation_client.py
Split out federated PDU retrieval into a non-cached version
Context: https://github.com/matrix-org/synapse/pull/11114/files#r741643968
This code is unused but thought it seemed like a small refactor with a little bit of value to split some of the logic out. And the caching/rate-limiting is handled in the `get_pdu` consumer.
> Split out federated PDU retrieval into a non-cached version

- changelog.d/11286.doc
- docs/admin_api/user_admin_api.md
- Fix typo in the word `available`
- HTTP method should be `GET`, not `POST`
> Fix typos for `username_available` admin API

- changelog.d/11292.misc
- synapse/handlers/federation_event.py
- tests/test_federation.py
as of #11012, these parameters are unused.
> Remove redundant parameters on `_check_event_auth`

- changelog.d/11297.misc
- mypy.ini
- setup.py
- synapse/_scripts/register_new_matrix_user.py
- synapse/_scripts/review_recent_signups.py
These were pretty straightforward, a couple of oddities though.
> Add type hints to synapse._scripts

- changelog.d/11303.feature
- changelog.d/11303.misc
- synapse/storage/schema/main/delta/65/05remove_deleted_devices_from_device_inbox.sql
Between creation and merging PR #10969 was an schema update in #10975 (v1.46.0). That is the reason why the bg task remove_deleted_devices_from_device_inbox is not running in v1.47.0.rc2. https://github.com/matrix-org/synapse/pull/10969/files#diff-d664ca027d1e3730574905917ca3ab47ab476edca1434fe0ae08b8bce06d1fdb has to move from schema 64 to 65.
(run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html# …
> Move sql file for `remove_deleted_devices_from_device_inbox` into v65

- changelog.d/11310.misc
- mypy.ini
- synapse/storage/databases/main/room_batch.py
#10975 introduce a function of the form
```
async def foo(*args, **kwargs) -> Optional[str]:
{
await expression
}
```
This is legit syntax (it's building a set literal) but unusual (see `python -c "from __future__ import braces"`). The function as written will always return None. We don't inspect the return value of this function at its only call site, so it's safe to remove the braces and declare a return type of `None`.
> Correct type hint for room_batch.py

- changelog.d/11312.misc
- mypy.ini
- synapse/events/builder.py
- synapse/storage/databases/main/signatures.py
Introduce an intermediate variable so we don't replace `Dict[str, bytes]` with `Dict[str, str]`.
> Get db signatures file to pass mypy

- changelog.d/11313.misc
- mypy.ini
- synapse/storage/databases/main/user_erasure_store.py
I'm not sure why this was excluded---it seemed to be passing for me. But
it's easy enough to fixup.
> Annotations for user_erasure_store

- changelog.d/11281.doc
- docs/setup/installation.md
I don't know if this is actually best, so hopefully someone with Debian opinions can confirm/deny if this is a good idea or not.
Fixes #11238.
> Suggest using `/etc/matrix-synapse/conf.d/` for configuration with Debian packages

- changelog.d/11321.misc
- synapse/http/server.py
- synapse/util/__init__.py
This cleans-up the type hints in `synapse/util/__init__.py`.
> Add more type hints to synapse.util.

- changelog.d/11322.misc
- mypy.ini
Instead of including specific files we include full modules.
The main benefit to this is that as we removed ignored files from mypy we require all the type hints in those files.
> Generalize the disallowed_untyped_defs in mypy.ini

- changelog.d/11323.misc
- synapse/rest/__init__.py
- synapse/types.py
- tests/replication/_base.py
- tests/rest/client/utils.py
- tests/server.py
- tests/unittest.py
While trying to annotate `storage.directory` I found myself suddenly awash with new mypy errors in `tests`. This is an effort to fix some of those up.
> Misc typing fixes for `tests`, part 1 of N

- changelog.d/11314.misc
- mypy.ini
- synapse/storage/databases/main/__init__.py
- synapse/storage/databases/main/events_forward_extremities.py
It was particularly painful to decipher why the DataStore mro was inconsistent.
> Attempt to annotate events_forward_extremities

- changelog.d/11327.misc
- mypy.ini
- synapse/handlers/directory.py
- synapse/storage/databases/main/directory.py
- tests/rest/client/test_directory.py
I thought there was a bug in #11319  by my reading of the source code. I learned that my reading was incomplete after I wrote a test case to try and demonstrate the bug. We may as well keep that test case around. While I'm at it, I did some typing too.
> Test room alias deletion

- changelog.d/11332.misc
- mypy.ini
It should have been `[mypy-tests.*]` but that obviously won't work.
> Rollback #11322 due to wrong syntax in mypy.ini

- changelog.d/11316.misc
- mypy.ini
- synapse/storage/databases/main/state_deltas.py
I was sad that I couldn't do better for
`_curr_state_delta_stream_cache`. At least it's explicitly called out in
a comment with #TODO.
> Annotations for state_deltas.py

- changelog.d/11335.feature
- synapse/rest/client/login.py
- tests/handlers/test_password_providers.py
- tests/rest/client/test_login.py
Stable prefixes can be used as soon as the MSC has finished FCP, and [MSC2778](https://github.com/matrix-org/matrix-doc/pull/2778) was accepted some time ago already.
> Add support for the stable version of MSC2778

- changelog.d/11342.misc
- mypy.ini
- synapse/storage/databases/main/profile.py
- tests/storage/test_profile.py
It already seems to pass mypy. I wonder what changed, given that it was
on the exclusion list. So this commit consists of me ensuring
`--disallow-untyped-defs` passes and a minor fixup to a function that
returned either `True` or `None`.
> Database storage profile passes mypy

- changelog.d/11346.bugfix
- synapse/storage/prepare_database.py
- tests/storage/test_rollback_worker.py
Fixes https://github.com/matrix-org/synapse/issues/11344.
Workers need to run `_upgrade_existing_database` to figure out if any outstanding delta files exist (it's the thing that actually traverses the filesystem for new delta files to apply). But, workers only need to run this if we're currently on the latest schema version.
If the database reports that we're not on the latest schema version, then we can simply bail out without needing to run `_upgrade_existing_database`.
#11255 made the correct fix for when we roll back the database schema version, in that `_upgrade_existing_database` should not be run if `version_info.schema_version` > SCHEMA_VERSION. But we still need to run this method on workers if `version_info.schema_version` == SCHEMA_VERSION to get them to halt startup, and let …
> Run _upgrade_existing_database on workers if at current schema_version

- changelog.d/11330.misc
- tests/handlers/test_register.py
- tests/rest/client/utils.py
- tests/server.py
- tests/unittest.py
I haven't included the mypy config that prompted these errors because there are too many. But I promise this fixed errors!
> Misc typing fixes for tests, part 2 of N

- changelog.d/11340.bugfix
- synapse/handlers/auth.py
Introduced in https://github.com/matrix-org/synapse/commit/cdd308845ba22fef22a39ed5bf904b438e48b491#diff-54e31652219b9be5b5121f808bd34ccf9fa7d56f45d04ab307e501445c11401aR1951.
Found whilst un-erasing type annotations for the module API.
> Properly register all callback hooks for legacy password authentication providers

- changelog.d/11318.feature
- synapse/app/homeserver.py
- synapse/rest/client/_base.py
- synapse/rest/client/keys.py
Step 2 of https://github.com/matrix-org/synapse/issues/11079
I also put `/keys/device_signing/upload` on the stable v3 API while I was here. After a quick look, that was the only new API in Matrix 1.1 I could find that wasn't already using a stable API prefix.
> Add support for `/_matrix/client/v3` APIs

- changelog.d/11355.bugfix
- synapse/handlers/room_summary.py
- tests/handlers/test_room_summary.py
Different users may be allowed to see different rooms within a space,
so sharing responses between users is inadvisable.
> Avoid sharing room hierarchy responses between users

- changelog.d/11368.misc
- scripts-dev/complement.sh
By reverting changes from #11166 in this script. Specifically commit 13f084eb58c379b2fc073680818d5931e94626f4.
Fixes #11362
> Fix running complement.sh script.

- changelog.d/11369.misc
- synapse/handlers/auth.py
- synapse/handlers/register.py
- synapse/rest/admin/users.py
- tests/handlers/test_auth.py
- tests/rest/admin/test_user.py
- tests/rest/client/test_capabilities.py
This one was a little bit confusing and I'm not a fan of conflating 'getting' with 'creating', especially around authentication code.
> Rename `get_access_token_for_user_id` method to `create_access_token_for_user_id`

- changelog.d/11381.doc
- docs/sample_config.yaml
- synapse/config/tls.py
Otherwise I get this beautiful stacktrace:
```
python3 -m synapse.app.homeserver --config-path /etc/matrix/homeserver.yaml
File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/root/synapse/synapse/app/homeserver.py", line 455, in <module>
main()
File "/root/synapse/synapse/app/homeserver.py", line 445, in main
hs = setup(sys.argv[1:])
File "/root/synapse/synapse/app/homeserver.py", line 345, in setup
config = HomeServerConfig.load_or_generate_config(
File "/root/synapse/synapse/config/_base.py", line 671, in load_or_generate_config
config_dict = read_config_files(config_files)
File …
```
> Docs: Quote wildcard `federation_certificate_verification_whitelist`

- changelog.d/11324.feature
- docs/admin_api/rooms.md
- synapse/rest/admin/__init__.py
- synapse/rest/admin/rooms.py
- synapse/storage/databases/main/room.py
- tests/rest/admin/test_room.py
Fix some parts of #11283
Add new admin API:
- `GET /_synapse/admin/v1/rooms/<room_id>/block`
- `PUT /_synapse/admin/v1/rooms/<room_id>/block`
I am not sure what is the best http method. `POST` vs. `PUT`
> Add dedicated admin API for blocking a room

- changelog.d/11333.misc
- synapse/config/emailconfig.py
- synapse/config/registration.py
- synapse/handlers/identity.py
- tests/config/test_load.py
Fixes #10545. As the title says, removes code associated with handling the deprecated config option, and Synapse refuses to start if this flag is set in the config.
> Remove legacy code related to deprecated `trust_identity_server_for_password_resets` config flag

- changelog.d/11265.bugfix
- synapse/appservice/api.py
- synapse/handlers/room_batch.py
- synapse/handlers/room_member.py
Prevent historical state from being pushed to an application service via `/transactions`. We now mark historical state from the MSC2716 `/batch_send` endpoint as `historical` which makes it `backfilled` and have a negative `stream_ordering` so it doesn't get queried by `/transactions`.
Fix https://github.com/matrix-org/synapse/issues/11241
Complement tests: https://github.com/matrix-org/complement/pull/221
Part of MSC2716: https://github.com/matrix-org/matrix-doc/pull/2716
```
update_membership
update_membership_locked
_local_membership_update
create_event
create_and_send_nonmember_event
create_event
```
`/sync` looks for `stream_ordering` but excludes all `outliers`.
https://github.com/matrix-org/synapse/blob/b09d90cac9179f84024d4cb3ab4574480c1fd1df/synapse/storage/databases/main/stream.p …
> Prevent historical state from being pushed to an application service via `/transactions` (MSC2716)

- changelog.d/11379.bugfix
- synapse/crypto/keyring.py
- tests/crypto/test_keyring.py
Fixes a bug introduced in #11129: objects signed by the local server, but with keys other than the current one, could not be successfully verified.
We need to check the key id in the signature, and track down the right key.
Fixes: #11373
> Fix verification of objects signed with old local keys

- .github/workflows/docker.yml
- changelog.d/11380.misc
I'd find it helpful to have a docker image corresponding to current develop, without having to build my own.
> Publish a `develop` docker image

- changelog.d/11382.misc
- synapse/storage/databases/main/end_to_end_keys.py
- tests/handlers/test_e2e_keys.py
This prevents the following situation:
- client uploads a fallback key.  Network dies, and client doesn't get acknowledgement that the upload succeeded, even though it did
- someone does a `keys/claim` and the fallback key gets marked as used
- client comes back later and tries to re-upload the key
- the key gets replaced and marked as unused
- the client doesn't get notified that the key was used, because the server thinks it is unused
This PR changes the behaviour so that it compares the uploaded key with the existing key, and if it's the same, it doesn't touch it.  Notably, this means that the key will remain marked as used, so that the client will get notified in the `/sync` that it needs to upload a new key.
- Be a short description of your change which makes sense to users. "Fixed a …
> Keep fallback key marked as used if it's re-uploaded

- changelog.d/11393.misc
- synapse/config/tls.py
I believe this should have been part of #10194. The only commits reference it are from #4384 and #10194. There's no current callers.
> Remove dead code from acme support.

- changelog.d/11392.bugfix
- synapse/config/room_directory.py
- synapse/handlers/room.py
- tests/handlers/test_directory.py
#7260 attempted to fix this, but the check was not correct, I'm actually surprised this hasn't caused an errors to appear anywhere, they would be of the form:
`TypeError: 'RoomAlias' object is not iterable`
> Fix checking whether a room can be published on creation.

- changelog.d/11352.feature
- docs/sample_config.yaml
- docs/usage/administration/admin_api/background_updates.md
- docs/user_directory.md
- synapse/config/user_directory.py
- synapse/rest/admin/__init__.py
- synapse/rest/admin/background_updates.py
- synapse/storage/background_updates.py
- tests/rest/admin/test_background_updates.py
Fixes: #8246
Related to: #8128
Add API to run predefined background jobs to prevent admins to poke in DB.
`POST /_synapse/admin/v1/background_updates/start_job`
> Add admin API to run background jobs

- changelog.d/11408.misc
- synapse/events/utils.py
- synapse/handlers/events.py
- synapse/handlers/message.py
- synapse/rest/admin/rooms.py
- synapse/rest/client/relations.py
- synapse/rest/client/room.py
- synapse/rest/client/sync.py
Spun out of #11284 to separate refactoring from new behavior.
The main goal of this was to have the relation bundling code be a separate method. It also clarifies some of the terminology used [MSC2675](https://github.com/matrix-org/matrix-doc/pull/2675) isn't clear about what to call these, so I chose "bundled relations" which I think is the clearer of the two options).
This also updates some comments and minor other refactorings. Should be reviewable commit-by-commit.
> Bundled relations refactoring

- changelog.d/11356.misc
- synapse/api/constants.py
This change makes mypy complain if the constants are ever reassigned,
and, more usefully, makes mypy type them as `Literal`s instead of `str`s,
allowing code of the following form to pass mypy:
```py
def do_something(membership: Literal["join", "leave"], ...): ...
do_something(Membership.JOIN, ...)
```
-----------------------------------------------------
I tried @DMRobertson 's suggestion of `StrEnums`, but we `sys.intern` bits of event JSON in various places, which raises when it encounters enums. And having dict keys sometimes be strings and sometimes be enum values defeats the purpose of interning. …
> Annotate string constants in `synapse.api.constants` with `Final`

- changelog.d/11376.bugfix
- synapse/storage/databases/main/events_worker.py
- tests/storage/databases/main/test_events_worker.py
The previous fix for the ongoing event fetches counter
(8eec25a1d9d656905db18a2c62a5552e63db2667) was both insufficient and
incorrect.
When the database is unreachable, `_do_fetch` never gets run and so
`_event_fetch_ongoing` is never decremented.
The previous fix also moved the `_event_fetch_ongoing` decrement outside
of the `_event_fetch_lock` which allowed race conditions to corrupt the
counter.
Fixes #11167
> Track ongoing event fetches correctly (again)

- changelog.d/11429.docker
- docker/Dockerfile-workers
- docker/conf-workers/healthcheck.sh.j2
- docker/configure_workers_and_start.py
Currently the healthcheck will never succeed as nginx does not route /health anywhere.
If it was routed to the main process, then the container could report healthy but one of the workers not be started yet, causing failures.
The intent is to iterate through all the worker ports and only report healthy when all are healthy, starting with the main process.
(run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_ …
> Create healthcheck script for synapse-workers container.

- changelog.d/11439.bugfix
- synapse/python_dependencies.py
Since e81fa9264873369653171157514ff68226491fff, Synapse depends on
the use_float flag which has been introduced in ijson 3.1 and
is not available in 3.0. This is known to cause runtime errors
with send_join.
> Bump ijson dependency to 3.1 (#11438)

- changelog.d/11441.misc
- mypy.ini
- tests/federation/transport/test_client.py
This would have caught the bug #11438 introduced in #11217 and fixed in #11439. I confirmed this by `pip install ijson==3.0`, running the test and seeing a failure.
> Add a test case for the SendJoinParser

- changelog.d/11029.misc
- mypy.ini
- synapse/module_api/__init__.py
Resurrected this from about a month ago. Merge wasn't too bad.
> disallow-untyped-defs for the module_api

- changelog.d/11440.bugfix
- synapse/crypto/keyring.py
- tests/crypto/test_keyring.py
If we tried to request multiple keys for the same server, we would end up dropping some of those requests, which would then cause errors like `Auth events could not be found` when trying to join rooms.
Introduced in #10035.
> Fix perspectives requests for multiple keys for the same server

- changelog.d/11415.doc
- docs/media_repository.md
> Update the media repository documentation

- changelog.d/11417.misc
- synapse/storage/databases/main/events.py
- synapse/storage/persist_events.py
Refactor backfilled into specific behavior function arguments (`_persist_events_and_state_updates`)
Using keyword-only arguments (`*`) to reduce the mistakes from `backfilled` being left as a positional argument somewhere and being interpreted wrong by our new arguments.
Part of #11300
Split-off from https://github.com/matrix-org/synapse/pull/11396
Call stack:
- `_persist_events_and_state_updates` (added `use_negative_stream_ordering`)
- `_persist_events_txn`
- `_update_room_depths_txn`
- `_update_metadata_tables_txn`
- `_store_room_members_txn` (added `inhibit_local_membership_updates`) …
> Refactor `backfilled` into specific behavior function arguments (`_persist_events_and_state_updates`)

- changelog.d/11452.misc
- synapse/rest/admin/__init__.py
- synapse/rest/admin/_base.py
- synapse/rest/admin/devices.py
- synapse/rest/admin/event_reports.py
- synapse/rest/admin/groups.py
- synapse/rest/admin/media.py
- synapse/rest/admin/registration_tokens.py
- synapse/rest/admin/rooms.py
- synapse/rest/admin/server_notice_servlet.py
- synapse/rest/admin/statistics.py
- synapse/rest/admin/users.py
No functional changes
Only code cleanup
> Convert status codes to `HTTPStatus` in `synapse.rest.admin`

- changelog.d/11455.misc
- tests/rest/admin/test_admin.py
- tests/rest/admin/test_background_updates.py
- tests/rest/admin/test_device.py
- tests/rest/admin/test_event_reports.py
- tests/rest/admin/test_media.py
- tests/rest/admin/test_registration_tokens.py
- tests/rest/admin/test_room.py
- tests/rest/admin/test_server_notice.py
- tests/rest/admin/test_statistics.py
- tests/rest/admin/test_user.py
- tests/rest/admin/test_username_available.py
No functional changes
Only code cleanup
Related to: #11452
> Convert status codes to `HTTPStatus` in `tests.rest.admin`

- changelog.d/11409.misc
- docs/templates.md
- synapse/push/emailpusher.py
- synapse/push/httppusher.py
- synapse/push/mailer.py
- synapse/push/push_types.py
- synapse/storage/databases/main/event_push_actions.py
I had started this quite a bit ago but never got around to submitting but I thought it might still be useful to have this.
I'm unhappy with a few bits, so maybe someone has a better idea on how to model this, I'll add specific comments inline.
> Improved push typing

- changelog.d/11459.feature
- synctl
If you're trying to shut down Synapse, it's rather handy if it *actually* shuts
down before you move on.
> synctl stop: wait for processes to exit

- changelog.d/11461.misc
- tests/rest/admin/test_room.py
No functional changes
Only code cleanup
> Remove not needed `json.dumps` from `tests.rest.admin`

- changelog.d/11453.misc
- synapse/util/caches/deferred_cache.py
- synapse/util/caches/lrucache.py
- synapse/util/linked_list.py
`Any`s make IDE navigation difficult, so let's get rid of them.
> Eliminate a few `Any`s in `LruCache` type hints

- changelog.d/11454.bugfix
- synapse/util/caches/lrucache.py
- tests/util/test_lrucache.py
When all entries in an `LruCache` have a size of 0 according to the
provided `size_callback`, and `drop_from_cache` is called on a cache
node, the node would be unlinked from the LRU linked list but remain in
the cache dictionary. An assertion would be later be tripped due to the
inconsistency.
Avoid unintentionally calling `__len__` and use a strict `is None`
check instead when unwrapping the weak reference.
Fixes #11436
> Fix `LruCache` corruption bug with a `size_callback` that can return 0

- changelog.d/11449.feature
- setup.py
- synapse/app/generic_worker.py
This exposes `worker` & `synapse` as executables using the [`entry_points`](https://setuptools.pypa.io/en/latest/userguide/entry_point.html)-feature of `setup.py`.
This change is used by the `matrix-synapse`-package in `nixpkgs` to automatically install `worker` & `homeserver` into `$out/bin` to make them available in the output-path of the package. This change only affects `generic_worker.py` since all other workers seem to call `generic_worker.py` and everything else happens based on the worker's configuration.
Not sure if that's useful to you, but I thought I'd file these patches anyways :)  …
> Expose worker & homeserver as entrypoints in `setup.py`

- changelog.d/11416.misc
- synapse/app/homeserver.py
- tests/app/test_homeserver_start.py
Fixes #11366. Basically checks to ensure that if you are starting Synapse via `synapse.app.homeserver` that you don't have `worker_app` set in the config and refuses to start if so.
> Don't start Synapse master process if `worker_app` is set

- changelog.d/11467.misc
- docs/postgres.md
> Add a note about huge pages to our Postgres doc

- docs/openid.md
Dex [isn't](https://github.com/dexidp/dex/issues/42) [yet](https://github.com/dexidp/dex/issues/262) a certified OpenID Provider implementation. As of today, it's not on the [list maintained by the OpenID Foundation](https://openid.net/certification/).
> Remove mention of OIDC certification from Dex

- changelog.d/11451.bugfix
- synapse/rest/client/login.py
- synapse/rest/client/room.py
This is a follow-up to #11318 which registers the login redirect endpoint for v3 since it doesn't use `client_patterns`.
There are a variety of other places that `/r0` is mentioned in our code, some of those are places where Synapse generates a URL back to itself (e.g. login fallback, SSO redirect URLs, etc.) We don't *have* to update those today, but we should eventually.
Part of #11079
> Register the login redirect endpoint for v3

- changelog.d/11465.misc
- synapse/app/_base.py
- synapse/config/__main__.py
- synapse/config/appservice.py
- synapse/config/cache.py
- synapse/config/cas.py
- synapse/config/database.py
- synapse/config/logger.py
- synapse/config/oidc.py
- synapse/config/registration.py
- synapse/config/repository.py
- synapse/config/saml2.py
- synapse/config/server.py
- synapse/config/sso.py
- synapse/config/workers.py
Adds some missing type hints to `synapse.config` on my journey to fully type it.
It will be several more PRs before that's done, unfortunately.
> Additional type hints for config module.

- changelog.d/11475.feature
- docs/SUMMARY.md
Looks like I forgot to do that in #11306
> Link background update controller docs to summary

- changelog.d/11468.misc
- synapse/util/versionstring.py
This cleans-up `get_version_string` a bit by factoring out common-code, fixing up some types and explicitly closing `/dev/null` (instead of assuming garbage collection will do it).
Note that this code is also shared by sydent so we might want to move it out at some point.
> Clean-up get_version_string

- changelog.d/11490.feature
- synctl
> Avoid waiting for zombie processes in `synctl stop`

- changelog.d/11483.misc
- mypy.ini
- synapse/federation/federation_client.py
- synapse/federation/federation_server.py
- synapse/federation/persistence.py
- synapse/federation/send_queue.py
- synapse/federation/sender/per_destination_queue.py
- synapse/federation/transport/client.py
- synapse/federation/transport/server/__init__.py
- synapse/federation/transport/server/_base.py
This adds most of the missing type hints to `synapse.federation`, but skips a few methods which are dicey. I think those can be done in a follow-up since this PR became decent sized and it is better to get the partial type hints in then to have none at all.
> Add most of the missing type hints to `synapse.federation`.

- changelog.d/11494.misc
- synapse/handlers/sync.py
- synapse/storage/databases/main/stream.py
Recommend commit-by-commit review.
> Comments on the /sync tentacles

- changelog.d/11501.misc
- mypy.ini
- tests/rest/admin/test_background_updates.py
- tests/rest/admin/test_device.py
- tests/rest/admin/test_event_reports.py
- tests/rest/admin/test_media.py
- tests/rest/admin/test_registration_tokens.py
- tests/rest/admin/test_room.py
- tests/rest/admin/test_server_notice.py
- tests/rest/admin/test_statistics.py
- tests/rest/admin/test_user.py
> Add type hints to `synapse/tests/rest/admin`

- changelog.d/11445.feature
- synapse/config/registration.py
- synapse/handlers/register.py
- tests/config/test_registration_config.py
- tests/rest/client/test_auth.py
Precursor to #11435 (which stabilises refresh tokens and documents these configuration flags).
`nonrefreshable_access_token_lifetime` is introduced as a configuration option so that homeserver admins can prevent bypassing auto-logout through the use
of clients that don't advertise support for refresh tokens.
> Support configuring the lifetime of non-refreshable access tokens separately to refreshable access tokens.

- changelog.d/11469.doc
- docs/development/room-dag-concepts.md
Update backward extremity docs to make it clear that it does not indicate whether we have fetched an events' `prev_events`.
This update was spawned by this discussion: https://github.com/matrix-org/synapse/pull/9445#discussion_r758958181
Follow-up to https://github.com/matrix-org/synapse/pull/10464 where the `room-dag-concepts.md` developer docs were first added.
(run the [linters](https://matrix-org.github.io/synapse/latest/development/contr …
> Update backward extremity docs to make it clear that it does not indicate whether we have fetched an events' `prev_events`

- changelog.d/11407.feature
- docs/SUMMARY.md
- docs/usage/administration/admin_api/federation.md
- synapse/rest/admin/__init__.py
- synapse/rest/admin/federation.py
- synapse/storage/databases/main/transactions.py
- tests/rest/admin/test_federation.py
Related to: #7982
Add `GET /_synapse/admin/v1/federation/destinations` to get some information to federation status.
> Add admin API to get some information about federation status

- changelog.d/11482.misc
- synapse/handlers/auth.py
- synapse/handlers/device.py
- synapse/handlers/oidc.py
- synapse/handlers/register.py
- synapse/handlers/sso.py
- synapse/module_api/__init__.py
- synapse/replication/http/login.py
- synapse/rest/client/login.py
- synapse/storage/databases/main/devices.py
- synapse/storage/schema/main/delta/65/11_devices_auth_provider_session.sql
- synapse/storage/schema/main/delta/65/11_devices_oidc_session.sql
- tests/handlers/test_auth.py
- tests/handlers/test_cas.py
- tests/handlers/test_oidc.py
- tests/handlers/test_saml.py
> Save the OIDC session ID (sid) with the device on login

- changelog.d/11435.feature
- docs/sample_config.yaml
- synapse/config/registration.py
- synapse/rest/client/login.py
- synapse/rest/client/register.py
- tests/rest/client/test_auth.py
Also documents the config options, which is one of the crucial parts of stabilising a feature :).
> Stabilise support for MSC2918 refresh tokens as they have now been merged into the Matrix specification.

- changelog.d/11522.feature
- tests/rest/client/test_auth.py
Typical story, one of the PRs changed something that needed tests changing,
another PR had a test added because 'this needs more tests!'
and oops.
Sorry :)
> Fix the test breakage introduced by #11435 as a result of concurrent PRs

- changelog.d/11511.bugfix
- synapse/handlers/sync.py
Fixes #11506. Corresponding test case at matrix-org/complement#267.
> Correctly ignore invites from ignored users

- changelog.d/11523.feature
- synapse/handlers/pagination.py
- synapse/handlers/room.py
- synapse/rest/admin/rooms.py
- tests/rest/admin/test_room.py
If, for some reason, we don't have the create event, we should still be able to purge a room.
Fixes #6547.
> Fix 'delete room' admin api to work on incomplete rooms

- changelog.d/11494.misc
- changelog.d/11515.misc
- synapse/handlers/sync.py
Small things that helped me when I was reading all of this stuff.
- 0af0643c7 is probably the most useful.
- f9dff2d60 and 963de4e5c pull out isolated chunks of code into their own functions.
- 0e2c6f6fc: I'm not sure if this makes things clearer or just introduces more noise. Input welcome.
> Refactors in `_generate_sync_entry_for_rooms`

- changelog.d/11505.misc
- changelog.d/11527.misc
- synapse/config/room_directory.py
- synapse/config/tls.py
- synapse/federation/federation_server.py
- synapse/push/push_rule_evaluator.py
- synapse/python_dependencies.py
- synapse/util/__init__.py
- tests/util/test_glob_to_regex.py
This reverts commit a77c36989785c0d5565ab9a1169f4f88e512ce8a.
Our downstream package maintainers need more notice before adding a new package.
To be revisited in the new year.
> Revert "Move `glob_to_regex` and `re_word_boundary` to `matrix-python-common` (#11505)

- changelog.d/11536.misc
- synapse/storage/databases/main/state_deltas.py
- synapse/storage/util/id_generators.py
Somehow I'd managed to get my database in a pickle with stream ids. These changes were useful to debug.
> Improve log messages for stream ids

- changelog.d/11520.misc
- tests/rest/client/test_auth.py
> Use HTTPStatus constants in place of literals in `tests.rest.client.test_auth`.

- changelog.d/11535.misc
- synapse/rest/admin/__init__.py
- synapse/rest/admin/background_updates.py
- synapse/rest/admin/devices.py
- synapse/rest/admin/event_reports.py
- synapse/rest/admin/federation.py
- synapse/rest/admin/groups.py
- synapse/rest/admin/media.py
- synapse/rest/admin/registration_tokens.py
- synapse/rest/admin/rooms.py
- synapse/rest/admin/server_notice_servlet.py
- synapse/rest/admin/statistics.py
- synapse/rest/admin/username_available.py
- synapse/rest/admin/users.py
- tests/rest/admin/test_statistics.py
No functional changes
Only code cleanup
- harmonize `PATTERNS`
- there are `PATTERNS` with and without trailing `$`
- there are `PATTERNS` with `[^/]+` and `[^/]*`
- replace
```
requester = await self._auth.get_user_by_req(request)
await assert_user_is_admin(self._auth, requester.user)
```
with `await assert_requester_is_admin(self._auth, request)` if `requester` is not needed
- remove not needed `self.hs = hs`
- use `allowed_values` of `parse_string`
- Start with a …
> Clean up `synapse.rest.admin`

- changelog.d/11531.misc
- synapse/api/constants.py
- synapse/handlers/receipts.py
- synapse/handlers/sync.py
- synapse/push/push_tools.py
- synapse/rest/client/notifications.py
- synapse/rest/client/read_marker.py
- synapse/rest/client/receipts.py
- synapse/storage/databases/main/receipts.py
Trying to get a bit familiar with the receipts code, figured I would:
* Add a constant for `m.read`.
* Finish up some missing type hints.
> Add receipt types constant

- changelog.d/11378.feature
- synapse/rest/client/room.py
This PR implements part of https://github.com/matrix-org/matrix-doc/pull/3419 needed to make group calls work. I have no idea if this is the proper way to do this and MSC3419 also has requirements to allow for more guest event types if they have the permission to do so. So we probably want to have a bigger discussion around this.
(run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linters …
> Allow guests to send state events

- changelog.d/11542.misc
- synapse/http/servlet.py
- tests/rest/admin/test_federation.py
- tests/rest/admin/test_media.py
- tests/rest/admin/test_statistics.py
- tests/rest/admin/test_user.py
Follow up to https://github.com/matrix-org/synapse/pull/11535#discussion_r764994933
> Add missing `errcode` to `parse_string` and `parse_boolean`

- changelog.d/11541.misc
- synapse/handlers/e2e_keys.py
- synapse/rest/client/sync.py
- tests/handlers/test_e2e_keys.py
Since FCP is complete on the MSC, we can use the unprefixed names now.
> Support unprefixed versions of fallback key property names.

- changelog.d/11480.misc
- synapse/config/key.py
- synapse/config/metrics.py
- synapse/config/server.py
- synapse/config/tls.py
Builds on #11465 to add a few more missing type hints in helpers, etc.
After this the only untyped things in `synapse.config` should be each classes `read_config` and `generate_config_section` methods. I have some WIPs for those to make the parameter explicit and such, so they're a bit more work.
> Additional type hints for config module, part 2.

- changelog.d/11516.bugfix
- synapse/events/utils.py
- synapse/rest/client/relations.py
- synapse/storage/databases/main/events.py
- synapse/storage/databases/main/relations.py
- tests/rest/client/test_relations.py
Due to some vagueness in [MSC2674](https://github.com/matrix-org/matrix-doc/pull/2674) Synapse could return some incorrect data. This updates our implementation to match the merged version of MSC2674, namely that it states an event and its relations must be in the same room.
> Do not allow cross-room relations, per MSC2674.

- changelog.d/11547.bugfix
- synapse/push/pusherpool.py
- synapse/storage/databases/main/monthly_active_users.py
- synapse/storage/databases/main/registration.py
- tests/rest/admin/test_user.py
Updates two callers of `get_user_id_by_threepid` to canonicalize the email argument. I audited other callers and ensured that they were fine (by calling `canonicalise_email` or `validate_email`).
Fixes #11458
> Ensure emails are canonicalized before fetching associated user.

- changelog.d/11558.misc
- synapse/storage/databases/main/events.py
- synapse/storage/schema/__init__.py
this field is never read, so we may as well stop populating it.
> Stop populating `state_events.prev_state`

- changelog.d/11560.misc
- synapse/storage/database.py
- synapse/storage/databases/main/events.py
This creates something I've been after for a while, which is a database helper method like `simple_insert_many`, but which takes raw row values, rather than {key=>value} dicts.
This saves us a bunch of dict munging and safety-checking, and makes it easier to use generators rather than creating intermediate lists and dicts.
> skip some dict munging in event persistence

- changelog.d/11550.misc
- synapse/handlers/sync.py
C.f. https://github.com/matrix-org/synapse/pull/11494#pullrequestreview-827780886
> Adjust _get_rooms_changed comments

- changelog.d/11487.misc
- tests/rest/client/test_room_batch.py
Test to ensure we share the same `state_group` across the whole historical batch.
Part of MSC2716: https://github.com/matrix-org/matrix-doc/pull/2716
We did some work on making sure the `state_groups` were shared in https://github.com/matrix-org/synapse/pull/10975 and I don't want to regress.
It also helps me test the details of this statement: https://github.com/matrix-org/synapse/pull/11243/files#discussion_r750819703
```
SYNAPSE_POSTGRES=1 SYNAPSE_TEST_LOG_LEVEL=INFO python -m twisted.trial tests.rest.client.test_room_batch
```
- Use markdown where necessary, mostly for `code …
> Test to ensure we share the same `state_group` across the whole historical batch (MSC2716)

- changelog.d/11546.misc
- mypy.ini
- synapse/storage/databases/main/account_data.py
- synapse/storage/databases/main/tags.py
> Add type hints to `synapse/storage/databases/main/account_data.py`

- changelog.d/11566.misc
- synapse/rest/media/v1/oembed.py
- synapse/rest/media/v1/preview_html.py
- synapse/rest/media/v1/preview_url_resource.py
- tests/rest/media/v1/test_url_preview.py
- tests/test_preview.py
This is an internal refactor to:
* Split out the HTML parsing code from the resource code by moving it to a separate file. (Brings a ~1k LOC file to ~600 LOC.)
* Fix a circular import in the oEmbed code (which uses the HTML parsing code).
* Renames some of the HTML parsing methods to:
* Make it clear which methods are "internal" to the module.
* Clarify what the methods do.
> Move HTML parsing to a separate file for URL previews.

- changelog.d/11564.misc
- synapse/storage/database.py
- synapse/storage/databases/main/presence.py
A couple of safety-checks to hopefully stop people doing what I just did, and create a storage function which only works the first time it is called (and not when it is re-run due to a database concurrency error or similar). It's not water-tight, of course, but it should catch the most obvious failure modes.
Ideally, I'd have this throw a ValueError or somesuch, but I'm a bit worried it'll break existing code that I haven't yet found, so for now at least, let's just log an error.
Also fixes up a particular case that I discovered during testing. In theory this is bug which could have caused us to send fewer presence updates than we should have done. In practice, it's such an edge-case I can't really imagine anyone will ever have hit it.
> checks for generators in database functions

- changelog.d/11571.misc
- mypy.ini
- synapse/http/__init__.py
- synapse/http/additional_resource.py
- synapse/http/server.py
- synapse/http/servlet.py
- synapse/http/site.py
- synapse/rest/key/v2/local_key_resource.py
This starts adding some missing type hints to `synapse.http`. There's still quite a bit to do but wanted to continue making baby steps!
I wasn't sure if I should add these to `mypy.ini` or not, but listing individual files seems painful.
> Add missing type hints to synapse.http.

- changelog.d/11574.misc
- synapse/handlers/events.py
- synapse/notifier.py
I was attempting to convince myself that `serialize_events` never took a `JsonDict` and only ever received `EventBase` instances...well turns out it does take them via the event streams.
I fixed up some of the types around this to use `attrs` instead of a `namedtuple` to avoid `Any` being passed around.
Vaguely related to #11399 since that spurred the original work.
> Convert EventStreamResult to attrs.

- changelog.d/11575.misc
- mypy.ini
- synapse/handlers/room_member.py
- synapse/storage/databases/main/__init__.py
- synapse/storage/databases/main/room.py
> Add type hints to `synapse/storage/databases/main/room.py`

- changelog.d/11582.misc
- synapse/config/experimental.py
- synapse/rest/client/versions.py
Add MSC2716 and MSC3030 to `/versions` -> `unstable_features` to detect server support.
As suggested in https://github.com/matrix-org/matrix-react-sdk/pull/7372#discussion_r769523369
> Add MSC2716 and MSC3030 to `/versions` -> `unstable_features`

- changelog.d/11589.misc
- mypy.ini
- synapse/storage/databases/main/transactions.py
> Add type hints to `synapse/storage/databases/main/transactions.py`

- changelog.d/11603.misc
- mypy.ini
- setup.py
- synapse/logging/opentracing.py
- synapse/logging/scopecontextmanager.py
This one was a little tricky due to the conditional import. After some consultation it was decided it was prudent to ignore the case where `opentracing` is set to `None`, rather than doing a larger refactor that is difficult to test. Happy to do it a different way but I figure this way would allow the types to be used and still checks that we are using `opentracing` correctly in this file, and doesn't involve a non-negligible refactor.
> Add opentracing types

- changelog.d/11602.bugfix
- synapse/app/homeserver.py
- synapse/http/server.py
- synapse/util/httpresourcetree.py
Fixes #11600 by returning JSON errors with CORS for unknown URLs from prefixes.
You can test this before/after this change via:
```bash
$ curl http://localhost:8080/_matrix/client/v2/foo
$ curl -vv -X OPTIONS http://localhost:8080/_matrix/client/v2/foo
$ curl http://localhost:8080/_matrix/client/v2/
$ curl http://localhost:8080/_matrix/client/
```
These now all return something like:
```json
{"errcode":"M_UNRECOGNIZED","error":"Unrecognized request"}
```
instead of:
```html
<html>
<head><title>404 - No Such Resource</title></head>
<body>
<h1>No Such Resource</h1>
<p>Sorry. No luck finding that resource.</p>
</body>
</html>
```
> Return JSON errors instead of HTML errors for unknown resources. 

- changelog.d/11618.misc
- synapse/federation/transport/server/_base.py
- synapse/http/site.py
- synapse/logging/opentracing.py
The main point of this PR is to ensure that the opentracing span for an incoming HTTP request stays open until we *really* finish dealing with it (including encoding the response and sending back the resultant bytes).
Doing so requires a bit of refactoring, to make `SynapseRequest` responsible for closing the span, as well as removing some redundant stuff from the federation handler.
Also adds a bit of extra opentracing logging for the stages of handling a request.
Suggest reviewing commit-by-commit.
> Improve opentracing for incoming HTTP requests

- changelog.d/11607.misc
- synapse/handlers/room.py
- synapse/util/async_helpers.py
- synapse/util/caches/response_cache.py
- tests/util/caches/test_response_cache.py
This adds some opentracing annotations to `ResponseCache`, to make it easier to see what's going on; in particular, it adds a link back to the initial trace which is actually doing the work of generating the response.
Since I was refactoring a bit of `ResponseCache` anyway, I also made a start on #11390 by factoring out an AbstractObservableDeferred.
Reviewable commit-by-commit (ish; c302d9389 has some important fixes to 
0d1dcb9)
> Improve opentracing support for `ResponseCache`

- changelog.d/11619.misc
- synapse/api/auth.py
- synapse/handlers/sync.py
- synapse/http/server.py
- synapse/rest/client/sync.py
This is a grab-bag of extra opentracing spans around the codebase, created in the process of debugging #11611.
Review commit-by-commit.
> Various opentracing enhancements

- changelog.d/11594.misc
- mypy.ini
- synapse/handlers/sync.py
- synapse/push/emailpusher.py
- synapse/push/httppusher.py
- synapse/push/mailer.py
- synapse/push/push_tools.py
- synapse/rest/client/notifications.py
- synapse/storage/databases/main/event_push_actions.py
- tests/replication/slave/storage/test_events.py
- tests/storage/test_event_push_actions.py
I was taking a look at notification counts and got a bit side tracked adding type hints...I figured I should finish them up.
This is broken into 3 commits, the first adds type hints and the subsequent ones switch from `TypedDict` to `attrs` since the return values don't need to be dicts for any reason.
> Add type hints to event_push_actions.

- changelog.d/11503.misc
- tests/server.py
- tests/storage/test_base.py
- tests/storage/test_roommember.py
- tests/utils.py
Only `tests.server.setup_test_homeserver` is called by anything at the moment
(all users of the one from `tests.util` have been *removed* in 3 prior PRs)
> Refactor `tests.util.setup_test_homeserver` and `tests.server.setup_test_homeserver`.

- .github/workflows/tests.yml
- changelog.d/11595.misc
- tox.ini
As the title states. Drops python 3.6 and postgres 9.6 from the CI and removes the python 3.6 environment from tox.
> Drop EOL python 3.6 from CI

- changelog.d/11553.doc
- docs/turn-howto.md
Signed-off-by: Andrew Ferrazzutti <fair@miscworks.net>
* (Not sure if this is required, since this is only a documentation change. I did run `mdbook build` and `mdbook serve` with no issues, however.)
> Add details for how to set up TURN behind NAT

- changelog.d/11622.misc
- synapse/logging/opentracing.py
On `develop` I was getting an error with mypy:
```
synapse/logging/opentracing.py:224: error: Module has no attribute "tags"  [attr-defined]
synapse/logging/opentracing.py:587: error: Module has no attribute "tags"  [attr-defined]
```
I think this is due to the `tags` module under `opentracing` not being imported anywhere, but used. This generally works, but is poor form.
> Fix mypy error with opentracing.tags.

- changelog.d/11596.misc
- pyproject.toml
- setup.py
- synapse/logging/context.py
- synapse/util/caches/lrucache.py
As the title states. Part of the cleanup from dropping Python 3.6: #11552.
> Update to the current version of Black and run it on Synapse codebase

- changelog.d/11653.misc
- mypy.ini
- synapse/storage/databases/main/stats.py
> Add type hints to `synapse/storage/databases/main/stats.py`

- changelog.d/11623.bugfix
- synapse/handlers/message.py
I made a minor mistake in #11592 where it requested to bundle aggregations when fetching the room state for `/members` and `/state` -- the bundled aggregations wouldn't actually get added ([since we don't include them for state events](https://github.com/matrix-org/synapse/blob/dd4778875213d9cb8be7ee71d32751fbd6cdaba2/synapse/events/utils.py#L430)), but it means that we're "opting-in" to something that makes no sense for the APIs.
> Do not attempt to bundled aggregations for /members and /state.

- changelog.d/11652.misc
- synapse/storage/databases/main/deviceinbox.py
- synapse/storage/databases/main/event_federation.py
- synapse/storage/databases/main/event_push_actions.py
- synapse/storage/databases/main/filtering.py
- synapse/storage/databases/main/media_repository.py
- synapse/storage/databases/main/pusher.py
- synapse/storage/databases/main/registration.py
- synapse/storage/databases/main/relations.py
- synapse/storage/databases/main/ui_auth.py
> Update some type hints in storage classes

- changelog.d/11657.misc
- mypy.ini
- tests/storage/test_account_data.py
Just a tiny one that I spotted when thinking about editing this file (though I later didn't anyway...).
> Fix a type annotation in `test_account_data.py` and remove it from the Mypy exclusion list.

- changelog.d/11654.misc
- mypy.ini
- synapse/storage/databases/main/events_bg_updates.py
> Add type hints to `synapse/storage/databases/main/events_bg_updates.py`

- changelog.d/11665.misc
- synapse/api/filtering.py
- synapse/config/repository.py
- synapse/federation/federation_base.py
- synapse/federation/send_queue.py
- synapse/handlers/appservice.py
- synapse/handlers/directory.py
- synapse/handlers/room_list.py
- synapse/handlers/typing.py
- synapse/http/server.py
- synapse/replication/tcp/streams/_base.py
- synapse/replication/tcp/streams/federation.py
- synapse/rest/media/v1/media_repository.py
- synapse/state/__init__.py
- synapse/storage/databases/main/directory.py
- synapse/storage/databases/main/events.py
- synapse/storage/databases/main/room.py
- synapse/storage/databases/main/search.py
- synapse/storage/databases/main/state.py
- synapse/storage/databases/main/stream.py
- synapse/types.py
- tests/replication/test_federation_ack.py
This converts an instances of `namedtuples` to `attrs`. The main benefit of this is that it gives you type hints. I had to fix a couple of things along the way. Should be reviewable commit-by-commit.
> Convert all namedtuples to attrs.

- changelog.d/11633.misc
- docker/Dockerfile-dhvirtualenv
- scripts-dev/build_debian_packages
- setup.py
Related to #11552, stops building bionic, updates the `dh-virtualenv` (which we can do now that we have dropped bionic) and updates Trove classifier to indicate that we have dropped support for EOL python 3.6.
> Drop Bionic from Debian builds 

- changelog.d/11666.feature
- docs/sample_config.yaml
- synapse/config/api.py
- tests/federation/transport/test_knocking.py
[MSC3173](https://github.com/matrix-org/matrix-doc/pull/3173) suggests that the topic of a room should be included in the prejoin state. Synapse does not currently do this, but it is easy enough to include it.
> Include the topic event in the prejoin state, per MSC3173.

- changelog.d/11638.misc
- synapse/storage/databases/main/state.py
"Unknown room" can mean a multitude of things here. To help with debugging, add
some more words to the exception text.
> Better error messages from `get_create_event_for_room`

- changelog.d/11643.misc
- synapse/handlers/federation_event.py
- synapse/handlers/presence.py
- synapse/replication/slave/storage/events.py
- synapse/storage/databases/main/__init__.py
- synapse/storage/databases/main/events_worker.py
- synapse/storage/databases/main/stream.py
We had three duplicate implementations of `get_room_max_stream_ordering`... time to get rid of some. Review commit-by-commit.
> Remove redundant `get_current_events_token`

- changelog.d/11632.bugfix
- synapse/federation/federation_client.py
- synapse/handlers/federation_event.py
Events returned by `backfill` should not be flagged as outliers.
Fixes:
```
AssertionError: null
File "synapse/handlers/federation.py", line 313, in try_backfill
dom, room_id, limit=100, extremities=extremities
File "synapse/handlers/federation_event.py", line 517, in backfill
await self._process_pulled_events(dest, events, backfilled=True)
File "synapse/handlers/federation_event.py", line 642, in _process_pulled_events
await self._process_pulled_event(origin, ev, backfilled=backfilled)
File "synapse/handlers/federation_event.py", line 669, in _process_pulled_event
assert not event.internal_metadata.is_outlier()
```
See https://sentry.matrix.org/sentry/synapse-matrixorg/issues/231992
Fixes #8894.
> `FederationClient.backfill`: stop flagging events as outliers

- changelog.d/11536.bugfix
- changelog.d/11536.misc
- changelog.d/11642.bugfix
- scripts-dev/check-newsfragment
- synapse/handlers/stats.py
- synapse/handlers/user_directory.py
If you purged a bunch of events from your database, and then restarted synapse
without receiving more events, then you would get a bunch of AssertionErrors on
restart.
This fixes the situation by rewinding the stream processors.
(I've also updated the changelog for #11536, since this was the cause of the mixup I was trying to debug there.)
> Fix AssertionErrors after purging events

- changelog.d/11680.doc
- docs/reverse_proxy.md
this should not be a case-insensitive match.
> update ngnix reverse-proxy example

- changelog.d/11640.doc
- contrib/docker/docker-compose.yml
- docker/README.md
Couple of tweaks to documentation. Doesn't include all the above methods, assuming they don't all apply to docs.
Partly this came from #8304.
> Improve Docker docs for use with Postgres

- changelog.d/11681.doc
- docs/sso_mapping_providers.md
I like how our modern Module API documentation does this; thought I'd copy it here quickly since it came up.
It sets people off on the right foot.
> Clarify SSO mapping provider documentation by writing `def` or `async def` before the names of methods, as appropriate.

- changelog.d/11664.feature
- docs/admin_api/user_admin_api.md
- synapse/rest/admin/__init__.py
- synapse/rest/admin/users.py
- tests/rest/admin/test_user.py
Add admin API
```
GET /_synapse/admin/v1/users/<user_id>/accountdata
```
> Add admin API to get users' account data

- changelog.d/11677.bugfix
- synapse/http/client.py
I suppose that in `SimpleHttpClient.get_json` function, `actual_headers` dict should be used in `SimpleHttpClient.get_raw` call instead of passed `headers` dict.
> Fix SimpleHttpClient not sending Accept header in `get_json`

- changelog.d/11690.misc
- synapse/rest/client/capabilities.py
> Include `io.element.thread` capability for MSC3440.

- changelog.d/11593.bugfix
- synapse/rest/admin/federation.py
- synapse/storage/databases/main/transactions.py
- tests/rest/admin/test_federation.py
At the moment you get a `NotFoundError` if you request `GET /_synapse/admin/v1/federation/destinations/<destination>` and the destination has no problems.
The reason is that `get_destination_retry_timings` returns `None` if there is no problem with the destination.
This PR fix it:
- add DB function to query that a destination exists
- update rest API
- add a test
(run the [linters](https://matrix-org.github.io/synapse/latest/development/contr …
> Fix get federation status of destination if no error occured

- changelog.d/11667.bugfix
- synapse/handlers/room_summary.py
* `creation_ts` isn't a thing, and doesn't appear to be used by anything.
* ~~`aliases` is *technically* required by the MSC, but not provided and wasn't in the MSC example. It's required by `PublicRoomsChunk`.~~ See https://github.com/matrix-org/matrix-doc/pull/3624
* `join_rule` was spelled incorrectly in the MSC and should have been copied from `PublicRoomsChunk`.
* ~~`allowed_spaces` feels like it can be removed from the federation response now.~~
- Start with a …
> Fix space hierarchy endpoint to match MSC

- changelog.d/11693.misc
- synapse/handlers/sync.py
#4422
as per
https://github.com/matrix-org/synapse/pull/11532#discussion_r769123269
> Remove debug logging for #4422

- changelog.d/11672.feature
- synapse/handlers/room.py
Solve issue #11245
Whenever the `spamcheck` forbids a user to create a room, a `SynapseError` with `errcode` `M_UNKNOWN` is returned to the client. However, it would be more specific to return the `errcode` `M_UNKNOWN`.  
Therefore, this PR will raise `M_FORBIDDEN` instead of `M_UNKNOWN` whenever `synapse/events/spamcheck.py:user_may_create_room` returns `False`.
Note: The `M_FORBIDDEN` code is set in the methods which currently call `user_may_create_room`, not in the method `user_may_create_room` itself.
Signed-off-by: Lukas Denk <lukasdenk@web.de>
- Use markdown where necessary, …
> Make room creations denied by `user_may_create_room` cause an `M_FORBIDDEN` error to be returned, not `M_UNKNOWN`

- changelog.d/11696.misc
- synapse/util/__init__.py
This will be unnecessary once https://github.com/matrix-org/mjolnir/pull/174 lands.
> Work around Mjolnir compatibility issue by adding an import for `glob_to_regex` in `synapse.util`, where it moved from.

- changelog.d/11699.misc
- synapse/types.py
Removes a Python 2-ism in our code where indexing into a byte-string on Python 2 returned a bytes object, but on Python 3 returns an int.
> Remove a Python 2-ism and improve type hints.

- changelog.d/11682.removal
- synapse/rest/client/relations.py
- tests/rest/client/test_relations.py
This endpoint was removed from MSC2674 before it was approved, so is obsolete. matrix.org does not seem to have any records in the past few weeks of this endpoint being used. To my knowledge, no client has used this endpoint.
Fixes #10285
> Remove the /send_relation endpoint.

- changelog.d/11612.misc
- synapse/events/utils.py
- synapse/handlers/events.py
- synapse/handlers/initial_sync.py
- synapse/handlers/message.py
- synapse/handlers/pagination.py
- synapse/handlers/room.py
- synapse/handlers/search.py
- synapse/rest/admin/rooms.py
- synapse/rest/client/events.py
- synapse/rest/client/notifications.py
- synapse/rest/client/relations.py
- synapse/rest/client/room.py
- synapse/rest/client/sync.py
- synapse/server.py
- synapse/storage/databases/main/relations.py
- tests/rest/client/test_retention.py
This is some partial work towards #11611, the main benefit of which is that the event serialization process is now synchronous and does not access the database.
This requires the callers which wish to include bundled aggregations to manually fetch them and pass them in (as opposed to just passing a flag).
~~Based on #11592~~
This will be the basis for some future work for #11611:
* Including the bundled aggregations in the response cache for sync -- see #11659.
* Fetching the bundled aggregations of multiple events at once (to reduce database round trips) -- see #11660 for doing this with edits.
> Bundle aggregations outside of the serialization method

- changelog.d/11701.misc
- tests/handlers/test_sync.py
- tests/rest/client/utils.py
I have tried to capture the race described by @richvdh in [this comment](https://github.com/matrix-org/synapse/pull/11532#discussion_r769104461).
It passes when I ran the test against develop locally, and it fails when I run it against #11532.
> Test case for an edgy race

- changelog.d/11702.misc
- tests/server.py
- tests/utils.py
When debugging a test it is sometimes useful to inspect the state of the
DB. This is not easy when the db is in-memory: one cannot attach the
sqlite CLI to another process's DB. (I suppose you could ferret out the
sqlite connection object from within the debugger and sending text
directly but... that is painful and doesn't have tab completion.)
With this change, if SYNAPSE_TEST_SQLITE_DB_LOCATION is set, we try to
write the DB to disk at that location (deleting any existing db file as
necessary).
Quick and dirty.
> Optionally use an on-disk sqlite db in tests

- changelog.d/11695.bugfix
- synapse/handlers/room_summary.py
- tests/handlers/test_room_summary.py
This updates the support for the `/hierarchy` endpoint to support > 50 rooms in a single space.
This is done by duplicating some logic for the legacy `/spaces` API in callers to `_summarize_local_room`, which is also used by the `/hierarchy` endpoint.
The initial commit asserts the current logic on `develop` and should pass those tests, I then updated it for fixing this bug which is only fixed for `/hierarchy`, not `/spaces`.
Fixes #11134
> Support spaces with > 50 rooms in the /hierarchy endpoint

- .github/workflows/tests.yml
- changelog.d/11707.misc
Modifies Github Actions to make Complement logs prettier.
E.g https://github.com/matrix-org/synapse/runs/4740778609?check_suite_focus=true#step:7:18
> Prettier complement logs

- changelog.d/11714.misc
- tests/crypto/test_event_signing.py
Fixes #11644.
I really don't like that we're monkey patching pynacl SignedKey
instances with alg and version objects. But I'm too scared to make the
changes necessary right now.
(Ideally I would replace `signedjson.types.SingingKey` with a runtime class which
wraps or inherits from `nacl.signing.SigningKey`.)
> Deal with mypy errors w/ type-hinted pynacl 1.5.0

- changelog.d/11716.misc
- synapse/handlers/account_data.py
- synapse/storage/databases/main/account_data.py
It looks like a copy and paste mistake: the previous function has the same docstring and *is* intended for room account data.
> Fix docstring on `add_account_data_for_user`.

- .gitignore
- changelog.d/11718.misc
- scripts-dev/complement.sh
This is a subset of the changes in #11431 containing just the trivial complement changes, which are expanding .gitignore and moving to the new name of environment variable
> Complement environment variable name change and .gitignore expansion.

- .github/workflows/tests.yml
- changelog.d/11691.misc
- docker/Dockerfile
- scripts-dev/complement.sh
Having spent much of the last week attempting to run complement tests from somewhere with damp string instead of internet... something had to be done.
> Use buildkit's cache feature to speed up docker builds

- changelog.d/11729.bugfix
- synapse/storage/databases/main/devices.py
- tests/storage/test_devices.py
Fixes #11727: you can't resume reading the stream if there are more than `limit` entries because you get told to continue from the end of the stream, not the end of where you read up to.
Of note: #7010: stream_ids used to not be unique, but the ones produced in modern times are (since v1.13.0). Thanks Erik for saving me a lot of pain!
It appears to have been introduced in https://github.com/matrix-org/synapse/commit/2d1d7b7e6f2bec3b96b0d23993369ce46aad4f32, which has been there since the good ol' days of v1.0.0 :).
Required change for the fix to #11719, which is a release blocker.
> Fix a bug introduced in Synapse v1.0.0 whereby device list updates would not be sent to remote homeservers if there were too many to send at once.

- changelog.d/11723.misc
- synapse/app/_base.py
- synapse/metrics/__init__.py
- synapse/metrics/_gc.py
Rather than hooking into the reactor loop, just add a timed task that runs every 100 ms to do the garbage collection.
Part 1 of a quest to simplify the reactor monkey-patching.
> Simplify GC prometheus metrics

- changelog.d/11730.bugfix
- synapse/storage/databases/main/devices.py
- tests/storage/test_devices.py
Follows on from: #11729.
Fixes #11719.
Basically, sending both a prefixed and unprefixed copy of cross-signing key updates meant that `get_device_updates_by_remote` was blowing the budget and producing more EDUs than the limit it was given.
Working around this is a little bit ugly but the principle is simple: if there won't be room for a device update, stop early!
The ugliness arises because depending on the row that comes back from the database (and whether it's a duplicate of another or not), there could be 0, 1 or 2 EDUs produced.
This can all be stripped out once we remove the duplication of cross-signing key updates.
> Fix a bug introduced in Synapse v1.50.0rc1 whereby outbound federation could fail because too many EDUs were produced for device updates.

- changelog.d/11710.bugfix
- changelog.d/11745.bugfix
- synapse/push/mailer.py
From  #11710, originally by @br4nnigan.
My changes are running the linter and adding a changelog. I meant to do this in #11710 but screwed up my usage of (ma)git royally; apologies to all.
>  Fix missing app variable in mail subject

- changelog.d/11742.misc
- synapse/rest/admin/background_updates.py
- synapse/storage/database.py
- synapse/storage/databases/main/account_data.py
- synapse/storage/databases/main/deviceinbox.py
- synapse/storage/databases/main/devices.py
- synapse/storage/databases/main/directory.py
- synapse/storage/databases/main/e2e_room_keys.py
- synapse/storage/databases/main/end_to_end_keys.py
- synapse/storage/databases/main/event_push_actions.py
- synapse/storage/databases/main/events.py
- synapse/storage/databases/main/events_bg_updates.py
- synapse/storage/databases/main/presence.py
- synapse/storage/databases/main/pusher.py
- synapse/storage/databases/main/user_directory.py
- synapse/storage/databases/state/bg_updates.py
- synapse/storage/databases/state/store.py
- tests/rest/admin/test_registration_tokens.py
- tests/storage/test_event_federation.py
And the `_txn` form, and then renames `simple_insert_many_values` back to `simple_insert_many`. This finishes the work started in #11560 and should give us some more gains by avoiding creating intermediary dictionaries.
Should probably be reviewed commit-by-commit.
> Replace uses of simple_insert_many with simple_insert_many_values.

- changelog.d/11749.doc
- changelog.d/11749.feature
- docs/sample_config.yaml
- synapse/config/api.py
Follow on from #11561 
Closes #11741
> Fix sample_config.yaml in regards track_puppeted_user_ips

- changelog.d/11576.feature
- docs/admin_api/user_admin_api.md
- synapse/handlers/admin.py
- synapse/rest/admin/__init__.py
- synapse/rest/admin/users.py
- tests/rest/admin/test_user.py
A `password_hash` field is returned by both `GET` and `PUT` methods of `/_synapse/admin/v2/users/<user_id>`. There is little use for this to be returned, and returning it is an unnecessary security risk.
Note that I don't believe this field was included on purpose. It is simple a consequence of using `get_user_by_id` directly for this Admin API endpoint (which we probably shouldn't do, as it means that changing an internal storage method changes an external API shape!).
~~As this is a backwards-incompatible change, the endpoint version has been bumped.~~ This ended up being considered a bug, slight security risk, and not intentionally included in the first place. Additionally, we're not aware of any usecases for it. Thus we have simply dropped it from the existing v2 API.
Reviewable …
> Remove the 'password_hash' from the Users Admin API endpoint response dictionary

- changelog.d/11737.bugfix
- synapse/storage/databases/main/room.py
- tests/rest/admin/test_room.py
Always add `state.room_id` after the configurable ORDER BY. Otherwise,
for any sort, certain pages can contain results from
other pages. (Especially when sorting by creator, since there may
be many rooms by the same creator)
Fixes: #11736 
> Make pagination of rooms in admin api stable

- changelog.d/11686.doc
- docs/turn-howto.md
This helps to avoid client-side issues:
* https://github.com/vector-im/element-android/issues/1533
* https://github.com/vector-im/element-ios/issues/2712
Signed-off-by: Andrew Ferrazzutti <fair@miscworks.net>
I can confirm that using a ZeroSSL certificate instead of a Let's Encrypt one allows `turns:` connections to work. To test this, I configured my `coturn` to enable only TLS/DTLS listeners. By doing nothing other than switching certs, calls work with the ZeroSSL cert and fail with the Let's Encrypt cert. I tested this with both Element Android and Jitsi Meet.
This PR can be treated as a more complete version of https://github.com/matrix-org/synapse/pull/10358.
- Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other …
> Warn against using Let's Encrypt certs for encrypted TURN

- changelog.d/11675.feature
- synapse/_scripts/review_recent_signups.py
- synapse/handlers/register.py
Solve issue #10699
Adds a flag to the `synapse_review_recent_signups` script to ignore and filter appservice users.
**Signed-off-by:** Lukas Denk <lukasdenk@web.de>
> Add a flag to the `synapse_review_recent_signups` script to ignore and filter appservice users.

- changelog.d/11764.bugfix
- synapse/app/homeserver.py
Fixes https://github.com/matrix-org/synapse/issues/11763
#11602 compiled known client resource prefixes under one, simplified '/_matrix/client' prefix. Unfortunately, '/_matrix/client' is already a prefix used by the 'webclient' resource. As we use a Python dictionary to hold a mapping from prefix to resource, configuring a 'webclient' resource after a 'client' resource would end up with all client requests being redirected to the 'webclient' resource (which doesn't know how to handle things like `/login` or `/sync`).
This PR essentially reverts #11602 in order to provide a working version of Synapse v1.50.x. A proper fix will come later. Additionally, this bug has highlighted how fragile the resource code is currently.
> Revert #11602 to prevent webclient overriding client resource

- changelog.d/11577.feature
- synapse/handlers/pagination.py
- synapse/handlers/room.py
- synapse/handlers/sync.py
- synapse/rest/client/relations.py
- synapse/rest/client/room.py
- synapse/storage/databases/main/events.py
- synapse/storage/databases/main/relations.py
- tests/rest/client/test_relations.py
Per [MSC3440](https://github.com/matrix-org/matrix-doc/pull/3440), whether the requesting user has responded to the thread should be included in the thread summary.
This is broken into two commits, the first of which pipes the requesting user through to the serialization layer. I believe that we're going to need this there anyway since MSC2675 specifies that bundle aggregations need to account for ignored users.
Fixes #11399
> Include whether the requesting user has participated in a thread.

- changelog.d/11669.bugfix
- docs/development/url_previews.md
- synapse/rest/media/v1/oembed.py
- synapse/rest/media/v1/preview_url_resource.py
- tests/rest/media/v1/test_url_preview.py
Related to #11563
This PR fixes the preview of tenor.com URLs.
Before: 
After:
This was broken because oEmbed JSON from tenor.com looks like:
```json
{
"type": "video",
"version": "1.0",
"provider_name": "Tenor",
"provider_url": "https://tenor.com/",
"cache_age": 86400,
"html": "<iframe src=\"https://tenor.com/embed/4945328\" width=\"600\" height=\"400\" frameborder=\"0\"></iframe>",
"width": 600,
"height": 400
}
```
And we don't know how to handle the iframe. This PR fixes it by aborting the oEmbed preview and falling back to the Open Graph one (which I think was what was done before).
Note that this does not completely fix #11563 because imgur previews are still broken. The oEmbed looks like
```json
{
"version": "1.0",
"type": "rich",
"provider_name": "Imgur",
"provider_url": …
```
> Fix preview of some gif URLs

- changelog.d/11768.misc
- synapse/logging/opentracing.py
Otherwise `_reporter` would end up as a `attr.Factory`, not a `Reporter`.
Uses the same changelog as #11692.
> Add missing `auto_attribs=True` to the `_WrappedRustReporter` class

- changelog.d/11771.misc
- synapse/metrics/_reactor_metrics.py
Follow-up to #11724 to fix mypy on macOS.
> Fix mypy for platforms without epoll support.

- changelog.d/11776.misc
- synapse/storage/databases/main/events.py
A couple of surprises for me here, so thought I'd document them
> Comments and typing for `_update_outliers_txn`

- changelog.d/11775.bugfix
- synapse/federation/federation_client.py
- synapse/handlers/room_summary.py
- tests/handlers/test_room_summary.py
`FederationClient.get_room_hierarchy()` caches its return values, so
avoid modifying the returned room summary and clone it instead.
Fixes #11773.
> Fix a bug that corrupted the cache of federated space hierarchies

- .gitignore
- changelog.d/11766.misc
- scripts-dev/complement.sh
Allows you to define COMPLEMENT_REF to use a different branch or commit
than master, when running complement and not using a local
COMPLEMENT_DIR.
(run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#r …
> Allow overriding the complement ref

- changelog.d/11760.misc
- synapse/federation/sender/transaction_manager.py
- synapse/federation/transport/server/federation.py
- synapse/storage/databases/main/devices.py
Debug for #8631. I want to establish if we actually _are_ sending out the
correct EDUs over federation.
I'm having a hard time tracking down what's going wrong in that issue.
In the reported example, I could see server A sending federation traffic
to server B and all was well. Yet B reports out-of-sync device updates
from A.
I couldn't see what was _in_ the events being sent from A to B. So I
have added some entirely untested crude logging to track
- when we have updates to send to a remote HS
- the edus we actually accumulate to send
- when a federation transaction includes a device list update edu
- when such an EDU is received
This is a bit of a sledgehammer. Is this a good idea? I'm anxious that this might create too much logspam.
> Debug for device lists updates

- changelog.d/11774.misc
- docs/sample_config.yaml
- docs/upgrade.md
- synapse/app/homeserver.py
- synapse/config/server.py
This ends up having a slight behavior change: if `web_client_location` points to an HTTP(S) URL than `/` will now redirect to it, regardless of whether `webclient` is a configured listener.
As part of this I removed the documentation in the sample config for `webclient` listeners.
First part of #9078.
> Add deprecation warnings for `webclient` listener and non-HTTP(S) `web_client_location`.

- changelog.d/11781.doc
- docs/setup/installation.md
#11595 dropped support for python 3.6, but forgot to update this doc.
> installation.md: drop python 3.6 support

- changelog.d/11770.feature
- synapse/handlers/register.py
Closes https://github.com/matrix-org/synapse/issues/11769. Necessary context is in the issue.
> Partially revert #11675; prevent attempting to create pushers on workers

- changelog.d/11765.misc
- tests/http/test_webclient.py
Add a regression test for the bug detailed in https://github.com/matrix-org/synapse/issues/11763.
This test configures a `SynapseSite` with both a `webclient` and `client` resource, then makes a `GET` request against both `/_matrix/client` and `/_matrix/client/v3/login`, check that the appropriate status codes and response header/bodies were returned. Both possible orderings of configuring `webclient` and `client` are attempted (`[webclient, client]` vs `[client, webclient]`).
Manipulating resources in unit tests ended up a lot more complicated than originally desired. I was hoping to just be able to `override_config` with the `listeners` section and be done with it. Unfortunately, resources for homeservers created when inheriting `HomeserverTestCase` are hardcoded: …
> Add a regression test for using both webclient and client resources simultaneously

- changelog.d/11783.misc
- synapse/app/homeserver.py
Follow-on to #11774 which fixes redirection `/` -> `/_matrix/client` in the situation where a non-HTTP(S) `web_client_location` option is given.
Related to #9078.
> Fix redirecting to the webclient for non-HTTP(S) web_client_location.

- changelog.d/11786.bugfix
- synapse/handlers/auth.py
- tests/handlers/test_password_providers.py
Looks like this was an oversight from https://github.com/matrix-org/synapse/pull/10548
> Correctly await on_logged_out callbacks

- changelog.d/11789.feature
- synapse/storage/databases/main/account_data.py
This is useful as part of #11621 to allow invalidating all the rows by user ID.
> Make `get_account_data_for_room_and_type` a tree cache

- changelog.d/11788.feature
- synapse/handlers/sync.py
- synapse/rest/client/account_data.py
- synapse/storage/databases/main/account_data.py
- synapse/visibility.py
- tests/replication/slave/storage/test_account_data.py
A review of this PR should have a bit of scrutiny behind it to make sure nothing has been missed; the type checker won't help us here for swapping a str and another str.
This is useful as part of #11621 to allow invalidating all the rows by user ID.
> Make the `get_global_account_data_by_type_for_user` cache be a tree-cache whose key is prefixed with the user ID

- changelog.d/11793.misc
- synapse/events/__init__.py
- synapse/events/snapshot.py
This is more efficient, since we only have to look up `state_key` in the event dict once, rather than three (!) times. It also makes type annotations work rather better.
> Add `FrozenEvent.get_state_key` and use it in a couple of places

- changelog.d/11795.misc
- synapse/storage/databases/main/purge_events.py
- synapse/storage/schema/__init__.py
- synapse/storage/schema/main/delta/67/01drop_public_room_list_stream.sql
- tests/rest/admin/test_room.py
This is a follow-up to #10565.
> Drop unused table `public_room_list_stream`.

- changelog.d/11612.bugfix
- changelog.d/11612.misc
- changelog.d/11791.bugfix
- synapse/events/utils.py
- synapse/rest/admin/rooms.py
- synapse/rest/client/room.py
- tests/rest/client/test_relations.py
Fixes #11772 -- in the `/context` API we were pushing the raw aggregations into the result dictionary instead of just using it to serialize the events. This is due to some questionable re-use of dictionaries that I plan to clean-up separately.
Also expands tests to cover edits under more APIs.
> Do not try to serialize raw aggregations dict.

- changelog.d/11806.bugfix
- synapse/storage/databases/main/event_federation.py
- tests/storage/test_event_federation.py
This PR is a cherry-pick of a patch by @richvdh and fixes #11802.
There was a typo for `prev_events_tuple` in #10390 which lead to the infinite looping.
Fixes infinite loops of:
> logger.info("Invalid prev_events for %s", event_id)
> Fix logic for dropping old events in fed queue

- changelog.d/11784.bugfix
- synapse/http/client.py
Fixes #8302.
Applies a timeout to reading the body for `SimpleHttpClient.get_file()`. This brings the code more inline with `MatrixFederationHttpClient.get_file`, although that uses `addTimeout` instead of `timeout_deferred`.
I tested this by attempting to preview a stream (I used a local radio station), waiting several minutes and noticing the file was still growing. With this patch the download stops after 60 seconds and the client receives an error message:
```json
{"errcode":"M_TOO_LARGE","error":"Requested file took too long to download"}
```
We are rather inconsistent with using timeouts when reading bodies, we seem to do it in some places, but not many other places. It is unclear if this is on purpose or not though. This particular method is only used by URL previews.
> Apply a timeout to reading the body when fetching a file.

- changelog.d/11817.misc
- synapse/events/validator.py
types-jsonschema 4.4.0 broke our mypy, see python/typeshed#7028.
Previously the type was just an alias for `Any`, so we're not missing much by ignoring it.
> Ignore the jsonschema type.

- changelog.d/11821.doc
- docs/development/contributing_guide.md
The pull request template says that in order to submit a pull request you have to run the linters and links to [Run the linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linters).  IMO "Run the linters" should explain that development dependencies are a pre-requisite.
I also included `pip install wheel`  which I had to run inside my virtual environment on ubuntu before the `pip install -e ".[all,dev]"` command would succeed.
Signed-off-by: forest johnson (forest.n.johnson@gmail.com)
> Docs: add missing PR submission process how-tos

- changelog.d/11823.misc
- docs/development/database_schema.md
- synapse/storage/prepare_database.py
1. make the functions in python delta files optional
2. document the things
> Minor updates, and docs, for schema delta files

- changelog.d/11813.misc
- synapse/app/_base.py
It's probably useful to log a list of all modules Synapse loads at startup now that we're moving towards one standardised and ordered interface, at least to allow server admins to see that their modules are starting correctly, and in which order they're being loaded.
An example of what this looks like in the startup logs:
```
[...]
2022-01-24 18:29:27,145 - synapse.federation.federation_server - 1281 - INFO - main - Registering federation query handler for 'directory'
2022-01-24 18:29:27,145 - twisted - 279 - INFO - main - Redirected stdout/stderr to logs
2022-01-24 18:29:27,145 - synapse.app.homeserver - 156 - INFO - sentinel - Running
2022-01-24 18:29:27,147 - synapse.app.homeserver - 29 - INFO - sentinel - Set file limit to: 524288
2022-01-24 18:29:27,147 - …
```
> Log modules at startup

- .github/workflows/tests.yml
- changelog.d/11811.misc
This requires https://github.com/matrix-org/complement/pull/289 - the branch name matches this PR so CI should test this new configuration.
The run: https://github.com/matrix-org/synapse/runs/4924828255?check_suite_focus=true
We now run Complement on the VM instead of inside a Docker container. This is to allow Complement to bind to any high-numbered port when it starts up its own federation servers. We want to do this to allow for more concurrency when running complement tests.
Previously, Complement only ever bound to `:8448` when running its own federation server. This prevented multiple federation tests running at the same time as they would fight each other on the port. This did however allow Complement to run in Docker, as the host could just port forward `:8448` to allow homeserver …
> CI: run Complement on the VM, not inside Docker

- changelog.d/11816.misc
- synapse/app/_base.py
A similar check was removed in #11683. The check determined whether the program was being run on Python 3.7 before using a garbage collection method and thus was deemed redundant in this comment: https://github.com/matrix-org/synapse/pull/11683#pullrequestreview-859931689, so I removed it. However, it was pointed out here: https://github.com/matrix-org/synapse/pull/11683#discussion_r790695704 that not all implementations of Python have that API so I have restored a version of the removed check in this new PR.
> Check that `gc` method is available before using in `synapse/app/_base` 

- changelog.d/11817.misc
- changelog.d/11830.misc
- synapse/events/validator.py
Similar to #11817.
In `_create_power_level_validator` we
- retrieve `validator`. This is a class implementing the
`jsonschema.protocols.Validator` interface. In other words,
`validator: Type[jsonschema.protocols.Validator]`.
- we then create an second validtor class by modifying the original
`validator`. We return that class, which is also of type
`Type[jsonschema.protocols.Validator]`.
So the original annotation was incorrect: it claimed we were returning
an instance of jsonSchema.Draft7Validator, not the class (or a subclass)
itself. (Stricly speaking this is incorrect, because `POWER_LEVELS_SCHEMA`
isn't pinned to a particular version of JSON Schema. But there are other
complications with the type stubs if you try to fix this; I felt like
the change herein was a decent compromise that …
> Fix another jsonschema typecheck error

- changelog.d/11834.misc
- synapse/python_dependencies.py
Upper bound to < 0.13.0. Not directly pinning it so the package maintainers have flexibility.
#11537 would have helped.
> Avoid type annotation problems in prom-client

- changelog.d/11827.bugfix
- synapse/http/site.py
Fixes #11812. See also #7188 and
https://github.com/matrix-org/synapse/pull/7188#r401719326 in
particular.
> Don't print HTTPStatus.* in "Processed..." logs

- changelog.d/11815.misc
- synapse/events/utils.py
- synapse/handlers/room.py
- synapse/handlers/search.py
- synapse/handlers/sync.py
- synapse/push/mailer.py
- synapse/rest/admin/rooms.py
- synapse/rest/client/room.py
- synapse/rest/client/sync.py
- synapse/storage/databases/main/relations.py
- synapse/storage/databases/main/stream.py
- tests/rest/client/test_relations.py
This somewhat came up [in a previous review](https://github.com/matrix-org/synapse/pull/11612#discussion_r780255443) and helps to avoid a potential issues similar to #11791. The main goal is to make the type hinting stronger and to stop mutating dictionaries in odd ways.
> Improvements to bundling aggregations

- changelog.d/11798.bugfix
- synapse/storage/databases/main/appservice.py
Signed-off-by: Vaishnav Nair <nairvaishnav007@icloud.com>
Fixes #11732
> Include `prev_content` field in AS events

- changelog.d/11836.misc
- synapse/storage/state.py
No point recreating these for each call, since they are frozen
> Create singletons for `StateFilter.{all,none}()`

- changelog.d/11847.misc
- synapse/storage/database.py
This was missed in https://github.com/matrix-org/synapse/pull/11799
> Pass `isolation_level` to `runWithConnection`

- changelog.d/11860.doc
- changelog.d/11860.misc
- docs/MSC1711_certificates_FAQ.md
- docs/admin_api/media_admin_api.md
- docs/admin_api/rooms.md
> Remove not needed old table of contents in documentation

- changelog.d/11861.doc
- docs/admin_api/account_validity.md
- docs/admin_api/delete_group.md
- docs/admin_api/event_reports.md
- docs/admin_api/media_admin_api.md
- docs/admin_api/purge_history_api.md
- docs/admin_api/room_membership.md
- docs/admin_api/rooms.md
- docs/admin_api/statistics.md
- docs/admin_api/user_admin_api.md
The `access_token` specifications are inconsistent. Sometimes it is written per api and sometimes not.
There is already a note in the [parent documentation page](https://matrix-org.github.io/synapse/latest/usage/administration/admin_api/index.html) for the API.
This PR consolidates the repetitive information centrally once at the top of the page.
- Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or …
> Consolidate the `access_token` information in the admin api

- changelog.d/11880.misc
- tests/appservice/test_appservice.py
This ended up being a requirement for testing sending device lists to application services (https://github.com/matrix-org/synapse/pull/11881). I've split it out into a separate PR for ease of review.
> Convert `ApplicationServiceTestCase` to use `simple_async_mock`

- changelog.d/11615.misc
- tests/handlers/test_user_directory.py
- tests/rest/client/test_room_batch.py
- tests/storage/test_user_directory.py
- tests/unittest.py
This is part of the E2E AS work, spun out onto develop for sanity's sake.
> Expose the registered device ID from the `register_appservice_user` test helper.

- changelog.d/11884.misc
- synapse/config/server.py
- synapse/push/baserules.py
- synapse/rest/client/push_rule.py
- synapse/storage/databases/main/push_rule.py
> Revert experimental push rules from #7997.

- .ci/scripts/test_old_deps.sh
- changelog.d/11888.misc
We disabled coverage calculation for most of CI in #11017, but the olddeps
build uses a separate script and got forgotten.
> Disable coverage calculation for olddeps build.

- changelog.d/11890.bugfix
- synapse/federation/transport/server/federation.py
Missed in #11760.
Fixes #11889. Homeservers should only be affected if the
`synapse.8631_debug` logger was enabled for DEBUG mode.
I am not sure if this merits a bugfix release: I think the logging can
be disabled in config if anyone is affected? But it is still pretty bad.
> Fix losing incoming EDUs if debug logging enabled

- changelog.d/11878.misc
- synapse/storage/_base.py
- synapse/storage/databases/main/cache.py
We seem to clear the `get_users_in_room` and `get_users_in_room_with_profiles` caches unnecessarily -- when any room state changes, not just when memberships change.
I'm not sure if this is a problem in real-life usage, but I don't see any reason to do this.
Fixes #11875
> Only clear the get_users_in_room caches when necessary.

- changelog.d/11869.misc
- synapse/logging/opentracing.py
- synapse/logging/scopecontextmanager.py
- tests/logging/test_opentracing.py
`start_active_span` was inconsistent as to whether it would activate the span immediately, or wait for `scope.__enter__` to happen (it depended on whether the current logcontext already had an associated scope). The inconsistency was rather confusing if you were hoping to set up a couple of separate spans before activating either.
Looking at the other implementations of opentracing `ScopeManager`s, the intention is that it *should* be activated immediately, as the name implies. Indeed, the idea is that you don't have to use the scope as a contextmanager at all - you can just call `.close` on the result. Hence, our cleanup has to happen in `.close` rather than `.__exit__`.
So, the main change here is to ensure that `start_active_span` does activate the span, and that `scope.close()` does …
> Fixes for opentracing scopes

- changelog.d/11859.doc
- docs/admin_api/user_admin_api.md
> Fix typo: unpind -> unbind

- changelog.d/11867.feature
- docs/modules/password_auth_provider_callbacks.md
- docs/upgrade.md
- docs/workers.md
- synapse/api/constants.py
- synapse/handlers/ui_auth/__init__.py
- synapse/rest/client/register.py
- tests/rest/client/test_register.py
Finalizes the work done in #10142
Stablizes MSC3231 according to the spec wording of https://github.com/matrix-org/matrix-doc/pull/3616
`Signed-off-by: Jonathan de Jong …
> Stabilise MSC3231 (Token Based Registration)

- .github/workflows/tests.yml
- changelog.d/11910.misc
Since #11811 there has been general Complement flakiness around networking.
It seems like tests are hitting the wrong containers. In an effort to diagnose
the cause of this, as well as reduce its impact on this project, set the
parallelsim to 1 (no parallelism) when running tests.
If this fixes the flakiness then this indicates the cause and I can diagnose
this further. If this doesn't fix the flakiness then that implies some kind
of test pollution which also helps to diagnose this further. …
> Run Complement tests sequentially

- changelog.d/11909.misc
- tests/rest/client/test_sync.py
The need was discovered after a [silly bug](https://github.com/matrix-org/synapse/pull/11905/files#r798840354) in https://github.com/matrix-org/synapse/pull/11905 wasn't being caught automatically. This test will fail when that bug is present.
We always try to send device list changes of users down to their own devices, so that multiple devices of the same user stay in sync. This wasn't being verified by our unit tests.
> Add a unit test for users receiving their own device list updates

- changelog.d/11914.misc
- synapse/handlers/typing.py
A small clean up to some rather dubious access to the datastore. The variable name `_main_store` comes from https://github.com/matrix-org/synapse/issues/11733.
> Clean up an indirect reference to the homeserver datastore

- changelog.d/11927.misc
- synapse/rest/media/v1/upload_resource.py
I believe twisted/twisted#1669 being merged caused this error to be spotted by mypy.
Hopefully the fix should be pretty straightforward, but now we operate over the integer version of the `Content-Length` header, instead of the string one. In reality I don't think this caused an issue since the database would cast it eventually anyway (?).
This also fixes a separate issue if decoding the uploaded name failed. (We would reference an invalid variable name.)
Fixes #11923
> Pass the proper type when uploading files.

- changelog.d/11911.misc
- synapse/appservice/__init__.py
- synapse/handlers/appservice.py
- tests/appservice/test_appservice.py
This parameter was only optional for the benefit of unit tests (not providing the parameter thus disabled some of the checks). This is a code smell, and did cause issues during implementation of #11881.
At the very least, we should implement the required methods on the mock passed to this method in the unit tests, and make the argument non-optional (which is should always be in production code). Ideally we'd rewrite the tests to operate on a proper testing homeserver object instead of a tower of mocks - but one step at a time.
Types were corrected up and down the call stack as needed. `event` in several methods also should not have been `Optional` as far as I can tell.
> Remove optional state of `ApplicationService.is_interested`'s `store` parameter

- changelog.d/11912.misc
- synapse/storage/databases/main/devices.py
Yet more refactors split out from #11881.
Public functions lacking docstrings, and some missing/incorrect type hints.
> Add a docstring to `add_device_change_to_streams` and fix some nearby types

- changelog.d/11930.bugfix
- synapse/app/homeserver.py
This reverts #11764 to get the behavior back from #11602. This is safe to re-apply now that we've fixed #9078. With this PR, any unknown endpoint under `/_matrix/client` should return JSON errors instead of HTML 404s.
Fixes #11600.
> Return JSON errors instead of HTML errors for unknown resources

- changelog.d/11939.misc
- synapse/handlers/send_email.py
- synapse/replication/tcp/handler.py
- synapse/replication/tcp/redis.py
Fixes #10899 now that Twisted has released a new update we don't need to ignore the host parameter for `connectTCP` anymore.
This will require updating local installs to the latest Twisted or mypy will fail.
> Remove unnecessary ignores due to Twisted upgrade.

- changelog.d/11938.misc
- mypy.ini
- synapse/replication/slave/storage/_slaved_id_tracker.py
- synapse/replication/slave/storage/client_ips.py
- synapse/replication/slave/storage/devices.py
- synapse/replication/slave/storage/groups.py
- synapse/replication/slave/storage/push_rule.py
- synapse/replication/slave/storage/pushers.py
- synapse/replication/tcp/client.py
- synapse/replication/tcp/commands.py
- synapse/replication/tcp/handler.py
- synapse/replication/tcp/protocol.py
- synapse/replication/tcp/redis.py
- synapse/replication/tcp/resource.py
- synapse/replication/tcp/streams/_base.py
- synapse/replication/tcp/streams/events.py
- synapse/util/stringutils.py
- tests/replication/_base.py
- tests/replication/tcp/test_remote_server_up.py
Follow-up to #11856 which completes the type hints in `synapse.replication`.
I think this was all pretty straightforward?
> Add missing type hints to synapse.replication.

- changelog.d/11946.doc
- docs/structured_logging.md
This should read `stream` instead of `location`.
This is a docs-only change.
> Fix stream location for StreamHandler

- changelog.d/11954.doc
- docs/SUMMARY.md
- docs/development/releases.md
Tries to formalize the conversation from #9914 that we've been following recently.
Also related to #11940.
> Document the release cycle

- changelog.d/11913.misc
- tests/federation/test_complexity.py
- tests/federation/test_federation_server.py
- tests/federation/transport/test_knocking.py
- tests/federation/transport/test_server.py
- tests/rest/client/test_third_party_rules.py
- tests/unittest.py
If we prepopulate the test homeserver with a key for a remote homeserver, we
can make federation requests to it without having to stub out the
authenticator. This has two advantages:
* means that what we are testing is closer to reality (ie, we now have
complete tests for the incoming-request-authorisation flow)
* some tests require that other objects be signed by the remote server (eg,
the event in `/send_join`), and doing that would require a whole separate
set of mocking out. It's much simpler just to use real keys.
> Tests: replace mocked Authenticator with the real thing

- changelog.d/11953.misc
- mypy.ini
- synapse/event_auth.py
- synapse/handlers/oidc.py
- synapse/http/client.py
- synapse/http/matrixfederationclient.py
- synapse/notifier.py
- synapse/server.py
- tests/handlers/test_oidc.py
This was a WIP branch I found, it is rather small but I don't know if I'll have time to get back to it soon and figured it makes sense to merge it as is.
> Adds misc missing type hints

- changelog.d/11965.misc
- synapse/event_auth.py
This is but a tiny step towards fixing #11176.
> Fix import cycle

- changelog.d/11966.bugfix
- synapse/storage/databases/main/deviceinbox.py
- tests/rest/client/test_sendtodevice.py
If ther are more than 100 to-device messages pending for a device
`/sync` will only return the first 100, however the next batch token was
incorrectly calculated and so all other pending messages would be
dropped.
This is due to `txn.rowcount` only returning the number of rows that
*changed*, rather than the number *selected* in SQLite.
c.f. #11457
> Fix to-device being dropped in limited sync in SQLite.

- .github/workflows/tests.yml
- changelog.d/11971.misc
use `HEAD` rather than hardcoding `master`
> Prepare for rename of default complement branch

- changelog.d/11752.misc
- synapse/storage/databases/main/events.py
- synapse/storage/databases/main/relations.py
This uses the same approach as #11660, but for the thread relation type instead of the edit relation type.
I did similar performance testing on this as in #11660 and #11612 and it seems to be ~15-20% improvement compared to develop when MSC3440 enabled. (The changes in this PR bring performance roughly on par as develop with MSC3440 *disabled*.)
Part of #11825.
> Fetch thread summaries for multiple events in a single query

- changelog.d/11941.feature
- synapse/rest/client/relations.py
- tests/rest/client/test_relations.py
Implements MSC3715 to add a `dir` parameter to `/relations`.
This API is currently unstable and the default behavior is the same, so I think it is safe to just add, but willing to hear alternatives!
> Support the `dir` parameter for `/relations`.

- changelog.d/11967.feature
- synapse/config/experimental.py
- synapse/federation/federation_server.py
- synapse/federation/transport/server/federation.py
- synapse/storage/databases/main/event_federation.py
- tests/federation/test_federation_server.py
- tests/storage/test_event_federation.py
Part of my work on #11249: this lands the changes needed on the "server" side of federation to reduce the response size of the `/send_join` response.
There are a few changes. First, we add a query-param allowing federation "clients" to opt in to the new behaviour.
If a client opts in, we then:
* reduce the number if state events we return
* only return the auth events needed to auth those state events, and only those not duplicated by the state list.
* return a list of servers currently in the room.
It's all guarded by an experimental config flag.
Suggest reviewing commit-by-commit as there are a couple of preparatory commits.
> Implement MSC3706: partial state in `/send_join` response

- changelog.d/11905.misc
- synapse/handlers/device.py
When a device list update occurs, [`Notifier.on_new_event`](https://github.com/matrix-org/synapse/blob/610578e27177136b6a4b187783c490d35c688272/synapse/notifier.py#L406) is called with the key `device_list`. This method determines the set of users to notify of this update from both a collection of `users` and a collection of `rooms`. 
Users are consolidated before notifying (waking up sync streams etc.) occurs. `Notifier.rooms_to_users_state` is used to translate from a given room ID to a set of users in the room. Those users are then merged into the list of those to notify.
This all works pretty well, until we [hooked into this method](https://github.com/matrix-org/synapse/pull/8437) to send EDUs to AS's:
https://github.com/matrix-org/synapse/blob/610578e27177136b6a4b187783c490d35c688272/ …
> Notify users, rather than rooms, of device list updates

- changelog.d/11975.bugfix
- synapse/module_api/__init__.py
From my suggestion at https://github.com/matrix-org/synapse/pull/11950#discussion_r803013130
This should give us more flexibility to add/remove module callbacks since they must be named as keyword arguments.
This isn't 100% backwards compatible though, unfortunately, if someone *was* not using kwargs.
I poked around at all the modules I could find that we've created and they seem to use keyword arguments.
> Require that modules register their callbacks using keyword arguments

- changelog.d/11989.feature
- docs/upgrade.md
This entry in the upgrade notes was added in https://github.com/matrix-org/synapse/pull/11933/files#diff-3ec187be4d5027db52c481841dbbf321b2f4b39dea03033c971aeba9a4a20e51R113, however included a placeholder for an unknown Synapse version. That version is likely going to be 1.54.0, and we need to pick a number before putting out 1.53.0rc1 -- due tomorrow.
Filing as a release blocker so that it gets picked up in time. Uses the same changelog as #11933.
> Note when unstable MSC3283 prefixes will be removed

- changelog.d/11969.misc
- synapse/python_dependencies.py
This reverts commit 2bf31f7807c7a0c229170803c97090d612dc16f9.
As mentioned in https://github.com/matrix-org/synapse/pull/11625#issuecomment-1035903958 by @K900
> The upstream issue is now fixed, and the pin breaks distros that ship a newer frozendict instead (Arch, NixOS, etc.).
(run the …
> Revert "Pin to frozendict<2.1.2 (#11625)"

- changelog.d/11972.misc
- synapse/notifier.py
- tests/rest/client/test_device_lists.py
- tests/rest/client/utils.py
Born out of trying to test a particular condition in https://github.com/matrix-org/synapse/pull/11905.
There's some duplication between these methods, though not so much that I think refactoring it out is sorely needed. Feel free to refute that claim though!
> Add some tests for propagation of device list changes between local users

- changelog.d/11992.bugfix
- synapse/events/utils.py
- synapse/storage/databases/main/events_worker.py
- synapse/storage/databases/main/relations.py
- tests/rest/client/test_relations.py
If the latest event in a thread is edited the edit is not reflected properly in the bundled aggregation. This PR fixes that behavior and includes a regression test.
Fixes #11973
> Fix a bug with thread summaries when the latest event is edited

- changelog.d/11999.bugfix
- synapse/storage/databases/main/events.py
- tests/storage/test_events.py
When the server leaves a room the `get_rooms_for_user` cache is not
correctly invalidated for the remote users in the room. This means that
subsequent calls to `get_rooms_for_user` for the remote users would
incorrectly include the room (it shouldn't be included because the
server no longer knows anything about the room).
> Fix incorrect `get_rooms_for_user` for remote user

- changelog.d/12000.feature
- synapse/util/caches/__init__.py
- synapse/util/caches/expiringcache.py
- synapse/util/caches/lrucache.py
Currently we only track evictions due to size or time constraints.
> Track cache invalidations

- changelog.d/11994.misc
- synapse/handlers/federation_event.py
`_auth_and_persist_outliers` is called in three places:
* `process_remote_join`
* `_get_remote_auth_chain_for_event`
* `_get_events_and_persist`.
The first two of those contain code to filter out any events we have already seen, with a call to `have_seen_events`. (The third, `_get_events_and_persist`, doesn't bother, because in theory it is only called for events we don't already have).
I'm shortly going to add a fourth caller, which will also need to filter out events we have already seen. Rather than add yet a third copy of the deduplication code, let's just push it down into `auth_and_persist_outliers`.
> `_auth_and_persist_outliers`: drop events we have already seen

- changelog.d/11996.misc
- synapse/handlers/room_member.py
Initially introduced in `matrix-org-hotfixes` by https://github.com/matrix-org/synapse/commit/e5537cf98333b428dbc481ed443daed2f0cfa074 (and tweaked by later commits).
Fixes https://github.com/matrix-org/synapse/issues/11995
See also https://github.com/matrix-org/synapse/issues/4826
I haven't ported https://github.com/matrix-org/synapse/commit/ca21957b8a4942e829050834297afb290338c120 as part of this PR because it looks like something that should be done separately and would need a switch from hardcoded settings to configuration knobs.
> Limit concurrent AS joins

- changelog.d/12003.doc
- docs/modules/spam_checker_callbacks.md
#10758 documented various module API callbacks which must return a `bool`. It did _not_ specify the meaning of those bools, leaving module authors to either inspect Synapse's source, or else guess the meaning of the return value based on the function's name.
In this change I have tried to explicitly spell out what each return value indicates. Please double-check this carefully: I did this in a hurry, and am not familiar with the module API.
Motivation: Most callbacks return `False` to prevent some kind of action from taking place. Unfortunately `check_username_for_spam` is the opposite (return `True` to exclude from user directory searches; `False` for no effect). This isn't obvious. As a result, for about a week or two we ran a module on matrix.org [which effectively considered all users …
> Explain the meaning of spam checker callbacks' return values

- changelog.d/11835.feature
- synapse/push/httppusher.py
- tests/push/test_http.py
Fixes #11704.
Make a `POST` to `/rooms/<room_id>/receipt/m.read/<event_id>` only trigger a push notification when the count of unread messages is different to the one in the last successfully sent push.
**Signed-off by:** Lukas Denk, lukasdenk@web.de
@reivilibre:
-  As I believe, every message sent to a room triggers a push notification to be sent. So is there actually a scenario in which a `POST` to `/rooms/<room_id>/receipt/m.read/<event_id>` will still trigger a push now?
- I have not written an extra test since `test_push_unread_count_message_count` will now fail in case a `POST` to `/rooms/<room_id>/receipt/m.read/<event_id>` erroneaously causes a push notification to be sent.
- Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving …
> Prevent duplicate push notifications for room reads

- changelog.d/12005.misc
- synapse/handlers/federation_event.py
https://github.com/matrix-org/matrix-doc/blob/rav/proposal/partial_state_on_join/proposals/3706-partial-state-in-send-join.md#changes-to-the-response proposes changing the `/send_join` response:
> Any events returned within `state` can be omitted from `auth_chain`.
Currently, we rely on `m.room.create` being returned in `auth_chain`, but since the `m.room.create` event must necessarily be part of the state, the above change will break this.
In short, let's look for `m.room.create` in `state` rather than `auth_chain`.
> `send_join` response: get create event from `state`, not `auth_chain`

- .ci/scripts/test_old_deps.sh
- changelog.d/12015.misc
- tox.ini
As the comment says, virtualenv is a pile of fail.
> Configure `tox` to use `venv`

- changelog.d/12011.misc
- synapse/config/experimental.py
- synapse/federation/federation_client.py
- synapse/federation/transport/client.py
- synapse/python_dependencies.py
- tests/federation/transport/test_client.py
Part of my work on #11249: add code to handle the new fields added in MSC3706.
> Faster joins: parse msc3706 fields in send_join response

- changelog.d/12009.feature
- docs/modules/password_auth_provider_callbacks.md
- synapse/handlers/auth.py
- synapse/module_api/__init__.py
- synapse/rest/client/register.py
- tests/handlers/test_password_providers.py
Part of the Tchap mainlining. Very similar to [`get_username_for_registration`](https://matrix-org.github.io/synapse/latest/modules/password_auth_provider_callbacks.html#get_username_for_registration), except for setting the display name. The reason this is needed is because Tchap's Synapse fork derives the display name from the email address on registration - see [this code](https://github.com/matrix-org/synapse-dinsic/blob/f20caae101a482f19c81fbf36d4952388274d2d8/synapse/rest/client/register.py#L700-L710).
> Allow modules to set a display name on registration

- changelog.d/12025.misc
- tox.ini
Our olddeps check don't check for the oldest possible versions on _transitive_ dependencies. Markupsafe 2.1 was released recently, which breaks Jinja 2.x. So olddeps installs Jinja 2.9 (since it's the oldest version allowed) and markupsafe 2.1 (since it's the latest version of the transitive dep), which breaks everything.
See https://github.com/pallets/jinja/issues/1587
> Update the olddeps CI check to use an old version of markupsafe

- changelog.d/12024.bugfix
- synapse/storage/databases/main/events_worker.py
Fix 500 error with Postgres when looking backwards with the MSC3030 `/timestamp_to_event` endpoint.
`==` is a valid comparison operator in SQLite but not in Postgres.
This wasn't caught in the [MSC3030 Complement tests](https://github.com/matrix-org/complement/pull/178) because they use SQLite, see https://github.com/matrix-org/complement/blob/18aa82f2635cb5f69d720adb4b6bb722debb7c47/dockerfiles/synapse/homeserver.yaml#L34-L35
SQLite says:
> Equals can be either = or ==.
>
> *-- https://sqlite.org/lang_expr.html*
But for Postgres, https://www.postgresql.org/docs/8.2/functions-comparison.html, only lists `=`
Example Synapse 500 error when using `/_matrix/client/unstable/org.matrix.msc3030/rooms/!HBehERstyQBxyJDLfR:my.synapse.server/timestamp_to_event?ts=1644278400000&dir=b`:
```
2022-02-17 …
```
> Fix 500 error with Postgres when looking backwards with the MSC3030 `/timestamp_to_event` endpoint

- changelog.d/12021.feature
- synapse/rest/client/account.py
- tests/rest/client/test_account.py
> Use stable MSC3069 `is_guest` flag on `/whoami`

- changelog.d/12004.doc
- docs/admin_api/user_admin_api.md
- synapse/module_api/__init__.py
- synapse/storage/databases/main/registration.py
This updates some docstrings with some info from discussions
Open questions:
* Does this sound fine or should we really be validating those?
* Should we update the markdown documentation?
* Should we update the documentation for the module API?
> Document why auth providers aren't validated in the admin API

- changelog.d/11984.misc
- mypy.ini
- synapse/handlers/presence.py
- synapse/storage/databases/main/presence.py
- synapse/storage/databases/main/purge_events.py
- synapse/storage/databases/main/user_directory.py
- synapse/types.py
> Add type hints to `synapse/storage/databases/main`

- changelog.d/12034.misc
- synapse/federation/sender/per_destination_queue.py
- synapse/handlers/message.py
- synapse/handlers/register.py
These started failing in https://github.com/matrix-org/synapse/pull/12031... I'm a bit mystified by how they ever worked.
> Minor typing fixes

- changelog.d/12039.misc
- synapse/federation/federation_client.py
- synapse/handlers/federation.py
- synapse/storage/databases/main/room.py
A follow-up to #12005, in which I apparently missed that there are a bunch of other places that assume the create event is in the auth chain.
> remote join processing: get create event from state, not auth_chain

- changelog.d/12019.misc
- synapse/rest/client/auth.py
Untested, but no reason to believe this wouldn't work. Part of [Matrix 1.1](https://github.com/matrix-org/synapse/issues/11079) work, but not blocking.
> Use v3 endpoints for fallback auth (Matrix 1.1)

- changelog.d/12052.misc
- pyproject.toml
- setup.cfg
- tox.ini
To avoid confusion with setuptools, I'd like to move this config into pyproject.toml. (I don't think this is strictly required for #11537, but I think it's slightly neater.)
> Move isort config to `pyproject.toml`

- .github/workflows/release-artifacts.yml
- .github/workflows/tests.yml
- changelog.d/12051.misc
We seem to build sdists and wheel distributions in two places:
- `tests.yml`, on `develop`, ` release-*` and on PRs.
- `release-artifacts.yml`, on `develop`, `v.*` tags and on PRs.
In particular this means that we build these twice for all PRs, and twice on develop.
I propose that
- we stop build distributions in `tests.yml`.
- we trigger `release-artifacts.yml` on release branches. That means we'll now build debs and docker images on the release branch, not just on the release tag.
Additionally, I propose we make use of [the workflow in backend-meta](https://github.com/matrix-org/backend-meta/blob/main/.github/workflows/packaging.yml) to save a bit of yaml, and also make it slightly easier to switch over to poetry (#11537). The common workflow [uploads sdist and wheel with different …
> Tidy the building of sdists and wheels

- changelog.d/12033.misc
- tests/storage/databases/test_state_store.py
Follows on from #10870.
I felt like a few more tests wouldn't hurt.
> Add more tests for in-flight state query duplication.

- changelog.d/11985.feature
- changelog.d/11985.misc
- synapse/res/providers.json
- synapse/rest/media/v1/preview_url_resource.py
We found that some websites return opengraph information based
on the user agent.
In order to address this, using (bot) in the user agent string
may help the website behave correctly. When testing Twitter, we
found that the correct metadata is returned with the (bot) user
agent while it isn't for the default user agent.
This change additionally updates providers.json, as with the
user agent fix twitter will now return the expected openGraph
metadata.
- Start with a …
> Fetch images when previewing Twitter

- changelog.d/12013.misc
- synapse/federation/federation_base.py
- synapse/federation/federation_client.py
- synapse/federation/transport/client.py
- synapse/http/matrixfederationclient.py
- tests/federation/test_federation_client.py
- tests/unittest.py
This is an endpoint that we have server-side support for, but no client-side support. It's going to be useful for resyncing partial-stated rooms, so let's introduce it.
> Faster joins: Support for calling `/federation/v1/state`

- changelog.d/12058.feature
- docs/sample_config.yaml
- synapse/config/server.py
[MSC3589](https://github.com/matrix-org/matrix-doc/pull/3589) passed FCP, so we can use version 9 as the default.
Fixes #11697.
> Bump the default room version to 9 per MSC3589.

- changelog.d/11608.misc
- synapse/storage/databases/state/store.py
- tests/storage/databases/test_state_store.py
Small incremental change above #10870 that prevents too many concurrent requests being in-flight for a single state group, by just requesting the whole state filter from the database.
> Cap the number of in-flight requests for state from a single group

- .flake8
- MANIFEST.in
- changelog.d/12052.misc
- changelog.d/12059.misc
- setup.cfg
Similar to #12052: I want to move stuff away from setup.cfg where possible. However, this time I have an additional motivation. I've only been able to get `tox` and `poetry` to cooperate if `setup.cfg` and `setup.py` are nowhere to be seen. Otherwise, when `tox` invokes `pip`, the latter guesses we're in a setuptools project and tries to run `setup.py develop`, which fails.
Merging this will mean that only `check_manifest` config remains in setup.cfg. That isn't needed for poetry (it doesn't use a manifest file, but config in pyproject.toml). So we will soon be able to remove setup.cfg altogether.
> Prune setup.cfg some more

- changelog.d/12063.misc
- scripts-dev/complement.sh
The complement.sh script relies on the name of the ref matching the name
of the unpacked folder. The branch redirect from renaming the default
branch breaks that assumption.
(run the [linters](https://matrix-org.github.io/synapse/latest/developmen …
> Rename default branch of complement.sh to main

- changelog.d/12067.feature
- synapse/handlers/account.py
- synapse/rest/client/account.py
- tests/rest/client/test_account.py
These were added in #12001, and were snuck in since #12031 was started.
Also a couple of other cleanups while we're in the area.
> Remove more references to `get_datastore`

- changelog.d/12066.misc
- tests/rest/client/test_auth.py
- tests/rest/client/test_capabilities.py
- tests/rest/client/test_login.py
- tests/rest/client/test_sync.py
> Add type hints to `tests/rest/client`

- changelog.d/12068.misc
- synapse/handlers/sync.py
> Add logging to `/sync` for debugging #11916

- changelog.d/12069.misc
- synapse/storage/databases/main/events.py
- synapse/storage/persist_events.py
These popped up after I tried to type `get_datastores().main` as `DataStore` instead of `Any`.
> Minor typing fixes for `synapse/storage/persist_events.py`

- changelog.d/12069.misc
- changelog.d/12070.misc
- synapse/storage/databases/__init__.py
- synapse/storage/persist_events.py
Now that #12031 has landed, it's helpful if `Databases.main` wasn't `Any`.
> Ensure that `get_datastores().main` is typed

- changelog.d/12077.bugfix
- synapse/federation/federation_client.py
Related to #11694.
There was a bug in the failover logic for finding "unknown endpoints" in that it considered any 404 an unknown endpoint. This isn't always accurate though since some federation endpoints actually return a 404 for missing objects.
Note that I wrote [MSC3743](https://github.com/matrix-org/matrix-doc/pull/3743) to make this behavior less...annoying to deal with. That MSC has some information about where the bodies of the 404s come from (pretty much Conduit and Dendrite).
> Properly failover for unknown endpoints from Conduit/Dendrite

- changelog.d/12100.bugfix
- synapse/api/filtering.py
- synapse/push/push_rule_evaluator.py
- tests/api/test_filtering.py
- tests/push/test_push_rule_evaluator.py
frozendicts do not (necessarily) inherit from dict, so this needs to handle them correctly.
It seems like the Python version of `frozendict` *does* inherit from `dict`, which is why we have gotten away with this for so long. Versions of `frozendict` since 2.2 make it easier to install the C version (there are now prebuilt `manylinux` wheels).
> Fix `PushRuleEvaluator` and `Filter` to work on frozendicts

- changelog.d/12099.misc
- synapse/rest/client/capabilities.py
- synapse/rest/client/versions.py
Per changes to the MSC: [matrix-org/matrix-doc@`e640f6b` (#3440)](https://github.com/matrix-org/matrix-doc/pull/3440/commits/e640f6b95d828076003626d131c51a846be58e05).
> Move experimental support for MSC3440 to /versions.

- changelog.d/12109.misc
- synapse/handlers/message.py
- synapse/util/__init__.py
- synapse/util/async_helpers.py
- tests/util/test_async_helpers.py
An incremental improvement... by converting to async/await, we can reduce the amount of traceback data that gets lost.
Review commit-by-commit.
> Improve exception handling for concurrent execution

- changelog.d/12089.bugfix
- synapse/util/caches/descriptors.py
- tests/util/caches/test_descriptors.py
Fixes a CRITICAL "Unhandled error in Deferred" log message which happened when a function wrapped with `@cachedList` failed.
There's a couple of other tweaks here - review commit by commit.
> Fix 'Unhandled error in Deferred'

- changelog.d/12111.misc
- setup.py
This PR updates our classifiers defined in `setup.py` to advertise Synapse's support for Python 3.10.
I'm not entirely sure if this was omitted from https://github.com/matrix-org/synapse/issues/11780 on purpose or simply missed, but presenting it here for review.
> Advertise Python 3.10 support in setup.py

- changelog.d/11610.misc
- synapse/storage/databases/state/store.py
- tests/storage/databases/test_state_store.py
The rough idea is that we should favour re-using a small number of broad state filters that are already in-flight, rather than needing to wait for them ALL.
Builds on #10870 and #11608.
> Order in-flight state group queries in biggest-first order

- changelog.d/12106.misc
- synapse/util/async_helpers.py
- tests/util/test_async_helpers.py
This'll be generally useful for #3528.
In particular, it gets used in https://github.com/matrix-org/synapse/commit/ef5273847c5b0a8c71d2071b8299434dd457b026 (to be PRed)
> Add `stop_cancellation` utility function

- changelog.d/12062.feature
- docs/modules/third_party_rules_callbacks.md
- synapse/events/third_party_rules.py
- synapse/handlers/deactivate_account.py
- synapse/handlers/profile.py
- synapse/module_api/__init__.py
- tests/rest/client/test_third_party_rules.py
Part of the Tchap mainlining work.
Adds 2 new module callbacks: `on_profile_update` and `on_deactivation`, which are called after a profile update and a deactivation, respectively.
> Add module callbacks called for reacting to deactivation and profile update

- changelog.d/12105.bugfix
- synapse/util/async_helpers.py
- tests/util/test_rwlock.py
> Fix rare error in `ReadWriteLock` when writers complete immediately

- changelog.d/12088.misc
- synapse/app/__init__.py
- synapse/app/homeserver.py
- synapse/config/cache.py
- synapse/config/metrics.py
- synapse/config/oidc.py
- synapse/config/redis.py
- synapse/config/repository.py
- synapse/config/saml2.py
- synapse/config/tracer.py
- synapse/python_dependencies.py
- synapse/util/check_dependencies.py
- tests/util/test_check_dependencies.py
Part of #11537. We will have to use `importlib.metadata` to read our dependencies at runtime once we have moved to a declarative config. I do this now to ease the transition.
Before this change, python_dependencies has four confused purposes:
1. setup.py evaluates this to define matrix-synapse's dependencies and optional
dependencies.
2. The twisted olddeps CI job edit this file in-place so that we install the oldest
version of all dependencies. Similarly, the twisted trunk CI job patches this file
to use twisted trunk from github.
3. This data is made available at runtime for the application to check dependencies
are present and correctly versioned.
4. Finally, the script can be executed directly to print out all dependencies
(though this lacks the extras grouping information). This is …
> Use importlib.metadata to read requirements

- .github/workflows/tests.yml
- changelog.d/12119.misc
- docs/sample_config.yaml
- scripts-dev/check-newsfragment
- tox.ini
As part of #11537 we are going to move away from tox.
This pulls out two linting steps from tox which refer to the `scripts` directory. Will be useful for #12118.
> Detox, part 1 of N

- changelog.d/11808.misc
- synapse/storage/databases/main/state.py
- tests/handlers/test_room_summary.py
Fixes #11706.
Make method `get_room_version` use cached `get_room_version_id`.
**Signed-off by:** Lukas Denk, lukasdenk@web.de
> Make get_room_version use cached get_room_version_id.

- changelog.d/12113.misc
- tests/rest/client/test_relations.py
This is a grab bag of changes to the relations tests, most do not aim to change functionality. It should be reviewable commit-by-commit.
Note that the redaction tests get broken out into a separate class as more tests need to be added there for #12104 and #11753 and the current class is fairly monstrous. (And this PR exists as a precursor to those since it got sizeable by itself.)
> Improve the tests for relations

- changelog.d/12128.misc
- synapse/federation/federation_client.py
- synapse/handlers/room_summary.py
Since a string is a sequence, and this is all data from JSON we really only care about lists.
Fixes #12123
> Check if instances are lists, not sequences.

- changelog.d/12127.misc
- scripts-dev/release.py
As we want to include the previous version in the "No new changes..." string.
> Make release script write correct no-op changelog

- changelog.d/12136.misc
- tests/rest/client/test_typing.py
Noticed in #12108.
It's not clear what these do. `get_user_by_access_token` has the wrong
signature, including the return type. Tests all pass without these. I
think we should nuke them.
> Remove unused mocks from `test_typing`

- changelog.d/12129.misc
- synapse/util/check_dependencies.py
- tests/util/test_check_dependencies.py
#12088 was causing @clokep trouble. The error message:
```
✗ python -m [synapse.app](http://synapse.app/).homeserver --config-path demo/etc/8080.config 
ERROR:root:Need matrix-common==1.0.0, but got matrix-common==1.1.0
ERROR:root:Need mypy==0.910; extra == "dev", but got mypy==0.931
ERROR:root:Need mypy-zope==0.3.2; extra == "dev", but got mypy-zope==0.3.5
ERROR:root:Need mypy==0.910; extra == "mypy", but got mypy==0.931
ERROR:root:Need mypy-zope==0.3.2; extra == "mypy", but got mypy-zope==0.3.5
Missing Requirements: "matrix-common", "mypy", "mypy-zope", "mypy", "mypy-zope"
To install run:
pip install --upgrade --force "matrix-common" "mypy" "mypy-zope" "mypy" "mypy-zope"
```
The `matrix-common` is a well-meaning error. Patrick had the correct version on disk (presumably having upgraded …
> Don't impose version checks on dev extras at runtime

- changelog.d/12152.misc
- tox.ini
I've argued in #11537 that poetry and tox don't cooperate well at the
moment. (See also #12119.) Therefore I'm pruning away bits of `tox` to make the transition to poetry easier. This change removes the commands for `coverage`.
We don't use coverage in anger at the moment. It shouldn't be too hard to add `coverage` as a dev-dependency and reintroduce this if we really want it.
> Detox, part 2 of N

- changelog.d/11915.misc
- synapse/appservice/__init__.py
- synapse/handlers/appservice.py
- synapse/handlers/directory.py
- synapse/handlers/receipts.py
- synapse/handlers/typing.py
- tests/appservice/test_appservice.py
- tests/handlers/test_appservice.py
Another splitting out of refactoring work from #11881. This PR attempts to simplify the mental model of part of the ApplicationService class's interface - that which revolves around checking the AS's interest in various entities (rooms, users, events etc). It also attempts to correct some missing checks that may have been a result of the complexity.
In summary, the main changes are:
* Rename existing `ApplicationService` class methods:
* ApplicationServices.is_interested -> is_interested_in_event and add caching
* ApplicationService.is_interested_in_user -> is_user_in_namespace
* ApplicationService.is_interested_in_alias -> is_room_alias_in_namespace
* ApplicationService.is_interested_in_room_id -> is_room_id_in_namespace
* Add `is_interested_in_user` and `is_interested_in_room` methods …
> Rename various ApplicationServices interested methods

- changelog.d/12154.misc
- synapse/handlers/room_member.py
If we locally generate a rejection for an invite received over federation, it
is stored as an outlier (because we probably don't have the state for the
room). However, currently we still generate a state group for it (even though
the state in that state group will be nonsense).
By setting the `outlier` param on `create_event`, we avoid the nonsensical
state.
> Avoid generating state groups for local out-of-band leaves

- changelog.d/12156.misc
- synapse/state/__init__.py
- synapse/storage/state.py
We make multiple passes over these things, so a regular iterable won't do.
> Fix type of `event_ids` parameters in `StateGroupStorage` and `StateHandler`

- changelog.d/12155.misc
- synapse/visibility.py
- tests/test_visibility.py
Avoid trying to get the state for outliers, which isn't a sensible thing to do.
> Update client-visibility filtering for outlier events

- changelog.d/12132.feature
- synapse/federation/send_queue.py
- synapse/federation/sender/__init__.py
- synapse/federation/sender/per_destination_queue.py
- synapse/handlers/device.py
- synapse/replication/tcp/client.py
- tests/federation/test_federation_sender.py
This does to device list updates as to what #10398 did for presence.
The net effect of this is that we spread out starting new transmission loops when sending a device list update, up to a maximum of 30s. Hosts that already have a transmission loop running will send out the update immediately.
It's not super clear to me if this is acceptable. It means that a new device may not be able to read newly received messages for 30s after login. We may want to try and prioritise some hosts over others.
c.f. #7721
> Spread out sending device lists to remote hosts

- changelog.d/12138.removal
- synapse/rest/client/relations.py
- synapse/storage/relations.py
- tests/rest/client/test_relations.py
This removes the backwards compatibility (added in #11952) with the `RelationPaginationToken` for the `/relations` and `/aggregations/.../` endpoints.
From a user POV, this means that if someone makes a request on Synapse < v.1.52.0, then the administrator upgrades to Synapse >= v1.55.0 the pagination token will be rejected.
I think this is a fairly unlikely situation, but I'm not sure. 🤷 
Related to #11753.
> Remove backwards compatibility with RelationPaginationToken.

- changelog.d/12149.misc
- tests/util/test_async_helpers.py
`ObservableDeferred` already did the right thing, so let's ensure it continues to do the right thing with a test.
> Add test for `ObservableDeferred`'s cancellation behaviour

- changelog.d/12159.misc
- synapse/util/async_helpers.py
While poking around `ObservableDeferred`, I noticed that my IDE didn't understand the types of its attributes.
This'll be likely due to the use of `object.__setattr__` to set them.
> Add type hints for `ObservableDeferred` attributes
