changelog.d/12163.misc, synapse/storage/databases/main/deviceinbox.py
Right now we always hit the DB, even if the stream change cache reports that there are no new to-device messages for the users.
=> Reduce to-device queries for /sync.

changelog.d/12166.misc, synapse/python_dependencies.py
It’s just occurred to me that #12088 pulled in the “packaging” package (~=21.3). I pulled in the newest version I had at the time, and I didn’t check this with the packagers, sorry. (Also sorry to bring up the P-word again.)
I only use it for packaging.requirements.Requirements. Which was added in packaging 16.1: https://github.com/pypa/packaging/releases/tag/16.1
https://pkgs.org/download/python3-packaging suggests that the oldest version we care about is 17.1 in Ubuntu Bionic. So I think with this bound we're hunky dory.
=> Relax version guard for packaging

.github/workflows/tests.yml, changelog.d/12161.misc
I've factored it out for easier use in other workflows.
=> Switch the `tests-done` job to an Action

changelog.d/12177.bugfix, synapse/util/check_dependencies.py, tests/util/test_check_dependencies.py
Lovely `fix_bug=True` flag, if only it was always that easy :).
Fixes #12176.
=> Fix a bug introduced in 1.54.0rc1 which meant that Synapse would refuse to start if pre-release versions of dependencies were installed.

changelog.d/12175.bugfix, synapse/handlers/room_summary.py, tests/handlers/test_room_summary.py
Note that this was done properly for the `/spaces` API, but not the `/hierarchy` API.
Now with a test! 🎉 
Fixes #12169.
=> Do not return allowed_room_ids from /hierarchy response.

.github/workflows/release-artifacts.yml, changelog.d/12131.misc
#12051 separated the wheels and sdist artifacts, but our GHA stuff was not set up to attach them to the GitHub releases with their new locations.
This hopefully fixes those. (They're used in the release script but 404ed this time around.)
See also: https://github.com/matrix-org/synapse/runs/5393252759?check_suite_focus=true#step:4:10
=> Fix CI not attaching source distributions and wheels to the GitHub releases.

changelog.d/12173.misc, synapse/handlers/federation.py
We don't *have* the state at a backwards-extremity, so this is never going to do anything useful.
As part of my investigation, I stuck some debug in the middle of the code to see if it ever found a non-empty list of servers to fetch from, and ran it through sytest. It was never hit.
(part of my quest to sort out #12074)
=> Skip attempt to get state at backwards-extremities

changelog.d/12182.misc, synapse/replication/http/_base.py
Closes: #12178
Signed off by Nick Mills-Barrett <nick@beeper.com>
=> Retry some http replication failures

changelog.d/12187.misc, synapse/storage/databases/main/roommember.py
These were noticed while looking at some of the caching descriptors (+ PyCharm flagging them as unused).
=> Clean-up some unused variables

changelog.d/12197.misc, tests/storage/test_database.py
=> Remove dead code in `tests/storage/test_database.py`

changelog.d/12202.misc, tests/rest/client/test_retention.py
This test was relying on poking events which weren't in the database into `filter_events_for_client`, which is conflicting with my changes elsewhere.
The intention of the test is to see what happens when `filter_events_for_client` is called on events which should have expired, but are still in the db. So let's *actually* test that by leaving them in the db!
=> Retention test: avoid relying on state at purged events

changelog.d/12204.doc, docs/development/contributing_guide.md
Contributors can now sign off their contributions without revealing their legal name to the public.
This has existed for a little while now. It's time to write it down somewhere.
=> Note that contributors can sign off privately

changelog.d/12206.misc, synapse/handlers/device.py, synapse/handlers/presence.py, synapse/http/matrixfederationclient.py, synapse/http/server.py, synapse/rest/media/v1/_base.py, synapse/server.py, synapse/storage/databases/main/registration.py, synapse/storage/schema/main/delta/30/as_users.py, synapse/util/caches/treecache.py, tests/handlers/test_password_providers.py
I was attempting to use `autoflake` to find unused variables, but it just removed a bunch of unneeded `pass` calls. I see no reason not to do this though. 🤷
=> Remove unnecessary passes.

changelog.d/12208.misc, mypy.ini, tests/rest/client/test_transactions.py, tests/rest/media/v1/test_media_storage.py, tests/rest/media/v1/test_url_preview.py
=> Add type hints to `tests/rest`

changelog.d/12210.misc, docs/sample_config.yaml, docs/templates.md, synapse/config/oidc.py, synapse/handlers/oidc.py, synapse/handlers/sso.py, synapse/res/templates/sso_auth_account_details.html, synapse/rest/synapse/client/pick_username.py
Fixes https://github.com/matrix-org/synapse/issues/12205
cc @reivilibre
=> Update the SSO username picker template to comply with SIWA guidelines

changelog.d/12211.misc, synapse/handlers/typing.py, synapse/replication/tcp/handler.py, synapse/replication/tcp/resource.py, synapse/replication/tcp/streams/_base.py
@H-Shay and I took a look at some typing replication stuff; these things in particular both confused me and were easy enough to 'fix'.
The surrounding code is a little bit spaghetti-like due to how it's fairly generic; I haven't taken a crack at that (yet) but hopefully this
is a worthy incremental improvement on its own.
(cc @H-Shay: do these changes make it easier for you to read as well?)
=> Improve code documentation for the typing stream over replication.

changelog.d/12212.feature, docs/sample_config.yaml, docs/templates.md, synapse/config/oidc.py, synapse/handlers/oidc.py, synapse/util/templates.py
When discussing config changes for https://github.com/matrix-org/synapse/issues/12205, we concluded that we want to use email address localparts. We don't have a filter for that currently, so this PR adds one:
```python
>>> from synapse.util.templates import _localpart_from_email_filter
>>> from jinja2.environment import Environment
>>> env = Environment()
>>> env.filters.update({"localpart_from_email": _localpart_from_email_filter})
>>> t = env.from_string("{{ email|localpart_from_email }}")
>>> t.render(email="foo@bar.com")
'foo'
>>> t.render(email="foo@bar.com@example.com")
'foo@bar.com'
>>> 
```
=> Implement a Jinja2 filter to extract localparts from email addresses

changelog.d/12200.removal, docs/upgrade.md, synapse/app/generic_worker.py, synapse/config/experimental.py, synapse/federation/transport/server/__init__.py, synapse/rest/__init__.py, synapse/rest/admin/__init__.py
The first part of #11584, this:
1. Adds an experimental configuration flag for groups (but enables it by default).
2. Places the groups/communities endpoints behind the configuration flag.
3. Documents that groups/communities are deprecated.
=> Deprecate the groups/communities endpoints

changelog.d/12180.misc, synapse/util/async_helpers.py, tests/util/test_async_helpers.py
`delay_cancellation` behaves like `stop_cancellation` (#12106), except it
delays `CancelledError`s until the original `Deferred` resolves.
This is handy for unifying cleanup paths and ensuring that uncancelled
coroutines don't use finished logcontexts.
Comes from a suggestion by @erikjohnston.
As part of these changes I've ended up updating some of the `stop_cancellation` code and tests.
Generally useful for #3528.
- Feel free to credit …
=> Add `delay_cancellation` utility function

changelog.d/12215.bugfix, synapse/storage/databases/main/search.py
=> Fix broken background updates when using sqlite with `enable_search` off

changelog.d/12225.misc, synapse/handlers/sync.py, synapse/push/bulk_push_rule_evaluator.py, synapse/storage/databases/main/account_data.py, synapse/visibility.py, tests/storage/test_account_data.py
Instead of parsing the account data in multiple places, this uses the `ignored_users` table to fetch all users that are ignored by a user (previously we were only using it to calculate all users which ignore a specific user).
There was concern in #11964 that this would need another index, but it does not the uniqueness that's on the table can be used:
```sql
=> EXPLAIN SELECT ignored_user_id FROM ignored_users WHERE ignorer_user_id = '@clokep:matrix.org';
QUERY PLAN                                             
----------------------------------------------------------------------------------------------------
Index Only Scan using ignored_users_uniqueness on ignored_users  (cost=0.41..4.45 rows=2 width=25)
Index Cond: (ignorer_user_id = '@clokep:matrix.org'::text)
(2 rows)
```
Fixes …
=> Use the ignored_users table when testing event visibility.

changelog.d/12219.misc, synapse/rest/media/v1/preview_html.py, synapse/rest/media/v1/preview_url_resource.py, tests/rest/media/v1/test_html_preview.py
@reivilibre asked me to use `urljoin` instead of our own rebasing logic in https://github.com/matrix-org/synapse/pull/11767#discussion_r789506708, from that I further cleaned up some of the logic around rebasing URLs.
This should be reviewable commit-by-commit, but the gist is:
1. Use [`urljoin`](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urljoin) instead of re-implementing the logic.
2. Realization that we do not need to call `rebase_url` in multiple places, so remove a call to it.
3. Inline the rebase URL logic.
I think overall this is a nice clean-up, but let me know if you have questions!
=> Clean-up logic for rebasing URLs

changelog.d/12232.misc, tests/rest/client/test_relations.py
This refactors the relations tests a bit:
* Moves out pagination tests to a separate class.
* Move the assertion of the response code into the `_send_relation` helper (which is used in like every test...)
* Moves some helpers into the base-class (note that this isn't terribly useful *in this PR*, but I plan to use them in a few different future PRs).
Mostly making this a separate PR since it is only refactoring and because I want these changes in multiple separate PRs (#12228 and the follow-on to #12227) and hoping it will help parallelize them.
=> Refactor relations tests

changelog.d/12227.misc, synapse/handlers/pagination.py, synapse/handlers/relations.py, synapse/rest/client/relations.py, synapse/server.py
This is some pre-work towards #11753, it injects a handler layer between the rest and datastore layers, as much of our other code has.
A partial goal of this is to make the relations code a bit closer to the pagination code, so this mirrors more of the `RoomMessageListRestServlet` -> `PaginationHandler.get_messages()` -> `StreamWorkerStore.paginate_room_events()` flow.
=> Refactor relations code to avoid duplication

changelog.d/12240.misc, mypy.ini, tests/handlers/test_cas.py, tests/handlers/test_federation.py, tests/handlers/test_presence.py, tests/push/test_http.py
=> Add type hints to some tests files

changelog.d/12242.misc, scripts-dev/release.py
Quick and dirty.
```
$ scripts-dev/release.py announce 
Hi everyone. Synapse 1.55.0rc1 has just been released.
[notes](https://github.com/matrix-org/synapse/releases/tag/v1.55.0rc1) |[docker](https://hub.docker.com/r/matrixdotorg/synapse/tags?name=v1.55.0rc1) | [debs](https://packages.matrix.org/debian/) | [pypi](https://pypi.org/project/matrix-synapse/1.55.0rc1/)
Announce the RC in
- #homeowners:matrix.org (Synapse Announcements)
- #synapse-dev:matrix.org
```
=> Generate announcement links in release script

changelog.d/12246.doc, docs/modules/spam_checker_callbacks.md, synapse/events/spamcheck.py, synapse/handlers/user_directory.py, synapse/module_api/__init__.py, synapse/rest/client/user_directory.py, synapse/storage/databases/main/user_directory.py, synapse/types.py
Fixes #12245.
I'm not completely sure how I feel about using a `TypedDict` here, but
- using a namedtuple or attrs struct would mean the diff had to update a bunch of tests
- we don't do very much with the user profile data; deserialising to a struct only to reseralise to a dict seemed like overkill
- more compellingly, the spam checker callback already expects a dictionary, so let's keep giving them a dictionary
Not convinced the documentation change is super easy to read. All thoughts are welcome.
=> Correct `check_username_for_spam` annotations and docs

changelog.d/12243.doc, docs/workers.md
Fixes #12229.
These were missed in [`44853ea` (#11599)](https://github.com/matrix-org/synapse/pull/11599/commits/44853ea070646a3bdac4cf567fd43997afea6932).
=> Sync more worker regexes in the documentation.

changelog.d/12228.bugfix, synapse/storage/databases/main/relations.py, tests/rest/client/test_relations.py, tests/server.py
This makes the code match the comment: we should only attempt to fetch whether the current user has participated in a thread *if there's actually a thread at all on that event*.
As part of this I implemented a way for unit tests to assert the number of database transactions occurring, which I checked is decreased by this PR. 🎉 
~~Depends on #12232.~~
Reviewable commit-by-commit (much of the code-change is refactoring some test code).
=> Only fetch participated for events with threads

changelog.d/12237.misc, synapse/events/utils.py, synapse/handlers/pagination.py, synapse/handlers/relations.py, synapse/handlers/room.py, synapse/handlers/search.py, synapse/handlers/sync.py, synapse/rest/client/room.py, synapse/storage/databases/main/relations.py
Follow-up to #12227, which moves some more code to the handler. `get_bundled_aggregations` is pretty high-level and doesn't make sense to be in the datastore IMO. @reivilibre seemed to agree in the review of #12227.
This is a lift-and-shift of `get_bundled_aggregations`, `_get_bundled_aggregations_for_event`; and then a rename of some private methods.
=> Move get_bundled_aggregations to relations handler.

changelog.d/12244.misc, synapse/util/check_dependencies.py, tests/util/test_check_dependencies.py
=> Try to detect borked package installations.

changelog.d/12087.bugfix, synapse/federation/federation_server.py, synapse/handlers/federation.py
Fixes #12074
The main fix here is the `if event.internal_metadata.outlier` condition, which makes sure we return a sensible result in this situation, but I suggest reviewing commit-by-commit as there are a few other cleanups while we're here.
=> Return a 404 from `/state` for an outlier

changelog.d/12258.misc, synapse/app/homeserver.py
Super quick one; this can provide significant bandwidth savings pulling metrics from
synapse instances.
Signed off by Nick @ Beeper
=> Make it possible to enable compression for the metrics HTTP resource

changelog.d/12260.misc, synapse/res/templates/sso_auth_account_details.html
Fixes #12259; enhances #12210 and addresses part of #12205.
=> Reword 'Choose your user name' as 'Choose your account name' in the SSO registration template, in order to comply with SIWA guidelines.

changelog.d/12265.misc, synapse/res/templates/sso_auth_account_details.html, synapse/res/templates/sso_auth_account_details.js, synapse/res/templates/sso_footer.html
=> Tweak copy for sso account details template

changelog.d/12250.feature, synapse/module_api/__init__.py, tests/module_api/test_api.py
=> Allow registering admin users using the module API

changelog.d/12038.misc, docs/workers.md, synapse/rest/client/mutual_rooms.py, synapse/rest/client/shared_rooms.py
Resolves https://github.com/matrix-org/synapse/issues/10339
=> Remove mutual_rooms `update_user_directory` check, and add extra documentation

changelog.d/12269.misc, setup.py, synapse/storage/database.py, synapse/storage/engines/__init__.py
This didn't find anything interesting---one problem that I've suppressed
for now. But it feels good to feed more types into mypy's belly where
possible.
=> Use psycopg2 type stubs

changelog.d/12262.misc, docs/postgres.md, docs/sample_config.yaml, synapse/config/database.py, synapse/storage/engines/postgres.py, tests/storage/test_unsafe_locale.py
Currently Synapse will refuse to start new deployments if they have an unsafe DB locale. This PR extends that behavior to existing deployments, unless the user sets the new config flag `allow_unsafe_locale` added in this PR. Fixes #12055.
=> Refuse to start if DB has an unsafe locale

changelog.d/12266.misc, synapse/config/server.py, synapse/handlers/account.py, tests/rest/client/test_account.py
Add a configuration option to include account validity expiration info in the responses to MSC3720 account status requests. This is because DINUM wants to use this info in Tchap.
I'm reluctant to add this new configuration flag to the sample configuration. It's not compliant with the MSC, account validity isn't part of the Matrix spec (and imo shouldn't be), and I don't want clients to start relying on them (apart from closed, controlled deployments like Tchap). Happy to discuss this further if the reviewer thinks otherwise.
=> Optionally include account validity in MSC3720 account status responses

changelog.d/12227.bugfix, changelog.d/12227.misc, changelog.d/12232.bugfix, changelog.d/12232.misc, changelog.d/12285.bugfix, synapse/handlers/relations.py, tests/rest/client/test_relations.py
This is part of the last bit needed for #11753; we need to ensure that if a user ignores another user, their related events are properly ignored.
This PR (which is split from #12235) handles filtering events from an ignored user in `/relations`.
As #12235 is about to come a bit more complicated I figured it was worth while to separate this out to a separate PR since the diff is more self-contained.
=> Do not consider events by ignored users for relations

changelog.d/12289.misc, synapse/push/mailer.py, synapse/python_dependencies.py
The Jinja2 recently [removed](https://jinja.palletsprojects.com/en/3.1.x/changes/#version-3-1-0) the long-deprecated `Jinja2.Markup` property, instead advising callers to import `Markup` from the [markupsafe](https://pypi.org/project/MarkupSafe/) library directly.
This PR:
* Adds a direct dependency on MarkupSafe as we now import from it. Pinned to the currently major version of `2`.
* Replaces uses of `Jinja2.Markup` with `markupsafe.Markup`
=> Replace instances of deprecated `Jinja2.Markup` with `markupsafe.Markup`

synapse/push/mailer.py, synapse/python_dependencies.py
Reverts matrix-org/synapse#12289. Due to https://github.com/matrix-org/synapse/issues/12294.
=> Revert "Replace instances of deprecated `Jinja2.Markup` with `markupsafe.Markup`"

changelog.d/12297.misc, synapse/python_dependencies.py
Pins [Jinja2](https://pypi.org/project/jinja2/) to <3.1.0, as 3.1.0 removed the deprecated `jinja2.Markup` class which we still rely on.
An alternative to https://github.com/matrix-org/synapse/pull/12289, which ended in https://github.com/matrix-org/synapse/issues/12294.
=> Pin Jinja to <3.1.0

.github/workflows/tests.yml, changelog.d/12283.misc
The issues which meant concurrency caused flakey tests has been resolved for over a month now without issue ( https://github.com/matrix-org/complement/pull/318 ) so it's safe to re-enable this for Synapse.
For context, this reduces the total time from ~9m 52s to ~8m 11s. Most of the savings are during the actual running of the tests, which has gone from 7m 20s to 5m 47s.
=> Re-enable concurrency on Complement

changelog.d/12301.misc, synapse/federation/federation_server.py
It is currently rather hard to see which rooms are causing inbound federation traffic. Add the room id to the logs.
Currently, this log line looks like:
```
2022-03-25 09:13:55,104 - synapse.federation.federation_server - 1096 - INFO - _process_incoming_pdus_in_room_inner-829556 - handling received PDU: <FrozenEventV3 event_id=$Hk4ESFnYBbj9Ph-6Lx3PD-obTuOWzndD2hNk7du_SCU, type=m.room.message, state_key=None, outlier=False>
```
=> Enhance logging for inbound federation events

changelog.d/12272.misc, synapse/push/bulk_push_rule_evaluator.py, synapse/storage/databases/main/cache.py, synapse/storage/databases/main/events.py, synapse/storage/databases/main/roommember.py, synapse/storage/persist_events.py
This should speed up push rule calculations for rooms with large numbers of local users when the main push rule cache fails.
=> Add cache for `get_membership_from_event_ids`

changelog.d/12311.misc, synapse/storage/database.py
Should be a commit-by-commit review.
This was something that I agreed to look into whilst I was in the area.
Turns out the `*args` was not necessary; there's only one arg here (an iterable of value rows).
I also added a comment to `_do_execute`, where we could improve the type annotations easily a little bit
once `ParamSpec` is more usable.
=> Improve type annotations for `execute_values`.

changelog.d/12195.feature, synapse/module_api/__init__.py
Part of the Tchap mainlining. On Tchap, users register with their work email address, which is automatically associated on Sydent using Sydent's internal API. These associations then need to be stored in Synapse's database. The idea is to move that into a module that implements [`on_user_registration`](https://matrix-org.github.io/synapse/latest/modules/account_validity_callbacks.html#on_user_registration), binds the 3pid, and then inserts the association into the database.
Ideally I would have copied over `add_user_bound_threepid` into the module, but it requires doing an upsert which isn't trivial from a module.
=> Allow modules to store already existing 3PID associations

changelog.d/12313.misc, synapse/push/mailer.py, synapse/python_dependencies.py
* Reverts https://github.com/matrix-org/synapse/pull/12296
* Pins `Jinja2>=3.0`
Fixes https://github.com/matrix-org/synapse/issues/12294
=> Un-revert Jinja2 fix

changelog.d/12255.misc, mypy.ini, synapse/storage/databases/main/media_repository.py, synapse/storage/databases/main/receipts.py, synapse/storage/databases/main/registration.py, synapse/storage/databases/main/room.py, synapse/storage/databases/main/search.py, synapse/storage/databases/main/state.py, synapse/storage/databases/main/stats.py, synapse/storage/databases/main/user_directory.py, synapse/storage/engines/__init__.py
=> Add some type hints to datastore

changelog.d/12314.misc, synapse/storage/databases/main/event_federation.py
When we are processing a `/backfill` request from a remote server, exclude any
outliers from consideration early on. We can't return outliers anyway (since we
don't know the state at the outlier), and filtering them out earlier means that
we won't attempt to calculate the state for them.
part of my work on fixing #12074.
=> Exclude outliers in `on_backfill_request`

changelog.d/12320.misc, contrib/jitsimeetbridge/jitsimeetbridge.py, setup.py, synapse/api/constants.py, synapse/appservice/scheduler.py, synapse/crypto/keyring.py, synapse/events/utils.py, synapse/http/proxyagent.py, synapse/replication/http/_base.py, synapse/rest/media/v1/media_storage.py, synapse/rest/media/v1/preview_html.py, synapse/storage/database.py, synapse/util/patch_inline_callbacks.py, synapse/util/retryutils.py, tests/handlers/test_federation.py, tests/replication/_base.py
To include https://github.com/psf/black/pull/2966 which is necessary
after https://github.com/pallets/click/issues/2198.
This should hopefully fix CI. Shoutout to #11537.
=> Bump `black` and `click` versions

CHANGES.md, changelog.d/12322.misc, docs/upgrade.md
This was added in https://github.com/matrix-org/synapse/pull/12091, which was expected to land in the v1.55 release. However, it was first included in v1.56.0rc1, and thus the upgrade notes need to be moved to the right version section.
Uses the same changelog as https://github.com/matrix-org/synapse/pull/12091.
=> Move warning of open registration to v1.56 upgrade notes

changelog.d/12326.misc, mypy.ini, synapse/config/key.py, synapse/crypto/keyring.py, synapse/events/builder.py, synapse/rest/key/v2/local_key_resource.py, synapse/rest/key/v2/remote_key_resource.py, tests/crypto/test_event_signing.py, tests/rest/key/v2/test_remote_key_resource.py
This depends on a (now-released) fix to signedjson which marks the SigningKey and VerifyKey as things that can be directly converted to `bytes`.
Fixes #12324.
Relates to #12325.
=> Fix typechecker problems exposed by signedjson 1.1.2

changelog.d/12310.feature, docs/sample_config.yaml, synapse/config/server.py, synapse/handlers/sync.py, synapse/storage/databases/main/roommember.py, synapse/storage/databases/main/stream.py, tests/rest/client/test_sync.py
Part of the Tchap mainlining.
This is in order to implement the new plan for user discovery. See https://github.com/matrix-org/synapse-dinsic/issues/125 for the high-level description and https://docs.google.com/document/d/1wQw1OMgqn0blbv4Jt7ApZhR8mtN39ZLkNHKuNY-Xd_M/edit for the detailed action plan (which this work is a part of).
=> Add a configuration to exclude rooms from sync response

changelog.d/12271.doc, docs/development/contributing_guide.md
I thought it would be sensible to document these whilst I remember.
=> Flesh out documentation for running SyTest against Synapse, including use of Postgres and worker mode.

changelog.d/12333.bugfix, synapse/rest/media/v1/preview_url_resource.py, tests/rest/media/v1/test_url_preview.py
Fixes https://github.com/matrix-org/synapse/issues/12328
Introduced in https://github.com/matrix-org/synapse/pull/688
=> Ensure the type of URL attributes is always str when matching against preview blacklist

.github/workflows/tests.yml, changelog.d/12334.misc, tox.ini
It only checks the manifest. Once #11537 lands there won't be a manifest
any more.
=> Nuke the tox `packaging` job

.gitignore, changelog.d/12335.misc
`direnv` + either 
- `layout python` or 
- `layout poetry` with config as described in https://github.com/direnv/direnv/wiki/Python#poetry 
works well for me. Its configuration file is `.envrc`. I happen to know @reivilibre uses it too and finds is a pleasurable.
I haven't committed an `.envrc` file because I don't want to
introduce clutter for people who aren't using direnv, and because I
suppose in principle someone could choose to use a different layout.
=> Ignore .envrc for direnv users

changelog.d/12332.misc, synapse/visibility.py, tests/test_visibility.py
The intention here is to avoid doing state lookups for outliers in `/_matrix/federation/v1/event`. Unfortunately that's expanded into something of a rewrite of `filter_events_for_server`, which ended up trying to do that operation in a couple of places.
First of all, note that there is a long-standing fudge here, where we return outliers via `/_matrix/federation/v1/event` to any server that is *currently* in the room, even though we don't know the `history_visibility` in force at the time of the event, nor if the server was in the room at that time (which are normally prerequisites for allowing this). This *has* to be the case, because the federation protocol relies on being able to pull `auth_events` for a given event in this manner (and we have no way to show that the server should …
=> Handle outliers in `/federation/v1/event`

changelog.d/12341.feature, synapse/module_api/__init__.py, tests/module_api/test_api.py
Signed-off-by: Amanda Graven <amanda@graven.dev>
=> Add set_user_admin function to the module API

changelog.d/12327.feature, docs/SUMMARY.md, docs/modules/account_data_callbacks.md, docs/modules/writing_a_module.md, synapse/handlers/account_data.py, synapse/module_api/__init__.py, tests/rest/client/test_account_data.py
Part of the Tchap mainlining.
This is in order to implement the new plan for user discovery. See https://github.com/matrix-org/synapse-dinsic/issues/125 for the high-level description and https://docs.google.com/document/d/1wQw1OMgqn0blbv4Jt7ApZhR8mtN39ZLkNHKuNY-Xd_M/edit for the detailed action plan (which this work is a part of).
More specifically, this callback will be used by the module that will maintain the "red list" to change a user's visibility when the right account data changes.
=> Add a module callback to react to account data changes

changelog.d/12040.feature, synapse/handlers/federation_event.py, synapse/storage/databases/main/events_worker.py, tests/handlers/test_federation_event.py
If we're missing most of the events in the room state, then we may as well call the `/state` endpoint, instead of individually requesting each and every event.
Builds on #12013 which added the `get_room_state` method.
Requires the changes to sytest which landed in matrix-org/sytest#1223, and those which have yet to land in https://github.com/matrix-org/sytest/pull/1231.
=> Optimise `_get_state_after_missing_prev_event`: use `/state`

changelog.d/12191.misc, synapse/storage/databases/main/state.py, synapse/storage/state.py, tests/handlers/test_federation.py
Rather than silently returning an invalid result when someone tries to get the state at an outlier event, raise an exception.
~~Based on #12332~~ now rebased
=> Raise an exception when getting state at an outlier

changelog.d/12348.misc, tests/rest/client/test_account.py, tests/storage/test_cleanup_extrems.py, tests/unittest.py
These methods are only used by a single testcase, so they shouldn't be
cluttering up the base `TestCase` class.
=> Move single-use methods out of `TestCase`

changelog.d/12350.bugfix, synapse/handlers/room.py, tests/module_api/test_api.py, tests/rest/client/utils.py, tests/storage/test_cleanup_extrems.py
Our tests pretty heavily depend on the broken behaviour, so I changed our test helper to default to creating public rooms rather than 'default' rooms, since I think that matches the casual style of most tests anyway.
(Tests are usually not too fussed about privacy rules and just want some users in a room!)
Should be a commit-by-commit review. Just a quick fix to #11498.
=> Default to `private` room visibility rather than `public` when a client does not specify one, according to spec.

changelog.d/12346.misc, tests/handlers/test_deactivate_account.py, tests/handlers/test_profile.py, tests/handlers/test_sync.py, tests/module_api/test_api.py, tests/replication/slave/storage/test_events.py, tests/rest/admin/test_server_notice.py, tests/rest/client/test_rooms.py, tests/storage/test_id_generators.py, tests/storage/test_redaction.py, tests/storage/test_stream.py, tests/test_visibility.py, tests/unittest.py
There are a bunch of places we call `get_success` on an immediate value, which is unnecessary. Let's rip them out, and remove the redundant functionality in `get_success` and friends.
=> Remove redundant `get_success` calls in test code

changelog.d/12347.misc, mypy.ini, tests/handlers/test_e2e_keys.py, tests/handlers/test_federation.py, tests/handlers/test_oidc.py, tests/handlers/test_user_directory.py, tests/rest/admin/test_media.py, tests/rest/admin/test_user.py, tests/server.py, tests/storage/databases/main/test_lock.py, tests/storage/test_appservice.py, tests/unittest.py
In particular, add type hints for `get_success` and friends, which are then helpful in a bunch of places.
Needs a few fixes, so review commit-by-commit.
=> Add type hints for `tests/unittest.py`.

changelog.d/12367.feature, synapse/replication/slave/storage/devices.py, synapse/storage/databases/main/__init__.py
This makes restarting the synchrotrons less of a pain
=> Prefill the device_list_stream_cache

changelog.d/12329.bugfix, synapse/handlers/room_batch.py
Allow non-member state sent in room batch to resolve for historic events. `/batch_send` `state_events_at_start`
Previously, non-member state didn't resolve because [`filter_events_for_client`](https://github.com/matrix-org/synapse/blob/e0bb2681340752f2716f1f386139ca37c53f26cd/synapse/visibility.py#L44) [filters out all `outlier` state](https://github.com/matrix-org/synapse/blob/e0bb2681340752f2716f1f386139ca37c53f26cd/synapse/visibility.py#L79-L81) except for out-of-band membership.
Part of https://github.com/matrix-org/synapse/issues/12110
Complement test: https://github.com/matrix-org/complement/pull/354
Part of [MSC2716](https://github.com/matrix-org/matrix-spec-proposals/pull/2716)
- Be a short description of your change which makes sense to users. "Fixed a bug that prevented …
=> Allow non-member state sent in room batch to resolve for historic events (MSC2716)

changelog.d/12369.doc, docs/workers.md
As the title states. Fixes #12359.
=> Update broken link in `workers.md`

changelog.d/12317.misc, synapse/types.py
Explain how to decipher live and historic pagination tokens
- `s2633508_17_338_6732159_1082514_541479_274711_265584_1`
- `t426-2633508_17_338_6732159_1082514_541479_274711_265584_1`
Fix https://github.com/matrix-org/synapse/issues/12305
(run the …
=> Explain how to decipher live and historic pagination tokens

changelog.d/12376.misc, docs/development/contributing_guide.md, tests/server.py, tests/utils.py
Due to weirdness, my local dev machine has its Postgres UNIX socket specified as number 5433 rather than 5432,
so I need to be able to specify the port to run the tests locally.
This adds an environment variable to the tests that allows you to specify the Postgres port.
I also update the documentation and describe how to use this environment variable, as well as the fact that most of these
are optional if you're using a well-configured Postgres server with a UNIX socket, as is common on Debians/Ubuntus.
=> Allow specifying the Postgres database's port when running unit tests with Postgres.

changelog.d/12364.bugfix, synapse/federation/transport/client.py
Fixes the sending half of #10304.
Synapse is able to **accept** either strings or integers (and likely floats and bools ... sigh), but should really only emit spec-approved integers.
Enforcing this requirement on the receiving side is out of scope for this PR, but we might consider it someday, after giving enough time for Synapse versions to spread throughout the network.
=> Fix a spec compliance issue where requests to the `/publicRooms` federation API would specify `limit` as a string.

changelog.d/12353.misc, tests/util/test_linearizer.py
To fix #12114, it might be useful to convert the `Linearizer` from raw `Deferred`s to async. But first, we need to convert the tests.
Probably easier to review commit by commit. There's a commit in the middle that adds comments, so that the correspondence between `inlineCallbacks` and async code is clearer.
- Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of …
=> Convert `Linearizer` tests from `inlineCallbacks` to async

changelog.d/12366.misc, synapse/types.py
`StreamToken.from_string` and `RoomStreamToken.parse` are both async
methods that could be cancelled. These methods must not replace
`CancelledError`s with `SynapseError`s.
(run the [linters](https://matrix-org.github.io/synapse/latest/development/contribu …
=> Make `StreamToken` and `RoomStreamToken` methods propagate cancellations

.github/workflows/docs.yaml, changelog.d/12339.doc
Update `mdbook` (the tool used to render the documentation website) to version 0.4.17. [Full changelog](https://github.com/rust-lang/mdBook/blob/master/CHANGELOG.md#mdbook-0417).
There's not really any particular reason, other than staying relatively up to date with our dependencies.
I've tested this version locally and all seems to work well.
=> Update mdbook to 0.4.17

changelog.d/12320.misc, changelog.d/12379.misc, synapse/python_dependencies.py
* Revert temporary pin of signedjson (ca7e34cb57a93ea48e7bb00b89c63b6f14989736).
* Remove changelog for #12320, which went into Synapse 1.56.0
=> Post 1.56.0 release tidy up

.gitignore, changelog.d/12381.misc, poetry.lock, pyproject.toml
As a first step towards poetry, commit its configuration and lockfile. Crucially, we leave the setuptools configuration in place and declare that our `[build-system]` is setuptools. This means that poetry isn't used unless one explicitly goes out of their way to run `poetry install`.
This is not a sustainable state to be in, because now the project metadata is duplicated in two places.
CI seems to be happy and this will allow us to break up the review.
I am assuming that:
- the twisted trunk CI job will continue to run successfully via setuptools
- the full set of debian builds succeed (only the debian sid build runs on PRs)
Xref #11537 .
=> Poetry: initial pyproject.toml and poetry.lock

changelog.d/12384.misc, poetry.lock, pyproject.toml, synapse/python_dependencies.py
Missed in #12088. We got away with it because we were indirectly
requiring it via other packages.
Without this change, we encounter pain in `poetry export`; and besides,
we should be explicit about our direct dependencies.
=> Add missing dependency on importlib_metadata

changelog.d/12389.misc, synapse/metrics/__init__.py, synapse/metrics/_gc.py, synapse/metrics/_reactor_metrics.py, synapse/metrics/_types.py, synapse/metrics/background_process_metrics.py, synapse/metrics/jemalloc.py, synapse/storage/databases/main/events.py
Principally, `prometheus_client.REGISTRY.register` now requires its argument to extend `prometheus_client.Collector`.
Additionally, `Gauge.set` is now annotated so that passing `Optional[int]` causes an error.
Fixes #12387.
=> Update type annotations for compatiblity with prometheus_client 0.14

changelog.d/12390.bugfix, synapse/storage/databases/main/events.py
Fixes a bug introduced in #11417 where we would only included backfilled events
in `synapse_event_persisted_position`.
=> Fix `synapse_event_persisted_position` metric

changelog.d/12400.misc, synapse/python_dependencies.py
`pyproject.toml` already has the version guard. I struggled to work out
how to reproduce this guard under setuptools in #12384. But I really
should have persisted there; without this, poetry and setuptools
generate different sets of requirements. That means a poetry-installed
Synapse on a 3.8+ interpreter will fail the runtime dependency checks.
=> Narrow the `importlib_metadata` dependency

changelog.d/12398.misc, synapse/handlers/identity.py
Fixes #11113.
Sydent since v2.5.0 has supported the stable identifier. This was released November 2021.
=> Remove the unstable identifier from MSC3288.

changelog.d/12370.bugfix, changelog.d/12370.feature
Update changelog to describe changes from #12370 relative to `develop`
Follow-up to https://github.com/matrix-org/synapse/pull/12370
Context: https://github.com/matrix-org/synapse/pull/12370#discussion_r842253671
(run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing …
=> Update changelog to describe changes from #12370 relative to `develop`

changelog.d/12345.doc, docs/development/room-dag-concepts.md
Clarify that we mark as outliers because we don't have any state for them
As discussed at https://github.com/matrix-org/synapse/pull/12179#discussion_r837263852
=> Clarify that we mark as outliers because we don't have any state for them

changelog.d/12403.feature, synapse/rest/client/relations.py, tests/rest/client/test_relations.py
Part of #11753, all the tasks in there which block enabling `v1/rooms/{roomId/relations/{eventId}` are done! 🎉
=> Support the v1 endpoint for `/relations`.

changelog.d/12380.misc, synapse/logging/opentracing.py, synapse/replication/tcp/external_cache.py
I don't think redis is causing any issues, but we should be adding spans whenever we talk to an external service.
=> Add opentracing spans to calls to external cache

changelog.d/12408.misc, synapse/handlers/sync.py, synapse/rest/client/sync.py
This was missed in #12200 -- if we disable groups/communities we should stop returning them as part of sync results.
=> Do not add groups to sync results if disabled.

changelog.d/12409.misc, synapse/handlers/sync.py
Currently causes future incremental syncs to fail.
Broke by #12191
=> Fix rejecting invites over federation

changelog.d/12415.misc, synapse/federation/federation_client.py, synapse/federation/transport/client.py, synapse/http/client.py, synapse/http/matrixfederationclient.py, synapse/http/types.py
Fixes #12411. Please see that issue for my motivation; otherwise, it should be accessible commit-by-commit.
These are mostly just type-hinting changes: but please note commits 904d57fd7e6259f1455940edc7eb3bce17c2e458 and 00f22d7c258531d68846e96273ddb3706b5f9b61, which include runtime changes. Those changes are intended to be no-ops, but please do check my reasoning.
The [documentation](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlencode) and [implementation](https://github.com/python/cpython/blob/3.10/Lib/urllib/parse.py#L911) of urlencode will likely be of interest!
=> Unify HTTP query parameter type hints

changelog.d/12420.misc, docs/code_style.md, pyproject.toml, scripts-dev/lint.sh, tox.ini
instead, configure the tools to find sensible targets.
Pulled out from #12337; part (but not all) of
e53e99edba7ccda8319ebd4fe832637cbe9261cc. Related: #12107.
=> Stop maintaining a list of lint targets

changelog.d/12421.misc, mypy.ini, synapse/_scripts/export_signing_key.py, synapse/_scripts/move_remote_media_to_new_store.py, synapse/_scripts/synapse_port_db.py, synapse/_scripts/update_synapse_database.py
A first pass. I plan to run a second pass to make the scripts pass `--disallow-untyped-defs`.
=> Make `synapse._scripts` pass typechecks

changelog.d/12252.feature, synapse/storage/database.py, synapse/storage/databases/main/client_ips.py, tests/storage/test__base.py
This easy optimisation was noticed in #10425 by anoa, and it seemed like the right time to implement these
(along with #12251). Not expecting super magical powers, but it might be a nice little improvement.
Depends on: #12251
=> Optimise `_update_client_ips_batch_txn` to batch together database operations.

.ci/scripts/test_export_data_command.sh, .github/workflows/tests.yml, changelog.d/12418.misc
=> CI: Fix the export-data job to run under poetry

.github/workflows/tests.yml, changelog.d/12404.misc, docker/README-testing.md, docker/complement/Dockerfile, docker/complement/README.md, docker/complement/SynapseWorkers.Dockerfile, docker/complement/conf-workers/caddy.complement.json, docker/complement/conf-workers/workers-shared.yaml, docker/complement/conf/homeserver.yaml, docker/complement/conf/log_config.yaml, docker/complement/conf/start.sh, scripts-dev/complement.sh
Fixes https://github.com/matrix-org/complement/issues/330 (or it will, once we remove the old files).
It's not *quite* a lift-and-shift: I've also taken the opportunity to get rid of the custom CA that we used to use to sign the TLS certs, which has been superceded by the CA exposed by Complement.
=> Move complement setup stuff into the Synapse repo

changelog.d/12422.misc, mypy.ini, synapse/_scripts/export_signing_key.py, synapse/_scripts/generate_config.py, synapse/_scripts/generate_log_config.py, synapse/_scripts/generate_signing_key.py, synapse/_scripts/hash_password.py, synapse/_scripts/move_remote_media_to_new_store.py, synapse/_scripts/register_new_matrix_user.py, synapse/_scripts/synapse_port_db.py, synapse/_scripts/synctl.py, synapse/_scripts/update_synapse_database.py, synapse/storage/types.py, tests/scripts/test_new_matrix_user.py
Follows on from #12421.
Suggest commit-by-commit review.
Most of these were trivial; two were not. 
- In d960589b08d11570dbee50d5334a98fc9e660682 the script's dependency injection was fighting the type system.
- There was simply a lot to do in c8139e02039432824a5b2cf07fda3f03f0cbf027.
=> Disallow untyped defs in synapse._scripts

changelog.d/12436.feature, synapse/config/experimental.py, synapse/handlers/search.py
[MSC3666](https://github.com/matrix-org/matrix-spec-proposals/pull/3666) has finished FCP, so this is stable now.
=> Remove experimental configuration flag for MSC3666.

changelog.d/12444.misc, poetry.lock, pyproject.toml, setup.py, synapse/python_dependencies.py
It was already pulled in for us by `treq`, but we should be explicit
that we do use the `tls` functionality of Twisted directly.
=> Specify tls extra for Twisted dependency.

.ci/scripts/test_old_deps.sh, .github/workflows/tests.yml, changelog.d/12407.misc, tox.ini
There are a few moving parts here.
- Once we ditch setup.py we'll need to patch the dependencies in pyproject.toml to maintain this CI job.
- If we were using poetry-core as our PEP 517 build system, it would suffice to `pip install .[all,test]`. But we're gradually transitioning to that; setuptools remains the build system for now.
- Therefore use the "full" poetry to _lock_ an olddeps environment and run using `poetry run`.
=> Poetry: select olddeps using `poetry`

changelog.d/12382.removal, synapse/api/constants.py, synapse/api/filtering.py, synapse/config/experimental.py, synapse/events/utils.py, synapse/handlers/message.py, synapse/rest/client/versions.py, synapse/server.py, synapse/storage/databases/main/events.py, synapse/storage/databases/main/relations.py, tests/api/test_filtering.py
Remove anything unstable from MSC3440.
Fixes #12148
=> Remove references to unstable identifiers from MSC3440.

changelog.d/12394.misc, synapse/handlers/federation.py, synapse/handlers/federation_event.py, synapse/storage/databases/main/events.py, synapse/storage/databases/main/events_worker.py, synapse/storage/databases/main/room.py, synapse/storage/databases/main/state.py, synapse/storage/persist_events.py
We work through all the events with partial state, updating the state at each of them. Once it's done, we recalculate the state for the whole room, and then mark the room as having complete state.
I'm afraid this doesn't really have any tests yet. I do have some Complement tests, but they need more bits of this to land.
Part of #11249, and a follow-up to #12012.
=> Resync state after partial-state join

changelog.d/12344.removal, docs/upgrade.md, synapse/config/experimental.py, tests/rest/admin/test_admin.py
This is the next bit of #11584 -- disabling groups by default, but leaving the configuration flag there to enable it.
**Blocked until develop is on Synapse v1.58.0.**
Requires matrix-org/sytest#1233.
=> Disable groups/communities by default.

changelog.d/12395.misc, synapse/federation/federation_server.py, synapse/federation/transport/client.py
Fixes #11345 which goes into more detail about this, but I think we can drop support for the unstable identifier in `send_join` responses from MSC3083, which was erroneously used for a bit after stabilization.
The stable identifier was added in Synapse v1.49.0; the unstable identifiers were added in Synapse v1.41.0; so 1.41.0 - 1.48.0 are potentially of concern? Of those I only see any significant set of servers on 1.42.0.
=> Remove the unstable event field for `/send_join` per MSC3083.

.github/workflows/tests.yml, changelog.d/12434.misc, poetry.lock, tox.ini
Pulled out from #12337.
- We don't recommend tox in `code_style.md`
- After #12107 it's much easier for black, isort and flake8 to find the
scripts we want them to lint; we don't need to maintain `lint_targets`
in the tox config. See also #12420.
=> Run lints under poetry in CI; remove lint tox jobs

.github/workflows/tests.yml, changelog.d/12438.misc
Olddeps and twisted trunk tests are handled in separate PRs.
The PyPy config is a best-effort only; it's completely untested.
Pulled out from #12337.
=> Run "main" trial tests under poetry

changelog.d/12445.misc, synapse/rest/client/versions.py
Altering the MSCs implementation as per [this MSC commit](https://github.com/matrix-org/matrix-spec-proposals/pull/2666/commits/591d3e55c97c9d4d92144e62cbcd8f868a96578b) …
=> Rename Mutual Rooms `unstable_features` flag to match MSC

.ci/patch_for_twisted_trunk.sh, .github/workflows/twisted_trunk.yml, changelog.d/12425.misc, poetry.lock
Pulled out from #12337.
Co-authored-by: Sean Quah <seanq@element.io>
Co-authored-by: Dan Callahan <danc@element.io>
=> Use poetry lockfile in twisted trunk CI job

changelog.d/12340.doc, docs/website_files/table-of-contents.js
If you try to print our docs currently: https://matrix-org.github.io/synapse/v1.55/print.html
...you will presented with about 6 pages of page headers before you finally get to the actual content. This is due to our custom table-of-contents renderer rendering all page titles upon page load. This is very useful for most pages, but not the print page (which shows all contents in the entire book).
This PR exits the table-of-contents loading code early if it notices that it's running on the print page.
=> docs: Don't render the table of contents on the print page

changelog.d/12466.misc, docker/configure_workers_and_start.py
When we run a worker-mode synapse under docker, everything gets logged to stdout. Currently, output from the workers is tacked with a worker name, for example:
```
2022-04-13 15:27:56,810 - worker:frontend_proxy1 - synapse.util.caches.lrucache - 154 - INFO - LruCache._expire_old_entries-0 - Dropped 0 items from caches
```
- note `worker:frontend_proxy1`. No such tag is applied to log lines from the master, which makes somewhat confusing reading.
To fix this, we generate a dedicated log config file for the master in the same way that we do for the workers, and use that.
=> Dockerfile-workers: give the master its own log config

changelog.d/12465.feature, synapse/handlers/device.py, synapse/storage/databases/main/devices.py, tests/federation/test_federation_sender.py, tests/storage/test_devices.py
=> Only send out device list updates for our own users

changelog.d/12467.misc, docker/complement/SynapseWorkers.Dockerfile, docker/complement/conf-workers/start-complement-synapse-workers.sh
... with a bit more verbosity.
=> complement-synapse-workers: factor out separate entry point script

changelog.d/12451.doc, docs/workers.md
We've been running them on m.org for a long time; asking around, it seems like it's just been forgotten about :).
=> Update documentation to reflect that `run_background_tasks_on` is no longer experimental.

changelog.d/12483.misc, synapse/storage/databases/main/state.py
=> Fix grammatical error in error message

changelog.d/12474.misc, synapse/federation/federation_server.py, synapse/federation/transport/server/federation.py, sytest-blacklist, tests/federation/test_federation_server.py
MSC2314 has now been closed, so we're backing out its implementation, which originally happened in #6176.
Unfortunately it's not a direct revert, as that PR mixed in a bunch of unrelated changes to tests etc.
=> Back out implementation of MSC2314

changelog.d/12476.bugfix, synapse/events/utils.py, synapse/rest/client/room.py, tests/rest/client/test_relations.py
This is what the MSC (now) requires. Fixes https://github.com/matrix-org/synapse/issues/10310.
=> Fix `/room/.../event/...` to return the *original* event after any edits

changelog.d/12496.bugfix, synapse/storage/databases/main/events_forward_extremities.py
=> Fix returned count of delete extremities admin API

.ci/latest_deps_build_failed_issue_template.md, .github/workflows/latest_deps.yml, changelog.d/12472.misc
Our old CI used to be this canary on every job. Now we are using poetry, we'll be using locked versions everywhere and so won't see problems coming from fresh `pip install matrix-synapse[all]` installations. Introduce this new job to try and cover that gap.
Based on the twisted trunk job. Runs an hour before the Twisted trunk job does. 
Not fully sure if mypy is appropriate here, see comments in the diff.
=> Add CI job to act as a canary for testing against latest dependencies

changelog.d/12427.feature, synapse/api/errors.py, synapse/config/experimental.py, synapse/handlers/events.py, synapse/rest/client/room.py, synapse/rest/client/versions.py, synapse/storage/databases/main/events_worker.py
This pull request implements the query parameter described in MSC2815 to allow room moderators and server admins to get the original content of redacted events using the `/rooms/{roomId}/event/{eventId}` endpoint.
Signed-off-by: Tulir Asokan <tulir@maunium.net>
=> Implement MSC2815: allow room moderators to view redacted event content

README.rst, changelog.d/12475.doc, docs/development/contributing_guide.md, docs/development/dependencies.md, docs/upgrade.md
- readme
- contributor guide
- upgrade notes
- new dev cheat sheet for poetry
=> Recommend poetry in docs

changelog.d/12512.docker, poetry.lock
The v1.56.0 image included v0.2.0 whereas the v1.57.0 image included v0.1.5, which broke homeservers that are using it with the generic module API.
Issue likely introduced by https://github.com/matrix-org/synapse/pull/12385/files?
Fixes https://github.com/matrix-org/matrix-synapse-ldap3/issues/162.
We'll want to release a patch release with this.
=> Include version 0.2.0 of the Synapse LDAP Auth Provider module in the Docker image.

changelog.d/12510.bugfix, synapse/res/templates/notif.html
Fixes #12506
`scale` in the template was referring to a non-existent variable, so Jinja replaces it with `""`, which causes a blank value in the resulting HTTP URL. Putting single quotes around it allows the true string value of `"scale"` to be used.
=> Fix Jinja templating error when generating thumbnail URLs.

changelog.d/12514.misc, mypy.ini, scripts-dev/lint.sh
Missed in #12478.
In particular this fixes running the linter script on `develop`.
=> Remove leftover references to setup.py

changelog.d/12520.bugfix, synapse/appservice/__init__.py, synapse/appservice/api.py
Having tried to test this feature out with the matrix-bot-sdk, I noticed that the MSC called for `device_unused_fallback_key_types` but Synapse was sending a `device_unused_fallback_keys` field instead. The bot-sdk seems to concur with the MSC, so I think we should probably fix this in Synapse.
=> MSC3202: Fix device_unused_fallback_keys -> device_unused_fallback_key_types

changelog.d/12468.misc, synapse/storage/database.py, synapse/util/async_helpers.py, tests/util/test_async_helpers.py
This will mainly be useful when dealing with module callbacks, which are
all typed as returning `Awaitable`s instead of coroutines or
`Deferred`s.
=> Update `delay_cancellation` to accept any awaitable

changelog.d/12492.doc, docs/systemd-with-workers/workers/background_worker.yaml, docs/systemd-with-workers/workers/event_persister.yaml, docs/systemd-with-workers/workers/generic_worker.yaml, docs/workers.md
... and update [architectural diagram](https://matrix-org.github.io/synapse/develop/workers.html#architectural-diagram)
- add dedicated configuration for a stream writer
- add dedicated configuration for a background worker
- add connection from event persister to main process
- I did a tcpdump and the worker thorws error if no `worker_replication_host` is configured
- link example configuration for `generic-worker` to existing yaml file to avoid duplicated documentation …
=> Add some example configurations for worker

changelog.d/12501.doc, docs/reverse_proxy.md
Signed-off-by: Ville Petteri Huh.
=> HAProxy delegation example

changelog.d/12533.doc, docs/admin_api/user_admin_api.md
Remove extraneous comma in users_admin_api device deletion section so example JSON is actually valid and working.
Signed-off-by: Sami Olmari <sami@olmari.fi>
=> Docs/admin_api: Correct typo in device deletion JSON

changelog.d/12529.misc, synapse/storage/databases/main/events_worker.py, tests/storage/databases/main/test_events_worker.py
Multiple calls to `EventsWorkerStore._get_events_from_cache_or_db` can
reuse the same database fetch, which is initiated by the first call.
Ensure that cancelling the first call doesn't cancel the other calls
sharing the same database fetch.
(run the …
=> Handle cancellation in `EventsWorkerStore._get_events_from_cache_or_db`

changelog.d/12527.doc, docs/usage/configuration/config_documentation.md
Adds an index for the config manual so users can jump to headers. Note that this may end up being temporary as the the lack of an index could also be fixed in the website code, but for now this is the quickest and easiest way to fix this and the manual is not really usable without an index.
=> Add an index to config manual 

changelog.d/12522.bugfix, changelog.d/12522.misc, synapse/handlers/federation.py, synapse/handlers/room_batch.py, synapse/storage/databases/main/event_federation.py, synapse/visibility.py
Try to avoid an OOM by checking fewer extremities.
Generally this is a big rewrite of `_maybe_backfill`, to try and fix some of the TODOs and other problems in it. It's best reviewed commit-by-commit.
Fixes: #12523
=> Optimise backfill calculation

changelog.d/12543.misc, scripts-dev/build_debian_packages.py
As the title states. Fixes #12430, also note https://github.com/matrix-org/pkg-repo-configs/pull/11. I saw no problems building this locally so hopefully this is good to go.
=> Build packages for Ubuntu 22.04

changelog.d/12555.bugfix, synapse/storage/databases/main/devices.py
=> Fix sending opentracing contexts to remote servers

changelog.d/12554.bugfix, synapse/handlers/device.py
Mitigation for #12552.
Tested in-place on matrix.org. We are still seeing high CPU usage, but now Synapse is making forward progress doing work rather than spending time being unable to handle logging/sentry errors correctly.
=> Comment out dodgy log-kv

changelog.d/12544.bugfix, synapse/handlers/appservice.py, synapse/handlers/receipts.py, tests/handlers/test_appservice.py
Spend a couple of hours working through this with @bradtgmurray:
> When the appservice-pusher handles a new read receipt, it grabs up to 100 events newer than the current position and then advances to the new current position. However, it doesn't advance past the 100 events it just grabbed. This means that if there are newer events to handle in the database but we're still in the process handling older events, we'll grab the same events over and over again, pushing them to the appservice scheduler queue.
This can happen if the appservice is slow to respond (but does not error), and thus the in memory queue of events-to-send grows and grows full of duplicated events.
Signed off by Nick @ Beeper
- Be a short description of your change which makes sense to users. "Fixed a bug that prevented …
=> Bound ephemeral events by key

changelog.d/12526.feature, docs/sample_config.yaml, synapse/config/registration.py, synapse/handlers/ui_auth/checkers.py, synapse/rest/client/register.py
This PR attempts to add a second flow for token registration which does not require 3pid validation to succeed, *regardless* of the configuration of `registrations_require_3pid`. The requirement is that we would like to be able to offer tokens that allow users to sign up for a homeserver without having to jump through a email / msidn verification flow.
I'm not a massive fan of the config flag that I have come up with, and I'm a little worried this feels like adding another layer upon an already complicated configuration system (and at this point, does it just become easier to allow advanced users to craft their own registration flows?). That said, I think the idea of having temporal tokens that allow users to bypass registration requirements could be a useful thing, so it's worth figuring …
=> Add option to enable token registration without requiring 3pids

changelog.d/12505.misc, synapse/logging/context.py, tests/federation/test_federation_client.py, tests/federation/test_federation_sender.py, tests/handlers/test_e2e_keys.py, tests/handlers/test_password_providers.py, tests/handlers/test_typing.py, tests/handlers/test_user_directory.py, tests/rest/client/test_presence.py, tests/rest/client/test_rooms.py, tests/rest/client/test_transactions.py, tests/server_notices/test_resource_limits_server_notices.py, tests/storage/test_monthly_active_users.py, tests/test_federation.py
When configuring the return values of mocks, prefer awaitables from
`make_awaitable` over `defer.succeed`. `Deferred`s are only awaitable
once, so it is inappropriate for a mock to return the same `Deferred`
multiple times.
Best reviewed commit by commit. The first commit modifies `run_in_background` to support the awaitables returned by `make_awaitable`. Without it, the tests in the third commit will fail.
Should unblock #12469, which failed CI because `delay_cancellation` "consumes" the result of Deferreds which can come from these mocks.
=> Prefer `make_awaitable` over `defer.succeed` in tests

README.rst, changelog.d/12579.doc
Signed-off-by: Nicolas Werner <nicolas.werner@hotmail.de>
=> Add linebreak to pipx install quote in README

changelog.d/12580.bugfix, synapse/http/server.py, tests/handlers/test_cas.py, tests/handlers/test_saml.py
The status code of requests must always be set, regardless of client
disconnection, otherwise they will always be logged as 200!.
Broken for `respond_with_json` in f48792eec43f893f4f893ffdcbf00f8958b6f6b5.
Broken for `respond_with_json_bytes` in 3e58ce72b42f2ae473c1e76a967548cd6fa7e2e6.
Broken for `respond_with_html_bytes` in ea26e9a98b0541fc886a1cb826a38352b7599dbe.
=> Fix logging of incorrect status codes for disconnected requests

changelog.d/12581.misc, synapse/storage/databases/main/receipts.py
This is split out of #12168 in an effort to reduce that diff / make it more obvious what is changing in that PR.
This has two changes in it:
* Adds/corrects docstrings.
* Removes useless `num_args` parameter to `@cached()` (it defaults to all args).
=> Improve the docstrings for the receipts store.

.github/workflows/latest_deps.yml, .github/workflows/twisted_trunk.yml, changelog.d/12576.misc
Where "bleeding edge" means the Twisted Trunk and Latest Deps jobs.
Follow up from #12531.
Resolves #12574.
Accidentally commited directly to develop: ce6ecdd4b4939fd99418bc949b40c01d39480489, f282d5fc1185dde3f9ec31c49b630cff962545d7, 5a320baa45b8e826e52bdd6cadadfad727ab0357. Reverted in 5d3509dfda607323892f1cc96d7421612816e803.
=> Allow unused ignores in "bleeding edge" CI

changelog.d/12589.misc, docs/sample_log_config.yaml, synapse/config/logger.py
This was originally added when we first added a `MemoryHandler` to the default log config back in https://github.com/matrix-org/synapse/pull/8040, to ensure that we didn't explode with an infinite loop if there was an error formatting the logs.
Since then, we made additional improvements to logging which make this workaround redundant. In particular:
* we no longer attempt to log un-UTF8-decodable byte sequences, which were the most likely cause of an error in the first place.
* https://github.com/matrix-org/synapse/pull/8268 ensures that in the unlikely case that there *is* an error, it won't cause an infinite loop.
=> Remove special-case for `twisted` logger

changelog.d/12594.bugfix, synapse/storage/databases/main/events.py, synapse/storage/databases/main/purge_events.py
This works by taking a row level lock on the `rooms` table at the start of both transactions, ensuring that they don't run at the same time. In the event persistence transaction we also check that there is an entry still in the `rooms` table.
I can't figure out how to do this in SQLite. I was just going to lock the table, but it seems that we don't support that in SQLite either, so I'm *really* confused as to how we maintain integrity in SQLite when using `lock_table`....
=> Fix race when persisting an event and deleting a room

changelog.d/12570.bugfix, synapse/events/__init__.py, synapse/federation/sender/__init__.py
As the comment says, there is no need to process such events, and indeed we need to avoid doing so.
Fixes #12509.
=> Exclude OOB memberships from the federation sender

changelog.d/12614.misc, synapse/federation/sender/__init__.py
... in order to debug some problems we've been having with certain events not being sent when expected.
=> Add extra debug logging to federation sender

changelog.d/12596.removal, synapse/rest/client/account.py, tests/rest/client/test_account.py
The stable identifiers have existed for a while and were part of the 1.2 release of the Matrix spec.
Fixes #12029.
=> Remove unstable identifiers for MSC3069.

changelog.d/12613.removal, poetry.lock, pyproject.toml
Discussed in #synapse-dev last week.
This is presumably a minimum CPython version; I don't
think the abstract language has point releases.
Resolves #12575.
=> Bump Synapse minimum Python version to 3.7.1

changelog.d/12620.misc, synapse/storage/databases/main/events_worker.py, tests/storage/databases/main/test_events_worker.py
I've seen a few errors which can only plausibly be explained by the calculated event id for an event being different from the ID of the event in the database. It should be cheap to check this, so let's do so and raise an exception.
=> Add a consistency check on events read from the database

README.rst, changelog.d/12627.doc
Fixes a couple of formatting errors which were introduced in #12475.
=> Fixes to the formatting of `README.rst`

changelog.d/12587.misc, docs/usage/administration/request_log.md, synapse/http/server.py
Don't log stack traces for cancelled requests and use a custom HTTP
status code of 499.
=> Improve logging for cancelled requests

changelog.d/12616.misc, docs/sample_config.yaml, docs/upgrade.md, docs/usage/configuration/config_documentation.md, synapse/config/federation.py
Closes https://github.com/matrix-org/synapse/issues/12414.
This PR sets the default value of `allow_device_name_lookup_over_federation` to `false`, such that device names are not available to remote users unless explicitly enabled by the homeserver admin. This does not affect device IDs (i.e. XCJKDEM).
=> Disable device name lookup over federation by default

changelog.d/12599.misc, synapse/api/auth.py, synapse/handlers/auth.py, synapse/handlers/identity.py, synapse/handlers/sso.py, synapse/http/site.py, synapse/logging/opentracing.py, synapse/rest/client/auth.py, synapse/rest/client/login.py, synapse/rest/client/register.py, tests/api/test_auth.py, tests/handlers/test_cas.py, tests/handlers/test_oidc.py, tests/handlers/test_saml.py, tests/replication/_base.py, tests/server.py
`getClientIP` is deprecated, switch to `getClientAddress`.
Fixes #11142
=> Use `getClientAddress` instead of `getClientIP`.

changelog.d/12619.feature, docs/sample_config.yaml, docs/sample_log_config.yaml, docs/usage/configuration/config_documentation.md, synapse/config/server.py, synapse/storage/databases/main/registration.py, tests/test_mau.py
The intention here is to hold appservice users to a different trial duration to regular users, for instance tracking them immediately rather than delayed at the same rate as other users. This should be a "free" check, because `is_trial_user` already pulls this information anyway.
=> Add `mau_appservice_trial_days` config

changelog.d/12610.misc, synapse/replication/tcp/handler.py, synapse/replication/tcp/resource.py
I was investigating something with replication and noticed this should be a quick win on the logging front.
c.f. #8021
=> Reduce log spam when running multiple event persisters

changelog.d/12639.bugfix, synapse/config/registration.py, synapse/handlers/ui_auth/checkers.py, synapse/rest/client/register.py
This typo appeared in half the code in #12526, I think it's safe to fix this since it was never part of a release.
=> Drop triple s from enable_registration_token_3pid_bypass

changelog.d/12632.misc, synapse/storage/databases/main/receipts.py
Noticed while reviewing #12168 -- there's a couple of methods which are unused, but we take great care to properly invalidate.
This just removes it all.
=> Remove unused receipt methods.

changelog.d/12577.misc, synapse/api/auth.py
Fixes #10964.
This commentary was confusing without the historical context (the comments are still roughly in a state where macaroons were the new thing, but now they're the old thing and opaque tokens are back in fashion!).
Especially notable was that 'Invalid macaroon passed.' is completely obscure to a client developer; customers have asked what this means!!
=> Improve comments and error messages around access tokens.

changelog.d/12640.misc, debian/build_virtualenv, debian/changelog
Fixes #12631.
The `systemd` and `cache_memory` extra package groups contain python dependencies that are necessary for using all available options of the base distribution of Synapse in debian packages.
`systemd` provides the `systemd-python` package which is required for logging to the systemd journal, whereas `cache_memory` provides the `pympler` package, which is required for the `caches.track_memory_usage` homeserver config option.
These dependencies were available before the poetry changeover, where [they seem to have gone missing](https://github.com/matrix-org/synapse/issues/12631#issuecomment-1118418265). This PR adds these extras groups back.
Merging to the `release-v1.58` branch with the intention of including this in a v1.58.1 release.
---
I'm not sure if we also need to add the …
=> Include extra dependency groups 'systemd' and 'cache_memory' in debian packages

changelog.d/12656.misc, synapse/handlers/presence.py, synapse/util/wheel_timer.py
When presence was disabled in Synapse <v1.58.0 (fixed by #12213) there was a small memory leak where the sync code would call `set_state` and insert items into the wheel timer, but would then never read *from* the wheel timer, causing a memory leak.
=> Prevent memory leak from reoccurring when presence is disabled.

changelog.d/12657.bugfix, synapse/events/utils.py, synapse/handlers/room.py, tests/events/test_utils.py, tests/rest/client/test_upgrade_room.py
Fixes #12537.
The commit messages aren't great, but the diffs might be more manageable commit-by-commit.
I wasn't thrilled with the type-ignores I had to add, but I didn't have the energy to think if there was a better way.
=> Convert stringy power levels to integers on room upgrade

changelog.d/12652.misc, debian/build_virtualenv, debian/changelog, poetry.lock, pyproject.toml
Undoes a change I made in #12381. I can't fully remember my reasoning,
but this changed the contents of the debian packages in a backwards
incompatible way. We're not aware of anyone who's been bitten by this,
but we still want to fix it.
To the reviewer: please be convinced that the debian packages will still
contain pympler after this change.
=> Move `pympler` back into the `all` extras

changelog.d/12666.misc, pyproject.toml, synapse/storage/database.py
I'm not sure this gives us a huge amount of type safety, see this
comment:
https://github.com/matrix-org/synapse/issues/12312#issuecomment-1120289915
In any case, it's a nice bit of practice with `ParamSpec`.
On the face of it, resolves #12312. But as per the linked comment above, I'm not sure if we want to consider that done.
=> Use `Concatenate` to annotate `do_execute`

changelog.d/12664.doc, docs/development/contributing_guide.md
Fix docs on how to run specific Complement tests after recent `complement.sh` change
The behavior changed in [#12404](https://github.com/matrix-org/synapse/pull/12404#discussion_r867307790) which removed the automatic insertion of `-run` for test regex.
❌ If you tried using the old method of supplying a test regex with the new behavior, you'd run into the following behavior and tests aren't run:
```sh
$ COMPLEMENT_ALWAYS_PRINT_SERVER_LOGS=1 COMPLEMENT_DIR=../complement ./scripts-dev/complement.sh TestImportHistoricalMessages
...
Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
Images built; running complement
package TestImportHistoricalMessages is not in GOROOT (/Users/eric/.gvm/gos/go1.18/src/TestImportHistoricalMessages)
```
✅ The new …
=> Fix docs on how to run specific Complement tests after recent `complement.sh` change

changelog.d/12602.misc, contrib/grafana/synapse.json
=> docs(contrib): Add link to documentation in dashboard

changelog.d/12667.misc, poetry.lock, pyproject.toml, synapse/app/_base.py, synapse/events/presence_router.py, synapse/module_api/__init__.py, synapse/rest/client/knock.py, synapse/rest/client/transactions.py, synapse/storage/database.py, synapse/storage/databases/main/events.py, synapse/util/async_helpers.py, synapse/util/distributor.py, synapse/util/metrics.py, synapse/util/patch_inline_callbacks.py
I tried to concentrate on publicly visible functions which pass a `*args,  **kwargs` pair, so that we get some checking that we end up passing the right arguments.
Related: #11711 
Will probably conflict with #12666.
=> Use `ParamSpec` in a few places

changelog.d/12671.misc, poetry.lock, synapse/rest/media/v1/thumbnailer.py
=> Fix mypy against latest pillow stubs

changelog.d/12665.misc, synapse/federation/federation_client.py
"M_UNRECOGNIZED" is the errcode used by in the protocol.
https://github.com/matrix-org/synapse/blob/3a8ee229112697b02b876299869d7511474ecf92/synapse/api/errors.py#L34
Signed-off-by: Valentin Lorentz <progval+git@progval.net>
=> Fix inconsistent spelling of 'UNRECOGNIZED' when refering to endpoints

changelog.d/12637.misc, docker/conf-workers/supervisord.conf.j2, scripts-dev/complement.sh
* Bump the HS startup timeout
* Log prefixes for more processes
* Bump the overall timeout
=> Tweaks to workers-under-complement

changelog.d/12536.doc, docs/usage/administration/useful_sql_for_admins.md
Fixes: #12525
- ~~reformat queries with https://www.freeformatter.com/sql-formatter.html~~
- replace use of `user_stats_historical`
- replace use of role `synapse` with username and passwort with `psql` and add link to psql docs
- add query to get same information with native sql
(run the …
=> Update SQL statements in docs for Synapse Admins

changelog.d/12621.doc, docs/replication.md, synapse/replication/tcp/__init__.py
As the title states. I came across the comment in `synapse/replication/tcp/__init__.py` by accident and thought it might be useful to give a little more visibility to it.
=> Update `replication.md` with info on TCP module structure

changelog.d/12676.misc, synapse/push/__init__.py
Adds some top-level information to the `synapse.push` module. It includes (a rough) algorithm of how pushes are calculated and a class-level diagram of the interactions.
I think this is mostly accurate, but might be glossing over some details.
=> Add class-diagrams and notes for push.

changelog.d/12677.misc, synapse/push/bulk_push_rule_evaluator.py, synapse/push/push_rule_evaluator.py
It was quite confusing to me that we had some floating variables / functions which operate on a `PushRuleEvaluatorForEvent` instance. It seems clearer to move them onto the class.
Also adds some docstrings.
Tangentially related to #12551.
=> Move methods into PushRuleEvaluatorForEvent.

changelog.d/12588.misc, synapse/http/site.py
See the linked PR for usage of the new attributes.
---
In #12583:
`render_deferred` is set in `_AsyncResource.render` in `synapse/http/server.py`.
`is_render_cancellable` is more tricky and gets set in `_AsyncResource._async_render`, `JsonResource._async_render` (`synapse/http/server.py`) and `ReplicationEndpoint._check_auth_and_handle` (`synapse/replication/http/_base.py`)
...because in Synapse, we have 5 ways of defining async HTTP endpoints:
* `RestServlet` subclasses with `on_$METHOD` methods
* `BaseFederationServlet` subclasses with `on_$METHOD` methods
* `ReplicationEndpoint` subclasses with a `_handle_request` implementation
* `DirectServe{Html,Json}Resource` subclasses with `_async_render_$METHOD` methods
All of these get invoked …
=> Add ability to cancel disconnected requests to `SynapseRequest`

changelog.d/12679.misc, synapse/storage/databases/main/events.py, synapse/storage/databases/main/purge_events.py, synapse/storage/schema/__init__.py, tests/storage/test_event_federation.py
This table is never read, since #11794. We stop writing to it; in future we can drop it altogether.
Part of #6574.
=> Stop writing to `event_reference_hashes`

changelog.d/12694.misc, synapse/http/server.py, synapse/http/site.py
All async request processing goes through `_AsyncResource`, so this is
the only place where a `Deferred` needs to be captured for cancellation.
Unfortunately, the same isn't true for determining whether a request
can be cancelled. Each of `RestServlet`, `BaseFederationServlet`,
`DirectServe{Html,Json}Resource` and `ReplicationEndpoint` have
different wrappers around the method doing the request handling and they
all need to be handled separately.
----
We finally set the `is_render_cancellable` flag in:
* 46cdb4bd0746df6aad0b2408beb35b38b5a94c18 for `DirectServe{Html,Json}Resource`
* 2326bbf0999e99b57dafcebd966dd9bd942c52a2 for `RestServlet` and `BaseFederationServlet`
* …
=> Capture the `Deferred` for request cancellation in `_AsyncResource`

changelog.d/12683.bugfix, synapse/handlers/pagination.py, synapse/storage/databases/main/stream.py
Fix `/messages` throwing a 500 when querying for non-existent room
Fix https://github.com/matrix-org/synapse/issues/12678
Complement test added:  https://github.com/matrix-org/complement/pull/369
**Before:** 500 internal server error
**After:** According to the [spec](https://spec.matrix.org/latest/client-server-api/#get_matrixclientv3roomsroomidmessages), calling `/messages` against a non-existent `room_id` should throw a 403 forbidden (since you're not part of the room). This also matches the behavior before https://github.com/matrix-org/synapse/pull/12370 which regressed Synapse to the 500 behavior.
```json
{
"errcode": "M_FORBIDDEN",
"error": "User @test:my.synapse.server not in room !dne:my.synapse.server, and room previews are disabled"
}
```
- -> …
=> Fix `/messages` throwing a 500 when querying for non-existent room

changelog.d/12698.misc, synapse/http/server.py, tests/test_server.py
`DirectServeHtmlResource` and `DirectServeJsonResource` both inherit
from `_AsyncResource`. These classes expect to be subclassed with
`_async_render_*` methods.
This commit has no effect on `JsonResource`, despite inheriting from
`_AsyncResource`. `JsonResource` has its own `_async_render` override
which will need to be updated separately.
---
=> Respect the `@cancellable` flag for `DirectServe{Html,Json}Resource`s

changelog.d/12699.misc, synapse/http/server.py, tests/federation/transport/server/__init__.py, tests/federation/transport/server/test__base.py, tests/http/test_servlet.py, tests/unittest.py
Both `RestServlet`s and `BaseFederationServlet`s register their handlers
with `HttpServer.register_paths` / `JsonResource.register_paths`. Update
`JsonResource` to respect the `@cancellable` flag on handlers registered
in this way.
Although `ReplicationEndpoint` also registers itself using
`register_paths`, it does not pass the handler method that would have the
`@cancellable` flag directly, and so needs separate handling.
---
=> Respect the `@cancellable` flag for `RestServlet`s and `BaseFederationServlet`s

changelog.d/12700.misc, synapse/replication/http/_base.py, tests/replication/http/__init__.py, tests/replication/http/test__base.py
While `ReplicationEndpoint`s register themselves via `JsonResource`,
they pass a method that calls the handler, instead of the handler itself,
to `register_paths`. As a result, `JsonResource` will not correctly pick
up the `@cancellable` flag and we have to apply it ourselves.
---
=> Respect the `@cancellable` flag for `ReplicationEndpoint`s

changelog.d/12705.misc, synapse/federation/transport/server/_base.py, tests/federation/transport/server/test__base.py
`BaseFederationServlet` wraps its endpoints in a bunch of async code
that has not been vetted for compatibility with cancellation.
Fail CI if a `@cancellable` flag is applied to a federation endpoint.
----
Follows on from #12699, where cancellation for `BaseFederationServlet`s came for free.
This is the last PR broken out from #12583.
Many thanks to everyone who has been involved in reviewing the PR series!
=> Complain if a federation endpoint has the `@cancellable` flag

changelog.d/12715.doc, docs/admin_api/media_admin_api.md
`unix_timestamp_in_ms` refers to an example in the docs, not the actual query parameter's name.
=> Fix reference to the wrong symbol in the media admin api docs

changelog.d/12720.misc, synapse/rest/media/v1/preview_url_resource.py
Noticed while working on a separate feature in the area.
This commit:
* Moves some not-very-info-worthy log lines related to the URL preview cache expiry background job from INFO to DEBUG.
* Clarifies the text of some log lines to mention that they related to URL preview cache expiry.
Slightly helps with https://github.com/matrix-org/synapse/issues/8021.
=> URL preview cache expiry logs: INFO -> DEBUG, text clarifications

changelog.d/12727.doc, docs/openid.md
Newer versions of keycloak returning a 404 when using the `/auth` prefix.
Related: https://github.com/matrix-org/synapse/issues/12714
=> Update openid.md to avoid crash on startup

changelog.d/12513.feature, synapse/events/spamcheck.py, synapse/server.py, tests/rest/client/test_rooms.py
=> SpamChecker metrics

changelog.d/12726.misc, mypy.ini, synapse/handlers/e2e_keys.py, synapse/http/connectproxyclient.py, synapse/http/proxyagent.py, synapse/logging/_remote.py, synapse/logging/formatter.py, synapse/logging/handlers.py, synapse/logging/scopecontextmanager.py, synapse/storage/background_updates.py, synapse/types.py
Like #12716. Recommend commit-by-commit review.
`mypy -p synapse --disallow-untyped-errors` now reports 99 errors on my machine. Before the previous PR, it was around 150.
=> Another batch of type annotations

changelog.d/12731.misc, docker/complement/conf-workers/workers-shared.yaml, docker/complement/conf/homeserver.yaml
Updates the configs used by Complement to allow more invites and 3PID validations
Reason: [failing CI](https://github.com/matrix-org/complement/runs/6423329110?check_suite_focus=true#step:8:1954) 
Tested in https://github.com/matrix-org/complement/pull/353 which had the same issue, with these changes it worked without issues.
- Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your …
=> Update configs used by Complement to allow more invites

changelog.d/12729.bugfix, synapse/storage/databases/main/stream.py
I've based this on v1.59 branch, I think its worth sneaking this fix into v1.59.0
Fixes #12571
=> Fix bug /sync returning 404

changelog.d/12711.misc, synapse/handlers/initial_sync.py, synapse/handlers/receipts.py, tests/handlers/test_receipts.py
=> Optimize private read receipt filtering

changelog.d/12745.bugfix, synapse/storage/databases/main/stream.py
=> Fix query performance for /sync

changelog.d/12734.misc, mypy.ini, synapse/storage/engines/__init__.py, synapse/storage/engines/_base.py, synapse/storage/engines/postgres.py, synapse/storage/engines/sqlite.py, synapse/storage/types.py
A Friday indulgence.
We tell the engines which module to use as a database driver. I wanted to change this because a) it seems weird, and b) my secret ulterior motive is to add yet more type coverage to Synapse.
Closes #12724.
=> Tidy up and type-hint the database engine modules

changelog.d/12747.bugfix, synapse/storage/databases/main/cache.py, synapse/storage/schema/main/delta/69/02cache_invalidation_index.sql
For workers that rarely write to the cache the `get_all_updated_caches`
query can become expensive if the worker falls behind when reading the
cache.
=> Add index to cache invalidations

changelog.d/12721.bugfix, synapse/push/httppusher.py
badge_count_last_call was never set to non-zero values when the response for push
notifications included a "rejected" key which mapped to an empty list.
Signed-off-by: Tobias Büttner …
=> Fix push for m.read events

changelog.d/12769.misc, scripts-dev/mypy_synapse_plugin.py, synapse/storage/databases/main/roommember.py
The mypy plugin is unnecessarily strict: see https://github.com/matrix-org/synapse/pull/12717#issuecomment-1128008804. I discussed this with Erik in DM and he agreed this looks sensible.
=> allow `on_invalidate=None` in `@cached` methods

changelog.d/12765.doc, docs/development/contributing_guide.md
=> Suggest using docker when testing against postgres

changelog.d/12772.bugfix, changelog.d/12772.misc, synapse/storage/databases/main/push_rule.py
Fixes https://github.com/matrix-org/synapse/issues/12764.
Signed-off-by: Adam Roddick <ajroddick@tuta.io>
=> Move methods that call add_push_rule to PushRuleStore

changelog.d/12774.misc, synapse/federation/transport/server/_base.py, synapse/http/matrixfederationclient.py, tests/federation/transport/server/test__base.py
main differences are:
- values with delimiters (such as colons) should be quoted, so always quote the origin, since it could contain a colon followed by a port number
- should allow more than one space after "X-Matrix"
- quoted values with backslash-escaped characters should be unescaped
- names should be case insensitive
=> make handling of federation Authorization header (more) compliant with RFC7230

changelog.d/12762.misc, synapse/rest/client/room.py, synapse/storage/databases/main/events.py, synapse/storage/databases/main/user_directory.py, synapse/util/stringutils.py, tests/handlers/test_user_directory.py
Fixes #12755.
Closes #12743.
I tested the new test case (8c977edec) without the fix and reproduced a postgres error for my troubles.
```
File "/home/dmr/.cache/pypoetry/virtualenvs/matrix-synapse-YNqvS2_4-py3.10/lib/python3.10/site-packages/twisted/internet/defer.py", line 700, in errback
self._startRunCallbacks(fail)
File "/home/dmr/.cache/pypoetry/virtualenvs/matrix-synapse-YNqvS2_4-py3.10/lib/python3.10/site-packages/twisted/internet/defer.py", line 763, in _startRunCallbacks
self._runCallbacks()
File "/home/dmr/.cache/pypoetry/virtualenvs/matrix-synapse-YNqvS2_4-py3.10/lib/python3.10/site-packages/twisted/internet/defer.py", line 857, in _runCallbacks
current.result = callback(  # type: ignore[misc]
File …
```
=> Discard null-containing strings before updating the user directory

changelog.d/12759.doc, docs/usage/configuration/config_documentation.md
Document how each section of the `rc_invite` ratelimiting option affects user invites. Prompted after someone asked me this question in a room, and I realised that our documentation had no answers!
=> Add some documentation around the `rc_invites` option to the config docs

changelog.d/12748.doc, docs/welcome_and_overview.md
As the config manual is probably where people actually want to be when looking to configure their homeserver.
I also fixed a bunch of `*.html` links on this page - they should be links to the markdown instead. mdbook will then translate these to `*.html` when the book is built. As well as a couple typos.
Recommended to review commit-by-small-amount-of-commits.
=> Switch the 'Configuration' link in the docs homepage to the config manual

changelog.d/12779.bugfix, synapse/handlers/directory.py, synapse/handlers/room.py
This situation happened because someone was using an SDK that didn't make it very clear that `room_alias_name` was supposed to be a **localpart**.
In this case, they passed e.g. `#wombat:matrix.org` as the localpart and then Synapse wound up returning 502 Bad Gateway (which confused Cloudflare to return a page saying that Synapse was down, rather than passing through the error message).
(I'm not entirely sure why; possibly whilst trying to resolve the alias to check it doesn't exist?)
This is a quick drive-by fix to make Synapse not entertain the idea of trying to create `##wombat:matrix.org:matrix.org` (whilst creating a room), instead opting to give a more helpful error to a confused client developer.
Note that `##wombat:matrix.org` appears to be in order; apparently LiberaChat uses …
=> Give a meaningful error message when a client tries to create a room with an invalid alias localpart.

changelog.d/12775.misc, synapse/state/__init__.py, synapse/storage/databases/state/store.py, synapse/storage/state.py, tests/test_state.py
One of the tasks in #12684. Currently when `resolve_state_groups_for_events` calculates the state groups for events, the full state is pulled from the DB to make this calculation, which is unnecessary. This PR changes `resolve_state_groups_for_events` to pull the just the state groups for the events and checks to see if the events are all part of the same state group, and if so, returns the state as no state resolution is necessary.
=> Refactor `resolve_state_groups_for_events` to not pull out full state when no state resolution happens.

changelog.d/12785.doc, docs/usage/configuration/config_documentation.md
You cannot start a block in YAML with `*`. Otherwise a YAML parser may spit out:
```
did not find expected alphabetic or numeric character while scanning an alias
```
Also add some missing `yaml`s to codeblocks.
=> Fix YAML parsing error in `url_preview_accept_language`

changelog.d/12498.misc, synapse/storage/state.py
If `StateFilter` specifies a state set which we will have regardless of state-syncing, then we may as well return it immediately.
Part of https://github.com/matrix-org/synapse/issues/11249 / https://github.com/matrix-org/synapse/issues/12647
=> Skip waiting for full state if a StateFilter does not require it

changelog.d/12783.misc, demo/start.sh, docs/development/demo.md
This fixes a regression from #12143 where I broke federation between the homeservers created by the demo scripts.
I had changed the server names to use the HTTP listening port, instead of the HTTPS listening port, which meant that federation (which always uses TLS) broke.
This reverts that change, which adds the annoyance back that you would generally connect to the homeserver over HTTP at e.g. `localhost:8080`, but end up with an MXID at the HTTPS address: `localhost:8480`.
=> Fix federation in demo scripts.

changelog.d/12723.misc, synapse/handlers/oidc.py
This means we won't get tracebacks reported to Sentry.
There are other `logger.exception` and `logger.error` calls in this
file. I tried to only target errors that
- show up a lot in Sentry
- don't sound like our fault
- are still reported to the end-user by other means.
I erred on the side of caution and included the error's string representation in the logged warning.
I know very little about open ID etc, so would appreciate sanity checking from a responsible adult.
Closes #12707.
=> Downgrade some OIDC exceptions to warnings

changelog.d/12773.doc, docs/workers.md
Fixes #12768 
Signed-off-by: Sami Olmari <sami@olmari.fi>
=> Add missing user_dir endpoint from the generic worker documentation

changelog.d/12786.feature, synapse/handlers/room.py
Resolves: #11896
Signed-off-by: Aminda Suomalainen
=> Implement MSC3818: copy room type on upgrade

changelog.d/12790.misc, mypy.ini
Bask in _the glory_
Arguably:
Closes #11302.
#11315 remains, but that was somewhat contravertial and has now bitrotted.
=> Simplify untyped-defs config in mypy.ini

changelog.d/12789.misc, synapse/_scripts/hash_password.py
Signed-off by: Jae Lo Presti <me@jae.fi>
=> hash_password: raise an error if no config file is specified

changelog.d/12687.bugfix, docs/upgrade.md, synapse/storage/background_updates.py, synapse/storage/databases/state/bg_updates.py, synapse/storage/schema/state/delta/70/08_state_group_edges_unique.sql
=> Add a unique index to `state_group_edges` to prevent duplicates being accidentally introduced and the consequential impact to performance.

changelog.d/12794.bugfix, synapse/config/oembed.py
I noticed lots of `synapse/config/oembed.py:60: ResourceWarning: unclosed file <_io.BufferedReader name='synapse/res/providers.json'>` warnings when I ran tests in `v1.59.1` and earlier versions. It should be possible to reproduce it with following command (I used python 3.9)
```sh
python -m unittest -v tests/unittest.py
```
which outputs
```
runTest (tests.unittest.FederatingHomeserverTestCase)
If no C{methodName} argument is passed to the constructor, L{run} will ... ok
synapse/config/oembed.py:60: ResourceWarning: unclosed file <_io.BufferedReader name='synapse/res/providers.json'>
providers = json.load(
runTest (tests.unittest.HomeserverTestCase)
If no C{methodName} argument is passed to the constructor, L{run} will ... ok
synapse/config/oembed.py:60: ResourceWarning: unclosed file …
```
=> Close providers.json stream when the json is loaded

changelog.d/12777.doc, docs/usage/configuration/config_documentation.md
As the title states. Currently this is documented in the media repo section of the documentation, this PR adds it to the beginning of the manual with the time-related suffixes are documented. 
Fixes #12757
=> Update configuration manual to document size-related suffixes

changelog.d/12776.doc, docs/usage/configuration/config_documentation.md
=> Add detail to `cache_autotuning` config option documentation 

changelog.d/12803.bugfix, synapse/util/retryutils.py
Fixes #12797
Discovered while testing faster room joins' state re-syncing against unreachable homeservers.
=> Fix `RetryDestinationLimiter` re-starting finished log contexts

changelog.d/12791.misc, synapse/events/snapshot.py, synapse/handlers/federation.py, synapse/handlers/federation_event.py, synapse/handlers/message.py, synapse/handlers/room.py, synapse/handlers/room_member.py, synapse/push/bulk_push_rule_evaluator.py, synapse/storage/databases/main/roommember.py, synapse/storage/state.py, tests/test_state.py
Currently there are a number of places where we pull full state from the DB, which is unnecessary. This PR refactors two functions in EventContext,  `get_current_event_ids` and `get_prev_event_ids`, to accept a state filter as a parameter and then applies those filters in calls to these functions where appropriate.
=> Update EventContext `get_current_event_ids` and `get_prev_event_ids` to accept state filters and update calls where possible

changelog.d/12703.misc, synapse/api/errors.py
This PR is part of an ongoing refactoring to make the spam-checker API more powerful and more uniform.
In this PR, we introduce a string enum `Code` that regroups all known error codes. This will help us progressively replace some string-typing in error codes by strong typing. In particular, this is necessary for the ongoing refactoring.
- Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed …
=> Uniformize spam-checker API, part 1: the `Code` enum.

changelog.d/12672.feature, changelog.d/12672.misc, changelog.d/12809.feature, synapse/replication/tcp/commands.py, synapse/replication/tcp/redis.py
Fixes #12460.
I will note that I confirmed the tests complain if there is a mistake in the channel name, so we are confirming that the messages are making it across.
=> Send `USER_IP` commands on a different Redis channel, in order to reduce traffic to workers that do not process these commands.

changelog.d/12823.bugfix, synapse/storage/database.py
Fixes #12798.
I don't think we would have noticed this if not for Complement tripping up on it :-).
This is necessary because upserts require a unique index.
These unique indices are introduced in the background by https://github.com/matrix-org/synapse/blob/b76f1a4d5f918def1f643910939b80e9e035e07f/synapse/storage/databases/main/media_repository.py#L85-L112
=> Fix media thumbnails being unusable before the index had been added in the background.

.git-blame-ignore-revs
This PR adds https://github.com/matrix-org/synapse/pull/7953 to the git blame revision blacklist (which prevents the associated commit appearing when using git blames).
A relatively small commit, but one that did get in the way today. I don't think this one is very useful when viewing blames.
Not sure if this one needs a changelog entry?
=> Add a windows->unix file endings commit to git blame ignore file

changelog.d/12819.misc, docker/complement/conf-workers/workers-shared.yaml
`TestCanRegisterAdmin` is fixed as a result, though a couple of others look admin registration-related and therefore might be fixed too.
Cross-ref: https://github.com/matrix-org/complement/blob/64517973539750c3a006dec14f13b4fb82de0b66/internal/client/client.go#L26-L28
=> Fix Complement `TestCanRegisterAdmin` with workers, by adding Complement's shared registration secret.

changelog.d/12842.misc, scripts-dev/complement.sh
Closes #12822.
Our implementation of MSC2775 is monolith-only for now.
This disables those tests when testing workers in Complement.
=> Disable 'faster room join' Complement tests when testing against Synapse with workers.

changelog.d/12744.feature, docs/modules/spam_checker_callbacks.md, docs/spam_checker.md, synapse/events/spamcheck.py, synapse/federation/federation_server.py, synapse/module_api/__init__.py
something to be very careful about in a feature like this is correctly expressing the danger of such a callback. ignoring a federated event splitbrains our view of the DAG and thus …
=> add SpamChecker callback for silently dropping inbound federated events

changelog.d/12853.docker, docker/Dockerfile
I *think* this should fix the docker images. It's unclear as to why, though a beta `poetry.core` package was released yesterday, and we don't pin the version of *that* 
Fixes #12854
=> Pin poetry.core in Docker images

changelog.d/12860.misc, synapse/rest/media/v1/preview_html.py
`*args: T` means that `args: Tuple[T, ...]` within the function body.
I don't think this makes much sense because lxml doesn't come with any
type annotations out of the box.
=> Correct annotation of `_iterate_over_text`

changelog.d/12863.doc, docs/message_retention_policies.md, docs/structured_logging.md, docs/workers.md
=> Fix typos in documentation

changelog.d/12829.bugfix, synapse/handlers/device.py
While this change seems a bit strange, I was seeing TypeErrors on my
homeserver because someone is sending device lists where they explicitly
set `"prev_id": null` which causes the next list comprehension to fail.
Signed-off-by: Carl Bordum Hansen <carl@bordum.dk>
(run the …
=> Make sure `prev_ids` defaults to empty list

changelog.d/12866.misc, docs/workers.md, synapse/app/generic_worker.py
Another endpoint to move off main. Useful where lots of external tooling is using the endpoint to validate user tokens.
Signed off by Nick @ Beeper.
=> Add the `/account/whoami` endpoint to generic workers

changelog.d/12869.misc, synapse/appservice/scheduler.py
Leftover fix/performance improvement we made a few weeks back to workaround an issue with the `get_latest_as_txn` query running slowly (we've not figured that out yet!).
Signed off by Nick @ Beeper.
=> Don't create empty AS txns when the AS is down

changelog.d/12868.misc, docker/configure_workers_and_start.py, docs/workers.md, synapse/app/generic_worker.py
I believe this should be safe, just as general room event sending is safe on worker instances. Another thing that can be pulled off main.
Signed off by Nick @ Beeper.
=> Add the `batch_send` endpoint to generic workers

changelog.d/12856.misc, synapse/storage/databases/main/push_rule.py
This has a few unrelated changes to the push rules datastore that I noticed.
=> Misc clean-up of push rules datastore

changelog.d/12859.feature, synapse/storage/databases/main/relations.py, synapse/util/caches/descriptors.py
`cachedList` automatically adds to the cache for every item it receives, even if the underlying function returns nothing for it.
This fixes the behavior of `get_mutual_event_relations` to properly return an entry for every item it receives.
=> Fix caching behavior for relations push rules.

changelog.d/12871.misc, synapse/handlers/admin.py, synapse/handlers/device.py, synapse/handlers/federation.py, synapse/handlers/federation_event.py, synapse/handlers/initial_sync.py, synapse/handlers/message.py, synapse/handlers/pagination.py, synapse/handlers/room.py, synapse/handlers/room_batch.py, synapse/handlers/search.py, synapse/handlers/sync.py, synapse/push/mailer.py, synapse/state/__init__.py, tests/handlers/test_federation.py
We used the name `state_store` to refer to the `StateGroupStorage` (soon to be renamed to `StateStorage`), but `_store` implies that the variable is a `DataStore` style class rather than a `Storage` style class.
=> Fix up `state_store` naming

changelog.d/12877.bugfix, synapse/federation/transport/client.py, synapse/http/matrixfederationclient.py, tests/http/test_fedclient.py
=> Allow bigger responses to `/federation/v1/state`

changelog.d/12879.misc, synapse/federation/sender/per_destination_queue.py, synapse/storage/databases/main/event_push_actions.py, synapse/storage/databases/main/receipts.py, synapse/storage/persist_events.py
I was poking at the receipts code and noticed that we unconditionally call `_remove_old_push_actions_before_txn` for any read or private read receipt. This [deletes things from `event_push_actions` and `event_push_summary`](https://github.com/matrix-org/synapse/blob/de6e2bc986170605c9500395008fd0129aaea0c1/synapse/storage/databases/main/event_push_actions.py#L930-L974), but those tables only have entries for local users. We can skip those deletes which will never find any users.
These tables both have indexes on them such that the queries are both probably "instant", but if we can avoid the round-trip to the database, creating a transaction, etc. that's a nice win.
(Also fixes some spelling of "transaction" in a few spots.)
=> Avoid attempting to delete push actions for remote users.

changelog.d/12843.bugfix, synapse/storage/databases/main/event_federation.py
Fixes #12825.
@MadLittleMods I'd like to request your eyes to check this is what you intended.
It matches my reading of the surrounding commentary, but SQLite's query plan would have used `i` according to some experimentation!
Complement tests pass with *either* `c` or `i` so weren't much use in discerning the two :/.
=> Fix ambiguous column name that would prevent use of MSC2716 History Import when using Postgres as a database.

changelog.d/12887.misc, synapse/rest/media/v1/preview_html.py
Many of these tags aren't intended to be text for human consumption, or if they are, the content is only shown to older browsers that don't understand them and so they usually
just say silly things like 'Upgrade your browser!!'.
=> Improve URL previews by not including the content of media tags in the generated description.

changelog.d/12886.misc, synapse/storage/databases/main/events_worker.py
My server is currently OOMing in the middle of have_seen_events, so let's try to fix that.
=> Refactor have_seen_events to reduce OOMs

changelog.d/12883.feature, docs/sample_config.yaml, docs/usage/configuration/config_documentation.md, synapse/config/auth.py, synapse/handlers/auth.py, tests/rest/client/test_auth.py
Fixes #12844.
This splits up the use of passwords *for login* and *for reauthentication (for privileged operations, e.g. deleting devices, setting cross-signing keys, ...)*.
Registration is unaffected.
=> Add an option allowing users to use their password to reauthenticate even though password authentication is disabled.

changelog.d/12875.bugfix, synapse/federation/transport/client.py, synapse/http/matrixfederationclient.py
Hopefully this means that exceptions raised due to truncated JSON
get a sensible logging context and stack.
-------
On matrix.org sentry, we are seeing a lot of `Exception ignored in: <generator object utf8_encoder at 0x7f87c9b1ccf0>` errors without a proper stack trace or logging context.
Digging into the logs, we find something like:
```
2022-05-25 05:15:16,092 - twisted - 279 - ERROR - sentinel - Exception ignored in: <generator object utf8_encoder at 0x7ff6c944b6d0>
2022-05-25 05:15:16,093 - twisted - 279 - ERROR - sentinel - Traceback (most recent call last):
2022-05-25 05:15:16,095 - twisted - 279 - ERROR - sentinel -   File "/.../site-packages/ijson/backends/python.py", line 46, in utf8_encoder
2022-05-25 05:15:16,098 - twisted - 279 - …
```
=> Close `ijson` coroutines ourselves instead of letting the GC close them

changelog.d/12894.misc, synapse/config/tracer.py, synapse/logging/opentracing.py, synapse/metrics/background_process_metrics.py
I think these are correct, but to have them properly flow through the rest of the program we need some hard decorator annotations.
Might be worth commit-by-commit review, but I didn't put much effort into chopping it up into orthogonal changes.
=> Easy type hints in synapse.logging.opentracing

changelog.d/12888.misc, synapse/storage/databases/main/receipts.py
I was poking at this code a few times and there's some bits that annoy me / confuse me about it:
* Properly marks private methods as private.
* Add some docstrings.
* Rejigger some useless / inline methods.
=> Clean-up some receipts code

changelog.d/12832.bugfix, synapse/storage/databases/main/lock.py, tests/storage/databases/main/test_lock.py
This PR fixes acquiring a lock via `LockStore.try_acquire_lock` which is currently broken.
* Adds a test that demonstrates the issue. See https://github.com/matrix-org/synapse/pull/12484#issuecomment-1116286459
* Adds a `Linearizer` to `LockStore` to make the test pass.
Outstanding questions:
<details><summary>old error</summary>
```
$ trial tests.storage.databases.main.test_lock
tests.storage.databases.main.test_lock
LockTestCase
test_acquire_contention ...                                            [OK]
test_drop ...                                                       [ERROR]
test_maintain_lock ...                                                 [OK]
test_shutdown ...                                                      [OK]
test_simple_lock ... …
```
=> LockStore: fix acquiring a lock via `LockStore.try_acquire_lock`

changelog.d/12912.misc, poetry.lock, synapse/events/validator.py
Fixes #12901 by incoprating https://github.com/python/typeshed/pull/7980
(The latest deps job will automatically be fixed now that newer stubs are available, but let's pull in the more complete stubs while we're at it.)
=> Bump jsonschema stubs

changelog.d/12904.misc, synapse/storage/databases/main/state.py
This method was introduced in #12852. It is using the `state_key` column from
the `events` table, which is not (yet) reliable (see #11496).
=> Fix `get_metadata_for_events`

changelog.d/12840.bugfix, synapse/push/bulk_push_rule_evaluator.py, synapse/storage/databases/main/pusher.py, tests/rest/client/test_notifications.py
fixes #12839
introduced in #705
Signed-off-by: Nicolas Werner <nicolas.werner@hotmail.de>
=> Fix invite notifications for users without pushers

changelog.d/12808.feature, changelog.d/12846.feature, changelog.d/12846.misc, synapse/api/errors.py, synapse/events/spamcheck.py, synapse/handlers/message.py
=> Uniformize spam-checker API, part 3: Expand check_event_for_spam with the ability to return additional fields

changelog.d/12917.feature, synapse/module_api/__init__.py
Looks like this got missed in https://github.com/matrix-org/synapse/pull/12838
Also did `sleep` which I've probably missed when I documented the other existing methods.
=> Document the Synapse version of a new module API method

changelog.d/12903.bugfix, synapse/handlers/pagination.py
Fixes #12102.
Judging by this [comment](https://github.com/matrix-org/matrix-spec-proposals/issues/2251#issuecomment-932821615) and the [spec](https://spec.matrix.org/v1.2/client-server-api/#get_matrixclientv3roomsroomidmessages) this should fix the issue.
I'm not sure if end should be null if this was the last chunk of information but was non empty, but I do not know if it is possible to check if there are no more events in `next_token`.
Signed-off-by: Jacek Kuśnierz <kusnierz@protonmail.com>
=> Don't return `end` from `/messages` if there are no more events

changelog.d/12918.bugfix, docs/modules/spam_checker_callbacks.md, docs/upgrade.md, synapse/events/spamcheck.py, synapse/federation/federation_base.py, synapse/handlers/message.py, synapse/module_api/__init__.py, synapse/spam_checker_api/__init__.py
This got missed while reviewing https://github.com/matrix-org/synapse/pull/12808
=> Fix import in module_api module and docs on the new check_event_for_spam signature

changelog.d/12914.misc, synapse/storage/databases/main/event_federation.py, synapse/storage/databases/main/events_worker.py, synapse/storage/schema/__init__.py
A first step for #12892, and another go at #3613. `event_edges.room_id` is implied by the event id, so there is no need to join on the room id.
=> Stop reading from `event_edges.room_id`.

changelog.d/12885.misc, synapse/storage/databases/main/presence.py
While the query was fast, we were calling it *a lot*.
=> Reduce DB load of /sync when using presence

changelog.d/12732.feature, docs/sample_config.yaml, docs/usage/configuration/config_documentation.md, synapse/config/repository.py, synapse/rest/media/v1/media_repository.py, tests/rest/media/test_media_retention.py
Closes https://github.com/matrix-org/synapse/issues/6832.
Adds configuration options for automatically removing media if it hasn't been accessed (either locally or remotely) after a certain period of time. This is managed by an hourly background job that searches the database for old media according to the configured lifetimes, removing the files from disk if any is found.
TODO:
Questions:
* ~~Do we apply any jitter to our background jobs? Otherwise I feel that a lot is going to happen 1hr after your start your homeserver.~~ I don't think we do. However, the period is now configurable with the default being every 24 hours. This is also not really a problem to consider in this PR.
=> Add config options for media retention

changelog.d/12925.misc, synapse/federation/federation_base.py, synapse/federation/federation_client.py, synapse/federation/federation_server.py
Attempts to log less useless stuff, and give clearer warnings about what's going on when there are genuine fails.
Review commit-by-commit.
=> Improve logging when signature checks fail

changelog.d/12932.bugfix, synapse/rest/media/v1/media_repository.py, synapse/rest/media/v1/thumbnailer.py
We are meant to call close on `Image` after we're done with it, which we don't do. It's unclear to me if `Image` eventually does clear up its data if you don't call `close()`, but we should do it regardless.
=> Fix potential thumbnail memory leaks.

changelog.d/12936.removal, docs/workers.md, synapse/api/constants.py, synapse/appservice/__init__.py, synapse/config/appservice.py, synapse/handlers/room.py, synapse/storage/databases/main/media_repository.py, tests/api/test_auth.py, tests/api/test_ratelimiting.py, tests/appservice/test_api.py, tests/appservice/test_appservice.py, tests/handlers/test_appservice.py, tests/handlers/test_user_directory.py, tests/rest/client/test_account.py, tests/rest/client/test_login.py, tests/rest/client/test_register.py, tests/rest/client/test_room_batch.py, tests/storage/test_user_directory.py, tests/test_mau.py
* Updates worker docs to remove endpoints that no longer exist. (Missed in #12553.)
* Removes a (now) unneeded bit of application services. (Clean-up from #12558.)
* Break media repo dependency on groups.
* Clean-up room upgrades. (Missed in #12553).
Part of #11584.
=> Remove remaining bits of groups code.

.github/workflows/tests.yml, changelog.d/12933.misc
=> Fix complement tests using the wrong path

changelog.d/12951.feature, synapse/rest/media/v1/preview_html.py, tests/rest/media/v1/test_html_preview.py
Namely the target here was [our documentation](https://matrix-org.github.io/synapse).
Note that the broken image is #1309.
=> Improve URL previews for some pages

changelog.d/12952.feature, docs/admin_api/user_admin_api.md, synapse/rest/admin/users.py
Signed-off-by: Jan Christian Grünhage <jan.christian@gruenhage.xyz>
Fixes  #12949
=> Allow updating passwords using the admin api without logging out devices

changelog.d/12950.bugfix, synapse/rest/media/v1/preview_url_resource.py, tests/rest/media/v1/test_url_preview.py
Fixes #5298.
If we fail to download an image (i.e. due to a 404), or are unable to process that image. We should still return *something* for the URL preview.
=> Do not break URL previews if an image 404s

changelog.d/12964.misc, synapse/federation/sender/__init__.py, synapse/handlers/typing.py, synapse/state/__init__.py, synapse/storage/_base.py, synapse/storage/controllers/state.py, synapse/storage/databases/main/roommember.py, tests/federation/test_federation_sender.py, tests/handlers/test_typing.py
Reducing the amount of state we pull from the DB is useful as fetching state is expensive in terms of DB, CPU and memory.
=> Reduce state pulled from DB due to sending typing and receipts over federation

changelog.d/12966.removal, synapse/_scripts/synapse_port_db.py, synapse/handlers/profile.py, synapse/storage/databases/main/__init__.py, synapse/storage/databases/main/profile.py, synapse/storage/databases/main/purge_events.py, synapse/storage/schema/__init__.py, tests/rest/admin/test_room.py
Hopefully the last piece of #11584 before dropping the tables.
This removes two things:
* A stream generator which is now unused.
* The remote profile cache feature, which is now unused.
=> Remove more remaining pieces of groups code.

changelog.d/12972.feature, docs/usage/configuration/config_documentation.md, synapse/rest/admin/media.py, synapse/rest/media/v1/media_repository.py, synapse/storage/databases/main/media_repository.py, tests/rest/media/test_media_retention.py
Fixes https://github.com/matrix-org/synapse/issues/12928
This PR prevents local or remote media marked as "quarantined" from being purged by active media retention config.
This serves as a fix to https://github.com/matrix-org/synapse/pull/12732, and uses the same changelog entry.
=> Prevent local quarantined media from being claimed by media retention

changelog.d/12977.feature, synapse/storage/databases/main/media_repository.py
Addresses https://github.com/matrix-org/synapse/pull/12972#discussion_r891058932.
Includes the same changelog as https://github.com/matrix-org/synapse/pull/12972 as it fixes a bug in the implementation.
=> Prevent breaking old sqlite's when media retention is enabled

changelog.d/12970.misc, synapse/handlers/device.py, synapse/module_api/__init__.py, synapse/rest/admin/devices.py, synapse/rest/client/devices.py, synapse/rest/client/logout.py, synapse/storage/databases/main/devices.py, tests/handlers/test_device.py
By removing the `delete_device` methods and directly calling `delete_devices` with a single device ID.
I always find it confusing we have both and they have gotten out of sync in the past.
=> Consolidate the logic of delete_device/delete_devices

changelog.d/12969.misc, synapse/storage/databases/main/state.py
This comment was originally added in #6729 and then modified in #10245 to stop checking the create event (and only depend on the data in `rooms.room_version`. The comment lies though and says it falls back to the create event.
A combination of #6847/#7070 made it so that all nulls are filled in, but as far as I can see the column is still nullable though it seems that, so not sure if this change was on purpose.
=> Fix a stale comment in get_room_version_id_txn.

changelog.d/12963.misc, synapse/federation/sender/per_destination_queue.py
Currently we pull out all hosts in the room for each event we want to send to check that the server is allowed to see the event, even for public rooms. Instead, let's use `filter_events_for_server` which does the right thing.
=> Reduce amount of state we pull out when attempting to send catchup PDUs.

changelog.d/12979.bugfix, synapse/storage/databases/main/events.py, synapse/storage/engines/__init__.py, synapse/storage/engines/postgres.py, synapse/storage/prepare_database.py
Fixes #12962.
Closes #12974.
I mooted using some kind of dummy class in https://github.com/matrix-org/synapse/pull/12734/files#r873691359. This is different approach, but the idea is the same: try the imports, and define a stub for the `isinstance` checks if the imports fail.
=> Use dummy fallback engines if imports fail

changelog.d/12984.misc, synapse/config/experimental.py, synapse/rest/client/relations.py, tests/rest/client/test_relations.py
This wasn't done in #11941 for some reason and I don't know why.
=> Move the dir parameter for /relations behind an experimental flag.

changelog.d/12957.misc, synapse/storage/databases/main/receipts.py
This is by far the greatest cause of serialisation errors in our instance. Read committed is actually beneficial here because we check for a receipt with greater stream order, and checking the very latest data at select time is better than the data at transaction start time (I think :)).
Signed off by Nick @ Beeper
=> Use READ COMMITTED isolation level when inserting read receipts

changelog.d/12985.misc, mypy.ini, synapse/state/v2.py, tests/state/test_v2.py
Drive-by. I was looking at this and wrote annotations to make more sense of it.
Recommend commit-by-commit review.
=> Type annotations for `test_v2`

changelog.d/13004.misc, synapse/handlers/federation.py, synapse/handlers/federation_event.py, synapse/handlers/message.py, synapse/storage/controllers/persist_events.py, synapse/storage/controllers/state.py, synapse/storage/databases/main/room.py, synapse/storage/databases/main/state.py, synapse/storage/state.py
... to help us keep track of these things
=> Faster joins: add issue links to the TODOs

changelog.d/12991.bugfix, synapse/federation/federation_client.py, tests/handlers/test_room_summary.py
This was missed during work for #10946, we should not be returning a `room_id` for each item in the return `children_state` field. Unfortunately we validate that it is there and a string when fetching over federation, thus we can't just remove it.
=> Stop depending on `room_id` to be returned for children state in the hierarchy response.

changelog.d/13013.misc, contrib/graph/graph.py, contrib/graph/graph2.py, contrib/graph/graph3.py
I had a need to run the `graph2` script and get it running on Python 3. The changes were straightforward to make to all 3 files so I went ahead and did that.
Note that `graph.py` still won't run, the API it calls doesn't exist on homeservers (and I cannot find a reference to it ever existing).
=> Fix-up the graph scripts

changelog.d/13017.misc, synapse/event_auth.py, synapse/events/validator.py, synapse/handlers/event_auth.py, synapse/handlers/federation.py, synapse/handlers/federation_event.py, synapse/handlers/message.py, synapse/handlers/room.py, synapse/state/v1.py, synapse/state/v2.py, tests/test_event_auth.py
`validate_event_for_room_version` and `check_auth_rules_for_event` both take a dedicated `room_version` parameter, which is redundant because it is the same as  `event.room_version`.
Apart from simplifying the interface, this also means we can get rid of a few `store.get_room_version` calls.
The parameter was added in #4482 (though the code has evolved a lot since then), but it's been redundant since #6875 gave events their own room version property. 
=> Remove redundant `room_version` object from event auth functions

changelog.d/13047.feature, docs/modules/spam_checker_callbacks.md
Missed that in https://github.com/matrix-org/synapse/pull/12857 since that PR was opened before 1.61's first RC.
=> Fix version number in spam checker callbacks doc

changelog.d/13048.misc, scripts-dev/complement.sh
As it takes longer than 10m to run the postgres tests too.
=> Up complement time outs

changelog.d/13052.misc, synapse/app/appservice.py, synapse/app/client_reader.py, synapse/app/event_creator.py, synapse/app/federation_reader.py, synapse/app/federation_sender.py, synapse/app/frontend_proxy.py, synapse/app/media_repository.py, synapse/app/pusher.py, synapse/app/synchrotron.py, synapse/app/user_dir.py
This makes it possible to import them and call the `main()` function,
e.g. if you were supposedly developing a new way to launch Synapse.
Part of #13051 — scaffolding needed to make Complement-with-workers CI faster.
=> Refactor entry points so that they all have a `main` function.

changelog.d/13061.misc, tests/handlers/test_federation.py, tests/state/test_v2.py
Fixes #13059. See individual commits.
Tested locally with `pip install git+https://github.com/twisted/twisted.git#trunk && mypy`.
=> Fix typechecks against twisted trunk

changelog.d/13060.misc, synapse/app/_base.py
Otherwise modules won't work if they name their `__init__` args differently than Synapse.
=> Don't use keyword arguments when initialising modules

changelog.d/13036.feature, synapse/state/__init__.py
I want to try https://github.com/matrix-org/matrix-spec/issues/1118 to see if it makes Synapse quicker to compute state resolutions (particularly when there is little state in conflict). To evaluate if this has a noticeable effect, I would like to add finer metrics tracking the computation of state resolution.
At the moment, we track how much time we spend the state, totalled on a room-by-room basis. When Prometheus asks us for a report, we report the time spent in the largest N rooms, where N = 1 or 10 depending on the configured logging verbosity. This lets us see improvements to the worst-case performance of state-res, but not the average case. To address the latter, add a Histogram which tracks the duration of each individual state resolution.
Completely untested!
=> Track a histogram of state res durations

.github/workflows/tests.yml, changelog.d/13058.misc, docker/Dockerfile, docker/Dockerfile-workers, docker/complement/Dockerfile, scripts-dev/complement.sh
apt-get is frequently one of the spammiest things when scrolling down into Complement logs. Let's quieten it a bit.
Note that nobody seems to have found the ultimate cure for apt-get noise other than `/dev/null`, which I'm reluctant to do...
EDIT: The entire Docker building process is basically spam, so this PR now folds that away.
=> Collapse Docker build commands in Complement CI runs to make the logs easier to read.

changelog.d/13025.misc, mypy.ini, synapse/replication/slave/storage/devices.py, synapse/storage/databases/main/__init__.py, synapse/storage/databases/main/devices.py
This is one of the remaining files in the synapse source tree which isn't checked by mypy. This change starts checking that file.
Most of these fixes were relatively straightforward. The stream id generator/tracker was painful to deal with, though. I've type-ignored that and left a TODO.
Recommend commit-by-commit review.
```diff
Name    Anys    Exprs   Coverage
------------------------------------------------------------------------------------
--- out/any-exprs.txt	2022-06-10 19:23:16.151256162 +0100
+++ out2/any-exprs.txt	2022-06-10 19:22:47.460110866 +0100
@@ -358,0 +359 @@
+                   synapse.storage.databases.main.devices     133     1914     93.05%
@@ -625 +626 @@
-                                                    Total   24391   285258     91.45%
+ …
```
=> Type annotations in `synapse.databases.main.devices`

changelog.d/13065.misc, synapse/event_auth.py, synapse/handlers/event_auth.py, synapse/handlers/federation_event.py, synapse/state/v1.py, synapse/state/v2.py, tests/test_event_auth.py
Some of the event auth checks apply to an event's auth_events, rather than the state at the event - which means they can play no part in state resolution. Move them out to a separate method.
=> Move some event auth checks out to a different method

changelog.d/13073.doc, docs/development/contributing_guide.md
I personally find it confusing to have local output be completely different to CI, so consistency helps a lot here.
I also appreciate being able to hide passing tests; the output is cluttered enough!
=> Add instructions for running Complement with `gotestfmt`-formatted output locally.

changelog.d/13075.misc, docker/complement/README.md, docker/complement/conf/start_for_complement.sh
If no database is configured explicitly, use sqlite.
This means that you don't have to pass any variables into the image.
=> Complement: use SQLite by default

changelog.d/13070.misc, synapse/handlers/room_member.py
=> Reduce the duplication of code that invokes the rate limiter.

changelog.d/13056.feature, synapse/rest/media/v1/preview_html.py, tests/rest/media/v1/test_html_preview.py
In particular this improves URL previews for LWN.net.
We attempt to parse the `twitter:` meta tags and use those to fill in any missing gaps in the `og:` meta tags.
See #12591.
=> Improve URL previews for sites with only Twitter card information

changelog.d/13071.misc, docker/complement/conf/start_for_complement.sh
=> Add a Subject Alternative Name to the certificate generated for Complement tests.

changelog.d/13085.misc, synapse/storage/databases/main/stats.py
Otherwise it gets reported as `simple_select_one_onecol`
=> Add desc to `get_earliest_token_for_stats`

changelog.d/13089.misc, synapse/handlers/federation_event.py
When we fail to persist a federation event, we kick off a task to remove
its push actions in the background, using the current logging context.
Since we don't `await` that task, we may finish our logging context
before the task finishes. There's no reason to not `await` the task, so
let's do that.
Fixes #12987.
----
As part of #12988, we'd like to raise a special exception from deep within the event persistence code.
That exception triggers the bug that we fix in this PR.
=> Fix logging context misuse when we fail to persist a federation event

changelog.d/13062.misc, synapse/rest/client/room.py
Part of #13019
A small one: when I checked where `Auth.check_user_in_room` was being used, it looked like we're using `check_user_in_room_or_world_readable` almost everywhere else, except here. IMO it does not make sense to not allow this without join on world-readable rooms
(run the …
=> Allow MSC3030 'timestamp_to_event' calls from anyone on world-readable rooms.

changelog.d/13045.feature, synapse/handlers/device.py, synapse/handlers/sync.py, synapse/storage/databases/main/devices.py
=> Use new `device_list_changes_in_room` table when getting device list changes

changelog.d/13093.misc, synapse/rest/client/directory.py, tests/rest/client/test_directory.py
Part of #13019.
I'm trying to get rid of `Auth.get_appservice_by_req`, because it does things that `Auth.get_user_by_req` already does. Also, `get_user_by_req` sets up the tracing attributes span correctly, which `get_appservice_by_req` does not.
I also added a test for this specific endpoint, because I could not find one which was covering this branch (maybe in Sytest/Complement, but I have not looked that up)
- Feel free to credit …
=> Simplify the alias deletion logic as an application service.

changelog.d/13098.feature, synapse/storage/databases/main/devices.py
=> Fix type error that made its way onto develop

changelog.d/13087.bugfix, synapse/event_auth.py, tests/test_event_auth.py
Clean up the validation code for `m.room.create` events, and make sure we're checking everything we should do.
=> Fix inconsistencies in event validation for `m.room.create` events

changelog.d/13076.doc, docs/opentracing.md
Currently the opentracing docs in our manual reference un-commenting an option in the configuration file, which is no longer possible since the comments in the configuration file have been removed. This PR removes that reference and points the reader to the configuration manual instead.
=> Update opentracing docs to reference the configuration manual rather than the configuation file.

changelog.d/13106.bugfix, synapse/rest/client/directory.py, tests/rest/client/test_directory.py
Signed-off-by: santhoshivan23 <santhoshivan23@gmail.com>
Added validation checks for room aliases. This patch would prevent requests with invalid room aliases from causing internal server error. Fixes #13104
=> validate room alias before interacting with the room directory

changelog.d/12944.misc, synapse/http/server.py, synapse/rest/media/v1/download_resource.py, synapse/rest/media/v1/thumbnail_resource.py, tests/rest/media/v1/test_media_storage.py
This PR is an implementation of [MSC3828](https://github.com/matrix-org/matrix-spec-proposals/pull/3828) which adds the `Cross-Origin-Resource-Policy: cross-origin` header to the media repository's thumbnail and download endpoints. This is a required header for web-based Matrix clients which use features like `SharedArrayBuffer` which requires the `Cross-Origin-Embedder-Policy: require-corp` header be set.
=> Add Cross-Origin-Resource-Policy header to thumbnail and download media endpoints

changelog.d/13124.misc, mypy.ini, tests/test_server.py
Written on a plane to Italy with a throttled battery.
=> Extra type annotations in `test_server`

changelog.d/13118.misc, synapse/storage/databases/main/event_push_actions.py, synapse/storage/databases/main/receipts.py, synapse/storage/schema/main/delta/72/01event_push_summary_receipt.sql, tests/storage/test_event_push_actions.py
Fixes #13117
The idea is that we include the last read receipt in `event_push_summary` when calculating push, and only use the counts if it matches the current read receipt. This allows us to move deleting of push actions out of sending a receipt and into a background task.
=> Fix serialization errors when rotating notifications

changelog.d/13129.misc, synapse/storage/database.py
This came up while investigating why https://github.com/matrix-org/synapse-email-account-validity wasn't creating its database properly. It turns out the `CREATE TABLE` statement this module uses includes comments to explain what each column represents - see https://github.com/matrix-org/synapse-email-account-validity/blob/b05341f2cc56bc1b471138f095e8400438780567/email_account_validity/_store.py#L51-L74
However, this didn't work because by making the query one line we would make everything after the first comment part of that comment, meaning we would get errors about unfinished statement or syntax errors (depending on the engine).
According to the docstring of `_make_sql_one_line` we only need one-lined SQL for logging (which seems to match my understanding of the code), so let's use the …
=> Don't actually one-line the SQL statements we send to the DB

changelog.d/13135.misc, mypy.ini
=> Actually typecheck `tests.test_server`

.github/workflows/tests.yml, changelog.d/13127.misc, docker/complement/conf/start_for_complement.sh, docker/conf-workers/synapse.supervisord.conf.j2, docker/conf/log.config, docker/configure_workers_and_start.py, docker/start.py, synapse/app/_base.py, synapse/app/_complement_fork_starter.py, synapse/app/complement_fork_starter.py
Fixes #13051.
Should be more or less a step-by-step review, but it may be clear enough from the overall diff also, I don't know.
=> Improve startup times in Complement test runs against workers, particularly in CPU-constrained environments.

changelog.d/13141.bugfix, synapse/_scripts/synapse_port_db.py, synapse/storage/databases/main/event_push_actions.py, synapse/storage/schema/main/delta/72/02event_push_actions_index.sql
We need this index to efficiently delete old non-highlight push actions, without having to wade through all the old highlights.
=> Add index to help delete old push actions

changelog.d/13140.bugfix, synapse/storage/databases/main/event_push_actions.py, tests/storage/test_event_push_actions.py
Broke by #13118.
Fixes #13138
The problem was that we would limit the number of rows we pull out of the DB, but always update the latest location to the most recent ID
=> Fix unread counts on large servers

changelog.d/13139.doc, docs/usage/configuration/homeserver_sample_config.md
After reducing the sample config to only a subset of options, this docs page became a bit of a dead end, especially if you were previously using it to search for option descriptions.
This PR simply adds a link to the configuration manual, which is the new place to find option documentation.
=> Add a link to the configuration manual from the homeserver sample config documentation page

changelog.d/13077.doc, docs/admin_api/user_admin_api.md, docs/code_style.md, docs/jwt.md, docs/manhole.md, docs/message_retention_policies.md, docs/openid.md, docs/setup/forward_proxy.md, docs/setup/installation.md, docs/upgrade.md, docs/usage/configuration/config_documentation.md, docs/usage/configuration/user_authentication/single_sign_on/cas.md, synapse/config/emailconfig.py
Now that the comments in the configuration file have been removed, users must use the configuration manual instead of referencing the comments in the sample config. This PR removes relevant references to the sample config in the docs and adds references to the configuration manual instead.
=> Cleanup references to sample config in the docs and redirect users to configuration manual

changelog.d/13134.misc, synapse/handlers/message.py
Currently we check the ratelimit for a /send request after quite a bit of processing has already occurred. This PR adds a ratelimit check much earlier in the processing, reducing unnecessary processing and remediating performance delays caused by processing over-ratelimit requests. Fixes #13072.
=> Don't process /send requests for users who have hit their ratelimit

changelog.d/13144.misc, synapse/state/__init__.py, tests/test_state.py
When we receive an event over federation during a faster join, there is no need
to wait for full state, since we have a whole reconciliation process designed
to take the partial state into account.
=> Skip waiting for full state for incoming events

changelog.d/13145.misc, synapse/handlers/federation_event.py
`_check_event_auth` is expected to raise `AuthError`s, so no need to log it again.
=> `_process_received_pdu`: Improve exception handling

changelog.d/13143.misc, scripts-dev/complement.sh
Add a `-f` argument to `complement.sh` to skip the docker build
The docker bits take 10 seconds or so even if everything is cached, so if you just want to rerun some complement tests, it's nice to be able to skip them.
=> complement.sh: Permit skipping docker build

changelog.d/13156.bugfix, poetry.lock
Changes the locked version only, so only affects docker images and debian packages.
See https://github.com/matrix-org/matrix-synapse-ldap3/issues/165 for more context.
=> matrix-synapse-ldap3: 0.2.0 -> 0.2.1

changelog.d/13159.misc, mypy.ini, tests/server.py, tests/utils.py
Replaces #11349.
Not many changes needed to do this these days compared to back then. Let's finish it off!
=> Remove tests/utils.py from mypy's exclude list

changelog.d/13168.bugfix, synapse/storage/databases/main/event_push_actions.py, tests/storage/test_event_push_actions.py
There was an off-by-one error due to incorrect bounds on stream ordering.
=> Fix stuck notification counts on small servers 

changelog.d/13136.misc, tests/rest/admin/test_room.py, tests/rest/admin/test_user.py, tests/rest/client/test_account.py, tests/rest/client/test_profile.py, tests/rest/client/test_relations.py, tests/server.py
and fix up tests that are inspecting json_body.
I chose to annotate this as `Dict[str, Any]` (although it could in
principle be any json payload: str, number, list, boolean, null).
Mypy now knows that json_body.get("foo") returns `Optional[Any]` and is
complaining in a few places. I generally replaced these with direct
lookups, since either
- the test would already fail if the key was missing, or
- the test probably ought to fail if the key was missing.
Happy to be persuaded otherwise if you're not convinced.
- End with either a …
=> annotate tests.server.FakeChannel

changelog.d/13166.doc, docs/usage/configuration/config_documentation.md
=> Add missing links to config options

changelog.d/13131.bugfix, synapse/handlers/room_member.py
Fix application service not being able to join remote federated room without a profile set
Fix https://github.com/matrix-org/synapse/issues/4778
Complement tests: https://github.com/matrix-org/complement/pull/399
(run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing …
=> Fix application service not being able to join remote federated room without a profile set

.ci/scripts/setup_complement_prerequisites.sh, .github/workflows/tests.yml, .github/workflows/twisted_trunk.yml, changelog.d/13157.misc
This seemed like the least bad way to do it.
A little bit of trickery is included to cleanly create log groups for the setup portions, without also tracing (due to `-x`) the `echo` statements for these.
=> Factor out some common Complement CI setup commands to a script.

changelog.d/13174.bugfix, synapse/events/third_party_rules.py
When adding a `on_new_event` handler on a federated homeserver, I keep hitting:
```python
File "/usr/local/lib/python3.9/site-packages/synapse/replication/tcp/handler.py", line 285, in _unsafe_process_queue
await self._process_command(cmd, conn, stream_name)
File "/usr/local/lib/python3.9/site-packages/synapse/replication/tcp/handler.py", line 300, in _process_command
await self._process_rdata(stream_name, conn, cmd)
File "/usr/local/lib/python3.9/site-packages/synapse/replication/tcp/handler.py", line 516, in _process_rdata
await self.on_rdata(stream_name, cmd.instance_name, cmd.token, rows)
File "/usr/local/lib/python3.9/site-packages/synapse/replication/tcp/handler.py", line 531, in on_rdata
await self._replication_data_handler.on_rdata(
File …
```
=> Make `_get_state_map_for_room` not break when room state events don't contain an event id.

changelog.d/13195.misc, docs/postgres.md, synapse/_scripts/synapse_port_db.py
The portdb script relies on `rowid`s being consistent.
`VACUUM` does not uphold that.
`auto_vacuum` is not enabled by default (unless SQLite was compiled with an option to make it default), but I'm aware that
some community members manually VACUUM and I wouldn't be surprised if some of them enabled `auto_vacuum` themselves.
Doing so is dangerous for the portdb script as it means that some rows may be omitted from the copy.
For safety's sake, let's prohibit `auto_vacuum` when porting a database **and** document that manual `VACUUM` are also not to be done.
=> Check that `auto_vacuum` is disabled when porting a SQLite database to Postgres, as `VACUUM`s must not be performed between runs of the script.

changelog.d/13151.misc, synapse/handlers/federation.py, synapse/replication/http/__init__.py, synapse/replication/http/state.py, synapse/state/__init__.py, synapse/storage/controllers/persist_events.py, synapse/storage/databases/main/events.py, tests/test_state.py
When we finish un-partial stating all events in a room, we recalculate
the current state using forward extremities. This can race with
persistence of another event, which could result in an invalid current
room state in the database.
To avoid the race, we recalculate current room state in the same
queue as event persistence. The event persistence queue may be on
another worker, so a new replication endpoint is required as well.
Fixes #13007.
---
May be easiest to review commit by commit.
=> Faster room joins: fix race in recalculation of current room state

changelog.d/13200.removal, tests/storage/test_room.py
This method does not exist in `HomeServer` since version `v0.6.0`, where
it was removed in commit 3c77d13aa537 - `Kill off synapse.api.events.*`.
The method was basically replaced with `get_event_builder_factory`
before mentioned removal, except this one place, most probably because
all tests are prefixed with `STALE_` and therefore they are silently
skipped. They were moved to `STALE_` in version `v0.5.0` in commit
2fcce3b3c508 - `Remove stale tests`.
Tests from `RoomEventsStoreTestCase` class are not used for last 8
years, I believe the best would be to remove them entirely.
- Use …
=> Remove obsolete RoomEventsStoreTestCase

changelog.d/13223.bugfix, synapse/storage/databases/main/event_push_actions.py, tests/storage/test_event_push_actions.py
The crux of the problem was that when we rotated the notifications we didn't filter out read-but-highlighted messages. This only affected highlights as we delete non-highlights after they're read.
Fixes #13196
Broke by #13005
=> Fix notification count after a highlighted message

.editorconfig, changelog.d/13228.misc
See the documentation for the property here:
https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#max_line_length
Signed-off-by: Sumner Evans <me@sumnerevans.com> …
=> editorconfig: add max_line_length for Python files

changelog.d/13226.bugfix, synapse/_scripts/synapse_port_db.py
#982 tried to fix this problem (missing rows with negative row ids), but unfortunately it only selected at most one batch_size's worth of such rows (default: 1000).
The `backward_select` query uses the `backward_chunk` variable as an
inclusive upper bound on the rowids it selects. It is initially 0 (see
`setup_table`). It is then set to
```
backward_chunk = min(row[0] for row in brows) - 1
```
where `brows` is the result of running the `backwards_select` query.
For this to make sense, we need to ensure that `backwards_select` picks
rows in descending order. Otherwise we'll jump right to the bottom of
the rowids, pick out the lowest batch only and discard everything we
skipped over. This is a Bad Thing.
I've tested this locally with the reproduction case reported in #13191.
Without the …
=> Ensure portdb selects _all_ rows with negative rowids

changelog.d/13236.bugfix, synapse/appservice/scheduler.py
As is in the case of presence.
Fixes this error:
```
element-dev-stack-eledev-synapse-1      | 2022-07-09 02:04:50,721 - synapse.metrics.background_process_metrics - 242 - ERROR - as-sender-encrypted_appservices-13 - Background process 'as-sender-encrypted_appservices' threw an exception
element-dev-stack-eledev-synapse-1      | Traceback (most recent call last):
element-dev-stack-eledev-synapse-1      |   File "/usr/local/lib/python3.9/site-packages/twisted/internet/defer.py", line 1660, in _inlineCallbacks
element-dev-stack-eledev-synapse-1      |     result = current_context.run(gen.send, result)
element-dev-stack-eledev-synapse-1      | StopIteration: 504208
element-dev-stack-eledev-synapse-1      | 
element-dev-stack-eledev-synapse-1      | During handling of the above exception, …
```
=> Fix appservice EDUs failing to send if the EDU doesn't have a room ID

changelog.d/13222.misc, synapse/app/admin_cmd.py, synapse/visibility.py
This is going to be used in a refactor of the bulk push rule evaluator.
First we refactor existing methods to allow us to reuse the code.
=> Add a `filter_event_for_clients_with_state` function

changelog.d/13211.misc, synapse/storage/databases/main/event_push_actions.py
We want to be as up to date as possible, and sleeping doesn't help here and can mean we fall behind.
=> Remove delay when rotating event push actions

changelog.d/13257.misc, synapse/storage/util/partial_state_events_tracker.py
The stack is already logged when waiting for an event to be un-partial
stated. Log the stack for rooms as well.
---
When writing complement tests for faster room joins, debugging failing tests is easier when there's a nice big indicator in the logs when Synapse blocks itself waiting for full state.
=> Faster room joins: Log the stack when waiting for a entire room to be un-partial stated

changelog.d/13218.misc, synapse/storage/schema/main/delta/72/03drop_event_reference_hashes.sql
This is unused since Synapse 1.60.0 (#12679). It's time for it to go.
Fixes #6574.
=> Drop unused table `event_reference_hashes`

changelog.d/13175.misc, synapse/appservice/api.py
Add some more counters for the new types of content that we now push to app services.
Signed-off-by: Brad Murray [brad@beeper.com](mailto:brad@beeper.com)
=> Add prometheus counters for content types other than events

changelog.d/13224.misc, synapse/handlers/room.py, synapse/handlers/room_member.py, tests/rest/client/test_rooms.py
Next steps on top of: https://github.com/matrix-org/synapse/pull/13210
This takes things further by:
- Covering the name/topic/invite events with the same logic passing previous events around
- Explicitly define depth for events sent into a new room, avoiding repeat lookups between each event for this
Signed off by Nick @ Beeper (@fizzadar)
=> Optimise room creation event lookups part 2

changelog.d/13231.doc, docs/usage/administration/admin_api/README.md
Pointed out, that the Admin API is not accessible by default from any remote computer, but only from the PC `matrix-synapse` is running on.
Added a full, working example, making sure to include the cURL flag `-X`, which needs to be prepended to `GET`, `POST`, `PUT` etc. and listing the full query string including protocol, IP address and port.
Signed-off-by: jejo86 28619134+jejo86@users.noreply.github.com
=> Document advising against publicly exposing the Admin API and provide a usage example

changelog.d/13254.misc, synapse/notifier.py
Pulled out of #13169.
The per-room join rate planned for #12710 needs to be incremented by
- the event persistence logic, when persisting a join; and
- the replication logic, when one worker learns of a new event persisted by another worker.
The rate limiter itself will be kept on the RoomMemberHandler (i.e. the thing which services joins). We need a way for the incrementers to tell the room member handler that a join has happened. I first tried to make the relevant handlers directly call out to the RoomMemberHandler, but this introduced circular dependencies among the homeserver `cache_in_self` attributes. Break the dependency by using the notifier.
=> Notifier: accept callbacks to fire on room joins

changelog.d/13253.misc, synapse/api/ratelimiting.py, tests/api/test_ratelimiting.py
This adds a new `record_action` method to Ratelimiters. It allows them to track occurrences of an action which they are not in a position to deny.
For motivation, the example I have in mind is a rate limiter which tracks the number of joins in a room (#12710). Any homeserver in the room can create and publish a join event via the `make_join`/`send_join` handshake. The rate limiter needs to track these joins so it can accurately reject future joins requested of it. But we cannot refuse those incoming joins: they have already taken place and are already part of the room.
Pulled out of #13169.
=> Allow rate limiters to passively record actions they cannot limit

changelog.d/13251.misc, synapse/federation/sender/__init__.py, synapse/handlers/appservice.py, synapse/storage/databases/main/appservice.py, synapse/storage/databases/main/events_worker.py, synapse/storage/databases/main/stream.py, tests/handlers/test_appservice.py
Found this by accident while poking around on room creation optimisation; two things:
+ Use same get events stream DB query as the federation senders do in the appservice worker
- this moves the AS pusher closer to the federation sender instances - which we'd like to setup to run multiple AS pushers in parallel just as you can fed senders
- de-dupes the two near-identical functions into one for a bit of cleanup
+ Pull down event received TS in the stream query and thus remove the additional query to fetch this
- the received TS is fetched per event processed by both of these workers, so this has potential to yield a significant reduction in query traffic depending on the synapse install/size/content
Signed off by Nick @ Beeper (@fizzadar)
(run the …
=> Federation Sender & Appservice Pusher Stream Optimisations

changelog.d/13242.misc, synapse/storage/database.py, synapse/storage/databases/main/cache.py, synapse/storage/databases/main/events.py, synapse/storage/databases/main/events_worker.py, synapse/storage/databases/main/purge_events.py, synapse/storage/databases/main/roommember.py, synapse/util/caches/lrucache.py, tests/handlers/test_sync.py, tests/storage/databases/main/test_events_worker.py, tests/storage/test_purge.py
Some experimental prep work to enable external event caching based on https://github.com/matrix-org/synapse/pull/9379 & https://github.com/matrix-org/synapse/pull/12955. Doesn't actually move the cache at all, just lays the groundwork for async implemented caches.
One change here is the invalidation is now divided into two types: async which the "primary" invalidator must call and local which is for replication based invalidation that happens after the async invalidation is completed. Any external cache is thus invalidated after database update and before local in memory process caches.
This should solve the original invalidation problem spotted in #9379 unblocking implementation of actual external cache classes. Passes tests & complement w/workers locally. This work is primarily for our …
=> Async get event cache prep

changelog.d/13279.misc, docker/complement/Dockerfile, docker/complement/conf/postgres.supervisord.conf
When building the docker images for complement testing, copy a preinstalled complement over from a base image, rather than apt installing it. This avoids network traffic and is much faster.
An attempt to improve the situation in #13204.
=> Docker: copy postgres from base image

changelog.d/13278.bugfix, synapse/state/__init__.py, synapse/storage/controllers/persist_events.py, tests/test_state.py
There are two fixes here:
1. A long-standing bug where we incorrectly calculated `delta_ids`; and
2. A bug introduced in https://github.com/matrix-org/synapse/pull/13267 where we got current state incorrect.
=> Fix a bug which could lead to incorrect state

changelog.d/13215.misc, synapse/storage/databases/main/events_bg_updates.py, synapse/storage/schema/main/delta/72/03bg_populate_events_columns.py
Part 3 of my long-held secret scheme to kill off the `state_events` and `rejections` tables: see https://github.com/matrix-org/synapse/issues/11496.
These columns were added back in Synapse 1.52 (#11792), and have been populated for new events since then. It's now (beyond) time to back-populate them for existing events.
=> Bg update to populate new `events` table columns

changelog.d/13284.misc, poetry.lock
`frozendict` 2.3.2 includes a fix for a memory leak in
`frozendict.__hash__`. This likely has no impact outside of the
deprecated `/initialSync` endpoint, which uses `StreamToken`s,
containing `RoomStreamToken`s, containing `frozendict`s, as cache keys.
=> Update locked frozendict version to 2.3.2

changelog.d/13270.bugfix, synapse/events/builder.py, synapse/handlers/room_member.py, synapse/state/__init__.py
Before this change, we were using the current state of the room. (The two are usually but not always consistent.)
Fixes #13269, see there for context and motivation. Commitwise review recommended.
#10254 introduced some of the logic I'm changing here.
=> Use state before join to determine if we `_should_perform_remote_join`

changelog.d/13297.misc, tests/federation/test_complexity.py, tests/federation/test_federation_server.py, tests/federation/transport/test_knocking.py, tests/handlers/test_password_providers.py, tests/rest/admin/test_user.py, tests/rest/client/test_account.py, tests/rest/client/test_login.py, tests/rest/client/test_rooms.py
=> Use HTTPStatus constants in place of literals in tests

changelog.d/13304.misc, synapse/handlers/typing.py, synapse/replication/slave/storage/devices.py, synapse/replication/slave/storage/push_rule.py, synapse/replication/slave/storage/pushers.py, synapse/replication/tcp/client.py, synapse/storage/_base.py, synapse/storage/databases/main/account_data.py, synapse/storage/databases/main/cache.py, synapse/storage/databases/main/deviceinbox.py, synapse/storage/databases/main/events_worker.py, synapse/storage/databases/main/presence.py, synapse/storage/databases/main/receipts.py, synapse/storage/databases/main/tags.py
More prep work for asyncronous caching, also makes all `process_replication_rows` methods consistent (presence handler already is so).
Signed off by Nick @ Beeper (@fizzadar)
=> Make all `process_replication_rows` methods async

changelog.d/13307.misc, tests/rest/client/test_rooms.py
#13281 seems to have changed the number of expected database queries required when creating a room, thus breaking the following tests on develop:
- `tests.rest.client.test_rooms.RoomsCreateTestCase.test_post_room_no_keys`: 36 -> 43 queries
- `tests.rest.client.test_rooms.RoomsCreateTestCase.test_post_room_initial_state`: 40 -> 49 queries
It's currently not clear why the number of queries increased with the change. @DMRobertson proposed:
> I guess because we don't have a cache which takes the filter into account
=> Update expected DB query count when creating a room

changelog.d/13172.misc, poetry.lock, pyproject.toml
I've recently seen people complaining about getting bitten by https://github.com/matrix-org/python-canonicaljson/issues/36 so figured we might as well ensure we use a patched version of it in Synapse.
=> Up the dependency on canonicaljson to ^1.5.0

changelog.d/13296.bugfix, synapse/push/pusherpool.py
=> Fix overcounting of pushers when they are replaced

changelog.d/13300.misc, synapse/storage/databases/main/push_rule.py, synapse/storage/databases/main/roommember.py
This fell out of some investigation I was doing with Eric re: increasing local room join performance. Many small batches were being sent to the DB for processing by these calls (especially in larger rooms), and it seems that we could probably up the batch size some and hopefully improve overall transaction time.
=> Increase batch size of `bulk_get_push_rules` and `_get_joined_profiles_from_event_ids`.

changelog.d/13271.doc, contrib/workers-bash-scripts/create-multiple-generic-workers.md, contrib/workers-bash-scripts/create-multiple-stream-writers.md
This PR adds another bash script to contrib directory. It creates multiple stream writers and also prints out the example configuration for homeserver.yaml.
Also, renamed my first script for distinctness.
(run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.h …
=> Bash script for creating multiple stream writers

changelog.d/13326.removal, scripts-dev/build_debian_packages.py
=> Stop building Ubuntu 21.10 (Impish Indri) which is end of life.

changelog.d/13323.misc, synapse/storage/databases/state/bg_updates.py
We intern the key/values (which we already do for the current state caches), so that we deduplicate e.g. event types.
I think this causes roughly a 25-50% drop in memory usage from state group caches.
=> Reduce memory usage of state group cache

changelog.d/13258.misc, synapse/handlers/federation_event.py
This warning showed up while I was testing faster room joins using Complement.
On closer inspection it turned out to be triggering incorrectly.
=> Fix spurious warning when fetching state after a missing prev event

changelog.d/13332.bugfix, synapse/push/bulk_push_rule_evaluator.py, tests/push/test_push_rule_evaluator.py
This can cause a lot of extra load on servers with lots of appservice users. Introduced in https://github.com/matrix-org/synapse/pull/13078
=> Don't include appservice users when calculating push rules

changelog.d/13318.misc, synapse/http/matrixfederationclient.py, tests/federation/test_federation_client.py
Fixes #13155. Currently we have some validation for destinations in place but apparently we are missing some code paths, part of the idea behind this PR to use the logging to pick out where validation is missing.
=> Validate federation destinations and log an error if server name is invalid.

changelog.d/13342.misc, synapse/storage/database.py
By my reckoning, this should mean that each txn `desc` produces 2 time
series, down from 17. If we don't like this, we could keep the histogram
but configure it with coarser buckets.
This saves on storage and CPU cycles. We don't use the full histogram distribution in our dashboards, so we think this is safe to drop.
Closes #11081.
=> Track DB txn times w/ two counters, not histogram

changelog.d/13324.misc, synapse/state/__init__.py
We have a `state_cache`  in `StateHandler` which stores the result of a state resolution. This is an `ExpiringCache`, rather than an `LruCache`, and so doesn't support the full set of cache expiry config options, which means we should try and keep this cache as small as possible. 
It's fairly safe to drop storing the `state` (whenever possible), as we have a separate cache for storing the state of each state group, so removing `state` from the `StateCacheEntry` is really only deduplicating the cached dicts. 
There's also a commit to make the `__len__` a bit more accurate.
=> Don't hold onto full state in state cache

changelog.d/13354.misc, synapse/handlers/federation_event.py
When a room has the partial state flag, we may not have an accurate
`m.room.member` event for event senders in the room's current state, and
so cannot perform soft fail checks correctly. Skip the soft fail check
entirely in this case.
As an alternative, we could block until we have full state, but that
would prevent us from receiving incoming events over federation, which
is undesirable.
=> Skip soft fail checks for rooms with partial state

changelog.d/13352.bugfix, docs/upgrade.md, poetry.lock
frozendict 2.3.3 includes fixes for memory leaks that get triggered
during `/sync`.
Resolves #13282.
Resolves #13286.
=> Update locked frozendict version to 2.3.3

changelog.d/13313.misc, synapse/handlers/presence.py, synapse/storage/_base.py, synapse/storage/databases/main/roommember.py
See #10826 and #10786 for context as to why we had to disable pruning on those caches.
`get_users_who_share_room_with_user` is currently only called frequently in the presence code. So we just need to refactor presence to call the function less frequently, and then we can remove the various levels of caching that is going on.
Note: I've tested this on jki.re, and it doesn't seem to change the performance much. The DB query also seems fairly efficient based on testing on jki.re and matrix.org DBs.
=> Refactor presence so we can prune user in room caches

changelog.d/13362.misc, synapse/logging/opentracing.py
Should fix #13357.
I couldn't get poetry to properly update mypy / mypy-zope, but the changes are fine to do and pass with the current versions too.
=> Additional fixes for opentracing type hints.

changelog.d/13383.misc, synapse/handlers/relations.py, synapse/storage/databases/main/relations.py
Should have been removed in #12293. This option is unused, let's remove it.
=> Remove unused argument for get_relations_for_event.

changelog.d/13354.misc, changelog.d/13355.misc, synapse/handlers/federation_event.py, synapse/handlers/message.py, synapse/state/__init__.py, synapse/storage/controllers/state.py, tests/handlers/test_federation.py, tests/storage/test_events.py, tests/test_state.py
Avoid blocking on full state in `_resolve_state_at_missing_prevs` and
return a new flag indicating whether the resolved state is partial.
Thread that flag around so that it makes it into the event context.
Resolves #13002.
---
Corresponding Complement tests: https://github.com/matrix-org/complement/pull/419
Best reviewed commit by commit.
The first commit is from #13354.
=> Faster room joins: avoid blocking when pulling events with missing prevs

changelog.d/13365.bugfix, synapse/handlers/room_summary.py
Fixes #10946
Needs the corresponding complement changes at matrix-org/complement#422.
=> Stop returning the room_id from the `/hierarchy` endpoint.

changelog.d/12978.misc, scripts-dev/release.py
This is a typically error-prone part of our process, so it seems to make sense to try and automate it.
Should be a commit-by-commit review.
Unfortunately I haven't tested it myself yet, since I already did it :/.
Marking as a release blocker to try and give someone the idea that they should try it before creating the branch themselves.
It will only create the branch if it's also responsible for creating the branch on Synapse, **so you need to disregard the wiki instructions a bit and just run it straight on develop**.
(You probably need to make a copy of the script outside of the tree first, or you'll get told off for having a dirty tree)
=> Extend the release script to automatically push a new SyTest branch, rather than having that be a manual process.

changelog.d/13392.bugfix, synapse/handlers/typing.py
We encouter this from time to time:
```
RuntimeError  in synapse.handlers.typing in get_new_events_as: dictionary changed size during iteration
```
The await call to `service.is_interested_in_room` makes this possible and copying the data before generating events should work around it.
=> Copy room serials before handling in `get_new_events_as`

changelog.d/13346.misc, synapse/federation/federation_client.py
Fix `get_pdu` asking every remote destination even after it finds an event
As discovered by @richvdh, https://github.com/matrix-org/synapse/pull/13320#discussion_r924273830
> wait... does this loop *always* try all the destinations, even if the first one works? that would be a substantial bug, if it was ever called with more than one destination, which I don't think it is...
- Feel free to credit yourself, by adding a sentence "Contributed …
=> Fix `get_pdu` asking every remote destination even after it finds an event

changelog.d/13413.bugfix, synapse/handlers/federation_event.py, synapse/storage/databases/main/state.py
=> Faster joins: fix rejected events becoming un-rejected during resync

.github/workflows/tests.yml, changelog.d/13420.misc
Looking at #13161 and the status on recent PRs, the really big painful flakes have now been dealt with.
I don't think we've reached perfection, but that might take months! The remaining flakes of which I am aware are considerably rarer than the ones that kept biting us a few weeks ago.
=> Re-enable running Complement tests against Synapse with workers.

.github/workflows/latest_deps.yml, changelog.d/13213.misc, docker/Dockerfile, scripts-dev/complement.sh
=> Enable Complement CI tests in the 'latest deps' test run.

changelog.d/13404.misc, synapse/handlers/federation_event.py, synapse/state/__init__.py, synapse/storage/controllers/state.py, tests/handlers/test_federation.py
Previously, `_resolve_state_at_missing_prevs` returned the resolved
state before an event and a partial state flag. These were unwieldy to
carry around would only ever be used to build an event context. Build
the event context directly instead.
---
May be easier to review commit by commit.
=> Refactor `_resolve_state_at_missing_prevs` to return an `EventContext`

changelog.d/13431.misc, synapse/handlers/federation_event.py
#13404 removed an import of `Optional` which was still needed (I think because #13413 added more usages).
=> Fix missing import in `federation_event` handler.

changelog.d/13403.misc, synapse/handlers/federation.py, tests/handlers/test_federation.py
=> Faster Room Joins: don't leave a stuck room partial state flag if the join fails.

changelog.d/13432.bugfix, synapse/handlers/federation.py
so that we raise the intended error instead.
---
Fixes #13430:
```
File "/home/synapse/src/synapse/synapse/metrics/background_process_metrics.py", line 240, in run
return await func(*args, **kwargs)
File "/home/synapse/src/synapse/synapse/handlers/federation.py", line 1597, in _sync_partial_state_room
if attempt == len(destinations) - 1:
UnboundLocalError: local variable 'destinations' referenced before assignment
```
=> Fix error when out of servers to sync partial state with

changelog.d/13393.misc, scripts-dev/release.py
I messed this up last time, so it's about time it was taken out of my hands and into the hands of the computer :-).
TODO:
=> Add a `merge-back` command to the release script, which automates merging the correct branches after a release.

changelog.d/13437.doc, docs/usage/configuration/config_documentation.md
=> Fix wrong headline for `url_preview_accept_language` in docs

changelog.d/13428.feature, synapse/module_api/__init__.py, tests/module_api/test_api.py
=> Add module API method to resolve a room alias to a room ID

changelog.d/13442.misc, synapse/api/ratelimiting.py, synapse/config/ratelimiting.py, synapse/rest/client/register.py, synapse/util/ratelimitutils.py
Fixes: #4983
Rename
- `RateLimitConfig` to `RatelimitSettings`
- `FederationRateLimitConfig` to `FederationRatelimitSettings`
=> Rename `RateLimitConfig` to `RatelimitSettings`

changelog.d/13443.doc, docs/usage/configuration/config_documentation.md
=> Update doc for setting `macaroon_secret_key`

changelog.d/13230.doc, docs/usage/administration/admin_api/README.md
Added steps describing how to elevate an existing user to administrator by manipulating a `postgres` database.
Signed-off-by: jejo86 28619134+jejo86@users.noreply.github.com
=> Improve documentation on becoming server admin

changelog.d/13372.docker, docker/Dockerfile
This is needed because poetry depends on cryptography. Without this,
building fails when building on an architecture where an upstream
cryptography wheel is not available - for example, on an
armv7 (raspberry pi 4 not in 64 bits mode).
This fixes #13371 
Signed-off-by: Jasper Spaans <j@jasper.es> …
=> Install cryptography build dependencies in requirements image.

changelog.d/13368.misc, synapse/api/auth.py, synapse/federation/federation_client.py, synapse/handlers/federation.py, synapse/handlers/federation_event.py, synapse/handlers/pagination.py, synapse/handlers/relations.py, synapse/storage/controllers/persist_events.py, synapse/storage/controllers/state.py, synapse/storage/databases/main/stream.py, synapse/streams/events.py, synapse/visibility.py
Instrument `/messages` for understandable traces in Jaeger
Before (huge list of uncategorized database calls) | After (nice and collapsible into units of work)
--- | ---
See https://github.com/matrix-org/synapse/pull/13399
(run the [linters](https://matrix-org.github.io/synapse/latest/development/co …
=> Instrument `/messages` for understandable traces in Jaeger

changelog.d/13439.misc, synapse/handlers/message.py, synapse/handlers/room_member.py
As part of the local joins investigation I'd like to add some tracing spans to get better insight into the timing of processing the `/join` request.
=> Add some tracing spans to give insight into local joins

changelog.d/13429.feature, synapse/module_api/__init__.py, tests/module_api/test_api.py
Please refer to PR title (as it's self-explanatory).
=> Add module API method to create a room

changelog.d/13435.misc, synapse/storage/databases/main/events_worker.py, synapse/storage/databases/main/roommember.py, synapse/util/caches/lrucache.py
We turned on Redis get event caching... and it hammered the CPU! The huge number of lookups came from the roomember optimisation lookup (changed in https://github.com/matrix-org/synapse/commit/030888bbfb7a8b86b06910a79be719ae2a0a9fed). I also changed the get events function to prevent double lookups from any external cache there too (unconfirmed whether that had any impact, but seems sensible).
=> Optimise async get event lookups

changelog.d/13416.misc, synapse/federation/federation_server.py, synapse/handlers/federation.py
Fixes #13290.
Complement test: https://github.com/matrix-org/complement/pull/432
=> Faster Room Joins: prevent Synapse from answering federated join requests for a room which it has not fully joined yet.

changelog.d/13460.misc, synapse/events/snapshot.py, synapse/storage/databases/main/events.py
`Union[Literal[False], str]` is a stupid type.
=> Update type of `EventContext.rejected`

changelog.d/13455.misc, synapse/storage/databases/main/event_push_actions.py
I keep getting lost in this code (there's lots of different stream orderings, min / max, inclusive / exclusive going on).
This adds some docstrings and some inline comments, as well as a few other formatting changes. Should be reviewable commit-by-commit.
There is one functional change in the second commit and some code reordering, that should be a no-op.
=> Add some docstrings (and avoid a duplicate query) in push actions processing

changelog.d/13452.misc, synapse/logging/opentracing.py
Fix `@tag_args` being off-by-one (ahead)
Before | After
--- | ---
Example:
```
argspec.args=[
'self',
'room_id'
]
args=(
<synapse.storage.databases.main.DataStore object at 0x10d0b8d00>,
'!HBehERstyQBxyJDLfR:my.synapse.server'
)
```
(run the …
=> Fix `@tag_args` being off-by-one (ahead)

changelog.d/13445.misc, synapse/storage/databases/main/event_push_actions.py
So that you don't have to read all the code to grok it.
=> Add some comments about how event push actions are stored

changelog.d/13441.feature, synapse/module_api/__init__.py, tests/module_api/test_api.py
The current implementation is a manifestation of the discussion that ended [here](https://github.com/matrix-org/synapse/pull/11147#issuecomment-1202207819).
Following that discussion …
=> Update module API "update room membership" method to allow for remote joins

changelog.d/13463.misc, tests/federation/test_complexity.py, tests/federation/transport/test_knocking.py, tests/handlers/test_deactivate_account.py, tests/handlers/test_message.py, tests/handlers/test_room_member.py, tests/http/server/_base.py, tests/rest/client/test_filter.py, tests/rest/client/test_login.py, tests/rest/client/test_redactions.py, tests/rest/client/test_register.py, tests/rest/client/test_report_event.py, tests/rest/client/test_third_party_rules.py, tests/rest/client/utils.py, tests/rest/test_health.py, tests/rest/test_well_known.py, tests/test_server.py, tests/test_terms_auth.py
Follow up: https://github.com/matrix-org/synapse/pull/13298#issuecomment-1205400668
=> Use literals in place of `HTTPStatus` constants in tests

changelog.d/13470.misc, poetry.lock
Include the new `matrix-synapse-ldap3 v0.2.2` in the locked environment. Achieved by running `poetry update matrix-synapse-ldap3`.
=> Update matrix-synapse-ldap3 version in lockfile to v0.2.2.

changelog.d/13481.doc, docs/usage/configuration/config_documentation.md
The [current documentation for the cache](https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#caching) is not as clear as the [old example file](https://github.com/matrix-org/synapse/blob/053ca5f3ca6b913d2c4bfdc7a77cb4657bc86d68/docs/sample_config.yaml#L726).
This is an attempt to make it a little bit clearer.
The headlines does not show code format like: \`caches\` / `caches`
=> Make the configuration for the cache clearer

changelog.d/13471.misc, tests/storage/test_event_push_actions.py
This somewhat "regressed" in #13260.
=> Strengthen tests about deleted old push actions.

changelog.d/13474.misc, synapse/handlers/sync.py, synapse/visibility.py
=> Add some miscellaneous comments around sync

changelog.d/13501.misc, synapse/handlers/room_summary.py
The only client we're aware of that needs updating to not use the unspecified field is Element iOS, but it will take some time for users to update even once a new version has been made available.
Reverts #13365.
=> Revert 'Remove the unspecced  field in the  response. (#13365)' to give more time for clients to update.

changelog.d/13492.doc, docs/usage/configuration/config_documentation.md
A small detail that may otherwise cause sysadmin confusion/run against policy in some enterprise environments.
=> Add note to `redaction_retention_period` documentation mentioning that event purging runs at most every 5m

changelog.d/13472.doc, docs/admin_api/register_api.md
Signed-off-by: James Barton <james@neodon.com>
=> Add openssl example for registration hmac

changelog.d/13515.doc, docker/README.md
Small thing but it doesn't work without it :).
=> Document that the `DOCKER_BUILDKIT=1` flag is needed to build the docker image.

changelog.d/13521.misc, poetry.lock, synapse/app/_base.py, synapse/logging/context.py, synapse/logging/opentracing.py, synapse/storage/database.py, tests/utils.py
=> Update locked versions of mypy and mypy-zope

changelog.d/13485.misc, synapse/storage/databases/main/event_push_actions.py, synapse/storage/databases/main/receipts.py
This builds on #13455 a bit and:
* Adds more comments!
* Renames a variable to be clearer (IMO).
* Fixes an erroneous comment added in #13455 (I got a bit aggressive in my coping and pasting, I think).
It also simplifies the logic slightly in a way which should be a no-op.
=> Clarifications for event push action processing

changelog.d/13499.misc, synapse/federation/federation_server.py, synapse/handlers/federation.py, synapse/rest/client/room.py, synapse/storage/databases/main/event_federation.py, synapse/util/ratelimitutils.py
Instrument `FederationStateIdsServlet` - `/state_ids` so it's easier to follow what's going on in Jaeger when viewing a trace.
```
/_matrix/federation/v1/state_ids/:roomId?event_id=:eventId
```
Part of https://github.com/matrix-org/synapse/issues/13356
Sometimes slow `/state_ids` is just ratelimiter 😴
Before |  After
--- | ---
- Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your …
=> Instrument `FederationStateIdsServlet` - `/state_ids`

changelog.d/13497.doc, docs/message_retention_policies.md, docs/usage/configuration/config_documentation.md
Retention is apparently well-known to cause database corruption, but we don't mention this in the docs. This PR changes that. Fixes  #13475.
=> Add a warning to retention documentation regarding the possibility of database corruption

changelog.d/13522.misc, synapse/push/baserules.py, synapse/push/bulk_push_rule_evaluator.py, synapse/push/clientformat.py, synapse/push/push_rule_evaluator.py, synapse/storage/databases/main/event_push_actions.py, synapse/storage/databases/main/push_rule.py, tests/handlers/test_deactivate_account.py
There are two major changes here:
1. replace using dicts for push rules with proper structs; and
2. stop copying the base rules all over the place.
I didn't split this into two separate PRs, as just doing the first point lead to a lot of effort that would later be removed by the second point. (LMK if I should do that, but the changes are pretty much a rewrite so an iterative approach may not be that helpful).
This improves load times for push rules:
| Version  | Time per user | Time for 1k users | 
| ------------- | ------------- | -- |
| Develop  | 138 µs  | 138ms |
| PR (with custom push rules)   | 2.11 µs  |  2.11ms |
| PR (without custom push rules) | 49.7 ns | 0.05 ms |
This therefore has a large impact on send times for rooms with large numbers of local users in the room.
Reviewable …
=> Make push rules use proper structures.

changelog.d/13514.bugfix, synapse/handlers/message.py, synapse/storage/controllers/state.py, synapse/storage/databases/main/roommember.py
=> Faster room joins: make `/joined_members` block whilst the room is partial stated.

changelog.d/13531.misc, synapse/app/generic_worker.py, synapse/app/homeserver.py
Synapse does not currently support faster room joins on deployments with
workers.
Closes #13527.
=> Refuse to start when `faster_joins` is enabled on a worker deployment

changelog.d/13535.misc, synapse/handlers/federation.py, synapse/handlers/federation_event.py
Time how long it takes us to do backfill processing
The after timing can be influenced by slow `/state_ids` requests when processing the pulled events.
Part of https://github.com/matrix-org/synapse/issues/13356
Mentioned in [internal doc](https://docs.google.com/document/d/1lvUoVfYUiy6UaHB6Rb4HicjaJAU40-APue9Q4vzuW3c/edit#bookmark=id.g611b9kmqk1m)
- Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or …
=> Time how long it takes us to do backfill processing

changelog.d/13544.misc, synapse/util/ratelimitutils.py
Add metrics to track rate limiter queue timing
Related to:
- https://github.com/matrix-org/synapse/pull/13534
- https://github.com/matrix-org/synapse/pull/13541
=> Add metrics to track rate limiter queue timing

changelog.d/13538.doc, docs/templates.md, synapse/config/account_validity.py, synapse/config/emailconfig.py, synapse/config/sso.py
Fixes #13498.
Fix the doc and some warnings that were referring to the nonexistent `custom_templates_directory` setting (instead of `custom_template_directory`).
=> Fix a typo in docs and in some warnings

.github/workflows/tests.yml, changelog.d/13502.misc, scripts-dev/check_pydantic_models.py, scripts-dev/lint.sh
Closes #13336.
This script is a bodge. Until Pydantic 2 introduces a strict mode, this script does the following
1. monkey patches pydantic's machinery with versions that detect non-strict types at model definition time
2. imports all of synapse to detect non-strict types.
By "non-strict" type I mean types which will coerce when they are being ingested into a Pydantic model. For example, Pydantic is perfectly happy to receive the string `"123"` for the field `x: int`, and will interpret it as the integer `x = 123`.
Ideally review would suffice to catch this, but I found myself using non-strict types in #13188 even though I'd already spent some time thinking about how we want to use Pydantic.
I've tried to add comments to describe WTF this script does, but …
=> Reject non-strict types in Pydantic models

changelog.d/13547.misc, synapse/push/baserules.py
Broke by https://github.com/matrix-org/synapse/pull/13522
It looks like we have some rules in the DB with a priority class less
than 0 that don't override the base rules. Before these were just
dropped, but https://github.com/matrix-org/synapse/pull/13522 made that a hard error.
I'm not sure if want the second commit, where we ignore push rules with bad priority classes entirely
=> Fix breaking event sending due to bad push rule

changelog.d/13477.misc, synapse/handlers/sync.py, synapse/storage/controllers/state.py
Use a state filter or accept partial state in a few places where we
request state, to avoid blocking.
To make lazy-loading `/sync`s work, we need to provide the memberships
of event senders, which are not guaranteed to be in the room state.
Instead we dig through auth events for memberships to present to
clients. The auth events of an event are guaranteed to contain a
passable membership event, otherwise the event would have been rejected.
Note that this only covers the common code paths encountered during
testing. There has been no exhaustive checking of all sync code paths.
Fixes #13146.
---
May or may not be easier to review commit by commit.
Complement tests:
- https://github.com/matrix-org/complement/pull/440
- …
=> Avoid blocking lazy-loading `/sync`s during partial joins

changelog.d/13554.misc, synapse/util/ratelimitutils.py
Introduced in #13499.
Likely to be the cause of most of the errors seen in #13552.
=> Fix incorrect juggling of logging contexts in `_PerHostRatelimiter`

changelog.d/13543.misc, tests/handlers/test_room_member.py, tests/module_api/test_api.py, tests/replication/_base.py, tests/replication/tcp/test_handler.py, tests/replication/test_sharded_event_persister.py
This is a small step towards #11728 -- it reduces the number of test cases which use TCP replication (using Redis replication instead for those instances).
This is done by combining the `RedisMultiWorkerStreamTestCase` into `BaseMultiWorkerStreamTestCase`.
=> Reduce the number of tests using TCP replication

changelog.d/13558.misc, tests/events/test_presence_router.py, tests/handlers/test_password_providers.py, tests/handlers/test_register.py, tests/server.py
Always initialises Synapse modules in tests if any have been configured. This saves one needing to do so manually in specific test cases (or be confused why their modules aren't loading until they check other tests, as I was).
=> Register homeserver modules when creating test homeserver

changelog.d/13549.feature, changelog.d/13549.misc, docs/admin_api/user_admin_api.md, synapse/config/experimental.py, synapse/handlers/device.py, synapse/rest/client/devices.py, tests/rest/admin/test_user.py, tests/unittest.py
This PR implements [MSC3852](https://github.com/matrix-org/matrix-spec-proposals/pull/3852), which exposes a `org.matrix.msc3852.last_seen_user_agent` field on the following Client-Server API endpoints:
* [`GET /_matrix/client/v3/devices`](https://spec.matrix.org/v1.3/client-server-api/#get_matrixclientv3devices)
* [`GET /_matrix/client/v3/devices/{deviceId}`](https://spec.matrix.org/v1.3/client-server-api/#get_matrixclientv3devicesdeviceid)
These endpoints only allow you to get information about your own devices; not those of other users.
Because of how the implementation worked out, this PR also adds a `last_seen_user_agent` field to a couple Admin API endpoints:
* [`GET /_synapse/admin/v2/users/<user_id>/devices`](https://matrix-org.github.io/synapse/v1.65/admin_api/user_admin_api.html# …
=> Implement MSC3852: Expose `last_seen_user_agent` to users for their own devices; also expose to Admin API

changelog.d/13551.feature, synapse/api/constants.py, synapse/api/room_versions.py, synapse/events/utils.py, synapse/handlers/federation_event.py
MSC2716v4 room version - remove namespace from MSC2716 event content fields
Complement PR: https://github.com/matrix-org/complement/pull/450
As suggested in
https://github.com/matrix-org/matrix-spec-proposals/pull/2716#discussion_r941444525
(run the …
=> MSC2716v4 room version - remove namespace from MSC2716 event content fields

changelog.d/13574.bugfix, synapse/rest/client/keys.py, synapse/rest/client/sendtodevice.py
Fixes https://github.com/matrix-org/synapse/issues/13567.
=> Remove redundant opentracing spans for `/sendToDevice` and `/keys/upload`

changelog.d/13566.bugfix, synapse/handlers/room_member.py, tests/rest/admin/test_server_notice.py, tests/server_notices/test_resource_limits_server_notices.py
Fixes an edge case, indroduced in #11846.
If `parse_and_validate_mxc_uri` is called in `check_avatar_size_and_mime_type` because `max_avatar_size` or `allowed_avatar_mimetypes` is set, you get an error if `system_mxid_avatar_url` is `None`.
Error
```
File "/usr/lib/python3.10/site-packages/synapse/http/server.py", line 366, in _async_render_wrapper
File "/usr/lib/python3.10/site-packages/synapse/http/server.py", line 572, in _async_render
File "/usr/lib/python3.10/site-packages/synapse/rest/admin/server_notice_servlet.py", line 99, in on_POST
event = await self.server_notices_manager.send_notice(
File …
```
=> Fix that sending server notices fail if avatar is `None`

changelog.d/13573.misc, synapse/handlers/sync.py, synapse/state/__init__.py, synapse/storage/databases/main/roommember.py, synapse/util/caches/descriptors.py
The profile objects are never used and increase cache size significantly.
=> Cache user IDs instead of profile objects

CHANGES.md, changelog.d/13596.removal, docs/upgrade.md, docs/usage/configuration/config_documentation.md, synapse/app/homeserver.py, synapse/config/emailconfig.py, synapse/config/registration.py, synapse/handlers/identity.py, synapse/handlers/ui_auth/checkers.py, synapse/rest/client/account.py, synapse/rest/client/register.py, synapse/rest/synapse/client/password_reset.py, tests/rest/client/test_register.py
Revert "Revert "Drop support for delegating email validation (#13192)" (#13406)"
This reverts commit 98fb610cc043e4f6ba77f78aaecef6b646bf61d6.
History:
- #13192 removed this functionality, aimed at 1.64.
- #13406 reverted this after admins pointed out that we didn't give them any notice of this.
- In #13421 we decided to compromise on 1.66 (giving admins a month to adjust). This was announced in the [1.64 blog post](https://matrix.org/blog/2022/08/03/synapse-1-64-released#delegating-email-verification-is-now-deprecated).
1.66 is being cut, so I am reverting the revert.
=> Drop support for delegating email validation, round 2

synapse/handlers/message.py
This reverts https://github.com/matrix-org/synapse/commit/fae708c0e8c35930f1172322b7c0e9f0b1b3f9a4.
We believe this to be unnecessary---other Synapse deployments do not
have this patch, and we are not aware of bridging problems as a result.
Related:
- https://github.com/matrix-org/matrix-appservice-irc/issues/506
- https://github.com/matrix-org/synapse/issues/4826
=> Hotfixes: revert room members hack

changelog.d/13592.misc, synapse/replication/slave/storage/push_rule.py, synapse/storage/databases/main/account_data.py, synapse/storage/databases/main/push_rule.py
Two separate parts:
1. Don't cache the enabled status of each rule, they get cached as part of the push rule lookup anyway, so there's no benefit from storing that in two caches.
2. Increase the batch size when bulk fetching enabled status (to match that of bulk fetching of push rules).
=> Speed up fetching large numbers of push rules

changelog.d/13602.doc, docs/auth_chain_difference_algorithm.md
=> Write about the chain cover a little.

changelog.d/13583.bugfix, synapse/federation/federation_server.py
Follow-up to #13416; caught by adding tests so that was a good idea :-).
=> Faster Room Joins: fix `/make_knock` blocking indefinitely when the room in question is a partial-stated room.

changelog.d/13606.misc, synapse/handlers/event_auth.py
Use dedicated `get_local_users_in_room` to find local users when calculating `join_authorised_via_users_server` ("the authorising user for joining a restricted room") of a `/make_join` request.
Found while working on https://github.com/matrix-org/synapse/pull/13575#discussion_r953023755 but it's not related.
- Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of …
=> Use dedicated `get_local_users_in_room` to find local users when calculating `join_authorised_via_users_server` of a `/make_join` request

changelog.d/13608.misc, synapse/handlers/events.py, synapse/handlers/message.py, synapse/handlers/room.py, synapse/handlers/room_member.py, synapse/server_notices/server_notices_manager.py, synapse/storage/databases/main/roommember.py, tests/rest/client/test_relations.py
Directly lookup local membership instead of getting all members in a room first (`get_users_in_room` mis-use)
See https://github.com/matrix-org/synapse/pull/13575#discussion_r953023755
```
get_user_in_room_with_profile (not implemented)
get_subset_users_in_room_with_profiles
check_user_in_room
get_local_current_membership_for_user_in_room
check_user_in_room_or_world_readable
is_user_in_rooms
```
---
```
member\S*room
membership\S*room
join\S*room
user\S*room
```
- Start …
=> Directly lookup local membership instead of getting all members in a room first (`get_users_in_room` mis-use)

changelog.d/13605.misc, synapse/handlers/device.py, synapse/handlers/directory.py, synapse/handlers/presence.py, synapse/handlers/typing.py, tests/federation/test_federation_sender.py
Update `get_users_in_room` mis-use to get hosts with dedicated `get_current_hosts_in_room` which has its own performance optimizations for this use case.
See https://github.com/matrix-org/synapse/pull/13575#discussion_r953023755
(run the [linters](https://matrix-org.github.io/synapse/latest/developm …
=> Update `get_users_in_room` mis-use to get hosts with dedicated `get_current_hosts_in_room`

changelog.d/13603.misc, synapse/state/v2.py
in the auth difference calculation logic.
This is "just" a rename, but I hope it makes this slightly easier to follow.
=> Rename `event_map` to `unpersisted_events`

changelog.d/13586.misc, synapse/handlers/federation_event.py
Comment about a better future where we can get the state diff between two events
Split off from https://github.com/matrix-org/synapse/pull/13561
Part of https://github.com/matrix-org/synapse/issues/13356
Mentioned in [internal doc](https://docs.google.com/document/d/1lvUoVfYUiy6UaHB6Rb4HicjaJAU40-APue9Q4vzuW3c/edit#bookmark=id.2tvwz3yhcafh)
- Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or …
=> Comment about a better future where we can get the state diff between two events

.github/workflows/triage-incoming.yml
GitHub appears to be deprecating addProjectNextItem by not allowing it to be used alongside projectV2 to get the project ID, so switching to using addProjectV2ItemById instead.
=> Update automation for incoming issues

changelog.d/13616.bugfix, synapse/_scripts/register_new_matrix_user.py
Fixes https://github.com/matrix-org/synapse/issues/3672: `https://localhost:8448` is virtually never right.
=> register_new_matrix_user: read server url from config

changelog.d/13614.feature, docs/usage/configuration/config_documentation.md, synapse/_scripts/register_new_matrix_user.py, synapse/config/registration.py
A new `registration_shared_secret_path` option. This is kinda handy for k8s deployments and things.
=> Support `registration_shared_secret` in a file

changelog.d/13632.bugfix, synapse/handlers/pagination.py
Fixes #9927 
Signed-off-by: Brad Murray [brad@beeper.com](mailto:brad@beeper.com)
=> Move the execution of the retention purge_jobs to the main worker

changelog.d/13615.feature, docs/usage/configuration/config_documentation.md, synapse/config/_base.py
If things like the signing key file are missing, let's just try to generate them on startup.
Again, this is useful for k8s-like deployments where we just want to generate keys on the first run.
=> Generate missing configuration files at startup

changelog.d/13575.misc, synapse/handlers/federation.py, synapse/handlers/room.py, synapse/storage/controllers/state.py, synapse/storage/databases/main/roommember.py
Optimize how we calculate `likely_domains` during backfill because I've seen this take 17s in production just to `get_current_state` which is used to `get_domains_from_state` (see case [*2. Loading tons of events* in the `/messages` investigation issue](https://github.com/matrix-org/synapse/issues/13356)).
There are 3 ways we currently calculate hosts that are in the room:
1. `get_current_state` -> `get_domains_from_state`
- Used in `backfill` to calculate `likely_domains` and `/timestamp_to_event` because it was cargo-culted from `backfill`
- This one is being eliminated in favor of `get_current_hosts_in_room` in this PR 🕳
1. `get_current_hosts_in_room`
- Used for other federation things like sending read receipts and typing indicators
1. `get_hosts_in_room_at_events`
- Used when pushing …
=> Optimize how we calculate `likely_domains` during backfill

changelog.d/13546.bugfix, synapse/handlers/room_member.py, tests/handlers/test_room_member.py, tests/storage/test_roommember.py
https://github.com/matrix-org/synapse/issues/13517#issuecomment-1216133811:
> I suspect that after the last member leaves the room, the background update `_background_remove_left_rooms` is deleting rows related to this room from the table `current_state_events`.
> the return value for `get_current_state_events` is `None`
Fixes: #13517
~~Blocked by: #13503
for using ` is_locally_forgotten_room` in tests~~
=> Fix that user cannot `/forget` rooms after the last member has left

changelog.d/13649.bugfix, synapse/server.py, synapse/util/ratelimitutils.py
Fix rate limit gauge metrics registering twice and misreporting by registering once and adding a label to differentiate the instances (although we only track the federation servlets at the moment). The gauge metrics were originally added in https://github.com/matrix-org/synapse/pull/13541
`FederationRateLimiter` is being instantiated twice in Synapse:
1. [`UsernameAvailabilityRestServlet`](https://github.com/matrix-org/synapse/blob/c4e29b6908ac8ae57b5e9a3e7662ad638b61e94a/synapse/rest/client/register.py#L300-L321) which uses it to rate limit people by IP
1. For the [Federation servlets](https://github.com/matrix-org/synapse/blob/c4e29b6908ac8ae57b5e9a3e7662ad638b61e94a/synapse/server.py#L757-L760) which `FederationRateLimiter` was made for
Fix …
=> Fix rate limit metrics registering twice and misreporting

changelog.d/13634.feature, synapse/storage/databases/main/event_push_actions.py
This switches from using `execute_batch` to `execute_values`, from some testing against a large database with a room of 3870 local users this reduces the time to insert into the `event_push_actions_staging` from ~0.2s to <0.1s in most cases. (This wasn't super scientific, but it definitely seemed to help.)
=> Speed up inserting `event_push_actions_staging`

changelog.d/13657.bugfix, synapse/rest/media/v1/preview_url_resource.py
See the excellent write-up in #13637 of why this is safe.
Without this Synapse may not expire URL cache entries for a long time when there are large background updates (e.g. things that crawl `events`).
Fixes #13637.
=> Do not wait for background updates to complete do expire URL cache.

changelog.d/13660.bugfix, synapse/rest/media/v1/_base.py
We incorrectly didn't use the returned `Responder` if the client had
disconnected, which meant that the resource used by the Responder
wasn't correctly released.
In particular, this exhausted the thread pools so that *all* requests
timed out.
The change is simply to move the `request._disconnected` into the context manager
Broke in #8465
=> Fix bug where we wedge media plugins if clients disconnect early

changelog.d/13645.doc, docs/systemd-with-workers/workers/generic_worker.yaml, docs/workers.md
This has been the same as a generic_worker since #6964, so let's get rid of it.
Fixes #3717
Supercedes #13451.
=> Remove documentation of legacy `frontend_proxy` worker app

changelog.d/13658.bugfix, synapse/storage/databases/main/events_worker.py
Give the correct next event when the message timestamps are the same.
Discovered while working on https://github.com/matrix-org/synapse/pull/13589 and I had all the messages at the same timestamp in the tests.
Part of https://github.com/matrix-org/matrix-spec-proposals/pull/3030
Complement tests: https://github.com/matrix-org/complement/pull/457
- Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or …
=> Give the correct next event when the message timestamps are the same - MSC3030

CHANGES.md
Per the request at https://github.com/matrix-org/synapse/pull/13647#pullrequestreview-1090714217.
=> Remind people that direct TCP replication is deprecated.

debian/changelog, debian/matrix-synapse-py3.postinst
This is another stab at fixing the `dpkg-statoverride` that generates warnings on (first) install of the Debian package. Looking at the bug report and the first PR to fix this, this was postponed because then-supported Ubuntu versions didn't have a sufficiently new `dpkg`, but I think this should no longer be the case (please correct me if I'm wrong). 
Fixes: #8391 …
=> Change dpkg-statoverride to use --force-statoverride-add

changelog.d/13662.misc, synapse/federation/transport/server/_base.py, synapse/http/server.py, synapse/replication/http/_base.py, synapse/rest/client/room.py, synapse/util/cancellation.py, tests/federation/transport/server/test__base.py, tests/http/test_servlet.py, tests/replication/http/test__base.py, tests/test_server.py
This allows general functions to be audited and then marked with the annotation to reduce work whilst auditing more functions.
Previously, this annotation was only permitted on servlet methods.
Should be fairly commit-by-commit to review.
=> Generalise the `@cancellable` annotation so it can be used on functions other than just servlet methods.

changelog.d/13653.removal, synapse/api/constants.py, synapse/config/experimental.py, synapse/handlers/receipts.py, synapse/replication/tcp/client.py, synapse/rest/client/notifications.py, synapse/rest/client/read_marker.py, synapse/rest/client/receipts.py, synapse/rest/client/versions.py, synapse/storage/databases/main/event_push_actions.py, tests/handlers/test_receipts.py, tests/rest/client/test_sync.py, tests/storage/test_receipts.py
Fixes https://github.com/matrix-org/synapse/issues/13468
<hr>
=> Remove support for unstable private read receipts

.github/workflows/tests.yml, changelog.d/13688.docker, docker/Dockerfile
Seems like a sensible thing, but also makes my life slightly easier in the rust PR.
=> Bump docker image to use stable poetry version

changelog.d/13683.bugfix, synapse/rest/key/v2/remote_key_resource.py
I want to set up a test server which has lots of room data in it, but is part of a closed federation. It needs to return the signing keys to make that work.
=> Return keys for unwhitelisted servers from `/_matrix/key/v2/query`

changelog.d/13697.misc, contrib/grafana/synapse.json
I'm doing this to reunify matrix.org's with the one in contrib/, so that I can start making a lot of fixes to the used metric names as part of #11106.
Blocks #11106.
=> Update the Grafana dashboard that is included with Synapse in the `contrib` directory.

changelog.d/13692.removal, synapse/storage/schema/main/delta/72/05remove_unstable_private_read_receipts.sql
Follow-up to #13653, we need to somehow still handle unstable private read receipts that are in the database so that we don't leak them to other users.
As they're unstable it makes more sense to either:
1. Drop them completely.
2. Migrate them to the stable prefix.
I chose to just drop them since it is an unstable feature, but could be convinced to migrate them.
=> Add a schema delta to drop unstable private read receipts.

changelog.d/13665.doc, docs/usage/configuration/config_documentation.md
=> Fix two typos with colon in headlines

.github/workflows/tests.yml, changelog.d/13698.misc
To reduce the number of CI jobs we have.
=> Only run trial CI on all python versions on non-PRs

changelog.d/13678.doc, docs/metrics-howto.md
*Spawning from enabling metrics locally to test https://github.com/matrix-org/synapse/pull/13649*
---
Update docs to make enabling metrics more clear. It's really easy to miss the `enable_metrics: True` step with the previous langauge.
(run the …
=> Update docs to make enabling metrics more clear

changelog.d/13701.doc, docs/development/database_schema.md
Clarify `(room_id, event_id)` global uniqueness
Summarized from @richvdh's reply at https://github.com/matrix-org/synapse/pull/13589#discussion_r961116999
=> Clarify `(room_id, event_id)` global uniqueness

changelog.d/13712.misc, synapse/api/filtering.py
=> Fix typechecking with latest `types-jsonschema`

changelog.d/13714.misc, contrib/grafana/synapse.json, synapse/metrics/_legacy_exposition.py, synapse/util/caches/__init__.py
Part of #11106: since #13540 it is possible to disable legacy metric names.
This PR updates the provided Grafana dashboard so that it doesn't use those legacy metric names. This removes one of the blockers for turning off legacy metric names in reality.
To come up with this PR, I diffed the list of metrics with and without legacy metric names enabled and fed it into a script which finds whole-word occurrences of those removed metrics in the dashboard JSON file.
TO DO:
=> Update Grafana dashboard to not use legacy metric names.

changelog.d/13724.misc, synapse/api/filtering.py
Closes #13721. In #13708 I forgot to actually check my changes against the latest stubs, whoops.
```
$ mypy
synapse/api/filtering.py:142: error: Value of type variable "_F" of function cannot be "Callable[[str], bool]"  [type-var]
synapse/api/filtering.py:147: error: Value of type variable "_F" of function cannot be "Callable[[str], bool]"  [type-var]
Found 2 errors in 1 file (checked 728 source files)
$ pip install --upgrade types-jsonschema
Requirement already satisfied: types-jsonschema in /home/dmr/.cache/pypoetry/virtualenvs/matrix-synapse-RhMlrixz-py3.10/lib/python3.10/site-packages (4.4.6)
Collecting types-jsonschema
Downloading types_jsonschema-4.15.1-py3-none-any.whl (8.7 kB)
Installing collected packages: types-jsonschema
Attempting uninstall: types-jsonschema
Found existing …
```
=> Actually fix typechecking with latest types-jsonschema

changelog.d/13706.misc, synapse/api/room_versions.py, synapse/event_auth.py, synapse/events/__init__.py, synapse/events/builder.py, synapse/events/validator.py, synapse/federation/federation_base.py, synapse/federation/federation_client.py, synapse/storage/databases/main/event_federation.py, synapse/storage/databases/main/events_worker.py, tests/storage/databases/main/test_events_worker.py, tests/storage/test_event_federation.py, tests/test_event_auth.py
I found this confusing and apparently that's common, so I suggest we rename them to sound a bit more related to the room versions they come from.
I understand that room versions aren't necessarily chronologically-ordered and that this pattern may not hold up forever, but I think that's a problem for later. Right now, this convention seems sensible and it reduces the mental load for me.
=> Rename the `EventFormatVersions` enum values so that they line up with room version numbers.

changelog.d/13680.feature, synapse/api/auth.py, synapse/handlers/device.py, synapse/handlers/e2e_keys.py, synapse/rest/client/keys.py, synapse/storage/controllers/state.py, synapse/storage/databases/main/devices.py, synapse/storage/databases/main/end_to_end_keys.py, synapse/storage/databases/main/event_federation.py, synapse/storage/databases/main/events_worker.py, synapse/storage/databases/main/roommember.py, synapse/storage/databases/main/state.py, synapse/storage/databases/main/stream.py, synapse/storage/databases/state/store.py, synapse/storage/util/partial_state_events_tracker.py, synapse/types.py, tests/http/server/_base.py, tests/rest/client/test_keys.py
Fixes #12890.
- A list of primitives that are believed to cancellation-safe is available at: https://github.com/matrix-org/synapse/issues/3528#issuecomment-1083481216.
- An example for cancellation safety testing is available at: https://github.com/matrix-org/synapse/pull/12674/files#diff-42dd577b913384e2a37797a714882b5e4da6ef17a85e9c9cbbc1eb87004c48f8R663.
(Note that the testing doesn't catch absolutely everything.)
=> Cancel the processing of key query requests when they time out.

changelog.d/13728.doc, docs/deprecation_policy.md
Rabbithole:  #13715 -> #6394-> https://github.com/matrix-org/synapse/issues/6311#issuecomment-553835368 -> https://github.com/matrix-org/synapse/issues/12983#issuecomment-1234825826
=> Define SQLite compat policy

.github/workflows/tests.yml, changelog.d/13735.misc
Thanks to @jplatte for the suggestion
=> Add some rust caching to CI

.github/workflows/latest_deps.yml, .github/workflows/twisted_trunk.yml, changelog.d/13734.misc
Hopefully fixes #13731 and #13732.
Broke by #12595
=> Fix latest deps CI

changelog.d/13730.misc, synapse/storage/databases/main/state.py
Instrument `get_metadata_for_events` for tracing
When backfilling, `_get_state_ids_after_missing_prev_event` calls [`get_metadata_for_events`](https://github.com/matrix-org/synapse/blob/26bc26586b4b95d63ce7e453e9312469843f796e/synapse/handlers/federation_event.py#L1133). For `#matrix:matrix.org`, it's called with 77k `state_events` which means 77 calls to the database and takes 28 seconds.
- Feel free to credit yourself, by adding a sentence …
=> Instrument `get_metadata_for_events` for tracing

changelog.d/13738.bugfix, synapse/config/key.py
Fixes #13737: we just filter out empty lines.
But it also seemed prudent to ensure we don't accept empty files altogether.
=> Fix a bug where Synapse fails to start if a signing key file contains an empty line.

.github/workflows/latest_deps.yml, changelog.d/13743.misc
Take 2, hopefully fixes https://github.com/matrix-org/synapse/issues/13739
=> Fix latest deps

changelog.d/13746.bugfix, synapse/server.py, tests/test_types.py
Previously, `is_mine_id` would raise an exception when passed an ID with
no colons. Return `False` instead.
Fixes #13040.
---
This fix is helpful for #13749, which uses `is_mine_id` in the event persistence path, where we don't want to error out due to invalid user IDs.
=> Fix error in `is_mine_id` when encountering a malformed ID

changelog.d/13748.misc, synapse/storage/databases/main/roommember.py
Handle malformed user IDs with no colons in `get_current_hosts_in_room`.
It's not currently possible for a malformed user ID to join a room, so
this error would never be hit.
=> Avoid raising errors due to malformed IDs in `get_current_hosts_in_room`

changelog.d/13756.misc, contrib/prometheus/synapse-v2.rules
A few of these rules were unused. Some didn't even have the right metric names in the expression, so weren't recording anything.
I've removed those.
Others are just used in the Prometheus console (which I'm not aware of anyone using, but I'll ask separately). Some are used in the included Grafana dashboard.
=> Remove unused Prometheus recording rules from `synapse-v2.rules` and add comments describing where the rest are used.

changelog.d/13754.misc, synapse/handlers/sync.py
---
The idea here is to make it easier to reason about the sync code.
By promising not to modify collections via type hints, it becomes easier to figure out how these sets are calculated, since we can be reasonably sure that there aren't any hidden bits of code that apply corrections to them in the 2000+ lines of sync code.
=> Re-type hint some collections in `/sync` code as read-only

changelog.d/13760.removal, synapse/storage/database.py, synapse/storage/databases/main/lock.py, synapse/storage/databases/main/stats.py, synapse/storage/databases/main/transactions.py, synapse/storage/engines/_base.py, synapse/storage/engines/postgres.py, synapse/storage/engines/sqlite.py, tests/storage/test_base.py
As per https://github.com/matrix-org/synapse/issues/12983#issuecomment-1234825826: bump the min version, then remove `can_native_upsert`.
=> Require SQLite >= 3.27.0

.github/workflows/tests.yml, changelog.d/13763.misc, rust/src/lib.rs
We only run the CI when the rust directory has changed.
=> Add rust to CI

changelog.d/13752.misc, synapse/storage/databases/main/receipts.py
Instead of a delete + insert. Essentially ports #7607 to `receipts_graph` (from `receipts_linearized`).
=> Use upsert for receipts_graph.

changelog.d/13761.misc, synapse/api/auth.py, synapse/logging/opentracing.py
Tag trace with instance name. We tag the Synapse instance name so that it's an easy jumping off point into the logs. Can also be used to filter for an instance that is under load.
As suggested by @clokep and @reivilibre in,
- https://github.com/matrix-org/synapse/pull/13729#discussion_r964719258
- https://github.com/matrix-org/synapse/pull/13729#discussion_r964733578 …
=> Tag trace with instance name

changelog.d/13765.misc, synapse/push/push_tools.py
Most of the time this function is heavily cached, but when that isn't the case fetching the counts room by room slows down push delivery on users with many (thousands) of rooms.
Signed off by Nick @ Beeper.
=> Concurrently collect room unread counts for push badges

changelog.d/13745.misc, synapse/storage/databases/main/roommember.py, synapse/storage/schema/main/delta/72/07force_update_current_state_events_membership.py
Bit of cleanup; originally added [back in 2019](https://github.com/matrix-org/synapse/pull/5706) with schema compat changing since, so should be safe to assume this is complete.
Contributed by Nick @ Beeper (@fizzadar).
=> Remove check current state membership up to date

changelog.d/13703.misc, synapse/_scripts/synapse_port_db.py, synapse/storage/databases/main/receipts.py, synapse/storage/schema/main/delta/72/05receipts_event_stream_ordering.sql
More work on #13448. Adds a new column `event_stream_ordering` to the `receipts_linearized` table specifically to remove the relatively expensive join on events when processing push actions (https://github.com/beeper/synapse/commit/26fd50f2b030f1908a1259c6cd9bc264e42077ba).
One question here is when an event is `None` - as far as I can tell this should only ever happen if a client sends in a bad event ID with a receipt. In all other cases the event should exist - if the client knows about an event ID the server must have provided it.
Alternative approach to this problem: reject receipts with invalid event IDs (might need spec update?). Don't think that's within scope here, but probably worth considering unless I've missed something.
(run the …
=> Add receipts event stream ordering

.github/workflows/tests.yml, changelog.d/13784.misc
This removes edges from some lint jobs to `tests-done`.
Before: https://github.com/matrix-org/synapse/actions/runs/3039314342
After: https://github.com/matrix-org/synapse/actions/runs/3039998218
Should have no effect (it's removing an edge that's implied by transitivity). Makes me feel less neurotic though.
=> Simplify CI tests DAG

changelog.d/13770.misc, scripts-dev/make_full_schema.sh, synapse/storage/schema/state/delta/30/state_stream.sql
These are some opinionated updates to the schema dump script. Should be commit-by-commit reviewable.
In particular:
- generate separate schema and data files. In think this makes it a bit easier to understand wtf is going on.
- don't use portdb. Sorry, I don't trust it (and it _definitely_ missed out any postgres-specific migrations).
Not done (hard?)
- split out `common`, `main` and `state`
=> Updates to the schema dump script

changelog.d/13789.bugfix, synapse/federation/transport/server/federation.py
I checked the logs on matrix.org and no recent requests hit this pattern.
It seems like this question has been around a long time without a good reason, so I propose we remove it... :)
=> Fix a long-standing spec compliance bug where Synapse would accept a trailing slash on the end of `/get_missing_events` federation requests.

changelog.d/13802.misc, synapse/storage/background_updates.py, synapse/storage/databases/main/event_push_actions.py, synapse/storage/schema/main/delta/72/09partial_indices.sql.sqlite
According to #13760 we now require SQLite > 3.27, so we can safely use partial indices on SQLite which (according to this comment) have been supported since 3.8.
This is blocking #13782 (where we need to upsert on a partial index).
=> Use partial indices on SQLIte.

changelog.d/13162.misc, poetry.lock, pyproject.toml, synapse/rest/media/v1/media_repository.py, synapse/rest/media/v1/upload_resource.py, tests/rest/media/test_media_retention.py
This PR bumps the minimum version of [matrix-python-common](https://github.com/matrix-org/matrix-python-common) from v1.2.1 to v1.3.0 to [include a MXCUri class](https://github.com/matrix-org/matrix-python-common/pull/29). This class provides a couple benefits:
* Consolidating the logic for parsing a MXC uri to/from a string.
* Allow us to pass around a single object (`MXCUri`) versus both a server name and media ID.
These both helped greatly simplify `MediaRetentionTestCase`.
=> Add a `MXCUri` class to make working with mxc uri's easier.

changelog.d/13822.misc, synapse/storage/background_updates.py, synapse/storage/database.py
This is required for #13782, but I'm pulling it out into a separate pull request. You can see this in-use:
https://github.com/matrix-org/synapse/blob/f9f3f777de39a6aa9178a423b299993bb20edbe8/synapse/storage/databases/main/receipts.py#L707-L732
I decided to just take a raw `where_clause` (as a string) instead of key-value pairs to match `register_background_index_update` (and to simplify the implementation).
=> Support providing an index predicate for upserts.

changelog.d/13785.doc, docs/development/dependencies.md
Document common fix of Poetry problems by removing `matrix_synapse.egg-info/`
Mentioned at https://matrix.to/#/!vcyiEtMVHIhWXcJAfl:sw1v.org/$aKy_IjrKwb70aTVZWeW_6zt0k7OIZ1YkyZpkP9uiRaM?via=matrix.org&via=element.io&via=beeper.com and many other places.
(run the …
=> Document common fix of Poetry problems by removing egg-info

changelog.d/13794.doc, docs/usage/administration/request_log.md
```
synapse/http/site.py
448:            requester = f"{authenticated_entity}|{requester}"
```
=> Update request log format documentation to mention the format used when the authenticated user is controlling another user.

changelog.d/13810.feature, docs/admin_api/user_admin_api.md, synapse/rest/admin/__init__.py, synapse/rest/admin/users.py, tests/rest/admin/test_user.py
This adds an endpoint like this:
```http
GET /_synapse/admin/v1/auth_providers/oidc/users/123
{
"user_id": "@hello:example.com"
}
```
This is useful for reacting to events from the IDP, like deactivating an account when it gets deactivated on the IDP side
(run the …
=> Add an admin API endpoint to find a user based on its external ID in an auth provider.

changelog.d/13819.misc, docker/complement/Dockerfile
Doing so in the base postgres image doesn't work with buildah because changes in a declared VOLUME in the Dockerfile is supposed to be discarded, cf https://docs.docker.com/engine/reference/builder/#volume
=> complement: init postgres DB directly inside the target image

changelog.d/13826.bugfix, synapse/handlers/e2e_keys.py
The error message introduced in #13749 has turned out to be very spammy.
Remove it for now.
At some point we'll want to create a background update to mark the appropriate device lists as unsubscribed (see https://github.com/matrix-org/synapse/issues/13651#issuecomment-1249234310).
=> Remove error spam when users query the keys of departed remote users

.github/workflows/tests.yml, changelog.d/13827.misc
Very minor. These aren't on the critical path (that's the linting job) but it might help ease runner contention.
=> Minor speedups to CI linting

.dockerignore, changelog.d/13811.misc, docker/Dockerfile
Ignore the .so file when sending Docker context to the build process.
Also enforce `bullseye` tag for the base Python images so we are sure to not have some discrepancy regarding glibc version among others.
Fix #13803.
=> Fix Docker build when Rust .so has been build locally first

changelog.d/13825.bugfix, synapse/storage/databases/main/purge_events.py, synapse/storage/schema/__init__.py, synapse/storage/schema/main/delta/73/02room_id_indexes_for_purging.sql
Add support to purge rows from tables I've added in the past like the MSC2716 related ones and the [recent `event_failed_pull_attempts`](https://github.com/matrix-org/synapse/pull/13589) when purging a room.
(run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guid …
=> Add support to purge rows from MSC2716 and other tables when purging a room

.github/workflows/tests.yml, changelog.d/13857.misc, rust/Cargo.toml
To make life a bit easier for packagers. I don't think there are any particularly useful features for us between 1.58 and 1.61.
=> Lower minimum rustc version to 1.58.1

changelog.d/13836.doc, docs/sso_mapping_providers.md, synapse/handlers/sso.py
Changed `displayname` to `display_name`.
See [/synapse/handlers/sso.py L130](https://github.com/matrix-org/synapse/blob/fe1daad67237c2154a3d8d8cdf6c603f0d33682e/synapse/handlers/sso.py#L130).
=> Correct documentation for map_user_attributes of OpenID Mapping Providers

changelog.d/13831.feature, changelog.d/13831.misc, synapse/push/__init__.py, synapse/push/pusherpool.py, synapse/rest/client/pusher.py, synapse/storage/databases/main/pusher.py, synapse/storage/schema/main/delta/73/03pusher_device_id.sql, tests/push/test_http.py
Second half of the MSC3881 implementation. Depends on #13799.
=> Track device IDs for pushers

changelog.d/13860.feature, synapse/rest/client/versions.py
Forgot this bit in #13799. Not yet part of the MSC (at the time of writing this) but should be added shortly.
=> Add version flag for MSC3881

changelog.d/13832.feature, synapse/rest/client/account.py
=> Last batch of Pydantic for synapse/rest/client/account.py

changelog.d/13866.bugfix, pyproject.toml
=> Fix sdist to include rust build script

changelog.d/13870.doc, docs/admin_api/register_api.md
See https://matrix-org.github.io/synapse/latest/admin_api/register_api.html, the cross-link to `registration_shared_secret` is missing a `/usage` in it.
=> Fix the cross-link from register admin API to config docs.

changelog.d/13876.misc, contrib/prometheus/synapse-v2.rules
Add some louder comment 'blocks' so it's exceedingly clear which rules you might care about.
Fixes #13758 (some / most people probably don't care about Prometheus Console, but at least one does).
=> Add comments to the Prometheus recording rules to make it clear which set of rules you need for Grafana or Prometheus Console.

changelog.d/13823.misc, synapse/api/errors.py, synapse/config/experimental.py, synapse/federation/federation_server.py, synapse/handlers/event_auth.py, synapse/handlers/federation.py, synapse/handlers/federation_event.py, synapse/handlers/receipts.py, synapse/handlers/room_summary.py, synapse/handlers/typing.py, tests/handlers/test_typing.py
Fixes #13288.
Instead of trying to perform authorisation checks on the requesting server, we tell them that we're not able to authorise them right now. (This uses a small appendix to MSC3706 to define an error code.)
The requesting server should already have failover logic to query another resident server, so this shouldn't harm them.
The main concern comes about when sending an event (#12997), where we may need to answer some queries so that the server receiving our event can accept it. This PR leaves that as future work for #12997...
An alternative suggestion is to accept servers that are on the list given to us from the server we `/make_join`ed against (and possibly keep this up to date), but this seems error-prone and it's not as though we can't do that at a later date if we reason …
=> Faster Remote Room Joins: tell remote homeservers that we are unable to authorise them if they query a room which has partial state on our server.

changelog.d/13874.misc, synapse/handlers/device.py, synapse/storage/controllers/state.py, synapse/storage/databases/main/room.py
Use the provided list of servers in the room from the `/send_join`
response, since we will not know which users are in the room.  This
isn't sufficient to ensure that all remote servers receive the right
device list updates, since the `/send_join` response may be inaccurate
or we may calculate the membership state of new users in the room
incorrectly.
---
> This isn't sufficient to ensure that all remote servers receive the right device list updates, since the `/send_join` response may be inaccurate or we may calculate the membership state of new users in the room incorrectly.
To handle these cases, we'll need to implement the first item in the plan laid out in https://github.com/matrix-org/synapse/issues/12993#issuecomment-1253785129
=> Send device list updates out to servers in partially joined rooms

changelog.d/13782.feature, synapse/config/experimental.py, synapse/handlers/receipts.py, synapse/replication/tcp/client.py, synapse/replication/tcp/streams/_base.py, synapse/rest/client/read_marker.py, synapse/rest/client/receipts.py, synapse/rest/client/versions.py, synapse/storage/database.py, synapse/storage/databases/main/receipts.py, synapse/types.py, tests/federation/test_federation_sender.py, tests/handlers/test_appservice.py, tests/replication/slave/storage/test_events.py, tests/replication/tcp/streams/test_receipts.py, tests/storage/test_event_push_actions.py, tests/storage/test_receipts.py
Track thread IDs for receipts, partially implementing MSC3771.
This updates the endpoints, replication, etc. to support a `thread_id` parameter on receipts. It then stores it into the database.
Note that #13824 is fairly close related to this, but I left it separate. I can include it here if a reviewer would like, but was trying to minimize the size of PRs.
Part of #12550.
This is essentially a rebase of #13202 on top of #13776.
=> Store thread IDs on receipts (implement MSC3771) (redo)

Cargo.lock, changelog.d/13889.misc
Since it is out of date. I ran `cargo check`.
This was missed in #13768, I think.
=> Update Cargo.lock file.

changelog.d/13855.bugfix, synapse/http/proxyagent.py
Fix access token leak to logs from proxyagent. This can happen specifically with an application service `/transactions/10722?access_token=leaked` request
Fix https://github.com/matrix-org/synapse/issues/13010
---
Saw an example leak in https://github.com/matrix-org/synapse/issues/13423#issuecomment-1205348482
```
2022-08-04 14:47:57,925 - synapse.http.client - 401 - DEBUG - as-sender-signal-1 - Sending request PUT http://localhost:29328/transactions/10722?access_token=<redacted>
2022-08-04 14:47:57,926 - synapse.http.proxyagent - 223 - DEBUG - as-sender-signal-1 - Requesting b'http://localhost:29328/transactions/10722?access_token=leaked' via <HostnameEndpoint localhost:29328>
```
- Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving …
=> Fix access token leak to logs from proxyagent

changelog.d/13888.misc, synapse/handlers/device.py, synapse/storage/controllers/state.py
Part of the work for #12993.
Once #12993 is fully resolved, we expect `/keys/changes` to behave
sensibly when joined to a room with partial state.
=> Faster room joins: Avoid blocking `/keys/changes`

changelog.d/13905.misc, poetry.lock, synapse/http/server.py
Fixes #13896. Follow-up to matrix-org/python-canonicaljson#52.
=> Fix mypy errors with latest canonicaljson

changelog.d/13796.misc, synapse/storage/_base.py, synapse/storage/databases/main/cache.py, synapse/storage/databases/main/events.py
Been looking at caching a bunch recently (to externalise to Redis), this felt like a good cleanup and deduplication of code. Will invalidate slightly more than before, but now means workers and the persister are consistent and the code is much simpler.
Contributed by Nick @Beeper (@Fizzadar).
=> Simplify cache invalidation after event persist txn

changelog.d/13830.bugfix, synapse/handlers/typing.py, tests/handlers/test_typing.py
This is also using the partial state approximation if needed so we do not block here during a fast join.
Fix at least partially #13684.
Also fix #13869.
=> typing: check origin server of typing event against room's servers

changelog.d/13911.doc, debian/changelog, debian/hash_password.ronn
The default number of bcrypt rounds were incorrect:
https://github.com/matrix-org/synapse/blob/f16ec055cc235eed1ae02f7cede99c366fedca5e/synapse/_scripts/hash_password.py#L26-L27
I don't claim that this PR prevents this mistake happening again in the future when we update the default for bcrypt rounds once more. Rather, it's just a quick drive-by fix.
=> Update the manpage documentation for the hash_password script

changelog.d/13893.feature, synapse/storage/databases/main/event_push_actions.py, tests/storage/test_event_push_actions.py
Adds a docstring, reduces a little duplicated code, and adds some better tests for `get_unread_push_actions_for_user_in_range_http` and `get_unread_push_actions_for_user_in_range_email`.
Spun some of the commits out of #13878 since they're unrelated to the changes I'm making.
=> Improve tests for get_unread_push_actions_for_user_in_range

changelog.d/13914.misc, synapse/app/complement_fork_starter.py
This should mean that logs from worker processes are flushed before shutdown.
When a test completes, Complement stops the docker container, which means that synapse will receive a SIGTERM. Currently, the `complement_fork_starter` exits immediately (without notifying the worker processes), which means that the workers never get a chance to flush their logs before the whole container is vaped. We can fix this by propagating the SIGTERM to the children.
=> Complement image: propagate SIGTERM to all workers

changelog.d/13872.bugfix, synapse/handlers/sync.py
During a `lazy_load_members` `/sync`, we look through auth events in
rooms with partial state to find prior membership events. When such a
membership is not found, an error is logged.
Since the first join event for a user never has a prior membership event
to cite, the error would always be logged when one appeared in the room
timeline.
Avoid logging errors for such events.
Introduced in #13477.
=> Faster room joins: Fix spurious error when joining a room

changelog.d/13885.misc, synapse/app/admin_cmd.py, synapse/storage/controllers/persist_events.py, synapse/storage/databases/main/__init__.py, synapse/storage/databases/main/devices.py, synapse/storage/databases/main/events.py, synapse/storage/databases/main/roommember.py
This is bullet two in https://github.com/matrix-org/synapse/issues/12993#issuecomment-1253785129
=> Handle the case of remote users leaving a partial join room for device lists

changelog.d/13867.misc, docker/complement/Dockerfile
Follow-up to https://github.com/matrix-org/synapse/pull/13819
=> Dockerfile for tests: align comments with current behavior

docs/upgrade.md
Needs merging to master and develop afterwards.
=> Update upgrade notes

changelog.d/13922.bugfix, synapse/federation/sender/per_destination_queue.py
Otherwise device list changes for large accounts can temporarily delay to-device messages.
=> Prioritize outbound to-device over device list updates

changelog.d/13920.feature, synapse/rest/client/relations.py, tests/rest/client/test_relations.py
Part of #13919, this has now passed FCP so we can support the stable `dir` parameter.
=> Support the stable dir parameter for /relations.

changelog.d/13892.feature, synapse/handlers/federation.py, synapse/storage/databases/main/room.py, synapse/storage/schema/main/delta/73/04partial_join_details.sql
First half of #13891. A contribution to #12993.
This information will let us work out which servers to send device list updates to once we have fully joined the room. Doing so will ensure that we correctly fulfil our obligation to notify other HSes of our users' device list changes.
=> Add new columns tracking when we partial-joined

changelog.d/13487.misc, synapse/handlers/message.py, synapse/handlers/room.py, synapse/state/__init__.py, tests/rest/client/test_rooms.py
This PR begins work on batching up events during the creation of a room. The PR splits out the creation and sending/persisting of the events. The first three events in the creation of the room-creating the room, joining the creator to the room, and the power levels event are sent sequentially, while the subsequent events are created and collected to be sent at the end of the function. This is currently done by appending them to a list and then iterating over the list to send, the next step (after this PR) would be to send and persist the collected events as a batch.
=> Prepatory work for batching events to send

changelog.d/13800.misc, synapse/handlers/message.py, synapse/handlers/room.py, synapse/handlers/room_batch.py, synapse/handlers/room_member.py, synapse/replication/http/__init__.py, synapse/replication/http/send_event.py, synapse/replication/http/send_events.py, tests/handlers/test_message.py, tests/handlers/test_register.py, tests/storage/test_event_chain.py, tests/unittest.py
This pr builds on #13487, which gathers up the initial room creation events to be persisted as a batch. This pr adds functionality to actual persist those events to the DB in a batch.
=> Persist CreateRoom events to DB in a batch

changelog.d/13928.doc, docs/development/contributing_guide.md
This PR updates the contributing guide with the instruction for running unit tests in parallel.
=> Add instruction for running unit tests in parallel

changelog.d/13913.misc, synapse/handlers/device.py, synapse/handlers/federation.py, synapse/storage/databases/main/devices.py, synapse/storage/databases/main/room.py, synapse/storage/schema/main/delta/73/04pending_device_list_updates.sql
c.f. https://github.com/matrix-org/synapse/issues/12993#issuecomment-1253785129, point 3
This stores all device list updates that we receive while partial joins are ongoing, and processes them once we have the full state.
Note: We don't actually process the device lists in the same ways as if we weren't partially joined. Instead of updating the device list remote cache, we simply notify local users that a change in the remote user's devices has happened. I think this is safe as if the local user requests the keys for the remote user and we don't have them we'll simply fetch them as normal.
**<del>TODO:</del>**
=> Handle remote device list updates during partial join

changelog.d/13930.doc, debian/hash_password.1
Missed in https://github.com/matrix-org/synapse/pull/13911, uses the same changelog entry.
Yes I'm still not happy about how manual this is, but doing a quick fix for now given we rarely update this value anyway.
=> Correct default number of bcrypt hash rounds in .1 man page

changelog.d/13931.doc, docs/usage/configuration/config_documentation.md
Updates the documentation to clarify that you can auto-join new users to Spaces using the `auto_join_rooms` option, as well as a couple updates to related documentation.
=> Document that the 'auto_join_rooms' option works with Spaces

changelog.d/13933.feature, synapse/storage/databases/main/event_push_actions.py
I don't think there's any benefit to returning this column (maybe an old version of Postgres/SQLite made you return it if you ordered by it or something, but I'd be surprised by that?)
Let's get some CI going...
=> Avoid returning an unused column.

changelog.d/13933.feature, synapse/storage/databases/main/event_push_actions.py
Reverts matrix-org/synapse#13933.
Turns out this *is* used, but in a confusing spot further down in the code:
https://github.com/matrix-org/synapse/blob/7766bd5b354cd4ea1a33351ba320e54a14d3aeac/synapse/storage/databases/main/event_push_actions.py#L1124-L1127
=> Revert "Avoid returning an unused column."

changelog.d/13932.feature, docs/upgrade.md
Missing from #13782, as discussed in #synapse-dev earlier today.
This is pretty much copied from the v1.64 notes:
https://matrix-org.github.io/synapse/latest/upgrade.html#changes-to-the-event-replication-streams
=> Add upgrade notes for receipts replication.

changelog.d/13934.misc, synapse/handlers/device.py, synapse/storage/databases/main/devices.py, synapse/storage/databases/main/room.py
=> Handle local device list updates during partial join

changelog.d/13890.misc, synapse/handlers/federation.py
Only give up backfilling after 5 denials (where denial = 4xx response code).
=> Improve backfill robustness by trying more servers.

changelog.d/13904.bugfix, synapse/push/clientformat.py
Spec marks those as required fields and clients rely on it.
Broken in 1.66.
Fixes #13837
=> Always send default and rule_id to clients

changelog.d/13937.feature, synapse/storage/databases/main/event_push_actions.py, synapse/storage/databases/main/receipts.py, tests/storage/test_receipts.py
Splitting this out of #13877, it is mostly a refactor / clarification:
* Renames a method.
* Moves a method into tests, which is test-only.
* The newly renamed `get_last_unthreaded_receipt_for_user_txn` now only checks for *unthreaded receipts*, which is all that should exist in the database anyway.
=> Clarify that a method returns only unthreaded receipts

changelog.d/13939.feature, synapse/storage/databases/main/event_push_actions.py
This would have caught #13933.
=> Explicit cast to enforce type hints.

changelog.d/13924.misc, synapse/storage/database.py
Follow-up to https://github.com/matrix-org/synapse/pull/13760#issuecomment-1251129040. I have tried to write down my understanding and better explain what the heck is going on. It may be too verbose for your taste.
=> Update UPSERT comment now that native upserts are the default

changelog.d/13952.bugfix, synapse/util/check_dependencies.py, tests/util/test_check_dependencies.py
Fixes https://github.com/matrix-org/synapse/issues/13926, see https://github.com/matrix-org/synapse/issues/13926#issuecomment-1260740889
I don't like special-casing it, but :shrug:
=> Don't require `setuptools_rust` at runtime

changelog.d/13947.feature, synapse/module_api/__init__.py
Looks like these were missed in https://github.com/matrix-org/synapse/pull/13667
=> Add missing version information in the ModuleApi

changelog.d/13972.bugfix, synapse/handlers/federation.py, synapse/handlers/room.py, synapse/storage/controllers/state.py, synapse/storage/databases/main/roommember.py
Fixes #13942. Introduced in #13575.
Basically, let's only get the ordered set of hosts out of the DB if we *need* an ordered set of hosts. Since we split the function up the caching won't be as good, but I think it will still be fine as e.g. multiple backfill requests for the same room will hit the cache.
=> Fix performance regression in `get_users_in_room`

changelog.d/13974.doc, docs/systemd-with-workers/workers/media_worker.yaml, docs/workers.md
IMHO fixes #12221
There are information to the http listener in section for:
- `generic_worker`
- `stream_writers`
- `media_repository`
Other types of workers either do not handle any REST endpoints or are deprecated.
There are also examples for:
- generic worker
- stream writer
- background worker
- media worker
- Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the …
=> Add some cross references to worker documentation

changelog.d/13957.feature, synapse/handlers/send_email.py
Fixes #13951.
I don't have an email server (nor an Exchange account) to test this with, so it would be good if someone else could help on that front.
I'd like to sanity check that
- Synapse still sends out emails (and they don't now suddenly get marked as spam)
- Exchange auto-replies aren't sent in response to Synapse's emails
- Perhaps @a-0-dev could confirm if this works once it has landed in a release?
=> Discourage automatic replies to Synapse's emails

changelog.d/13973.misc, synapse/push/bulk_push_rule_evaluator.py, tests/push/test_push_rule_evaluator.py
We move the expensive check of visibility to *after* calculating push actions, avoiding the expensive check for users who won't get pushed anyway.
I think this should have a big impact on rooms with large numbers of local users that have pushed disabled.
=> Speed up calculating push actions in large rooms

.github/dependabot.yml, changelog.d/13976.misc, changelog.d/13977.misc
Let's just try this.
Fixes https://github.com/matrix-org/synapse/issues/11828
=> Enable dependabot updates

changelog.d/13925.misc, poetry.lock, scripts-dev/check_pydantic_models.py, synapse/app/_base.py, synapse/logging/context.py, synapse/logging/opentracing.py, synapse/storage/database.py, synapse/storage/databases/main/search.py, tests/storage/test_monthly_active_users.py, tests/utils.py
A second attempt at #13521. Closes #13500.
I want to update mypy to take advantages of their fixes to ParamSpec support. I previously did this in #13521 but ran into unexplained false positive mypy errors on other branches after that. I suspected a caching related problem (we do use [mypy caches in CI](https://github.com/matrix-org/backend-meta/blob/d58c9421951776c0f4e2895cb73ea3eb209df1de/.github/workflows/python-poetry-ci.yml#L68-L69)).
I had another go and was able to reproduce the caching problems locally. It's been reported upstream as https://github.com/Shoobx/mypy-zope/issues/76; I PRed a fix in https://github.com/Shoobx/mypy-zope/pull/80 (partly written in my own time) which made it into a release this morning.
I'm pretty confident that we shouldn't have any problems with caching …
=> Update mypy and mypy-zope

changelog.d/13992.misc, synapse/push/bulk_push_rule_evaluator.py, synapse/visibility.py, tests/rest/client/test_rooms.py
=> Skip filtering during push if there are no push actions

changelog.d/13966.misc, synapse/handlers/user_directory.py
Clarifications in user directory for users who share rooms tracking.
Spawned while working on [`get_users_in_room` mis-uses](https://github.com/matrix-org/synapse/pull/13958#discussion_r984074897) and thinking we could use `get_local_users_in_room` here but we can't.
From first glance, it seemed like this was only using local users from all of the `is_mine_id(user_id)` checks but I see that it does actually use remote users. Just making things a little more clear here what it does and mentions remote users so maybe that will be more obvious in the future.
- Use markdown where necessary, …
=> Clarifications in user directory for users who share rooms tracking

changelog.d/13960.misc, synapse/handlers/room_member.py
Fix `get_users_in_room` mis-use in `transfer_room_state_on_room_upgrade`
Spawning from looking into `get_users_in_room` while investigating https://github.com/matrix-org/synapse/issues/13942#issuecomment-1262787050.
See https://github.com/matrix-org/synapse/pull/13575#discussion_r953023755 for the original exploration around finding `get_users_in_room` mis-uses.
Related to the following PRs where we also cleaned up some `get_users_in_room` mis-uses:
- https://github.com/matrix-org/synapse/pull/13605
- https://github.com/matrix-org/synapse/pull/13608
- https://github.com/matrix-org/synapse/pull/13606
- https://github.com/matrix-org/synapse/pull/13958
- Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." …
=> Fix `get_users_in_room` mis-use in `transfer_room_state_on_room_upgrade`

changelog.d/13969.misc, synapse/handlers/federation_event.py
Revert the general exception recording introduced in https://github.com/matrix-org/synapse/pull/13814
As discussed with @reivilibre, https://github.com/matrix-org/synapse/pull/13815#discussion_r983384698
We should only be handling errors that we know how to handle. For example, we don't want to record the following errors or anything like them as failed pull attempts:
- `CancelledError`: When a request is cancelled by the user. This one is probably not as applicable for `/backfill` but is a perfect example of why we shouldn't catch everything.
- `NotRetryingDestination`: The per-destination HTTP request backoff error
- `FederationDeniedError`: "If this destination  is not on our federation whitelist"
- `RuntimeError`, `ValueError`, `AssertionError`, `KeyError`, etc because these represent …
=> Revert the general exception recording introduced in #13814

build_rust.py, changelog.d/14009.bugfix
=> Always build Rust extension in release mode

.github/workflows/dependabot_changelog.yml, changelog.d/13998.misc
I tried a version of this out on #13995 earlier and was able to automatically generate [a sensible-looking commit](https://github.com/matrix-org/synapse/pull/13995/commits/66a8cbb8107fc852d0fac3a110428a553c7de1f4).
Follow-up to #11828/#13976.
=> Protoype automatic changelogs for dependabot PRs

changelog.d/13956.bugfix, synapse/storage/database.py, synapse/storage/databases/main/end_to_end_keys.py
Instead of running a single large query, run a single query for
user-only lookups and additional queries for batches of user device
lookups.
Resolves #13580.
---
There is test coverage for `(user_id, device_id)` queries in `tests.storage.test_end_to_end_keys.EndToEndKeyStoreTestCase`.
Not sure about `user_id` queries. There are a few tests that run down that path but expect no results to be returned.
EDIT: complement includes a bunch of tests that run `/keys/query` requests containing `user_id`-only queries.
=> Refactor `_get_e2e_device_keys_txn` to split large queries

changelog.d/14012.misc, synapse/handlers/cas.py, synapse/handlers/ui_auth/checkers.py
PartialDownloadError is now marked as `Optional[bytes]`, though I think it should never be None in practice. See
https://github.com/twisted/twisted/pull/11688/files#r985657476
Closes #14008.
=> Fix twisted trunk mypy errors

.github/workflows/dependabot_changelog.yml, changelog.d/14017.misc
Follow-up to #11828, #13976, #13998, #14011.
We ran the workflow on a PR, but it failed to `git push` the changelog commit:
https://github.com/matrix-org/synapse/actions/runs/3174480896/jobs/5171326123
=> Try again to automate dependabot changelogs

changelog.d/14014.bugfix, synapse/storage/databases/main/events.py
=> Fix bug where we didn't delete staging push actions

.github/workflows/dependabot_changelog.yml, changelog.d/14021.misc
I'm now bored of this.
Previous iteration created a changelog [but the CI didn't then run afterwards](https://github.com/matrix-org/synapse/pull/14019#issuecomment-1265541594).
History: #11828, #13976, #13998, #14011, #14017, #this.
=> yet another attempt to make dependabot changelogs work

.github/workflows/dependabot_changelog.yml, .github/workflows/release-artifacts.yml, .github/workflows/tests.yml, changelog.d/14027.misc
History: #11828, #13976, #13998, #14011, #14017, #14021, ddcb52e455a275109d0d6f757e58118883b28fd8,  #this.
After some [digging](https://github.com/matrix-org/synapse/pull/14021#issuecomment-1265638135) it looks like workflows can't trigger other workflows by default. So let's be explicit and see if that lets us run CI on these `<EXPLETIVE>` changelogs.
=> Dependabot changelogs: trigger CI explicitly

changelog.d/14024.removal, docs/metrics-howto.md, docs/upgrade.md, docs/usage/configuration/config_documentation.md, synapse/config/metrics.py
Part of a series on #11106
This sets a timeline for removal of the legacy metrics, plus an intermediate step of disabling by default.
I've decided to document `enable_legacy_metrics` temporarily since it can't really be considered 'experimental' anymore if we're telling admins they can feel free to use it. But it has removal warning signs all over it, so hopefully this is OK?
Soft release blocker because this announcement needs to go out in the v1.69.0 release to be fair, though I suppose it *can* miss the RC if it needs to.
=> Announce that legacy metric names are deprecated, will be turned off by default in Synapse v1.71.0 and removed altogether in Synapse v1.73.0.

changelog.d/14003.doc, docs/usage/configuration/config_documentation.md
A lot of the links in the [documentation](https://matrix-org.github.io/synapse/v1.67/usage/configuration/config_documentation.html) have not been properly linkified, for [instance](https://matrix-org.github.io/synapse/v1.67/usage/configuration/config_documentation.html#user_directory), this PR fixes that!
=> Linkify config documentation.

changelog.d/13997.feature, rust/src/push/base_rules.rs, rust/src/push/mod.rs, stubs/synapse/synapse_rust/push.pyi, synapse/config/experimental.py, synapse/storage/databases/main/push_rule.py, tests/rest/client/test_rooms.py
Enables the push rule to not push server ACL events.
I'm not sure if there's anything special to do here or just Do It™️.
Part of #13954.
=> Use the stable prefix for MSC3786.

.github/workflows/release-artifacts.yml, changelog.d/14046.misc
Follow-up to #13983. I missed a breaking change in setup-python v4. Serves me right for rushing to cut through the dependabot spam.
=> Fix building wheels on OSX

changelog.d/14032.feature, synapse/rest/client/versions.py
Fixes #13953.
It is likely worth a quick look over https://matrix.org/blog/2022/06/16/matrix-v-1-3-release#the-full-changelog by a reviewer to make sure that nothing is missed. #13953 also has some cross-links.
=> Advertise supporting version 1.3 of the Matrix spec.

changelog.d/14045.misc, synapse/storage/databases/main/event_push_actions.py
I realized that the changes in #13776 (which are slated to go in v1.70.0, so the next release) cannot be properly rolled back, see below for a stack trace.
The changes in this PR essentially apply the on-going background update also to any new rows we're updating, so that the upsert will work correctly once the constraints are dropped (see #13776).
----
```
2022-10-04 08:30:22,309 - synapse.metrics.background_process_metrics - 242 - ERROR - rotate_notifs-4 - Background process 'rotate_notifs' threw an exception
File "synapse/synapse/metrics/background_process_metrics.py", line 240, in run
return await func(*args, **kwargs)
File "synapse/synapse/storage/databases/main/event_push_actions.py", line 1006, in _rotate_notifs
caught_up = await …
```
=> Fix backwards compatibility with upcoming threads schema changes

changelog.d/14053.bugfix, synapse/storage/databases/main/room.py, tests/rest/client/test_rooms.py
Fixes two related bugs:
* The handling of `[None]` for room types was not quite correct (as you'd end up with the wrong number of arguments).
* The ordering of arguments when providing both a network tuple and room type field was incorrect.
Fixes #14051
=> Fix handling of public rooms filter with a network tuple.

changelog.d/14063.misc, docker/Dockerfile-workers, docker/conf-workers/nginx.conf.j2
Have nginx send its logs to stderr/out, so that we can debug https://github.com/matrix-org/synapse/issues/13334.
=> Complement test image: capture logs from nginx

changelog.d/14033.misc, synapse/handlers/federation_event.py, synapse/handlers/message.py, synapse/notifier.py, synapse/replication/tcp/client.py
A little clean-up from after the work in #13800. Currently the code wakes up the notifier for each event in the batch, this PR changes that so the notifier is only called on the last persisted event. Reviewable commit-by-commit.
=> Batch up notifications after event persistence 

changelog.d/14080.misc, pyproject.toml
Mitigates #14079 by using poetry-core 1.2.0, no exceptions.
=> Pin build-system requirements

changelog.d/14065.misc, synapse/federation/transport/client.py, synapse/util/__init__.py, tests/federation/transport/test_client.py
Fixes #13293. Improves on #12875 and #9958.
This change means that we should raise one Sentry event for each such failure to `.finish()` a parser, instead of an event for each line printed to stderr.
I have only included the first traceback `exceptions[0]`: I'm assuming that's enough to diagnose what happened if we see this error. I do make sure to include the `str()` of each individual exception though.
I considered using https://pypi.org/project/exceptiongroup/ but this was a little scary: it mentions patching TracebackException and adding exception hooks; I feared that this wouldn't play nicely with twisted + logcontexts + other arcanery in Synapse I don't grok.
=> Always close _all_ `ijson` coroutines, even if doing so raises Exceptions

changelog.d/14093.doc, docker/README.md, docs/usage/configuration/config_documentation.md
A small fixup I noticed just now. Link was broken in #13491.
=> Fix broken links to README

changelog.d/14072.misc, synapse/metrics/_legacy_exposition.py
=> Catch BrokenPipeError from metrics server, and log as a warning

changelog.d/14054.feature, synapse/rest/client/devices.py
=> Use Pydantic to validate /devices endpoints

changelog.d/14077.doc, docs/systemd-with-workers/workers/federation_sender.yaml, docs/systemd-with-workers/workers/pusher_worker.yaml, docs/workers.md
=> Add sample worker files for `pusher` and `federation_sender`

changelog.d/14089.bugfix, synapse/rest/media/v1/oembed.py, tests/rest/media/v1/test_oembed.py
This adds some more validation to the oEmbed code and slightly changes the philosophy of the return values -- previously if an "error" was encountered (e.g. a bad `cache_age`) we would ignore the entire result. Now we try to parse as much as possible and return any "valid" data that we encounter.
I think for URL previews getting as much data as possible is the desired outcome.
(The whitespace changes in this PR are awful, sorry about that.)
Fixes #14061
=> Be more lenient in the oEmbed response parsing.

changelog.d/14078.doc, docs/metrics-howto.md
Try to fix #9955
What is the prefered / better way?
```yaml
- port: 9000
type: http
bind_addresses: ['::1', '127.0.0.1']
resources:
- names: [metrics]
```
vs
```yaml
- port: 9000
type: metrics
bind_addresses: ['::1', '127.0.0.1']
```
(run the …
=> Improve the listener example on the metrics documentation

changelog.d/14085.misc, docs/upgrade.md, pyproject.toml, synapse/config/repository.py
Fixes #14079, properly. Reverts #14080.
A summary of the problem:
1. Synapse defines an extra called `url_preview` with an underscore.
2. Synapse looks up its own packaging metadata at runtime to check if the dependencies needed for `url_preview` are installed.
3. Poetry-core 1.3.0 now [normalises extra names](https://github.com/python-poetry/poetry-core/pull/476) when writing metadata, per PEP 685. 
- This means the extra will be written to metadata as `url-preview` _with a hyphen_. 
- So the lookup in point 2 will fail if Synapse was built/installed by poetry-core 1.3.0.
Fix ourselves to be forward compatible by changing the spelling of `url_preview` to `url-preview`. Call this out in the upgrade notes.
_Remark._ I considered adding compatibility code to `check_dependencies.py` which …
=> Unpin build-system requirements, but impose an upper-bound

changelog.d/14092.misc, synapse/__init__.py, synapse/config/logger.py
This properly parses the `SYNAPSE_ASYNC_IO_REACTOR` environement variable similar to what we do with `SYNAPSE_USE_FROZEN_DICTS`.
It also logs the reactor class currently being used on startup, to help with debugging.
There also was an unecessary try/catch on the reactor installation that I removed.
This is needed for this PR in sytest: https://github.com/matrix-org/sytest/pull/1301
Related: 
- https://github.com/matrix-org/synapse/issues/14091
=> Parse SYNAPSE_ASYNC_IO_REACTOR env variable & log the reactor on startup

changelog.d/14124.doc, docs/usage/configuration/config_documentation.md
The config manual had this listed as "alias_creation", whereas the option is named "alias_creation_rules".
=> Fix name of "alias_creation_rules" option in config manual

.dockerignore, changelog.d/14129.bugfix, docker/Dockerfile
We tried to do this in #13858, but failed.
The fix here is to copy over the `Cargo.lock` file in the dockerfile. While we're here we also copy over the `Cargo.toml`, which doesn't change anything right now but would if we included more metadata in it.
I'm not actually sure how to check this is picking up the lock file, beyond observing that the lockfile is in the directory when the Rust extension is built
=> Fix pinning Rust deps in docker images

.github/dependabot.yml, Cargo.lock, changelog.d/14132.misc
And update the lockfile to avoid spam.
=> Enable dependabot for Rust dependencies

changelog.d/14135.bugfix, synapse/replication/http/register.py
Fixes https://github.com/matrix-org/synapse/issues/14131
=> Fallback if 'approved' isn't included in a registration replication request

changelog.d/14138.bugfix, synapse/storage/databases/main/event_push_actions.py
Broke by #14045. Fixes #14120.
Introduced in v1.69.0rc2.
=> Fix rotating existing notifications in push summary

.ci/scripts/setup_complement_prerequisites.sh, changelog.d/14144.misc, docs/development/contributing_guide.md
Fixes the problem as described at https://github.com/matrix-org/complement/issues/497
=> Handle `gottestfmt` repository move

changelog.d/14141.docker, changelog.d/14141.misc, docker/Dockerfile, docker/Dockerfile-dhvirtualenv, pyproject.toml
Closes #14139
(branch name is wrong, should be `dmr/rust-minimal-profile`)
Will likely conflict with #14130.
=> Use minimal Rust installation in docker images and CI

changelog.d/14109.misc, synapse/storage/databases/main/roommember.py
This avoids blocking calls to the signular `get_rooms_for_user` when loading rooms for many users by batching the batched list calls.
To resolve: #14049
=> Batch up calls to `get_rooms_for_users`

changelog.d/14159.feature, synapse/storage/databases/main/receipts.py
#13782 was missing a commit from #13202 (https://github.com/matrix-org/synapse/pull/13202/commits/d35ee33c050c4f7eca75022a2383c88e2e6c8e5c) causing the receipts returned down sync to be missing information.
Builds on #14140.
Tests at matrix-org/complement#500.
=> Return the thread ID properly down sync.

changelog.d/14125.bugfix, synapse/handlers/federation_event.py, synapse/handlers/message.py
Currently we pre-calculate the joined hosts at an event when using redis so that external federation senders don't have to calculate this themselves. The bug being fixed, introduced in #13800,  resulted in the joined hosts only being calculated for the first event in a batch being persisted, rather than at all of them. This PR changes `cache_joined_hosts_for_events` to take a list of events, and calculate the joined hosts at each of the events.
=> Fix a bug where the joined hosts for a given event were not being properly cached

changelog.d/14171.feature, synapse/storage/databases/main/relations.py
Fixes the backfill script given in #13394. I missed parentheses for sqlite.
=> Fix sqlite syntax for upserts.

changelog.d/14172.bugfix, synapse/storage/databases/main/event_push_actions.py
BG job added in #13753, see https://github.com/matrix-org/synapse/pull/13753/files#diff-f121377d76a7b35c60092da2c4bf8c849544459a2c676cf8e87057aff24ece54R244-R247
=> Optimise the event_push_backfill_thread_id bg job

.github/workflows/docker.yml, changelog.d/14173.docker, docker/Dockerfile
Not sure if we just want to default to true?
=> Fix docker build OOMing in CI for arm64 builds

changelog.d/14163.feature, synapse/storage/databases/main/cache.py
This was missed in #13824 -- we were not invalidating the cache if the event was redacted.
=> Properly invalidate cache for get_thread_id.

changelog.d/14174.feature, synapse/rest/client/receipts.py, synapse/storage/databases/main/cache.py, synapse/storage/databases/main/relations.py, tests/storage/test_relations.py
See the discussion in #14168, this is a minor spec-compliance fix for how clients expect receipts to work.
Builds on #14163 
More tests at matrix-org/complement#501.
=> Accept receipts on events related to the root event.

changelog.d/14189.doc, docs/usage/configuration/config_documentation.md
"Register a user" in https://matrix-org.github.io/synapse/v1.68/usage/configuration/config_documentation.html?highlight=shared%20secret#registration_shared_secret is broken. No longer.
=> Fix dead link to admin registration API

changelog.d/14155.misc, synapse/storage/databases/main/cache.py
More info detail on issue: https://github.com/matrix-org/synapse/issues/14154
This should fix a race where the event notification comes in over replication before the state replication, leaving a window during which a sync may get an incorrect list of rooms for the user.
=> Invalidate rooms for user caches when receiving membership events

changelog.d/14148.feature, synapse/api/filtering.py, synapse/config/experimental.py, synapse/rest/client/versions.py, synapse/storage/databases/main/stream.py, tests/api/test_filtering.py, tests/rest/client/test_relations.py, tests/rest/client/test_rooms.py, tests/storage/test_stream.py
Provides an experimental config option to enable support for [MSC3874](https://github.com/matrix-org/matrix-spec-proposals/pull/3874), filtering of `/messages` by the relation type of events.
Related to #14143.
=> Support filtering the /messages API by relation type (MSC3874)

.ci/scripts/calculate_jobs.py, .github/workflows/docs.yaml, .github/workflows/release-artifacts.yml, .github/workflows/tests.yml, changelog.d/14216.misc
Part of #14203.
I think warnings are the only ones that come directly from the Synapse repo.
=> Deal with some GHA deprecation warnings

changelog.d/14221.misc, pyproject.toml, synapse/config/cache.py
The same kind of problem as discussed in #14085:
1. we defined an extra with an underscore
2. we look it up at runtime with an underscore
3. but poetry-core 1.3.x. installs it with a dash, causing (2) to fail.
Fix by using a dash everywhere.
=> Fix `track_memory_usage` on poetry-core 1.3.x installations

changelog.d/14198.misc, docker/complement/conf/workers-shared-extra.yaml.j2
This is to soon add a removed test in https://github.com/matrix-org/complement/pull/279, converted sytest "Test URL preview".
Might not play well with https://github.com/matrix-org/synapse/issues/14079
(run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html …
=> Enable url preview in complement

changelog.d/14227.misc, poetry.lock, pyproject.toml
This makes it slightly less tedious to update these things via successive dependabot updates, by reducing the likelihood of a merge conflict.
=> Don't pin dev-deps in pyproject; use lower bounds

changelog.d/14214.misc, synapse/event_auth.py, synapse/handlers/event_auth.py, synapse/handlers/federation.py, synapse/handlers/message.py, synapse/handlers/room.py
This is work to support adding the initial power level event to the events that are batch persisted when creating a room. 
This PR allows auth checks to look in the batch of events to be persisted for an authorizing event, as an event's authorizing event may not have been persisted yet if it is part of the batch to be persisted. Currently it only checks the DB.
=> Prepatory work for adding power level event to batched events

.github/workflows/release-artifacts.yml, changelog.d/14212.feature
=> Add aarch64 wheels to CI

changelog.d/14145.doc, synapse/events/snapshot.py
Based on the other comments I think this is what was meant? Otherwise it doesn't make sense.
=> Fix docstring in EventContext

changelog.d/14215.bugfix, synapse/storage/databases/main/events_worker.py, tests/rest/client/test_rooms.py
Fix MSC3030 `/timestamp_to_event` endpoint returning `outliers` that it has no idea whether are near a gap or not (and therefore unable to determine whether it's actually the closest event). The reason Synapse doesn't know whether an `outlier` is next to a gap is because our gap checks rely on entries in the `event_edges`, `event_forward_extremeties`, and `event_backward_extremities` tables which is [not the case for `outliers`](https://github.com/matrix-org/synapse/blob/2c63cdcc3f1aa4625e947de3c23e0a8133c61286/docs/development/room-dag-concepts.md#outliers).
Also fixes MSC3030 Complement `can_paginate_after_getting_remote_event_from_timestamp_to_event_endpoint` test flake.  Although this acted flakey in Complement, if `sync_partial_state` raced and beat us before `/timestamp_to_event`, …
=> Fix MSC3030 `/timestamp_to_event` returning `outliers` that it has no idea whether are near a gap or not

.github/workflows/triage-incoming.yml, changelog.d/14230.misc
Uses https://github.com/matrix-org/backend-meta/pull/14.
=> Use backend-meta edition of issue triage workflow
