matrix-org/synapse

changelog.d/14110.doc
docs/usage/configuration/config_documentation.md

(i really wish our doc was autogenerated from the code to avoid typos and desyncs like this.)

Document encryption_enabled_by_default_for_room_type under the right name

---

changelog.d/14191.doc
synapse/api/errors.py
synapse/federation/federation_server.py

Explain `SynapseError` and `FederationError` better
Spawning from https://github.com/matrix-org/synapse/pull/13816#discussion_r993262622

Explain `SynapseError` and `FederationError` better

---

.github/workflows/release-artifacts.yml
changelog.d/14249.misc

Part of of https://github.com/matrix-org/synapse/issues/14203
10.15 is end-of-life as of ~5 weeks ago, see https://endoflife.date/macos and also https://github.com/actions/runner-images/issues/5583

Build wheels on macos 11, not 10.15

---

changelog.d/13710.bugfix
synapse/event_auth.py

This fixes Synapse possibly defederating some rooms with conduit and dendrite<=0.9.5 as well as breaking some clients relying on the guarantees of the client-server API.
Spec link: https://spec.matrix.org/v1.3/client-server-api/#size-limits
Spec issue: https://github.com/matrix-org/matrix-spec/issues/1001
This does break some rooms, if they have any events violating these constraints in their auth chain. This however should not affect that many rooms, considering how long it took to discover this. Most notably those rooms didn't federate with conduit or dendrite servers (although the latter has changed their auth code to match the current synapse implementation recently). More specifically:
- the event id and room id is not user controlled and all implementations so far use plain ASCII. …

Fix event size checks

---

changelog.d/14248.bugfix
synapse/storage/databases/main/events.py
tests/rest/client/test_relations.py

When the last event in a thread was redacted we were not properly updating the `threads` table to either:
* Find the *new* latest event in the thread and store it into the table; or
* Removing the thread from the table if it is no longer a thread (i.e. all events in the thread were redacted).
Fixes #14241

Properly update the threads table when thread events are redacted

---

changelog.d/14259.misc
pyproject.toml

As they are too slow to build for everything else

Only build aarch64 wheels for cpython manylinux

---

changelog.d/14258.bugfix
synapse/app/_base.py

Fix logging error on SIGHUP

---

changelog.d/14268.misc
synapse/storage/databases/main/devices.py

Some frantic clutching at straws to debug https://github.com/matrix-org/synapse/issues/14251.

Add debugging to help diagnose lost device-list-update

---

changelog.d/14283.bugfix
synapse/storage/databases/main/relations.py

This reverts commit ab8047b4bf581d0c343c1e900e8740745668d941 (#14034) due to #14252.
Fixes #14252.
Reopens #12793, #12503.
Any subsequent fix requires behavior corrections to the spec, see matrix-org/matrix-spec#1299.

Revert behavior change for bundling edits of non-message events

---

changelog.d/13897.feature
synapse/storage/engines/sqlite.py

As discussed in https://github.com/matrix-org/synapse/issues/2917#issuecomment-877146280, it makes sense to use the WAL for SQLite installs.
Further optimizations are possible (e.g. `synchronous = NORMAL`), but since they require tradeoffs (e.g. for the DB's durability), they have not been implemented in this PR, and could be implemented in a follow-up PR. …

Enable WAL for SQLite

---

.github/workflows/tests.yml
changelog.d/14287.misc

This was missed in #12595 I think, as the docker images already had a rust compiler in it?
Anyway, I'm hoping this will speed up starting `trial` runs a bit due to the rust cache.

Cache rust build deps in trial CI

---

changelog.d/13844.misc
docs/upgrade.md
synapse/handlers/auth.py
synapse/module_api/__init__.py
synapse/rest/client/login.py
synapse/rest/client/login_token_request.py
synapse/storage/databases/main/registration.py
synapse/storage/schema/main/delta/73/10login_tokens.sql
synapse/util/macaroons.py
tests/handlers/test_auth.py
tests/util/test_macaroons.py

Fixes #13841, based on #13842
One important thing this does, is that now login tokens can only be used once. Before, they could be used multiple times before they expired.

Save login tokens in database 

---

changelog.d/14301.bugfix
synapse/appservice/api.py
tests/appservice/test_api.py

Introduced by #13996 in 1.70.0rc1.
I would like to do a follow-up patch which improves the typehinting to catch this at lint-time.

Fix incorrectly sending authentication tokens to application service as headers

---

.github/workflows/twisted_trunk.yml
changelog.d/14305.misc

Surprised it worked without this tbh!
Fixes #14296. Hopefully.

Use poetry 1.2 for complement in latest deps

---

changelog.d/14243.bugfix
synapse/storage/databases/main/roommember.py

Fix presence bug #13601 introduced by #13313.
This happens when presence coming from users that are in 2 or more different rooms is calculated for a sync.
Complement PR: https://github.com/matrix-org/complement/pull/525

Fix presence bug introduced in 1.64 by #13313

---

changelog.d/14310.feature
synapse/storage/databases/main/search.py
tests/storage/test_room_search.py

See #14298 for details, but postgresql 14 changed the behavior of `websearch_to_tsquery` to fix some bugs. The tests were hitting those edge-cases though.
This is a bit ugly, but I couldn't come up with a better way to do it...
Fixes #14298.
This was broken in #11635.

Fix tests for change in PostgreSQL 14 behavior change.

---

changelog.d/14314.bugfix
synapse/api/ratelimiting.py
synapse/handlers/room.py
tests/rest/client/test_rooms.py

Fixes #14312.
~~I make special effort to match the old limits, though I've tried to do it in a saner way: we apply the 2 units of ratelimiting upfront atomically rather than perhaps doing some work only to fail persisting the creator's membership event.
It doesn't seem to make sense to ratelimit half-way through creating a room — it's much better to avoid the wasted work and avoid half-creating a room (possibly leading to a janky state).~~
I *did* match the old limits, but now decided to be twice as lenient — Element Web's space creation screen always did fall over even with the old limits if you were fast enough. Given that we're making room creation more performant, it seems reasonable to apply the same cost as one event send — you're not really hurting anyone by creating empty rooms. …

Fix room creation being rate limited too aggressively since Synapse v1.69.0.

---

CHANGES.md

We noted in a [previous announcement](https://matrix.to/#/!iyIlInqJyxXrRmRHFx:matrix.org/$JCTRKh_85cuEUuM0HB1a8w9WtRaypmqDUR-GqOLqw2Q?via=matrix.org&via=tchncs.de&via=privacytools.io) that https://github.com/matrix-org/synapse/issues/14300 was a regression in 1.70.0.
Since then, we've concluded that the problem was limited to the reporter, and thus have not needed to include a fix for it in 1.70.1.
---
This PR does not require a changelog entry.

Add a note that #14300 did not get a fix for 1.70.1

---

changelog.d/14311.feature
synapse/storage/databases/main/search.py

Requested at https://github.com/matrix-org/synapse/pull/11635#discussion_r1004176648
This uses triple quote strings (instead of string concatenation) for the SQL queries in the search store.

Switch search SQL to triple-quote strings.

---

changelog.d/14304.bugfix
synapse/handlers/e2e_keys.py
synapse/storage/databases/main/end_to_end_keys.py

Fixes https://github.com/matrix-org/synapse/issues/13114 using the solution described in https://github.com/matrix-org/synapse/issues/13114#issuecomment-1171312030. May also fix https://github.com/matrix-org/synapse/issues/12750.
This commit prevents the [`POST /_matrix/federation/v1/user/keys/query`](https://spec.matrix.org/v1.4/server-server-api/#post_matrixfederationv1userkeysquery) endpoint from returning device names for users when the [`allow_device_name_lookup_over_federation` config option](https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#allow_device_name_lookup_over_federation) was set to `false`.
I opted for a `include_displaynames` option for `query_local_devices` as I assume we'll eventually add in a similar option to …

Prevent federation user keys query from returning device names if disallowed

---

changelog.d/14336.bugfix
synapse/rest/client/devices.py
tests/rest/client/test_devices.py

Fixes #14334, an oversight in #14054.
Unspotted because no test hits that rest endpoint. I've written a very rudimentary one.
Also fixes a bug in #14054 which mypy missed. https://github.com/matrix-org/synapse/pull/14055 would have helped.

Fix dehydrated device REST checks

---

.github/workflows/tests.yml
changelog.d/14313.misc

Use a maintained action for setting up the rust toolchain.
Be explicit that we're fine with any Python 3 version for the simple lint checks.
Part of #14203.
Needs the `[DO NOT MERGE]` commit to be reverted before merging.

Deal with another batch of GHA warning messages

---

changelog.d/14347.bugfix
synapse/federation/federation_client.py

The typo causes `logger.info(...)` to fail. Stdlib(?) logging describes the failure on stderr, which ends up getting reported as multiple events in Sentry.

Fix typo in #13320 which could cause log spam

---

.github/workflows/triage_labelled.yml

Run when an issue is labelled with X-Needs-Info only. Add to triage board.
Use itemId which is output by actions/add-to-project to run the mutation to update the field value (i.e. move to the right column).
(run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide …

Fix issue automation for Needs-Info

---

CHANGES.md
changelog.d/14353.removal
docs/upgrade.md
docs/usage/configuration/config_documentation.md
synapse/config/metrics.py

Fixes #14352.
Context: #11106.

Disable legacy Prometheus metric names by default. They can still be re-enabled for now, but they will be removed altogether in Synapse 1.73.0.

---

.github/workflows/latest_deps.yml
.github/workflows/twisted_trunk.yml
changelog.d/14351.misc

Part of #14203. Like the changes in #14313.

Use maintained action to install Rust in latest deps/twisted trunk jobs

---

changelog.d/14358.doc
docs/usage/administration/monthly_active_users.md

These were changed in https://github.com/matrix-org/synapse/pull/13718

Update legacy `synapse_admin_mau:` metric names in docs

---

changelog.d/14364.bugfix
synapse/rest/client/login.py
tests/rest/client/test_auth.py

As per https://github.com/matrix-org/matrix-spec/pull/1289, the refresh token MSC landed before the new endpoint versioning scheme, which means the /refresh endpoint should be available as /r0 and /v3 instead of /v1
Signed-off-by: Tulir Asokan <tulir@maunium.net>

Fix /refresh endpoint version

---

changelog.d/14369.bugfix
synapse/api/filtering.py
tests/api/test_filtering.py

For forward compatibility, Synapse needs to ignore fields it does not
recognise instead of raising an error.
Fixes #14365.

Do not reject `/sync` requests with unrecognised filter fields

---

changelog.d/14297.doc
docs/workers.md

---
Any information is better than "exercise for the reader".
cc @deepbluev7 @cvwright thx for the solution

Add example on how to load balance /sync requests

---

changelog.d/14374.bugfix
synapse/storage/databases/main/events_bg_updates.py

When this background update did its last batch, it would try to update all the
events that had been inserted since the bgupdate started, which could cause a
table-scan. Make sure we limit the update correctly

Fix background update table-scanning `events`

---

.ci/scripts/calculate_jobs.py
.github/workflows/tests.yml
changelog.d/14394.misc

Test against PostgreSQL 15 in CI

---

changelog.d/14397.removal
synapse/storage/databases/main/search.py
synapse/storage/engines/postgres.py
tests/storage/test_room_search.py

We can simplify the full text search code a bit now that we support only Postgres 11+
Builds on #14392.

Drop support for Postgres 10 in full text search code.

---

changelog.d/14346.misc
synapse/handlers/federation_event.py

Quieter logging for stateres failure at missing prev events

---

changelog.d/14409.bugfix
synapse/storage/schema/main/delta/73/11event_search_room_id_n_distinct.sql.postgres

PostgreSQL may underestimate the number of distinct `room_id`s in
`event_search`, which can cause it to use table scans for queries for
multiple rooms.
Fix this by setting `n_distinct` on the column.
Resolves #14402.

Fix PostgreSQL sometimes using table scans for `event_search`

---

changelog.d/14410.misc
synapse/util/caches/stream_change_cache.py

This code looks like it was factored out, but the original version wasn't deleted.
Calling this twice in a row makes no sense since the first call will reduce the size appropriately. The second loop would immediately be skipped, so this wasn't calling a bug besides wasted CPU.

Remove duplicated code to evict entries.

---

changelog.d/14414.doc
docs/reverse_proxy.md

I chased my tail for a few hours tonight debugging an issue where my client seemed to time out on production requests that seemed to go off without a hitch in my local environment.
After a good amount of debugging, it appeared to me that the chunked responses from upstream (likely thanks to https://github.com/matrix-org/synapse/pull/8013) were not being properly handled by one of the proxies in use. (I'm running an Openresty/Nginx proxy on Cloud Run.)
Turns out that Nginx [defaults to using HTTP/1.0 for upstream proxy requests](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_http_version), which is crazy to me but that's the way it is. `transfer-encoding: chunked` was introduced in HTTP 1.1.
It also seems to me that Nginx response buffering isn't helpful to us in this …

Update sample Nginx configuration to HTTP 1.1

---

changelog.d/14411.misc
synapse/storage/controllers/persist_events.py
synapse/storage/databases/main/events.py

This cleans-up some incorrect type hints and unused variables.

Clean-up events persistance code

---

.github/dependabot.yml
changelog.d/14434.misc
rust/Cargo.toml

This is to help downstream packagers.
c.f. https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#versioning-strategy

Make Dependabot only bump Rust deps in the lock file

---

changelog.d/14417.misc
synapse/storage/databases/main/events_worker.py

Sometimes a docstring that omits detail is more harmful than not having one — it wasn't clear to me that this had extra conditions on what events it returned.

Update docstring to clarify that `get_partial_state_events_batch` does not just give you completely arbitrary partial-state events.

---

changelog.d/14356.bugfix
synapse/push/clientformat.py

Dirty fix for #14348
A proper fix would have proper tests and factor out the pattern_type cases as well as clean up the logic.
Signed-off-by: Nicolas Werner <nicolas.werner@hotmail.de>
(run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linters) …

Send content rules with pattern_type to clients

---

changelog.d/14461.misc
synapse/handlers/room.py

We don't filter state usually, so doing so here is a waste of time. This is not much of an issue for clients that enable lazy loading of members, since there will be fewer state events.
c.f. implementation of `/state` where we don't do the same filitering: https://github.com/matrix-org/synapse/blob/1eed795fc56d95df3968e37f3a4db92f24513e15/synapse/handlers/message.py#L165

Don't filter state in /context response

---

changelog.d/14376.misc
synapse/replication/slave/__init__.py
synapse/replication/slave/storage/__init__.py
synapse/replication/slave/storage/_slaved_id_tracker.py
synapse/storage/databases/main/account_data.py
synapse/storage/databases/main/devices.py
synapse/storage/databases/main/events_worker.py
synapse/storage/databases/main/push_rule.py
synapse/storage/databases/main/pusher.py
synapse/storage/databases/main/receipts.py
synapse/storage/util/id_generators.py

Reverts matrix-org/synapse#14376
Due to https://github.com/matrix-org/synapse/issues/14456

Revert "Remove slaved id tracker"

---

changelog.d/14453.bugfix
synapse/storage/databases/main/receipts.py
tests/storage/databases/main/test_receipts.py

As part of the database migration to support threaded receipts, there is
a possible window in between
`73/08thread_receipts_non_null.sql.postgres` removing the original
unique constraints on `receipts_linearized` and `receipts_graph` and the
`reeipts_linearized_unique_index` and `receipts_graph_unique_index`
background updates from `72/08thread_receipts.sql` completing where
the unique constraints on `receipts_linearized` and `receipts_graph` are
missing. Any emulated upserts on these tables must therefore be
performed with a lock held, otherwise duplicate rows can end up in the
tables when there are concurrent emulated upserts. Fix the missing lock.
Note that emulated upserts no longer happen by default on sqlite, since
the minimum supported version of sqlite supports native upserts by …

Fix background updates failing to add unique indexes on receipts

---

changelog.d/14393.bugfix
synapse/handlers/presence.py
tests/handlers/test_presence.py
tests/module_api/test_api.py
tests/replication/_base.py

This PR fixes an invalid comparison of types. The comparison was included in https://github.com/matrix-org/synapse/pull/12213 and effectively meant that the fix did not apply when calling `/sync` or `/events` on a worker process. Presumably the included unit tests didn't catch the bug as they don't run in worker mode.
How come mypy didn't catch this?

Fix an invalid comparison of `UserPresenceState` to `str`

---

changelog.d/14476.misc
docs/workers.md
synapse/config/workers.py

#14400 just missed the 1.72 merge window. Thanks @dklimpel for [pointing that out](https://github.com/matrix-org/synapse/pull/14400#discussion_r1025303088).

Fix version that `worker_main_http_uri` is redundant from

---

changelog.d/14452.misc
mypy.ini

This change enables the [`strict_equality`](https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-strict-equality) option for mypy. This catches equality comparisons between variables with "non-overlapping" types.
This check would have prevented the bug in:
- https://github.com/matrix-org/synapse/pull/14393
- https://github.com/matrix-org/synapse/pull/14449
so seems worthwhile to switch on by default!
The following PRs must first be merged (to fix existing errors) before this PR can be merged:
- https://github.com/matrix-org/synapse/pull/14393
- https://github.com/matrix-org/synapse/pull/14449
- https://github.com/matrix-org/synapse/pull/14451
Thanks to @babolivier for originally pointing out this option in https://github.com/matrix-org/synapse/pull/14393#issuecomment-1307 …

Enable 'strict_equality' checking for mypy

---

changelog.d/14487.misc
synapse/config/ratelimiting.py

The previous default was the same as the `rc_message` rate limit, which
defaults to 17,280 per day.
---
As suggested by @clokep.

Reduce default third party invite rate limit to 216 invites per day

---

changelog.d/14490.misc
synapse/crypto/keyring.py
tests/crypto/test_keyring.py

Fixes #14488.
I haven't yet done an audit of everywhere else we call urllib.parse.quote---suggest making that a separate task.

Fix /key/v2/server calls with URL-unsafe key IDs

---

changelog.d/14479.misc
scripts-dev/federation_client.py

Turns out that the `federation_client` script had a bug for servers with `.well-known` files: suppose the server `example.com` had a well-known file which redirected to `matrix.example.net`. The client would then set the `Host` header to `example.com`, where it should have been `matrix.example.net`.
While I'm messing about with it, I've fixed TLS verification.

Fixes to `federation_client` dev script

---

changelog.d/14499.doc
docs/usage/administration/admin_api/README.md

Signed-off-by: Brennan Chapman <brennan@chapmanb.com>
* [✅ ] Pull request is based on the develop branch
* [✅ ] Pull request includes a [changelog file](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
* [✅ ] Pull request includes a [sign …

Fix broken admin API request recommendation link

---

changelog.d/14477.bugfix
contrib/grafana/synapse.json

Unfortunately these got held back because our Grafana instance was playing funny.
Replacing all `${DS_PROMETHEUS}` with `${datasource}` in the JSON Model in Grafana seems to have fixed the option to export the dashboard for sharing externally.
Fixes: #14465 
Supersedes: #14235 
Part of: #11106 
<ol>
<li>
Update Grafana dashboard with fixed panels 
</li>
</ol>

Update forgotten references to legacy metrics in the included Grafana dashboard.

---

changelog.d/14491.feature
synapse/handlers/relations.py
synapse/storage/database.py
synapse/storage/databases/main/relations.py
synapse/util/caches/descriptors.py
tests/rest/client/test_relations.py

This applies similar changes for annotations as we did for edits (#11660) and threads (#11752) -- namely we make a query per group of events instead of per individual event.
Please see inline comments for some more info.
See #13624.

Batch fetch bundled annotations

---

changelog.d/14508.feature
synapse/handlers/relations.py
synapse/storage/databases/main/cache.py
synapse/storage/databases/main/events.py
synapse/storage/databases/main/relations.py
tests/rest/client/test_relations.py

This applies similar changes for annotations as we did for edits (#11660, threads (#11752), and annotations (#14491) -- namely we make a query per group of events instead of per individual event.
Please see inline comments for some more info.
See #13624.
Also relates to #14486.
Based on #14491.

Batch fetch bundled references

---

changelog.d/14510.feature
synapse/handlers/relations.py

This parallelizes the calls to fetch annotations, references, and edits since they can't affect one another.
Related to #13624.
Based on #14508.

Parallelize calls to fetch bundled aggregations.

---

changelog.d/14516.misc
synapse/handlers/device.py
synapse/storage/database.py
synapse/storage/databases/main/devices.py
synapse/storage/schema/main/delta/73/12refactor_device_list_outbound_pokes.sql
tests/storage/test_devices.py

When a local device list change is added to
`device_lists_changes_in_room`, the `converted_to_destinations` flag is
set to `FALSE` and the `_handle_new_device_update_async` background
process is started. This background process looks for unconverted rows
in `device_lists_changes_in_room`, copies them to
`device_lists_outbound_pokes` and updates the flag.
To update the `converted_to_destinations` flag, the database performs a
`DELETE` and `INSERT` internally, which fragments the table. To avoid
this, track unconverted rows using a `(stream ID, room ID)` position
instead of the flag.
From now on, the `converted_to_destinations` column indicates rows that
need converting to outbound pokes, but does not indicate whether the
conversion has already taken place.
Closes #14037.
Signed-off-by: …

Track unconverted device list outbound pokes using a position instead

---

.editorconfig
changelog.d/14526.misc

The current configuration might cause some editors to misbehave when editing stub files.

Apply correct editorconfig to .pyi files

---

changelog.d/14527.misc
synapse/storage/databases/state/bg_updates.py

Optimize `filter_events_for_client` for faster `/messages`. Seems like it will make it a magnitude faster. As discussed at https://github.com/matrix-org/synapse/pull/14494#discussion_r1028806102 (which was a v1 of this PR)
Fix https://github.com/matrix-org/synapse/issues/14108
Part of https://github.com/matrix-org/synapse/issues/13356#issuecomment-1272149596
Previous optimizations:
- https://github.com/matrix-org/synapse/pull/7567
- A v1 attempt of this PR: https://github.com/matrix-org/synapse/pull/14494
---
Grabbing all of the state via `get_state_for_events` is the longest part of `filter_events_for_client`
- `filter_events_for_client`
- `get_state_for_events`
- `get_state_group_for_events`
-  `_get_state_group_for_events`
- `_get_state_for_groups`
- `_get_state_for_groups_using_cache` …

Optimize `filter_events_for_client` for faster `/messages` - v2

---

changelog.d/14529.misc
mypy.ini
tests/util/caches/test_cached_call.py
tests/util/caches/test_deferred_cache.py
tests/util/caches/test_descriptors.py
tests/util/caches/test_response_cache.py
tests/util/caches/test_ttlcache.py

Just a minor clean-up of types.
I have the remaining types for `test_descriptors` separate because it got very messy.

Add missing type hints to test.util.caches

---

changelog.d/14534.misc
synapse/storage/databases/main/devices.py
synapse/storage/schema/main/delta/73/13add_device_lists_index.sql

This helps avoid reading unnecessarily large amounts of data from the table when querying with a set of room IDs.

Add another index to `device_lists_changes_in_room`

---

changelog.d/14515.misc
synapse/handlers/event_auth.py

Follow up to #14404.
If `allow_partial_state_rooms` is specified we use the servers list received on `send_join` (potentially updated with received membership events) instead of using the membership events only to check that we can send events to a server.

Faster joins: use servers list approximation in `assert_host_in_room`

---

changelog.d/14149.bugfix
synapse/handlers/pagination.py
synapse/streams/events.py
tests/rest/admin/test_room.py

Include unit tests for forward and backward pagination of room messages.
Fixes #12383 .

Implement message forward pagination from start when no from is given, fixes #12383

---

changelog.d/14469.misc
synapse/storage/database.py
synapse/storage/databases/main/account_data.py
synapse/storage/databases/main/appservice.py
synapse/storage/databases/main/devices.py
synapse/storage/databases/main/event_federation.py
synapse/storage/databases/main/pusher.py
synapse/storage/databases/main/room.py
synapse/storage/databases/main/room_batch.py
synapse/storage/databases/main/user_directory.py

To perform an emulated upsert into a table safely, we must either:
* lock the table,
* be the only writer upserting into the table
* or rely on another unique index being present.
When the 2nd or 3rd cases were applicable, we previously avoided locking
the table as an optimization. However, as seen in #14406, it is easy to
slip up when adding new schema deltas and corrupt the database.
The only time we lock when performing emulated upserts is while waiting
for background updates on postgres. On sqlite, we do no locking at all.
Let's remove the option to skip locking tables, so that we don't shoot
ourselves in the foot again.
---
Originally suggested by @DMRobertson.

Remove option to skip locking of tables during emulated upserts

---

changelog.d/14466.bugfix
synapse/federation/sender/per_destination_queue.py
synapse/handlers/receipts.py
tests/federation/test_federation_sender.py

Send the thread ID as part of the receipt meta data over federation.
This gets a bit complicated since the same room / receipt type / user could appear multiple times with different thread IDs and we don't want to stomp over each other. To avoid this we send them as separate EDUs.
Fixes #14459
This was missed as part of #12550 somehow.

Include thread information when sending receipts over federation.

---

changelog.d/14574.bugfix
synapse/metrics/common_usage_metrics.py

`setup()` is run under the sentinel context manager, so we wrap the
initial update in a background process. Before this change, Synapse
would log two warnings on startup:
Starting db txn 'count_daily_users' from sentinel context
Starting db connection from sentinel context: metrics will be lost
---
Noticed while debugging complement flakes.

Fix logging context warnings due to common usage metrics setup

---

changelog.d/14575.misc
synapse/handlers/message.py

This PR renames a variable in `create_new_client_event` which potentially clashes with a same-named parameter of the function. It seems unlikely that they would clash but I figured it should be fixed just in case as the fix is easy.

Fix possible variable shadow in `create_new_client_event`

---

synapse/storage/databases/main/devices.py

Oversight in #14038? @erikjohnston

Fix `UndefinedColumn: column "key_json" does not exist` errors when handling users with more than 50 non-E2E devices

---

changelog.d/14576.feature
synapse/rest/client/versions.py

Fixes #14486, see https://matrix.org/blog/2022/11/17/matrix-v-1-5-release. I think everything is supported here so this isn't much to do.

Advertise support for Matrix v1.5.

---

changelog.d/14582.bugfix
synapse/handlers/device.py
synapse/storage/databases/main/devices.py
tests/handlers/test_device.py
tests/storage/test_client_ips.py

This reverts commits c7e29ca277cf60bfdc488b93f4321b046fa6b46f and e860316818da4bd643d567708adb8d104f4a3351.
Deploying #14038 to matrix.org caused https://status.matrix.org/incidents/3rkqhtqpt4d9 because the database connection pool was saturated.
We do want to prune old devices (and limit the max number of devices more generally) but we probably need to do the pruning carefully, e.g. in a background task queue of some sort.
For now, revert it so that we can release 1.73 RCs.

Revert "POC delete stale non-e2e devices for users (#14038)"

---

changelog.d/14490.feature
changelog.d/14490.misc
changelog.d/14525.feature
synapse/crypto/keyring.py
tests/crypto/test_keyring.py
tests/rest/key/v2/test_remote_key_resource.py

Stop using deprecated `keyIds` param on /key/v2/server

---

changelog.d/14549.misc
synapse/federation/sender/__init__.py
tests/federation/test_federation_sender.py

Currently sending read receipts to the federation is waiting for the full state, while it doesn't seem necessary.
This PR uses the partial state servers list approximation instead.
Worst case we would only send local read receipts to dodgy servers so this is deemed acceptable.

Use servers list approx to send read receipts when in partial state

---

changelog.d/14517.doc
docs/setup/installation.md

And add drive-by links to downstream packages while I'm here.
See https://pr14517--synapse-docs-previews.netlify.app/setup/installation.html#downstream-debian-packages for a demo.

Cite launchpad bug that says ubuntu's pkgs are old

---

changelog.d/14551.feature
docs/usage/configuration/config_documentation.md
synapse/config/push.py
synapse/push/bulk_push_rule_evaluator.py
tests/push/test_bulk_push_rule_evaluator.py

Fixes https://github.com/matrix-org/synapse/issues/9524
This should short circuit calls to generate push notifications, for homeservers which don't make practical use of them. This is intended for the likes of things like t2bot.io and libera.chat.

Add `push.enabled` option to disable push notification calculation

---

changelog.d/14597.misc
mypy.ini
tests/util/test_async_helpers.py
tests/util/test_batching_queue.py
tests/util/test_check_dependencies.py
tests/util/test_dict_cache.py
tests/util/test_expiring_cache.py
tests/util/test_file_consumer.py
tests/util/test_itertools.py
tests/util/test_logcontext.py
tests/util/test_logformatter.py
tests/util/test_lrucache.py
tests/util/test_macaroons.py
tests/util/test_ratelimitutils.py
tests/util/test_retryutils.py
tests/util/test_rwlock.py
tests/util/test_stream_change_cache.py
tests/util/test_stringutils.py
tests/util/test_threepids.py
tests/util/test_treecache.py
tests/util/test_wheel_timer.py

Should be reviewable commit-by-commit. First I did the files which were completely ignored, then I went back and fixed the remaining files to be fully typed.

Add missing types to tests.util.

---

.github/workflows/tests.yml
changelog.d/14602.misc
rust/benches/evaluator.rs
rust/src/push/evaluator.rs

We weren't correctly reporting warnings as errors.

Fix Rust lint CI

---

.ci/scripts/setup_complement_prerequisites.sh
changelog.d/14611.misc

```
go get: installing executables with 'go get' in module mode is deprecated.
Use 'go install pkg@version' instead.
For more information, see https://golang.org/doc/go-get-install-deprecation
or run 'go help get' or 'go help install'.
```
So, this is coming. And it's been in the logs for a long time now. Simple change from `go get` to `go install`. [Quick link](https://golang.org/doc/go-get-install-deprecation) to the address given in the log message.

Handle 'go get' deprecation

---

changelog.d/14600.bugfix
synapse/rest/client/room.py

We've already decided to allow empty bodies for backwards compat. The change here stops us from emitting a misleading warning; see also https://github.com/matrix-org/synapse/issues/14478#issuecomment-1319157105

Suppress empty body warnings in room servelets

---

changelog.d/14619.doc
docs/usage/configuration/config_documentation.md

Found this when I went to deploy.

Fix push.enabled config documentation

---

changelog.d/14598.feature
synapse/api/constants.py
synapse/federation/sender/per_destination_queue.py
synapse/handlers/appservice.py
synapse/handlers/devicemessage.py
synapse/handlers/sync.py
synapse/logging/opentracing.py
synapse/rest/client/sendtodevice.py
synapse/storage/databases/main/deviceinbox.py
tests/handlers/test_appservice.py

A batch of changes intended to make it easier to trace to-device messages through the system.
The intention here is that a client can set a property `org.matrix.msgid` in any to-device message it sends. That ID is then included in any tracing or logging related to the message.  (Suggestions as to where this field should be documented welcome. I'm not enthusiastic about speccing it - it's very much an optional extra to help with debugging.)
I've also generally improved the data we send to opentracing for these messages.
Suggest reviewing commit-by-commit.
Part of https://github.com/vector-im/element-meta/issues/558.
If you know the message id (eg, from a client rageshake), the Jaeger spans can be found by searching for a tag such as `to_device.msgid=8ea835d3-0470-4f74-aa75-9ccd2521f194`. …

Improve logging and opentracing for to-device message handling

---

changelog.d/14620.bugfix
synapse/federation/federation_client.py

Implement the client side of MSC3743 over federation APIs: treat a spec-compliant homeserver which returns a `404`/`405` with an errcode of `M_UNRECOGNIZED` as not implementing an endpoint.
Split out of #14605
Part of #14599.

Failover on proper error responses.

---

changelog.d/14631.bugfix
synapse/rest/client/user_directory.py
synapse/storage/databases/main/user_directory.py
tests/storage/test_user_directory.py

Fixes: #10840 
This is a very quick drive-by fix because I noticed someone running into it in a client dev room.
This pull request is commit-by-commit review friendly. 
<ol>
<li>
Respect the limit in the return of the user directory 
</li>
<li>
Add a test to ensure this doesn't happen again 
</li>
<li>
Clamp `limit` because it would be janky for negative numbers to slice backwards in the array 
</li>
</ol>

Fix a long-standing bug where the user directory would return 1 more row than requested.

---

changelog.d/14634.doc
docs/turn-howto.md

When running yamllint on homeserver.yaml, I got an error because `turn_allow_guests` was `True` instead of its lowercase value. Changed the value based on [truthy](https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.truthy) instructions. 
(run the …

Change `turn_allow_guests` example value to lowercase `true`

---

changelog.d/14636.misc
docker/Dockerfile

This removes cargo install made with `apt`, since we fetch a recent Rust toolchain using `rustup` later on in the build process.

docker: remove useless cargo install with apt

---

changelog.d/14548.misc
docker/Dockerfile-workers
docker/complement/Dockerfile
docker/editable.Dockerfile
scripts-dev/complement.sh

This PR adds an `--editable` flag to `complement.sh`, which you can use during development.
The image is automatically rebuilt if the Rust source changes or the Poetry lockfile changes.
The initial image rebuild takes a long time but for subsequent runs, the Synapse source code is mounted into the container whilst running Complement and this means there's no need to rebuild a Docker image to only change Synapse's Python code.
Related: #13204
This pull request is commit-by-commit review friendly. 
<ol>
<li>
Allow Dockerfile-workers and complement/Dockerfile to use any FROM 
</li>
<li>
Add a Dockerfile for building editable install of Synapse 
</li>
<li>
Add an --editable flag to complement.sh 
</li>
</ol>

Add `--editable` flag to `complement.sh` which uses an editable install of Synapse for faster turn-around times whilst developing iteratively.

---

.github/workflows/tests.yml
changelog.d/14610.misc

A few small changes that allow the unit tests to exercise more of the full power of the hardware they are running on.
1. Postgres data files by default are written inside the docker container as a layer on top of the container file system. This can add up in latency if the underlaying filesystem on Github doesn't support Copy-on-write(but it probably does). Remove this abstraction layer by mounting those files on a [tmpfs](https://docs.docker.com/engine/reference/commandline/run/#mount-tmpfs---tmpfs) filesystem inside the docker instead. Bonus: tmpfs has less complex data structures and a much simpler filesystem layout, and doesn't have to deal with the added latency of a fsync operation on a(potentially) external device like a hard drive.
2. Postgres exposes a unix socket for …

Unit tests CI speedup

---

changelog.d/14639.bugfix
synapse/util/caches/stream_change_cache.py
tests/util/test_stream_change_cache.py

If the stream position is at/earlier than the earliest known stream position, but the cache is empty we should still consider entities to have changed.

Check the stream position before checking if the cache is empty.

---

changelog.d/14643.bugfix
synapse/storage/schema/main/delta/73/22_rebuild_user_dir_stats.sql

Due to #14435, #14592, and #14639 I was curious if these tables were actually of date.
I ran the following on matrix.org to see if any room names in `room_stats_state` were different from `current_state_events`:
```sql
SELECT room_id, event_id, name AS stats_name, json::json->'content'->>'name' AS json_name
FROM current_state_events
INNER JOIN event_json USING (event_id, room_id)
INNER JOIN room_stats_state USING (room_id)
WHERE
type = 'm.room.name' AND state_key = ''
AND name != json::json->'content'->>'name';
```
(This returned results, I limited it to 3 since I didn't see any reason to get a full list.)
Thus, we should likely rebuild the tables which are affected by the state delta processing. To my knowledge this is just the user directory and user / room stats.

Rebuild the user directory and stats tables.

---

changelog.d/14649.misc
synapse/handlers/device.py
synapse/storage/databases/main/devices.py
tests/handlers/test_device.py

Limit the number of devices we delete at once

---

changelog.d/14650.bugfix
synapse/storage/background_updates.py
synapse/storage/databases/main/receipts.py

When Synapse is terminated while running the background update to create
the `receipts_graph` or `receipts_linearized` indexes, the indexes may
be successfully created (or marked as invalid on postgres) while the
background update remains unfinished. When Synapse next starts up, the
background update will fail because the index already exists, or exists
but is invalid on postgres.
Use the existing code to create indices in background updates, since it
handles these edge cases.
---
Follows on from #14453.

Handle half-created indices in receipts index background update

---

changelog.d/14670.bugfix
synapse/appservice/__init__.py

#11915 introduced the `@cached` `is_interested_in_room` method in
Synapse 1.55.0, which depends upon `get_aliases_for_room`. Add a missing
cache invalidation callback so that the `is_interested_in_room` cache is
invalidated when `get_aliases_for_room` is invalidated.
#13787 made `get_rooms_for_user` `@cached`. Add a missing cache
invalidation callback so that the `is_interested_in_presence` cache is
invalidated when `get_rooms_for_user` is invalidated.

Fix missing cache invalidation in application service code

---

changelog.d/14671.misc
mypy.ini
scripts-dev/release.py
synapse/storage/database.py
synapse/storage/engines/postgres.py

Doesn't do much but helps me sleep better at night.

Enable `--warn-redundant-casts` option in mypy

---

changelog.d/14644.bugfix
contrib/grafana/synapse.json

Fixes: #14622 
Introduced in #14477; copied over from our Grafana where someone must have made this well-intentioned change without knowing that this isn't portable (and perhaps not even knowing that we export our Grafana dashboard into the Synapse repository).
<ol>
<li>
Remove job~= condition and aggregate with max() \
The job~= condition is not portable: it depends on how we do things on EMS and matrix.org
Other people don't set up their job names the same way we do.
Therefore we can't rely on job~= and cut it out.
But doing that means that you end up with one trace per worker.
To avoid this being a problem, I propose we aggregate them with max() so we take the number from the
correct worker that is reporting MAU.
</li>
</ol>

Fix the *MAU Limits* section of the Grafana dashboard relying on a specific `job` name for the workers of a Synapse deployment.

---

changelog.d/14545.misc
synapse/handlers/federation_event.py
synapse/replication/tcp/streams/__init__.py
synapse/replication/tcp/streams/partial_state.py
synapse/storage/databases/main/events_worker.py
synapse/storage/databases/main/state.py
synapse/storage/schema/main/delta/73/22_un_partial_stated_event_stream.sql
synapse/storage/schema/main/delta/73/23_un_partial_stated_room_stream_seq.sql.postgres

Fixes: #14418 
Part of: #12994 
Base: `rei/frrj_streams_psr_unblock`
This pull request is intended for commit-by-commit review. 
<ol>
<li>
Add tables for un-partial-stated events stream 
</li>
<li>
Add an ID generator for un-partial-stated events stream 
</li>
<li>
Add update fetch txn for unPS-event stream 
</li>
<li>
Add un-partial-stated events stream 
</li>
<li>
Write to the un-partial-stated events stream when the event is un-partial-stated 
</li>
</ol>
| PR | Title | Status |  Merges Into  |
|:--:|:------|:-------|:-------------:|
|#14473|Faster remote room joins: stream the un-partial-stating of rooms over replication.|![](https://img.shields.io/github/pulls/detail/state/matrix-org/synapse/14473?label=Pending)|-|
|#14474|Faster remote …

Faster remote room joins: stream the un-partial-stating of events over replication. [rei:frrj/streams/unpsr]

---

changelog.d/14676.misc
synapse/state/__init__.py

if fetching a subset of state that is trusted during a partial join.
This makes the function consistent with others that take both a `state_filter` and an `await_full_state` bool. (As part of this I checked all other uses of `await_full_state`.)

Allow `compute_state_after_events` to use partial state

---

changelog.d/14674.doc
docs/usage/configuration/config_documentation.md

Fix `target_memory_usage` being used in the description for the actual `cache_autotune` sub-option `target_cache_memory_usage`.

Fix missing word in autotune sub-option description

---

changelog.d/14680.misc
mypy.ini
synapse/handlers/auth.py
tests/handlers/test_appservice.py
tests/handlers/test_cas.py
tests/handlers/test_directory.py
tests/handlers/test_e2e_room_keys.py
tests/handlers/test_federation.py
tests/handlers/test_federation_event.py
tests/handlers/test_message.py
tests/handlers/test_oidc.py
tests/handlers/test_password_providers.py
tests/handlers/test_presence.py
tests/handlers/test_profile.py
tests/handlers/test_receipts.py
tests/handlers/test_register.py
tests/handlers/test_room.py
tests/handlers/test_room_summary.py
tests/handlers/test_saml.py
tests/handlers/test_send_email.py
tests/handlers/test_stats.py
tests/handlers/test_sync.py

...and require type hints there.

Add missing type hints to tests.handlers.

---

changelog.d/14685.misc
synapse/util/caches/descriptors.py

`invalidate` bit me — I forgot to wrap my single arg in a tuple.
I noticed we can do slightly better on these type annotations. But notably I couldn't figure out how to convert it to `ParamSpec` to ensure the tuples passed are all correct — I'm not even sure it's possible. (I think ParamSpec can only be used within `Concatenate` (which can only prepend args) and you don't seem to be able to convert ParamSpec to a Tuple(?) -- or at least just using `FP.args` doesn't cause any type errors when called with the wrong things).
<ol>
<li>
Add type annotations for invalidate, invalidate_all, prefill 
</li>
</ol>

Improve type annotations for the helper methods on a `CachedFunction`.

---

changelog.d/14681.misc
mypy.ini
synapse/config/cache.py
synapse/util/caches/lrucache.py
tests/config/test___main__.py
tests/config/test_background_update.py
tests/config/test_base.py
tests/config/test_cache.py
tests/config/test_database.py
tests/config/test_generate.py
tests/config/test_load.py
tests/config/test_ratelimiting.py
tests/config/test_registration_config.py
tests/config/test_room_directory.py
tests/config/test_server.py
tests/config/test_tls.py
tests/config/test_util.py
tests/config/utils.py

Add missing type hints to tests.config.

---

changelog.d/14712.misc
docker/Dockerfile
docs/development/contributing_guide.md
docs/setup/installation.md
docs/upgrade.md

Fixes #14704.
Signed-off-by: Mathieu Velten <mathieuv@matrix.org>

Add release note and update doc regarding ICU

---

changelog.d/14720.misc
pyproject.toml

Develop's trial-olddeps is [currently failing](https://github.com/matrix-org/synapse/actions/runs/3749275354/jobs/6367704839) with:
```
Failed to build PyYAML
ERROR: Could not build wheels for PyYAML, which is required to install pyproject.toml-based projects
```
The actual error seems to be:
```
ext/_yaml.c:20800:21: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘exc_type’; did you mean ‘curexc_type’?
20800 |     *type = tstate->exc_type;
|                     ^~~~~~~~
|                     curexc_type
```
This matches the error of yaml/pyyaml#152 which says [they released PyYAML 3.13 to fix this](https://github.com/yaml/pyyaml/issues/152#issuecomment-402791014). (See [diff from 3.12](https://github.com/yaml/pyyaml/compare/3.12...3.13)).
Unfortunately I haven't been able …

Bump minimum pyyaml to 3.13.

---

changelog.d/14724.misc
synapse/handlers/sync.py

An extension to https://github.com/matrix-org/synapse/pull/14598, and related to https://github.com/vector-im/element-meta/issues/558.

Log to-device msgids when we return them over /sync

---

changelog.d/14730.doc
docs/usage/configuration/config_documentation.md

Fixes: #13384
no modification only movement
Signed-off-by: Dirk Klimpel [dirk@klimpel.org](mailto:dirk@klimpel.org)

Move `email` to Server section in config file documentation

---

changelog.d/14663.feature
synapse/module_api/__init__.py

As suggested in https://github.com/matrix-org/synapse/pull/14026#discussion_r1003324598
I've had a look at the parameters the internal `cached` method has, and concluded that the three that didn't sound too Synapse internals-ey and sounded helpful for modules to have are `max_entries`, `num_args` and `uncached_args`. I'm happy to revisit this list if folks think modules would benefit from having access to more controls (it's also worth nothing that it's easy to add support to more arguments of `synapse.util.caches.descriptors.cached` later on).

Add a `cached` helper to the module API

---

docs/reverse_proxy.md

The link above leads to an ERROR 404

Broken link "request_id_header"

---

changelog.d/14741.misc
scripts-dev/lint.sh

I find it distracting and I don't particularly like software checking for updates automatically, so I propose we quieten this.
Follows: #14633 
<ol>
<li>
Suppress update check in ruff 
</li>
</ol>

Suppress the update check in the ruff linter.

---

changelog.d/14751.bugfix
synapse/handlers/oidc.py

This seems like a bug in #13917, related to #9357.
The default mapping provider allowed a `picture_claim` to be configured, but it was not used.

Actually use the picture_claim as configured in OIDC config.

---

changelog.d/14714.feature
docker/complement/conf/workers-shared-extra.yaml.j2
scripts-dev/complement.sh
synapse/config/experimental.py
synapse/handlers/account_data.py
synapse/replication/http/account_data.py
synapse/rest/client/account_data.py
synapse/storage/database.py
synapse/storage/databases/main/account_data.py

This PR adds experimental support for MSC3391. It implements the "Base behaviour" section of https://github.com/matrix-org/synapse/issues/14244. This means that while account data is deleted from the client's perspective, entries are not removed from the database. Doing so (the "Permanently deleting items from the account data stream" section of the same issue) will come in a later PR - this one was big enough!
Paired with Complement tests at https://github.com/matrix-org/complement/pull/574
Reviewers are encouraged to read MSC3391, then the implementation plan in #14244, before then reviewing commit-by-commit.

Add experimental support for MSC3391: deleting account data

---

changelog.d/14723.bugfix
synapse/replication/tcp/client.py
synapse/storage/_base.py
synapse/storage/databases/main/account_data.py
synapse/storage/databases/main/cache.py
synapse/storage/databases/main/deviceinbox.py
synapse/storage/databases/main/devices.py
synapse/storage/databases/main/events_worker.py
synapse/storage/databases/main/presence.py
synapse/storage/databases/main/push_rule.py
synapse/storage/databases/main/pusher.py
synapse/storage/databases/main/receipts.py
synapse/storage/databases/main/tags.py

This creates a new store method, `process_replication_position` that is called after `process_replication_rows`. By moving stream ID advances here this guarantees any relevant cache invalidations will have been applied before the stream is advanced.
This avoids race conditions where Python switches between threads (used by twisted for db txns) mid way through processing the `process_replication_rows` method where stream IDs may be advanced before caches are invalidated due to class resolution ordering.
See this comment/issue for further discussion: https://github.com/matrix-org/synapse/issues/14158#issuecomment-1344048703
Signed off by Nick @ Beeper (@Fizzadar).

Update all stream IDs after processing replication rows

---

.github/workflows/dependabot_changelog.yml
changelog.d/14772.misc

This is best practice for avoiding shell injection stuff, though given this is already locked down to only dependabot it shouldn't be an issue.
c.f. https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#example-of-a-script-injection-attack

Use env vars in GHA dependabot changelog

---

changelog.d/14744.doc
docs/admin_api/account_validity.md
docs/admin_api/event_reports.md
docs/admin_api/media_admin_api.md
docs/admin_api/purge_history_api.md
docs/admin_api/room_membership.md
docs/admin_api/rooms.md
docs/admin_api/statistics.md
docs/admin_api/user_admin_api.md
docs/development/contributing_guide.md
docs/modules/writing_a_module.md
docs/openid.md
docs/postgres.md
docs/setup/installation.md
docs/sso_mapping_providers.md
docs/upgrade.md
docs/usage/administration/admin_api/README.md
docs/usage/administration/admin_api/federation.md
docs/usage/administration/admin_api/registration_tokens.md
docs/usage/administration/admin_faq.md
docs/usage/administration/monitoring/reporting_homeserver_usage_statistics.md
docs/usage/administration/request_log.md
docs/usage/configuration/config_documentation.md
docs/workers.md

<ol>
<li>
Fix stale external links 
</li>
<li>
Fix some internal links 
</li>
<li>
Fix URLs without trailing / where needed 
</li>
<li>
Fix more links 
</li>
</ol>

Fix broken links in the Synapse documentation.

---

.github/workflows/docs-pr.yaml
changelog.d/14743.misc

Base: `rei/docs_links_fix`
<ol>
<li>
Add htmltest to check links in the documentation 
</li>
</ol>

Use `htmltest` to check links in the Synapse documentation.

---

changelog.d/14786.feature
synapse/api/filtering.py
synapse/handlers/search.py
synapse/handlers/sync.py

This has two related fixes:
* It enables fast-path processing for an empty filter (`[]`) which was previously only used for wildcard not-filters (`"*"`), e.g. it treats a filter like `{"types": []}` equivalent to `{"not_types": ["*"]}`. The spec isn't really clear if this is meant to be the same (see matrix-org/matrix-spec#1312), but empirically they do the same thing in Synapse today, except that in the empty filter case we would pull all data from the database to disregard it.
* It special cases a `/sync` filter with no-rooms to skip all room processing, previously we would partially skip processing, but would generally still calculate state for each room.
Things it does *not* do:
* We still generate per-room account data (to throw away).
* It does not try to make improvements to other …

Improve /sync performance of when passing filters with empty arrays

---

changelog.d/14727.bugfix
changelog.d/14727.misc
synapse/push/clientformat.py

Signed-off-by: Jeyachandran.rathnam [jeyrathnam@proton.me](mailto:jeyrathnam@proton.me)
Fixes #12482 

Remove undocumented device from pushrules

---

.github/workflows/release-artifacts.yml
changelog.d/14802.misc

The `build_wheel` CI job broke on develop when running tests against the built `pypy37-manylinux-x86_64` wheel. This was due to the `cryptography` package dropping support for OpenSSL 1.x.y [as of v39.0.0](https://cryptography.io/en/latest/changelog/#v39-0-0).
The container that `cibuildwheel` pulls and spins up ([`manylinux2014`](https://github.com/pypa/manylinux#manylinux) aka CentOS 7) does not come with OpenSSL 3.x.y, which causes the tests to fail. The wheel is still built successfully however, so downstream users will not be affected as long as they have OpenSSL 3.x.y and other dependencies available on their system.
A proper solution here is to run tests for our wheels on a more modern distribution - we're currently skipping testing a few different configurations (as shown in the …

Skip testing pypy-3.7-linux wheels as we don't have openssl 3.x on manylinux2014

---

changelog.d/14748.doc
docs/usage/configuration/config_documentation.md
docs/workers.md

Add missing worker settings to shared configuration

---

changelog.d/14716.misc
synapse/handlers/device.py
synapse/handlers/devicemessage.py
synapse/handlers/e2e_keys.py
synapse/handlers/federation_event.py
synapse/replication/http/devices.py
synapse/storage/databases/main/devices.py
synapse/types/__init__.py
synapse/util/async_helpers.py

We currently make one replication request per user we want to resync.
This batches those up into one request per destination (in the hopes that doing it this way will simplify sharding later).
Also limit the concurrency to 10 rather than number of destinations, for somewhat fairer processing.
---
Intending to put this on matrix.org, then later polish up for release?
<ol>
<li>
Build a set of who we are interested in first and foremost 
</li>
<li>
Add log lines 
</li>
<li>
Add async helpers 
</li>
<li>
Limit query_devices_for_destination to 10 concurrent invocations 
</li>
<li>
Add multi-user device resync in handler 
</li>
<li>
Add a replication servlet for multi-user device resync 
</li>
<li>
Use assertions to ensure we don't …

Batch up replication requests to request the resyncing of remote users's devices.

---

changelog.d/14811.feature
synapse/config/experimental.py
synapse/events/utils.py
synapse/server.py
tests/rest/client/test_relations.py

Two parts to this:
* Bundle the *whole* of the replacement with any edited events. This is backwards-compatible so I haven't put it behind a flag.
* Optionally, inhibit server-side replacement of edited events. This has scope to break things, so it is currently disabled by default.

Implement MSC3925: changes to bundling of edits

---

changelog.d/14803.doc
docs/usage/administration/request_log.md
docs/usage/configuration/config_documentation.md

Add `tag` to `listeners` documentation

---

.gitignore
changelog.d/14807.misc

Did you know that `poetry` has [lots of configuration options](https://python-poetry.org/docs/configuration/)? You can use `poetry config ...` to set them, and if you add the `--local` flag then changes are written to a `poetry.toml` file in the local checkout.
The poetry config docs (above link) explicitly recommend not checking these into source control, as they will then apply to all users, which is typically undesirable.
This commits add `/poetry.toml` to `.gitignore`, such that any local poetry config files are automatically ignored by git.

Add poetry.toml to .gitignore

---

changelog.d/14747.feature
docs/usage/configuration/config_documentation.md
synapse/app/generic_worker.py
synapse/app/homeserver.py

Fixes: #8780
Document the http `listener` `health`.
This actually corresponds to the statement of no resource name. But I think a documented `health` is clearer and has the chance for further development in the future.
Similar to / same like:
```yaml
- port: 10000
type: http
bind_addresses: ['::1', '127.0.0.1']
```
Clearer:
```yaml
- port: 10000
type: http
bind_addresses: ['::1', '127.0.0.1']
resources:
- names: [health]
```
- Feel free to …

Add listener `health`

---

changelog.d/14810.bugfix
synapse/api/filtering.py
synapse/handlers/sync.py

#14786 was overly ambitious -- the results of `_generate_sync_entry_for_rooms` is used to calculate device lists as an input to `_generate_sync_entry_for_device_list` (by looking through the events of joined / left rooms to see who has joined / left).

Calculate rooms changed for device lists to work.

---

changelog.d/14799.bugfix
synapse/storage/databases/main/events_bg_updates.py
synapse/storage/schema/main/delta/73/24_events_jump_to_date_index.sql

Follows: #9445, #14215 
<ol>
<li>
Add index to `events` table to help with 'jump to date' \
Before
```sql
synapse=> explain             SELECT event_id FROM events
LEFT JOIN rejections USING (event_id)
WHERE
room_id = '!...:matrix.org'
AND origin_server_ts <= 1620172800000
/**
* Make sure the event isn't an `outlier` because we have no way
* to later check whether it's next to a gap. `outliers` do not
* have entries in the `event_edges`, `event_forward_extremeties`,
* and `event_backward_extremities` tables to check against
* (used by `is_event_next_to_backward_gap` and `is_event_next_to_forward_gap`).
*/
AND NOT outlier
/* Make sure event is not rejected */
AND rejections.event_id IS NULL
/**
* First sort by the message …
```

Add index to improve performance of the `/timestamp_to_event` endpoint used for jumping to a specific date in the timeline of a room.

---

changelog.d/14816.misc
mypy.ini
stubs/synapse/synapse_rust/push.pyi
tests/push/test_email.py
tests/push/test_http.py
tests/push/test_presentable_names.py
tests/push/test_push_rule_evaluator.py

Some of these files were ignored and it was easy enough to require type defs.

Fix-up type hints for tests.push

---

changelog.d/14749.misc
synapse/handlers/message.py

Fixes: Complement `TestPartialStateJoin/CanSendEventsDuringPartialStateJoin` under `WORKERS=1` 
Follows: #14403 
Part of: #12994 
<ol>
<li>
Don't block for full state to cache hosts in room when sending events 
</li>
</ol>

Faster remote room joins (worker mode): do not populate external hosts-in-room cache when sending events as this requires blocking for full state.

---

changelog.d/14629.feature
synapse/module_api/__init__.py
tests/module_api/test_api.py

Add `set_displayname` to the module API

---

changelog.d/14817.bugfix
synapse/storage/databases/main/stream.py

Fix race calling `/members?at=`

---

changelog.d/14821.misc
pyproject.toml
stubs/sortedcontainers/sortedlist.pyi
stubs/sortedcontainers/sortedset.pyi
stubs/synapse/synapse_rust/push.pyi
synapse/config/_base.pyi
tests/storage/test_event_push_actions.py

Re-enable some linting

---

changelog.d/14822.misc
scripts-dev/lint.sh

This PR:
* Adds the `cargo clippy` and `cargo fmt` commands to the linting script.
* Adds comments with a brief description for the existing commands.
These should roughly match what's run in CI ([clippy](https://github.com/matrix-org/synapse/blob/f4d2a734f977c0a88f3a5fcdea38b7f9490481dc/.github/workflows/tests.yml#L112), [fmt](https://github.com/matrix-org/synapse/blob/f4d2a734f977c0a88f3a5fcdea38b7f9490481dc/.github/workflows/tests.yml#L154)).
The `clippy` command required some finesse for two reasons:
1. `clippy` may be configured to check benchmark code by default on some distributions (nixpkgs). Doing so on a stable Rust channel will yield an `#![feature]` may not be used on the stable release channel` on the files in `rust/benches/`. We can explicitly specify `--bins, --examples, …

Add rust linting commands to `scripts-dev/lint.sh`

---

changelog.d/14812.bugfix
synapse/rest/client/register.py
synapse/server.py
synapse/util/ratelimitutils.py
tests/server.py
tests/util/test_ratelimitutils.py

When there are many synchronous requests waiting on a
`_PerHostRatelimiter`, each request will be started recursively just
after the previous request has completed. Under the right conditions,
this leads to stack exhaustion.
A common way for requests to become synchronous is when the remote
client disconnects early, because the homeserver is overloaded and slow
to respond.
Avoid stack exhaustion under these conditions by deferring subsequent
requests until the next reactor tick.
Fixes #14480.

Fix stack overflow in `_PerHostRatelimiter` due to synchronous requests

---

changelog.d/14804.misc
synapse/crypto/keyring.py

This caused me a great deal of confusion both back when writing https://github.com/matrix-org/synapse/issues/12767 and now. I've added some clarifying comments and refactoring some of the logic in the `Keyring` class.
Logic should not have changed, but please double-check. Closes https://github.com/matrix-org/synapse/issues/12767.

Add some clarifying comments and refactor a portion of the `Keyring` class for readability

---

changelog.d/14832.misc
synapse/federation/federation_server.py
synapse/federation/transport/client.py
synapse/federation/transport/server/federation.py
tests/federation/test_federation_server.py
tests/federation/transport/test_client.py

Fixes #14828.
Synapse issue: https://github.com/matrix-org/synapse/issues/14828
Synapse PR: https://github.com/matrix-org/synapse/pull/14832
Complement PR: https://github.com/matrix-org/complement/pull/583
GMSL PR: https://github.com/matrix-org/gomatrixserverlib/pull/350
MSC: https://github.com/matrix-org/matrix-spec-proposals/pull/3706
Spec diff: https://github.com/matrix-org/matrix-spec/pull/1393

Use stable identifiers for faster joins

---

changelog.d/14841.misc
synapse/federation/federation_client.py
synapse/federation/federation_server.py
synapse/federation/transport/client.py
tests/federation/transport/test_client.py

follow-up to #14832
Sean [pointed out](https://matrix.to/#/!vcyiEtMVHIhWXcJAfl:sw1v.org/$SdA3tdegQxt8tOFAKwNPZGKLgHrNzbko-D0KpmTSrVc?via=matrix.org&via=element.io&via=beeper.com) that the response struct should mirror the spec, which I agree with. I haven't chased this through the rest of the source tree though---I don't think it'd be worth it.

Also use stable name in SendJoinResponse struct

---

changelog.d/14845.doc
docs/application_services.md

The [AS Configuration Snippet](https://matrix-org.github.io/synapse/latest/application_services.html) is missing `id` field, without it Synapse will fail to load:
```
synapse-synapse-main-0 synapse 2023-01-13 23:05:25,450 - synapse.storage.databases - 84 - INFO - main - [database config 'master']: Starting 'main' database
synapse-synapse-main-0 synapse 2023-01-13 23:05:25,452 - synapse.config.appservice - 79 - ERROR - main - Failed to load appservice from '/as/synapse-hookshot-as/registration.yaml'
synapse-synapse-main-0 synapse 2023-01-13 23:05:25,452 - synapse.config.appservice - 80 - ERROR - main - "Required string field: 'id' (/as/synapse-hookshot-as/registration.yaml)"
synapse-synapse-main-0 synapse Traceback (most recent call last):
synapse-synapse-main-0 synapse   File …
```

Fix missing field in AS documentation

---

changelog.d/14842.bugfix
synapse/rest/client/register.py
synapse/server.py
synapse/util/ratelimitutils.py
tests/util/test_ratelimitutils.py

Fix up #14812 to avoid introducing a reference to the reactor.

Remove unnecessary reactor reference from `_PerHostRatelimiter`

---

changelog.d/14855.misc
synapse/handlers/presence.py

This stops us from incrementing the presence stream position for no-op updates.

Add an early return when handling no-op presence updates.

---

changelog.d/14843.misc
synapse/federation/federation_client.py
synapse/federation/transport/client.py

When the local homeserver is already joined to a room and wants to
perform a remote join, we may find it useful to do a non-partial state
join if we already have the full state for the room.

Add parameter to control whether we do a faster join

---

changelog.d/14856.misc
synapse/replication/tcp/client.py
tests/replication/tcp/test_handler.py

We were incorrectly checking if the *local* token had been advanced, rather than the token for the remote instance.
In practice, I don't think this has caused any bugs due to where we use `wait_for_stream_position`, as critically we don't use it on instances that also write to the given streams (and so the local token will lag behind all remote tokens).

Fix bug in `wait_for_stream_position` 

---

changelog.d/14839.feature
docker/complement/conf/workers-shared-extra.yaml.j2
synapse/config/experimental.py
synapse/federation/transport/server/federation.py
tests/federation/test_federation_server.py

Fixes #14829.
Serving partial join responses is no longer experimental. They will only be served under the stable identifier if the the undocumented config flag `experimental.msc3706_enabled` is set to true.
Synapse continues to _request_ a partial join only if the undocumented config flag `experimental.faster_joins` is set to `true`; this setting remains present and unaffected.

Stabilise serving partial join responses

---

changelog.d/14864.bugfix
synapse/event_auth.py

Fixes a bug in #13220 when using frozen events.
Tested @ matrix-org/sytest#1328.

Properly check for frozendicts.

---

changelog.d/14872.misc
synapse/replication/tcp/client.py

This caused some requests to fail.
This really only started causing issues due to https://github.com/matrix-org/synapse/pull/14856

Fix bug in wait for stream position

---

changelog.d/14844.misc
synapse/handlers/federation.py
tests/handlers/test_federation.py

Currently, we will try to start a new partial state sync every time we
perform a remote join, which is undesirable if there is already one
running for a given room.
We intend to perform remote joins whenever additional local users wish
to join a partial state room, so let's ensure that we do not start more
than one concurrent partial state sync for any given room.
------------------------------------------------------------------------
There is a race condition where the homeserver leaves a room and later
rejoins while the partial state sync from the previous membership is
still running. There is no guarantee that the previous partial state
sync will process the latest join, so we restart it if needed.
---
Best reviewed commit by commit.

Faster joins: Avoid starting duplicate partial state syncs

---

changelog.d/14881.misc
synapse/replication/http/_base.py
synapse/replication/tcp/client.py

Now that we wait for stream positions whenever we do a HTTP replication hit, we need to be less brutal in the case where we do timeout (as we have bugs around this).

Reduce max time we wait for stream positions

---

changelog.d/14885.misc
mypy.ini
tests/api/test_ratelimiting.py

Fix some incorrect type hints by providing actual objects to arguments instead of `None`.

Add type hints to `TestRatelimiter`

---

changelog.d/14889.misc
mypy.ini
tests/server_notices/test_resource_limits_server_notices.py

Reviewable commit-by-commit. `invites` was just plainly the wrong type.

Fix type hints for Monthly Active Users tests

---

changelog.d/14882.bugfix
synapse/federation/federation_client.py
synapse/handlers/federation.py

When joining a restricted room where the local homeserver does not have
a user able to issue invites, we perform a second remote join. This
wasn't accounted for previously and we make a few fixes.
* We avoid clearing out forward extremities when the local homeserver is
already in the room. The forward extremities would already be up to
date and clearing them out creates a window in which the room can get
bricked if Synapse crashes.
* We perform a full join when doing a second remote join into a full
state room. Previously, we would always do a partial state join, which
would fail to be persisted into the room.
* We introduce a lock guarding the partial state flag for rooms. This
makes the remote join code a little easier to reason about.
* We avoid overwriting details about the partial …

Faster joins: Fix incompatibility with restricted joins

---

changelog.d/14874.bugfix
synapse/handlers/federation.py
synapse/replication/tcp/client.py
synapse/storage/controllers/state.py

When finishing a partial state join to a room, we update the current
state of the room without persisting additional events. Workers receive
notice of the current state update over replication, but neglect to wake
the room stats and user directory updaters, which then get incidentally
triggered the next time an event is persisted or an unrelated event
persister sends out a stream position update.
We wake the room stats and user directory updaters at the appropriate
time in this commit.
Part of #12814 and #12815.

Faster joins: Update room stats and the user directory on workers when finishing join

---

changelog.d/14873.bugfix
synapse/storage/databases/main/events_worker.py
synapse/storage/databases/main/stats.py
tests/storage/databases/main/test_room.py

If we fail to pull events from the database that we know the IDs of then somethign is wrong and there's really no hope of fixing these rooms. We skip them, leaving whatever stats data is already in place.
Fixes #14800

Skip processing stats for broken rooms.

---

changelog.d/14870.feature
synapse/handlers/federation.py
synapse/handlers/sync.py
synapse/notifier.py
synapse/replication/tcp/client.py
synapse/storage/databases/main/relations.py
synapse/storage/databases/main/room.py
synapse/storage/databases/main/roommember.py
synapse/streams/events.py
synapse/types/__init__.py
tests/rest/admin/test_room.py
tests/rest/client/test_rooms.py
tests/rest/client/test_sync.py

Based on #14831 by @MatMaul. Best reviewed commitwise.
See https://github.com/matrix-org/complement/pull/588 for testing.

Faster joins: omit partial rooms from eager syncs until the resync completes

---

changelog.d/14905.feature
docs/upgrade.md
synapse/config/experimental.py
synapse/storage/databases/main/stream.py

This is a little sloppy, but we are trying to gain confidence in faster joins in the upcoming RC.
Admins can still opt out by adding the following to their Synapse config:
```yaml
experimental:
faster_joins: false
```
We may revert this change before the release proper, depending on how testing in the wild goes.

Request partial joins by default

---

changelog.d/14883.doc
docs/usage/administration/admin_faq.md

Document the export user data command.

---

changelog.d/14910.bugfix
synapse/storage/engines/_base.py
synapse/storage/engines/sqlite.py

#13873 introduced a regression which causes sqlite database migrations
to no longer run inside a transaction. Wrap them in a transaction again,
to avoid database corruption when migrations are interrupted.
Fixes #14909.

Make sqlite database migrations transactional again

---

changelog.d/14912.misc
synapse/federation/transport/client.py

to allow faster joins resyncs the chance to complete for large rooms. We have seen this fair poorly (~90s for Matrix HQ's /state) in testing, causing the resync to advance to another HS who hasn't seen our join yet.
I'd like to see something cleverer "e.g. extend timeout as you receive data" but this is good enough for now.

Bump the client-side timeout for /state

---

changelog.d/14887.misc
mypy.ini
tests/federation/transport/test_knocking.py
tests/rest/client/test_sync.py
tests/unittest.py

This is my first type declaring a `Protocol` for type hinting, so hopefully I've done it right!

Fix type hints in knocking tests

---

changelog.d/14916.misc
docs/development/dependencies.md

Per the conversation I had with @DMRobertson: https://matrix.to/#/!vcyiEtMVHIhWXcJAfl:sw1v.org/$0Q06BIzItJuMIN7Zf6VMGaQOgJo3t44qAcT85OmAAIM?via=matrix.org&via=element.io&via=beeper.com

Document how to handle Dependabot pull requests.

---

changelog.d/14904.misc
mypy.ini
synapse/events/utils.py
tests/events/test_presence_router.py
tests/events/test_snapshot.py
tests/events/test_utils.py

Add missing type hints for tests.events

---

changelog.d/14880.bugfix
synapse/handlers/presence.py
synapse/module_api/__init__.py
synapse/notifier.py
synapse/streams/__init__.py
synapse/types/__init__.py

Reported at https://matrix.to/#/!vcyiEtMVHIhWXcJAfl:sw1v.org/$mG_v0O-a887V8k7WVH8VSA9VIagKQibmnNHew74k2PI?via=matrix.org&via=element.io&via=beeper.com
Part of #14809

Fix a bug in the send_local_online_presence_to module API

---

changelog.d/14886.misc
mypy.ini
synapse/server.py
tests/handlers/test_typing.py
tests/storage/test_user_directory.py
tests/unittest.py

Best to review commit-by-commit. Commits contain individual descriptions of changes.

Fix type hints in typing edu unit tests

---

changelog.d/14914.bugfix
synapse/storage/databases/main/devices.py

On startup, the `_device_list_id_gen` stream id generator is initialized
using the maximum stream id seen in a list of tables. When we started
populating the `device_list_remote_pending` table in #13913, we forgot
to add it to the aforementioned list of tables, so the stream id
generator can hand out old stream ids after a restart. The end result is
that Synapse can fail to handle device list update EDUs after a restart
when a partial state join is in progress.
Add the `device_list_remote_pending` table to the list of tables to
consider when initializing the `_device_list_id_gen` stream id generator.

Fix initialization of `_device_list_id_gen`

---

changelog.d/14917.misc
synapse/handlers/sync.py
synapse/storage/database.py
synapse/storage/databases/main/room.py

This should save some CPU time.
We might also want to increase the cache size on `is_partial_state_room`?

Batch look-ups to see if rooms are partial stated.

---

changelog.d/14922.misc
synapse/handlers/account_data.py
synapse/handlers/device.py
synapse/handlers/event_auth.py
synapse/handlers/federation.py
synapse/handlers/federation_event.py
synapse/handlers/pagination.py
synapse/handlers/room.py
synapse/handlers/room_summary.py
synapse/handlers/search.py
synapse/handlers/sso.py
synapse/handlers/sync.py
synapse/rest/client/push_rule.py

Related to #14809; we replace more instances of `Colletion[str]` and `Sequence[str]` with `StrCollection`.

Use StrCollection in place of Collection[str] in (most) handlers code.

---

changelog.d/14866.bugfix
synapse/storage/databases/main/relations.py
synapse/storage/databases/main/stream.py

The `/relations` endpoint was not properly handle "live tokens" (i.e sync tokens), to do this properly we abstract the code that `/messages` has and re-use it.
Tests at matrix-org/complement#586.
Fixes #14830
Related to #13862

Fix paginating /relations with a live token

---

changelog.d/14927.misc
synapse/api/constants.py
synapse/handlers/admin.py
synapse/handlers/initial_sync.py
synapse/handlers/pagination.py
synapse/handlers/relations.py
synapse/storage/databases/main/relations.py
synapse/storage/databases/main/stream.py
synapse/streams/config.py

For better static analysis, per https://github.com/matrix-org/synapse/pull/14866#discussion_r1088169647.

Use an enum for direction.

---

changelog.d/14677.doc
docs/SUMMARY.md
docs/development/synapse_architecture/faster_joins.md

I think this is substantial enough to start to be useful. Would appreciate thoughts from the team.
IDK if we want to fix this a bit but merge as-is and iterate?
See https://pr14677--synapse-docs-previews.netlify.app/development/synapse_architecture/faster_joins.html

Initial batch of notes on faster joins

---

changelog.d/14942.bugfix
synapse/push/bulk_push_rule_evaluator.py
tests/push/test_bulk_push_rule_evaluator.py
tests/test_event_auth.py

Commitwise-reviewable.
Should fix https://github.com/matrix-org/synapse/issues/14933. The problem is that a pre-v10 room has `{"notifications": {"room": null}}` in its power levels event content. The `null` becomes a `None` inside the Python interpreter. Then the logic which tries to handle stringy power levels falls over when computing `int(None)`.
I have implemented this assuming that the spec considers `{"notifications": {"room": null}}` to be acceptable and equivalent to `{"notifications": {}}`. I don't know if this is actually true; the OpenAPI definition is https://github.com/matrix-org/matrix-spec/blob/5f2fac89afdd02830099b5010e46724d905057d5/data/event-schemas/schema/m.room.power_levels.yaml#L88-L97. (`room` is not marked as `required`, but nor is it marked as `nullable`.)
But …

Handle malformed values of `notification.room` in power level events

---

changelog.d/14945.misc
synapse/config/_base.py
synapse/config/cache.py
synapse/config/server.py
synapse/events/validator.py
synapse/federation/federation_client.py
synapse/handlers/message.py
synapse/rest/admin/__init__.py
synapse/rest/admin/registration_tokens.py
synapse/rest/admin/users.py
synapse/rest/client/report_event.py
synapse/rest/media/v1/oembed.py
synapse/rest/media/v1/thumbnailer.py
synapse/storage/databases/main/events.py

We saw in https://github.com/matrix-org/synapse/pull/14940 that `issubclass(bool, int)`, which meant that a bunch of our hand-rolled validation that used `isinstance(..., int)` was permitting bools through.
Much like with #14944, this changeset explicitly inspects the type of an object wherever we were testing for `isinstance(x, int)`.
The two PRs cover every case I could see where `x` was user-controlled. Those remaining are:
```
$ rg -s 'isinstance.*[^_]int'
tests/replication/_base.py
576:        if isinstance(obj, int):
synapse/util/caches/stream_change_cache.py
136:        assert isinstance(stream_pos, int)
214:        assert isinstance(stream_pos, int)
246:        assert isinstance(stream_pos, int)
267:        assert isinstance(stream_pos, int) …
```

Prefer `type(x) is int` to `isinstance(x, int)`

---

changelog.d/14926.bugfix
synapse/storage/engines/_base.py
synapse/storage/engines/postgres.py
synapse/storage/engines/sqlite.py
tests/storage/test_database.py

#14910 fixed the regression introduced by #13873 where sqlite database
migrations would no longer run inside a transaction. However, it
committed the transaction before Synapse updated its bookkeeping of
which migrations have been run, which means that migrations may be run
again after they have completed successfully.
Leave the transaction open at the end of `executescript`, to restore the
old, correct behaviour. Also make the PostgreSQL behaviour consistent
with SQLite.
Fixes #14909.

Make sqlite database migrations transactional again, part two

---

changelog.d/14950.misc
synapse/federation/federation_server.py
synapse/logging/opentracing.py

Useful when using jaeger to retroactively profile.
Propose that we don't put this in the RC.

Tag /send_join responses to detect faster joins

---

.github/workflows/tests.yml
changelog.d/14943.feature
rust/benches/evaluator.rs

As #14823 broke it where I didn't update all the callers of `PushRuleEvaluator::py_new(...)`.
See https://github.com/matrix-org/synapse/actions/runs/4047992030/jobs/6962741368 for example output.

Ensure cargo bench still functions.

---

changelog.d/14957.feature
rust/src/push/base_rules.rs

Fixes a couple of oversights in #14823.
* Fixes the push rule IDs.
* Removes the sound tweak for room notifications.

Fix inconsistencies between MSC3952 and implementation.

---

changelog.d/14956.misc
synapse/federation/federation_client.py
synapse/federation/federation_server.py
synapse/federation/transport/client.py
synapse/federation/transport/server/federation.py
synapse/handlers/account_data.py
synapse/handlers/receipts.py
synapse/handlers/room.py
synapse/http/servlet.py
synapse/rest/admin/event_reports.py
synapse/rest/admin/federation.py
synapse/rest/admin/media.py
synapse/rest/admin/rooms.py
synapse/rest/admin/statistics.py
synapse/rest/admin/users.py
synapse/rest/client/relations.py
synapse/rest/client/room.py
synapse/storage/databases/main/__init__.py
synapse/storage/databases/main/events_worker.py
synapse/storage/databases/main/media_repository.py
synapse/storage/databases/main/room.py
synapse/storage/databases/main/stats.py
synapse/storage/databases/main/transactions.py
synapse/streams/config.py
tests/rest/admin/test_event_reports.py

As requested in https://github.com/matrix-org/synapse/pull/14927#pullrequestreview-1271937751 this uses the `Direction` `enum` in more places.
I split it into a few commits, but it is kind of hard to trace around the code-base. I was using the following to find things (and then looking at callers / callees):
```bash
pygrep -rE '"[bf]"' synapse
```

Add helper to parse an enum from query args & use it.

---

changelog.d/14965.misc
rust/Cargo.toml

I have linking errors when using `cargo test` or `cargo bench` locally. From the [pyo3 FAQs this is the suggested fix](https://pyo3.rs/v0.17.1/faq#i-cant-run-cargo-test-or-i-cant-build-in-a-cargo-workspace-im-having-linker-issues-like-symbol-not-found-or-undefined-reference-to-_pyexc_systemerror).
Everything now works if I run with the `--no-default-features` flag, e.g.:
```
cargo test --no-default-features
```
Spun out of #14964.

Make extension-module optional, but default.

---

changelog.d/14962.feature
synapse/storage/databases/main/roommember.py

This should hopefully improve the response time to serve a faster join, to persist an outgoing event, and probably other things too.

Fetch fewer events when getting hosts in room

---

changelog.d/14981.misc
synapse/push/bulk_push_rule_evaluator.py
tests/push/test_push_rule_evaluator.py

I pulled this out of #14964 since I want them for another PR (and to make that PR slightly smaller).

Add a docstring & tests for _flatten_dict.

---

changelog.d/14971.misc
synapse/push/bulk_push_rule_evaluator.py

Naughty, but should be a big speedup in large rooms. In particular this should make it quicker to (faster-) join and leave a room.

Only notify the target of a membership event

---

changelog.d/14992.misc
mypy.ini

Canonicaljson has included (properly-distributed) type hints since https://github.com/matrix-org/python-canonicaljson/pull/52, which is included in the canonicaljson present in the lockfile.

Expect type stubs from canonicaljson

---

changelog.d/14987.misc
mypy.ini
tests/replication/_base.py
tests/replication/http/test__base.py
tests/replication/slave/storage/_base.py
tests/replication/slave/storage/test_events.py
tests/replication/tcp/streams/test_account_data.py
tests/replication/tcp/streams/test_events.py
tests/replication/tcp/streams/test_federation.py
tests/replication/tcp/streams/test_partial_state.py
tests/replication/tcp/streams/test_typing.py
tests/replication/tcp/test_commands.py
tests/replication/tcp/test_remote_server_up.py
tests/replication/test_auth.py
tests/replication/test_client_reader_shard.py
tests/replication/test_federation_ack.py
tests/replication/test_federation_sender_shard.py
tests/replication/test_module_cache_invalidation.py
tests/replication/test_multi_media_repo.py
tests/replication/test_pusher_shard.py
tests/replication/test_sharded_event_persister.py

Requires types hints in `tests.replication`.

Add type hints to tests.replication

---

changelog.d/14949.misc
pyproject.toml

Following up from https://github.com/matrix-org/synapse/issues/14931
To force building with poetry-core-1.5.0, I ran the following on a fresh synapse checkout with the pr patch
```
#!/bin/bash
set -euxo pipefail
poetry install --no-root --extras "saml2 oidc url-preview redis test"
poetry add build installer poetry-core==1.5.0
poetry run python -m build --no-isolation --wheel
poetry run python -m installer --dest=$(poetry env info --path) --prefix=/ dist/matrix_synapse-*.whl
poetry run python -m twisted.trial --jobs=$(nproc) tests
poetry remove build installer poetry-core
```
Test summary `PASSED (skips=60, successes=2574)` with the following skipped categories
```
[SKIPPED]
`BaseFederationServlet` does not support cancellation yet.
[SKIPPED]
Requires Postgres
[SKIPPED]
Requires …
```

Allow poetry-core 1.5.0

---

changelog.d/14979.misc
synapse/storage/databases/main/events.py
synapse/storage/databases/main/events_bg_updates.py
synapse/storage/databases/main/events_worker.py
synapse/storage/schema/main/delta/73/26membership_tables_event_stream_ordering.sql

This adds an `event_stream_ordering` column to `current_state_events`, `local_current_membership` and `room_memberships`. Each of these tables is regularly joined with the `events` table to get the stream ordering and denormalising this into each table will yield significant query performance improvements once used. Includes a background job to populate these values from the `events` table.
Same idea as https://github.com/matrix-org/synapse/pull/13703 which has been a significant improvement on our database instance, suspect once applied this will be far greater.

Add `event_stream_ordering` column to membership state tables

---

changelog.d/14988.misc
mypy.ini
synapse/http/client.py
synapse/http/proxyagent.py
tests/http/__init__.py
tests/http/federation/test_matrix_federation_agent.py
tests/http/federation/test_srv_resolver.py
tests/http/server/_base.py
tests/http/test_additional_resource.py
tests/http/test_client.py
tests/http/test_endpoint.py
tests/http/test_matrixfederationclient.py
tests/http/test_proxyagent.py
tests/http/test_servlet.py
tests/http/test_simple_client.py
tests/http/test_site.py
tests/server.py

This wasn't too bad to get working in the end.

Properly typecheck types.http

---

changelog.d/15002.misc
synapse/push/bulk_push_rule_evaluator.py
tests/push/test_push_rule_evaluator.py

As was asked for in https://github.com/matrix-org/synapse/pull/14981#discussion_r1095990509
They were easier than expected, should have just done it in that PR. Sorry for the churn!

Add tests for using _flatten_dict with an event.

---

changelog.d/15016.feature
rust/src/push/base_rules.rs

Per @richvdh's comment: https://github.com/matrix-org/synapse/pull/14960#discussion_r1099037197
And to match what MSC3958 says.

Include no actions instead of dont_notify for suppressing edits.

---

.ci/scripts/auditwheel_wrapper.py
.github/workflows/release-artifacts.yml
changelog.d/15019.misc

A desperate attempt to make CI work again after #14949.
Tested in #15015.
My hypothesis is:
- poetry-core 1.3.2 builds a wheel that says it's for `macosx_10_16` under the CI env
- poetry-core 1.5.0 (maybe 1.4.0?) builds a wheel that says it's for `macosx_11_0` under the CI
- the version of pip in the CI env considers that not installable

Hacky fix to make mac wheels 

---

changelog.d/14959.doc
docs/delegate.md

This PR just clarifies in the SRV DNS delegation document that there are still cases a user may have to serve files from `.well-known`  endpoints, and this may not be a valid case for using SRV delegation. This has caused some confusion in a few cases.
Signed-off-by: William Kray <github@williamkray.com>
- Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the …

Clarify limitations of SRV delegation in documentation

---

changelog.d/15022.doc
docs/development/contributing_guide.md

I was trying to run Synapse today and couldn't remember how to do it. If I missed this information somewhere else, maybe a link from the contributing guide would be useful?
I'm not 100% sure what I've written here is right, but if it's not I still hope we can add something similar, because I got stuck at this point.
Signed-off-by: Andy Balaam <andy.balaam@matrix.org> …

Document how to run Synapse

---

changelog.d/15024.bugfix
synapse/replication/http/_base.py

Fixes exception:
```
Exception: ('data to send contains %r key', '_INT_STREAM_POS')
File "synapse/http/server.py", line 307, in _async_render_wrapper
File "synapse/http/server.py", line 513, in _async_render
File "synapse/replication/http/_base.py", line 442, in _check_auth_and_handle
raise Exception("data to send contains %r key", _STREAM_POSITION_KEY)
```
Introduced in #14820

Fix bug in replication where response is cached

---

changelog.d/15026.misc
mypy.ini

If mypy passes we can merge this.
My thought is that we now have an explicit list of things to "fix" and any newly added files will be opted in automatically to requiring type hints.

Explicit disabling of disallowed_untyped_defs.

---

changelog.d/15031.misc
mypy.ini
tests/events/test_presence_router.py
tests/module_api/test_api.py

Proper types for `tests.module_api`

---

changelog.d/15035.misc
mypy.ini
synapse/handlers/room.py
synapse/server.py
synapse/storage/_base.py
synapse/storage/database.py
synapse/storage/databases/main/events.py

I was finally able to figure out the right incantation here. It seems to have shook out some spots that were `Any`? I think?

Add final type hint to synapse.server.

---

changelog.d/15036.misc
synapse/storage/schema/__init__.py

This should have been included in
f10caa73eee0caa91cf373966104d1ededae2aee (and #14979).

Bump schema version

---

changelog.d/15038.bugfix
synapse/handlers/directory.py

Avoid mutating cached room aliases.

---

changelog.d/15033.misc
poetry.lock
pyproject.toml

0.0.237 includes a change (https://github.com/charliermarsh/ruff/pull/2293) to ruff's `pyproject.toml` which fixes a build error for me.
<details>
<summary>Click to view build error output</summary>
```
× Preparing metadata (pyproject.toml) did not run successfully.
│ exit code: 1
╰─> [8 lines of output]
💥 maturin failed
Caused by: Failed to parse Cargo.toml into python metadata
Caused by: Failed to read Readme specified in Cargo.toml, which should be at /tmp/pip-req-build-_a1wf8ok/ruff_cli/../README.md
Caused by: failed to open file `/tmp/pip-req-build-_a1wf8ok/ruff_cli/../README.md`
Caused by: No such file or directory (os error 2)
Error running maturin: Command '['maturin', 'pep517', 'write-dist-info', '--metadata-directory', '/tmp/pip-modern-metadata-c3qvdts1', '--interpreter', …
```

Bump ruff version from 0.0.230 to 0.0.237

---

changelog.d/14840.misc
synapse/storage/prepare_database.py

While running the unit tests locally and watching my postgres logs, I saw the following log line start to be emitted for every DB query that was being run:
```
2023-01-13 18:05:15.379 GMT [493791] WARNING:  there is already a transaction in progress
```
Which resulted in quite a lot of log lines, generating noise...
This warning is harmless, and is merely telling us that we've started a transaction (with `BEGIN`) and then started another one (with another `BEGIN`). Now this warning will only appear when we actually prepare a database for the first time (which we do all the time when running the unit tests, as each tests uses a separate database) or apply database migrations. 
So while on your actual homeserver you may see this warning pop up a couple times when you update Synapse, it …

Do not always start a db txn on Postgres

---

changelog.d/15042.feature
synapse/api/auth.py
synapse/logging/opentracing.py

Rich commented that we should do this, when we were looking at /send_join traces last week.
We already include such a tag for CSAPI requests in `get_user_by_req`; this includes a worker name tag in all traces by making it part of the tracer's configuration.
After:

Tag federation request spans with the worker name

---

changelog.d/15041.misc
synapse/storage/databases/main/devices.py

Fix exception on start up about device lists

---

changelog.d/15040.misc
synapse/handlers/e2e_keys.py
synapse/storage/databases/main/devices.py

Split from #13755.
This was mutating a cached value (in a confusing way), but only if the input was somewhat bogus data anyway. I refactored to avoid this situation.

Refactor get_user_devices_from_cache to avoid mutating cached values.

---

changelog.d/15047.misc
synapse/handlers/sync.py

---
Split out from https://github.com/matrix-org/synapse/pull/13755.

Avoid mutating cached values in `_generate_sync_entry_for_account_data`

---

changelog.d/14973.misc
synapse/api/filtering.py
synapse/handlers/account_data.py
synapse/handlers/initial_sync.py
synapse/handlers/room_member.py
synapse/handlers/sync.py
synapse/rest/admin/users.py
synapse/storage/databases/main/account_data.py

Currently we fetch global & room specific account data at once, but if we don't care about the room account data than we discard that data.
Regardless, it is confusing that we fetch those in a single place and then pass them around.
Follow-on to #14908.

Avoid fetching unused account data in sync

---

changelog.d/14964.feature
rust/benches/evaluator.rs
rust/src/push/evaluator.rs
rust/src/push/mod.rs
stubs/synapse/synapse_rust/push.pyi
synapse/config/experimental.py
synapse/push/bulk_push_rule_evaluator.py
synapse/types/__init__.py
tests/push/test_push_rule_evaluator.py

Supports [MSC3758](https://github.com/matrix-org/matrix-spec-proposals/pull/3758) the `exact_event_match` push condition which checks for equality when searching for a value in an event, instead of string globbing.

Support for MSC3758: exact_event_match push condition

---

changelog.d/15053.misc
synapse/handlers/auth.py
synapse/handlers/deactivate_account.py
synapse/handlers/identity.py
synapse/rest/client/account.py

This is just generally cleaner, and prevent footguns of modifying dict arguments, which are passed by reference.
Broken out from https://github.com/matrix-org/synapse/pull/15044.

Refactor arguments of `try_unbind_threepid(_with_id_server)` from dict to separate args

---

changelog.d/14980.misc
synapse/handlers/sync.py
synapse/storage/databases/main/event_push_actions.py

This is strictly a perf improvement, since we don't calculate push actions if `enable_push` config is false.

Skip calculating unread push actions in `/sync` when `enable_push` is false.

---

changelog.d/15069.misc
synapse/handlers/sync.py

...when lazy loading of members is not enabled. It's weird to notify
a client that another user's device list has changed when the client
doesn't think that they share a room.
Note that when a room is un-partial stated, device list updates are
emitted for every member in that room over /sync.

Faster joins: Omit device list updates from partial state rooms in /sync

---

changelog.d/15073.feature
rust/src/push/base_rules.rs

This does nothing and I want to remove it from the MSC.

Remove spurious `dont_notify` action from `.m.rule.reaction`

---

changelog.d/15068.bugfix
synapse/handlers/federation.py
synapse/storage/databases/main/purge_events.py

See also https://github.com/matrix-org/complement/pull/608
`partial_state_rooms` has an FK on `events` pointing to the join event we get from `/send_join`, so we must delete from that table before deleting from `events`.
**NB:** It would be nice to cancel any resync processes for the room being purged. We do not do this at present. To do so reliably we'd need an internal HTTP "replication" endpoint, because the worker doing the resync process may be different to that handling the purge request.
The first time the resync process tries to write data after the deletion it will fail because we have deleted necessary data e.g. auth events. AFAICS it will not retry the resync, so the only downside to not cancelling the resync is a scary-looking traceback.
(This is presumably extremely …

Fix order of partial state tables when purging

---

changelog.d/15075.feature
synapse/api/errors.py
synapse/handlers/message.py

MSC2677 now specifies `M_DUPLICATE_ANNOTATION`.

Update the error code for duplicate annotation

---

changelog.d/15074.bugfix
synapse/federation/federation_client.py

Previously we would give up upon receiving a 404 from the first server,
instead of trying the rest of the servers in the list.
---
Tested by https://github.com/matrix-org/complement/pull/612.

Fix federated joins when the first server in the list is not in the room

---

changelog.d/15078.doc
docs/usage/configuration/config_documentation.md

Fixes a minor mistake in docs.
Option `registration_shared_secret_file` should be `registration_shared_secret_path`

Fix a mistake in registration_shared_secret_path docs

---

changelog.d/14892.doc
docs/workers.md

Document how to start Synapse with Poetry

---

changelog.d/15080.bugfix
synapse/handlers/federation.py

Previously, when creating a join event in /make_join, we would decide
whether to include additional fields to satisfy restricted room checks
based on the current state of the room. Then, when building the event,
we would capture the forward extremities of the room to use as prev
events.
This is subject to race conditions. For example, when leaving and
rejoining a room, the following sequence of events leads to a misleading
403 response:
1. /make_join reads the current state of the room and sees that the user
is still in the room. It decides to omit the field required for
restricted room joins.
2. The leave event is persisted and the room's forward extremities are
updated.
3. /make_join builds the event, using the post-leave forward extremities.
The event then fails the restricted room …

Mitigate a race where /make_join could 403 for restricted rooms

---

changelog.d/15084.misc
mypy.ini
tests/appservice/test_scheduler.py
tests/http/federation/test_matrix_federation_agent.py
tests/http/test_proxyagent.py
tests/rest/client/test_auth.py
tests/rest/client/utils.py
tests/server.py
tests/unittest.py

This is the last ignored file for tests. Most of it was pretty straight-forward, but it did leak a little bit to other files. I tried to separate it into reasonable commits.
(Note there's one more file which doesn't *require* type hints.)

Stop ignoring tests/server.py

---

changelog.d/15079.bugfix
synapse/storage/databases/main/user_directory.py
tests/handlers/test_user_directory.py
tests/storage/test_user_directory.py

Fixes: #14815 
Introduced by: #14464 (as far as I can tell: it changed the tokenisation rules to leave `:`s in when you have ICU installed.)
This pull request is commit-by-commit review friendly. 
<ol>
<li>
Add failing test 
</li>
<li>
Small rename of variables 
</li>
<li>
Add minitests to characterise how we do tokenisation today 
</li>
<li>
Add escaping to our tsquery builder 
</li>
<li>
Test that we can find a user by prefix of MXID \
(I wasn't super confident that the ICU tokeniser wouldn't break this, but a bit of poking later,
I think I'm happy. But thought it should be tested anyway!)
</li>
</ol>

Fix a bug introduced in Synapse v1.74.0 where searching with colons when using ICU for search term tokenisation would fail with an error.

---

changelog.d/15096.bugfix
synapse/config/server.py

I was testing the new(ish) `health` listener resource that was added in #14747 and....it didn't work. All I got as an error was:
```log
Unknown listener resource
```
Very cryptic. The worker I attached it to would not start up.
This should fix it to work now.

Allow health listener resource to load

---

changelog.d/15110.misc
debian/changelog
debian/control

This is so installations will pull in the keyring package, allowing us to update the expiry time of the `packages.matrix.org` repository.
c.f. https://github.com/matrix-org/synapse/issues/10389

Add `matrix-org-archive-keyring` package as `Recommends`

---

changelog.d/15114.misc
poetry.lock
pyproject.toml

This is an ugly kludge to solve
https://github.com/matrix-org/synapse/issues/15109. It is not the most friendly thing to do for downstream packagers (apologies), but we are a) running low on time at the moment, and b) seeking to remove frozendict anyway.
Fixes #15109.

Upper-bound frozendict dependency

---

changelog.d/15093.bugfix
synapse/handlers/register.py
synapse/handlers/room.py
synapse/module_api/__init__.py
synapse/rest/client/room.py
synapse/server_notices/server_notices_manager.py
tests/storage/test_cleanup_extrems.py
tests/storage/test_event_metrics.py
tests/storage/test_receipts.py
tests/test_federation.py

Fixes #10321.
Supersedes #14884.
Commitwise reviewable.

Remove unused `room_alias` field from `/createRoom` response

---

changelog.d/15071.doc
docs/modules/third_party_rules_callbacks.md

Just a bit of clarification for the `on_new_event` module API callback as a result of a question someone asked internally.
This callback is called on the worker that persists the new event, as well as every worker that's listening on the events stream (which is every worker afaik).

Clarify the workers that the ThirdPartyRules' `on_new_event` callback will run on

---

changelog.d/15095.misc
synapse/app/admin_cmd.py

Follow up: https://github.com/matrix-org/synapse/pull/14969#discussion_r1108859420
> This is fine here (we don't expect account_data to be large), but for general interest it might be more efficient to use `json.dump(account_data, f)` (see [here](https://docs.python.org/3/library/json.html#json.dump)) for large `account_data` blobs.
no functional change, only refactoring code
- Feel free to credit yourself, by adding a sentence "Contributed …

Use `json.dump` in `FileExfiltrationWriter`

---

changelog.d/15135.misc
docs/usage/configuration/config_documentation.md
synapse/config/ratelimiting.py

We have occasionally seen users logging in frequently with user-agents that look like scripts. This isn't valid behavior and we should be ratelimiting more aggressively.
From my math this means we should allow 5 devices, then 1 every ~5 minutes.

Tighten the rate limit of creating new devices.

---

changelog.d/15112.doc
docs/openid.md

Just added a working config for Shibboleth with OIDC Plugin

Add Shibboleth with OIDC Plugin Documentation

---

changelog.d/15139.doc
docs/usage/configuration/config_documentation.md

I hope a changelog is not necessary for this kind of change
Signed-off-by: Vincent Post <cent@spline.de>

Fix reference to federation_verify_certificates server config documentation

---

changelog.d/15138.misc
synapse/config/experimental.py
synapse/push/bulk_push_rule_evaluator.py
tests/push/test_push_rule_evaluator.py

I typoed the 8 and the 7 in #15004. 😢

Fix a typo in MSC3873 config option.

---

changelog.d/15137.removal
synapse/rest/media/v1/thumbnail_resource.py

Fixes #14913, this is the minimum change necessary to be spec compliant. I didn't want to rip out all of the functions which then use this as I think we'll want to do something similar with the `Accept` header. @Half-Shot and I are planning an MSC there.
Note that if a client *is* sending this then it will just be ignored, which is the behavior the client would see on e.g. Conduit or Dendrite.

Stop parsing the unspecced type parameter on thumbnail requests.

---

changelog.d/15092.bugfix
synapse/rest/media/v1/preview_url_resource.py
tests/rest/media/v1/test_url_preview.py

This fixes previews of https://blog.jetbrains.com/idea/2022/05/take-part-in-the-new-ui-preview-for-your-jetbrains-ide/, that page has oEmbed autodiscovery in it:
```html
<link
rel="alternate"
type="application/json+oembed"
href="https://blog.jetbrains.com/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fblog.jetbrains.com%2Fidea%2F2022%2F05%2Ftake-part-in-the-new-ui-preview-for-your-jetbrains-ide%2F" />
```
But if you go to that URL you get a 403 forbidden error. This shouldn't break URL previews completely, we already parsed the HTML page, let's just return that.
This is similar to #12950 where I made this change for image previews.

Do not fail completely if oEmbed autodiscovery fails.

---

changelog.d/15143.misc
synapse/storage/databases/main/user_directory.py
tests/storage/test_user_directory.py

* Fix a long-standing bug where non-ASCII characters in search terms,
including accented letters, would not match characters in a different
case.
* Fix a long-standing bug where search terms using combining accents
would not match display names using precomposed accents and vice
versa.
To fully take effect, the user directory must be rebuilt after this
change.
Fixes #14630.
---
May be reviewed commit by commit.
The last three commits can be split out into a separate PR if it makes more sense.

Improve handling of non-ASCII characters in user directory search

---

changelog.d/15150.bugfix
synapse/replication/tcp/resource.py
tests/replication/tcp/test_handler.py

This only affects deployments using workers.
Introduced in #14820

Fix bug where 5s delays would occasionally happen.

---

changelog.d/14918.misc
synapse/events/snapshot.py
synapse/handlers/message.py
synapse/handlers/room.py
synapse/handlers/room_batch.py
synapse/handlers/room_member.py
synapse/storage/databases/state/store.py
tests/handlers/test_message.py
tests/handlers/test_register.py
tests/push/test_bulk_push_rule_evaluator.py
tests/rest/client/test_rooms.py
tests/storage/test_event_chain.py
tests/storage/test_state.py
tests/unittest.py

This work builds upon #14675, and adds functionality to batch persist the state groups of unpersisted event contexts. The impetus for this work is  #13961, and it is part of the work to speed up DM/room creation. Should be reviewable commit-by-commit.

Batch up storing state groups when creating new room

---

changelog.d/15168.doc
docs/usage/configuration/config_documentation.md

Correct documentation about registration_shared_secret_path

---

changelog.d/15116.feature
docs/admin_api/event_reports.md
synapse/rest/admin/event_reports.py
synapse/storage/databases/main/room.py
tests/rest/admin/test_event_reports.py

Closes #15011
Add admin API endpoint to delete a reported event.
~~Move `get_event_report` and `get_event_reports_paginate` from `RoomStore` to `RoomWorkerStore`.
Both are read only queries. IMO there is no reason why this is should not possible for workers.~~
(run the …

Admin API endpoint to delete a reported event

---

changelog.d/15164.misc
mypy.ini
synapse/http/client.py

Bitty PR to finish type hints in `synapse.http.client`.

Add missing type hints to InsecureInterceptableContextFactory.

---

changelog.d/15134.feature
docker/configure_workers_and_start.py
docs/workers.md
synapse/rest/__init__.py
synapse/storage/databases/main/__init__.py
synapse/storage/databases/main/filtering.py

Since clients (Element Web at least) check and set `/filter`s before doing basic operations like `/sync`, this endpoint being married to the master process is a single point of failure.
By my reading, the endpoint itself would Just Work™ on a worker today, as long as we enabled it. That's what I'm proposing in this PR.
<ol>
<li>
Collapse FilteringStore into FilteringWorkerStore \
This is safe because all transactions do not write to any streams
or otherwise do anything racy.
</li>
<li>
Register /filter servlets on workers too 
</li>
</ol>

Allow use of the `/filter` Client-Server APIs on workers.

---

changelog.d/15163.bugfix
synapse/rest/client/sync.py
synapse/storage/databases/main/account_data.py
tests/storage/test_account_data.py

Partially addresses: #15162
<ol>
<li>
Invalidate initial sync if ignored user set changes 
</li>
</ol>

Fix a long-standing bug where an initial sync would not respond to changes to the list of ignored users if there was an initial sync cached.

---

changelog.d/15175.misc
docs/modules/spam_checker_callbacks.md

This was missed in #15146. Note that the `FileStorageProvider` is not referenced in the config manual (we use `file_system` as a special constant instead).

Update spam checker documentation for moved media modules.

---

changelog.d/15180.bugfix
synapse/rest/client/devices.py

A regression from #14605.
Fixes #15178
I tested with: `curl -v -X POST http://localhost:8080/_matrix/client/unstable/org.matrix.msc2697.v2/dehydrated_device/claim` which was returning unrecognised request and is now returning a missing access token error. 👍 
I also checked that `curl -v http://localhost:8080/_matrix/client/unstable/org.matrix.msc2697.v2/dehydrated_device` (and with `-X PUT`) still works as expected.

Fix conflicting URLs for dehydrated devices.

---

changelog.d/15186.docker
docker/configure_workers_and_start.py

I didn't realise this and was confused for quite some time.
(This bit me when working with complement.)

Dockerfile-workers: spell out when config isn't generated

---

changelog.d/15189.misc
synapse/rest/client/knock.py

This removes the PUT method on the /knock/{roomId} endpoint, which is unspecced, and probably bugged anyway.

Remove the unspecced and bugged PUT /knock/{roomIdOrAlias} endpoint

---

changelog.d/15191.misc
synapse/storage/databases/main/account_data.py
synapse/storage/util/id_generators.py
synapse/storage/util/sequence.py

This allows for fetching the next stream ID while within a DB transaction, where one is not able to call `get_next` due to not being able to call async methods from within a database txn.
Additional context in commit messages.
Split out from https://github.com/matrix-org/synapse/pull/14869. Includes a couple docstring fixes I noticed in the area.

Add a `get_next_txn` method to `StreamIdGenerator` to match `MultiWriterIdGenerator` (#15191

---

changelog.d/14869.bugfix
synapse/handlers/account_data.py
synapse/storage/databases/main/account_data.py

This PR fixes a bug introduced in https://github.com/matrix-org/synapse/pull/14714 with ~~two~~ one major change:
* Stop providing a `content` kwarg to `ReplicationRemoveUserAccountDataRestServlet`, which didn't take that argument. This was causing a `TypeError` when trying to remove user account when experimental MSC3890 support was enabled and an account data writer worker was in use.
* ~~Set `WAIT_FOR_STREAMS` to `False` for `ReplicationRemoveUserAccountDataRestServlet`. Don't update the account_data stream when a delete comes in for data that doesn't exist. This stops the master process waiting for the `account_data` stream to increment after issuing a replication command. In the case of attempting to delete an account data entry which doesn't exist, we don't update the account data …

Experimental MSC3890 Implementation: Fix deleting account data when using an account data writer worker

---

changelog.d/15194.misc
scripts-dev/lint.sh

This adds the `--fix` option to `ruff`, similar to what we allow our other linting bits to do.

Allow ruff to automatically fix issues.

---

changelog.d/15199.misc
synapse/rest/client/room_batch.py

Similar to https://github.com/matrix-org/synapse/pull/15189
The PUT method on that endpoint was never in the MSC, and probably buggy, since the PUT did not have a `txn_id`, so you could only do one PUT per room_id.
For reference: https://github.com/matrix-org/matrix-spec-proposals/blob/matthew/msc2716/proposals/2716-batch-send-historical-messages.md#unstable-prefix

Remove unspecced and buggy `PUT` method on the unstable `/rooms/<room_id>/batch_send` endpoint.

---

changelog.d/15192.misc
synapse/storage/databases/main/devices.py
synapse/storage/databases/main/events_worker.py
synapse/storage/databases/main/push_rule.py
synapse/storage/databases/main/pusher.py
synapse/storage/databases/main/receipts.py
synapse/storage/util/id_generators.py

Follow-up to #14468 to combine the `AbstractStreamIdTracker` with `AbstactStreamIdGenerator`. #14468 combined the trackers/generators into single objects, thus there's no reason to have separate abstract classes anymore, after #15191 the only concrete sub-classes (`StreamIdGenerator` and `MultiWriterIdGenerator` have essentially the same interface and we can remove a bunch of explicit type hints.

Combine AbstractStreamIdTracker and AbstractStreamIdGenerator.

---

changelog.d/15185.feature
rust/benches/evaluator.rs
rust/src/push/base_rules.rs
rust/src/push/evaluator.rs
rust/src/push/mod.rs
stubs/synapse/synapse_rust/push.pyi
synapse/config/experimental.py
synapse/push/bulk_push_rule_evaluator.py
tests/push/test_bulk_push_rule_evaluator.py
tests/push/test_push_rule_evaluator.py

* Updates the identifier to `event_property_is` (and any references to it and property names derived from it).
* Rips out the experimental configuration flag.
[MSC3758](https://github.com/matrix-org/matrix-spec-proposals/pull/3758) is currently in FCP, so will need to wait for that to finish before merging.

Stabilize support for MSC3758: event_property_is push condition

---

changelog.d/15193.bugfix
synapse/config/experimental.py
synapse/events/utils.py
synapse/rest/client/room.py
synapse/server.py
tests/rest/client/test_relations.py

* Makes the code added in #14811 default to on and rips out unneeded code.
* Updates tests.

Enable MSC3925 by default: stop applying edits.

---

changelog.d/15215.misc
synapse/storage/database.py
synapse/storage/databases/main/end_to_end_keys.py

We look up keys in batches, but we should do that outside of the transaction to avoid starving the database pool.

Split up txn for fetching device keys

---

changelog.d/15184.misc
scripts-dev/complement.sh

Seemed to work locally for me :shrug:

Hack to rebuild the complement editable image

---

changelog.d/15200.misc
synapse/rest/admin/server_notice_servlet.py
synapse/rest/client/room.py
synapse/rest/client/sendtodevice.py
synapse/rest/client/transactions.py
tests/rest/client/test_transactions.py

This changes the `HttpTransactionCache` so it uses the `Requester` in addition of the `Request` to build the transaction key. This will help with #13064, when/if we want to change the scope of transaction IDs. 
This means that every time we use the transaction cache, we need to figure out the requester first, which was not needed before.
cc @clokep

Pass the Requester down to the HttpTransactionCache

---

changelog.d/15190.bugfix
rust/src/push/base_rules.rs
synapse/config/experimental.py
synapse/push/bulk_push_rule_evaluator.py
tests/push/test_push_rule_evaluator.py

* Unconditionally escapes the keys when flattening dictionaries.
* Rips out the experimental configuration flag.
[MSC3873](https://github.com/matrix-org/matrix-spec-proposals/pull/3873) is currently in FCP, so will need to wait for that to finish before merging.

Stabilize support for MSC3873: disambuguated event push keys.

---

changelog.d/15195.misc
synapse/event_auth.py
synapse/events/snapshot.py
synapse/handlers/event_auth.py
synapse/handlers/room.py

These changes come from a discussion with Erik and are follow-ups to the batching persisting event work, speeding it up/making it more efficient. Best reviewable commit-by-commit, and I can split these out into separate PRs if others think it necessary.

More speedups/fixes to creating batched events

---

changelog.d/15222.misc
synapse/handlers/pagination.py
synapse/storage/controllers/purge_events.py
synapse/storage/databases/main/purge_events.py
synapse/storage/databases/state/store.py

Otherwise if you have multiple purges at once then you can't tell which is progressing.

Include the room ID in more purge-room log lines.

---

changelog.d/15229.misc
synapse/handlers/room.py

This PR adds the topic and name events to the group of events that are batch persisted when creating a room.

Add topic and name events to group of events that are batch persisted when creating a room.

---

changelog.d/15230.misc
mypy.ini
synapse/storage/database.py

Finishes up this module so we can require type hints in it.

Add missing type hints to `synapse.storage.database`.

---

changelog.d/15232.bugfix
synapse/handlers/sync.py

When pushing events in partial state rooms down incremental /sync, we
try to find the `m.room.member` state event for their senders by digging
through their auth events, so that we can present the membership to the
client. Events usually have a membership event in their auth events,
with the exception of the `m.room.create` event and a user's first join
into the room.
When implementing #13477, we took the case of a user's first join into
account, but forgot to handle the `m.room.create` case. This change
fixes that.
Fixes #15221.

Faster joins: Fix spurious errors on incremental sync

---

changelog.d/15238.misc
synapse/server.py

See the big comment for a description of what this does.

Give PyCharm some help with `@cache_in_self`

---

changelog.d/15227.bugfix
synapse/events/third_party_rules.py
tests/rest/client/test_third_party_rules.py

https://github.com/matrix-org/synapse/pull/15044 added two new Module API callbacks: `on_add_user_third_party_identifier` and `on_remove_user_third_party_identifier` for informing Synapse modules that a user had added/removed a third party ID (email, phone number) to/from their account.
However, the bit of code which actually did the registering of `on_remove_user_third_party_identifier` callbacks was missing.
Additionally, the tests included with that PR were also wrong: they registered mocked callbacks under `on_threepid_bind`, instead of the correct callback names. The tests still passed, as `test_on_remove_user_third_party_identifier_is_called_on_deactivate` only checked that the removal variant of the callbacks was called once after both an add and remove action. It has been modified …

Fix missing conditional for registering `on_remove_user_third_party_identifier` module api callbacks (#15227

---

changelog.d/15240.misc
synapse/federation/sender/per_destination_queue.py
synapse/handlers/federation.py
synapse/visibility.py
tests/test_visibility.py

I found it hard to reason about; this is my attempt to remedy that.
Spun out of https://github.com/matrix-org/synapse/pull/15228.
Commitwise reviewable.
Intended to have no behavioural changes.

Refactor `filter_events_for_server`

---

changelog.d/15239.docker
docker/Dockerfile

Thanks to @atomdmac for spotting the fix.
Fixes #15179.

Install rust during Stage 0 of docker build

---

changelog.d/15248.bugfix
synapse/federation/sender/per_destination_queue.py
tests/federation/test_federation_catch_up.py
tests/test_utils/event_injection.py

Fixes #15220.
Previous iterations were https://github.com/matrix-org/synapse/pull/15228 https://github.com/matrix-org/synapse/pull/15241.

Ensure fed-sender catchup does not block for full state

---

changelog.d/15262.misc
synapse/handlers/register.py

This hot-paths out of the auto-join room functionality if there are no auto-join rooms configured.

Do not calculate whether to create auto-rooms if there aren't any configured

---

changelog.d/15266.misc
synapse/storage/databases/main/transactions.py

Just happened to notice this one was unreachable now, so thought I'd lop it off.
<ol>
<li>
Remove unused _set_destination_retry_timings_emulated 
</li>
<li>
Rename the _native one to _txn as it's clearer anyway 
</li>
</ol>

Remove unused store method `_set_destination_retry_timings_emulated`.

---

changelog.d/15247.misc
synapse/storage/schema/main/delta/74/90COMMENTS_destinations.sql.postgres

I'm intending to write up an overview document about the mechanism but I thought this might not be a bad trend to start.
At some point it'd be nice to export a clean view of these comments, but for now `\d+ destinations` in `psql` gets you some hints.
<ol>
<li>
Add some comments to the schema about destinations and destination_rooms 
</li>
</ol>

Add schema comments about the `destinations` and `destination_rooms` tables.

---

.github/workflows/release-artifacts.yml
.github/workflows/tests.yml
changelog.d/15244.misc

This is a step to enabling merge queues on Synapse. We might be able to slim down on PRs a little bit, maybe:
* Run portdb on once?
* Do not run sytest with and without asyncio?
* Do not build wheels / debs on PRs?
This only adds the merge queue for `tests.yml` & `release-artifacts.yml`; the other things which run for PRs are:
* `docs-pr.yml`: We build a preview of docs for PRs and then build them when we push to `develop`, I don't think we need to do it here too. (This check isn't part of our CI checks just a convenience.)
* `dependabot_changelog.yml`: These run when dependabot pushes PRs?
* `poetry_lockfile.yaml`: If two PRs modify the lockfile I don't see how this check could fail (it checks to ensure all deps have sdists -- if this is true for each PR individually it must be true for …

Enable running tests & release artifacts on merge queue.

---

changelog.d/15272.misc
synapse/replication/tcp/client.py

Part of #11728 -- this is simply an unused class, but some more code we can drop.

Remove unused class: DirectTcpReplicationClientFactory.

---

changelog.d/15237.misc
synapse/handlers/account_validity.py
synapse/module_api/__init__.py
synapse/module_api/callbacks/__init__.py
synapse/module_api/callbacks/account_validity_callbacks.py
synapse/rest/admin/users.py
synapse/server.py
tests/rest/client/test_account.py

This is the first in a series of PRs that attempts to migrate the module API callback registration code to a single set of classes under `synapse.module_api.callbacks`, instead of spread throughout various handlers and other bespoke classes.
Spreading module callback registration across the codebase also makes it unclear where a developer should put their code when they want to define a new class of callbacks. Consolidating these under the `synapse.module_api.callbacks` module cleans things up a bit, puts related code in the same place and makes it much more obvious how to extend it.
This PR creates the `synapse.module_api.callbacks` directory, a `account_validity_callbacks.py` file and an `__init__.py` that initialises and exposes a new `AccountValidityModuleApiCallbacks` class. It then …

Move Account Validity callbacks to a dedicated file

---

changelog.d/14756.bugfix
synapse/handlers/profile.py
synapse/handlers/user_directory.py
synapse/storage/databases/main/user_directory.py
tests/handlers/test_user_directory.py

This PR uses the 'stale remote profile' concept introduced in the previous PR in order to refresh genuine profiles over federation once we believe them to be stale.
There is a mechanism for retrying them, as well as scheduling them for later to prevent sending floods of queries in the event of state events gradually coming into our rooms (e.g. because the profile data *was* changed and their homeserver is gradually broadcasting `m.room.member` events).
What's missing, making this PR not a total fix, is a fix for the initial population stage of the User Directory, which presumably currently assumes state events represent profiles.
Follows: #14755 
Part of: #5677 
Base: `rei/userdirpriv1_collect_public_only` 
This pull request is intended for commit-by-commit review. 
Original commit …

Refresh remote profiles that have been marked as stale, in order to fill the user directory. [rei:userdirpriv]

---

changelog.d/15275.misc
docker/configure_workers_and_start.py

This `| None` syntax seems to not be supported on older versions, which tripped up some testing.
<ol>
<li>
Make configure_workers_and_start more backwards compatible 
</li>
</ol>

Make `configure_workers_and_start` script used in Complement tests compatible with older versions of Python.

---

.github/workflows/docker.yml
changelog.d/15281.docker

Will document this when we check it is working...
Part of: #10977 
<ol>
<li>
Push images to both GHCR and Docker Hub 
</li>
</ol>

Mirror images to the GitHub Container Registry (`ghcr.io/matrix-org/synapse`).

---

changelog.d/15235.bugfix
synapse/handlers/message.py
tests/rest/admin/test_room.py

When a room is deleted in Synapse we remove the event forward extremities in the room, so if (say a bot) tries to send a message into the room we error out due to not being able to calculate prev events for the new event *before* we check if the sender is in the room.
Fixes #8094

Fix error when sending message into deleted room.

---

changelog.d/15282.docker
docs/setup/installation.md

Fixes: #10977 
Follows: #15281 
<ol>
<li>
Document that our docker image can now additionally be acquired from GHCR 
</li>
</ol>
Blocked:

Document that our Docker images are mirrored to GHCR.

---

changelog.d/15295.bugfix
synapse/storage/databases/main/relations.py

Currently Synapse only fetches edits for `m.room.message` events, this is not correct according to the specification. It should [apply for all types of events](https://spec.matrix.org/v1.4/client-server-api/#validity-of-replacement-events).
This manifest in two related bugs (see below):
* No edit information is bundled for events which aren't `m.room.message`.
* `m.new_content` is not applied where available.
Due to the structure of our code both of these have the same room cause, which is simply that we enforce that the event type must be `m.room.message` when fetching edits from the database. We relax that in this PR.
Note that I didn't modify any tests since the current tests send `m.room.message` events, which is still valid.
Fixes #12793, fixes #12503
----
This reapplies #14034, …

Apply & bundle edits for non-message events.

---

.github/workflows/twisted_trunk.yml
changelog.d/15302.misc

I would like to do this so we can try Synapse's typechecking against a specific branch that the project solicited tests for, see https://mail.python.org/archives/list/twisted@python.org/message/GGO5JHA5S475AK6JZ3GCC3GIHGKQYM6Y/

Allow running twisted trunk against other branches

---

changelog.d/15128.misc
synapse/storage/databases/main/events.py
synapse/storage/databases/main/events_bg_updates.py
synapse/storage/databases/main/purge_events.py
synapse/storage/schema/__init__.py
synapse/storage/schema/main/delta/74/01membership_tables_event_stream_ordering.sql
synapse/storage/schema/main/delta/74/02membership_tables_event_stream_ordering_triggers.py

Reintroduces https://github.com/matrix-org/synapse/pull/14979 with fixes per https://github.com/matrix-org/synapse/issues/15014.
Original description:
This adds an `event_stream_ordering` column to `current_state_events`, `local_current_membership` and `room_memberships`. Each of these tables is regularly joined with the `events` table to get the stream ordering and denormalising this into each table will yield significant query performance improvements once used. ~~Includes a background job to populate these values from the `events` table~~ pushed back for now.
Same idea as https://github.com/matrix-org/synapse/pull/13703 which has been a significant improvement on our database instance, suspect once applied this will be far greater.
(run the …

Reintroduce membership tables event stream ordering

---

.gitignore
changelog.d/15319.misc

<ol>
<li>
Fix Complement gitignore rule 
</li>
</ol>

Fix `.gitignore` rule for the Complement source tarball downloaded automatically by `complement.sh`.

---

changelog.d/15331.feature
docker/configure_workers_and_start.py
docs/workers.md
synapse/rest/__init__.py
synapse/rest/client/password_policy.py

This endpoint reads only config information.

Load `/password_policy` endpoint on workers

---

changelog.d/15332.bugfix
synapse/handlers/typing.py

Rather than keeping them around forever in memory, slowing things down.
Fixes #11750.

Prune old typing notifications

---

.github/workflows/tests.yml
changelog.d/15339.misc

Most of the time taken currently is building the rust bit, which we can cache.

Speed up pydantic CI lint

---

changelog.d/15323.bugfix
synapse/handlers/federation_event.py
synapse/handlers/room_member.py

Since forever synapse did not allow you to join a room after you have been unbanned from it over federation. This was not actually because of the unban event not federating. Synapse simply used outdated state to validate the join transition. This skips the validation if we are not in the room and for that reason won't have the current room state.
Fixes #1563 …

Fix joining rooms you have been unbanned from

---

changelog.d/15341.doc
docs/usage/configuration/config_documentation.md

From:  https://github.com/matrix-org/synapse/pull/15135/files#diff-1865c1e8307bb29e7f82bbaae74af9e1e09936211f514e8a8006cfd0c2bdea9dR1524

doc: fix account login requests ratelimit defaults typo

---

changelog.d/15183.misc
synapse/handlers/device.py
synapse/handlers/register.py
synapse/storage/databases/main/devices.py
tests/handlers/test_admin.py
tests/handlers/test_device.py
tests/storage/test_client_ips.py

This should help reduce the number of devices e.g. simple bots the repeatedly login rack up.
We only delete non-e2e devices as they should be safe to delete, whereas if we delete e2e devices for a user we may accidentally break their ability to receive e2e keys for a message.
Basically #14595, but makes sure that we only have one delete going per-person at a time, and with a longer timeout.

Delete stale non-e2e devices for users, take 3

---

changelog.d/15348.misc
synapse/handlers/register.py
synapse/storage/databases/main/devices.py
tests/rest/client/test_register.py

Fixes up #15183
(I forgot to write tests in turns out...)

Fix registering a device on an account with lots of devices

---

changelog.d/15354.misc
docs/tcp_replication.md
synapse/replication/tcp/protocol.py
synapse/replication/tcp/streams/_base.py

This PR tries to convey in the doc/comments what @erikjohnston said [here](https://matrix.to/#/!vcyiEtMVHIhWXcJAfl:sw1v.org/$Qkd_2M5Q_U2pGbZnykb5EA9T9sUQZ0OfLxkU54rOF6Y?via=matrix.org).
Point 2 is already made [here](https://github.com/matrix-org/synapse/blob/develop/docs/tcp_replication.md?plain=1#L126) and [here](https://github.com/matrix-org/synapse/blob/develop/docs/tcp_replication.md?plain=1#L124) I believe.

Add some clarification to the doc/comments regarding TCP replication

---

changelog.d/15351.bugfix
synapse/api/errors.py
synapse/handlers/federation.py
synapse/handlers/federation_event.py
synapse/storage/databases/main/event_federation.py
tests/storage/test_event_federation.py

Previously, we would spin in a tight loop until
`update_state_for_partial_state_event` stopped raising
`FederationPullAttemptBackoffError`s. Replace the spinloop with a wait
until the backoff period has expired.

Fix spinloop during partial state sync when a prev event is in backoff

---

changelog.d/15349.bugfix
synapse/storage/databases/main/deviceinbox.py
tests/replication/_base.py
tests/replication/tcp/streams/test_account_data.py
tests/replication/tcp/streams/test_to_device.py

to_device updates could be dropped when consuming the replication stream

---

changelog.d/15183.misc
changelog.d/15348.misc
synapse/handlers/device.py
synapse/handlers/register.py
synapse/storage/databases/main/devices.py
tests/handlers/test_admin.py
tests/handlers/test_device.py
tests/rest/client/test_register.py
tests/storage/test_client_ips.py

Reverts #15183 and #15348
The problem is deleting devices that exist in very large rooms cause huge amounts of device list replication traffic.

Revert pruning of old devices

---

changelog.d/15381.feature
scripts-dev/build_debian_packages.py

Build Debian packages for Ubuntu 23.04 Lunar Lobster

---

changelog.d/15383.bugfix
synapse/handlers/sync.py

This change fixes a rare bug where initial /syncs would fail with a
`KeyError` under the following circumstances:
1. A user fast joins a remote room.
2. The user is kicked from the room before the room's full state has
been synced.
3. A second local user fast joins the room.
4. Events are backfilled into the room with a higher topological
ordering than the original user's leave. They are assigned a
negative stream ordering. It's not clear how backfill happened here,
since it is expected to be equivalent to syncing the full state.
5. The second local user leaves the room before the room's full state
has been synced. The homeserver does not complete the sync.
6. The original user performs an initial /sync with lazy_load_members
enabled.
* Because they were kicked from the room, the room is …

Fix a rare bug where initial /syncs would fail

---

changelog.d/15385.misc
synapse/storage/databases/main/roommember.py
synapse/storage/schema/main/delta/74/03_room_membership_index.sql

The queries were written on the assumption that users would only have a small number of forgotten rooms, this turns out not to be the case for some users. This causes *very* slow query times for `get_forgotten_rooms_for_user`, an example plan currently:
```
Group  (cost=0.56..9917.58 rows=19 width=68)
Group Key: m.room_id, m.user_id
->  Index Only Scan using room_memberships_user_room_forgotten on room_memberships m  (cost=0.56..4.89 rows=19 width=60)
Index Cond: (user_id = '?'::text)
SubPlan 1
->  Aggregate  (cost=521.71..521.72 rows=1 width=8)
->  Bitmap Heap Scan on room_memberships  (cost=519.69..521.70 rows=1 width=0)
Recheck Cond: ((user_id = m.user_id) AND (room_id = m.room_id))
Filter: (forgotten = 0)
->  BitmapAnd  (cost=519.69..519.69 rows=1 width=0)
->  Bitmap Index Scan on …
```

Speed up membership queries for users with forgotten rooms

---

changelog.d/15391.bugfix
synapse/storage/databases/main/pusher.py

Fixes #15389
This should be included for v1.81.0rc2
One thing I don't know, is if the background update will properly continue/restart for people who have upgraded to v1.81.0rc1. Am I right to assume that no progress on the update should have been recorded, so it should just restart from the beginning?

Fix the 'set_device_id_for_pushers_txn' background update.

---

changelog.d/15393.misc
synapse/api/room_versions.py
synapse/events/utils.py
tests/events/test_utils.py

Trivial implementation of [MSC3989](https://github.com/matrix-org/matrix-spec-proposals/pull/3989) which updates the redaction algorithm to redact the `origin` field.

Implement MSC3989 to redact the origin field.

---

.ci/scripts/setup_complement_prerequisites.sh
.github/workflows/latest_deps.yml
.github/workflows/tests.yml
.github/workflows/twisted_trunk.yml
changelog.d/15403.misc

See https://github.com/actions/runner-images/issues/7276 and similarly https://github.com/matrix-org/complement/pull/634

Use setup-go instead of relying on go 1.17 to exist

---

.github/workflows/latest_deps.yml
.github/workflows/tests.yml
.github/workflows/twisted_trunk.yml
changelog.d/15406.misc

This action doesn't have versioned release branches or tags like github's [advice](https://docs.github.com/en/actions/creating-actions/releasing-and-maintaining-actions#example-developer-process). Out of paranoia, I pinned the action to a specific commit to guard against CI breaking under us.
This hasn't happened, but we have had semiregular dependabot updates which I think are just a bit too noisy. So I would like us to trust the author of the action.
Closes #15368.

Trust dtolnay/rust-toolchain

---

.github/workflows/tests.yml
changelog.d/15409.misc

I'm trying to fix one specific thing:
1. Weird mypy failures as seen recently on dependabot PRs, e.g. https://github.com/matrix-org/synapse/pull/15376#issuecomment-1498983775 and on develop CI, e.g. https://github.com/matrix-org/synapse/actions/runs/4631780873/jobs/8195058949
But my chosen way of doing so allows me to fix a pain point:
2. Having parts of the CI defined in a separate repo has caused us too much pain---it makes things especially hard to debug. (One has to make two branches on two repos to experiment---maybe three if `setup-python-poetry` is involved`. I don't think the indirection is worth it, especially since we haven't used it in anger across all of our python projects.
Additionally: I think I'm coming round to the view[^1] that
∞.  All CI config is a mess; efforts to …

Attempt to fix weird mypy failures on ignored files

---

changelog.d/15425.bugfix
synapse/config/appservice.py
tests/config/test_appservice.py

Fixes #15422 
This adds some tests. I also chose to throw errors in read_config because it feels weird to me that we allow invalid types to persist for any length of time.
(This is technically breaking, if you've configured your homeserver badly and forgot about it)

Throw if the appservice config list is the wrong type

---

changelog.d/15428.bugfix
synapse/rest/client/login.py

Disable loading `RefreshTokenServlet` on workers

---

changelog.d/15429.misc
synapse/storage/databases/main/event_federation.py

Follows: #15382 
<ol>
<li>
Add missing comma 
</li>
</ol>

Add comma missing from #15382.

---

changelog.d/15433.misc
tests/handlers/test_sso.py

Part of: #15430
Currently there are about 220 other tests with `async def`. These do not seem to generate errors or warnings
Signed-off-by: Dirk Klimpel …

Convert async to normal tests in `TestSSOHandler`

---

changelog.d/15410.bugfix
docs/modules/password_auth_provider_callbacks.md
synapse/handlers/device.py
synapse/server.py
tests/module_api/test_api.py

The assumption that `on_logged_out` module hooks will be called before deleting the pushers has been "broken" by #15280.
This behavior was not really specified, hence my quoted `broken`, so this PR also add it to the doc of the module API.

Delete pushers after calling on_logged_out module hook on device delete

---

changelog.d/15435.misc
synapse/storage/databases/main/user_directory.py

c.f. #15264
The two changes are:
1. Add indexes so that the select / deletes don't do sequential scans
2. Don't repeatedly call `SELECT count(*)` each iteration, as that's slow

User directory background update speedup

---

changelog.d/15436.feature
docker/configure_workers_and_start.py
docs/workers.md
synapse/rest/__init__.py
synapse/rest/client/capabilities.py

This endpoint reads only config information.

Load `/capabilities` endpoint on workers

---

changelog.d/15438.misc
synapse/http/server.py

Disable directory listing for `/_matrix/static/`.

Disable directory listing for `StaticResource`

---

changelog.d/15429.misc
changelog.d/15432.misc
synapse/storage/database.py
synapse/storage/databases/main/event_federation.py
synapse/storage/types.py

More precise type for `LoggingTransaction.execute` to catch expression misuse where a tuple should go.
ex. (via https://stackoverflow.com/a/7992642/796832)
```
(1)  # the number 1 (the parentheses are wrapping the expression `1`)
(1,) # a 1-tuple holding a number 1
() # confusingly, a 0-tuple
```
---
If you revert https://github.com/matrix-org/synapse/pull/15429 atop this PR and run mypy, it spots the error. See [here](https://github.com/matrix-org/synapse/actions/runs/4694603815/jobs/8322922294#step:7:16) on https://github.com/matrix-org/synapse/pull/15432/commits/f0863f735947d157e3a8083ff1449d9c4e69b304:
```
Run poetry run mypy
synapse/storage/databases/main/event_federation.py:1715: error: Argument 2 to "execute" of "LoggingTransaction" has incompatible type "Optional[int]"; expected …
```

More precise type for LoggingTransaction.execute

---

changelog.d/15427.misc
synapse/http/client.py

Simple refactor job. The main use of `SimpleHttpClient` is to allow crossing a proxy and to respect a block/allow list. Most of the other methods are unrelated to that and are reusable. Factor those out so creating/deduplicating other `Client`'s is less work.

Refactor `SimpleHttpClient` to pull out reusable methods

---

changelog.d/15452.doc
docs/usage/configuration/config_documentation.md

I was prompted to add this little tidbit of information after receiving a question about it from an Element customer.

Add a note to the config documentation that the 'delete_stale_devices_after' job always runs on the main process

---

changelog.d/15453.misc
synapse/app/_base.py
synapse/federation/federation_base.py
synapse/federation/federation_server.py
synapse/handlers/directory.py
synapse/handlers/federation.py
synapse/handlers/message.py
synapse/handlers/register.py
synapse/handlers/room.py
synapse/handlers/room_member.py
synapse/handlers/user_directory.py
synapse/media/media_storage.py
synapse/module_api/__init__.py
synapse/module_api/callbacks/__init__.py
synapse/module_api/callbacks/spamchecker_callbacks.py
synapse/server.py
tests/handlers/test_user_directory.py
tests/media/test_media_storage.py
tests/rest/client/test_rooms.py
tests/server.py

This PR is a follow-on from https://github.com/matrix-org/synapse/pull/15237, in an effort to move all Synapse module callback classes to a central location, rather than spread out throughout the codebase.
* The first commit moves the `synapse.events.spam_check.SpamChecker` module to `synapse.module_api.callbacks.spamchecker_callbacks.SpamCheckerModuleApiCallbacks`, and updates some references.
* The second commit updates all other points in the codebase that call out to the spam checker for checking events/user actions. There's a lot of files changed in this commit, but the changes are pretty repetitive.
Highly recommended to review the two commits individually. Admittedly these commits could probably be split out further, though I refrained to for time. Let me know if that is necessary.

Move Spam Checker callbacks to a dedicated file

---

changelog.d/15418.misc
changelog.d/15418.removal
synapse/handlers/device.py
synapse/handlers/devicemessage.py
synapse/handlers/federation_event.py
synapse/replication/http/devices.py
tests/test_federation.py

Closes #14808
Signed-off-by: Alok Kumar Singh alokaks601@gmail.com

Remove legacy code of single user device resync api

---

changelog.d/15465.misc
mypy.ini
synapse/federation/federation_client.py
synapse/federation/transport/client.py
synapse/http/matrixfederationclient.py
tests/federation/test_complexity.py
tests/http/test_matrixfederationclient.py

Requires type hints for `synapse/federation/transport/client.py` and `synapse/http/matrixfederationclient.py`. The commits are fairly separate.

Finish up type hints for federation client code

---

changelog.d/15318.feature
synapse/config/experimental.py
synapse/events/__init__.py
synapse/events/utils.py
synapse/handlers/message.py
synapse/handlers/room_member.py
synapse/rest/client/transactions.py
synapse/server.py
synapse/storage/databases/main/events.py
synapse/storage/databases/main/events_worker.py
synapse/storage/schema/main/delta/74/05_events_txn_id_device_id.sql

This adds support for MSC3970 behind an experimental flag.
MSC3970 changes the scope of transaction IDs to be scoped to devices instead of access tokens. I managed to implement it behind an experimental config flag.
Supersedes #13083
Fixes #13064
Complement test to check the behaviour: https://github.com/matrix-org/complement/pull/632
To try those, checkout the complement PR, enable the `msc3970_enabled` in the synapse complement config, and run the test suite with the `msc3970` build tag.
When reviewing this, there are three main changes to look at:
1. the device_id gets added to the event internal metadata, and with MSC3970 enabled it changes whether the transaction_id gets included or not in the event serializer
2. with MSC3970 enabled, the HTTP transaction cache uses the `(user_id, …

Experimental support for MSC3970: per-device transaction IDs

---

changelog.d/15462.misc
synapse/federation/federation_server.py
synapse/federation/transport/server/__init__.py
synapse/federation/transport/server/federation.py
synapse/handlers/appservice.py
synapse/handlers/e2e_keys.py
synapse/rest/client/keys.py
synapse/storage/databases/main/end_to_end_keys.py
tests/handlers/test_e2e_keys.py

See a [newly add bit of the MSC](https://github.com/matrix-org/matrix-spec-proposals/blob/travis/msc/enc-as/otk-query/proposals/3983-sending-otk-claims-to-appservices.md#returning-extra-keys) to always return fallback keys in a `/keys/claim` response.
Note that I implemented this as  a separate unstable endpoint, per [this thread](https://github.com/matrix-org/matrix-spec-proposals/pull/3983#discussion_r1171826670). Other options would be a keyword argument or deciding it is just "fine" to do, but being conservative as the MSC is going through review.

Add unstable /keys/claim endpoint which always returns fallback keys

---

changelog.d/15482.feature
docs/admin_api/statistics.md
synapse/rest/admin/__init__.py
synapse/rest/admin/statistics.py
synapse/storage/controllers/__init__.py
synapse/storage/controllers/stats.py

A fairly simple admin API that returns the largest rooms by database size, using the postgres statistics.

Add admin endpoint to query room sizes

---

changelog.d/15494.bugfix
rust/src/push/mod.rs

This fixes a regression from #14524 where some of the experimental push rules were being leaked even if the feature was not enabled.
I tested this with:
```bash
curl --header "Authorization: Bearer $TOK" http://localhost:8080/_matrix/client/v3/pushrules/  |
jq '.global[][] | select(.rule_id | startswith(".org"))'
```

Do not return extensible events experimental push rules by default.

---

.gitignore
changelog.d/15495.misc
flake.lock
flake.nix

This PR adds a [nix](https://nixos.org/) flake to the repository, which allows for setting up a complete development environment for Synapse (including native dependencies for Sytest and Complement too!) with a single `nix develop --impure` invocation. No containers are used - all software runs natively. Users can activate this environment automatically when they enter their Synapse checkout by installing https://direnv.net/.
A short example video:
[Screencast from 2023-04-26 20-10-00.webm](https://user-images.githubusercontent.com/1342360/234683620-ee4e4e4e-8705-4705-b977-6dacc77f4a41.webm)
You can even start up local Redis and PostgreSQL servers for testing Synapse in worker mode. The PostgreSQL server is pre-configured with a `synapse` database and a `synapse_user` user. No need to …

Add a nix flake that sets up a development environment (via devenv)

---

changelog.d/15496.misc
mypy.ini
synapse/storage/databases/__init__.py
synapse/storage/databases/main/cache.py

We do this by adding specific `ignore` statements on the lines that break.
This is not ideal, but much more local than ignoring the entire file.

Stop ignoring a couple more files for mypy

---

changelog.d/15514.misc
synapse/http/client.py
synapse/push/httppusher.py
synapse/server.py
tests/push/test_http.py
tests/replication/test_pusher_shard.py

#2817 increased the size of the HTTP connection pool for all `SimpleHttpClient` due to the HTTP pushers being killed by TLS negotiation.
In #15440 I noted that for URL previews this means we might keep lots of connections hanging around which might never be re-used.
To solve this we allow overriding the pool and then *only* override it for the pusher pool.

Reduce the size of the HTTP connection pool for non-pushers.

---

changelog.d/15516.feature
docs/usage/configuration/config_documentation.md
synapse/config/push.py
synapse/push/httppusher.py
tests/push/test_http.py

This is to discourage timing based profiling on the push gateways.

Allow adding random delay to push

---

changelog.d/15522.misc
docs/admin_api/experimental_features.md
synapse/rest/admin/experimental_features.py
tests/rest/admin/test_admin.py

Per the comment here: https://github.com/matrix-org/synapse/pull/15345#discussion_r1182415342 it was determined that it doesn't make sense to support enabling msc2654 per user, so remove references to supporting it from the codebase.

Remove references to supporting per-user flag for msc2654

---

changelog.d/15527.misc
demo/start.sh

Before this change, contributors would see the following when running `demo/start.sh`:
```
❯ ./demo/start.sh 
Starting server on port 8080... 
~/code/test-checkout/demo/8080 ~/code/test-checkout
Generating config file 8080.config
Generating log config file /home/work/code/test-checkout/demo/8080/localhost:8480.log.config which will log to /home/work/code/test-checkout/demo/8080/homeserver.log
Generating signing key file /home/work/code/test-checkout/demo/8080/localhost:8480.signing.key
A config file has been generated in '8080.config' for server name 'localhost:8480'. Please review this file and customise it to your needs.
..+...+............+...+.......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*........+.....+..........+...+..+.......+...+..+.+..+......+......+...+. …
```

Suppress the trusted key server warning for matrix.org in the demo scripts

---

changelog.d/15529.misc
synapse/storage/database.py
synapse/storage/databases/main/user_directory.py

The idea here is to batch up the work.
Note the second commit is simply moving a function out, and so reviewing with whitespace changes disabled is recommended.

Speed up rebuilding of the user directory for local users

---

changelog.d/15531.misc
synapse/storage/databases/main/event_push_actions.py

Enforce that we use index scans (rather than seq scans), which we also do for state queries. The reason to enforce this is that we can't correctly get PostgreSQL to understand the distribution of `stream_ordering` depends on `highlight`, and so it always defaults (on matrix.org) to sequential scans. 
In #13118 we accidentally stopped deleting old highlight notifications, and instead only deleted non-highlight notifications. This is especially exacerbated the above problem.
We can't just delete old highlight notifications from the `event_push_actions` table, as they don't get summarised in the same normal notifications do. We could fix that, but that is a much bigger job.
(This PR supersedes #15519).

Speed up deleting of old rows in `event_push_actions`

---

changelog.d/15533.misc
flake.lock
flake.nix

In the PR that introduced `flake.nix` (#15495), I had to point towards a fork of https://github.com/cachix/devenv which included [a fix](https://github.com/cachix/devenv/pull/559) for a bad interaction between [devenv services (processes)](https://devenv.sh/processes/); the feature that allows devs to start up postgres and redis via `devenv up`.
We can now switch back to upstream devenv, as the fix was merged :tada: This will cause an update to `flake.lock`, which is a file that tracks "flake inputs" - the repos we pull packages from. https://github.com/cachix/devenv being one of them.
Local developer environments will rebuild automatically to point to the new upstream upon re-entry.
The changelog entry for this change is combined with: https://github.com/matrix-org/synapse/pull/15532.

Switch back to upstream devenv flake

---

changelog.d/15532.misc
flake.nix

The [`xmlsec` library](https://search.nixos.org/packages?channel=unstable&show=xmlsec&from=0&size=50&sort=relevance&type=packages&query=xmlsec) is required to run the `tests.handlers.test_saml.SamlHandlerTestCase` unit tests:
https://github.com/matrix-org/synapse/blob/42aea0d8af1556473b4f31f78d9facb448230a1f/tests/handlers/test_saml.py#L129-L130
This PR will install the `xmlsec` library into developer environments generated by `flake.nix`. Said environments will update and install the library automatically upon re-entry.
Missed in #15495.

Add `xmlsec` package to flake.nix

---

changelog.d/15535.misc
synapse/app/_base.py
synapse/handlers/auth.py
synapse/handlers/deactivate_account.py
synapse/handlers/directory.py
synapse/handlers/federation.py
synapse/handlers/federation_event.py
synapse/handlers/message.py
synapse/handlers/profile.py
synapse/handlers/room.py
synapse/handlers/room_member.py
synapse/module_api/__init__.py
synapse/module_api/callbacks/__init__.py
synapse/module_api/callbacks/third_party_event_rules_callbacks.py
synapse/notifier.py
synapse/rest/admin/rooms.py
synapse/server.py
tests/rest/client/test_third_party_rules.py
tests/server.py

A follow-on from https://github.com/matrix-org/synapse/pull/15453, in an effort to move all Synapse module callback classes to a central location, rather than spread out throughout the codebase.
* The first commit moves the `synapse.events.third_party_rules.ThirdPartyEventRules` module to `synapse.module_api.callbacks.third_party_event_rules.ThirdPartyEventRulesModuleApiCallbacks`, and updates the references in `ModuleApi`.
* The second commit updates all other points in the codebase that call out to third party rules modules for checking events/user actions. There's a lot of files changed in this commit, but the changes are pretty repetitive.

Move ThirdPartyEventRules into module_api/callbacks

---

changelog.d/15542.misc
synapse/api/auth_blocking.py
synapse/crypto/keyring.py
synapse/federation/federation_base.py
synapse/federation/federation_client.py
synapse/federation/federation_server.py
synapse/federation/send_queue.py
synapse/federation/sender/__init__.py
synapse/federation/transport/client.py
synapse/federation/transport/server/_base.py
synapse/handlers/event_auth.py
synapse/handlers/federation.py
synapse/handlers/federation_event.py
synapse/handlers/profile.py
synapse/handlers/sso.py
synapse/handlers/typing.py
synapse/rest/admin/media.py
synapse/rest/client/room.py
synapse/rest/media/download_resource.py
synapse/rest/media/thumbnail_resource.py
synapse/server.py
synapse/storage/databases/main/room.py
tests/unittest.py

Add an `is_mine_server_name` method, similar to `is_mine_id`.
Ideally we would use this consistently, instead of sometimes comparing
against `hs.hostname` and other times reaching into
`hs.config.server.server_name`.
Also fix a bug in the tests where `hs.hostname` would sometimes differ
from `hs.config.server.server_name`.

Factor out an `is_mine_server_name` method

---

changelog.d/15544.doc
docs/admin_api/user_admin_api.md
synapse/handlers/profile.py
synapse/rest/admin/users.py
synapse/storage/databases/main/profile.py
synapse/util/msisdn.py

Lots of little changes to the documentation for the `PUT /_synapse/admin/v2/users/<user_id>` Admin API. There's also a couple code changes (mostly docstrings), where I came across issues.
Recommended to review commit-by-commit.

Clean up and clarify "Create or modify Account" Admin API documentation

---

changelog.d/15532.misc
changelog.d/15533.misc
changelog.d/15545.misc
flake.nix

Such that it is available in the nix developer environment. [mdbook](https://rust-lang.github.io/mdBook/) is used to build the [Synapse documentation website](https://matrix-org.github.io/synapse).
The changelogs of #15532 and #15533 have been updated to match this PR's changelog, as they all touch the same area. This saves the maintainer from needing to do the same during the next Synapse release :)

Add `mdbook` to flake.nix

---

changelog.d/15523.bugfix
synapse/http/federation/srv_resolver.py

* [✅] Pull request is based on the develop branch
* [✅] Pull request includes a [changelog file](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
* [✅] Pull request includes a [sign …

Handle `DNSNotImplementedError` in SRV resolver

---

changelog.d/15539.misc
synapse/handlers/device.py
tests/handlers/test_device.py

[MSC3984](https://github.com/matrix-org/matrix-spec-proposals/pull/3984) sends `/keys/query` requests to appservices, but there's another way that device keys get returned, the `/user/devices` endpoint over federation. Luckily the formats are close enough that we can target the same underlying appservice endpoint and munge the data a bit.
See this thread: https://github.com/matrix-org/matrix-spec-proposals/pull/3984#discussion_r1185375659

Check appservices for devices during a /user/devices query.

---

changelog.d/15554.misc
synapse/api/constants.py
synapse/handlers/read_marker.py
synapse/handlers/sync.py
synapse/rest/client/account_data.py

Adds an `m.push_rules` constant and uses it, uses the `m.fully_read` constant in more places.

Use account data constants in more places

---

changelog.d/15470.misc
synapse/http/client.py
synapse/http/replicationagent.py
synapse/replication/http/_base.py
synapse/server.py
tests/test_state.py

Part 3 of 5(ish) to wire up HTTP replication Unix socket support.
Create a new Client that doesn't have support for Forward Proxies, Browser-like redirects, Cookie Handling, IP Block/Allow listing, Buffered Response Bodies and has a smaller `HttpConnectionPool` than `SimpleHttpClient`. This should be a drop-in replacement. Only set up to handle HTTP and HTTPS at this time.
Additional notes: 
* Unlike `SimpleHttpClient` and it's base class(`BaseHttpClient`), this removes `treq` as the request library as it was an extra layer that seemed to bring some of the functionality we no longer need and was getting in the way of future work in this area by enforcing IDNA2008 standards which won't be used or needed as well.
* Opentracing span was named `outgoing-replication-request`
Inspiration for …

HTTP Replication Client

---

changelog.d/15562.misc
synapse/rest/client/versions.py

Missed in https://github.com/matrix-org/synapse/pull/14714.
This PR adds `org.matrix.msc3391` to the unstable feature flags advertised by Synapse on `/versions`, [as specified in MSC3391](https://github.com/ShadowJonathan/matrix-doc/blob/account-data-delete/proposals/3391-account-data-delete.md#unstable-prefix). The value of the flag matches the value of the `experimental_features.msc3391_enabled` config option.

Add an unstable feature flag for MSC3391 to the /versions endpoint

---

changelog.d/15491.misc
docker/conf-workers/worker.yaml.j2
docker/configure_workers_and_start.py
docs/systemd-with-workers/workers/generic_worker.yaml
docs/upgrade.md
docs/usage/configuration/config_documentation.md
docs/workers.md
synapse/config/workers.py
synapse/replication/http/_base.py
tests/module_api/test_api.py
tests/replication/_base.py
tests/replication/test_auth.py
tests/replication/test_client_reader_shard.py
tests/replication/test_sharded_event_persister.py

...by placing the main process instance data directly on the `instance_map` and removing special casing. Existing `worker_replication_*` settings are migrated into the 'in-memory' configuration if the `instance_map` data isn't found, ensuring backwards compatibility(which can be verified by check Sytest, as it has not been updated to reflect new settings).
Specifically, this removes
```
worker_replication_host
worker_replication_http_port
worker_replication_http_tls
```
I understand that the use of the word 'master' has...historic significance, so the word 'main' is used for the `instance_map`. Constants were added to allow easier change over to 'main' from 'master' in other code places in the future.
Example of usage:
```yaml
instance_map:
main:
host: 127.0.0.1
port: 1234
```
(run the …

Remove `worker_replication_*` settings

---

changelog.d/15566.bugfix
pyproject.toml

Synapse [makes use](https://github.com/matrix-org/synapse/blob/7e6ad62c49104e5a17d1d35fe4c743b9fd7cd31d/pyproject.toml#L355) of poetry’s [dependency groups](https://python-poetry.org/blog/announcing-poetry-1.2.0/#dependency-groups) that were introduced in poetry v1.2.0. Bump the minimum required version of the poetry-core dependency to reflect that requirement. …

Require at least poetry-core v1.2.0

---

changelog.d/15570.misc
pyproject.toml

This was bumped by dependabot in #15512, but we didn't bump also raise the version guard here. I don't know how we can avoid this happening in the future.
Closes #15461.
Spotted in https://github.com/matrix-org/synapse/issues/15461#issuecomment-1543513934 by @landryb.

Allow `pip install` to use setuptools_rust 1.6.0

---

changelog.d/15569.feature
synapse/app/_base.py

I found the error in the **Before** really vague and obtuse and didn't realize port `5432` corresponded to the Postgres port until searching the codebase. It says to check the logs but that wasn't my first instinct. It's just more obvious if we just print the full thing which gives context of the error type and the traceback to the relevant area of code.
```
$ poetry run python -m synapse.app.homeserver -c homeserver.yaml
**********************************************************************************
Error during initialisation:
connection to server at "localhost" (::1), port 5432 failed: Connection refused
Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
Is the server running on …
```

Print full startup/initialization error

---

changelog.d/15567.docker
docker/Dockerfile

Add pkg-config package to Stage 0 to be able to build Dockerfile on ppc64le architecture.
Signed-off-by: Fabian Ruf <dev@fru-its.com>

Add pkg-config package to Stage 0

---

changelog.d/15559.feature
synapse/rest/client/versions.py
synapse/rest/key/v2/local_key_resource.py
synapse/rest/key/v2/remote_key_resource.py

The only remaining bit is dealing with the removal of the key ID, as @richvdh [stated](https://github.com/matrix-org/synapse/issues/15089#issuecomment-1523204339) his thought for supporting 1.6 was to be technically non-compliant and just log when that happens. We can't fully drop support for it or we'd be non-compliant for Matrix <1.6.
#15089 has a list of needed features and some cross-links back out to other pieces.
Fixes #15089

Declare support for Matrix 1.6

---

changelog.d/15587.doc
docs/openid.md

Adds `display_name_template` and `localpart_template` to Mastodon SSO instructions. Also changed the deprecated `subject_claim` to `subject_template`.
This was requested in the Synapse Admins room a while back.
More info about these parameters can be found on the [Mastodon API page](https://docs.joinmastodon.org/methods/accounts/#get).
The original Mastodon doc PR can be found here #14594 
- Feel free to credit yourself, by adding a sentence …

Update Mastodon SSO instructions

---

changelog.d/15599.bugfix
synapse/app/_base.py

`traceback.format_exception(...)` usage that is compatible with Python 3.7 ([our current minimum supported version](https://matrix-org.github.io/synapse/latest/deprecation_policy.html)) and 3.11
> Since Python 3.10, instead of passing `value` and `tb`, an exception object can
be passed as the first argument. If `value` and `tb` are provided, the first
argument is ignored in order to provide backwards compatibility.
>
> -- https://docs.python.org/3/library/traceback.html
As encountered by @clokep and findings from @DMRobertson, https://matrix.to/#/!vcyiEtMVHIhWXcJAfl:sw1v.org/$GIF9SEOUOkz06kGTQzRn2alUFpiLzDruOunSC3kRAbo?via=matrix.org&via=element.io&via=pixie.town
Follow-up to https://github.com/matrix-org/synapse/pull/15569
- Types: …

`traceback.format_exception(...)` usage that is compatible with Python 3.7 and 3.11

---

changelog.d/15604.misc
synapse/storage/controllers/stats.py
tests/test_state.py

Fix subscriptable type usage in Python <3.9
Fix the following `mypy` errors when running `mypy` with Python 3.7:
```
synapse/storage/controllers/stats.py:58: error: "Counter" is not subscriptable, use "typing.Counter" instead  [misc]
tests/test_state.py:267: error: "dict" is not subscriptable, use "typing.Dict" instead  [misc]
```
Part of https://github.com/matrix-org/synapse/issues/15603
In Python 3.9, `typing` is deprecated and the types are subscriptable (generics) by default, https://peps.python.org/pep-0585/#implementation
- …

Fix subscriptable type usage in Python <3.9

---

.github/workflows/tests.yml
changelog.d/15602.misc
mypy.ini

Run mypy type checking with the minimum supported Python version. We use the oldest Python version because later Python versions can include some overloads which don't work in the older versions which we still support.
We're using Python 3.8 instead of 3.7 which is our actual minimum support version because it's EOL is in a matter of weeks so can avoid the extra effort. And in any case, minimum Python 3.8 support is better than winging it on Python 3.11.
Example of something that changed Python 3.10 which isn't compatible with older versions: https://github.com/matrix-org/synapse/pull/15599 …

Run mypy type checking with the minimum supported Python version

---

changelog.d/15601.bugfix
synapse/media/url_previewer.py
tests/media/test_url_previewer.py
tests/rest/media/test_url_preview.py

* If an oEmbed URL was substituted for one in the original URL it was not properly checked against `url_preview_url_blacklist` (this is a bit odd since they're both configured by the admin).
* If an oEmbed or image URL is discovered in the HTML, the resulting URLs were not checked against `url_preview_url_blacklist`.

Apply url_preview_url_blacklist to oEmbed and pre-cached images

---

changelog.d/15614.bugfix
synapse/config/appservice.py

The second argument of `ConfigError` is a path, passed as an optional
`Iterable[str]` and not a `str`. If a string is passed directly,
Synapse unhelpfully emits "Error in configuration at
a.p.p._.s.e.r.v.i.c.e._.c.o.n.f.i.g._.f.i.l.e.s'" when the config
option has the wrong data type.

Fix error message when `app_service_config_files` validation fails

---

changelog.d/15615.misc
synapse/config/_base.py
synapse/config/_base.pyi
synapse/config/_util.py
synapse/config/oembed.py
synapse/config/server.py
synapse/types/__init__.py
synapse/util/module_loader.py

Re-type config paths in `ConfigError`s to be `StrSequence`s

---

.github/workflows/tests.yml
changelog.d/15626.misc

Fixes #15608  by doing an `apt update` before attempting to install packages.

Fix olddeps build

---

changelog.d/15630.misc
synapse/util/ratelimitutils.py
tests/unittest.py

This change fixes two memory leaks during `trial` test runs.
Garbage collection is disabled during each test case and a gen-0 GC is
run at the end of each test. However, when the gen-0 GC is run, the
`TestCase` object usually still holds references to the `HomeServer`
used during the test. As a result, the `HomeServer` gets promoted to
gen-1 and then never garbage collected.
Fix this by periodically running full GCs.
Additionally, fix `HomeServer`s leaking after tests that touch inbound
federation due to `FederationRateLimiter`s adding themselves to a global
set, by turning the set into a `WeakSet`.
Resolves #15622.

Fix `HomeServer`s leaking during `trial` test runs

---

changelog.d/15633.misc
synapse/handlers/federation_event.py

Trace how many new events from the backfill response we need to process.
You can kinda derive this information from how many `_process_pulled_event` spans there are but it would be nice to quickly glance.
(run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.h …

Trace how many new events from the backfill response we need to process

---

changelog.d/15648.doc
docs/sample_log_config.yaml
synapse/config/logger.py

The now-removed comment was introduced in https://github.com/matrix-org/synapse/pull/8040, and referenced a "twisted" logging handler. That handler has since been removed from the file, so the associated comment is no longer necessary.

Remove outdated comment in log config

---

changelog.d/15636.misc
tests/test_utils/logging_setup.py

Remove duplicate timestamp from test logs (`_trial_temp/test.log`)
Fix https://github.com/matrix-org/synapse/issues/15618
```
2023-05-17 22:51:36-0500 [-] 2023-05-17 22:51:36,889 - synapse.server - 338 - INFO - sentinel - Finished setting up.
```
```
2023-05-19 18:16:20-0500 [-] synapse.server - 338 - INFO - sentinel - Finished setting up.
```
The `Twisted.Logger` controls the `2023-05-19 18:16:20-0500 [-]` prefix, see : [`twisted/twisted` -> `src/twisted/logger/_format.py#L362-L374`](https://github.com/twisted/twisted/blob/34b161e66bc7c9f9efbb95e82c770a863933e498/src/twisted/logger/_format.py#L362-L374)
And we delegate our logs to the Twisted Logger for the tests which puts it in `_trial_temp/test.log`
- Be a short description of your change which makes sense to users. "Fixed a bug that …

Remove duplicate timestamp from test logs (`_trial_temp/test.log`)

---

changelog.d/15634.bugfix
docs/modules/password_auth_provider_callbacks.md
synapse/appservice/__init__.py
synapse/handlers/auth.py
synapse/handlers/jwt.py
synapse/rest/client/login.py
tests/handlers/test_password_providers.py

Follow-up to #15624 to consolidate some of the logic checks.

Consolidate logic to check for deactivated users.

---

changelog.d/15647.bugfix
synapse/storage/controllers/state.py

*As discovered by @realtyem,*
Fix `@trace` not wrapping some state methods that return coroutines correctly
```
master | 2023-05-21 09:30:09,288 - synapse.logging.opentracing - 940 - ERROR - POST-1 - @trace may not have wrapped StateStorageController.get_state_for_groups correctly! The function is not async but returned a coroutine
```
Tracing instrumentation for these functions originally introduced in https://github.com/matrix-org/synapse/pull/15610
- Start with a …

Fix `@trace` not wrapping some state methods that return coroutines correctly

---

changelog.d/15658.misc
scripts-dev/mypy_synapse_plugin.py
synapse/storage/databases/main/roommember.py
synapse/util/caches/descriptors.py
tests/appservice/test_appservice.py
tests/storage/test_transactions.py

The `cached` and `cachedList` decorators return a `Deferred` regardless of whether the underlying function is async/returns a `Deferred`. The plugin we have didn't really do this properly and I was hitting an edge-case with it. This attempts to fix this up.

Improve type hints for cached decorator

---

changelog.d/15659.misc
mypy.ini
tests/util/caches/test_descriptors.py

Builds on #15658 to finish typing our test files.

Add type hints to test_descriptors.

---

changelog.d/15673.misc
flake.nix

Fixes: #15654 
Base: `release-v1.84` 
<ol>
<li>
Add dch and notify-send to the Nix dev flake 
</li>
</ol>

Add `dch` and `notify-send` to the development Nix flake so that the release script can be used.

---

changelog.d/15666.misc
synapse/api/room_versions.py

MSC: https://github.com/matrix-org/matrix-spec-proposals/pull/3820
There are no tests for this because the MSCs involved should already be tested, and when v11 is accepted there might be different test cases. Instead, it's suggested that tests get moved/created when v11 becomes stable.

Add MSC3820 (room version 11) option 2 unstable room version

---

.github/workflows/tests.yml
changelog.d/15672.bugfix
synapse/config/workers.py
tests/app/test_homeserver_start.py
tests/app/test_openid_listener.py
tests/config/test_workers.py
tests/replication/test_federation_ack.py
tests/storage/test_rollback_worker.py

(as long as the `worker_*` options are set)
Fixes: #15669 
Follows: #15491 
Base: `release-v1.84` 
<ol>
<li>
Fix #15669: always populate instance map even if it was empty 
</li>
<li>
Fix some tests 
</li>
<li>
Fix more tests 
</li>
</ol>

Fix a bug introduced in Synapse v1.84.0 where workers do not start up when no `instance_map` was provided.

---

changelog.d/15668.doc
docs/development/contributing_guide.md

Documentation improvements to contributing guide
- Reiterate the importance of getting Rust installed and set up before attempting to install the Python dependencies.
- Mention the importance of confirming that `poetry install` completed successfully and include a typical error that the user might see if it did not.
- Expand on "Now edit homeserver.yaml" to give examples of things likely to need changing and to link to the relevant sections of the Synapse server documentation.
Fix #15667
Signed-off-by: Grant McLean <grant@catalyst.net.nz>
- Use markdown where necessary, mostly for `code …

Documentation improvements to contributing guide (#15667)

---

changelog.d/15690.misc
synapse/federation/federation_server.py

Remove unused `FederationServer.__str__` override

---

changelog.d/15694.misc
mypy.ini
synapse/api/auth/msc3861_delegated.py
synapse/federation/federation_server.py
synapse/handlers/oidc.py
synapse/handlers/pagination.py
synapse/http/server.py
synapse/util/__init__.py
synapse/util/async_helpers.py
synapse/util/caches/lrucache.py
tests/server.py

This adds some stricter mypy options, I mostly enabled the ones that were very easy.

Add stricter mypy options

---

.github/workflows/release-artifacts.yml
changelog.d/15689.misc
docker/Dockerfile
docker/Dockerfile-dhvirtualenv
docker/Dockerfile-workers
docker/complement/Dockerfile
docker/editable.Dockerfile
scripts-dev/build_debian_packages.py

* Closes #15676 
Add fully qualified docker image names to all Dockerfiles and add relevant comments to scripts.
- Please double check I did the ones for the Debian artifacts right. It has notes in the commit(which is separate in case of need to revert).

Docker fully qualified image names

---

changelog.d/15700.misc
synapse/storage/databases/main/filtering.py
synapse/storage/databases/main/profile.py

This PR increases the number of entries processed per batch for each of the jobs from 50 to 1000, as it was discovered that `populate_full_user_id_profiles` was going to take ~12 days to complete at the current speed (~50 - 60hz). I bumped up the batch size in `populate_full_user_id_profiles` preemptively as it also was only processing 50 entries per batch.
Speed determined by this query that @clokep whipped up:
```
SELECT progress_json::json->'lower_bound_id' FROM background_updates WHERE update_name = 'populate_full_user_id_profiles'; SELECT pg_sleep(60); SELECT progress_json::json->'lower_bound_id' FROM background_updates WHERE update_name = 'populate_full_user_id_profiles'; SELECT pg_sleep(60); SELECT progress_json::json->'lower_bound_id' FROM background_updates WHERE update_name = …
```

Speed up background jobs populate_full_user_id_user_filters and populate_full_user_id_profiles

---

changelog.d/15703.removal
docs/upgrade.md

Part of #9547.
I chose v1.88.0+ for removal to match the deprecation given in #15317.
Targeting the release branch just to get this out a bit earlier since it is docs-only.

Add a note about deprecating /register with a user property.

---

changelog.d/15675.misc
synapse/storage/databases/main/devices.py
synapse/storage/databases/main/end_to_end_keys.py

This should mitigate the issue where lots of different servers requests the same user's devices all at once.

Cache requests for user's devices from federation

---

changelog.d/15709.misc
synapse/handlers/federation.py

Some house keeping on `maybe_backfill()` functions

Some house keeping on `maybe_backfill()` functions

---

.github/workflows/latest_deps.yml
.github/workflows/twisted_trunk.yml
changelog.d/15726.misc

This PR modifies the [latest_deps.yml](https://github.com/matrix-org/synapse/blob/develop/.github/workflows/latest_deps.yml) and [twisted_trunk.yml](https://github.com/matrix-org/synapse/blob/develop/.github/workflows/twisted_trunk.yml) GitHub Actions workflows - which typically run at 7 and 8am UTC respectively - such that they now only run if they are attached to the `matrix-org/synapse` repo. As a result, anyone with a fork of matrix-org/synapse will no longer have these jobs run on their fork.
Together, these two jobs check the default branch of the repository (`develop`) will not become incompatible with recently-released versions of our dependencies. This information is not very useful to people outside of our team.
As well as [preventing daily email …

Prevent "twisted trunk" and "latest deps" workflows from running on forks

---

changelog.d/15721.misc
synapse/http/matrixfederationclient.py

Add context for when/why to use the `long_retries` option when sending Federation requests
As explained by @erikjohnston, https://matrix.to/#/!vcyiEtMVHIhWXcJAfl:sw1v.org/$b56U7pYpjMqVMUU5ZU7yYLxohdTnjSOKOtrrZi8HVVs?via=matrix.org&via=element.io&via=pixie.town
Also link future ideas around more intelligent retries that @richvdh pointed out (https://github.com/matrix-org/synapse/issues/8917).
- Feel free to credit yourself, by adding a …

Add context for when/why to use the `long_retries` option when sending Federation requests

---

changelog.d/15725.misc
synapse/federation/federation_server.py

Update error to more plainly explain we can only authorize our own events

Update error to more plainly explain we can only authorize our own events

---

changelog.d/15731.misc
synapse/storage/databases/main/roommember.py

No need for the extra join since `membership` is built-in to the `current_state_events` table. This helps with the upstream `is_host_joined()` and `is_host_invited()` functions.
`membership` was added to `current_state_events` in https://github.com/matrix-org/synapse/pull/5706 and forced in https://github.com/matrix-org/synapse/pull/13745
Follow-up PRs:
- https://github.com/matrix-org/synapse/pull/15733
- https://github.com/matrix-org/synapse/pull/15732
- https://github.com/matrix-org/synapse/pull/15734
- https://github.com/matrix-org/synapse/pull/15735
```sh
$ psql --user postgres synapse
synapse=# \d+ current_state_events
Table "public.current_state_events"
Column         |  Type  | Collation | Nullable | Default | Storage  | Compression | Stats target | Description …
```

No need for the extra join since `membership` is built-in to `current_state_events`

---

changelog.d/15738.bugfix
synapse/storage/schema/main/delta/77/05thread_notifications_backfill.sql

There appears to be a race where you can end up with entries in `event_push_summary` with both a `NULL` and `main` thread ID.
Fixes #15736
Introduced in https://github.com/matrix-org/synapse/pull/15597

Fix schema delta error in 1.85

---

changelog.d/15695.bugfix
synapse/handlers/room.py
tests/rest/client/test_rooms.py

- If a server was configured to reject the creation of rooms with E2EE enabled (by specifying an unattainably high power level for "m.room.encryption" in default_power_level_content_override), the 403 error was not being triggered until after the room was created and before the "m.room.power_levels" was sent.  This allowed a user to access the partially-configured room and complete the setup of E2EE and power levels manually.
- This change causes the power level overrides to be checked earlier and the request to be rejected before the user gains access to the room.
- A new `_validate_room_config` method is added to contain checks that should be run before a room is created.
- The new test case confirms that a user request is rejected by the new validation method.
- Be a short description …

Check required power levels earlier in createRoom handler.

---

changelog.d/15732.doc
docs/usage/administration/admin_faq.md

Remove redundant `room_memberships` join from admin FAQ to find participating servers in a room
Spawning from https://github.com/matrix-org/synapse/pull/15731

Remove redundant `room_memberships` join from admin FAQ to find participating servers in a room

---

changelog.d/15733.misc
synapse/storage/databases/main/roommember.py

Remove superfluous `room_memberships` join from background update
Spawning from https://github.com/matrix-org/synapse/pull/15731

Remove superfluous `room_memberships` join from background update

---

changelog.d/15740.feature
synapse/metrics/__init__.py
synapse/storage/background_updates.py
synapse/storage/database.py

Tested with the demo scripts briefly:
```
$ curl -s http://localhost:8080/_synapse/metrics | grep background_update_status
synapse_background_update_status 3.0
```

Quick & dirty metric for background update status

---

.github/workflows/tests.yml
changelog.d/15768.misc
docs/upgrade.md
rust/Cargo.toml

Important crates such as `log` and `regex` have bumped theirs to 1.60.0 as well.
Note that 1.60.0 was released in April 2022, so over a year ago. [Our policy](https://github.com/matrix-org/synapse/blob/0b104364f9f118be0ec722894650fad9583bf59c/docs/deprecation_policy.md#context) for bumping minimum Rust version is that we can bump to whatever we like (though we try to avoid requiring very recent versions), so this change matches that policy.
c.f. #15761 and #15472

Bump minimum supported Rust version

---

changelog.d/15755.misc
synapse/federation/federation_client.py

Not just if one key is requested multiple times, e.g. `{"algo1": 2}` and {`"algo1": 1, "algo2": 1}` should both use unstable.

Fix MSC3983 support: Use the unstable /keys/claim federation endpoint if multiple keys are requested

---

changelog.d/15737.feature
synapse/handlers/pagination.py

Avoid backfill when we already have messages to return.
We now only block the client to backfill when we see a large gap in the events (more than 2 events missing in a row according to `depth`), more than 3 single-event holes, or not enough messages to fill the response. Otherwise, we return the messages directly to the client and backfill in the background for eventual consistency sake. 
Fix https://github.com/matrix-org/synapse/issues/15696
For a real-world example with the [trace linked from the issue](https://github.com/matrix-org/synapse/issues/15696) (from viewing the Matrix Public Archive), it makes the following `/messages` request. If we run the JS snippet over the response, we can see that there are no gaps in response and we didn't really need to backfill at all. Which means …

Avoid backfill when we already have messages to return

---

changelog.d/15772.doc
synapse/util/__init__.py

Document `looping_call()` functionality that will wait for the given function to finish before scheduling another
Thanks to @erikjohnston for clarifying, https://github.com/matrix-org/synapse/pull/15743#discussion_r1226544457
We don't have to worry about calls stacking up if the given function takes longer than the scheduled time.

Document `looping_call()` functionality that will wait for the given function to finish before scheduling another

---

changelog.d/15758.bugfix
synapse/storage/databases/main/events.py
synapse/storage/databases/main/events_worker.py
synapse/util/caches/lrucache.py
tests/storage/databases/main/test_events_worker.py

* Fixes #15757 
Add an explicit function for handling future `async` code to add entries into any external caching that may be implemented, and use it in a refactor of how the caching system is prefilled, in the correct order. The new function will no-op, as no actual code for such has been implemented in the Synapse code base(there is however an implementation in Beeper's tree.) Split the existing `prefill` function into two, a `local_prefill()` and an `external_prefill()`, allowing them to be used in the correct order.

Prefill events after invalidate not before when persisting events

---

changelog.d/15781.bugfix
rust/src/push/base_rules.rs
synapse/push/clientformat.py
tests/rest/client/test_push_rule_attrs.py

Also fix wrong rule names for `is_user_mention` and `is_room_mention`.
So we don't store a specific push rule per user, Synapse uses an internal generic representation for `is_user_mention`, and convert it to a spec compliant push rule on the fly.
This conversion is currently happening at the root of the push rule object while it should also be done for each of its `condition`.
Fix #15780.

push rules: fix internal conversion from _type to value

---

changelog.d/15788.bugfix
synapse/storage/database.py

This seems to have been a typo in https://github.com/matrix-org/synapse/pull/12252

Don't always lock "user_ips" table when performing non-native upsert

---

changelog.d/15806.misc
contrib/lnav/synapse-log-format.json
scripts-dev/federation_client.py
synapse/http/federation/matrix_federation_agent.py
synapse/http/matrixfederationclient.py
tests/federation/test_federation_client.py
tests/http/federation/test_matrix_federation_agent.py

Switch from `matrix://` to `matrix-federation://` scheme for internal Synapse routing of outbound federation traffic
`matrix://` is a registered, specced scheme nowadays and doesn't make sense for our internal to Synapse use case anymore. ([discussion](https://github.com/matrix-org/synapse/pull/15773#discussion_r1227598679))
Split out from https://github.com/matrix-org/synapse/pull/15773 to reduce the diff clutter there.

Switch from `matrix://` to `matrix-federation://` scheme for internal Synapse routing of outbound federation traffic

---

changelog.d/15805.doc
docs/admin_api/rooms.md

Fix admin api documentation typo

---

.github/workflows/tests.yml
changelog.d/15804.bugfix

This was subtle: the code as it was before this change assigned the Sytest environment variables with an expression that evaluated to either true or false. However, since the Sytest script only checks that the environment variable is non-empty, the environment variables that were assigned false were still counted and the part of the script run gated by that variable still ran. In practice this means that Sytest has been running on mulitpostgres for all of it's runs. 
This PR fixes this by replacing the expression that evaluated to true or false with one that evaluates to either true or an empty string. You can verify that this change is correct by checking the output of the Sytest runs below against the expected output from https://github.com/matrix-org/sytest/blob/develop/scripts/synapse_ …

Fix Sytest environmental variable evaluation in CI 

---

changelog.d/12504.misc
changelog.d/15783.misc
docs/usage/configuration/config_documentation.md
synapse/config/federation.py
synapse/http/matrixfederationclient.py
tests/http/test_matrixfederationclient.py

This is a revival of https://github.com/matrix-org/synapse/pull/12504.
It is now using `get_duration`, and the config var names have the unit in their name.

Allow for the configuration of max request retries and min/max retry delays in the matrix federation client

---

changelog.d/15812.doc
docs/development/synapse_architecture/faster_joins.md

Fix typo in faster join docs

---

changelog.d/15815.bugfix
synapse/storage/databases/main/cache.py
tests/handlers/test_room_member.py

If you leave a room and forget it, then rejoin it, the room would be missing from the next initial sync.
fixes #13262

Fix forgotten rooms missing in initial sync

---

changelog.d/15817.bugfix
synapse/storage/schema/main/delta/78/02_validate_and_update_user_filters.py
synapse/storage/schema/main/delta/78/03_remove_unused_indexes_user_filters.py
synapse/storage/schema/main/delta/78/04_add_full_user_id_index_user_filters.py

This PR fixes the upgrade to `user_filters` introduced in https://github.com/matrix-org/synapse/pull/15649. The PR set the columns `full_user_id` and `user_id` to be unique which is incorrect (there is a unique index on `user_id`, `filter_id`). The PR also adds a unique index on `full_user_id`, `filter_id` which I apparently forgot in the original upgrade. Fixes #15809.

Fix sqlite `user_filters` upgrade

---

changelog.d/15853.misc
synapse/storage/engines/postgres.py

We hit a problem where an 8-hour event search query (which the client had already walked away from) caused Postgres to not be able to vacuum, which in turn causes general DB slowness and notably
updating stream positions was slow, so event persistence was slow and an apdex page was raised.
I propose that we limit statements to 1 hour by default. I propose that we consider anything taking more than 1 hour to be a bug as it blocks Postgres from vacuuming, which is more or less essential housekeeping.
I considered going tighter but I am not sure if some of our background or admin operations might rely on longer-running queries and I think I would rather start at 1 hour and tighten later if we think that is sensible.
This limit is technically configurable but we also don't document …

Add a timeout that aborts any Postgres statement taking more than 1 hour.

---

.gitignore
changelog.d/15854.misc
flake.nix

I was confused when this wasn't hitting any of the logging I set for Postgres, then noticed that the database was empty. Oh.
Follows: #15613 
<ol>
<li>
Fix use of config override directory in `devenv up` \
`--config-directory` is for the generate config script; `-c` is for usage
</li>
<li>
Add homeserver config override directory to gitignore 
</li>
</ol>

Fix the `devenv up` configuration which was ignoring the config overrides.

---

changelog.d/15844.feature
docs/admin_api/user_admin_api.md
synapse/rest/admin/users.py
synapse/storage/databases/main/__init__.py
tests/rest/admin/test_user.py

closes https://github.com/matrix-org/synapse/issues/15720

Add not_user_type param to the list accounts admin API

---

changelog.d/15876.bugfix
synapse/media/thumbnailer.py

This fixes #15873.
Image.ANTIALIAS is not defined in current pillow releases. Since ANTIALIAS was just using LANCZOS anyways, this is just a cosmetic change, but makes synapse work …

use Image.LANCZOS instead of Image.ANTIALIAS for thumbnail resize

---

changelog.d/15826.misc
synapse/storage/databases/main/presence.py

* Fixes #15827
I considered(and tested) using a Linearizer for this, I liked it's queueing behavior. However on further investigation, I found out that this type of situation has occurred before in Synapse history and was simply changing the isolation level to be slightly less strict than the default of `REPEATABLE_READ`. Using `READ_COMMITTED` allows the `DELETE` transaction to continue, even if it means the `DELETE` not seeing the concurrent transaction taking place to add a lower Stream ID(that this `DELETE` would otherwise have removed). Since either function will run again shortly, it will then subsequently remove the lower Stream ID entry and all will be well. The Postgres docs suggest that depending on the order of the transaction, it may still go ahead and `DELETE` the row anyways …

Fix could not serialize access due to concurrent `DELETE` from presence_stream

---

changelog.d/15852.doc
docs/admin_api/user_admin_api.md

As is, there are a couple of entries that are incorrectly nested under the "Override ratelimiting for users" header:
This PR fixes this.

docs/admin_api: fix header level on 'Users' page

---

.ci/scripts/calculate_jobs.py
.github/workflows/release-artifacts.yml
.github/workflows/tests.yml
changelog.d/15851.removal
docker/Dockerfile-dhvirtualenv
docs/setup/installation.md
docs/upgrade.md
poetry.lock
pyproject.toml
synapse/__init__.py
synapse/util/check_dependencies.py
tests/metrics/test_metrics.py

Remove support for Python 3.7
Fix https://github.com/matrix-org/synapse/issues/15836
1. Update `python = "^3.8.0"` in `pyproject.toml`
1. `poetry lock --no-update`

Remove support for Python 3.7

---

changelog.d/15860.removal
docs/upgrade.md
docs/usage/configuration/config_documentation.md
docs/workers.md
synapse/config/workers.py
tests/app/test_homeserver_start.py
tests/config/test_workers.py

What it says on the tin. <del>Needs Sytest modifications.</del> Needs [#sytest/1357](https://github.com/matrix-org/sytest/pull/1357)
I'm not going to mark this as fixing the [issue](https://github.com/matrix-org/synapse/issues/15655) that's related, but if we could update that and pin it for another month, I'll finish the removal then.

Remove `worker_replication_*` deprecated settings, with helpful errors on startup

---

.ci/scripts/calculate_jobs.py
changelog.d/15892.misc

After noticing that tests were failing on merge, I found that we are still running Sytest on buster/python3.7, which now results in failure as we have [dropped support for Python 3.7](https://github.com/matrix-org/synapse/pull/15851). This PR drops this run from ci. Note that this was only being run against merges, not PRs.

Stop running sytest on buster/python3.7

---

changelog.d/15907.misc
synapse/storage/background_updates.py
synapse/storage/databases/main/event_federation.py
synapse/storage/schema/main/delta/78/03event_extremities_constraints.py
tests/storage/test_background_update.py

We do this by marking the constraint as deferrable.
c.f. #15751

Fix downgrading to previous version of Synapse

---

.github/workflows/twisted_trunk.yml
changelog.d/15893.misc
docs/deprecation_policy.md
docs/development/contributing_guide.md
scripts-dev/build_debian_packages.py

As part of the work around dropping python 3.7 drop any old references to buster/update any places we were still using it. 
Follow-up to:
- https://github.com/matrix-org/synapse/pull/15892
- https://github.com/matrix-org/synapse/pull/15851

Drop debian buster

---

changelog.d/15888.misc
synapse/media/media_storage.py
synapse/media/storage_provider.py

Make the media `/upload` tracing less ambiguous. A lot of the functions have the same name in this space like `store_file`, and we also do it multiple times for different reasons (main media repo, other storage providers, thumbnails, etc) so it's good to differentiate them so your head doesn't explode.
Follow-up to https://github.com/matrix-org/synapse/pull/15850
Tracing instrumentation to media `/upload` code paths to investigate https://github.com/matrix-org/synapse/issues/15841
Before | After
--- | ---

Make the media `/upload` tracing less ambiguous

---

changelog.d/15908.misc
synapse/http/server.py
tests/test_server.py

Like https://github.com/matrix-org/synapse/pull/14974 but for https://github.com/vector-im/element-web/issues/11070 - without this the Server header is not accessible to Web browser clients
(run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-lin …

Add `Server` to Access-Control-Expose-Headers header

---

changelog.d/15924.feature
docs/usage/configuration/config_documentation.md

Bump Unix sockets intro version
https://github.com/matrix-org/synapse/pull/15708 didn't quite make the cut for `1.88.0` this morning.

Bump Unix sockets intro version

---

changelog.d/15922.misc
synapse/handlers/directory.py

*Spawning from creating the [manual testing strategy for the outbound federation proxy](https://github.com/matrix-org/synapse/pull/15773).*
Better warning in logs when we fail to fetch an alias
**Before:**
```
Error retrieving alias
```
**After:**
```
Error retrieving alias #foo:bar -> 401 Unauthorized
```

Better warning in logs when we fail to fetch an alias

---

changelog.d/15921.doc
docs/workers.md

*Spawning from creating the [manual testing strategy for the outbound federation proxy](https://github.com/matrix-org/synapse/pull/15773).*
This was one sticking point I had when trying to run a worker setup.
Previously, if you just followed the instructions per the docs, you just ran into an error:
```sh
$ poetry run synapse_worker --config-path homeserver_generic_worker1.yaml
Missing mandatory `server_name` config option.
```

Better clarify how to run a worker instance (pass both configs)

---

changelog.d/15884.misc
synapse/storage/databases/main/user_directory.py
tests/handlers/test_user_directory.py
tests/rest/admin/test_user.py

Rename `get_user_in_directory` to `_get_user_in_directory` to mark it as private since it is only used in tests.
Also remove the cache out of it for simplification.

Mark get_user_in_directory private since only used in tests

---

changelog.d/15926.misc
synapse/federation/transport/server/federation.py

`FederationV2SendJoinServlet__ini__` simply calls `super().__init__(...)` with all the same input arguments.

Remove unneeded __init__.

---

changelog.d/15928.removal
docs/upgrade.md
synapse/rest/client/register.py

This has always been non-standard. We deprecated this several versions ago, let's remove it.
Fixes #9547

Stop accepting 'user' parameter for application service registration.

---

changelog.d/15938.doc
docs/admin_api/user_admin_api.md

This bit me today. I suspect it's a sensible security precaution, but we should call it out.

Mention that you cannot login as yourself on /_synapse/admin/v1/users/<user_id>/login

---

changelog.d/15940.misc
flake.lock
flake.nix

This PR addresses two problems:
1. Our nix flake development environment was always tracking the latest stable rust version. However, due to the nature of nix, that would be pinned to the git revision of https://github.com/nix-community/fenix defined in our `flake.lock` (which before this PR, gave us rust 1.69.0).
Ideally we would actually install Synapse's minimum supported version of Rust, so that we don't accidentally introduce any new rust features while developing. As far as I can tell [from our CI](https://github.com/matrix-org/synapse/blob/8d3656b994173b899ce2be18a2600273aa4e7d32/.github/workflows/tests.yml#L310-L311), this is 1.60.0.
So commit https://github.com/matrix-org/synapse/commit/0f50ea55d5c7c95a87a217d87c9f3bfe24dae790 pins the version of Rust defined in our flake.nix - …

Pin the rust version in `flake.nix`, and bump to 1.70.0 to fix installing `ruff`

---

changelog.d/15952.misc
synapse/handlers/presence.py

...to easily see if a presence state being processed is for a local or remote user.
Turns this:
Into being able to do this:
Notes:
To make this pretty, change the Legend template to include `{{locality}}`
I used `{{job}}{{index}}: {{locality}}:{{from}} -> {{to}}` for mine.
Turns this:
Into being able to do this:
Notes:
To make this pretty, change the Legend template to include `{{locality}}`.
I used `{{job}}{{index}}: {{locality}}:{{reason}}` for mine.

Add a locality to a few presence metrics

---

changelog.d/15887.misc
synapse/storage/schema/main/delta/78/05_mitigate_stream_ordering_update_race.py

Prior to this, if Synapse was upgraded from a sufficiently old version foreground migrations touching the `stream_ordering` column of the events table would apply before a background job also touching the same column was finished, resulting in the background job failing. Fixes https://github.com/matrix-org/synapse/issues/15677.
This work supercedes #15724, which turned out to be unworkable.

Fix background schema updates failing over a large upgrade gap

---

changelog.d/15960.misc
synapse/state/v2.py

We do this by yielding the reactor in hot loops.
Note: we do this already in other places in state res.

Ensure a long state res does not starve CPU

---

changelog.d/15968.misc
synapse/handlers/federation.py
synapse/handlers/message.py
synapse/handlers/room_member.py

This especially should help when deduplicating new state events for common types

Reduce the amount of state we pull out

---

changelog.d/15969.feature
synapse/http/server.py

Don't log exceptions for every non-200 response

---

changelog.d/15955.misc
synapse/storage/databases/main/__init__.py
synapse/storage/databases/main/stats.py
synapse/storage/databases/main/user_directory.py
tests/rest/admin/test_user.py

Per the title, these are stray reads I found after trying to drop the column `user_id`. The original work to shift reading from `user_id` to `full_user_id` was in https://github.com/matrix-org/synapse/pull/15649 but apparently I missed these when doing that.

Actually stop reading from column `user_id` of tables `profiles`

---

changelog.d/15973.bugfix
synapse/events/utils.py
tests/events/test_utils.py

Fixes https://github.com/matrix-org/synapse/issues/15962 and https://github.com/matrix-org/synapse/issues/15963.
Ensures that 
a: the `content` field is wholly preserved when redacting an event in room v11, but other non-allowed fields are removed, and that
b: the `creator` field is only added back when redacting an event in rooms < v11, leading to a partial redaction of `content`.
Note that there is already a test for b, as the behavior here is technically not changing but is made more explicit.

Properly handle redactions of creation events

---

changelog.d/15975.bugfix
synapse/handlers/device.py

This is so we don't block responding to federation transaction while we try and fetch the device lists.
Requires: https://github.com/matrix-org/sytest/pull/1359

Resync stale devices in background

---

changelog.d/15981.doc
docs/setup/installation.md

`Signed-off-by: Andrej Halveland <andrej.halv@gmail.com>`

Fix broken Arch Linux package link

---

changelog.d/15964.removal
synapse/appservice/api.py
tests/appservice/test_api.py

https://github.com/matrix-org/synapse/pull/15317 added support for using `/_matrix/app/v1` prefix and falling back to legacy paths if those failed - and deprecated these legacy paths. This PR removes support for the legacy paths in accordance with the deprecation. Fixes #15380.

Remove support for legacy application service paths

---

.github/workflows/docker.yml
changelog.d/16009.docker

Per https://github.com/matrix-org/synapse/pull/15972#issuecomment-1652665329
Completely untested. Suggest we YOLO merge this and see what the labels look like on the `develop` docker build.

Attempt to fix labelling in docker workflow

---

changelog.d/16012.bugfix
synapse/handlers/profile.py
tests/handlers/test_profile.py

Fix 404 on /profile when the display name is empty but not the avatar

---

changelog.d/16023.misc
synapse/handlers/message.py
synapse/handlers/room_member.py

I pulled this out of #15629 as it is a refactor, not actually stabilizing support. (And it is making the diff of that PR a little worse, even though that PR isn't too large.)
----
We have two bits of code which attempt to take a transaction ID and get the corresponding event ID. One is embedded in `get_event_from_transaction_id` and one is inline as part of `_local_membership_update`. I've combined them by pulling out the one from `get_event_from_transaction_id` (and creating an `get_event_id_from_transaction_id`) and calling it in both spots.
The logic is a little different in the two since `get_event_from_transaction_id` would return early while `_local_membership_update` didn't, but the new function should match the logic of both.

Combine duplicated code for calculating an event ID from a txn ID

---

changelog.d/16031.bugfix
synapse/handlers/profile.py
tests/rest/client/test_profile.py

(run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linters)
This code is not exploitable by the exploit i said earlier when user send only spaces in thier displayname.

Trim whitespace when setting display names

---

changelog.d/16043.bugfix
synapse/_scripts/synapse_port_db.py

The `synapse_port_db` script is missing configuration of some sequences. This results in a failure when Synapse starts. The sequences were added in:
* `application_services_txns` #12209
* `un_partial_stated_event_stream_sequence` #14545
This PR replaces #15965 to use abstract code instead of custom code for the AS sequence and should fix #16040.

Properly setup more sequences in portdb

---

changelog.d/16044.misc
poetry.lock

We have some logs about failed dependabot updates for these.

Update certifi to 2023.7.22 and pygments to 2.15.1.

---

changelog.d/16019.misc
flake.lock
flake.nix

This commit updates the version of nixpkgs that is pinned in `flake.lock` from [7a32a141db568abde9bc389845949dc2a454dfd3](https://github.com/NixOS/nixpkgs/commit/7a32a141db568abde9bc389845949dc2a454dfd3) to [8cacc05fbfffeaab910e8c2c9e2a7c6b32ce881a](https://github.com/NixOS/nixpkgs/commit/8cacc05fbfffeaab910e8c2c9e2a7c6b32ce881a). The new revision contains NixOS/nixpkgs#245747, which allows `debian-devscripts` to be built on MacOS (darwin).
Our development environment requires the `dch` tool from that package to update the Debian changelog during releases.
This has the side-effect of update all the other tools referenced in `flake.nix` as well, other than Rust which is manually pinned.
Thanks for @sandhose for testing it on their M1 Mac.

Update `flake.lock` to fix running the nix developer environment on MacOS

---

changelog.d/16013.bugfix
changelog.d/16013.misc
synapse/events/utils.py
tests/rest/client/test_redactions.py

Part of #15823, see https://github.com/matrix-org/synapse/issues/15823#issuecomment-1651983406
tl;dr is that for "older" room versions we should be injecting the `redacts` field into the `content` (for the Client-Server API) to make it easier to write client code. This is similar to how we (in #15912) added backwards compatibility support for the `redacts` field over the Client-Server API in room version 11.
This also fixes the tests to actually test what I wanted. 🤦

Add forward compatibility for the redacts property.

---

changelog.d/15991.misc
synapse/module_api/__init__.py

<ol>
<li>
Add module API function to ask whether the current worker is configured for background tasks 
</li>
</ol>

Allow modules to check whether the current worker is configured to run background tasks.

---

changelog.d/16046.bugfix
synapse/handlers/device.py
synapse/rest/client/devices.py
tests/rest/client/test_devices.py

The DELETE method for the `unstable/org.matrix.msc3814.v1/dehydrated_device` endpoint was deleting the old dehydrated device rather than the current one. This PR adds a simple function to delete the dehydrated device, and employs it 
- when DELETE is called
- when a new device is PUT by the user
as well as adding a test to verify that it is working. Fixes #16022.

Fix deletion for Dehydrated Devices

---

changelog.d/16015.doc
docs/SUMMARY.md
docs/development/synapse_architecture/streams.md

Wrote these up to understand WTF is going on, and I may as well try to save others from having to do the same in the future.
[Rendered](https://pr16015--synapse-docs-previews.netlify.app/development/synapse_architecture/streams#2)

Add notes describing Synapse's streams

---

changelog.d/16069.misc
synapse/events/snapshot.py

This workaround was originally added in https://github.com/matrix-org/synapse/pull/15233, which changed the format of `EventContext`. The workaround was to allow compatibility between workers and main which were using different formats of `EventContext`. Now that a few releases have passed it should be fine to remove. Fixes #15777.

Drop backwards compat hack for event serialization

---

changelog.d/16092.misc
synapse/handlers/presence.py

This is split out of #16066 / things I learned while doing that. It makes a handful of changes which are unrelated, but all various clean-ups.

Clean-up presence code

---

changelog.d/16089.misc
synapse/module_api/__init__.py

<ol>
<li>
Fix the method signature of `run_db_interaction` on the module API 
</li>
</ol>

Fix the type annotation on `run_db_interaction` in the Module API.

---

changelog.d/16094.feature
docs/usage/configuration/config_documentation.md
synapse/config/cas.py
synapse/config/saml2.py
synapse/handlers/cas.py
synapse/handlers/saml.py

Signed-off-by: Gabriel Rodríguez <rgabriel@mit.edu>

Allow customizing IdP name and icon for SAML and CAS

---

.github/workflows/twisted_trunk.yml
changelog.d/16115.misc
mypy.ini
synapse/util/manhole.py

Correctly pull twisted trunk when triggered overnight and ignore known type error

---

changelog.d/16112.misc
synapse/federation/federation_server.py
synapse/handlers/message.py
synapse/handlers/pagination.py
synapse/handlers/room_member.py
synapse/handlers/worker_lock.py
synapse/rest/client/room_upgrade_rest_servlet.py
synapse/storage/controllers/persist_events.py

Rename pagination&purge locks and add comments explaining them

---

changelog.d/16080.bugfix
synapse/handlers/sync.py

Disable caching in /sync corner case

---

changelog.d/16085.misc
synapse/storage/background_updates.py

#15853 added a global timeout for long-running Postgres statements, but this may interfere with long-running index creation. This PR adds a local statement timeout to override the global timeout and disable it when creating an index in the background. Fixes #15942.

Override global statement timeout when creating indexes in Postgres

---

changelog.d/16061.misc
synapse/storage/databases/main/lock.py
tests/storage/databases/main/test_lock.py

We were seeing serialization errors when taking out multiple read locks.
The transactions were retried, so isn't causing any failures.
Introduced in #15782.

Fix database performance of read/write worker locks

---

changelog.d/16117.misc
synapse/api/auth/msc3861_delegated.py
tests/handlers/test_oauth_delegation.py

This PR adds an expiring cache to the result of the `_introspect_token` of the  `MSC3861DelegatedAuth` class. The cache expires after five minutes, and the token introspection response is checked for expiration both when the response is pulled from the cache and when the response is received over network (although I am not sure if the second check is necessary, would the authorizing server ever send an introspection response with an expired `exp` field?).
A follow-on PR will add an endpoint for receiving revocations from the authorizing server.

Cache token introspection response from OIDC provider

---

changelog.d/16123.misc
synapse/rest/key/v2/remote_key_resource.py
synapse/storage/databases/main/keys.py
synapse/storage/keys.py
tests/crypto/test_keyring.py

Plus a lot of refactoring. 
Note that Synapse really only generates queries to this API for a single server name and a specific set of key IDs (rather than for multiple servers, or for all keys for a given server).

Add cache to `get_server_keys_json_for_remote`

---

changelog.d/16131.misc
synapse/api/auth/msc3861_delegated.py

Add response time metrics for introspection requests

---

changelog.d/16132.misc
synapse/api/auth/msc3861_delegated.py
tests/handlers/test_oauth_delegation.py

Related to https://github.com/matrix-org/synapse/issues/16129.
The query parameter used for impersonation is `_oidc_admin_impersonate_user_id`.

MSC3861: allow impersonation by an admin using a query param

---

changelog.d/16116.bugfix
synapse/storage/databases/main/event_federation.py
tests/storage/test_event_federation.py

If we don't have all the auth events in a room then not all state events will have a chain cover index. Even so, we can still use the chain cover index on the events that do have it, rather than bailing and using the slower functions.
This situation should not arise for newly persisted rooms, as we check we have the full auth chain for each event, but can happen for existing rooms.
c.f. #15245

Speed up state res in rare case we don't have all events

---

changelog.d/16030.feature
docs/usage/configuration/config_documentation.md
synapse/config/oidc.py

That way you don't have to leak your bind password into your config. Useful for e.g. NixOS where config is stored in a world-readable location.
Tested against a live synapse instance with authentik as OIDC provider.
(run the [linters](https://matrix-org.github.io/synapse/latest/development/contribut …

Add `client_secret_path` as alternative for `client_secret` for OIDC config

---

changelog.d/16127.bugfix
synapse/config/experimental.py
tests/config/test_oauth_delegation.py

Fixes https://github.com/matrix-org/synapse/issues/16126

Disallow user_consent where experimental MSC3861 is enabled

---

changelog.d/16150.misc
tests/server.py

This gets called anyway via `hs.setup()`:
https://github.com/matrix-org/synapse/blob/358896e1b835bf693ef40d4cf9f10077432e935b/synapse/server.py#L346-L347
This is important in that `hs.setup()` has an extra if-statement which *only* runs this code if the worker is running background tasks, instead of unconditionally.
Spun out of #16066.

Do not call setup_background_tasks twice in tests.

---

changelog.d/16152.misc
pyproject.toml

A new poetry-core version was released. Can we run the CI and see if it passes?

Raise poetry-core version cap to 1.7.0

---

changelog.d/16157.misc
tests/handlers/test_user_directory.py

Per @DMRobertson's explanation:
> I think the invariant that the test should be asserting is:
> * after deactivating the support user, it should not be visible in the user directory

Fix user directory test for deactivated support user.

---

changelog.d/16148.bugfix
synapse/replication/tcp/client.py

If we have lots of stuff waiting we ended up consuming lots of CPU.

Fix perf of `wait_for_stream_positions`

---

changelog.d/16149.misc
synapse/storage/schema/main/delta/80/02_read_write_locks_unlogged.sql.postgres

We do this by marking the tables as `UNLOGGED` in PostgreSQL.

Increase perf of read/write locks

---

changelog.d/16159.misc
synapse/handlers/federation.py
synapse/handlers/pagination.py

This reduces the amount of writes happening to the worker lock tables.
Note: the changes in pagination are mostly whitespace.

Only lock when we're backfilling

---

changelog.d/16156.bugfix
synapse/storage/databases/main/transactions.py
tests/util/test_retryutils.py

This was broken in 1.87 when the maximum retry interval got changed from almost infinite to a week (and made configurable).
fixes #16101

Properly update retry_last_ts when hitting the maximum retry interval

---

changelog.d/16165.misc
synapse/storage/databases/main/task_scheduler.py
synapse/util/task_scheduler.py

It is mainly useful so we have coherency if we look up tasks right after scheduling one ASAP.
Another small bug fixed on the way.

Task scheduler: mark task as active if we are scheduling ASAP

---

changelog.d/16164.bugfix
synapse/storage/databases/main/transactions.py

Follow on from #16156
I think by updating `retry_last_ts` we recover from the failure modes quicker (as we don't need to wait for the retry interval to ramp up?)

Always update `retry_last_ts`

---

changelog.d/16063.misc
flake.lock
flake.nix

https://github.com/cachix/devenv/issues/756 introduced a regression into the development branch of devenv which caused the `devenv up` command (which we utilise to start up a local Synapse, postgres and redis) to return an error.
We updated our pinned dependencies in https://github.com/matrix-org/synapse/pull/16019. This would have been caught if someone ran 'devenv up' during manual testing of that PR, or better yet, if we had CI for the nix developer environment.
This PR switches back to the latest release version of devenv ([v0.6.3](https://github.com/cachix/devenv/releases/tag/v0.6.3)), which doesn't have the regression. We are not relying on any features introduced since that version was tagged.
Uses the same changelog as https://github.com/matrix-org/synapse/pull/16019.

Switch `devenv` dependency in the nix development environment to the latest release (instead of the development branch)

---

changelog.d/16113.feature
rust/benches/evaluator.rs
rust/src/push/base_rules.rs
rust/src/push/evaluator.rs
rust/src/push/mod.rs
stubs/synapse/synapse_rust/push.pyi
synapse/config/experimental.py
synapse/storage/databases/main/push_rule.py
tests/push/test_bulk_push_rule_evaluator.py

MSC3958 passed FCP, we can stabilize it by updating the ID & removing the experimental configuration flag (and related clean-up).
See [MSC3958](https://github.com/matrix-org/matrix-spec-proposals/pull/3958) to double check I didn't typo. 😄

Stabilize support for MSC3958 (suppress notifications from edits)

---

.github/workflows/twisted_trunk.yml
changelog.d/16121.misc
synapse/handlers/message.py
synapse/logging/context.py
synapse/util/caches/deferred_cache.py
tests/util/test_async_helpers.py

Fix typechecking with twisted trunk

---

changelog.d/16178.doc
docs/usage/configuration/config_documentation.md

As the title states - adds documentation about this option to the configuration docs.

 Document `exclude_rooms_fom_sync` configuration option

---

changelog.d/16168.doc
docs/admin_api/account_validity.md
docs/admin_api/register_api.md
docs/admin_api/user_admin_api.md
docs/usage/administration/admin_api/registration_tokens.md

Fixes #16161 
This attempts to outline the things which are disabled when MSC3861 in the docs.

Add warnings about MSC3861 on certain APIs.

---

changelog.d/16180.misc
tests/api/test_auth.py
tests/appservice/test_appservice.py
tests/appservice/test_scheduler.py
tests/events/test_presence_router.py
tests/handlers/test_appservice.py
tests/handlers/test_cas.py
tests/handlers/test_oauth_delegation.py
tests/handlers/test_oidc.py
tests/handlers/test_saml.py
tests/module_api/test_api.py
tests/push/test_bulk_push_rule_evaluator.py
tests/rest/client/test_notifications.py
tests/storage/test_background_update.py
tests/test_utils/__init__.py

This was almost exactly `s/simple_async_mock/AsyncMock/g`, minus the `raises` flag being renamed to `side_effect`.
Builds on #16179.
Note that `AsyncMock` was added in Python 3.8.

Replace simple_async_mock with AsyncMock

---

changelog.d/16185.bugfix
synapse/federation/transport/client.py

When using a search filter with `include_all_networks`, Synapse currently sends invalid data (strings instead of bools). It seems this was *always* this way from #5859, although a similar issue with `limit` was fixed in #12364.
Note that when *parsing* this Synapse [doesn't attempt to convert the string](https://github.com/matrix-org/synapse/blob/8e9739449dd6d3c133adf9e995d27d06518a0bcf/synapse/federation/transport/server/__init__.py#L167), so both of these would be treated as `True`.
Also has some misc. clean-up.

Send proper JSON POST data to /publicRooms

---

changelog.d/16183.misc
synapse/rest/key/v2/remote_key_resource.py

Validates the `/_matrix/key/v2/query` body instead of throwing 500 errors. Should fix https://sentry.tools.element.io/organizations/element/issues/84082/ and https://sentry.tools.element.io/organizations/element/issues/84696/
Related to #13147 
I haven't really used pydantic before, but I did a bunch of testing and this is decently tested by sytest already.

Validate input to /key/query endpoint.

---

changelog.d/16186.misc
mypy.ini

There's no reason to exclude their imports anymore. Luckily mypy didn't detect any errors when doing so! 🎉

service-identity, incremental, and setuptools-rust now have type hints.

---

changelog.d/16171.misc
synapse/handlers/events.py
synapse/handlers/message.py
synapse/handlers/presence.py
synapse/replication/http/presence.py
synapse/rest/client/presence.py
synapse/rest/client/read_marker.py
synapse/rest/client/receipts.py
synapse/rest/client/room.py
synapse/rest/client/sync.py
tests/handlers/test_presence.py

Refactoring such that the presence code knows about the user ID & device ID in many places. Note the device ID is unused at this point.
Builds on #16170. Spun out of #16066.

Pass the device ID around in the presence handler

---

changelog.d/16205.bugfix
synapse/event_auth.py

Resolved issue#16202 of an inaccurate error message displaying "You don't have permission to ban" while attempting to ban or unban a user with the same or higher PL. Restructured the conditional statements to provide a more precise error message: "You don't have permission to ban this user."
Fixes matrix-org/synapse#16202

Fix inaccurate error message while trying to ban or unban a user with the same or higher PL

---

changelog.d/16187.misc
poetry.lock
pyproject.toml

We no longer target Python 3.7 and *do* target Python 3.11.
Bump the black version while we're here.
Note that this has no meaningful impact, but wanted to correct it while I saw it.
Closes #16197

Fix black's Python target configuration

---

changelog.d/16155.bugfix
synapse/handlers/send_email.py
tests/handlers/test_send_email.py
tests/server.py
tests/unittest.py

While there, do it in such a fashion that we both document and prepare the groundwork for similar issues relating to direct usage of reactor.connectTCP, which lead to IPv6 incompatibilities.
Closes #7720
(run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.ht …

Fix IPv6-only bugs on SMTP settings

---

changelog.d/16210.bugfix
synapse/storage/databases/main/lock.py
tests/storage/databases/main/test_lock.py

We can't interact with the reactor from the main thread via looping call. If you do then you can break existing looping calls (due to changing list size during iteration).
Introduced in v1.90.0 / #15791.
Example stack trace:
```
2023-08-30 07:44:09,624 - twisted - 275 - CRITICAL - sentinel - 
File "/home/erikj/.synapse39/lib/python3.9/site-packages/twisted/internet/defer.py", line 892, in _runCallbacks
current.result = callback(  # type: ignore[misc]
File "/home/erikj/.synapse39/lib/python3.9/site-packages/twisted/internet/task.py", line 238, in cb
self._scheduleFrom(self.clock.seconds())
File "/home/erikj/.synapse39/lib/python3.9/site-packages/twisted/internet/task.py", line 291, in _scheduleFrom
self.call = self.clock.callLater(howLong(), self)
File …
```

Fix rare bug that broke looping calls

---

changelog.d/16211.bugfix
synapse/__init__.py
synapse/media/media_repository.py

This is done by:
1. telling pillow that we don't mind truncated jpegs; and
2. ignoring failures to create thumbnails
I'm not 100% convinced that we should do the second one, in case there is a temporary problem generating the thumbnails.

Gracefully handle failing to thumbnail images

---

.github/workflows/latest_deps.yml
changelog.d/16213.misc

See https://github.com/matrix-org/synapse/issues/16100#issuecomment-1699317096
Closes https://github.com/matrix-org/synapse/issues/16100.

Ignore redundant casts in latest deps CI job

---

changelog.d/16220.misc
synapse/server.py

I don't think has caused any actual issues.
Introduced in #15891

Fix typo where we ended up with multiple `WorkerLocksHandler`

---

changelog.d/16241.misc
synapse/replication/http/devices.py

We have tested this internally on matrix.org and it has seemed to work well in practice.

Cache device resync requests over replication

---

changelog.d/16221.bugfix
synapse/federation/sender/per_destination_queue.py
synapse/federation/transport/client.py
synapse/http/matrixfederationclient.py
synapse/util/retryutils.py
tests/handlers/test_typing.py

Basically, we have a bunch of servers that return 404 or 403 etc to all requests. Those error codes are valid for *some* APIs, which ends up resetting the retry timers even though the server is still down. We fix this by not resetting the retry timer for those cases. This is fine as if the server *has* come back up, a subsequent request will get a 200 and reset the timers.

Don't reset retry timers on "valid" error codes

---

changelog.d/16174.bugfix
synapse/handlers/presence.py
tests/handlers/test_presence.py

Adds tests for the (unstable) busy presence with multiple workers (i.e. #16066, but for busy). It then also fixes those tests by adding a (long) timeout to when a "busy" device can timeout. This is kind of against what [MSC3026](https://github.com/matrix-org/matrix-spec-proposals/pull/3026) calls for, but I think implementation-wise it is the only reasonable thing to do. See https://github.com/matrix-org/matrix-spec-proposals/pull/3026#discussion_r1287453423 for MSC thread.
Spun-out of #16066. Builds on #16170, #16171, #16172, and #16066.

Time out busy presence status & test multi-device busy

---

changelog.d/16255.misc
synapse/api/ratelimiting.py

Fix-up incorrect docstring for Ratelimiter.

---

changelog.d/16257.bugfix
synapse/storage/databases/main/keys.py

We have two tables:
1. `server_keys_json` which stores the raw JSON that we got, and is unique on `(server_name, key_json, from_server)`.
2. `server_signature_keys` which stores the JSON fields as columns, and is unique on `(server_name, key_json)`
When fetching keys from the store in `Keyring`, we used the first table. However, the fetch function didn't correctly account for multiple rows per server / key ID, and so would return whichever row happened to be returned last by Postgres. (This is often the most recent row, but also often not). 
The fix here is: a) fix the read path to return the most recently added key JSON, and b) use the `server_signature_keys` instead for `Keyring` as we don't need the full JSON anyway.

Fix bug where we kept re-requesting a remote server's key repeatedly. 

---

changelog.d/16251.bugfix
synapse/storage/databases/main/deviceinbox.py
tests/handlers/test_appservice.py

This was a *really* subtle bug, but it caused a great deal of pain. In order to fetch to_device messages for an appservice, we must fetch all the devices an AS has control over. We were doing this filter, but mistakenly left in an extra clause that would filter for the *last* user_id in the set of users.
Why? Because Python is awful, and just above this statement there was a for loop that used the `user_id` variable to do some filter logic. This code worked because that variables was still in scope, and therefore the device query code looked like it worked...until you tried to use it with two user_ids.
Dropping this clause makes Synapse correctly calculate new messages for *all* users in the appservice namespace.

Fix appservices being unable to handle to_device messages for multiple users

---

changelog.d/16262.feature
docs/usage/configuration/config_documentation.md
synapse/config/cas.py
synapse/handlers/cas.py
tests/handlers/test_cas.py

Signed-off-by: Aurélien Grimpard [aurelien@grimpard.net](mailto:aurelien@grimpard.net)
This PR is related to this issue : fixes #15775

Handle "registration_enabled" parameter for CAS

---

changelog.d/16265.feature
docker/configure_workers_and_start.py
docs/workers.md
synapse/rest/__init__.py
synapse/rest/client/notifications.py
synapse/storage/databases/main/event_push_actions.py

Because why not.
Tested by https://github.com/matrix-org/sytest/pull/1369

Add `/notifications` endpoint to workers

---

changelog.d/16266.misc
scripts-dev/release.py

These were changes I had to make to the release script in order to get 1.91.2 out the door.

Support releasing on macOS.

---

changelog.d/16277.misc
pyproject.toml

Request to raise the defensive version cap of setuptools_rust to 1.7.0.

Raise setuptools_rust version cap to 1.7.0

---

changelog.d/16272.bugfix
synapse/rest/client/account.py
tests/rest/client/test_account.py

Fix a regression from #13188 and add a test.

Avoid temporary storage of sensitive information.

---

changelog.d/16278.misc
synapse/util/task_scheduler.py

Using the new `TaskScheduler` meant that we'ed create lots of new metrics (due to adding task ID to the desc of background process), resulting in requests for metrics taking an increasing amount of CPU.
This doesn't affect a released version, as nothing uses the task scheduler yet.

Fix bug with new task scheduler using lots of CPU.

---

changelog.d/16281.misc
synapse/storage/database.py

In #16271 I asked to see debug SQL logs to understand what exactly the user directory rebuild was doing. Unfortunately the logs didn't include the list of values given to the SQL statement:
```
2023-09-08 06:55:35,291 - synapse.storage.SQL - 449 - DEBUG - background_updates-1 - [SQL] {populate_user_directory_temp-1aa} INSERT INTO user_directory_search(user_id, vector) VALUES ? ON CONFLICT (user_id) DO UPDATE SET vector=EXCLUDED.vector
2023-09-08 06:55:35,292 - synapse.storage.SQL - 475 - DEBUG - background_updates-1 - [SQL time] {populate_user_directory_temp-1aa} 0.000619 sec
```
With my change, I ran the same(ish) logic using `SYNAPSE_POSTGRES=1 SYNAPSE_TEST_LOG_LEVEL=DEBUG trial tests.storage.test_user_directory` and observed e.g.
```
* 2023-09-08 13:52:47+0100 [-] synapse.storage.SQL - …
```

Log values at DEBUG level with execute_values

---

changelog.d/16283.misc
contrib/cmdclient/http.py
docker/start.py
pyproject.toml
scripts-dev/mypy_synapse_plugin.py
synapse/_scripts/update_synapse_database.py
synapse/events/snapshot.py
synapse/media/url_previewer.py
synapse/storage/background_updates.py
synmark/suites/logging.py
tests/handlers/test_device.py
tests/handlers/test_federation.py
tests/logging/test_remote_handler.py
tests/replication/tcp/streams/test_to_device.py
tests/rest/admin/test_federation.py
tests/rest/client/test_account.py
tests/rest/client/test_login.py
tests/rest/client/test_register.py
tests/storage/databases/main/test_lock.py
tests/storage/test_event_chain.py
tests/storage/test_event_federation.py
tests/storage/test_profile.py
tests/storage/test_txn_limit.py
tests/storage/test_user_filters.py
tests/test_visibility.py
tests/util/caches/test_descriptors.py

This cleans-up some unused ruff ignores and then enables `flake8-pie` and `flake8-executable`, which both seem like useful checks to make. Let me know if a reviewer disagrees.

Update ruff config

---

changelog.d/16276.misc
synapse/config/oembed.py
synapse/storage/controllers/persist_events.py
synapse/util/async_helpers.py
synapse/util/caches/dictionary_cache.py
synapse/util/caches/expiringcache.py
synapse/util/caches/ttlcache.py

An indulgent sorbet.
Commitwise reviewable.
In particular, according to https://github.com/python-attrs/attrs/issues/313 we should now be able to mark attrs classes using `slots=True` as Generic, as our minimum version of Python is 3.8. (Though let's confirm that in CI...)

Improve type hints for attrs classes

---

changelog.d/16274.feature
synapse/handlers/send_email.py
synapse/push/mailer.py
synapse/rest/synapse/client/unsubscribe.py
tests/push/test_email.py

This adds two headers `List-Unsubscribe` (RFC2369) and `List-Unsubscribe-Post` (RFC8058) to push notification emails, which together should:
1. Show an "Unsubscribe" link in the MUA UI for our notification emails.
2. Enable "one-click" unsubscribe (the user never leaves their MUA).
AFAIK The major players (Google, Yahoo, Microsoft, etc.) all support `List-Unsubscribe`, while `List-Unsubscribe-Post` is supported by fewer MUAs.
Fixes #16217

Add the List-Unsubscribe header for notification emails.

---

changelog.d/16273.misc
synapse/storage/databases/main/purge_events.py
synapse/storage/schema/__init__.py

Split out of #16268 as we need this to be a separate schema version otherwise we would not be able to rollback.

Stop purging tables which are slated for removal.

---

changelog.d/16300.misc
mypy.ini
poetry.lock
synapse/logging/opentracing.py

#16291 lets us bump this, unfortunately it didn't seem to tighten anything up.

Bump mypy from 1.4.1 to 1.5.1.

---

changelog.d/16309.misc
synapse/replication/tcp/handler.py
synapse/replication/tcp/resource.py

Two changes:
1. "Caught up with stream" was logged *within* the loop fetching updates, so was inaccurate. Move it till *after* the loop.
2. When sending replication include how many updates we're sending, whether there's more to send, and the current token of the stream. (This makes it obvious when we fall behind sending replication).

Improve logging of replication

---

changelog.d/16311.misc
synapse/handlers/device.py

Introduced in https://github.com/matrix-org/synapse/pull/16240
The action for the task was only defined on the "master" handler, rather than the base worker one.

Fix deleting device inbox when using background worker

---

changelog.d/16312.misc
synapse/handlers/sync.py

Introduced in https://github.com/matrix-org/synapse/pull/16240
The idea with doing it in a BG task is still useful, to avoid blocking syncs for devices that had a lot of to-device messages stacked up.

Don't schedule an async task on every sync

---

changelog.d/16288.bugfix
synapse/handlers/device.py
synapse/storage/databases/main/registration.py
tests/handlers/test_device.py

During re-hydration, after setting the access tokens from the current requester device to the re-hydrated device, we move the current device refresh tokens to the re-hydrated device as well. Technically, update the fields with old device id to the re-hydrated device id.
This is regarding the dehydrated devices feature [msc2697](https://github.com/matrix-org/matrix-spec-proposals/pull/2697).
Please check [16284](https://github.com/matrix-org/synapse/issues/16284) for bug description. …

Fix using dehydrated devices & refresh tokens

---

changelog.d/16314.misc
synapse/metrics/background_process_metrics.py

Reference cycles are bad and should feel bad.

Remove a reference cycle in background process

---

changelog.d/16316.misc
synapse/api/auth/internal.py
synapse/api/auth/msc3861_delegated.py
synapse/handlers/account.py
synapse/handlers/admin.py
synapse/handlers/message.py
synapse/module_api/__init__.py
synapse/rest/consent/consent_resource.py
synapse/server_notices/consent_server_notices.py
synapse/storage/databases/main/client_ips.py
synapse/storage/databases/main/registration.py
synapse/types/__init__.py
tests/api/test_auth.py
tests/storage/test_registration.py

1. Doesn't join against `user_ips` now, as `last_seen_ts` was rarely used and has been moved out to a separate function.
2. Make `get_user_by_id` return a proper type, rather than caching a dict.

Refactor `get_user_by_id`

---

changelog.d/16318.misc
synapse/handlers/device.py

Currently if we need to delete a large number of rows we'll delete 100 each time the task is rerun, which is once a minute.
Instead of that, let's just do the batched deletions in a loop.

Speed up deleting to-device messages task

---

changelog.d/16313.misc
synapse/replication/tcp/handler.py
synapse/storage/databases/main/task_scheduler.py
synapse/storage/schema/main/delta/82/02_scheduled_tasks_index.sql
synapse/util/task_scheduler.py

Introduced in https://github.com/matrix-org/synapse/pull/16240

Some minor performance fixes for task schedular

---

changelog.d/16315.misc
synapse/appservice/scheduler.py
synapse/metrics/background_process_metrics.py
synapse/util/caches/expiringcache.py

`LiteralString` doesn't do anything yet until https://github.com/python/mypy/issues/12554 lands.
Using unique names blows up our prometheus metrics and causes lots of CPU on `/metrics` requests.

Only use literal strings for process names

---

changelog.d/16299.misc
synapse/storage/database.py
synapse/storage/databases/main/receipts.py

Which should cut down on Postgres log spam like:
```log
2023-09-11 05:37:47.811 CDT [13934] ERROR:  could not serialize access due to concurrent update
2023-09-11 05:37:47.811 CDT [13934] STATEMENT:  INSERT INTO receipts_graph (room_id, receipt_type, user_id, thread_id, event_ids, data) VALUES ('!room_1:computer.surgery', 'm.read', '@some_redacted_user:gnome.org', 'main', '["$hCBJpUJwHjjG6ztFwHrDPtqHFyMQ8eWMOCRUhmO3UBs"]', '{"thread_id":"main","ts":1694427550626}') ON CONFLICT (room_id, receipt_type, user_id, thread_id)  DO UPDATE SET event_ids=EXCLUDED.event_ids, data=EXCLUDED.data
2023-09-11 05:52:03.258 CDT [13934] ERROR:  could not serialize access due to concurrent update
2023-09-11 05:52:03.258 CDT [13934] STATEMENT:  INSERT INTO receipts_graph (room_id, receipt_type, user_id, …
```

Convert `_insert_graph_receipts_txn` to `simple_upsert`

---

changelog.d/16329.bugfix
synapse/handlers/send_email.py

As stated by the [W3C], the charset parameter can be set to "any character encoding that has been registered with IANA". A full list of these is available [on their website][IANA].
Notably missing from that list is the `utf8` value that was being used for email charsets. The strictly more correct name is `utf-8` (or `UTF-8`, since these names are case-insensitive).
The popularity of UTF-8 has meant that aliases like `utf8` are supported by a number of email servers. Unfortunately, not all are as accommodating (see for example https://github.com/emersion/hydroxide/issues/165), so a more standard name means Synapse can be used even with the more opinionated servers.
[W3C]: https://www.w3.org/International/articles/http-charset/index
[IANA]: …

Set email charset as utf-8 rather than utf8

---

changelog.d/16347.misc
pyproject.toml

Mandate Pillow>=10.0.1 because of libwebp CVE

---

changelog.d/16327.bugfix
synapse/handlers/receipts.py
synapse/rest/client/read_marker.py
synapse/rest/client/receipts.py
tests/rest/client/test_receipts.py
tests/rest/client/test_sync.py

This improves the error messages sent to clients if they send bogus receipts and would have made my life much easier when I was debugging something.
For federation the best we do is check that the server is in the room and drop it if not (this is similar to what we do for typing, see #13830.
This essentially expands the validation added in #14632, and somewhat backs out https://github.com/matrix-org/synapse/commit/9f797a24a452a513628263b1b03172cee20a9856, but I still don't understand how that could ever happen. (Note that instead of raising an error if the event is unknown, we instead ignore the receipt. This should also help in situations where a room is purged, kind of like #15464.)
Sorry for the large diff -- one of the commits in the middle moves some tests around.

Additional validation of receipts

---

changelog.d/16326.misc
synapse/events/builder.py
synapse/handlers/federation_event.py
synapse/storage/controllers/persist_events.py
synapse/storage/databases/main/event_federation.py
synapse/storage/databases/main/events.py
tests/handlers/test_presence.py
tests/replication/storage/test_events.py
tests/replication/tcp/streams/test_events.py
tests/replication/test_federation_sender_shard.py
tests/storage/test_cleanup_extrems.py
tests/test_federation.py

Spun out of #14911, this changes the return type to an immutable value. Turns out all the callers actually wanted a set so instead of `List[str]` (or `StrSequence`) we can return `FrozenSet[str]`). This also should do less work since we cache exactly what we want and do less `set(...)` of the return value.

Return an immutable value from get_latest_event_ids_in_room.

---

changelog.d/16325.misc
synapse/app/admin_cmd.py
synapse/handlers/admin.py
synapse/handlers/sync.py
synapse/rest/admin/users.py
synapse/rest/client/account_data.py
synapse/storage/databases/main/account_data.py
synapse/storage/databases/main/experimental_features.py
synapse/storage/databases/main/tags.py

Spun out of #14911 to make that a bit smaller. This converts some of the types that are cached (inside a `@cached` decorator) to be immutable. For this PR it is pretty much `s/JsonDict/JsonMapping/g` and then deal with the callers who need to be updated.

Make cached account data/tags/admin types immutable

---

changelog.d/16328.feature
docs/admin_api/user_admin_api.md
synapse/rest/admin/users.py
synapse/storage/databases/main/__init__.py
synapse/storage/databases/main/stats.py
tests/rest/admin/test_user.py

Signed-off-by: [Hanadi](https://github.com/hanadi92)
This PR is related to this issue (feature request): https://github.com/matrix-org/synapse/issues/16323

Filter locked users in the admin API

---

changelog.d/16349.misc
tests/replication/storage/_base.py
tests/replication/storage/test_events.py

The tests seem to be too clever for their own good.

Stop patching EventBase.__eq__ in tests.

---

changelog.d/16353.doc
docs/usage/configuration/config_documentation.md

Synapse fetches this value from the config and casts it to a string, no matter what it was before. Using floats for protocol identifiers rubs me the wrong way, so I wanted to update the docs here. Synapse works with both a float and string here, so it's just a matter of adjusting the docs.
Signed-off-by: Jan Christian Grünhage <jan.christian@gruenhage.xyz> …

Use string for federation_client_minimum_tls_version documentation examples

---

changelog.d/16355.doc
docs/admin_api/user_admin_api.md

Fix-up deactivated notes in docs.

---

changelog.d/16350.misc
synapse/appservice/__init__.py
synapse/appservice/api.py
synapse/appservice/scheduler.py
synapse/handlers/appservice.py
synapse/handlers/e2e_keys.py
synapse/handlers/initial_sync.py
synapse/handlers/receipts.py
synapse/handlers/sync.py
synapse/handlers/typing.py
synapse/push/bulk_push_rule_evaluator.py
synapse/storage/databases/main/appservice.py
synapse/storage/databases/main/devices.py
synapse/storage/databases/main/end_to_end_keys.py
synapse/storage/databases/main/events_worker.py
synapse/storage/databases/main/keys.py
synapse/storage/databases/main/presence.py
synapse/storage/databases/main/push_rule.py
synapse/storage/databases/main/receipts.py
synapse/storage/databases/main/relations.py
synapse/storage/databases/main/roommember.py
synapse/storage/databases/main/state.py
synapse/storage/databases/main/transactions.py
synapse/storage/databases/main/user_erasure_store.py

Spun out of #14911. Updates anything decorator with `@cachedList` to return immutable types.
Note that technically the `cachedList` doesn't really need a `Mapping[..., ...]` and could work with `Dict[..., ...]` but it seems desirable to have it be immutable anyway.

Return immutable objects for cachedList decorators

---

changelog.d/16356.misc
synapse/api/filtering.py
synapse/federation/federation_client.py
synapse/handlers/federation_event.py
synapse/handlers/relations.py
synapse/rest/client/filter.py
synapse/storage/controllers/state.py
synapse/storage/databases/main/filtering.py
synapse/storage/databases/main/relations.py
synapse/storage/databases/main/roommember.py
tests/util/caches/test_descriptors.py

This is the last PR to spin out of #14911.

Convert more cached return values to immutable types

---

changelog.d/16383.misc
synapse/storage/databases/state/bg_updates.py

#15617 looks unwanted, but has some nice improvements to the comments.

Improve comments in StateGroupBackgroundUpdateStore.

---

.github/workflows/tests.yml
changelog.d/16387.misc

Also sneak in a fix to #14745: consider portdb an integration test, not a linter.

Skip export-data on non-code (e.g. docs) PRs

---

changelog.d/16361.feature
rust/benches/evaluator.rs
rust/src/push/base_rules.rs
rust/src/push/evaluator.rs
rust/src/push/mod.rs
stubs/synapse/synapse_rust/push.pyi
synapse/config/experimental.py
synapse/storage/databases/main/push_rule.py

See [MSC4028](https://github.com/matrix-org/matrix-spec-proposals/pull/4028).
Fixes #15847

Implement MSC4028: push all encrypted events.

---

changelog.d/16360.misc
rust/src/acl/mod.rs
rust/src/lib.rs
stubs/synapse/synapse_rust/acl.pyi
synapse/events/validator.py
synapse/federation/federation_server.py
synapse/handlers/federation_event.py
synapse/handlers/message.py
synapse/replication/tcp/client.py
synapse/storage/controllers/state.py
synapse/storage/databases/main/cache.py
tests/federation/test_federation_server.py

We were hitting this block frequently causing use to throw redo work unnecessarily. Just throw a cache on it.
I selfishly also converted it to Rust while I was here because it uses many of the same primitives as our push rules code, but I can back this out if it seems over the top.

Add a cache around server ACL checking

---

changelog.d/16394.misc
pyproject.toml
rust/Cargo.toml

See https://www.maturin.rs/migration#remove-packagemetadatamaturin-from-cargotoml

Use modern config for maturin.

---

changelog.d/16395.misc
synapse/state/v2.py
tests/state/test_v2.py

Drive-by fixing a type hint as I was looking at something.

More specific types.

---

changelog.d/16382.doc
docs/message_retention_policies.md
docs/usage/configuration/config_documentation.md

Partially reverts #13497 as we now consider the bugs fixed enough that it won't lead to database corruption.
Fixes #13476.

Remove warnings from the docs about using message retention.

---

changelog.d/16401.misc
synapse/replication/tcp/client.py

This is because if a worker reaches ~100% CPU then everything starts lagging and we hit the log line a lot. When at error we invoke sentry and that has a lot of overhead, which then puts even more pressure on the worker.

Downgrade repl stream time out error to warning

---

changelog.d/16426.misc
synapse/handlers/appservice.py
synapse/handlers/push_rules.py
synapse/handlers/receipts.py
synapse/notifier.py
synapse/push/__init__.py
synapse/push/emailpusher.py
synapse/push/httppusher.py
synapse/push/pusherpool.py
synapse/replication/tcp/client.py
synapse/storage/databases/main/e2e_room_keys.py
synapse/storage/databases/main/receipts.py
synapse/streams/events.py
synapse/types/__init__.py
tests/handlers/test_appservice.py
tests/handlers/test_typing.py

A couple of refactors aimed at making it easier to make receipts stream multi-writer. 

Some refactors around receipts stream

---

changelog.d/16421.misc
mypy.ini
synmark/__init__.py
synmark/__main__.py
synmark/suites/logging.py
synmark/suites/lrucache.py
synmark/suites/lrucache_evict.py

Was trying to figure out synmark the other day and type hints were helpful.

Add type hints to synmark.

---

changelog.d/16427.misc
synapse/handlers/admin.py
synapse/handlers/initial_sync.py
synapse/handlers/room.py
synapse/handlers/sync.py
synapse/rest/admin/__init__.py
synapse/storage/databases/main/stream.py
synapse/types/__init__.py
tests/handlers/test_appservice.py

So we can reuse code when we split up other streams.

Factor out `MultiWriter` token from `RoomStreamToken`

---

changelog.d/16429.misc
synapse/replication/tcp/commands.py

I'm hoping this will slim down our replication needs very very slightly, but it is also minimal effort.
WIth this change we have the following, sizes are done using [`_get_size_of`](https://github.com/matrix-org/synapse/blob/21fea6b7493533985f7fa14924949514b5a356e2/synapse/util/caches/lrucache.py#L64-L78).
| Class | Original size (bytes) | Final size (bytes) | Savings (bytes) |
|---|---|---|---|
| Any `_SimpleCommand` subclass | 408 | 360 | 48 |
| `RdataCommand` | 592 | 384 | 208 |
| `PositionCommand` | 672 | 448 | 224 |
| `UserSyncCommand` | 728 | 456 | 272 |
| `ClearUserSyncsCommand` | 416 | 360 | 56 |
| `FederationAckCommand` | 504 | 400 | 104 |
| `UserIpCommand` | 752 | 432 | 320 |
| `LockReleasedCommand` | 544 | 376 | 168 |
<details>
<summary>Code to produce the above</summary> …

Add __slots__ to replication commands.

---

changelog.d/16419.misc
synapse/http/server.py
synapse/media/_base.py
synapse/media/media_repository.py
synapse/rest/media/config_resource.py
synapse/rest/media/download_resource.py
synapse/rest/media/media_repository_resource.py
synapse/rest/media/preview_url_resource.py
synapse/rest/media/thumbnail_resource.py
synapse/rest/media/upload_resource.py
tests/media/test_media_storage.py
tests/media/test_url_previewer.py
tests/replication/test_multi_media_repo.py
tests/rest/admin/test_admin.py
tests/rest/admin/test_media.py
tests/rest/admin/test_statistics.py
tests/rest/admin/test_user.py
tests/rest/client/utils.py
tests/rest/media/test_url_preview.py
tests/unittest.py

This essentially converts the media repo stuff from the Twisted-way of registering resources to the regex way of registering servlets.
I tested this via trying some URLs with v1, v3, r0; testing that options still works, etc.
Vaguely related to #5118.
This is desirable for #15503 where a new endpoint (`/create`) needs to be registered as `v1` & the behavior of `/upload` is changed for `/v3` (to support `PUT` in addition to `POST`).

Register media URLs via regex.

---

changelog.d/16420.doc
docs/development/database_schema.md

I want this to exist before #16397 so I can then modify it in that PR.

Add documentation on background updates.

---

changelog.d/16428.misc
synapse/federation/sender/__init__.py
synapse/replication/tcp/commands.py

Fixes a typo and incorrect comment.

Fix comments related to replication.

---

changelog.d/16403.bugfix
synapse/federation/federation_client.py
synapse/federation/federation_server.py
synapse/federation/transport/client.py
synapse/handlers/federation.py
tests/federation/transport/test_knocking.py

Fixes #14151, per that we've said this is fine to remove.

Stop sending incorrect knock_state_events.

---

changelog.d/16438.misc
synapse/media/_base.py
synapse/media/media_repository.py
synapse/rest/media/thumbnail_resource.py
synapse/storage/databases/main/media_repository.py
tests/media/test_media_storage.py

Use attrs classes in more spots instead of dictionaries.
Kind of related to #16431.

Return ThumbnailInfo in more places

---

changelog.d/16441.misc
synapse/handlers/room_member.py
tests/rest/client/test_rooms.py

I came across this logic; got confused, then tried to tidy it up. I found this much easier to reason about---doing the rate limit check up front.
At some point, someone should draw out a flowchart of the various membership-updating functions here. It's very confusing.
Commitwise reviewable.

Apply join rate limiter outside the lineariser

---

changelog.d/16404.bugfix
synapse/api/auth/internal.py

Fix possible AttributeError when account-api is called over unix socket

---

.github/workflows/tests.yml
changelog.d/16454.misc

As this doesn't work with the private sign off flow.
c.f. https://github.com/matrix-org/synapse/pull/16404 for an example

Don't block CI on sign-off

---

changelog.d/16457.bugfix
synapse/storage/databases/main/account_data.py
synapse/storage/databases/main/e2e_room_keys.py
synapse/storage/schema/main/delta/82/04_add_indices_for_purging_rooms.sql

We have seen DELETEs from these tables clog up the background process worker on matrix.org. Indices should help.
Completely untested.

Add DB indices to speed up purging rooms

---

changelog.d/16440.bugfix
synapse/media/_base.py
tests/media/test_base.py

See https://github.com/matrix-org/synapse/issues/15885#issuecomment-1749200283
Complement tests: https://github.com/matrix-org/complement/pull/664

Handle content types with parameters.

---

changelog.d/16444.misc
synapse/storage/database.py
synapse/storage/databases/main/deviceinbox.py
synapse/storage/databases/main/devices.py
synapse/storage/databases/main/end_to_end_keys.py
synapse/storage/databases/main/event_federation.py
synapse/storage/databases/main/events.py
synapse/storage/databases/main/events_bg_updates.py
synapse/storage/databases/main/events_worker.py
synapse/storage/databases/main/keys.py
synapse/storage/databases/main/presence.py
synapse/storage/databases/main/push_rule.py
synapse/storage/databases/main/relations.py
synapse/storage/databases/main/room.py
synapse/storage/databases/main/roommember.py
synapse/storage/databases/main/state.py
synapse/storage/databases/main/stats.py
synapse/storage/databases/main/transactions.py
synapse/storage/databases/main/ui_auth.py
synapse/storage/databases/main/user_directory.py
synapse/storage/databases/main/user_erasure_store.py
synapse/storage/databases/state/store.py
tests/storage/test_event_chain.py

🪓 `cursor_to_dict`, more of #16431.
This one got a bit big, but I couldn't really figure out a good way to separate them. It is fairly tedious, but I'll try to mark noticeable spots.

Convert simple_select_many_batch, simple_select_many_txn to tuples.

---

changelog.d/16468.misc
synapse/handlers/account_validity.py
synapse/handlers/admin.py
synapse/handlers/deactivate_account.py
synapse/module_api/__init__.py
synapse/rest/admin/users.py
synapse/rest/client/account.py
synapse/storage/databases/main/registration.py
tests/module_api/test_api.py

This is related to #16431, but mostly just improves our type hints.

Convert user_get_threepids response to attrs.

---

changelog.d/16477.doc
docs/usage/administration/useful_sql_for_admins.md

Fix typo in useful_sql_for_admins.md

---

changelog.d/16488.misc
synapse/replication/http/federation.py
synapse/replication/http/send_events.py

* if we're going to log "got batch", don't log each event separately
* do log the room id which is super useful

Clean up logging on event persister endpoints

---

changelog.d/16506.bugfix
synapse/util/retryutils.py
tests/util/test_retryutils.py

As described in #15226, the `RetryDestinationLimiter` seems to mark servers as up when the connection fails. It seems to be a regression from #12500, see https://github.com/matrix-org/synapse/pull/12500#discussion_r877166594.
I think this will cause the notifier to be woken up and additional replication traffic. I think it will then cause federation traffic via a new transaction being sent to the unreachable server?

Fix a bug where servers could be marked as up when they were failing

---

changelog.d/16507.misc
synapse/handlers/device.py
synapse/storage/databases/main/client_ips.py
tests/storage/test_client_ips.py

Spun out of #16505 (so related to #16431).

Convert DeviceLastConnectionInfo to attrs.

---

.github/workflows/tests.yml
changelog.d/16512.misc

Run trial/integration tests if .ci is modified.

---

changelog.d/16492.misc
synapse/handlers/device.py
synapse/storage/databases/main/deviceinbox.py

cf #16479.
Signed-off-by: Mathieu Velten [matmaul@gmail.com](mailto:matmaul@gmail.com)

Improve performance of delete device messages query

---

changelog.d/16510.misc
synapse/replication/tcp/streams/events.py
synapse/storage/databases/main/cache.py
tests/replication/tcp/streams/test_events.py

When purging a room it doesn't make sense to send every individual update, we can combine them into a "all state is invalid for this room".
As it is hard to mark the room as "being purged" we do this whenever there's *many* state updates in the room. This should also cover any other unforeseen replication updates with massive amounts of state.

Avoid sending massive replication updates when purging a room.

---

changelog.d/16485.bugfix
synapse/handlers/sync.py
synapse/storage/databases/main/events.py
synapse/storage/databases/main/stream.py
synapse/storage/schema/main/delta/82/05gaps.sql

Mark sync as limited if there is a gap in the timeline 

---

changelog.d/16524.misc
scripts-dev/build_debian_packages.py

which was released a week ago: https://canonical.com/blog/canonical-releases-ubuntu-23-10-mantic-minotaur
Previously: #15381
Xref https://github.com/matrix-org/pkg-repo-configs/pull/21

Build Debian packages for Ubuntu 23.10 Mantic Minotaur

---

changelog.d/16521.misc
synapse/storage/databases/main/events_worker.py
synapse/storage/schema/__init__.py

See #16465, related to #16042.

Remove the last reference to event_txn_id.

---

changelog.d/16530.bugfix
synapse/_scripts/register_new_matrix_user.py

Rationale: If using the script remotely, there's no particularly convincing reason to disable certificate verification, as this makes the connection interceptible. If on the other hand, the script is used locally (the most common use case), you can simply target the HTTP listener and avoid TLS altogether.
- Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the …

Force TLS certificate verification in registration script.

---

changelog.d/16531.doc
docs/opentracing.md

This adds a small note to the opentracing docs when your jaeger is not on localhost next to synapse. For example in a Kubernetes env.
Signed-Off-By: Marcel Radzio <support@nordgedanken.dev>
(run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-lin …

Mention how to redirect the Jaeger traces to a specific Jaeger instance

---

changelog.d/16540.bugfix
synapse/storage/databases/main/account_data.py

This could happen if the last rows in the account data stream were inserted into `account_data`. After a restart the max account ID would be calculated without looking at the `account_data` table, and so have an old ID.

Fix bug that could cause a `/sync` to tightloop with sqlite after restart

---

changelog.d/16473.bugfix
docs/development/synapse_architecture/streams.md
synapse/replication/http/_base.py
synapse/replication/tcp/streams/_base.py
synapse/replication/tcp/streams/events.py
synapse/replication/tcp/streams/federation.py
synapse/replication/tcp/streams/partial_state.py
synapse/storage/util/id_generators.py
tests/storage/test_id_generators.py

When starting a new writer (for e.g. persisting events), the `MultiWriterIdGenerator` doesn't have a minimum token for it as there are no rows matching that new writer in the DB.
This results in the the first stream ID it acquired being announced as persisted *before* it actually finishes persisting, if another writer gets and persists a subsequent stream ID. This is due to the logic of setting the minimum persisted position to the minimum known position of across all writers, and the new writer starts off not being considered.
We fix this by setting the new writer to the minimum persisted position on startup.

Fix bug where a new writer advances their token too quickly

---

changelog.d/16526.misc
synapse/util/file_consumer.py
tests/handlers/test_appservice.py
tests/http/server/_base.py
tests/http/test_matrixfederationclient.py
tests/unittest.py

Fix type hint errors on Twisted trunk

---

changelog.d/16471.bugfix
contrib/grafana/synapse.json

Fixes: #16405 
(run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))</del> **Not applicable**
I replaced the `000000001` and `$datasource` Prometheus datasource UIDs `${DS_PROMETHEUS}` using regular expressions. Then I added the label …

Replace all Prometheus datasource UIDs of the Grafana Dashboard with the variable `${DS_PROMETHEUS}` and remove `__inputs`

---

changelog.d/16515.misc
synapse/replication/tcp/client.py
synapse/replication/tcp/handler.py

...and remove some additional code that appears to be 'dead' now.
Please read actual commit messages for details.

Remove duplicate call to wake a remote destination when using federation sending worker

---

changelog.d/16504.bugfix
synapse/http/connectproxyclient.py
tests/http/test_proxyagent.py

Fix http/s proxy authentication with long username/passwords

---

changelog.d/16551.misc
synapse/handlers/identity.py
synapse/handlers/ui_auth/checkers.py
synapse/media/media_repository.py
synapse/rest/admin/federation.py
synapse/rest/admin/rooms.py
synapse/rest/admin/statistics.py
synapse/storage/database.py
synapse/storage/databases/main/censor_events.py
synapse/storage/databases/main/devices.py
synapse/storage/databases/main/end_to_end_keys.py
synapse/storage/databases/main/events_bg_updates.py
synapse/storage/databases/main/events_forward_extremities.py
synapse/storage/databases/main/media_repository.py
synapse/storage/databases/main/registration.py
synapse/storage/databases/main/roommember.py
synapse/storage/databases/main/search.py
synapse/storage/databases/main/stats.py
synapse/storage/databases/main/stream.py
synapse/storage/databases/main/transactions.py
synapse/storage/databases/main/user_directory.py
synapse/storage/databases/state/bg_updates.py
tests/federation/test_federation_catch_up.py
tests/storage/test_background_update.py
tests/storage/test_profile.py
tests/storage/test_user_filters.py

More of #16431, this targets a bunch of individual usages, but also targets the usages of `execute` which can take a callable to map the results. In actuality it always passes `cursor_to_dict`.
This can be split further, but isn't too large and should be reviewable commit-by-commit.

Remove more usages of cursor_to_dict

---

changelog.d/16557.bugfix
synapse/replication/tcp/resource.py

This was exacerbated by #16473

Reduce replication traffic due to reflected cache stream POSITION

---

changelog.d/16558.bugfix
synapse/handlers/message.py

Fix cross-worker ratelimiting

---

changelog.d/16555.misc
synapse/replication/tcp/handler.py

The `POSITION` command includes two tokens, the "prev" and "new" tokens. The "new" token is what we should set the current token for the instance to be, and the "prev" token was where it was previously (i.e. the instance produced no rows between the "prev" and "new" tokens).
This means that we can safely relax the condition to only check for missing updates if the current token for the writer is strictly less than the "prev" token.
A common case is receiving something like `POSITIONS event_persister1 events 15 16`, which indicates the writer advanced their events stream token from 15 to 16 (usually as a response to another instance persisting an event with stream ID 16). Usually, the other instances would already have inferred that `event_persister1` must have advanced their token, so the …

Reduce spurious replication catchup

---

changelog.d/16561.bugfix
synapse/replication/tcp/streams/_base.py

Follow on from / actually correctly does #16557

Reduce amount of caches POSITIONS we send

---

changelog.d/16559.bugfix
synapse/handlers/room.py
synapse/storage/databases/main/roommember.py
tests/rest/admin/test_room.py

Currently when we purge a room only joined local users leave the room, stranding invites and knocking users in their old state.
This isn't a huge deal since well...you've purged the room and your own server doesn't know about it anymore. Other servers, however, will still see those users in those states and we should properly clean-up.

Ensure local invited & knocking users leave before purge.

---

changelog.d/16563.misc
synapse/_scripts/synapse_port_db.py

The table itself is fine to port over AFAICS:
```sql
CREATE TABLE IF NOT EXISTS users_in_public_rooms (
user_id TEXT NOT NULL,
room_id TEXT NOT NULL
);
```
But I think the user directory is deliberately rebuilt after porting (the FTS tables aren't portable).
Typo 1 introduced in #2375, moved in #7711, then changed to typo 2 in #7717.

Portdb: don't copy a table that gets rebuilt

---

changelog.d/16578.bugfix
synapse/replication/http/_base.py

Follow on from #16473, where we tried to change the HTTP replication to return the *minimum* current token for a stream (as this is used to wait for a position in the stream). However, turns out we need to change this in *two* places, both the request and response.

Fix HTTP repl response to use minimum token

---

.github/workflows/latest_deps.yml
.github/workflows/tests.yml
.github/workflows/twisted_trunk.yml
changelog.d/16567.misc

This should suppress the warnings in test runs, e.g. from https://github.com/matrix-org/synapse/actions/runs/6673818366?pr=16565
and presumably make it mildly quicker to prepare the complement test binary.

Run actions/setup-go after checking out complement

---

changelog.d/16570.feature
synapse/handlers/e2e_keys.py
synapse/storage/database.py
synapse/storage/databases/main/end_to_end_keys.py
tests/handlers/test_e2e_keys.py

This is the second performance change as suggested by from Rich in #16554. The first was #16565.
<details><summary>Testing that the query is legit</summary>
```sql
\echo nuke table\\
DROP TABLE IF EXISTS e2e_fallback_keys_json;
\echo Make table\\
CREATE TABLE e2e_fallback_keys_json (
user_id   text    NOT NULL,
device_id text    NOT NULL,
algorithm text    NOT NULL,
key_id    text    NOT NULL,
key_json  text    NOT NULL,
used      boolean NOT NULL,
UNIQUE (user_id, device_id, algorithm)
);
\echo Dummy data. 10 users, with 10 devices, with 10 algorithms. One key per alg. Keys alternate used and unused. \\
INSERT INTO e2e_fallback_keys_json (user_id, device_id, algorithm, key_id, key_json, used)
SELECT concat('@user_', id / 100, ':test'),
concat('user_', id / 100, '_dev_', (id / 10) % 10), …
```

Claim fallback keys in bulk

---

changelog.d/16580.bugfix
synapse/replication/tcp/streams/events.py

We can bail early if the from token is greater than or equal to the current token.
This can happen when the ID gen advances the current token for a remote writer past its last write.
Side note: I want to change how we do all this streaming stuff to put the ID generators in charge, which might be easier to grok rather than having abstract "streams" :shrug: 
Kinda follows on from #16473

Add fast path for replication events stream fetch

---

README.rst
changelog.d/16569.bugfix
changelog.d/16569.doc

In this PR, I have fixed the broken link of clients in the README file. Now it redirects to the correct link.

Clients link fixed in README

---

changelog.d/16565.feature
synapse/handlers/e2e_keys.py
synapse/storage/databases/main/end_to_end_keys.py
tests/handlers/test_e2e_keys.py

One of the performance optimsations that Rich spotted in https://github.com/matrix-org/synapse/issues/16554. Another in #16570.
See https://gist.github.com/DMRobertson/243121754aed82eff56fa8ec5181184a for how I convinced myself that the SQL query was legit.
Commitwise reviewable, but sitting in CI over the weekend to see if this works.

Claim local one-time-keys in bulk

---

changelog.d/16585.misc
synapse/storage/databases/main/events.py

Theoretically the `ANY(?)` query is more efficient in PostgreSQL?

Use simple_select_many_txn in event persistance code.

---

changelog.d/16586.misc
synapse/storage/databases/main/events.py

I think this is safe to do -- instead of updating the stream cache (which is somewhat expensive) for each persisted event, only do it for the maximum stream ordering being persisted.
Based on #16584.

Update the stream_cache less often.

---

changelog.d/16594.bugfix
synapse/storage/databases/main/pusher.py

Fix "'int' object is not iterable" error in set_device_id_for_pushers background update

---

changelog.d/16584.misc
changelog.d/16586.misc
synapse/storage/controllers/persist_events.py
synapse/storage/databases/main/events.py

We only ever persist events for a single room at once, but the code handles multiple rooms at once this:
* Makes the code harder to read.
* Creates an objects which map room ID -> whatever unnecessarily.
I'm not sure if this is desirable if we ever *want* to be able to persist from multiple rooms at once, but... 🤷 
The first commit factors out a method, so should be reviewed separately.

Simplify persistance code

---

changelog.d/16532.misc
mypy.ini
synapse/metrics/_reactor_metrics.py

Supports timing reactor ticks on `select` and `poll` reactors, as well as `epoll` (which we previously supported). Also supports reactor timings when using the `asyncio` reactor (when used with an underlying `select`, `poll`, `epoll`, `/dev/poll`, or `kqueue` event loop).

Support reactor timing on more reactors.

---

changelog.d/16605.misc
pyproject.toml

Bump setuptools_rust to match pinned version.

---

changelog.d/16590.misc
synapse/push/bulk_push_rule_evaluator.py
synapse/storage/databases/main/push_rule.py
synapse/util/async_helpers.py

The `PushRuleEvaluator` requires a bunch of information about the room / sender, etc. based on the new event, most of this information does not depend on each other and can be calculated in parallel.
Additionally `bulk_get_push_rules` has two separate queries which can be done in parallel.
Ideally we would use PostgreSQL pipeling here instead, but that's not available to use in psycopg2 (or PostgreSQL < 14).
Note that these queries running in parallel will still be subject to thread pool contention, but worse case they get serialized, as they are today.

Collect information for PushRuleEvaluator in parallel.

---

changelog.d/16596.misc
synapse/storage/database.py
tests/storage/test_base.py

After being a bit nervous about #16583, I wanted to write some tests for more of the `simple_*` methods of the `DatabasePool`.

More tests for the simple_* methods

---

changelog.d/16609.bugfix
synapse/storage/database.py
tests/storage/test_base.py

Right now when we use `simple_update_many_txn` (or `simple_update_many`) it appends the arguments twice meaning each row is found and updated twice.
I noticed this while writing the tests in #16596.
Logic has existed since it was added in #12252.
This is used when:
* Adding client IPs to the database.
* Updating unread counts based on processing of receipts.
* The `set_device_id_for_pushers` background update.

Avoid updating the same rows multiple times with simple_update_many_txn.

---

changelog.d/16613.feature
synapse/storage/database.py
synapse/storage/databases/main/cache.py
synapse/storage/databases/main/end_to_end_keys.py
synapse/storage/util/id_generators.py
tests/storage/databases/main/test_cache.py

As threatened in https://github.com/matrix-org/synapse/issues/16554#issuecomment-1787473387
History: 
- https://github.com/matrix-org/synapse/issues/16554
- #16565 
- #16570
I wrote a dirty test for the new bulk invalidation that I'm not particularly happy with. Completely untested otherwise.
Nominating Erik because a) streams and b) PC helped me write this.

Bulk-invalidate e2e cached queries after claiming keys

---

changelog.d/16618.misc
docs/postgres.md
docs/usage/configuration/config_documentation.md
tests/server.py
tests/utils.py

According to the [psycopg2 docs](https://www.psycopg.org/docs/module.html#psycopg2.connect) the connection should use `dbname`:
> `dbname` – the database name (`database` is a deprecated alias)
I don't think we need to do mapping or anything in the config since we document this as drive-specific configuration.
This was taken from my psycopg3 branch, which requires using `dbname`.

Use dbname instead of database for Postgres config.

---

changelog.d/16615.misc
synapse/storage/background_updates.py
synapse/storage/databases/main/search.py
synapse/storage/databases/state/bg_updates.py
tests/server.py

This is pulled from my psycopg3 branch, it uses `attempt_to_set_autocommit` instead of an `assert isinstance(conn, psycopg2.extensions.connection)` followed by directly setting the autocommit.
tl;dr we're just being a bit more generic.

Use attempt_to_set_autocommit everywhere.

---

changelog.d/16628.doc
docs/usage/configuration/config_documentation.md

Missed in https://github.com/matrix-org/synapse/pull/15773 and https://github.com/matrix-org/synapse/pull/15913.

Fix outbound_federation_restricted_to docs & note when added

---

changelog.d/16631.doc
docs/admin_api/rooms.md

It returns an extra timestamp parameter, and also the event_id description was a little confused.

Improve documentation for `/_synapse/admin/v1/rooms/<room_id>/timestamp_to_event`

---

changelog.d/16638.misc
docs/changelogs/CHANGES-pre-1.0.md

This makes it more inline with our modern changelogs. It was done via a bunch of regex find & replaces.

Add links to pre-1.0 changelog issue/PR references.

---

changelog.d/16634.misc
docs/admin_api/user_admin_api.md
synapse/handlers/e2e_keys.py
synapse/rest/admin/__init__.py
synapse/rest/admin/users.py
synapse/rest/client/keys.py
synapse/storage/databases/main/end_to_end_keys.py
synapse/storage/schema/main/delta/83/05_cross_signing_key_update_grant.sql
tests/handlers/test_e2e_keys.py
tests/rest/admin/test_user.py
tests/rest/client/test_keys.py
tests/storage/databases/main/test_end_to_end_keys.py

Add an Admin API to temporarily grant the ability to update an existing cross-signing key without UIA

---

changelog.d/16647.misc
synapse/storage/schema/common/delta/83/07_common_replica_identities.sql.postgres
synapse/storage/schema/main/delta/83/06_more_replica_identities.sql.postgres
tests/storage/test_database.py

Fixes: #16224 
Follows: #16456 
<ol>
<li>
Fix the CI query that did not detect all cases of missing primary keys 
</li>
<li>
Add more missing REPLICA IDENTITY entries 
</li>
</ol>

Fix test not detecting tables with missing primary keys and missing replica identities, then add more replica identities.

---

changelog.d/16640.misc
synapse/replication/tcp/handler.py
synapse/replication/tcp/streams/_base.py

We may receive `POSITION` commands where we already know that worker has advanced past that position, so there is no point in handling it.

More efficiently handle no-op POSITION

---

changelog.d/16639.bugfix
synapse/replication/tcp/handler.py
synapse/replication/tcp/redis.py
synapse/replication/tcp/resource.py
tests/replication/tcp/streams/test_typing.py

If a worker reconnects to Redis we send out the current positions of all our streams. However, if we're also trying to send out a backlog of RDATA at the same time then we can end up sending a `POSITION` with the current token *before* we've sent all the RDATA before the current token.
This doesn't cause actual bugs as the receiving servers see the POSITION, fetch the relevant rows from the DB, and then ignore the old RDATA as they come in. However, this is inefficient so it'd be better if we didn't  send out-of-order positions

Fix sending out of order `POSITION` over replication

---

changelog.d/16649.misc
synapse/handlers/federation_event.py
synapse/util/iterutils.py
tests/util/test_itertools.py

Recalculating the roots tuple every iteration could be very expensive, so instead let's do a topological sort.
(Note that `sorted_topologically_batched` is basically a slightly modified `sorted_topologically`, and the tests are more or less a copy and paste)

Speed up persisting large number of outliers

---

changelog.d/16643.misc
synapse/handlers/device.py
synapse/storage/databases/main/deviceinbox.py
synapse/util/task_scheduler.py

Keeping track of a lower bound of stream ID where we've deleted everything below makes the queries much faster. Otherwise, every time we scan for rows to delete we'd re-scan across all the rows that have previously deleted (until the next table VACUUM).

Speed up deleting device messages

---

.github/workflows/release-artifacts.yml
changelog.d/16653.misc

See https://github.com/matrix-org/synapse/actions/runs/6894805171/job/18757418241 erroring with:
```
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
```
My hope is that a newer cibuildwheel will use a newer pip which will be compatible with Python 3.12.

Fix building wheels.

---

changelog.d/16656.misc
synapse/handlers/device.py
synapse/util/task_scheduler.py

Most background tasks don't have any form of limiting on resource usage, so running ten of them at a time could be problematic for DB load. The deleting device messages task does have limiting, but we can make that less aggressive now that a) the queries are more efficient, and b) we are doing fewer in parallel.

Reduce task concurrency

---

changelog.d/16655.misc
synapse/replication/tcp/streams/_base.py

Also discard 'caches' and 'backfill' stream POSITIONS

---

changelog.d/16660.misc
synapse/util/task_scheduler.py

Now that we're reducing concurrency (#16656), this is more important.

Speed up how quickly we launch new tasks

---

changelog.d/16670.bugfix
synapse/server_notices/server_notices_manager.py

Signed-off-by: Mathieu Velten <matmaul@gmail.com>
A lot of the underlying calls in the server notice code are already using `ratelimit=False`, but some are missing leading to still being rate limited when using the API in bulk.

Admin API for server notice: consistently bypass rate limits

---

changelog.d/16672.feature
synapse/api/auth/base.py
synapse/api/auth/internal.py
synapse/api/auth/msc3861_delegated.py
synapse/storage/databases/main/client_ips.py
tests/config/test_oauth_delegation.py
tests/handlers/test_oauth_delegation.py
tests/rest/admin/test_jwks.py
tests/rest/client/test_keys.py
tests/rest/test_well_known.py
tests/utils.py

This was present in Synapse's "internal" auth, but was not available when delegating auth to an OIDC provider until now.
I haven't tested this end-to-end. But there isn't any variation in the way we write to the DB. So I'm fairly confident this should work. (Unless I'm missing something @sandhose?)

Keep track of `user_ips` and `monthly_active_users` when delegating auth

---

changelog.d/16682.misc
synapse/replication/tcp/streams/_base.py
synapse/storage/databases/main/deviceinbox.py

Fixes #16681.
Commitwise reviewable. Completely untested.
I also threw in an opinionated rename in the last commit.

Correctly read to-device stream pos on SQLite

---

changelog.d/16695.doc
docs/development/contributing_guide.md

Typo in #16550 :(
There was never a 1.5.2 release, according to https://pypi.org/project/poetry/#history
So I assume this was just a typo on my part.

Fix poetry version typo in contributors' guide

---

changelog.d/16677.misc
synapse/handlers/room.py
synapse/server_notices/server_notices_manager.py

~~Currently the created rooms are encrypted, but the sent notices there are unencrypted which is rather ugly.~~
My assumptions were wrong so this PR got fully rewrote.
It now bypasses `encryption_enabled_by_default_for_room_type` setting when creating server notices room, since the notices will be send unencrypted anyway.
Signed-off-by: Mathieu Velten <matmaul@gmail.com>

Ignore `encryption_enabled_by_default_for_room_type` for notices room

---

changelog.d/16667.misc
synapse/storage/databases/main/client_ips.py

Speed up pruning of `user_ips` table

---

.github/workflows/fix_lint.yaml
changelog.d/16704.misc

Hopefully useful for automatically fixing up a contributor's PR?

Add a workflow to try and automatically fixup a PR

---

changelog.d/16707.feature
synapse/rest/client/versions.py

This depends on #16701.
This fixes #15661 and fixes #16176 and fixes #16709. I would recommend the author double check that all the bits in those are supported in Synapse.

Declare support for Matrix v1.7, v1.8, and v1.9.

---

changelog.d/16702.misc
pyproject.toml

This fixes #16147 but I'm not sure this is precisely the right version bound. Looking through Poetry related issues directly or indirectly related to #16147 I tend to argue Poetry has created more problems than benefit and would prefer removing it altogether. 
For example, we are using an unsupported Poetry mechanism for building the Rust `synapse.synapse_rust` modules, see https://github.com/python-poetry/poetry/issues/2740#issuecomment-665073135
Happy to make the necessary changes in order to improve the new contributor onboarding experience, whatever they may be.
* [] Pull request includes a [changelog file](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
- Be a short description of your change which makes sense to users. …

Upgrade poetry-core range to fix #16147

---

changelog.d/16522.misc
synapse/handlers/message.py
synapse/storage/schema/__init__.py
synapse/storage/schema/main/delta/83/01_drop_old_tables.sql

This relands #16268 which was backed out in #16465.
This depends on #16521, which will hopefully land in Synapse 1.96.0. Meaning this PR can land in 1.98.0.
Fixes #16042 and fixes #15786.

Drop unused tables & unneeded access token ID for events.

---

changelog.d/16636.feature
synapse/config/experimental.py
synapse/handlers/profile.py
synapse/rest/client/profile.py
synapse/rest/client/versions.py
tests/rest/client/test_profile.py

MSC: https://github.com/matrix-org/matrix-spec-proposals/pull/4069

Implement MSC4069: Inhibit profile propagation

---

changelog.d/16699.feature
docs/server_notices.md
docs/usage/configuration/config_documentation.md
synapse/config/server_notices.py
synapse/server_notices/server_notices_manager.py
tests/rest/admin/test_server_notice.py

Signed-off-by: Mathieu Velten <mathieu.velten@beta.gouv.fr>

Server notices: add an autojoin setting for the notices room

---

changelog.d/16729.bugfix
synapse/rest/admin/federation.py

The docs say these values should be integers (0 if no retries have been tried), but Synapse is currently returning `null` instead.

Set response values to zero if None for /_synapse/admin/v1/federation/destinations

---

changelog.d/16725.bugfix
synapse/handlers/room.py
tests/rest/client/test_upgrade_room.py

Fixes #16715, per https://github.com/matrix-org/synapse/issues/16715#issuecomment-1838349379. Looks to have been introduced in https://github.com/matrix-org/synapse/pull/6237.
C.f. https://spec.matrix.org/v1.9/client-server-api/#mroompower_levels
Sanity checking Erik's reasoning, the point of this code is to ensure that the upgrader is able to set any state in the new room. If `event_power_levels` is empty then there are no extra requirements to impose, so I think a fallback of `0` is sensible.

Fix upgrading a room without `events` field in power levels

---

changelog.d/16737.doc
docs/usage/configuration/config_documentation.md

Clarify documentation for `only_for_reauth`
