synapse/app/homeserver.py, synapse/rest/client/v1/__init__.py, synapse/server.py, tests/rest/client/v1/test_presence.py, tests/rest/client/v1/test_profile.py
Reduce the number of objects involved in creating the client api resource.
=> Merge rest servlets into the client json resource object

README.rst
Added Documentation regarding ArchLinux
=> Update to README.rst

synapse/storage/_base.py, synapse/storage/appservice.py, synapse/storage/roommember.py, synapse/storage/transactions.py, tests/storage/test__base.py
* Extract a '@cached' decorator. Currently only used in a couple of places but hopefully the logic is nice enough we can start using it more from others
* Various little neatenings of cache-related to code elsewhere to add to readability
=> Performance cache improvements

static/client/register/index.html, static/client/register/style.css
Added the classic viewport meta to fix the display on iPhone Safari and webview. The width of input elements also needs to be fixed.
=> Fallback registration page: make the page autoresize on iPhone Safari/Webview

synapse/http/server.py, synapse/http/servlet.py, synapse/rest/client/v2_alpha/sync.py, synapse/rest/media/v1/base_resource.py, synapse/rest/media/v1/download_resource.py, synapse/rest/media/v1/thumbnail_resource.py, synapse/rest/media/v1/upload_resource.py
I'm merging the http wrapper functions in rest/media/v1 and http/server into one place to reduce amount of code duplication and to ensure that they both benefit from the same feature wrt to logging and error handling,
=> Unify http wrappers

synapse/storage/events.py
https://matrix.org/jira/browse/SYN-371
This also pulls in: https://github.com/matrix-org/synapse/pull/137
=> SYN-371 - Failed to persist event

synapse/handlers/presence.py
Reverts matrix-org/synapse#147 as it breaks presence.
=> Revert "Improvement to performance of presence event stream handling"

synapse/handlers/presence.py, tests/handlers/test_presence.py, tests/handlers/test_presencelike.py
and remove some unused arguments from some of the methods
=> Add some doc strings for presence.

synapse/handlers/presence.py, synapse/storage/presence.py, tests/handlers/test_presence.py, tests/handlers/test_presencelike.py, tests/rest/client/v1/test_presence.py
Since it is on the event stream  get_events code path.
=> Add a cache for the presence list

synapse/app/homeserver.py, synapse/config/repository.py
=> Make upload dir a configurable path.

synapse/config/homeserver.py, synapse/config/saml2.py, synapse/handlers/register.py, synapse/python_dependencies.py, synapse/rest/client/v1/login.py
Resending the pull request
Signed-off-by: Muthu Subramanian <muthu.subramanian.karunanidhi@ericsson.com>
=> Integrate SAML2 basic authentication - uses pysaml2

synapse/api/auth.py
https://matrix.org/jira/browse/SYN-192
This changes the rules of power levels so that you can only affect people with lower power levels than you. I.e. you can't change power levels, kick or ban users with the same or greater power level as you.
=> Change power level semantics.

synapse/api/constants.py, synapse/handlers/room.py
Also change default required power levels of such events to 50
=> Add m.room.avatar to default power levels.

synapse/python_dependencies.py
=> Correct pynacl version to 0.3.0

.gitignore, MANIFEST.in, setup.py, tox.ini
Checks flake8, runs the unit tests for py27, and checks that the manifest.in is correct.
=> Add a tox.ini config for synapse.

.gitignore
Get rid of unneccessary lines in git status after testing things :).
Signed-off-by: Stanislav Nikitin <pztrn@pztrn.name>
=> Ignore development virtualenv and generated logger configuration as well.

synapse/config/logger.py
I'd like to make use of this from sytest, in order to mark a single (failing) test case as "you should have your own logfile", so that when it fails I have some chance of picking apart why it failed, without too much noise from all the other activity in it. But I imagine it likely has much other useful utility to others as well.
=> Hacky attempt at catching SIGHUP and rotating the logfile around

synapse/api/auth.py, synapse/api/constants.py, synapse/handlers/message.py, synapse/handlers/room.py, synapse/rest/client/v1/initial_sync.py, synapse/rest/client/v1/room.py, synapse/storage/roommember.py, synapse/storage/stream.py, tests/rest/client/v1/test_rooms.py
Implement the changes implied by matrix-org/matrix-doc#40.
Tested by matrix-org/sytest#14.
=> SPEC-216: Allow users to view the history of rooms that they have left.

synapse/crypto/keyring.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/matrix-org/synapse/282)
=> Fix bug where we sometimes didn't fetch all the keys requested for a server.

synapse/app/synctl.py
Also, allow it to be run from directories other than the synapse directory
=> Allow config file path to be configurable in in synctl

synapse/config/cas.py, synapse/rest/client/v1/login.py
Add optional CAS config for a required attribute (and further optional for required attribute value) to restrict which CAS users can log in to synapse.
Any questions, let me know.
Signed-off-by: Steven Hammerton steven.hammerton@openmarket.com
=> SH CAS Required Attribute

synapse/api/filtering.py, tests/api/test_filtering.py
and remove support for filtering public_user_data.
=> Update the v2 filters to support filtering presence.

synapse/handlers/federation.py, synapse/handlers/message.py, synapse/handlers/sync.py, synapse/storage/state.py
This allows us to get state for events from different rooms.
=> Remove unused room_id arg

tests/crypto/__init__.py, tests/crypto/test_event_signing.py
This test creates a set of repeatable hashes and signatures, so that other implementations can perform a bytewise-perfect check that their algorithm matches ours.
=> Repeatable unit test of event hashing/signing algorithm

synapse/api/filtering.py
This is useful because the emphemeral events such as presence and
typing are represented as dicts inside synapse.
=> Support filtering events represented as dicts.

synapse/api/auth.py, synapse/api/errors.py
=> Reject events which are too large

synapse/handlers/sync.py, synapse/storage/tags.py
Tested by matrix-org/sytest#50
=> SYN-513: Include updates for rooms that have had all their tags deleted

synapse/handlers/sync.py
Overwriting hashes returned by other methods is poor form.
Fixes: SYN-516
=> Don't fiddle with results returned by event sources

synapse/api/constants.py, synapse/handlers/_base.py, synapse/handlers/federation.py, synapse/handlers/message.py, synapse/handlers/presence.py, synapse/handlers/room.py, synapse/rest/client/v1/room.py
Tests in https://github.com/matrix-org/sytest/pull/52
=> Allow guest users to join and message rooms

synapse/storage/events.py, synapse/storage/room.py, synapse/storage/schema/delta/25/guest_access.sql, tests/storage/test_room.py
Tests in https://github.com/matrix-org/sytest/pull/62
=> Return world_readable and guest_can_join in /publicRooms

synapse/app/homeserver.py, synapse/storage/background_updates.py, synapse/storage/schema/delta/25/00background_updates.sql, synapse/storage/schema/delta/25/fts.py, synapse/storage/search.py, synapse/util/__init__.py, tests/storage/test_background_update.py, tests/utils.py
Update database indexes, like full-text-search, in the background while synapse is running.
Each update tracks it progress as a JSON object.
Update full-text search to use the background re-indexing.
=> Incremental background updates for db indexes

synapse/handlers/room.py, synapse/rest/client/v1/room.py
As a side-effect, this also unbreaks the fact that this code is expecting 2 not 3 values from get_user_by_req
=> Allow guests to access room context API

synapse/rest/client/v1/profile.py
Depends: https://github.com/matrix-org/synapse/pull/363
Tests in https://github.com/matrix-org/sytest/pull/66
=> Allow guests to set their display names

synapse/handlers/message.py
* Allow world_readable rooms to be read by guests who have joined and
left
* Allow regular users to access world_readable rooms
=> Tweak guest access permissions

synapse/handlers/_base.py, synapse/handlers/sync.py, synapse/rest/client/v2_alpha/sync.py, synapse/state.py
Add a couple of type annotations, docstrings, and other comments, in the
interest of keeping track of what types I have.
=> Update some comments

jenkins.sh, tox.ini
Outputs:
* results.xml
* coverage.xml
* violations.flake8.log
=> Output results files on jenkins

jenkins.sh, tox.ini
Depends on https://github.com/matrix-org/synapse/pull/379
=> Run sytests on jenkins

jenkins.sh
Depends on https://github.com/matrix-org/synapse/pull/380
=> Share sytest clone across runs

synapse/handlers/search.py
Adds options to:
- Include historic display names in the event context section for all users that sent events during that batch. The options is: `search_categories.room_events.event_context.include_profile`
- Include the current room state for each room returned. The options is: `search_categories.room_events.include_state`
=> Add options for including state in search results

jenkins.sh
if appropriate databases exist for it to run against
=> Run sytest against postgresql

synapse/api/filtering.py, synapse/handlers/account_data.py, synapse/handlers/message.py, synapse/handlers/sync.py, synapse/rest/client/v2_alpha/__init__.py, synapse/rest/client/v2_alpha/account_data.py, synapse/rest/client/v2_alpha/sync.py, synapse/storage/__init__.py, synapse/storage/account_data.py, synapse/storage/schema/delta/26/account_data.sql, synapse/storage/tags.py
@NegativeMjark should squash merge this when he merges it because of foobar.
Implement the API added by matrix-org/matrix-doc#168
Tested by matrix-org/sytest#82
=> Add API for setting per user account data at the top level or room level.

synapse/storage/schema/delta/15/v15.sql
in the very unlikley event that anyone upgrades to 15...
=> Fix schema delta 15 on postgres

synapse/handlers/admin.py, synapse/rest/client/v1/admin.py
Test: https://github.com/matrix-org/sytest/pull/97
Spec: https://github.com/matrix-org/matrix-doc/pull/198
=> Fix implementation of /admin/whois

synapse/storage/schema/delta/25/fts.py
See issue https://github.com/matrix-org/synapse/issues/401
=> Older versions of SQLite don't like IF NOT EXISTS in virtual tables

synapse/rest/client/v1/push_rule.py
Allows bool as legacy fallback
See https://github.com/matrix-org/matrix-doc/pull/212
=> Take object not bool

synapse/util/logcontext.py
Move the resource tracking inside that setter so that it is easier
to make sure that the resource tracking isn't double counting the
resource usage.
=> Add a setter for the current log context.

synapse/app/homeserver.py, synapse/http/server.py, synapse/storage/_base.py, synapse/storage/events.py, synapse/util/logcontext.py
and track the number of transactions that request started.
=> Track the time spent in the database per request.

synapse/push/__init__.py, synapse/push/push_rule_evaluator.py
so it can be more readily reused. Should be functionally identical.
=> Split out the push rule evaluator into a separate file

synapse/handlers/search.py, synapse/storage/search.py
Also change queries to use more efficient query form in postgres
=> Include approximate count of search results

synapse/handlers/room.py
This allows it to form richer emails
=> Give the IS a bunch more 3pid invite context

synapse/handlers/room.py
Spec: https://github.com/matrix-org/matrix-doc/pull/244
Tests: https://github.com/matrix-org/sytest/pull/121
=> Return room avatar URLs in /publicRooms

synapse/notifier.py
Needs matrix-org/sytest#125 to land first
=> Missing yield on guest access auth check

synapse/handlers/sync.py
https://matrix.org/jira/browse/SYN-573
=> Return /sync when something under the 'leave' key has changed

synapse/config/captcha.py
See also https://github.com/matrix-org/package-synapse-debian/pull/2
=> Config Comment mixup in captcha public/private key

README.rst
https://matrix.org/jira/browse/SYN-435
=> Update readme to reflect change in signing key name

README.rst
Add FreeBSD installation instructions for both Ports and Packages now that matrix-synapse has landed [1] in the tree.
[1] https://svnweb.freebsd.org/changeset/ports/405527
=> Add FreeBSD install section & instructions

synapse/handlers/_base.py, synapse/handlers/federation.py, synapse/push/action_generator.py, synapse/push/bulk_push_rule_evaluator.py, synapse/push/push_rule_evaluator.py, synapse/server.py, synapse/storage/receipts.py
Add regex cache. Only caculate push actions for users that have sent read receipts, and are on that server
=> Push actions perf

synapse/push/bulk_push_rule_evaluator.py, synapse/storage/push_rule.py
otherwise they won't be able to disable server default rules.
Does one more bulk (batched) db query at bulk push rule eval time.
=> Overlay the push_rules_enabled map for users

synapse/api/filtering.py, synapse/handlers/sync.py, synapse/rest/client/v2_alpha/sync.py, tests/api/test_filtering.py
This includes PR https://github.com/matrix-org/synapse/pull/518
I've also changed it so that if a user gives an unrecognised filter id the server will return an error rather than using a default.
=> Move some sync logic from rest to handlers pacakege

synapse/rest/client/v1/push_rule.py, synapse/storage/push_rule.py
Fixes https://matrix.org/jira/browse/SYN-592
Fixes https://matrix.org/jira/browse/SYN-591
=> Fix adding push rules relative to other rules

synapse/app/homeserver.py, synapse/server.py, synapse/storage/__init__.py, synapse/storage/_base.py, synapse/storage/events.py, synapse/storage/receipts.py, synapse/storage/stream.py, synapse/storage/tags.py, synapse/storage/util/id_generators.py, tests/storage/test_appservice.py, tests/storage/test_registration.py, tests/utils.py
This is for setting up dependencies that require work on startup. This
is useful for the DataStore that wants to read a bunch from the database
before initializing.
=> Add a Homeserver.setup method

synapse/handlers/register.py
makes guest user actually recorded as such in the db
=> Pass make_guest when we autogen a user ID

synapse/handlers/register.py
This whole set of checks is kind of an ugly mess, which I may clean up
at some point, but for now let's be correct.
=> Enforce user_id exclusivity for AS registrations

tests/api/test_filtering.py
Also check that the __repr__ method for FilterCollection does something
sensible.
=> Test Filter.filter_rooms

synapse/handlers/_base.py
so the invitee has their display name and avatar.
=> Send the invier's member event in room invite state

scripts/synapse_port_db, synapse/app/homeserver.py, synapse/storage/appservice.py, synapse/storage/engines/__init__.py, synapse/storage/engines/postgres.py, synapse/storage/engines/sqlite3.py, synapse/storage/prepare_database.py, synapse/storage/schema/delta/30/as_users.py, tests/storage/test_base.py, tests/utils.py
Note that this PR also marks the 'id' field in AS configuration files as required. This is a breaking change.
=> Mark AS users with their AS's ID

synapse/handlers/_base.py, synapse/handlers/directory.py, synapse/handlers/federation.py, synapse/handlers/message.py, synapse/handlers/profile.py, synapse/handlers/room.py, synapse/rest/client/v1/directory.py, synapse/rest/client/v1/profile.py, synapse/rest/client/v1/room.py, tests/handlers/test_profile.py, tests/replication/test_resource.py, tests/rest/client/v1/test_profile.py, tests/utils.py
This will enable more detailed decisions
=> Pass whole requester to ratelimiting

synapse/handlers/directory.py, synapse/rest/client/v1/directory.py, synapse/storage/directory.py, synapse/storage/schema/delta/30/alias_creator.sql
Sytest: https://github.com/matrix-org/sytest/pull/197
=> Allow alias creators to delete aliases

synapse/api/auth.py, synapse/handlers/room.py, tests/rest/client/v1/test_rooms.py, tests/rest/client/v1/test_typing.py, tests/rest/client/v2_alpha/__init__.py
since there is no Matrix API to discover what user ID an access token is for.
=> Send the user ID matching the guest access token

synapse/http/servlet.py, synapse/rest/client/v1/directory.py, synapse/rest/client/v1/login.py, synapse/rest/client/v1/push_rule.py, synapse/rest/client/v1/pusher.py, synapse/rest/client/v1/register.py, synapse/rest/client/v1/room.py, synapse/rest/client/v2_alpha/_base.py, synapse/rest/client/v2_alpha/account.py, synapse/rest/client/v2_alpha/register.py, synapse/rest/client/v2_alpha/tokenrefresh.py
to deduplicate all the copy+pasted _parse_json functions. Also document
the parse_.* functions.
=> Add a parse_json_object function

synapse/storage/schema/delta/30/as_users.py
This significantly speeds up the updates on my desktop.
=> Update users table in a batched manner

synapse/rest/__init__.py, synapse/rest/client/v1/logout.py, synapse/storage/registration.py
https://github.com/matrix-org/sytest/pull/207
=> Implement logout

README.rst, scripts/gen_password, scripts/hash_password
Replace the bash/perl gen_password script with a python one, and write a note
on how to use it.
=> Password reset docs and script

synapse/notifier.py, synapse/replication/resource.py, synapse/rest/client/v1/pusher.py, synapse/storage/__init__.py, synapse/storage/pusher.py, synapse/storage/schema/delta/30/deleted_pushers.sql, synapse/storage/util/id_generators.py, tests/replication/test_resource.py
=> Add replication stream for pushers

synapse/federation/federation_server.py
This ensures we don't return a 200 OK for the transaction until we have actually dealt with the EDU
=> Yield on EDU handling

synapse/push/baserules.py
Fixes https://github.com/vector-im/vector-web/issues/828
=> Never notify for member events.

AUTHORS.rst
Added myself as author for https://github.com/matrix-org/synapse/pull/671
=> Add new author

synapse/push/push_rule_evaluator.py
Fixes https://github.com/vector-im/vector-web/issues/1244
=> Don't ignore the obey overlay if the rule has an enabled attribute of False

synapse/handlers/room_member.py, synapse/storage/events.py, synapse/storage/prepare_database.py, synapse/storage/roommember.py, synapse/storage/schema/delta/31/invites.sql
=> Store invites in a separate table.

scripts/synapse_port_db, synapse/app/homeserver.py, synapse/storage/engines/__init__.py, synapse/storage/engines/postgres.py, synapse/storage/engines/sqlite3.py, synapse/storage/prepare_database.py, synapse/storage/schema/delta/14/upgrade_appservice_db.py, synapse/storage/schema/delta/20/pushers.py, synapse/storage/schema/delta/25/fts.py, synapse/storage/schema/delta/27/ts.py, synapse/storage/schema/delta/30/as_users.py, tests/storage/test_base.py, tests/utils.py
This breaks upgrades of SQLite databases from before April 2015.
=> Don't require config to create database

synapse/replication/slave/__init__.py, synapse/replication/slave/storage/__init__.py, synapse/replication/slave/storage/_base.py, synapse/replication/slave/storage/_slaved_id_tracker.py, synapse/replication/slave/storage/events.py, synapse/storage/events.py, tests/replication/slave/__init__.py, tests/replication/slave/storage/__init__.py, tests/replication/slave/storage/_base.py, tests/replication/slave/storage/test_events.py
Add a test to check that get_room_names_and_aliases does the same
thing on both the master and on the slave data store.
=> Add a slaved events store class

synapse/handlers/_base.py
... otherwise clients get confused.
Fixes https://matrix.org/jira/browse/SYN-662,
https://github.com/vector-im/vector-web/issues/368
=> Let users see their own leave events

synapse/handlers/room_member.py
SyTest: https://github.com/matrix-org/sytest/pull/223
=> Set profile information when joining rooms remotely

synapse/handlers/message.py, synapse/handlers/profile.py
rather than using collect_presencelike_data
=> Call profile handler get_displayname directly

synapse/replication/slave/storage/events.py, tests/replication/slave/storage/test_events.py
Add ``get_invited_rooms_for_user`` to the ``SlavedEventStore`` and add the necessary cache invalidation logic.
=> Replicate get_invited_rooms_for_user

synapse/http/client.py
Otherwise it's impossible to write sytests for.
=> Use tls_server_context_factory for SpiderEndpoint

synapse/storage/receipts.py
I'm abusing this "feature" of the db in tests.replication.slave.test_receipts.
=> Allow receipts for events we haven't seen in the db

synapse/app/pusher.py, synapse/push/mailer.py, synapse/replication/slave/storage/events.py
Plus general bugfix to email notif code
=> Make email notifs work on the pusher synapse

synapse/api/auth.py, synapse/handlers/federation.py, synapse/handlers/message.py, synapse/handlers/presence.py, synapse/storage/roommember.py, synapse/types.py
=> Spell "domain" correctly

synapse/handlers/receipts.py, synapse/handlers/room_member.py, synapse/handlers/sync.py, synapse/handlers/typing.py, synapse/storage/roommember.py, tests/handlers/test_typing.py, tests/storage/test_roommember.py, tests/utils.py
=> Cleanup room member handler

res/templates/mail.css, res/templates/notif_mail.html, synapse/push/emailpusher.py, synapse/push/mailer.py
=> tune email notifs, fix CSS a bit, and add debugging details

synapse/handlers/__init__.py, synapse/handlers/sync.py, synapse/rest/client/v2_alpha/sync.py, synapse/server.py
=> Move SyncHandler out of the Handlers object

synapse/handlers/__init__.py, synapse/handlers/register.py, synapse/rest/client/v1/login.py, synapse/rest/client/v2_alpha/account.py, synapse/rest/client/v2_alpha/auth.py, synapse/rest/client/v2_alpha/register.py, synapse/rest/client/v2_alpha/tokenrefresh.py, synapse/server.py, tests/rest/client/v2_alpha/test_register.py, tests/utils.py
So I can use it in the pusher to make macaroons to authenticate email unsubscribe requests
=> Split out the auth handler

synapse/handlers/typing.py, tests/handlers/test_typing.py
Rather than storing them as UserID objects.
=> Store the typing users as user_id strings.

synapse/replication/slave/storage/presence.py, synapse/storage/__init__.py
Should have the methods needed for /sync.
=> Add a slaved store for presence

synapse/replication/slave/storage/account_data.py, synapse/replication/slave/storage/events.py, synapse/replication/slave/storage/receipts.py
Adds the methods needed by /sync to the slaved events,
account data and receipt stores.
=> Add methods to events, account data and receipt slaves

synapse/notifier.py
Change how the notifier updates the map from room_id to user streams on
receiving a join event. Make it update the map when it notifies for the
join event, rather than using the "user_joined_room" distributor signal
=> Notify users for events in rooms they join.

synapse/federation/transport/server.py, synapse/rest/client/v1/room.py
-  Enable auth on federation PublicRoomList
- Log user that is making /publicRooms calls
=> Enable auth on /publicRoom endpoints

synapse/handlers/room.py
It turns out that `state_handler.get_current_state` loads all the state anyway.
=> Pull full state for each room all at once

synapse/handlers/register.py, tests/handlers/test_register.py
Fix a bug caused by a change in auth_handler function
also fix the relevant unit test cases
=> Fix a bug caused by a change in auth_handler function

synapse/push/mailer.py
Fixes a key error where the mailer tried to get the ``msgtype`` of an
event that was missing a ``msgtype``.
```
File "synapse/push/mailer.py", line 264, in get_notif_vars
File "synapse/push/mailer.py", line 285, in get_message_vars
File ".../frozendict/__init__.py", line 10, in __getitem__
return self.__dict[key]
KeyError: 'msgtype'
```
=> Fix ``KeyError: 'msgtype'``. Use ``.get``

synapse/api/auth.py, synapse/handlers/auth.py, synapse/handlers/register.py, synapse/rest/client/v1/register.py, tests/api/test_auth.py, tests/handlers/test_register.py
A fix for actually expiring the access tokens with  a time limit.
=> Bug fix: expire invalid access tokens

synapse/rest/client/v2_alpha/account.py
Spec: https://github.com/matrix-org/matrix-doc/pull/361
Tests: https://github.com/matrix-org/sytest/issues/262
=> Feature: Add an /account/deactivate endpoint

synapse/storage/events.py
This was caused by trying to insert duplicate backward extremeties
=> Fix /purge_history bug

synapse/handlers/auth.py, synapse/rest/client/v1/login.py
Make sure that we have the canonical user_id *before* calling
get_login_tuple_for_user_id.
Replace login_with_password with a method which just validates the password,
and have the caller call get_login_tuple_for_user_id. This brings the password
flow into line with the other flows, and will give us a place to register the
device_id if necessary.
=> Refactor login flow

synapse/handlers/__init__.py
=> Update docstring on Handlers.

MANIFEST.in, synapse/handlers/_base.py, synapse/handlers/auth.py, synapse/rest/client/v1/base.py, synapse/rest/client/v1/register.py, synapse/rest/client/v2_alpha/register.py, synapse/server.pyi
Add some type annotations to help PyCharm (in particular) to figure out the
types of a bunch of things.
=> Type annotations

synapse/handlers/device.py, tests/handlers/test_device.py
Turns out I specced this to return a list of devices rather than a dict of them
=> make /devices return a list

synapse/util/presentable_names.py
Avoids insane pushes like, "Bob invited you to invite from Bob"
=> Don't include name of room for invites in push

synapse/storage/event_push_actions.py
Also sneakily makes `max_stream_ordering` mandatory, as it makes **no sense** for it to ever be called without a max ordering given concurrent inserts. Checked all usages via grep and we were surprise, surprise, always giving a max stream ordering so yay :D
=> Comment get_unread_push_actions_for_user_in_range function

MANIFEST.in, jenkins-dendron-postgres.sh, jenkins-postgres.sh, jenkins-sqlite.sh, jenkins/clone.sh, jenkins/prepare_synapse.sh
Ideally I'd update the jenkins scripts in sytest and dendron to use these scripts.
=> Factor out some of the code shared between the sytest scripts

synapse/federation/federation_server.py, synapse/federation/transport/server.py, synapse/handlers/e2e_keys.py, synapse/rest/client/v2_alpha/keys.py, synapse/server.py, synapse/server.pyi
... Move it into a handler, and make the federation and client queries share
implementation.
=> Refactor E2E query code

synapse/handlers/e2e_keys.py
... which makes it more consistent with user displaynames.
=> keys/query: Omit device displayname if null

synapse/federation/federation_client.py, synapse/storage/events.py
This corrects various trivial errors in #983, per discussion with @erikjohnston.
=> Tweak integrity error recovery to work as intended

synapse/rest/client/v1/login.py
Attempting to log in with CAS was giving a 500 error.
=> Fix CAS login

synapse/rest/client/v1/login.py
Remove some apparently unused code.
Clean up parse_cas_response, mostly to catch the exception if the CAS response
isn't valid XML.
=> Clean up CAS login code

synapse/app/synchrotron.py, synapse/handlers/presence.py, synapse/rest/client/v2_alpha/sync.py
Addressing https://matrix.org/jira/browse/SYN-747
Signed-off-by: Will Hunt half-shot@molrams.com
=> Don't change status_msg on /sync

synapse/handlers/auth.py
See the commit messages for more details.
=> Fix some bugs in the auth/ldap handler

synapse/handlers/federation.py
This works around a bug where if we make a backfill request with too many extremities it causes the request URI to be too long.
=> Limit number of extremeties in backfill request

jenkins-unittests.sh, synapse/rest/media/v1/preview_url_resource.py, tests/test_preview.py
This includes:
- Splitting out methods of a class into stand alone functions, to make them easier to test.
- Adding unit tests to split out functions, testing HTML -> preview.
- Handle the fact that elements in `lxml` may have tail text.
=> Fix up preview URL API. Add tests.

synapse/push/baserules.py, synapse/storage/schema/delta/34/push_display_name_rename.sql
As per https://github.com/matrix-org/matrix-doc/pull/373 and comment
Sorry github has made such a complete dog's dinner of this diff
=> Move display name rule

README.rst
Signed-off-by: Fabian Niepelt <fniepelt@takios.de>
=> Add prerequisites to install on openSUSE to README

synapse/rest/client/v1/room.py
Tested in https://github.com/matrix-org/sytest/pull/306
=> Allow clients to ask for the whole of a single state event

synapse/storage/event_push_actions.py, synapse/storage/schema/delta/35/event_push_actions_index.sql
and remove room_id caluse so it uses it
Mostly from @negativemjark
=> Add index to event_push_actions

synapse/storage/state.py
It turns out that postgres doesn't like doing a list of OR's and is about 1000x slower, so we just issue a query for each specific type separately.
=> Change state fetch query for postgres to be faster

synapse/handlers/auth.py
- properly parse return values of ldap bind() calls
- externalize authentication methods
- change control flow to be more error-resilient
- unbind ldap connections in many places
- improve log messages and loglevels
=> Restructure ldap authentication

synapse/handlers/typing.py
There's a bug somewhere that causes typing notifications to not be timed
out properly. By adding a paranoia timer and using correct inequalities
notifications should stop being stuck, even if it the root cause hasn't
been fixed.
=> Fix infinite typing bug

synapse/handlers/auth.py
Fixes https://matrix.org/jira/browse/SYN-773
Fixes https://github.com/vector-im/vector-web/issues/2538
=> Don't error on non-ascii passwords

synapse/config/_base.py
Signed-off-by: Daniel Dent <matrixcontrib@contactdaniel.net>
=> Add support for durations in minutes

synapse/rest/client/v2_alpha/register.py
Works around https://github.com/vector-im/vector-android/issues/715
and equivalent for iOS
=> Work around client replacing reg params

synapse/api/auth.py
=> Remove redundant list of known caveat prefixes

setup.py
Using tox to run the tests is a bad idea, as per the comments.
=> Don't try to run tox from setup.py

README.rst
- something of a corrolary to #1684
=> Update the readme to use trial

README.rst
I installed synapse on a fresh mac os sierra yesterday and I needed these 2 libs.
=> Update prerequisites instructions on Mac OS

synapse/handlers/sync.py, synapse/storage/deviceinbox.py
Attempt to track down the loss of to_device events
(https://github.com/vector-im/riot-web/issues/2711 etc).
=> Add some logging for syncing to_device events

synapse/handlers/auth.py
https://github.com/vector-im/riot-web/issues/2658
=> fix ability to change password to a non-ascii one

synapse/app/appservice.py, synapse/app/client_reader.py, synapse/app/federation_reader.py, synapse/app/federation_sender.py, synapse/app/homeserver.py, synapse/app/media_repository.py, synapse/app/pusher.py, synapse/app/synchrotron.py, synapse/config/server.py
=> Restore default bind address

synapse/api/auth.py, synapse/handlers/federation.py, synapse/state.py
Add make the cache size bigger.
=> Change resolve_state_groups call site logging to DEBUG

synapse/api/constants.py
=> Remove a few aspirational but unused constants

synapse/config/tls.py
Signed-off-by: Tyler Smith <tylersmith.me@gmail.com>
=> Fix typo in config comments.

synapse/rest/media/v1/media_repository.py
=> Fix #1677 (dynamic thumbnails aspect)

scripts/synapse_port_db
See https://matrix.to/#/!cURbafjkfsMDVwdRDQ:matrix.org/$148686272020hCgRD:potatofrom.space
=> Fix synapse_port_db failure (fixes #1902)

synapse/storage/prepare_database.py, synapse/storage/schema/delta/41/device_outbound_index.sql
As this is used for replication streaming
=> Add stream_id index to device_lists_outbound_pokes

synapse/storage/_base.py
looks like the upsert function was accidentally sending sql logging to the
general logger.
=> Remove spurious SQL logging

synapse/rest/client/v1/login.py
Disclaimer: I've not tested this because I don't have a CAS server to test against.
=> Handle PartialDownloadError in CAS login

docs/log_contexts.rst, synapse/util/logcontext.py
A bunch of RST about how logcontexts work
=> Logcontext docs

synapse/crypto/keyring.py
Ref: https://github.com/matrix-org/synapse/issues/2034
=> Add some debug to help diagnose weird federation issue

synapse/rest/client/v2_alpha/register.py
Like #2048, but more so
I've grepped for them this time. Hopefully it's the last one.
=> Add another missing yield on check_device_registered

README.rst
Also added Fedora 25 to header as the same packages work for it as well.
=> Add missing package to CentOS section

synapse/handlers/federation.py, synapse/handlers/message.py, synapse/notifier.py, synapse/util/logcontext.py
A series of commits clearing out some of the logcontext-preservation litter.
=> Cull spurious PreserveLoggingContexts

docs/metrics-howto.rst
those 2 items are:
* the prometheus yaml -> put the target under scrape_configs
* my targets are an array (as is the default prometheus target I was looking at) - consistency
=> setting up metrics, just adding/clarifying 2 very minor items

synapse/handlers/federation.py
This should help to clarify what is going on while processing a single federation transaction
=> Add some extra logging for edge cases of federation

synapse/http/client.py
=> Rewrite SimpleHttpClient.request to include timeouts 

synapse/rest/client/v2_alpha/register.py
Updates https://github.com/matrix-org/synapse/pull/2183
=> Change register/available to POST (from GET)

synapse/storage/user_directory.py
Fixes bug where we tried to update a users entry without having added them
=> Fix user dir to not assume existence of user

synapse/app/user_dir.py, synapse/config/server.py, synapse/handlers/user_directory.py, synapse/replication/tcp/streams.py, synapse/storage/events.py
This tested by https://github.com/matrix-org/sytest/compare/develop...erikj/split_out_user_dir, which depends on an unlanded PR
=> Split out user directory to a separate process

synapse/rest/media/v1/download_resource.py, synapse/rest/media/v1/filepath.py, synapse/rest/media/v1/media_repository.py, synapse/rest/media/v1/preview_url_resource.py, synapse/rest/media/v1/thumbnail_resource.py, synapse/storage/media_repository.py, synapse/storage/schema/delta/43/url_cache.sql
This makes it easier to clear old media out at a later date
=> Store URL cache preview downloads separately

contrib/prometheus/README, contrib/prometheus/consoles/synapse.html, contrib/prometheus/synapse.rules
... from https://github.com/matrix-org/synapse-prometheus-config.
=> Add prometheus config

scripts-dev/federation_client.py
Make it read the config file, primarily.
=> Improvements to the federation test client

synapse/crypto/keyring.py, synapse/federation/federation_base.py, synapse/federation/federation_client.py, synapse/storage/keys.py, tests/crypto/test_keyring.py
Refactor the Keyring code a bit, and try to bring some sanity to its use of logcontexts.
Each commit in this PR should make sense.
=> Clean up Keyring code

README.rst
Because of the constant flow of people screwing up with the network setup and TLS certificates, here is an improved README to clarify various points.
Should fix #2438
=> Clarify recommended network setup

synapse/config/password_auth_providers.py, synapse/util/module_loader.py
=> Factor out module loading to a separate place

synapse/handlers/federation.py
* Avoid preserve_context_over_deferred, which is broken
* set consumeErrors=True on defer.gatherResults, to avoid spurious "unhandled
failure" erros
=> Fix up deferred handling in federation.py

synapse/federation/transaction_queue.py
Avoid using preserve_context_over_function, which has problems with respect to
logcontexts.
=> Fix up logcontext handling in (federation) TransactionQueue

synapse/federation/federation_server.py
Move as much as possible to after the have_responded check, and reduce the
number of times we iterate over the pdu list.
=> fed server: refactor on_incoming_transaction

synapse/storage/group_server.py
The stream update functions expect the storage function to return a list
of tuples.
=> Fix group stream replication

synapse/handlers/groups_local.py
=> Log a warning when no profile for invited member

synapse/storage/events.py, synapse/util/async.py
* don't use preserve_context_over_deferred, which is known broken.
* remove a redundant preserve_fn.
* add/improve some comments
=> Fix logcontext handling for persist_events

synapse/events/builder.py, synapse/handlers/auth.py, synapse/handlers/room.py, synapse/rest/client/v1/login.py, synapse/rest/client/v2_alpha/groups.py, synapse/types.py
It just calls the constructor, so we may as well kill it rather than having
random codepaths.
=> Remove pointless create() method

docs/code_style.rst
This is mostly about documenting the import rules, but also includes some general tidying and reformatting. See the commits if that's easier.
=> Code_style updates

synapse/http/client.py
`preserve_context_over_fn` is borked
=> Fix logcontext leaks in httpclient

synapse/app/frontend_proxy.py
(So that we can stop riot relying on it in /unstable)
=> Support /keys/upload on /r0 as well as /unstable

synapse/rest/client/v2_alpha/devices.py
(otherwise there's no point in the UI auth)
=> Device deletion: check UI auth matches access token

synapse/app/frontend_proxy.py
This requires https://github.com/matrix-org/synapse/pull/2586, and does the same as that, but for the extra endpoint that's only on the matrix-org-hotfixes branch.
=> Front-end proxy: fix auth header for presence too

synapse/groups/attestations.py, synapse/groups/groups_server.py, synapse/storage/group_server.py
This should help with https://github.com/matrix-org/synapse/issues/2592
=> Don't generate group attestations for local users

synapse/groups/attestations.py
Reverts matrix-org/synapse#2596
=> Revert "Add jitter to validity period of attestations"

synapse/groups/groups_server.py
Fix https://github.com/vector-im/riot-web/issues/5272
=> Fix wording on group creation error

docs/password_auth_providers.rst
Document the existing interface, before I start adding new stuff.
=> Start some documentation on password providers

synapse/config/password_auth_providers.py
try to make the backwards-compat flows follow the same code paths as the modern
impl.
This commit should be non-functional.
=> Clean up backwards-compat hacks for ldap

synapse/handlers/auth.py, synapse/rest/client/v1/login.py
I'm going to need some more flexibility in handling login types in password
auth providers, so as a first step, move some stuff from LoginRestServlet into
AuthHandler.
In particular, we pass everything other than SAML, JWT and token logins down to
the AuthHandler, which now has responsibility for checking the login type and
fishing the password out of the login dictionary, as well as qualifying the
user_id if need be. Ideally SAML, JWT and token would go that way too, but
there's no real need for it right now and I'm trying to minimise impact.
This commit *should* be non-functional.
=> Refactor some logic from LoginRestServlet into AuthHandler

synapse/federation/transport/client.py, synapse/federation/transport/server.py, synapse/groups/groups_server.py, synapse/handlers/groups_local.py, synapse/rest/client/v2_alpha/groups.py, synapse/storage/group_server.py
also includes renamings to make things more consistent.
=> Modify group room association API to allow modification of is_public

synapse/rest/client/v1/login.py
Carefully though, to avoid logging passwords
=> Log login requests

synapse/handlers/auth.py
Somewhat open to abuse, but also somewhat unavoidable :/
=> Let auth providers get to the database

docs/password_auth_providers.rst, synapse/handlers/auth.py, synapse/rest/client/v1/login.py
... so that they have a way to record access tokens.
=> Allow password_auth_providers to return a callback

docs/password_auth_providers.rst, synapse/handlers/auth.py, synapse/storage/registration.py
Provide a hook by which auth providers can be notified of logouts.
=> Notify auth providers on logout

synapse/app/homeserver.py
This was a bit of a code vomit, so let's factor it out to preserve some sanity
=> Factor out _configure_named_resource

docs/password_auth_providers.rst, synapse/handlers/auth.py, synapse/module_api/__init__.py
We're going to need to use this from places that aren't password auth, so let's
move it to a proper class.
=> Factor _AccountHandler proxy out to ModuleApi

synapse/module_api/__init__.py
add `get_user_by_req` and `invalidate_access_token`
(this PR is a superset of https://github.com/matrix-org/synapse/pull/2626)
=> Add more hooks to ModuleApi

synapse/rest/client/v2_alpha/register.py
Allow things to pass inhibit_login when registering to ... inhibit logins.
=> support inhibit_login in /register

synapse/groups/groups_server.py
Return entries with is_public = True when they're public and is_public = False otherwise.
=> Make the get_rooms_in_group API more sane

synapse/util/async.py
Add some logging to the Limiter in a similar spirit to the Linearizer, to help
debug issues.
Also fix a logcontext leak.
Also refactor slightly to avoid throwing exceptions.
=> Logging and logcontext fixes for Limiter

synapse/groups/groups_server.py, synapse/storage/group_server.py
Done in favour of https://github.com/matrix-org/synapse/pull/2645 because it was a ultimately a hack and we can deal with ordering on the client, and worry about pagination (and the ordering of members from the server) later.
=> Return whether a user is an admin within a group

synapse/handlers/register.py
Because we're never going to be able to fix this :'(
=> Allow upper-case characters in mxids

synapse/handlers/register.py, synapse/rest/client/v1/register.py, synapse/rest/client/v2_alpha/register.py
Force username to lowercase before attempting to register
https://github.com/matrix-org/synapse/issues/2660
=> Downcase userid on registration

synapse/handlers/room_list.py
Adds some logging and reshuffles the code. It might help, it might not, but the extra logging might be useful either way.
(Two commits, one just logging, one a refactor)
=> Reshuffle room list request code

synapse/handlers/auth.py
=> Fix auth handler

synapse/storage/pusher.py, synapse/storage/schema/delta/46/drop_unique_deleted_pushers.sql
* replace the upsert into deleted_pushers with an insert
* no need to lock for upsert on pusher_throttle
=> Avoid locking for upsert on pushers tables

docs/workers.rst
Fixes https://github.com/matrix-org/synapse/issues/2554
=> Improve documentation of workers

synapse/app/synchrotron.py
Add a comment, remove a dead code line
=> Tiny code cleanups

synapse/federation/transaction_queue.py, synapse/notifier.py
These processes take a long time compared to the request, so there is lots of
"Entering|Restoring dead context" in the logs. Let's try to shut it up a bit.
=> Clear logcontext before starting fed txn queue runner

synapse/config/password_auth_providers.py
Signed-off-by: Richard von Seck <richard.von-seck@gmx.net>
=> synapse/config/password_auth_providers: Fixed bracket typo

synapse/federation/federation_base.py, synapse/federation/federation_client.py, synapse/federation/federation_server.py
Return a 400 rather than a 500 when somebody messes up their send_join
(commits are probably easier to review individually)
=> Check missing fields in event_from_pdu_json

synapse/event_auth.py
Fixes https://github.com/matrix-org/synapse/issues/2759
Signed-off-by: Travis Ralston <travpc@gmail.com>
=> Fix templating error with unban permission message

tests/rest/client/v1/test_rooms.py, tests/unittest.py, tests/utils.py
Disable user_directory updates
also a couple of small cleanups
=> Fix flaky test_rooms UTs

synapse/rest/client/v1/room.py
Turns out that there is a valid usecase for retrieving event by id (notably having received a push), but event ids should be scoped to room, so /event/{id} is wrong.
=> Add /room/{id}/event/{id} to synapse

synapse/replication/tcp/protocol.py
I found myself wishing we had this.
=> Metrics for number of RDATA commands received

synapse/federation/transaction_queue.py, synapse/handlers/appservice.py
=> Metrics for events processed in appservice and fed sender

synapse/storage/events.py
ObserveableDeferred expects its callbacks to be called without any
logcontexts, whereas it turns out we were calling them with the logcontext of
the request which initiated the persistence loop.
It seems wrong that we are attributing work done in the persistence loop to the
request that happened to initiate it, so let's solve this by dropping the
logcontext for it.
(I'm not sure this actually causes any real problems other than messages in the
debug log, but let's clean it up anyway)
=> Fix a logcontext leak in persist_events

synapse/storage/_base.py
... so that we can share the code
(factored out from #2775)
=> rework runInteraction in terms of runConnection

README.rst
Signed-off-by: Jeremy Cline <jeremy@jcline.org>
=> Note that Synapse is available in Fedora

synapse/config/repository.py, synapse/rest/media/v1/media_repository.py, synapse/rest/media/v1/storage_provider.py
I'm not the worlds biggest fan when it comes to how we store the class in the config, but it matches what we do with auth providers.
=> Make storage providers configurable

tests/replication/slave/storage/_base.py
Extracted from https://github.com/matrix-org/synapse/pull/2820
=> Matthew's fixes to the unit tests

synapse/app/appservice.py, synapse/app/client_reader.py, synapse/app/federation_reader.py, synapse/app/federation_sender.py, synapse/app/frontend_proxy.py, synapse/app/homeserver.py, synapse/app/media_repository.py, synapse/app/pusher.py, synapse/app/synchrotron.py, synapse/app/user_dir.py, synapse/server.py
This function is identical to all subclasses, so we may as well push it up to
the base class to reduce duplication (and make use of it in the tests)
=> Factor out get_db_conn to HomeServer base class

tests/utils.py
This isn't used, and looks thoroughly bitrotted.
=> Remove unused/bitrotted MemoryDataStore

synapse/storage/user_directory.py, tests/storage/test_user_directory.py, tests/utils.py
fix some syntax errors for user search when search_all_users is enabled
fixes #2801, hopefully
=> Fix SQL for user search

synapse/http/client.py, synapse/push/httppusher.py
Add some metrics to the pusher, and improve logging
... just to help figure out what it's up to.
=> Logging and metrics for the http pusher

synapse/storage/events.py
Just chop _calculate_state_delta in half and have the caller call both halves. This reduces the scope of a bunch of variables and simplifies the logic.
=> factor _get_new_state_after_events out of _calculate_state_delta

synapse/rest/media/v1/preview_url_resource.py
avoid failing with an exception if the remote server doesn't give us a
Content-Type header.
Also, clean up the exception handling a bit.
=> Handle url_previews with no content-type

synapse/storage/room.py, synapse/storage/search.py
we can reuse the same code as is used for event insert, for doing the
background index population.
=> Factor out common code for search insert

synapse/storage/events.py
we already have the state from _get_new_state_after_events, so returning it
from _calculate_state_delta is just confusing.
=> Remove redundant return value from _calculate_state_delta

synapse/storage/events.py
commit 278d21b5 added new code to avoid the tablescan, but didn't remove the
old :/
=> (Really) fix tablescan of event_push_actions on purge

synapse/handlers/federation.py
This duplicates the code in `messages.py`, but I'm not sure if its worth splitting the two out
=> Delete from push_actions_staging in federation too

synapse/replication/slave/storage/events.py, synapse/storage/events.py, synapse/storage/roommember.py
Includes #2902 
All the changes in `synapse.storage.roommember` should just be shuffling functions around
=> Split out RoomMemberStore

synapse/app/event_creator.py, synapse/handlers/message.py, synapse/replication/http/send_event.py
=> Calculate push actions on worker

synapse/util/logcontext.py
... because (a) it's actually simpler (b) it might be marginally more
performant?
=> Rewrite make_deferred_yieldable avoiding inlineCallbacks

synapse/handlers/read_marker.py, synapse/replication/slave/storage/account_data.py, synapse/storage/account_data.py, synapse/storage/events.py
(I've also added some sytests https://github.com/matrix-org/sytest/pull/433)
=> Improve caching for read_marker API

synapse/replication/slave/storage/directory.py, synapse/storage/directory.py
(And cheekily fix a cache invalidation when deleting an alias)
=> Split Directory store

synapse/storage/events.py
This seems like a useful thing to measure.
=> Add Measure block for persist_events

synapse/storage/room.py
This is needed by the base room member handler
=> Add is_blocked to worker store

synapse/federation/transport/client.py, synapse/federation/transport/server.py, synapse/groups/groups_server.py, synapse/handlers/groups_local.py, synapse/rest/client/v2_alpha/groups.py, synapse/storage/group_server.py, synapse/storage/prepare_database.py, synapse/storage/schema/delta/48/groups_joinable.sql
Adds API to set the 'joinable' flag, and corresponding flag in the
table.
=> Add joinability for groups

synapse/federation/transport/client.py, synapse/federation/transport/server.py, synapse/groups/groups_server.py, synapse/handlers/groups_local.py, synapse/storage/group_server.py
Based off https://github.com/matrix-org/synapse/pull/3045
=> Implement group join API

contrib/graph/graph3.py, scripts/synapse_port_db, synapse/appservice/__init__.py, synapse/config/_base.py, synapse/config/appservice.py
Signed-off-by: Adrian Tschira <nota@notafile.com>
=> Replace some type checks with six type checks

synapse/api/auth.py, synapse/app/frontend_proxy.py, synapse/http/server.py, synapse/http/site.py, synapse/rest/client/v1/register.py, tests/utils.py
This has no effect on python2
Signed-off-by: Adrian Tschira <nota@notafile.com>
=> Add b prefixes to some strings that are bytes in py3

synapse/federation/transport/server.py
we were checking the wrong server_name on inbound requests
=> fix federation_domain_whitelist

synapse/storage/event_federation.py, synapse/util/file_consumer.py
and a six.range change which I missed the last time
=> Replace Queue with six.moves.queue

jenkins/prepare_synapse.sh, synapse/python_dependencies.py
* add some doc about wtf this thing does
* pin Twisted to < 18.4
* add explicit dep on six (fixes #3089)
=> Miscellaneous fixes to python_dependencies

synapse/handlers/appservice.py
I've tried to grep for more of this with no success.
Signed-off-by: Adrian Tschira <nota@notafile.com>
=> Don't yield in list comprehensions

synapse/rest/client/v1/admin.py
fixes #3076 
Signed-Off-by: Matthias Kesler <krombel@krombel.de>
=> add guard for None on purge_history api

synapse/storage/profile.py
as this works on sqlite and postgres (postgres doesn't have IFNULL)
=> Use COALESCE rather than IFNULL

synapse/util/logformatter.py, tests/util/test_logformatter.py
This was introduced in 4f2f5171
cc @notafile
=> Fix incorrect reference to StringIO

scripts-dev/nuke-room-from-db.sh
Signed-off-by: Ruben Barkow <github@r.z11.de>
=> nuke-room-from-db.sh: added postgresql option and help

scripts-dev/nuke-room-from-db.sh
Signed-off-by: Ruben Barkow <github@r.z11.de>
=> nuke-room-from-db.sh: fix deletion from search table

synapse/storage/stream.py
This makes it easier to document what is being returned by the storage
functions and what some functions expect as arguments.
Based off of #3195
=>  Refactor pagination DB API to return concrete type

synapse/federation/units.py
transaction_id, destination defined twice
=> transaction_id, destination defined twice

CHANGES.rst, synapse/storage/chunk_ordered_table.py, synapse/storage/events.py, synapse/storage/prepare_database.py, synapse/storage/schema/delta/49/event_chunks.sql, synapse/util/katriel_bodlaender.py, tests/storage/test_chunk_linearizer_table.py, tests/util/test_katriel_bodlaender.py
This commit adds the necessary tables and columns, as well as an
implementation of an online topological sorting algorithm to maintain an
absolute ordering of the room chunks.
Note: This is the start of a series of PRs. I'm landing them on a separate branch as we should probably land the full set onto develop at once, but want to make separate PRs to make review easier
=> Begin adding implementing room chunks

synapse/rulecheck/domain_rule_checker.py, tests/rulecheck/__init__.py, tests/rulecheck/test_domainrulecheck.py
Attempts to answer the question: If users are on domain foo.baz, can they invite users on domain bar.baz
=> DomainRuleChecker

Dockerfile
Signed-off-by: Paul Tötterman <paul.totterman@iki.fi>
=> Add lxml to docker image for web previews

synapse/events/utils.py, synapse/events/validator.py, synapse/groups/groups_server.py, synapse/http/matrixfederationclient.py, synapse/push/push_rule_evaluator.py, synapse/rest/client/v1/presence.py
plus a bonus b"" string I missed last time
=> Replace some more comparisons with six

synapse/handlers/deactivate_account.py, synapse/handlers/user_directory.py
This is pretty blunt but basically just does the opposite of what happens on user registration!
=> Remove users from user directory on deactivate

synapse/metrics/__init__.py
=> disable CPUMetrics if no /proc/self/stat

synapse/config/consent_config.py
Signed-off-by: Ruben Barkow <github@r.z11.de>
=> Add link to thorough instruction how to configure consent

synapse/app/homeserver.py, synapse/storage/prepare_database.py, synapse/storage/registration.py, synapse/storage/schema/delta/50/add_creation_ts_users_index.sql
phone home stats to track aggregate daily sign ups by type of user
=> daily user type phone home stats

docs/postgres.rst
Also indent all of them with 4 spaces.
=> doc/postgres.rst: fix display of the last command block

synapse/rest/client/v1/admin.py
This got completely broken in 0.30.
Fixes #3300.
=> Fix event-purge-by-ts admin API

synapse/app/appservice.py
Fixes https://github.com/matrix-org/synapse/issues/3357
=> Use the RegistryProxy for appservices too

scripts-dev/federation_client.py
This appears to have stopped working since matrix.org moved to cloudflare. The
Host header should match the name of the server, not whatever is in the SRV
record.
=> Fix commandline federation_client to send the right Host header

synapse/handlers/room.py
This error code is mentioned in the documentation at https://matrix.org/docs/api/client-server/#!/Room32creation/createRoom
Signed-off-by: Michael Wagner <mitch.wagna@gmail.com>
=> Add error code to room creation error

synapse/federation/transaction_queue.py
=> Populate synapse_federation_client_sent_pdu_destinations:count again

synapse/handlers/search.py
to help debug the OOMs we were seeing.
=> Add some logging to /search and /context queries

synapse/storage/registration.py
Use simple_delete instead of simple_delete_one as commented
=> Fix error on deleting users pending deactivation

synapse/util/caches/stream_change_cache.py
Reverts matrix-org/synapse#3452
=> Revert "Revert "Try to not use as much CPU in the StreamChangeCache""

changelog.d/3316.feature, synapse/rest/client/v2_alpha/report_event.py
as per
https://matrix.org/docs/spec/client_server/unstable.html#post-matrix-client-r0-rooms-roomid-report-eventid
=> Enforce the specified API for report_event

synapse/api/auth.py, synapse/rest/client/transactions.py, synapse/rest/client/v1/base.py, synapse/rest/client/v1/logout.py, synapse/rest/client/v1/register.py, synapse/rest/client/v2_alpha/account.py, synapse/rest/client/v2_alpha/register.py, synapse/rest/client/v2_alpha/sendtodevice.py, tests/rest/client/test_transactions.py
This makes part of the auth subsystem a bit more testable, at least as how we test now. Making it less god-objecty would be nice later, of course.
=> Make auth & transactions more testable

changelog.d/3548.bugfix, synapse/util/logcontext.py, synapse/util/metrics.py
=> Don't spew errors because we can't save metrics

synapse/config/server.py
this tripped me up when I tried the setting
=> document that the affinity package is required for the cpu_affinity setting

synapse/handlers/deactivate_account.py, synapse/handlers/profile.py, synapse/rest/client/v2_alpha/account.py, synapse/storage/profile.py, synapse/storage/schema/delta/50/profiles_deactivated_users.sql
Related: https://github.com/matrix-org/sydent/pull/78
=> Remove deactivated users from profile search

changelog.d/3572.misc, synapse/util/async.py, tests/util/test_linearizer.py
(I think this might be an important omission in #3571)
=> Test and fix support for cancellation in Linearizer

changelog.d/3590.misc, synapse/storage/events.py
... to help us figure out where 40% of CPU is going
=> Add some measure blocks to persist_events

changelog.d/3591.misc, synapse/handlers/appservice.py, synapse/handlers/initial_sync.py, synapse/storage/events.py, synapse/storage/pusher.py
Fix some random logcontext leaks.
=> Logcontext fixes

changelog.d/3592.misc, synapse/storage/events.py
During a simple test this gave about a ~20% speed up of the function.
=> Speed up _calculate_state_delta

README.rst
Added instructions for installation on OpenSUSE and SUSE Linux Enterprise Server.
=> Add instructions for install on OpenSUSE and SLES

contrib/grafana/README.md
Thank you @richvdh for the dashboard JSON. Here are some steps and pointers for anyone looking to use it.
=> Add some documentation for using the dashboard

Dockerfile, changelog.d/3543.misc, contrib/docker/README.md, contrib/docker/docker-compose.yml
Small improvement for the dockerfile to match best practices and a small improvement to make the low level docker call unnecessary.
=> Improvements for Docker usage

changelog.d/3638.misc, synapse/federation/federation_client.py
Factor out the error handling from make_membership_event, send_join, and
send_leave, so that it can be shared.
=> Factor out exception handling in federation_client

changelog.d/3712.misc, docs/admin_api/register_api.rst
Presumably this is the intention anyways. I've also updated the domain part to be something more along the lines of what people might expect.
=> Update the admin register documentation to return a real user ID

changelog.d/3732.bugfix, synapse/rest/consent/consent_resource.py
=> Fix 500 error from /consent form

changelog.d/3749.feature, synapse/api/auth.py, synapse/config/server.py, synapse/storage/monthly_active_users.py, synapse/storage/registration.py, tests/server.py, tests/storage/test_registration.py, tests/test_mau.py
Another attempt at #3744, copies a bunch from there
=> Implement trial users

changelog.d/3805.misc, synapse/federation/transaction_queue.py
As per spec: https://matrix.org/speculator/spec/HEAD/server_server/unstable.html#transactions
=> Limit the number of PDUs/EDUs per fedreation transaction

changelog.d/3826.misc, synapse/crypto/keyring.py, synapse/federation/federation_base.py, synapse/storage/keys.py
=> add some logging for the keyring queue

changelog.d/3835.bugfix, synapse/rest/client/v1/voip.py
fixes #3821
Signed-Off-By: Matthias Kesler <krombel@krombel.de>
=> fix VOIP crashes under Python 3

changelog.d/3895.bugfix, synapse/http/request_metrics.py, synapse/http/site.py
=> Fix more b'abcd' noise in metrics

changelog.d/3894.feature, synapse/app/homeserver.py
=> Add python_version phone home stat

changelog.d/3912.misc, synapse/http/site.py, tests/test_server.py, tests/unittest.py
Fixes https://github.com/matrix-org/synapse/issues/3799
=> Add a regression test for logging on failed connections

changelog.d/3963.misc, synapse/federation/federation_client.py
=> fix docstring for FederationClient.get_state_for_room

changelog.d/3966.misc, synapse/handlers/federation.py, synapse/state/v1.py
Some more logging tweaks to help with debugging incoming federation transactions
=> Logging improvements

changelog.d/3970.bugfix, scripts-dev/dump_macaroon.py, synapse/api/filtering.py, synapse/app/__init__.py, synapse/app/appservice.py, synapse/app/client_reader.py, synapse/app/event_creator.py, synapse/app/federation_reader.py, synapse/app/federation_sender.py, synapse/app/frontend_proxy.py, synapse/app/homeserver.py, synapse/app/media_repository.py, synapse/app/pusher.py, synapse/app/synchrotron.py, synapse/app/user_dir.py, synapse/config/__main__.py, synapse/handlers/e2e_keys.py, synapse/handlers/profile.py, tests/unittest.py
Signed-off-by: Schnuffle  <schnuffle@github.com>
=> Replaced all occurences of e.message with str(e)

changelog.d/4046.bugfix, synapse/handlers/room_list.py, synapse/python_dependencies.py, tests/handlers/test_roomlist.py
=> Fix roomlist since tokens on Python 3

changelog.d/4050.bugfix, synapse/rest/media/v1/preview_url_resource.py
=> Fix bug where we raised StopIteration in a generator

changelog.d/4049.misc, synctl
We should probably not be hand rolling this, but I don't want to get lost in a rabbithole of replacing with a proper library.
=> Only colourise synctl output when attached to tty

changelog.d/4076.misc, synapse/app/homeserver.py
=> Run MAU queries as background processes

README.rst, changelog.d/4072.misc
Signed-off-by: steamport <steamport@protonmail.com>
=> Add Caddy example to README

changelog.d/4091.feature, changelog.d/4100.feature, synapse/api/constants.py, synapse/handlers/register.py, synapse/handlers/room.py, synapse/rest/__init__.py, synapse/rest/client/v2_alpha/room_upgrade_rest_servlet.py, synapse/server.pyi, synapse/storage/room.py, tests/server_notices/test_resource_limits_server_notices.py
=> Remember to copy the avatar on room upgrades

changelog.d/4121.misc, synapse/handlers/message.py, synapse/handlers/room.py
I found these helpful in debugging my room upgrade tests.
=> Log some bits about event creation

contrib/docker/docker-compose.yml
Signed-off-by: Jonas Schürmann <jonasschuermann@aol.de>
=> Fix typo in docker-compose.yml

changelog.d/4133.feature, synapse/rest/consent/consent_resource.py
Introduced in https://github.com/matrix-org/synapse/pull/4004
=> Fix logic error that prevented guests from seeing the privacy policy

synapse/handlers/room_member.py
Fixes an issue where things become unhappy when the room profile for a user is missing.
**This is on a demonstration branch and not intended for live usage.**
=> Catch room profile errors and anything else that can go wrong

.editorconfig, MANIFEST.in, changelog.d/4257.misc
https://editorconfig.org
Basically just makes it so I don't have to change my editor's indentation settings for every file.
=> Add a basic .editorconfig

changelog.d/4262.feature, synapse/app/homeserver.py, synapse/config/registration.py, synapse/rest/well_known.py, tests/rest/test_well_known.py
Sometimes it's useful for synapse to generate its own .well-known file.
=> Implement .well-known handling

changelog.d/4279.bugfix, synapse/rest/media/v1/config_resource.py
=> Make /config more CORS-y

.circleci/merge_base_branch.sh, changelog.d/4291.misc
=> Disable pager for ci script

changelog.d/4307.feature, synapse/api/constants.py, synapse/state/__init__.py
Implements: https://github.com/matrix-org/matrix-doc/pull/1759 (which hasn't yet landed).
This branch is based off the current release, in case we want to do a point release with just this
=> Add v2 room version

README.rst, changelog.d/4343.misc
=> Update README to not lie about required restart

changelog.d/4356.bugfix, synapse/config/__main__.py
Fixes https://github.com/matrix-org/synapse/issues/4350
=> Fix synapse.config.__main__ on python 3

changelog.d/4373.bugfix, changelog.d/4374.bugfix, synapse/api/auth.py, synapse/config/key.py, tests/api/test_auth.py
=> Fix spontaneous logout

changelog.d/4392.bugfix, synapse/api/constants.py
=> ALL_USER_TYPES should be a tuple

changelog.d/4445.feature, synapse/handlers/user_directory.py
=> Add metric for user dir current event stream position

changelog.d/4464.misc, synapse/http/federation/matrix_federation_agent.py, tests/http/federation/test_matrix_federation_agent.py
=> MatrixFederationAgent: Look up the right SRV record

changelog.d/4505.misc, synapse/storage/_base.py
https://github.com/matrix-org/synapse/issues/4504
=> Fix typo in upserts code

changelog.d/4538.misc, synapse/handlers/sync.py
I can't figure out what's going on with #4422 and #4436; perhaps this will help.
=> Add some debug for membership syncing issues

changelog.d/4564.bugfix, synapse/config/tls.py
=> Fix default ACME config for py2

changelog.d/4615.misc, synapse/app/_base.py, synapse/config/tls.py
Log which file we're reading keys and certs from, and refactor the code a bit
in preparation for other work
=> Logging improvements around TLS certs

INSTALL.md, README.rst, changelog.d/4621.misc
Lots of updates to the README/INSTALL.md.
Fixes #4601.
=> README updates

changelog.d/4635.misc, synapse/handlers/user_directory.py, synapse/storage/user_directory.py
To prevent mixing up of functional/formatting changes in the userdir rewrite branch.
=> Run `black` on user directory code

UPGRADE.rst, changelog.d/4657.misc, synapse/config/key.py
From: Juuso "Linda" Lapinlampi <linda@lindalap.fi>
PR done with a matrix.org hat on.
=> Fix spelling mistakes

changelog.d/4666.feature, changelog.d/4670.feature, docs/workers.rst, synapse/app/client_reader.py, synapse/storage/registration.py
Turns out this was simply moving some more functions into `RegistrationWorkerStore`
=> Split /login into client_reader

synapse/push/httppusher.py
Do it in the constructor, so that it works for badge updates as well as pushes
(nb: matrix-org-hotfixes target)
=> Apply the pusher http hack in the right place

changelog.d/4721.feature, synapse/federation/federation_client.py, synapse/federation/federation_server.py
Implements https://github.com/matrix-org/matrix-doc/pull/1866
=> MSC 1866 - Use M_UNSUPPORTED_ROOM_VERSION for invite API

changelog.d/4719.misc, synapse/handlers/sync.py, synapse/storage/stream.py
=> Add more debug for membership syncing issues

synapse/federation/transport/server.py, synapse/groups/groups_server.py, synapse/handlers/room_list.py
Copy of #4736 but that merges against dinsic branch cleanly. Will be merging once #4746 passes CI.
=> [DINSIC] Prevent showing non-fed rooms in fed /publicRooms

docs/reverse_proxy.rst
So that it actually works. See https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxypass
=> Fix apache reverse proxy example

changelog.d/4757.misc, synapse/federation/federation_server.py, synapse/replication/slave/storage/presence.py
=> When presence is disabled don't send over replication

changelog.d/4769.misc, synapse/handlers/sync.py
(nb matrix-org-hotfixes target)
=> Add more debug for #4422

changelog.d/4797.misc, changelog.d/4798.misc, synapse/handlers/receipts.py, synapse/storage/receipts.py
I'm hoping to establish which rooms are having lots of RRs sent for them, and how old the events are when they are sent.
Based on #4797
=> Add some debug about processing read receipts.

changelog.d/4794.misc, synapse/federation/transport/server.py
A dollar sign is already appended to the end of each PATH, so there's
no need to add one in the PATH declaration as well.
https://github.com/matrix-org/synapse/blob/ac6a0d72b25e69bd945a97954e72df3b43e72f9b/synapse/federation/transport/server.py#L304
=> Remove unnecessary dollar signs

AUTHORS.rst, changelog.d/4772.feature, docs/admin_api/version_api.rst, synapse/rest/client/v1/admin.py, tests/rest/client/v1/test_admin.py
=>  Add 'server_version' endpoint to admin API

changelog.d/4816.misc, synapse/handlers/sync.py
=> Port #4422 debug logging from hotfixes

changelog.d/4815.misc, synapse/handlers/sync.py, synapse/storage/stream.py
These are just some docstrings that
=> Add docstrings from matrix-org-hotfixes

debian/changelog, debian/matrix-synapse-py3.config
=> Debian package: fix warning during preconfiguration.

changelog.d/4824.misc, docker/README.md
=> Document the `generate` option for the docker image.

changelog.d/4828.misc, synapse/handlers/device.py
In attempt to track down #4827
=> Add some debug logging for device list handling

.gitignore, changelog.d/4843.misc
I know https://github.com/matrix-org/synapse/pull/4688 removed a lot from the `.gitignore` but now I have like 500 untracked files to look at. Surely these things should be added back.
=> Add some stuff back to the .gitignore

changelog.d/4881.misc, docs/reverse_proxy.rst
=> Repoint docs for federation

changelog.d/4887.feature, synapse/storage/schema/delta/53/user_dir_populate.sql
=> Fix user directory background update

changelog.d/4969.misc, synapse/api/constants.py, synapse/api/room_versions.py, synapse/event_auth.py, synapse/events/__init__.py, synapse/events/builder.py, synapse/events/validator.py, synapse/federation/federation_base.py, synapse/federation/federation_client.py, synapse/federation/federation_server.py, synapse/federation/transport/server.py, synapse/handlers/federation.py, synapse/handlers/message.py, synapse/handlers/room.py, synapse/rest/client/v2_alpha/capabilities.py, synapse/rest/client/v2_alpha/room_upgrade_rest_servlet.py, synapse/state/__init__.py, synapse/state/v1.py, synapse/storage/events_worker.py, tests/rest/client/v2_alpha/test_capabilities.py, tests/state/test_v2.py, tests/storage/test_redaction.py, tests/storage/test_roommember.py, tests/storage/test_state.py, tests/test_event_auth.py, tests/test_state.py, tests/test_visibility.py, tests/utils.py
Collect all the things that make room-versions different to one another into
one place, so that it's easier to define new room versions.
Sorry about the size of this PR :/
=> Collect room-version variations into one place

changelog.d/4974.misc, synapse/config/key.py
As requested by @andrewshadura
=> Add config.signing_key_path.

docs/sample_config.yaml, synapse/config/registration.py, synapse/rest/client/v2_alpha/register.py
=> Add config option to use email as display name for new users

changelog.d/4985.misc, tests/crypto/test_keyring.py
This is a bit fiddly due to the keyring doing weird things with logcontexts.
=> Rewrite KeyringTestCase as a HomeServerTestCase

changelog.d/5003.bugfix, scripts/synapse_port_db
Make synapse_port_db --curses work with Python 3.
Signed-off-by: Anders Jensen-Waud <anders@jensenwaud.com>
=> Fix issue #4596

synapse/util/threepids.py
=> Prevent exception when hs or shadow_hs missing

changelog.d/4972.misc, synapse/rest/well_known.py
=> Remove log error for .well-known/matrix/client

changelog.d/5184.misc, synapse/storage/appservice.py, synapse/storage/event_federation.py, synapse/storage/events_worker.py, synapse/storage/search.py, synapse/storage/stream.py, tests/storage/test_appservice.py
This is in preparation for reaction work which requires it.
=> Expose DataStore._get_events as get_events_as_list

synapse/storage/events.py, synapse/storage/relations.py, tests/rest/client/v2_alpha/test_relations.py
Based on #5195 (and a bit of #5203 where we change the way we test stuff)
=> Correctly update aggregation counts after redaction

changelog.d/5210.feature, synapse/api/room_versions.py, synapse/events/__init__.py
=> Add a test room version which updates event ID format

changelog.d/5218.bugfix, synapse/python_dependencies.py, tox.ini
Fixes https://github.com/matrix-org/synapse/issues/5199
=> Pin eliot to <1.8 on python 3.5.2

changelog.d/5249.feature, docs/sample_config.yaml, synapse/config/server.py
As per https://github.com/matrix-org/synapse/pull/5223#discussion_r286380341
I went through making everything consistent a while ago. Please can we try to keep it so?
=> Add missing blank line in config

changelog.d/5257.bugfix, synapse/http/servlet.py
=> Fix error code for invalid parameter

changelog.d/5260.feature, synapse/storage/stats.py
Fixes https://github.com/matrix-org/synapse/issues/5238
=> Fix logging for room stats background update

changelog.d/5283.misc, docs/CAPTCHA_SETUP.rst
=> Specify the type of reCAPTCHA key to use (#5013)

CHANGES.md
otherwise this is going to confuse me forever
=> fix changelog for 0.99.5.1

changelog.d/5458.feature, synapse/metrics/__init__.py, tests/storage/test_event_metrics.py
Actually uses the rendering-to-text to validate that it works.
Fixes #5452
=> Fix Prometheus erroring after the extremities monitoring

changelog.d/5394.bugfix, synapse/handlers/account_validity.py, synapse/handlers/deactivate_account.py, synapse/storage/_base.py, synapse/storage/registration.py, tests/rest/client/v2_alpha/test_register.py
Port of https://github.com/matrix-org/synapse/pull/5462 to the dinsic branch
=> Port "Don't send renewal emails to deactivated users" to dinsic

changelog.d/5465.bugfix, changelog.d/5465.misc, synapse/storage/registration.py
Port of #5465 to the dinsic branch
=> Port "Fix background job for deactivated flag" to dinsic

changelog.d/5474.feature, synapse/events/third_party_rules.py, synapse/handlers/room.py
Clone of https://github.com/matrix-org/synapse/pull/5474 for develop
=> Add third party rules hook into create room

changelog.d/5477.feature, synapse/events/third_party_rules.py, synapse/handlers/room_member.py
=> Port "Add third party rules hook for 3PID invites" to dinsic

changelog.d/5493.misc, synapse/storage/registration.py
Port of #5493 to the `dinsic` branch
=> Port "Fix typo in deactivation background job" to dinsic

changelog.d/5521.misc, synapse/handlers/acme.py, synapse/handlers/acme_issuing_service.py
This makes some of the conditional-import hoop-jumping easier.
=> Factor acme bits out to a separate file

changelog.d/5570.misc, contrib/purge_api/README.md
This points the reverse links in the Purge History API README at the intended location.
Signed-off-by: Jon Richter <jon@allmende.io>
=> Update purge_api README

changelog.d/5561.feature, docker/start.py
A bunch of non-functional refactors to clean up the start script before we do any other work here.
=> Refactor the docker/start.py script

changelog.d/5567.feature, docker/README.md, docker/conf/homeserver.yaml, docker/start.py
... to help people escape env var hell
Based on #5566, #5562.
=> Docker image: Add a migrate_config mode

changelog.d/5585.misc, synapse/rest/consent/consent_resource.py
=> fix async/await consentresource

changelog.d/5628.misc, synapse/handlers/register.py, tests/handlers/test_register.py
This is only used in tests, so...
=> Move get_or_create_user to test code

changelog.d/5643.misc, synapse/handlers/register.py
It was pretty unclear what was going on, so I've added a couple of log lines.
=> Better logging for auto-join.

.buildkite/pipeline.yml, changelog.d/5717.misc
put them on mediums so it's moar fast
=> Speed up the PostgreSQL unit tests

changelog.d/5725.bugfix, demo/start.sh
The start script uses an option used by removed by  #5678
=> Demo uses deprecated cli option

MANIFEST.in, changelog.d/5733.misc
I don't think its useful, and I don't even know where it would end up.
=> Don't package sytest-blacklist file.

changelog.d/5793.misc, synapse/storage/schema/delta/56/current_state_events_membership.sql
=> Don't recreate current_state_events.membership column

changelog.d/5801.misc, changelog.d/5805.misc, synapse/events/validator.py
=> Validate well known state events are state events.

changelog.d/5780.misc, synapse/util/__init__.py
Port #5780 to the `dinsic` branch
=> Add ability to pass arguments to looping calls

changelog.d/5807.feature, docs/sample_config.yaml, synapse/config/registration.py, synapse/handlers/account_validity.py, synapse/res/templates/account_renewed.html, synapse/res/templates/invalid_token.html, synapse/rest/client/v2_alpha/account_validity.py, tests/rest/client/v2_alpha/test_register.py
Port https://github.com/matrix-org/synapse/pull/5807 to the `dinsic` branch
=> Account validity: allow defining HTML templates to serve the user on account renewal attempt

changelog.d/5906.feature, synapse/handlers/profile.py
In response to https://github.com/matrix-org/synapse/issues/5870
=> Increase profile display name limit

docker/README.md
=> Typographical corrections in docker/README

synapse/storage/stats.py
This adds the stats regenerator, which is crucial for existing installations.
=> Separated Statistics [7/7ish]

INSTALL.md, changelog.d/5953.misc
=> Update INSTALL.md to say that Python 2 is no longer supported

changelog.d/5967.bugfix, synapse/rest/admin/media.py
Fixes https://github.com/matrix-org/synapse/issues/5737
Done with my community hat:
```
Signed-off-by: Travis Ralston <travis@t2bot.io>
```
=> Ensure an auth instance is available to ListMediaInRoom

changelog.d/5975.misc, synapse/event_auth.py
=> Cleanup event auth type initialisation

changelog.d/5998.bugfix, synapse/handlers/stats.py, synapse/storage/stats.py
=> Correctly handle non-bool m.federate flag

docs/admin_api/README.rst
The first two items don't seem relevant for a simple documentation change.
Signed-off-by: axel simon <github@axelsimon.net>
=> add explanations on how to actually include an access_token

changelog.d/5996.bugfix, synapse/config/tls.py, synapse/crypto/context_factory.py, synapse/http/federation/matrix_federation_agent.py, tests/config/test_tls.py
should fix https://github.com/matrix-org/synapse/issues/5939
=> Fix well-known lookups with the federation certificate whitelist

.github/ISSUE_TEMPLATE/BUG_REPORT.md
=> Update the issue template for new way of getting server version

MANIFEST.in, changelog.d/6191.misc
... after it got borked by #6081
=> Fix python packaging

changelog.d/6193.misc, synapse/handlers/e2e_keys.py, synapse/storage/end_to_end_keys.py, tests/storage/test_end_to_end_keys.py
as a result of: https://github.com/matrix-org/synapse/pull/5726#discussion_r322774116
=> make storage layer in charge of interpreting the device key data

contrib/docker/README.md, contrib/docker/docker-compose.yml
=> Update docker-compose.yml for a static config file, and update traefik examples

changelog.d/6217.misc, synapse/api/auth.py, synapse/handlers/federation.py
This method was somewhat redundant, and confusing.
=> Remove Auth.check method

changelog.d/6250.misc, synapse/storage/data_stores/main/stats.py
=> Make user stats less verbose

docker/README.md
I guess a changelog entry is not required? If it is, please let me know and I will add it.
=> Fix broken url in docker/README.md (rst -> md)

changelog.d/6269.misc, synapse/federation/federation_server.py
Fix small but incorrect comment.
=> Fix small typo in comment

changelog.d/6257.doc, docs/CAPTCHA_SETUP.md
=> Modify doc to update Google ReCaptcha terms

changelog.d/6305.misc, docs/tcp_replication.md, synapse/replication/slave/storage/_base.py, synapse/replication/tcp/client.py, synapse/replication/tcp/protocol.py
since I found myself wondering how it works
=> document the REPLICATE command a bit better

changelog.d/6318.misc, synapse/app/homeserver.py, synapse/python_dependencies.py, synapse/server.py, tests/test_phone_home.py
This replaces it with mostly-equiv functionality using `resource` (which is how contexts do it).
=> Remove the psutil dependency

changelog.d/6336.misc, synapse/app/homeserver.py
We removed some arguments from the functions.
Broke in #6318.
=> Fix phone home stats

changelog.d/6361.misc, tests/rest/admin/test_admin.py
This test was broken in https://github.com/matrix-org/synapse/pull/6295, comment out until a fix is ready so `develop` branch's CI isn't broken for everyone.
=> Blacklist PurgeRoomTestCase

changelog.d/6389.bugfix, docker/start.py
Fixes: https://github.com/matrix-org/synapse/issues/6303
Context: https://github.com/matrix-org/synapse/issues/6303#issuecomment-555974226
=> Docker: Change permissions for data dir before attempting to write to it

changelog.d/6388.doc, docs/user_directory.md
=> Fix link to user_dir_populate.sql in the user directory docs

changelog.d/6406.bugfix, synapse/handlers/register.py
=> Fix issue #6406 parameter mismatch

changelog.d/6480.misc, synapse/handlers/federation.py
replace the event_info dict with an attrs thing
=> Stronger typing in the federation handler

changelog.d/6541.doc, docs/admin_api/shutdown_room.md
Fixes #4784
Document the shutdown room admin API.
=> Document Shutdown Room admin API

changelog.d/6558.misc, synapse/push/pusher.py, synapse/push/pusherpool.py, synapse/rest/client/v1/pusher.py, synapse/storage/data_stores/main/pusher.py, tests/push/test_email.py, tests/push/test_http.py
There are several separate but related commits here; suggest reviewing them independently. It's all about trying to stop the pusher from logging a load of exceptions at startup.
=> Clean up startup for the pusher

changelog.d/6576.bugfix, synapse/handlers/federation.py
=> Fix exceptions when attempting to backfill

changelog.d/6645.bugfix, synapse/app/synchrotron.py, synapse/storage/data_stores/main/events_worker.py
Fixes https://github.com/matrix-org/synapse/issues/6428, I hope
=> Fix exceptions in the synchrotron worker log when events are rejected.

CHANGES.md, UPGRADE.rst
Its polite to let people know that their synapse might implode on upgrade.
=> Add note about log_file no longer be accepted

changelog.d/6682.bugfix, synapse/http/site.py
=> Fix exceptions on requests for non-ascii urls

changelog.d/6698.doc, docs/workers.md
=> Document more supported endpoints for workers

changelog.d/6711.bugfix, synapse/storage/purge_events.py, tests/rest/admin/test_admin.py
=> Fix purge_room admin API

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, changelog.d/6663.doc
To visualize what it will look like, edit this comment.
=> Add tips for the changelog to the pull request template

changelog.d/6716.misc, synapse/storage/data_stores/main/events.py, synapse/storage/persist_events.py
This will allow us to add more fields later without making the type insane.
(I also converted some stuff to async/await, and moved the typing up into the function definitions)
=> Add a DeltaState to track changes to be made to current state

changelog.d/6770.doc, docs/admin_api/rooms.md
This feature will go out in v1.9.0.
`release-v1.9.0` will need to be merged to develop once this is merged.
=> Update admin room docs with correct endpoints

changelog.d/6787.feature, changelog.d/6787.misc, synapse/api/room_versions.py, synapse/event_auth.py
cf [MSC2260](https://github.com/matrix-org/matrix-doc/pull/2260)
=> Implement updated auth rules from MSC2260

changelog.d/6821.misc, synapse/events/__init__.py, synapse/handlers/sync.py, tests/storage/test_redaction.py, tox.ini
Probably worth going through commit by commit
=> Add typing to SyncHandler

changelog.d/6849.bugfix, synapse/config/tls.py
Fixes #6817 
Signed-off-by: Tim Fierens <timfierens@fastmail.com>
=> allow empty federation_certificate_verification_whitelist

changelog.d/6856.misc, changelog.d/6857.misc, synapse/events/__init__.py, synapse/federation/federation_base.py, synapse/federation/federation_client.py, synapse/federation/federation_server.py, tests/handlers/test_federation.py
=> remove unused room_version_to_event_format

changelog.d/6877.removal, synapse/rest/client/versions.py
=> Remove m.lazy_load_members from unstable features since it is in CS r0.5.0

changelog.d/6905.doc, docs/ACME.md
I wasn't sure what to do with the part regarding the initial setup, I decided to keep it in case we can support ACMEv2 in a timely manner.
=> Update ACME.md to mention ACME v1 deprecation

changelog.d/6947.misc, synapse/storage/data_stores/main/event_federation.py
Large queries seem to cause postgres to take ages.
Broke in #6937
=> Limit size of get_auth_chain_ids query

changelog.d/6945.bugfix, synapse/handlers/pagination.py
Observed here: https://github.com/matrix-org/synapse/issues/6683#issuecomment-578240957
=> Fix log in message retention purge jobs

changelog.d/7063.misc, synapse/handlers/auth.py, tox.ini
While working on #5667 I started adding some docstrings / type information for myself. Figured it was worth cleaning up and merging.
=> Add type annotations and comments to auth handler

INSTALL.md, changelog.d/7107.doc
Signed-off-by: Kartikaya Gupta <kats@trevize.staktrace.com>
=> Update pre-built package name for FreeBSD

INSTALL.md, changelog.d/7141.doc
* complete markdownifying
* Home Server -> homeserver
* python2 -> python3
* Remove old/unnecessary troubleshooting guidelines
=> Various cleanups to INSTALL.md

changelog.d/7137.removal, docs/sample_config.yaml, synapse/config/captcha.py
=> Remove unused captcha_bypass_secret option

changelog.d/7192.misc, synapse/storage/data_stores/main/devices.py, synapse/storage/data_stores/main/schema/delta/57/remove_sent_outbound_pokes.sql
=> Remove sent outbound device list pokes from the database

changelog.d/7219.misc, synapse/federation/federation_server.py, tox.ini
This was another branch I had laying around. I finished it up to finish adding the typing information.
Anyway, it adds typing information, that's pretty much it.
=> Add typing information to federation_server.

.buildkite/worker-blacklist, changelog.d/7228.misc
Reverts matrix-org/synapse#7228
Needed to wait for https://github.com/matrix-org/sytest/pull/848 to be approved first.
=> Revert "Unblacklist /upgrade creates a new room"

changelog.d/1.bugfix, changelog.d/7243.misc, tests/rest/client/v1/test_events.py
Signed-off-by: Isaiah Singletary <zaysingletary@gmail.com>
=> Fix the parameters of a test fixture

changelog.d/7326.misc, synapse/replication/tcp/commands.py, tests/replication/tcp/test_commands.py
I messed this up last time I tried (#7239 / e13c6c7).
=> Another go at fixing one-word replication commands

changelog.d/7398.docker, docker/Dockerfile
Signed-off-by: Cédric Laubacher <cedric@laubacher.io>
=> Update docker runtime image to Alpine v3.11

changelog.d/7477.doc, synapse/config/server_notices_config.py
=> Fix copypasted comment

changelog.d/7513.misc, synapse/handlers/room_member.py, synapse/handlers/room_member_worker.py, tox.ini
The promised follow-up to #7507 with type hints and updated comments.
Note that some of the return types are...less than clear here, so checking them over would be helpful!
=> Add type hints to room member handlers

changelog.d/7519.misc, scripts-dev/convert_server_keys.py, synapse/http/matrixfederationclient.py, synapse/logging/utils.py, synapse/push/httppusher.py, synapse/replication/slave/storage/_base.py, synapse/replication/slave/storage/presence.py, synapse/rest/media/v1/_base.py, synapse/storage/_base.py, synapse/storage/data_stores/main/keys.py, synapse/storage/data_stores/main/roommember.py, synapse/storage/data_stores/main/state.py, synapse/storage/data_stores/main/transactions.py, synapse/storage/database.py, synapse/util/caches/__init__.py, synapse/util/stringutils.py
This stuff has been annoying me for a while.
Each commit should stand alone.
(There's plenty more that can be removed; this was just what I found in 10 minutes.)
=> Kill off some old python 2 code

changelog.d/7515.misc, synapse/app/generic_worker.py, synapse/replication/http/__init__.py
This allows workers to talk to each other over HTTP replication.
=> Allow ReplicationRestResource to be added to workers

changelog.d/7533.doc, docs/turn-howto.md
=> Minor clarifications to the TURN docs

changelog.d/7550.misc, docs/sample_config.yaml, synapse/config/captcha.py, synapse/config/emailconfig.py, synapse/config/key.py, synapse/config/metrics.py, synapse/config/registration.py, synapse/config/server.py
=> Fix some DETECTED VIOLATIONS in the config file

changelog.d/7553.misc, synapse/http/site.py, tox.ini
=> mypy for synapse.http.site

changelog.d/7536.misc, synapse/metrics/__init__.py
PyPy's gc.get_stats() returns an object containing detailed allocator statistics
which could be beneficial to collect as metrics.
Signed-off-by: Ivan Shapovalov <intelfx@intelfx.name>
=> synapse.metrics: implement detailed memory usage reporting on PyPy

changelog.d/7560.misc, synapse/http/server.py, tests/test_server.py
=> Fix missing CORS headers on OPTION responses

changelog.d/7546.misc, synapse/handlers/message.py, synapse/server_notices/resource_limits_server_notices.py, synapse/storage/data_stores/main/monthly_active_users.py, tests/server_notices/test_resource_limits_server_notices.py, tests/storage/test_client_ips.py, tests/storage/test_monthly_active_users.py, tests/test_mau.py
These are surprisingly expensive, and we only really need to do them at startup.
=> Optimise some references to hs.config

changelog.d/7563.misc, synapse/app/generic_worker.py
=> Fix incorrect exception handling in KeyUploadServlet.on_POST

changelog.d/7591.misc, contrib/systemd/matrix-synapse.service
Signed-off-by: David Rio Deiros <drio@drio.org>
=> Adds postgresql dependency to systemd template

changelog.d/7600.misc, synapse/groups/groups_server.py, synapse/handlers/groups_local.py
This converts the groups local and groups server handles to async/await. It got a bit bigger than I wanted, but they call into each other a lot so...
I didn't come across anything tricky while doing it.
=> Convert groups local and server to async/await

changelog.d/7623.misc, scripts-dev/check-newsfragment
It's too easy to typo the PR #, and then it's hard to spot it. Let's add a check to the CI.
=> Check the changelog number in check-newsfragment

changelog.d/7659.doc, docs/openid.md
* [?] Code style is correct (run the [linters](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#code-style))
=> Added basic  keycloak openid instructions

changelog.d/7746.bugfix, synapse/state/v2.py
=> Add another yield point to state res v2

INSTALL.md
I'm tempted to remove this section entirely, but it's helpful for admins who are trying to figure out why their Synapse is crashing on start with ACME errors.
Signed-off-by: Luke W Faraone <luke@faraone.cc>
=> Clearly state built-in ACME no longer works

changelog.d/7870.misc, synapse/handlers/_base.py, synapse/server.py
I found these made pycharm have more of a clue as to what was going on in other places.
=> Add some tiny type annotations

changelog.d/7877.misc, synapse/logging/context.py
This had some dead code and some just plain wrong docstrings.
=> Clean up PreserveLoggingContext

changelog.d/7990.doc, docs/workers.md
Some wording tweaks to the workers docs.
=> Update workers docs

changelog.d/8069.misc, synapse/storage/databases/main/devices.py, tests/handlers/test_typing.py, tests/storage/test_devices.py, tests/storage/test_end_to_end_keys.py
This converts the devices database to async/await. It was large enough that it seemed worthy of it's own PR.
I also got a bit carried away with adding type hints, but since it was all this file I figured why not go for it?
=> Convert devices database to async/await.

changelog.d/8202.misc, synapse/handlers/pagination.py, synapse/util/async_helpers.py, tests/util/test_rwlock.py
I converted this thinking it might be used in many places...then realized it is only used in the pagination code.
Anyway, it is a pretty straightforward change. I threw in some type hints too.
=> Convert ReadWriteLock to async/await.

changelog.d/8189.doc, docs/admin_api/user_admin_api.rst
Fixes https://github.com/matrix-org/synapse/issues/8185
=> Explain better what GDPR-erased means

changelog.d/8337.misc, contrib/cmdclient/console.py, contrib/cmdclient/http.py, contrib/graph/graph.py, contrib/graph/graph3.py, contrib/jitsimeetbridge/jitsimeetbridge.py, contrib/scripts/kick_users.py, scripts-dev/definitions.py, scripts-dev/dump_macaroon.py, scripts-dev/federation_client.py, scripts-dev/hash_history.py, scripts/move_remote_media_to_new_store.py, scripts/register_new_matrix_user, synapse/_scripts/register_new_matrix_user.py, synapse/app/homeserver.py, synapse/config/emailconfig.py, synapse/config/stats.py, synapse/storage/databases/main/events_worker.py, synapse/util/patch_inline_callbacks.py
> and one python-2 related assertion/assignment (raw_input/input)
*(Obligatory [Reference](https://youtu.be/yk7IDVzLiQo?t=5))*
Resolves #8333
=> Remove __future__ imports

changelog.d/8343.feature, synapse/rest/client/versions.py
=> Add flags about whether new rooms are encrypted by default.

changelog.d/8435.bugfix, synapse/rest/media/v1/media_repository.py
=> fix a logging error in thumbnailer

.gitignore, changelog.d/8566.misc
> This is so files automatically generated by `virtualenv` and pycharm will be ignored
=> Add .venv* to .gitignore

changelog.d/8571.misc, synmark/__init__.py
This seems to have been broken since #6513.
=> Fix synmark

changelog.d/8689.feature, tests/rest/admin/test_user.py
Broke by a combination of #8610 and #8616
=> Fix unit tests

changelog.d/8911.feature, tests/handlers/test_oidc.py
I've got some surgery of the SSO flow on the way which will break these tests, so I'm changing their approach beforehand so that we can prove that the changes don't break anything.
It's all just changes to test code but I've tried to organise it into standalone commits.
=> Preparatory refactoring of the OidcHandlerTestCase

changelog.d/8977.bugfix, synapse/handlers/groups_local.py, synapse/rest/client/v2_alpha/groups.py
I got annoyed at looking at these in Sentry all the time so I wanted to fix them once and for all, e.g. https://sentry.matrix.org/sentry/synapse-matrixorg/issues/127583/?query=is%3Aunresolved
=> Check if group IDs are valid before using them.

README.rst, changelog.d/9002.doc
Add link to Synapse developer room to the relevant section
Context: https://github.com/matrix-org/synapse/issues/8996#issuecomment-752722425
=> Add link to Synapse developer room to the relevant section

changelog.d/9035.doc, docs/systemd-with-workers/README.md
Signed-off-by: Emelie <em@nao.sh>
=> Fix typo in docs/systemd-with-workers/README.md

INSTALL.md, changelog.d/9040.doc
=> doc: fix small typo error

changelog.d/9063.misc, tests/rest/admin/test_admin.py, tests/rest/admin/test_event_reports.py, tests/rest/admin/test_media.py, tests/rest/admin/test_room.py, tests/rest/admin/test_statistics.py, tests/rest/admin/test_user.py
Removes unnecessary declarations in the tests for the admin API
=> Removes unnecessary declarations in the tests for the admin API

changelog.d/9135.doc, docs/turn-howto.md
=> docs: Add link to Matrix VoIP tester for turn-howto

changelog.d/9195.bugfix, synapse/storage/databases/main/schema/delta/59/07shard_account_data_fix.sql, synapse/storage/util/sequence.py
Added in https://github.com/matrix-org/synapse/pull/9193
Also fixes a typo in formatting.
=> Add schema update to fix existing DBs affected by #9193

changelog.d/9286.feature, docs/sample_config.yaml, synapse/config/sso.py, synapse/handlers/auth.py, synapse/res/templates/sso_auth_confirm.html, synapse/res/templates/sso_auth_success.html
=> Improve styling and wording of SSO UIA templates

changelog.d/9134.doc, docs/openid.md
Signed-off-by: Oliver Hanikel <Oliver.Hanikel@stud.h-da.de>
=> add OpenID example config for Gitea

changelog.d/9308.doc, docs/turn-howto.md
Elsewhere in the repo this service is already called
matrix-synapse.service.
=> docs: Correct matrix-synapse.service in TURN howto

INSTALL.md, changelog.d/9322.doc
=> Update installation instructions on Fedora

changelog.d/9539.feature, synapse/app/generic_worker.py
Should fix some remaining warnings
=> Set X-Forwarded-Proto header when frontend-proxy proxies a request

changelog.d/9568.misc, mypy.ini
Per matrix-org/python-unpaddedbase64#7.
=> Do not have mypy ignore unpaddedbase64.

changelog.d/9591.misc, synapse/api/auth.py, synapse/federation/federation_server.py, synapse/handlers/oidc_handler.py, synapse/http/client.py, synapse/logging/_remote.py, synapse/push/emailpusher.py, synapse/replication/tcp/handler.py, synapse/replication/tcp/protocol.py, synapse/replication/tcp/redis.py, synapse/rest/admin/_base.py, synapse/rest/admin/media.py, synapse/rest/client/v2_alpha/groups.py, synapse/rest/media/v1/config_resource.py, synapse/rest/media/v1/preview_url_resource.py, synapse/rest/media/v1/upload_resource.py, synapse/server.py, tests/replication/test_federation_ack.py
This has a handful of unrelated commits (which should be standalone).
This resolves another ~14 errors related to #9513.
=> Fix additional type hints from Twisted 21.2.0.

changelog.d/9604.doc, changelog.d/9604.misc, docs/sample_config.yaml, synapse/config/stats.py
... and complain if people try to turn it off.
Hopefully the commits here are self-explanatory.
=> Clean up config settings for stats

changelog.d/9691.feature, docs/admin_api/user_admin_api.rst, synapse/rest/admin/users.py, synapse/storage/databases/main/__init__.py, synapse/storage/databases/main/stats.py, tests/rest/admin/test_user.py
Add order_by to the admin API `GET /_synapse/admin/v2/users`.
=> Add `order_by` to list user admin API

changelog.d/9885.misc, synapse/handlers/presence.py
=> Add type hints to presence handler

changelog.d/9909.feature, scripts-dev/build_debian_packages
All debs build locally without error
Fixes #9732 
=> Build Debian packages for Ubuntu 21.04 Hirsute

changelog.d/9937.bugfix, synapse/python_dependencies.py
=> Pin attrs to <21.1.0

changelog.d/9980.doc, docs/sso_mapping_providers.md
Tries to clarify some info based on a conversation with @anoadragon453 this morning.
=> Update SSO mapping providers documentation about unique IDs

changelog.d/9988.doc, docs/postgres.md
Whoops, forgot to update this instance.
=> Update minimum supported version in postgres.md

changelog.d/10001.misc, contrib/grafana/synapse.json
This is just a dumb import from our internal grafana.
=> Update the contrib grafana dashboard

changelog.d/10084.feature, docs/workers.md, synapse/app/generic_worker.py, synapse/rest/client/v1/room.py
Tests at https://github.com/matrix-org/sytest/pull/1053
=> Move some more endpoints off master

README.rst, changelog.d/10258.doc
=> irc.libera.chat has replaced freenode

changelog.d/10286.bugfix, synapse/storage/schema/main/delta/60/02change_stream_ordering_columns.sql.postgres
=> Change more stream_ordering columns to BIGINT

changelog.d/10284.feature, synapse/storage/databases/main/event_federation.py
These will do a table scan, but I'm hoping that they'll remain really small.
=> Add some metrics to staging area

changelog.d/10345.misc, changelog.d/10357.misc, sytest-blacklist
Fixed in https://github.com/matrix-org/sytest/pull/1061 and https://github.com/matrix-org/sytest/pull/1067
c.f. #10275
=> Unblacklist fixed tests

changelog.d/10370.doc, contrib/docker/docker-compose.yml, contrib/grafana/README.md, contrib/prometheus/README.md, contrib/purge_api/README.md, contrib/purge_api/purge_history.sh, contrib/systemd-with-workers/README.md, docs/systemd-with-workers/README.md, docs/usage/configuration/logging_sample_config.md
=> Fix some links in `docs` and `contrib`

changelog.d/10396.doc, docs/setup/installation.md
=> Instructions on installing RC debs

changelog.d/10457.bugfix, synapse/rest/client/v2_alpha/sync.py
As per comment
Fixes https://github.com/matrix-org/synapse/issues/10456
See also https://github.com/vector-im/element-android/issues/3725
=> Always send device_one_time_keys_count

debian/build_virtualenv, debian/changelog, debian/matrix-synapse-py3.triggers
Replace the outdated list of dpkg triggers with an autogenerated one.
=> Fix debian package triggers

changelog.d/10543.doc, docs/upgrade.md
=> fix broken links in `upgrade.md`

changelog.d/10588.removal, scripts-dev/build_debian_packages
=> Stop building a debian package for Groovy Gorilla

changelog.d/10570.feature, contrib/grafana/synapse.json
With shiny new panels and stuff
=> Update the Synapse Grafana dashboard

changelog.d/10642.misc, synapse/storage/roommember.py
Per https://github.com/matrix-org/synapse/pull/10629#discussion_r691260369
=> Fix weakref_slot parameter for room member storage attrs.

changelog.d/10735.doc, docs/admin_api/rooms.md
@erikjohnston Is this what you mentioned earlier today?
=> Doc: Clarifying undoing room shutdowns

changelog.d/10746.misc, synapse/handlers/federation_event.py
=> Underscore-prefix private fields in `FederationEventHandler`

changelog.d/10925.misc, scripts-dev/release.py
=> Sign the git tag in release script

changelog.d/10958.misc, synapse/api/filtering.py, synapse/storage/databases/main/filtering.py
I was trying to figure out how these worked so I added type hints.
=> Add type hints to filtering classes.

changelog.d/10987.misc, synapse/handlers/federation_event.py
Add some more comments about wtf is going on here.
=> `_update_auth_events_and_context_for_auth`: add some comments

.github/PULL_REQUEST_TEMPLATE.md, changelog.d/11225.misc
=> Update outdated links in `PULL_REQUEST_TEMPLATE.md`

changelog.d/11199.bugfix, synapse/storage/databases/main/deviceinbox.py, synapse/storage/schema/main/delta/65/03remove_hidden_devices_from_device_inbox.sql, tests/storage/databases/main/test_deviceinbox.py
Follow up:
- #10969
- **Requires** #10097
Related:
- #9346
- #9348
- #5888
- #3599
=> Delete messages for hidden devices from `device_inbox`

changelog.d/11270.misc, sytest-blacklist
See https://github.com/matrix-org/sytest/pull/1111
=> Blacklist new sytest validation test

changelog.d/11273.misc, debian/changelog
=> Address review feedback from #11269

changelog.d/11359.misc, tests/storage/test_rollback_worker.py
This seems to be from a conflict between #11282 and #11346.
=> Fix incorrect return value in tests.

changelog.d/11370.misc, synapse/handlers/auth.py, synapse/handlers/register.py
Follow up to #11369 because of course I missed one
=> Rename `get_refresh_token_for_user_id` to `create_refresh_token_for_user_id`

changelog.d/11460.misc, tests/federation/transport/test_client.py
=> Add missing copyright header.

changelog.d/11479.feature, tests/storage/test_background_update.py
=> Add a license header and comment.

changelog.d/11493.misc, tests/storage/test_main.py
Hopefully pretty self-contained! :)
=> Clean up `tests.storage.test_main` to remove use of legacy code.

changelog.d/11492.misc, tests/storage/test_appservice.py
=> Clean up tests.storage.test_appservice

changelog.d/11551.misc, mypy.ini, synapse/storage/databases/main/__init__.py, synapse/storage/databases/main/end_to_end_keys.py
=> Add type hints to `synapse/storage/databases/main/end_to_end_keys.py`

changelog.d/11625.misc, synapse/python_dependencies.py
... to work around breakage on buster (https://github.com/Marco-Sulla/python-frozendict/issues/41)
=> Pin to frozendict<2.1.2

changelog.d/11267.doc, docs/setup/installation.md
=> Correct Synapse install command for FreeBSD.

changelog.d/11725.doc, docs/postgres.md
=> Fix documentation of supported PostgreSQL version

changelog.d/11735.doc, demo/README
=> Fix typo in demo docs: differnt

.github/PULL_REQUEST_TEMPLATE.md, changelog.d/11744.misc
I keep forgetting this and I think it's occasionally useful for release blog posts.
=> Invite PR submitters to credit themselves

changelog.d/11820.doc, changelog.d/11820.misc, docs/setup/installation.md
As the title states. One of the tasks in #11780.
=> Update installation docs to indicate that we support Python 3.10

changelog.d/11838.misc, docs/sample_config.yaml, synapse/config/modules.py
=> Fix some indentation inconsistencies in the sample config (modules)

changelog.d/11868.feature, synapse/module_api/__init__.py
Fixes https://github.com/matrix-org/synapse/issues/10701
=> Allow modules to retrieve server and worker names

changelog.d/12022.feature, synapse/rest/client/versions.py
After inspection of the v1.2 changelog, all the requirements except https://github.com/matrix-org/synapse/pull/12021 have been met for Synapse's area of impact. 
**Blocked behind https://github.com/matrix-org/synapse/pull/12021**
Probably should also be blocked behind https://github.com/matrix-org/synapse/pull/12020 for sanity.
- Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your …
=> Advertise Matrix 1.2 in `/_matrix/client/versions`

changelog.d/12084.misc, mypy.ini, tests/rest/client/test_profile.py, tests/rest/client/test_push_rule_attrs.py, tests/rest/client/test_redactions.py, tests/rest/client/test_relations.py, tests/rest/client/test_retention.py, tests/rest/client/test_sendtodevice.py, tests/rest/client/test_shadow_banned.py, tests/rest/client/test_shared_rooms.py, tests/rest/client/test_upgrade_room.py, tests/rest/client/utils.py
=> Add type hints to `tests/rest/client`

.github/workflows/tests.yml, changelog.d/12153.misc, tox.ini
Call `config-lint.sh` outside of tox, in the other step that lints the config.
Another minor thing which I can pull out of my poetry nonsense.
=> Detox, part 3 of N

changelog.d/12231.doc, synapse/config/spam_checker.py
=> Fix dead link in spam checker warning

changelog.d/12248.misc, mypy.ini, synapse/storage/databases/main/group_server.py, synapse/storage/databases/main/monthly_active_users.py
=> Add some type hints to datastore

.ci/scripts/test_synapse_port_db.sh, .github/workflows/tests.yml, changelog.d/12412.misc
=> CI: Get the portdb job to run under poetry

changelog.d/12440.misc, changelog.d/12441.misc, poetry.lock
May be necessary in lieu of https://github.com/matrix-org/synapse/pull/12439?
=> Bump twisted version to the latest in lockfile

README.rst, changelog.d/12495.doc
=> Fix a link in `README.rst`

changelog.d/12784.bugfix, synapse/storage/schema/main/delta/70/01clean_table_purged_rooms.sql
I haven't include a changelog since it's a follow up to a fixed bug, but can do if we prefer to do so.
=> Add a migration step to cleanup potential leftovers of bug 11833

.github/workflows/tests.yml, changelog.d/12965.misc
=> Enable testing against PostgreSQL databases in Complement CI.

changelog.d/13022.doc, docs/SUMMARY.md
=> Add missing TOC link to poetry cheat sheet

.github/workflows/tests.yml, changelog.d/13034.misc
GHA continues to pick a fight with me at every corner :-)
=> Fix Complement runs always being Postgres

changelog.d/13096.misc, synapse/storage/databases/main/event_push_actions.py
This should have been done as part of #13005
=> Rotate notifications more frequently

.ci/scripts/test_old_deps.sh, changelog.d/13082.misc, poetry.lock, pyproject.toml
See individual commit messages for more detail.
=> Use caret (semver bounds) for matrix.org packages

changelog.d/13123.removal, synapse/rest/client/directory.py
Signed-off-by: santhoshivan23 <santhoshivan23@gmail.com>
=> Remove unspecced DELETE endpoint that modifies room visibility

changelog.d/13029.doc, docs/setup/installation.md
Explained the meaning of the --report-stats argument.
Signed-off-by: jejo86 <28619134+jejo86@users.noreply.github.com>
=> Document the `--report-stats` argument

changelog.d/13167.misc, docker/complement/conf/workers-shared-extra.yaml.j2
Needed for https://github.com/matrix-org/complement/pull/375 to pass.
=> [Complement] Allow device_name lookup over federation

changelog.d/13132.doc, docs/SUMMARY.md, docs/development/contributing_guide.md, docs/development/reviews.md
Per our discussion on this last week.
=> Add information on how the Synapse team does reviews.

changelog.d/13344.doc, docs/reverse_proxy.md
Improve/simplify Caddy examples. Remove Caddy v1 (has long been EOL'ed)
=> Update Caddy reverse proxy documentation

changelog.d/13406.misc, docs/upgrade.md, docs/usage/configuration/config_documentation.md, synapse/app/homeserver.py, synapse/config/emailconfig.py, synapse/config/registration.py, synapse/handlers/identity.py, synapse/handlers/ui_auth/checkers.py, synapse/rest/client/account.py, synapse/rest/client/register.py, synapse/rest/synapse/client/password_reset.py, tests/rest/client/test_register.py
This reverts commit fa71bb18b527d1a3e2629b48640ea67fff2f8c59.
=> Revert "Drop support for delegating email validation (#13192)"

changelog.d/13438.doc, docs/usage/configuration/config_documentation.md
=> Remove 'Contents' section from the Configuration Manual

changelog.d/13450.doc, docs/modules/password_auth_provider_callbacks.md
=> Fix return value in example on `password_auth_provider_callbacks.md`

changelog.d/13449.doc, docs/sso_mapping_providers.md
Fixes: #13410
and update links to spec
=> Update some outdated information on `sso_mapping_providers.md`

changelog.d/13536.doc, docs/usage/configuration/config_documentation.md
=> Add missing link in `user_consent` section of configuration manual

changelog.d/13537.bugfix, docs/usage/configuration/config_documentation.md, synapse/app/homeserver.py
Closes Issue #13415
Signed-off-by: Ayush Anand [iamayushanand@gmail.com](mailto:iamayushanand@gmail.com)
=> Add support of compression to federation responses

.github/workflows/triage-incoming.yml
Set up automation to move newly opened issues in GitHub to the issue triage board.
=> Add GitHub automation for new issues

.github/workflows/triage_labelled.yml
Attempt to write a GH action that moves issues labelled with X-Needs-Info into a project.
=> First draft of triage_labelled action

changelog.d/13679.misc, synapse/federation/sender/__init__.py
c.f. #13444
Not sure if we want this to DEBUG or be a specific logger?
=> Add some logging to help track down #13444

changelog.d/13693.misc, synapse/storage/databases/main/room.py
=> Cache `is_partial_state_room`

changelog.d/13795.misc, synapse/api/auth.py
I removed all the calls to that method in https://github.com/matrix-org/synapse/pull/13094 and https://github.com/matrix-org/synapse/pull/13093, but forgot to actually remove that method.
(run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linte …
=> Remove unused method in `synapse.api.auth.Auth`.

changelog.d/13667.feature, scripts-dev/mypy_synapse_plugin.py, synapse/module_api/__init__.py, synapse/storage/_base.py, synapse/storage/databases/main/cache.py, synapse/util/caches/descriptors.py, tests/replication/test_module_cache_invalidation.py
=> Add cache invalidation across workers to module API

changelog.d/13818.doc, docs/setup/installation.md
=> Update NixOS module URL

.github/workflows/dependabot_changelog.yml, changelog.d/14011.misc
=> Change dependabot CL suffix

changelog.d/14087.doc, docs/development/contributing_guide.md
=> The changelog entry ending in a `.` or `!` is not optional

.github/workflows/release-artifacts.yml, changelog.d/14224.misc
=> Fixes to release-artifacts warnings

changelog.d/14280.bugfix, synapse/federation/sender/__init__.py
Fixes #14267. Introduced by #13813
=> Fix `TypeError: 'dict_keys' object is not reversible`

changelog.d/14339.misc, docker/complement/conf/workers-shared-extra.yaml.j2, scripts-dev/complement.sh
See corresponding complement PR: matrix-org/complement#547.
Related to #14143.
=> Enable testing MSC3874 in complement.

changelog.d/14396.feature, scripts-dev/build_debian_packages.py
=> Build Debian packages for Ubuntu 22.10 Kinetic Kudu

changelog.d/14433.misc, scripts-dev/release.py, synapse/streams/events.py
Oversights in #14427 and #14429.
=> Remove unused type-ignores

.github/ISSUE_TEMPLATE/BUG_REPORT.yml, changelog.d/14522.misc
Not everyone uses it. I hope this doesn't add too much friction. Still, these are common questions we have to ask when diagnosing a problem.
Untested. I don't know if we _can_ test it without just trying it??
=> Add more prompts to bug report form

changelog.d/14673.doc, docs/setup/installation.md
Closes https://github.com/matrix-org/synapse/issues/14601
See also https://github.com/matrix-org/synapse/issues/14601#issuecomment-1348741757
=> Declare support for Python 3.11

changelog.d/14778.doc, docs/openid.md
=> Document using Twitter as an OAuth 2.0 provider

changelog.d/14797.doc, docs/upgrade.md
As noticed in https://github.com/matrix-org/synapse/pull/14712/files#r1058433297
=> Fix upgrade notes for installing ICU

changelog.d/14825.misc, scripts-dev/database-save.sh, synapse/storage/schema/main/delta/73/25drop_presence.sql
=> Drop unused table `presence`

changelog.d/14875.docker, docker/Dockerfile
=> Dockerfile: Bump Python version from 3.9 to 3.11

changelog.d/15054.misc, synapse/rest/client/account.py
Part of #4826.
Originally added in #11882.
=> Apply logging from hotfixes branch to develop

Cargo.lock, changelog.d/15043.misc, rust/Cargo.toml
Signed-off-by: Kai A. Hiller <V02460@gmail.com>
=> Update pyo3-log to v0.8.1

changelog.d/15177.bugfix, tests/storage/test_user_directory.py
=> ICU on alpine / macOS behaves differently

changelog.d/15421.misc, synapse/rest/client/login.py
=> Load SSO rest API for redirect only if SSO is enabled

changelog.d/15588.misc, pyproject.toml
=> Allow poetry-core 1.6.0

changelog.d/15621.misc, synapse/rest/client/mutual_rooms.py, synapse/rest/client/versions.py, tests/rest/client/test_mutual_rooms.py
This updates the Mutual Rooms ([MSC2666](https://github.com/matrix-org/matrix-spec-proposals/pull/2666)) implementation to [the latest version](https://github.com/matrix-org/matrix-spec-proposals/pull/2666#issuecomment-1412236010).
(run the …
=> Update Mutual Rooms (MSC2666) Implementation

changelog.d/15678.misc, synapse/api/room_versions.py
=> Add `MSC3820opt2` as a known room version

changelog.d/15674.feature, contrib/grafana/synapse.json
Add Synapse version deploy annotations to Grafana dashboard
Fix https://github.com/matrix-org/synapse/issues/15662
This manifests as purple lines that show up on all time series panels that you can hover and see what version was deployed.
Also added a new "Deployed Synapse versions over time" panel with the color block changes of each version. And mixed this color block into the "Up" time series panel as well.
To get the Grafana dashboard JSON to copy here: use the **Share** icon at the top -> **Export** -> check the **Export for sharing externally** option -> **View JSON** or **Save to file** …
=> Add Synapse version deploy annotations to Grafana dashboard

changelog.d/15723.misc, synapse/handlers/presence.py, synapse/handlers/read_marker.py, synapse/handlers/room.py, synapse/handlers/stats.py, synapse/rest/media/upload_resource.py
=> Remove some unused `server_name` fields

changelog.d/15729.misc, synapse/storage/databases/main/user_directory.py
=> Improve performance of user directory search

changelog.d/15746.bugfix, synapse/http/replicationagent.py
Fixes #15744.
Introduced in #15578
=> Fix using TLS for replication

changelog.d/15774.bugfix, synapse/types/__init__.py
=> Fix empty scope when having version mismatch between workers

changelog.d/15872.doc, docs/systemd-with-workers/workers/background_worker.yaml, docs/systemd-with-workers/workers/event_persister.yaml, docs/systemd-with-workers/workers/federation_sender.yaml, docs/systemd-with-workers/workers/media_worker.yaml, docs/systemd-with-workers/workers/pusher_worker.yaml
=> Remove `worker_replication_*` settings from worker doc

changelog.d/15961.misc, scripts-dev/build_debian_packages.py
As the title states. Fixes #15857.
=> Build packages for Debian Trixie

changelog.d/16016.doc, synapse/replication/http/devices.py
This confused me the other day and sent me on a bit of an annoying wild goose chase so here is my attempt to make this clearer.
=> Clarify comment on key uploads over replication

changelog.d/16027.doc, docs/reverse_proxy.md
=> Do not expose Admin API in caddy reverse proxy example

changelog.d/16091.doc, docs/structured_logging.md
=> Add link explaining ELK stack to structured_logging.md

changelog.d/16114.feature, docs/admin_api/user_admin_api.md, synapse/rest/admin/users.py, synapse/storage/databases/main/__init__.py, tests/rest/admin/test_user.py
=> Allow filtering for admins in the list accounts admin API

changelog.d/16008.doc, docs/development/releases.md
=> Update URLs to matrix.org blog categories

changelog.d/16212.misc, synapse/storage/background_updates.py, tests/storage/test_background_update.py
Would have been useful for #16192
=> Log the details of background update failures

changelog.d/16263.misc, flake.nix
Follows: #16090 
<ol>
<li>
Suggestions from PR 
</li>
</ol>
=> Apply missed suggestions from the review of #16090.

.ci/scripts/calculate_jobs.py, changelog.d/16351.misc
PostgreSQL 16 is out: https://www.postgresql.org/about/news/postgresql-16-released-2715/
=> Test against PostgreSQL 16.

changelog.d/16359.misc, synapse/rest/models.py
=> Add missing license header.

changelog.d/16435.misc, synapse/storage/databases/main/__init__.py
As far as I can tell this is unused? Let's see...
=> Remove unused method.

.github/workflows/tests.yml, changelog.d/16466.misc, scripts-dev/complement.sh
Sister PR to https://github.com/matrix-org/complement/pull/666
Context: https://github.com/matrix-org/complement/issues/654#issuecomment-1746613495
=> Update complement.sh to match new public API shape

changelog.d/16461.misc, scripts-dev/release.py
<ol>
<li>
Add reminder to check special release notes board in release script 
</li>
</ol>
=> Update the release script to remind releaser to check for special release notes.

changelog.d/16657.misc, synapse/storage/databases/main/event_push_actions.py, synapse/storage/schema/main/delta/83/06_event_push_summary_room.sql
=> Speed up purge room by adding index
