matrix-org/synapse

changelog.d/6753.bugfix, scripts/hash_password
The old statement returned `None` for such a `password_config` (like the one
created on first run), thus retrieval of the `pepper` key failed with
`AttributeError`.
Fixes #5315
Signed-off-by: Ivan Vilata i Balaguer <ivan@selidor.net>
=> Avoid attribute error when `password_config` present but empty

changelog.d/6764.misc, synapse/rest/media/v1/thumbnail_resource.py, tests/rest/media/v1/test_media_storage.py
Fix a typo introduced in https://github.com/matrix-org/synapse/pull/6732 that broke thumbnailing with the `crop` method.
Also added some tests so that this code path is tested.
Fixes https://github.com/matrix-org/synapse/issues/6759
=> Fix typo in _select_thumbnail

changelog.d/6751.misc, synapse/handlers/admin.py, synapse/rest/admin/users.py, synapse/storage/data_stores/main/registration.py
Remove the methods in admin handler that just call store methods and instead call those methods directly. Also nice for not getting multiple implementations pop up in your IDE when you try to go to the definition of a method.
Inspired by https://github.com/matrix-org/synapse/pull/6720#discussion_r368470895
=> Remove unnecessary abstractions in admin handler

changelog.d/6761.bugfix, synapse/rest/admin/users.py
* don't insist on a password (this is valid if you have an SSO login)
* fix reference to undefined `requester`
=> Minor fixes to user admin api

changelog.d/6771.bugfix, synapse/events/__init__.py, synapse/storage/data_stores/main/events.py, synapse/storage/data_stores/main/events_worker.py, tests/storage/test_redaction.py
There are quite a few places that we assume that a redaction event has a
corresponding `redacts` key, which is not always the case. So lets
cheekily make it so that event.redacts just returns None instead.
Fixes exceptions being able to persist redaction events that don't have a redact key.
=> Make 'event.redacts' never raise.

changelog.d/6767.bugfix, synapse/handlers/identity.py, synapse/rest/client/v2_alpha/account.py, synapse/rest/client/v2_alpha/register.py, synapse/util/stringutils.py, tests/util/test_stringutils.py
Helps address #6766 
This is a port of https://github.com/matrix-org/synapse-dinsic/pull/20 for mainline, but allowing `:` characters. See the attached issue for context.
=> Validate client_secret parameter

changelog.d/6775.doc, docs/workers.md
* Add note that user_dir requires disabling user dir
updates from the main synapse process.
* Add note that federation_reader should have
the federation listener resource.
=> Clarifications to the workers documentation

changelog.d/6793.bugfix, synapse/storage/data_stores/main/monthly_active_users.py
Calling the invalidation function during initialisation of the data
stores introduces a circular dependency, causing Synapse to fail to
start.
Fixes #6791
=> Fix setting `mau_limit_reserved_threepids` config

changelog.d/6788.misc, synapse/api/auth.py, synapse/event_auth.py, synapse/handlers/federation.py, synapse/handlers/message.py, synapse/state/v1.py, synapse/state/v2.py, tests/test_event_auth.py
These are easier to work with than the strings and we normally have one around.
This fixes `FederationHander._persist_auth_tree` which was passing a
RoomVersion object into event_auth.check instead of a string.
=> Pass room version object into event_auth.check and check_redaction

changelog.d/6776.misc, synapse/handlers/devicemessage.py, synapse/handlers/federation.py, synapse/replication/slave/storage/devices.py, synapse/storage/data_stores/main/devices.py, synapse/storage/data_stores/main/schema/delta/57/device_list_remote_cache_stale.sql
When we receive to device messages or encrypted events from an unknown device we should log and mark the cache as stale. Currently we don't actually *do* anything about it, but that will come in a future PR.
=> Detect unknown remote devices and mark cache as stale

changelog.d/6796.bugfix, synapse/handlers/e2e_keys.py
We ended up only returning a single device, rather than all of them.
This only happens when the local server thinks it should be tracking the keys of a remote user, but hasn't yet fetched them, when a local user requests those keys. The results get correctly cached so subsequent calls were fine.
=> Fix bug when querying remote user keys that require a resync.

changelog.d/6792.misc, synapse/storage/data_stores/main/events.py, synapse/storage/persist_events.py
Otherwise its just stale data, which may get deleted later anyway so can't be relied on. It's also a bit of a shotgun if we're trying to get the current state of a room we're not in.
This also delete forward extremities, which I'm slightly more in two minds about.
=> Delete current state when server leaves a room

changelog.d/6799.bugfix, synapse/app/federation_sender.py, synapse/federation/send_queue.py
We were sending device updates down both the federation stream and
device streams. This mean there was a race if the federation sender
worker processed the federation stream first, as when the sender checked
if there were new device updates the slaved ID generator hadn't been
updated with the new stream IDs and so returned nothing.
This situation is correctly handled by events/receipts/etc by not
sending updates down the federation stream and instead having the
federation sender worker listen on the other streams and poke the
transaction queues as appropriate.
=> Fix race in federation sender that delayed device updates.

changelog.d/6790.feature, synapse/events/utils.py, synapse/handlers/directory.py, synapse/handlers/room.py, tests/events/test_utils.py
~~Based on #6787.~~
See https://github.com/matrix-org/matrix-doc/pull/2260
=> MSC2260: change the default power level for m.room.aliases events

changelog.d/6800.bugfix, synapse/federation/send_queue.py
=> Remove unused DeviceRow class

changelog.d/6803.misc, synapse/events/__init__.py, synapse/python_dependencies.py, synapse/types.py, tests/storage/test_keys.py
PR 1 of N: a couple of preparatory changes, to add some types which are handy for type annotations
* bump signedjson to 1.1
* add a JsonDict type
=> Type defintions for use in refactoring for redaction changes

changelog.d/6797.misc, synapse/storage/data_stores/main/devices.py
If we have detected that the remote users' keys may have changed then we should attempt to resync against the remote server rather than using the (potentially) stale local cache.
=> When a client asks for remote keys check if should resync.

changelog.d/6801.bugfix, synapse/storage/data_stores/main/roommember.py, synapse/storage/persist_events.py
When a server leaves a room it may stop sharing a room with remote
users, and thus not get any updates to their device lists. So we need to
check for this case and mark those device lists and stale.
We don't need to do this if we stop sharing a room because the remote
user leaves the room, because we track that case via looking at
membership changes.
---
The alternative to marking the device lists as stale is to delete the users from the cache? This would mean that if the remote server is down we won't get stale events.
This, coupled with #6797, should help fix #6399.
=> When server leaves room check for stale device lists.

changelog.d/6811.bugfix, synapse/federation/transport/client.py, synapse/federation/transport/server.py, synapse/replication/tcp/client.py, synapse/server.pyi, tox.ini
Add fix the typing of `synapse.federation.transport`
=> Fix sending server up commands from workers

changelog.d/6786.misc, synapse/handlers/devicemessage.py, synapse/handlers/federation.py, tests/handlers/test_typing.py
=> Resync remote device list when detected as stale.

changelog.d/6802.misc, synapse/storage/data_stores/main/schema/delta/57/delete_old_current_state_events.sql, synapse/storage/data_stores/main/state.py
This is a companion to #6792 and #6801.
Based on #6801.
=> Backgroud update to clean out rooms from current state

changelog.d/6794.feature, synapse/rest/client/v1/room.py, tests/rest/admin/test_admin.py, tests/rest/client/v1/test_directory.py
as per [MSC2260](https://github.com/matrix-org/matrix-doc/pull/2260)
=> MSC2260: Block direct sends of m.room.aliases events

changelog.d/6816.misc, synapse/storage/data_stores/main/state.py
=> Log when we delete room in bg update

changelog.d/6805.misc, synapse/federation/federation_server.py, synapse/handlers/federation.py
=> Pass room version into FederationHandler.on_invite_request

changelog.d/6810.misc, synapse/handlers/federation.py
`get_pdu` expects to get the room version as a string, not a `RoomVersion`
Broke in #6729
=> Fix bug with getting missing auth event during join 500'ed

changelog.d/6820.misc, synapse/api/errors.py, synapse/federation/federation_client.py, synapse/federation/federation_server.py, synapse/handlers/federation.py, synapse/handlers/message.py, synapse/handlers/pagination.py, synapse/handlers/room.py, synapse/state/__init__.py, synapse/storage/data_stores/main/state.py, synapse/storage/persist_events.py, tests/handlers/test_presence.py, tests/test_state.py, tests/unittest.py
boilerplate is boilerplatey; factor out a useful `get_room_version` method which looks up the room version in `KNOWN_ROOM_VERSIONS`
=> Make `get_room_version` return a RoomVersion object

changelog.d/6806.misc, synapse/crypto/event_signing.py, synapse/events/builder.py, synapse/federation/federation_client.py, tests/crypto/test_event_signing.py, tests/handlers/test_presence.py
PR 3/n: pass the room_version down through EventBuilder, and create_local_event into add_hashes_and_signatures.
Suggest looking at each commit separately
=> Pass room_version into add_hashes_and_signatures

changelog.d/6807.misc, synapse/crypto/event_signing.py, synapse/handlers/federation.py
PR 4/n
~~Based on #6805 and #6806~~
=> pass room_version into compute_event_signature

changelog.d/6819.misc, synapse/storage/data_stores/main/devices.py
We were in fact only deleting stale marker when we got an incremental update, rather than when we did a full resync.
Fixes up PR #6776
=> Fix deleting of stale marker for device lists

changelog.d/6827.misc, synapse/federation/federation_server.py, synapse/federation/transport/server.py
I messed this up a bit in #6805, but fortunately we weren't actually doing
anything with the room_version so it didn't matter that it was a str not a RoomVersion.
=> Fix `room_version` in `on_invite_request` flow

changelog.d/6825.bugfix, synapse/rest/admin/users.py
Fixes: https://github.com/matrix-org/synapse/issues/6824
Fixes: https://github.com/matrix-org/synapse/issues/6752
=> Allow URL-encoded user IDs on user admin api paths

changelog.d/6836.misc, synapse/util/async_helpers.py
So `__failure__` is a magic (undocumented) thing that twisted will look for when raising exception during an `await`: https://github.com/twisted/twisted/blob/twisted-19.10.0/src/twisted/internet/defer.py#L748.
Empirically this seems to Do The Right Thing, but it somewhat feels like we're working against Twisted here. Ideally there would be some sort of `ObservableDeferred` in Twisted that handled this stuff properly, but there doesn't seem to be.
=> Fix stacktraces when using ObservableDeferred and async/await

changelog.d/6837.misc, synapse/handlers/federation.py, synapse/handlers/message.py, synapse/handlers/room_member.py
Sorry about the size of this.
Each commit converts a single method to async/await.
=> Port much of `synapse.handlers.federation` to async/await.

CONTRIBUTING.md, changelog.d/6846.doc
Update contributing to add new suggested section on Merge Strategy based on chat on synapse-dev.
(I don't care about the details of this, I think I've captured the idea, but feel free to bikeshed as required. All I'm looking for is the intent written down so I don't forget to ask each time).
=> Update CONTRIBUTING.md about merging PRs.

changelog.d/6844.bugfix, synapse/storage/data_stores/main/devices.py
fixes https://github.com/matrix-org/synapse/issues/6830
=> add device signatures to device key query results

changelog.d/6848.bugfix, synapse/api/constants.py, synapse/handlers/federation.py, synapse/handlers/room.py, synapse/handlers/stats.py, synapse/storage/data_stores/main/stats.py
We were looking at the wrong event type (`m.room.encryption` vs
`m.room.encrypted`).
Also fixup the duplicate `EvenTypes` entries.
Introduced in #6776.
=> Fix detecting unknown devices from remote encrypted events.

changelog.d/6847.misc, synapse/storage/data_stores/main/schema/delta/57/rooms_version_column_2.sql.postgres, synapse/storage/data_stores/main/schema/delta/57/rooms_version_column_2.sql.sqlite
We're going to need this so that we can figure out how to handle redactions when fetching events from the database.
=> Database updates to populate rooms.room_version

changelog.d/6833.misc, synapse/storage/database.py
This PR reduces the default logging level of verbose performance monitoring counters from INFO to DEBUG.
Leo even wrote along side this code:
```
```
So there's definitely a case to rip this out entirely - reducing to DEBUG seems safe.
These metrics are available more generally in the prometheus metrics (eg `synapse_background_process_db_txn_duration_seconds`) which when looking at performance changes over time is probably a better way to …
=> Reduce performance logging to DEBUG

changelog.d/6850.misc, synapse/handlers/device.py, synapse/handlers/federation.py
If it doesn't then the device lists are probably out of sync so we should resync.
Also add info logging when we receive device updates to help debug missing device lists. Hopefully this shouldn't be tooooo spammy.
=> Check sender_key matches on inbound encrypted events.

changelog.d/6840.misc, synapse/federation/federation_client.py
Another big async/await PR I'm afraid.
~~Based on #6837.~~
=> Port much of `synapse.federation.federation_client` to async/await

README.rst, changelog.d/6855.misc
Without this change my shell complains with:
```
$ python -m pip install --no-use-pep517 -e .[all]
zsh: no matches found: .[all]
```
=> Add quotes around the pip install target to avoid my shell complaining

changelog.d/6823.misc, synapse/federation/federation_client.py, synapse/handlers/federation.py
This is a couple of commits which adds some `room_version` plumbing to bits of the code.
=> pass room versions around

changelog.d/6862.misc, synapse/federation/federation_server.py, synapse/federation/transport/server.py, synapse/handlers/room.py, synapse/handlers/stats.py, synapse/handlers/sync.py, synapse/handlers/user_directory.py, synapse/http/site.py, synapse/push/httppusher.py, synapse/storage/data_stores/main/user_directory.py, synapse/storage/persist_events.py, synapse/util/caches/response_cache.py
A lot of the things we log at INFO are now a bit superfluous, so lets
make them DEBUG logs to reduce the amount we log by default.
---
The big thing left is to reduce the number of log lines for outbound requests, but that is a bit more complicated so I've left that for now. We also might want to consider not logging GC gen 1 and 2 collections (potentially replacing with logging if they take a long time?)
Most of these were found by looking at jki.re logs and sytest logs.
=> Reduce amount of logging at INFO level.

changelog.d/6854.misc, synapse/federation/federation_client.py, synapse/handlers/federation.py
... and rewrite the way we sanity-check the create event.
=> pass room version into FederationClient.send_join

changelog.d/6864.misc, synapse/handlers/federation.py
Limits the maximum number of events that can be requested from the backfill events federation API.
The maximum limit was suggested by @erikjohnston to match what Synapse requests when calling this API as a client (see https://github.com/matrix-org/synapse/blob/v1.9.0/synapse/handlers/federation.py#L978-L980).
=> Limit the number of events that can be requested when backfilling events

changelog.d/6856.misc, synapse/federation/federation_base.py, synapse/federation/federation_client.py, synapse/federation/federation_server.py, tests/handlers/test_federation.py
It's called from all over the shop, so this one's a bit messy.
~~Based on #6823, #6854.~~
=> Pass room_version into `event_from_pdu_json`

changelog.d/6769.feature, docs/admin_api/user_admin_api.rst, synapse/handlers/admin.py, synapse/handlers/auth.py, synapse/rest/admin/users.py, tests/rest/admin/test_user.py
This implements #6769.
Signed-off-by: Dirk Klimpel <dirk@klimpel.org>
=> Admin api to add an email address

changelog.d/6866.feature, docs/workers.md, synapse/app/client_reader.py, synapse/app/federation_reader.py, synapse/groups/groups_server.py, synapse/handlers/groups_local.py, synapse/replication/slave/storage/groups.py, synapse/server.py, synapse/storage/data_stores/main/group_server.py
Tests: https://github.com/matrix-org/sytest/pull/798
Fixes #6415 
---
Most of this PR is separating the various stores and handlers into what can be run on master and what can be run on workers, i.e. a bunch of cutting and pasting
=> Allow moving group read APIs to workers

changelog.d/6871.misc, synapse/federation/federation_server.py, synapse/federation/sender/__init__.py, synapse/federation/sender/per_destination_queue.py, synapse/federation/sender/transaction_manager.py, synapse/federation/units.py, synapse/server.pyi, tests/handlers/test_typing.py, tox.ini
Probably easiest to go commit by commit.
=> Add typing to synapse.federation.sender

changelog.d/6858.misc, synapse/events/__init__.py, synapse/events/builder.py, synapse/federation/federation_base.py, tests/api/test_filtering.py, tests/crypto/test_event_signing.py, tests/events/test_utils.py, tests/federation/test_federation_server.py, tests/replication/slave/storage/test_events.py, tests/state/test_v2.py, tests/test_event_auth.py, tests/test_federation.py, tests/test_state.py
... and use it in places where it's trivial to do so.
This will make it easier to pass room versions into the FrozenEvent constructors.
Based on #6856.
=> Add a `make_event_from_dict` method

.buildkite/scripts/test_old_deps.sh, changelog.d/6880.misc, tox.ini
Workaround for https://github.com/jaraco/zipp/issues/40
=> Update setuptools for python 3.5 tests

changelog.d/6878.feature, synapse/visibility.py
We're in the middle of properly mitigating spam caused by malicious aliases being added to a room. However, until this work fully lands, we temporarily filter out all `m.room.aliases` events from /sync and /messages on the CS API, to remove abusive aliases.  This is considered acceptable as `m.room.aliases` events were never a reliable record of the given alias->id mapping and were purely informational, and in their current state do more harm than good.
=> filter out m.room.aliases from the CS API until a better solution is specced

.buildkite/worker-blacklist, changelog.d/6883.misc
This adds the "Can get rooms/{roomId}/members at a given point" to the SyTest worker mode blacklist.
=> Add a flaky test to the SyTest worker blacklist

changelog.d/6884.feature, synapse/handlers/sync.py
I forgot to filter out aliases from /sync state blocks as well as the timeline.
=> filter out m.room.aliases from /sync state blocks

changelog.d/6882.misc, synapse/handlers/device.py, tests/handlers/test_device.py
This rejects device display name updates that are too long by raising a `SynapseError` from update device endpoint.
This defines a maximum length of 100 characters, but that is arbitrary. If someone has a better suggestion, please let me know!
=> Reject device display names that are too long

changelog.d/6887.misc, scripts-dev/config-lint.sh
In the linting scripts the use of sed is not compatible with BSD's sed (which is what macOS uses unless a different version is installed).
This [StackOverflow](https://stackoverflow.com/questions/5694228/sed-in-place-flag-that-works-both-on-mac-bsd-and-linux) has a good explanation of the differences.
Without this change I end up with a `docs/sample_config.yaml-E` file in my directory each time I run the linting script.
I have not tested this with GNU sed, but I'm fairly certain it will work! You can check which version you have via the man pages (`man sed`). (Weirdly my version doesn't seem to have a `--version` flag...)
=> Use BSD-compatible in-place editing for sed.

changelog.d/6901.misc, synapse/rest/admin/users.py, tests/rest/admin/test_user.py
Fixes https://github.com/matrix-org/synapse/issues/6900
=> Return a 404 for admin api user lookup if user not found

changelog.d/6891.doc, docs/admin_api/purge_history_api.rst, docs/message_retention_policies.md
Because people can (rightfully) get confused by that, e.g. https://github.com/matrix-org/synapse/issues/3148
=> Spell out that the last event sent to a room won't be deleted by a purge

changelog.d/6888.feature, docs/spam_checker.md, synapse/events/spamcheck.py, synapse/handlers/user_directory.py, tests/handlers/test_user_directory.py
* Adds a method to the spam checker with a user ID & display name and expects whether to display that user or not.
* For backwards compatibility, if the method on the spam checker doesn't exist it is ignored.
* Uses the above method in the user directory search to filter the responses.
Fixes #5648
=> Filter the results of user directory searching via the spam checker

changelog.d/6919.misc, tests/handlers/test_directory.py
This is a test only change, so if the code looks sane and unit tests pass this should be fine!
As requested in https://github.com/matrix-org/synapse/pull/6904/files#r379126831
=> Convert the directory handler tests to use HomeserverTestCase

changelog.d/6921.docker, contrib/docker/docker-compose.yml
According to [the docs](https://github.com/matrix-org/synapse/blob/master/docs/postgres.md#set-up-database), these should be explicitly set. In my case, after setting up a homeserver with this compose file as a reference, I ended up with this:
```
synapse=# SELECT datcollate,datctype FROM pg_database WHERE datname = current_database();
datcollate |  datctype  
------------+------------
en_US.utf8 | en_US.utf8
```
Signed-off-by: Fridtjof Mund <fridtjof@das-labor.org>
=> contrib/docker: Ensure correct encoding and locale settings on DB creation

changelog.d/6915.misc, synapse/events/spamcheck.py, synapse/spam_checker_api/__init__.py, tox.ini
This adds type hints to the spam check module and has mypy check it.
This is my first foray into typing so hopefully I didn't do anything crazy.
I spun this out of #6906 since I couldn't get it working, but I've since fixed the issue.
=> Add type hints to the spam check module

changelog.d/6924.bugfix, synapse/storage/data_stores/main/schema/delta/57/delete_old_current_state_events.sql
=> wait for current_state_events_membership before delete_old_current_state_events

changelog.d/6918.docker, docker/README.md, docker/start.py
Lots of people seem to get confused by this mode, and it's been deprecated
since Synapse 1.1.0. It's time for it to go.
Fixes #6912
=> Kill off deprecated "config-on-the-fly" docker mode

changelog.d/6904.removal, synapse/handlers/directory.py, synapse/handlers/room.py, tests/handlers/test_directory.py
This implements the first task in #6898, new alias semantics:
* Update {PUT, DELETE} /_matrix/client/r0/directory/room/{roomAlias} to stop sending m.room.aliases events.
* Update DELETE /_matrix/client/r0/directory/room/{roomAlias} to check the alt_aliases in m.room.canonical_alias.
=> Stop sending events when creating or deleting aliases

changelog.d/6938.doc, docs/workers.md
Accompanying sytest https://github.com/matrix-org/sytest/pull/807
=> Fix worker docs to point `/publicised_groups` API correctly.

changelog.d/6937.misc, synapse/storage/data_stores/main/event_federation.py
We do this by moving the recursive query to be fully in the DB.
=> Increase perf of `get_auth_chain_ids` used in state res v2.

changelog.d/6907.doc, docs/sample_config.yaml, synapse/config/tls.py, synapse/handlers/acme.py
Also raises a more understandable error when failing to register against the ACME provider at startup (raising a `ConfigError`, not sure if that's the best error type to use?).
=> Add mention and warning about ACME v1 deprecation to the TLS config

changelog.d/6872.misc, synapse/events/__init__.py, tests/storage/test_redaction.py
... but first, replace _event_dict_property with DictProperty. I think that this removes a layer of function dispatch for each lookup.
=> Rewrite _EventInternalMetadata to back it with a dict

changelog.d/6939.feature, synapse/handlers/directory.py, synapse/rest/client/v1/room.py, tests/rest/client/v1/test_rooms.py, tests/unittest.py
per https://github.com/matrix-org/matrix-doc/pull/2432
=> Implement GET /_matrix/client/r0/rooms/{roomId}/aliases

changelog.d/6936.misc, synapse/storage/data_stores/main/roommember.py, synapse/storage/persist_events.py
For rooms with large amount of state a single user leaving could cause us to go and load a lot of membership events and then pull out membership state in a large number of batches.
=> Increase DB/CPU perf of `_is_server_still_joined` check.

changelog.d/6950.misc, synapse/http/server.py
we have hundreds of path_regexes (see #5118), so let's not convert the same
bytes to str for each of them.
=> Tiny optimisation for _get_handler_for_request

changelog.d/6948.feature, synapse/rest/client/v1/room.py, synapse/rest/client/versions.py, tests/rest/client/v1/test_rooms.py
it's not in the spec yet, so needs to be `unstable`. Also add a feature flag for it. Also add a test for admin users.
=> Move MSC2432 stuff onto unstable prefix

changelog.d/6949.feature, synapse/api/auth.py, synapse/handlers/directory.py, synapse/handlers/initial_sync.py, synapse/handlers/message.py, synapse/handlers/pagination.py, synapse/handlers/typing.py, synapse/rest/client/v2_alpha/relations.py, tests/handlers/test_typing.py, tests/rest/client/v1/test_rooms.py
As per https://github.com/matrix-org/matrix-doc/pull/2432#pullrequestreview-360566830, make room alias lists accessible to users outside world_readable rooms.
This also involves a bit of a refactor in `Auth`, in particular trying to avoid yet another method for checking user room membership, by combining `check_joined_room` and `check_user_was_in_room`. The commits should stand alone and be independently reviewable.
=> Make room alias lists peekable

changelog.d/6952.misc, synapse/state/__init__.py, synapse/state/v2.py, synapse/storage/data_stores/main/event_federation.py, tests/state/test_v2.py
The state res v2 algorithm only cares about the difference between auth chains, so we can pass in the known common state to the `get_auth_chain` storage function so that it can ignore those events.
=> Reduce auth chains fetched during v2 state res.

changelog.d/6953.misc, synapse/app/_base.py
This may make gc go a bit faster as the gc will know things like caches/data stores etc. are frozen without having to check.
I'm not actually sure this will work.
=> Freeze allocated objects on startup.

changelog.d/6615.misc, synapse/storage/data_stores/main/schema/full_schemas/README.md
Please someone explain, what the two folders 16 and 54 are about and why the dump is used for later, and why it is important.
I plan to add some information, how to add the foreign key CONSTRAINT like visualized in https://github.com/matrix-org/synapse/issues/934 like
ALTER TABLE event_forward_extremities ADD CONSTRAINT room_id_fk FOREIGN KEY (room_id) REFERENCES rooms (room_id);
ALTER TABLE room_account_data         ADD CONSTRAINT room_id_fk FOREIGN KEY (room_id) REFERENCES rooms (room_id);
ALTER TABLE room_account_data         ADD CONSTRAINT user_id_fk FOREIGN KEY (user_id) REFERENCES users (name);
ALTER TABLE room_memberships          ADD CONSTRAINT room_id_fk FOREIGN KEY (room_id) REFERENCES rooms (room_id);
ALTER TABLE room_memberships          ADD CONSTRAINT user_id_fk FOREIGN KEY …
=> Add some clarifications to README.md in the database schema directory

changelog.d/6956.misc, synapse/storage/data_stores/main/end_to_end_keys.py
device table should only be for local users.  This may also fix an issue when receiving multiple key updates from another server.
=> don't insert into the device table for remote cross-signing keys

changelog.d/6941.removal, synapse/handlers/directory.py, synapse/handlers/room.py
This is the second part of #6898:
> Update POST /_matrix/client/r0/rooms/{roomId}/upgrade API to stop copying room aliases (and thus to stop m.room.aliases events). Update POST /_matrix/client/r0/createRoom to stop sending m.room.aliases events.
~~Additionally it also propagates the "alt_aliases" from the old room to the new room during room upgrade.~~
Additionally it propagates the content of the canonical alias event from the old room to the new room during a room upgrade.
=> Do not send alias events when creating / upgrading a room

INSTALL.md, changelog.d/6944.doc, synapse/handlers/acme.py
Some small fixes to the copy in https://github.com/matrix-org/synapse/pull/6907.
=> Small grammar fixes to the ACME v1 deprecation notice

changelog.d/6967.bugfix, synapse/replication/tcp/streams/_base.py
This is intended to fix, or at least work around, #2738.
The problem is essentially that when we join a room with more than 10000 state events (ie, a room that has ever had more than 10000 different mxids in it), this creates an entry in the replication stream which consists of 10000 rows. The master then thinks that the worker has got behind and drops the connection. The worker reconnects, but immediately the same problem recurs.
There's some debate about whether it's useful to have a cap at all: it's not like booting the worker off actually fixes anything, so it's more a red flag to indicate that there's a problem (and helps stop the master ending up with massive queues of replication data when the workers get behind).
Still, it's likely that we'll be reworking things in this department …
=> Increase MAX_EVENTS_BEHIND for replication clients

changelog.d/6965.feature, synapse/api/auth.py
Another part of #6898.
This modifies the power level required to publish or remove a room from the room directory. Instead of looking m.room.alias, it looks at m.room.canonical_alias.
=> Require a user to have a PL > canonical_alias when (de-)publishing to the directory.

changelog.d/6970.removal, synapse/handlers/room_list.py
Part of #6898:
>  Update /_matrix/client/r0/publicRooms to stop sending a list of aliases.
=> Do not return aliases as part of the public room list

changelog.d/6966.removal, synapse/push/presentable_names.py
Part of #6898
* Stops using the room alias events to calculate room name.
* Use constants for event types instead of string literals.
=> Stop using room alias events to calculate room name

changelog.d/6962.bugfix, docs/sample_config.yaml, synapse/config/emailconfig.py
* Give `notif_template_html`, `notif_template_text` default values (fixes #6960)
* Don't complain if `smtp_host` and `smtp_port` are unset, since they have sensible defaults (fixes #6961)
* Set the example for `enable_notifs` to `True`, for consistency and because it's more useful
* Raise errors as ConfigError rather than RuntimeError for nicer formatting
=> Fix minor issues with email config

changelog.d/6968.bugfix, synapse/handlers/federation.py, synapse/storage/data_stores/main/room.py
This is intended as a precursor to storing room versions when we receive an
invite over federation, but has the happy side-effect of fixing #3374 at last.
In short: change the store_room with try/except to a proper upsert which
updates the right columns.
=> Upsert room version when we join over federation

changelog.d/6979.misc, synapse/handlers/federation.py
`_process_received_pdu` is only called by `on_receive_pdu`, which ignores any
events for unknown rooms, so this is redundant.
=> Remove redundant store_room call

changelog.d/6984.docker, contrib/docker/docker-compose.yml
I made a mistake in https://github.com/matrix-org/synapse/pull/6921 - the quotes break the postgres container's startup script (or docker-compose), which makes initdb fail: https://github.com/matrix-org/synapse/pull/6921#issuecomment-590657154
Signed-off-by: Fridtjof Mund <fridtjof@das-labor.org>
=> contrib/docker: remove quotes for POSTGRES_INITDB_ARGS

changelog.d/6990.bugfix, synapse/rest/admin/users.py, synapse/rest/client/v1/login.py, tests/rest/admin/test_user.py
Fixes https://github.com/matrix-org/synapse/issues/6989
=> Ensure 'deactivated' parameter is a boolean on user admin API, Fix error handling of call to deactivate user

changelog.d/6985.misc, synapse/storage/engines/postgres.py
This resolves #6831 
Signed-off-by: Uday Bansal <43824981+udaybansal19@users.noreply.github.com>
=> Updated warning for incorrect database collation/ctype

changelog.d/6996.bugfix, synapse/federation/federation_base.py
`FederationClient.get_pdu` was made async/await in #6840 (released in 1.110rc1), but a caller of it was not converted. I'm guessing this was missed because `FederationBase._check_sigs_and_hash_and_fetch` has an inner function which calls back into `FederationBase.get_pdu` (see the mypy errors in #6995).
Note that `FederationBase._check_sigs_and_hash_and_fetch` is also used by `FederationServer`, so I believe there's potential for another bug here.
Part of #6978.
=> Cast a coroutine into a Deferred in the federation base

changelog.d/6983.misc, synapse/handlers/federation.py, synapse/replication/http/_base.py, synapse/replication/http/federation.py, synapse/storage/data_stores/main/room.py, tests/app/test_openid_listener.py, tests/handlers/test_typing.py
When we get an invite over federation, store the room version in the rooms table.
The general idea here is that, when we pull the invite out again, we'll want to know what room_version it belongs to (so that we can later redact it if need be). So we need to store it somewhere...
=> Store room version on invite

changelog.d/6987.misc, synapse/storage/database.py, synapse/storage/engines/__init__.py, synapse/storage/engines/_base.py, synapse/storage/engines/postgres.py, synapse/storage/engines/sqlite.py, synapse/storage/types.py, tox.ini
I cracked, and added some type definitions in `synapse.storage`.
A few pointers here to help the reviewer:
* `synapse.storage.types.{Cursor,Connection}` are defined as interfaces which are implemented by the sqlite3 and psycopg2 implementations
* `LoggingTransaction` implicitly also implements `Cursor`.
* `BaseDatabaseEngine` is an abstract base class which is implemented by `Sqlite3Engine` and `PostgresEngine`.
* `create_engine` is rewritten with less magic, to keep mypy happy
* ditto `LoggingTransaction`.
* a bunch of other cleanups and annotations to appease mypy.
=> Add some type annotations in `synapse.storage`

changelog.d/6315.feature, snap/snapcraft.yaml
This PR exposed three binaries via the snap run interface, to make it easier to run them without entering the snap with `snap run --shell`.
* synctl
* hash_password
* generate_config
* generate_signing_key.py
* register_new_matrix_user
The underscores in the name have been replaced with dashes when exposed via snap as the underscore is invalid schema for snapcraft commands. The binaries themselves remain unmodified and use their original names.
Signed-off-by: James Hebden <james@ec0.io>
=> Expose common commands via snap run interface to allow easier invocation

changelog.d/7003.misc, tests/app/test_frontend_proxy.py
to stop the federationhandler trying to do master stuff
=> set worker_app for frontend proxy test

changelog.d/7002.misc, synapse/app/generic_worker.py
Instead lets just warn if the worker has a media listener configured but
has the media repository disabled.
Previously non media repository workers would just ignore the media
listener. Broke in #6964
=> Don't refuse to start worker if media listener configured.

changelog.d/6995.misc, synapse/federation/federation_base.py, synapse/federation/federation_client.py, tox.ini
While researching #6978 I decided to add some typing information to `federation_base` and `federation_client`.
=> Add types to federation client / base

contrib/docker/docker-compose.yml
=> Fix mounting of homeserver.yaml when it does not exist on host

INSTALL.md, changelog.d/7015.misc
Support for getting TLS certificates through ACMEv1 ended on November 2019.
=> Fix last date for ACMEv1 install

.buildkite/scripts/test_old_deps.sh, changelog.d/7018.bugfix
I'm not really sure how this was going wrong, but this seems like the
right approach anyway.
=> Fix py35-old CI by using native tox.

changelog.d/7019.misc, synapse/storage/data_stores/main/state_deltas.py
This currently causes presence notify code to log exceptions when there
is no state changes to process. This doesn't actually cause any problems
as we'd simply do nothing anyway.
Broke in #6991.
=> Always return a deferred from `get_current_state_deltas`.

changelog.d/6971.feature, synapse/api/errors.py, synapse/handlers/directory.py, synapse/handlers/message.py, synapse/types.py, tests/handlers/test_directory.py, tests/rest/client/v1/test_rooms.py, tests/test_types.py
Part of #6898:
>  Update PUT /_matrix/clent/r0/room/{roomId}/state to do validation on the alt_aliases in m.room.canonical_alias
This also does a few other things:
* Updates some of the code from #6904 to handle unexpected data in `alt_aliases` better.
* Updates the test-cases from #6904 for clarity / DRY-ness.
=> Validate alt_aliases property of canonical alias events

changelog.d/6874.misc, synapse/storage/data_stores/main/events_worker.py, tests/replication/slave/storage/test_events.py
This is a precursor to giving EventBase objects the knowledge of which room version they belong to.
=> Read the room version from database when fetching events

changelog.d/6986.feature, synapse/api/auth.py, synapse/handlers/directory.py, tests/handlers/test_directory.py, tox.ini
Part of #6898.
>  Update DELETE /_matrix/client/r0/directory/room/{roomAlias} to allow it to be used by local users with PLs sufficient to send m.room.canonical_alias events.
In my own words, this allows a user to delete an alias if they have power levels >= what is necessary to modify the canonical alias of a room.
This also finishes typing the directory handler since most of it was finished in this PR anyway.
=> Allow deleting an alias if the user has sufficient power level

changelog.d/7035.bugfix, synapse/visibility.py
Fix https://github.com/matrix-org/synapse/issues/6174
=> Hide extremities dummy events from clients

changelog.d/6875.misc, synapse/events/__init__.py, synapse/events/utils.py, synapse/replication/http/federation.py, synapse/replication/http/send_event.py
This is a bit fiddly because it all has to be done on one fell swoop:
* Wherever we create a new event, pass in the room version (and check it matches the format version)
* When we prune an event, use the room version of the unpruned event to create the pruned version.
* When we pass an event over the replication protocol, pass the room version over alongside it, and use it when deserialising the event again.
~~Based on #6874~~
=> Store room_versions in EventBase objects

changelog.d/7020.misc, synapse/rest/key/v2/remote_key_resource.py
I wanted to try converting some basic code from deferreds to async/await. After this PR `Deferreds` aren't used in the `synapse.rest.keys` module.
=> Convert remote key resource REST layer to async/await.

changelog.d/7030.feature, synapse/app/homeserver.py, synapse/storage/data_stores/main/monthly_active_users.py, tests/storage/test_monthly_active_users.py
and emit via prometheus. Fixes #6994.
=> Break down monthly active users by appservice_id 

changelog.d/6309.misc, synapse/logging/context.py
This is a preliminary exploration of adding fuller type hints to a file that seems to be checked by mypy in CI - not all are? I can expand this PR to include more of `logging/` if this kind of approach is deemed reasonable.
I'm not running a full dev environment right now due to lack of space/time, but have a matching mypy installed. I have one outstanding type hint complaint by mypy from my own changes, and one that appears to be in upstream.
I've split the flake8 changes into a separate commit, for now, as I'm not sure if they're all necessary or desirable - partly based on my experience with type hint style in Zulip. See the comments in the commit - basically re spacing and quotes.
Most changes in the first commit should be straightforward, but I'm unsure regarding whether:
* extra …
=> Add type hints to logging/context.py

changelog.d/7045.misc, synapse/handlers/e2e_room_keys.py
Fixes #7036, or at least the confusion around it, by adding a check on the type to return a more understandable error message.
=> Make sure that is_verified is a boolean when processing room keys

changelog.d/7048.doc, docs/workers.md
Per the description in #6705, this updates the documentation to state that fallback auth and register must be routed to the same worker node, this is because there is memory state shared between these endpoints (in the `session` `dict`).
Fixes #6705.
=> Document that fallback auth must be routed to the same worker node as register

changelog.d/7037.feature, synapse/api/room_versions.py, synapse/crypto/event_signing.py, synapse/event_auth.py, synapse/events/utils.py, synapse/storage/data_stores/main/events.py, tests/events/test_utils.py, tests/test_event_auth.py
Part of #6898. This adds an experimental room version that does *not* have special behavior of auth rules and redaction rules for `m.room.aliases` events.
This heavily builds on work from #6787, but modifies it to implement MSC2432 and MSC2261 instead of MSC2260.
I chose to rename the experimental room version since the flag seemed well named to re-use.
~~This is based on #6875.~~
Fixes #6465
=> Modify the auth rules and redaction rules for aliases.

changelog.d/7055.misc, synapse/push/mailer.py, synapse/storage/data_stores/main/event_push_actions.py
Fixes #7054
I also had a look at the rest of the functions in
`EventPushActionsStore` and in the push notifications send code and it
looks to me like there shouldn't be any other method with this issue in
this part of the codebase.
=> Move get_time_of_last_push_action_before to the EventPushActionsWorkerStore

changelog.d/7058.feature, docs/sample_config.yaml, synapse/config/saml2_config.py, synapse/handlers/saml_handler.py, synapse/logging/context.py, synapse/rest/saml2/response_resource.py, synapse/storage/database.py
If an error happened while processing a SAML AuthN response, or a client
ends up doing a `GET` request to `/authn_response`, then render a
customisable error page rather than a confusing error.
=> SAML2: render a comprehensible error page if something goes wrong

changelog.d/7053.feature, docs/sample_config.yaml, synapse/config/registration.py, synapse/handlers/profile.py, synapse/rest/client/v2_alpha/account.py, tests/handlers/test_profile.py, tests/rest/client/v2_alpha/test_account.py
PR for: #5267
Code from #3179 and #3180 with additional tests
=> Add options to disable setting profile info for prevent changes.

changelog.d/7066.bugfix, synapse/handlers/message.py, synapse/visibility.py
Otherwise the requesting user will get told `User @alice:example.com not allowed to view events in room !someroom:example.com at token StreamToken(...)`.
Technical explanation on why this causes Riot to show that error every time we render a room (as copy-pasted from internal room):
> Basically Riot will ask the server for the list of members in a room each time you render that room in Riot, using the latest sync token it knows about or something like that. Synapse then proceeds to check if the user is allowed to see the latest event before this token based on the state at that event, which happens to be the same function call as when wondering if Synapse should send an event to the client, which is a similar question but not exactly the same. For example, we don't want to send dummy …
=> Skip the correct visibility checks when checking the visibility of the state at a given event

changelog.d/7067.feature, docs/sample_config.yaml, synapse/config/saml2_config.py, synapse/res/templates/saml_error.html
Also add some JS to it to process any error we might have in the URI
(see #6893).
=> Move the default SAML2 error HTML to a dedicated file

changelog.d/7074.bugfix, synapse/handlers/account_validity.py
Otherwise renewal emails would be sent even if enabled is set to false in the account validity config.
=> Fix buggy condition in account validity handler

changelog.d/7070.bugfix, synapse/storage/data_stores/main/schema/delta/57/rooms_version_column_3.sql.postgres, synapse/storage/data_stores/main/schema/delta/57/rooms_version_column_3.sql.sqlite
Fixes #7065 
This is basically the same as https://github.com/matrix-org/synapse/pull/6847 except it tries to populate events from `state_events` rather than `current_state_events`, since this table might have been cleared from the state of some rooms too early, leaving them with a `NULL` room version.
=> Populate the room version from state events

changelog.d/7026.removal, synapse/federation/federation_base.py, synapse/federation/federation_client.py, synapse/federation/federation_server.py, synapse/federation/transport/server.py
This removes the unused federation endpoint at `/_matrix/federation/v1/query_auth/{roomId}/{eventId}`.
As part of this it also:
* Moves `_check_sigs_and_hash_and_fetch` from `FederationBase` to `FederationClient` (since it calls into `FederationClient.get_pdu`).
* Converts `_check_sigs_and_hash_and_fetch` to be async/await.
* Fixes type issues that `mypy` found.
~~I need to put up an MSC for this work still, but I wanted to see it run through CI.~~ See [MSC2451](https://github.com/matrix-org/matrix-doc/pull/2451).
Fixes #6997
=> Remove unused federation endpoint (`query_auth`)

changelog.d/7044.bugfix, synapse/rest/media/v1/_base.py
Fix #7043
I have this code running on my own homeserver. Here is the file being rendered there:
https://iddqd.social/_matrix/media/r0/download/iddqd.social/bkwUKJYKmwhMvddiGpErdAmG
I uploaded the same file to matrix.org here:
https://matrix-client.matrix.org/_matrix/media/r0/download/matrix.org/pAMkdBaolnxNCwQTuBaDJYrF
Signed-off-by: Bob Arctor <neetzsche@protonmail.com>
=> Set charset to utf-8 when adding headers for certain text content types

changelog.d/7094.misc, synapse/crypto/context_factory.py, synapse/http/client.py, synapse/http/federation/matrix_federation_agent.py, synapse/server.py, tests/config/test_tls.py, tests/http/federation/test_matrix_federation_agent.py
Extends #5794 etc to the SimpleHttpClient so that it also applies to non-federation requests.
Fixes #7092.
=> Share SSL contexts for non-federation requests

INSTALL.md, changelog.d/6925.doc
=> Update INSTALL.md updated CentOS8 install instructions

changelog.d/7085.feature, docs/admin_api/user_admin_api.rst, synapse/handlers/set_password.py, synapse/rest/admin/users.py, synapse/rest/client/v2_alpha/account.py
This updates the set password API (and the admin API to modify passwords) to take an optional flag: `logout_devices`. If set to `true` (the default) then other sessions are deleted. If set to `false` the password is updated, but any active sessions are left alone.
See matrix-org/matrix-doc#2457 for spec changes.
Fixes  #6963, Fixes #6976
=> Update the set password API to optionally logout other devices.

changelog.d/7095.misc, synapse/state/__init__.py, synapse/state/v2.py, synapse/storage/data_stores/main/event_federation.py, tests/state/test_v2.py, tests/storage/test_event_federation.py
It was originally implemented by pulling the full auth chain of all
state sets out of the database and doing set comparison. However, that
can take a lot work if the state and auth chains are large.
Instead, lets try and fetch the auth chains at the same time and
calcualte the difference on the fly, allowing us to bail early if all
the auth chains converge. Assuming that the auth chains do converge more
often than not, this should improve performance. Hopefully.
Relates to: #6943
=> Improve get auth chain difference algorithm.

changelog.d/7104.misc, synapse/app/_base.py, synapse/app/homeserver.py
This should be safe to do on all workers/masters because it is guarded by
a config option which will ensure it is only actually done on the worker
assigned as a pusher.
Hopefully fixes #7075.
=> Move pusherpool startup into _base.setup

changelog.d/7106.feature, synapse/push/pusherpool.py
add a lock to try to make this metric actually work
=> Fix concurrent modification errors in pusher metrics

changelog.d/7010.misc, synapse/app/generic_worker.py, synapse/replication/slave/storage/devices.py, synapse/replication/tcp/streams/_base.py, synapse/storage/data_stores/main/__init__.py, synapse/storage/data_stores/main/devices.py, tests/storage/test_devices.py
See commits for more details.
Broadly, this is apply a bit of sanity to things, and will allow us to clean up the replication stream code that has to deal with queries that can't be limited.
~~Based on #7018.~~
=> Change device list streams to have one row per ID

changelog.d/7089.bugfix, synapse/federation/federation_base.py, synapse/federation/federation_client.py, synapse/federation/federation_server.py
Per the conversation at https://github.com/matrix-org/synapse/pull/7026#discussion_r388975243, this fixes the typing issue found with mypy that was introduced in f84700fba8cd9345d7a1a025462c7f8650f27386.
The `room_version` variable is now consistently a `RoomVersion` instead of sometimes a `RoomVersion` and sometimes a `str`.
=> Fix a typing issue in the federation client code found with mypy

changelog.d/7110.misc, synapse/rest/media/v1/media_repository.py, synapse/rest/media/v1/preview_url_resource.py, synapse/rest/media/v1/thumbnail_resource.py
Partially converts the `synapse.rest.media` to async/await. (It doesn't do `synapse.rest.media.v1.media_storage` or `_base` -- those are a bit more complicated as far as I can tell.)
=> Convert some of the media REST code to async/await

changelog.d/7011.misc, synapse/handlers/presence.py, synapse/handlers/typing.py, synapse/replication/tcp/resource.py, synapse/replication/tcp/streams/_base.py, synapse/storage/data_stores/main/devices.py, synapse/storage/data_stores/main/end_to_end_keys.py, synapse/storage/data_stores/main/presence.py
This makes the replication streams implementation simpler.
Based on #7010.
=> Remove concept of a non-limited stream.

changelog.d/7115.misc, synapse/rest/client/v1/login.py, synapse/rest/client/v2_alpha/auth.py
I spun these changes out of #7102 since they're not really related to that and that diff is larger than I'd like (and it isn't done yet).
Two changes:
* De-duplicates some code in the auth REST code.
* Removes a couple of unused properties from the login REST code (these were added in b2bd54a2e31d9a248f73fadb184ae9b4cbdb49f9, but then the uses were factored out in 65c73cdfec1876a9fec2fd2c3a74923cd146fe0b).
=> Clean-up some auth/login REST code

changelog.d/7009.feature, synapse/rest/media/v1/download_resource.py
This patch sets the [Referrer Policy header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy) to `no-referrer` for media downloads. This is done in order to avoid leaking the download URL to third party servers when a document contains hyperlinks and a user clicks on them.
=> Set Referrer-Policy to no-referrer for media

changelog.d/7117.bugfix, synapse/app/generic_worker.py, synapse/replication/tcp/streams/__init__.py
`groups` != `receipts`
Introduced in #2378
=> Fix processing of `groups` stream, and use symbolic names for streams

changelog.d/7116.misc, synapse/app/generic_worker.py, synapse/federation/send_queue.py, synapse/replication/tcp/streams/_base.py, synapse/replication/tcp/streams/federation.py, tests/replication/tcp/streams/test_receipts.py
This just helps keep the rows closer to their streams, so that it's easier to
see what the format of each stream is.
=> Convert `*StreamRow` classes to inner classes

changelog.d/7109.bugfix, synapse/handlers/message.py
Per the clarification in the spec (see https://github.com/matrix-org/matrix-doc/pull/2432#issuecomment-601242488) the situation of an alias not existing should be treated the same as an alias that points to the wrong room.
Fixes #7105
See updated SyTests: matrix-org/sytest#837
=> Update the error code when a canonical alias that does not exist is used

changelog.d/6634.bugfix, synapse/rest/client/v1/login.py
Build the same service URL when requesting the CAS ticket and when calling the proxyValidate URL.
<strike>This now of course breaks the CAS-related tests.</strike>
The fixed tests are in https://github.com/matrix-org/sytest/pull/829
Fixes #2639 
Signed-off-by: Erik <erik.gto@googlemail.com>
=> Fix CAS redirect url

changelog.d/7120.misc, docs/log_contexts.md, synapse/crypto/keyring.py, synapse/federation/federation_base.py, synapse/handlers/sync.py, synapse/http/request_metrics.py, synapse/logging/_structured.py, synapse/logging/context.py, synapse/logging/scopecontextmanager.py, synapse/storage/data_stores/main/events_worker.py, synapse/storage/database.py, synapse/util/metrics.py, synapse/util/patch_inline_callbacks.py, tests/crypto/test_keyring.py, tests/http/federation/test_matrix_federation_agent.py, tests/http/federation/test_srv_resolver.py, tests/http/test_fedclient.py, tests/rest/client/test_transactions.py, tests/unittest.py, tests/util/caches/test_descriptors.py, tests/util/test_async_utils.py, tests/util/test_linearizer.py, tests/util/test_logcontext.py, tests/utils.py
This is a series of commits aimed at cleaning up a bit of stuff around `LoggingContext`.
The first couple are the big ones; they move `Sentinel`, `current_context` and `set_context` out to the top level. Mostly this means that I can more easily trace what's actually referring to `LoggingContext` itself, but I think it's generally neater.
The other two are simple enough and hopefully speak for themselves.
=> Clean up some LoggingContext stuff

changelog.d/7133.bugfix, synapse/app/generic_worker.py
This is a bit of a hacky fix, but will do for now. Branch is based off of master, so we can do a hotfix if we want to.
Fixes #7130.
=> Fix starting workers when federation sending not split out.

changelog.d/7068.bugfix, synapse/handlers/auth.py, synapse/rest/client/v2_alpha/account.py, synapse/rest/client/v2_alpha/devices.py, synapse/rest/client/v2_alpha/keys.py, synapse/rest/client/v2_alpha/register.py, tests/rest/client/v2_alpha/test_auth.py, tests/test_terms_auth.py
This is my attempt to fix:
>  make sure that UI-Auth sessions are tied to a single request (ie, the client can't change its mind about what it's asking for in the middle of a session)
The general idea is to store some additional information in the session about what is being authenticated (namely the URI, the method, and the data associated with whatever operation is being performed). So at each stage in when we check the status of the user interactive authentication session we ensure that the event being authenticated for has not been modified.
~~This isn't fully finished, but I wanted to put this up and get some feedback.~~
Part of #5667 
~~Currently based on #7063.~~
=> Validate that a UI-Auth session is not being reused

changelog.d/7136.misc, synapse/handlers/cas_handler.py, synapse/rest/client/v1/login.py, synapse/server.py, tox.ini
This refactors the CAS code to move the logic to a separate handler class. It somewhat takes the `SSOAuthHandler` and the logic of each of the servlets and combines them into a `CasHandler` class that is analogous to `SamlHandler`.
It also adds typing information to the various CAS methods.
Based on feedback in https://github.com/matrix-org/synapse/pull/7102#discussion_r397086662
=> Refactor the CAS code to move the logic to a handler

changelog.d/7151.bugfix, synapse/handlers/saml_handler.py
Allow custom SAML handlers to redirect after processing an auth response.
Fixes #7149
=> Allow RedirectResponse in SAML response handler

changelog.d/7155.bugfix, synapse/storage/engines/sqlite.py
Fixes: #7127
Signed-off-by: David Vo <david@vovo.id.au>
=> Only import sqlite3 when type checking

changelog.d/7150.bugfix, synapse/rest/client/v2_alpha/room_keys.py, synapse/storage/data_stores/main/e2e_room_keys.py
Fixes: https://github.com/matrix-org/synapse/issues/6977
Also tells the user whether they're missing the `version` query parameter instead of 500'ing (this confused me for a bit while testing).
I'm not sure how [this sytest](https://github.com/matrix-org/sytest/blob/aee12f9414e5b36cba569e3ca0220e8e2f995329/tests/41end-to-end-keys/07-backup.pl#L225) didn't catch this initially though.
=> Ensure is_verified on /_matrix/client/r0/room_keys/keys is a boolean

changelog.d/7153.feature, docs/sample_config.yaml, synapse/config/sso.py, tests/rest/client/v1/test_login.py
That fallback sets the redirect URL to itself (so it can process the login token then return gracefully to the client). This would make it pointless to ask the user for confirmation, since the URL the confirmation page would be showing wouldn't be the client's.
=> Always whitelist the login fallback for SSO

changelog.d/7152.feature, synapse/static/client/login/index.html, synapse/static/client/login/js/login.js
* Don't show the login forms if we're currently logging in with a
password or a token.
* Submit directly the SSO login form, showing only a spinner to the
user, in order to eliminate from the clunkiness of SSO through this
fallback.
=> Improve the UX of the login fallback when using SSO

INSTALL.md, changelog.d/6892.doc
replace python3-virutalenv by virutalenv as the latter provides the command
=> update debian installation instructions to recommend installing `virtualenv` instead of `python3-virtualenv`

changelog.d/7147.doc, docs/dev/cas.md, docs/dev/saml.md
This adds some documentation about running a local CAS server and hooking Synapse up to it. The docs are based on [our SAML docs](https://github.com/matrix-org/synapse/blob/229eb81498b0fe1da81e9b5b333a0285acde9446/docs/dev/saml.md). CAS is more annoying than SAML since Synapse needs to directly talk to the CAS server, so you can't do a lot of the stuff that samling does.
This uses a pretty simple package I found. I also pushed a git repo that has everything configured (which simplifies the configuration a bit): https://github.com/clokep/cas-test -- not sure if it is worth pointing to that or not though.
Here's the [rendered version](https://github.com/matrix-org/synapse/blob/clokep/cas-docs/docs/dev/cas.md).
This also makes a tweak to our SAML docs to note another parameter that must be …
=> Add developer documentation for running a local CAS server

INSTALL.md
In particular, we depend on `typing.TYPE_CHECKING`, which is only present in
3.5.2.
It turns out that Ubuntu Xenial, despite having a package called `python 3
(3.5.1-3)`, actually has python 3.5.2, so I think this is fine.
=> Attempt to clarify Python version requirements

changelog.d/7157.misc, tests/app/test_frontend_proxy.py, tests/app/test_openid_listener.py, tests/federation/test_complexity.py, tests/federation/test_federation_sender.py, tests/handlers/test_register.py, tests/rest/client/v2_alpha/test_register.py, tests/rest/key/v2/test_remote_key_resource.py, tests/server_notices/test_resource_limits_server_notices.py, tests/test_terms_auth.py, tests/unittest.py
This starts with a change to remove the somewhat spurious "name" parameter to `default_config`. It's a separate commit to help with review.
=> Add tests for outbound device pokes

changelog.d/7160.feature, synapse/handlers/device.py, synapse/handlers/sync.py
This will allow clients to notify users about new devices even if
the user isn't in any rooms (yet).
=> Always send the user updates to their own device list

changelog.d/7128.misc, docs/tcp_replication.md, synapse/app/generic_worker.py, synapse/replication/tcp/client.py, synapse/replication/tcp/commands.py, synapse/replication/tcp/protocol.py, synapse/replication/tcp/resource.py, synapse/server.py, synapse/server.pyi
Each tcp replication connection is assigned a "conn_id", which is used
to give an ID to a remotely connected worker. In a redis world, there
will no longer be a one to one mapping between connection and instance,
so instead we need to replace such usages with an ID generated by the
remote instances and included in the replicaiton commands.
Based on #7024
=> Remove usage of "conn_id" for presence.

changelog.d/7171.doc, docs/sample_config.yaml, synapse/config/metrics.py
=> Fix a small typo in the `metrics_flags` config option.

changelog.d/7157.misc, changelog.d/7159.bugfix, synapse/handlers/federation.py, synapse/storage/data_stores/main/devices.py, synapse/util/stringutils.py, tests/app/test_frontend_proxy.py, tests/app/test_openid_listener.py, tests/federation/test_complexity.py, tests/federation/test_federation_sender.py, tests/handlers/test_register.py, tests/rest/client/v2_alpha/test_register.py, tests/rest/key/v2/test_remote_key_resource.py, tests/server_notices/test_resource_limits_server_notices.py, tests/test_terms_auth.py, tests/unittest.py
* make sure we clear out all but one update for the user
* ~~there is no need to delete from `device_lists_outbound_last_success`: sticking with the last successful stream id is fine.~~
Based on #7157.
=> Rewrite prune_old_outbound_device_pokes for efficiency

changelog.d/7178.bugfix, synapse/server.py
If there was an exception setting up one of the attributes of the Homeserver
god object, then future attempts to fetch that attribute would raise a
confusing "Cyclic dependency" error. Let's make sure that we clear the
`building` flag so that we just get the original exception.
Ref: #7169
=> Fix a bug which could cause incorrect 'cyclic dependency' error.

changelog.d/7184.misc, synapse/rest/media/v1/preview_url_resource.py, synapse/storage/data_stores/main/media_repository.py
Fixes #7182
In the case were `removed_media` is an empty list then `delete_url_cache` returns `None`.
Wrapping this in `defer.ensureDeferred` should fix the error, but it does seem silly to call into a method which we know will just return `None` and then wrap that in a `Deferred`, etc. I did consider just moving the modified line down into the `if removed_media` block.
=> Do not try to await None, which can be returned by delete_url_cache.

changelog.d/7177.bugfix, synapse/storage/data_stores/main/devices.py
A possible fix for https://github.com/matrix-org/synapse/issues/7163
I'm not entirely sure what this code is doing, but I know it's incorrect that we're trying to pull a key out of a dictionary all the time, when we're only setting that key sometimes (when `key_json` is truthy).
~~Stopped the exception on Cadair's server (which is expected), however I'm not convinced that this isn't just fixing a symptom of another issue.~~ (@uhoreg seems to think this does the right thing). Considering this code was introduced in 1.11.0 with https://github.com/matrix-org/synapse/pull/6844, but has only been reported with 1.12.0.
=> Only setdefault for signatures if device has key_json

changelog.d/6639.bugfix, synapse/storage/data_stores/main/push_rule.py
Fixes #6636 
Signed-off-by: Karl Linderhed <git@karlinde.se>
=> Fill in the 'default' field for user-defined push rules

changelog.d/7181.misc, synapse/http/site.py, synapse/logging/context.py
=> Fix "'NoneType' has no attribute start|stop" logcontext errors

changelog.d/7167.doc, docs/turn-howto.md
Public IP seems to be a fixed requirement, and not mentioning it in the docs is guaranteed to have people waste their time on setups which will never work.
Signed-off-by: Jostein Kjønigsen <jostein@kjonigsen.net>
=> Improve TURN documentation.

changelog.d/7195.misc, synapse/replication/tcp/resource.py
This broke in a recent PR (#7024) and is no longer useful due to all
replication clients implicitly subscribing to all streams, so let's
just remove it.
Fixes #7189
=> Remove connections per replication stream metric.

changelog.d/7191.feature, synapse/handlers/directory.py, tests/handlers/test_directory.py
This fixes #7052 by allowing server admins to create aliases even when not in the room.
=> Allow admins to create aliases when they are not in the room

CHANGES.md, changelog.d/7102.feature, synapse/api/constants.py, synapse/handlers/auth.py, synapse/handlers/saml_handler.py, synapse/res/templates/sso_auth_confirm.html, synapse/rest/client/v2_alpha/account.py, synapse/rest/client/v2_alpha/auth.py, synapse/rest/client/v2_alpha/devices.py, synapse/rest/client/v2_alpha/keys.py, synapse/rest/client/v2_alpha/register.py
This aims to accomplish a portion of #5667:
* Update `validate_user_via_ui_auth` to return `m.login.sso` for homeservers which use sso login
* Implement a handler for `/_matrix/client/r0/auth/m.login.sso/fallback/web` which shows a confirmation page, and redirects to the SAML server.
* Update the SAML return page handlers to behave differently for a UI auth flow, and:
* Update the UI Auth session
* Return the fallback completion page
~~This is currently based on #7115.~~
I was testing SAML by first generally following the directions at [docs/dev/saml.md](https://github.com/matrix-org/synapse/blob/master/docs/dev/saml.md) to create a user. Note that I also had to set the following in the config:
```yaml
public_baseurl: http://localhost:8080/
```
Then to test the UI Auth workflow:
1. Add a …
=> Support SAML in the user interactive authentication workflow.

changelog.d/7212.misc, debian/changelog, debian/rules, synapse/python_dependencies.py
I believe this will fix #7208.
=> Update debian build scripts for Pillow 7.1.1.

changelog.d/7158.misc, synapse/storage/data_stores/main/devices.py, tests/federation/test_federation_sender.py
Occasionally we could get a federation device list update transaction which  looked like:
```
[
{'edu_type': 'm.device_list_update', 'content': {'user_id': '@user:test', 'device_id': 'D2', 'prev_id': [], 'stream_id': 12, 'deleted': True}},
{'edu_type': 'm.device_list_update', 'content': {'user_id': '@user:test', 'device_id': 'D1', 'prev_id': [12], 'stream_id': 11, 'deleted': True}},
{'edu_type': 'm.device_list_update', 'content': {'user_id': '@user:test', 'device_id': 'D3', 'prev_id': [11], 'stream_id': 13, 'deleted': True}}
]
```
Having `stream_ids` which are lower than `prev_ids` looks odd. It might work (I'm not actually sure), but in any case it doesn't seem like a reasonable thing to expect other implementations to support.
~~Based on #7157.~~
=> Fix device list update stream ids going backward

changelog.d/7203.bugfix, synapse/app/generic_worker.py
By running this stuff with `run_in_background`, it won't be correctly reported
against the relevant CPU usage stats.
Fixes #7202
=> Remove some `run_in_background` calls in replication code

changelog.d/7190.misc, synapse/storage/background_updates.py, synapse/storage/prepare_database.py, synapse/storage/schema/delta/58/00background_update_ordering.sql, tests/storage/test_background_update.py, tests/unittest.py
The intention here is to avoid SNAFUs like https://github.com/matrix-org/synapse/issues/6923 and https://github.com/matrix-org/synapse/issues/7065 which are basically caused by us not thinking hard enough about whether it is safe to run particular background updates in a particular order.
I'm adding an `ordering` column to the `background_updates` table, which we should try to populate for future updates, and which will define the order that background updates are performed.
There are a few preparatory changes here; see the individual commits.
=> Only run one background update at a time

changelog.d/7183.misc, synapse/logging/context.py
Let's just call `getrusage` once on each logcontext change, rather than twice.
There's two benefits to this:
* optimisation: fewer syscalls
* less cpu time lost down the cracks between logcontexts.
=> Reduce the number of calls to `resource.getrusage`

changelog.d/7188.misc, synapse/api/errors.py
Fixes https://github.com/matrix-org/synapse/issues/7017
This PR fixes a bug where `http.HTTPStatus` objects were printed (whose representation is a str) into logs, showing something like `HTTPStatus.FORBIDDEN` instead of `403`.
This was inconsistent with other log lines and thus made writing log parsers a bit more painful than necessary.
This PR changes any `CodeMessageException` given an `http.HTTPStatus` object will convert it to its integer equivalent when it's instantiated.
=> Convert http.HTTPStatus objects to their int equivalent

changelog.d/7006.feature, docs/sample_config.yaml, synapse/app/homeserver.py, synapse/config/server.py
The goal of this PR is to improve the situation in which running both homeserver and webclient on the same hostname is [discouraged](https://github.com/matrix-org/synapse#security-note) and at the same time made easy by the `web_client_location` option. The option is extended to allow redirecting to absolute URL and warning is printed when this is not the case.
I'm not at all familiar with the codebase or twisted so please review carefully. It is also quite possible that different approach would be better to resolve this problem.
See also vector-im/riot-web#1977
- Use markdown where …
=> Extend web_client_location to handle absolute URLs

changelog.d/7186.feature, synapse/handlers/auth.py, synapse/handlers/cas_handler.py, synapse/rest/client/v1/login.py, synapse/rest/client/v2_alpha/auth.py
This is part of #5667, it adds support for CAS into the user-interactive authentication by building on the work done in #7102. The general flow is the same as #7102, but using the CAS code instead of SAML. One difference is that a new endpoint is used for CAS (where SAML has to re-use the same endpoint), this simplifies code slightly. 
See sytests at matrix-org/sytest#845
=> Support CAS in UI Auth flows.

changelog.d/7199.bugfix, synapse/server_notices/resource_limits_server_notices.py, synapse/server_notices/server_notices_manager.py, tests/server_notices/test_resource_limits_server_notices.py
Fixes #6815
Before figuring out whether we should alert a user on MAU, we call `get_notice_room_for_user` to get some info on the existing server notices room for this user. This function, if the room doesn't exist, creates it and invites the user in it. This means that, if we decide later that no server notice is needed, the user gets invited in a room with no message in it. This happens at every restart of the server, since the room ID returned by `get_notice_room_for_user` is cached.
This PR fixes that by moving the inviting bit to a dedicated function, that's only called when the server actually needs to send a notice to the user. A potential issue with this approach is that the room that's created by `get_notice_room_for_user` doesn't match how that same function looks for an …
=> Server notices: Dissociate room creation/lookup from invite

changelog.d/7185.misc, synapse/app/admin_cmd.py, synapse/app/generic_worker.py, synapse/replication/tcp/__init__.py, synapse/replication/tcp/client.py, synapse/replication/tcp/handler.py, synapse/replication/tcp/protocol.py, synapse/server.py, synapse/server.pyi, tests/replication/slave/storage/_base.py, tests/replication/tcp/streams/_base.py, tests/replication/tcp/streams/test_receipts.py
The aim here is to move the command handling out of the TCP protocol classes and to also merge the client and server command handling (so that we can reuse them for redis protocol). This PR simply moves the client paths to the new `ReplicationCommandHandler`, a future PR will move the server paths too.
The commits should explain what's going on at each step.  "Add ReplicationCommandHandler" and "Merge replication command and client handlers" should mostly just be c+p.
Replaces #7134.
=> Move client command handling out of TCP protocol

changelog.d/7207.misc, synapse/storage/data_stores/main/stream.py
I noticed these debug log lines. They were added in 2016 and seemed a bit useless, but let me know if anyone actually uses them for debugging.
=> Remove stream before/after debug log lines

changelog.d/7187.misc, synapse/replication/tcp/handler.py, synapse/replication/tcp/protocol.py, synapse/replication/tcp/resource.py
This completes the merging of server and client command processing.
Based on #7185.
=> Move server command handling out of TCP protocol

changelog.d/7226.misc, synapse/replication/tcp/handler.py, synapse/replication/tcp/streams/_base.py, synapse/storage/data_stores/main/push_rule.py
Fixes a race between handling `POSITION` and `RDATA` commands. We do this by simply linearizing handling of them.
Also hopefully fixes exceptions described in https://github.com/matrix-org/synapse/issues/7206#issuecomment-608001475.
Broke in #7024.
=> Fix race in replication

changelog.d/7235.bugfix, synapse/static/client/login/js/login.js
This would cause the SSO login form to not show up, making it impossible to auth via SSO through the login fallback if SSO isn't the only authentication option the HS offers.
=> Fix typo in the login fallback javascript

changelog.d/7241.misc, synapse/storage/data_stores/main/media_repository.py
Fixes another instance from #7182. Uses the same fix as #7184.
=> Convert delete_url_cache_media to async/await.

changelog.d/7329.misc, synapse/replication/tcp/commands.py, synapse/replication/tcp/handler.py, synapse/replication/tcp/protocol.py
One per commit:
* Remove vestigal references to SYNC replication command
We've ripped pretty much all of this out: let's remove the remains.
* Fix warnings about not calling superclass constructor
Separate `SimpleCommand` from `Command`, so that things which don't want to use the `data` property don't have to, and thus fix the warnings PyCharm was giving me about not calling `__init__` in the base class.
* Handle one-word replication commands correctly
`REPLICATE` is now a valid command, and it's nice if you can issue it from the console without remembering to call it `REPLICATE ` with a trailing space.
=> Miscellaneous cleanups to replication code

changelog.d/7193.misc, synapse/storage/data_stores/main/client_ips.py, synapse/storage/data_stores/main/devices.py, synapse/storage/data_stores/main/schema/delta/58/02remove_dup_outbound_pokes.sql, synapse/storage/database.py, tests/storage/test_database.py
We seem to have some duplicates, which could do with being cleared out.
~~Based on #7190.~~
=> bg update to clear out duplicate outbound_device_list_pokes

changelog.d/7238.doc, docs/password_auth_providers.md, docs/sample_config.yaml, synapse/config/password_auth_providers.py
Sooo... I just watched someone trying to set up Synapse's LDAP support but getting stuck with not knowing that they needed to install [matrix-synapse-ldap3](https://github.com/matrix-org/matrix-synapse-ldap3) to actually get things working.
During so I also realized that the `password_providers` config option has zero documentation in the sample config.
So in an attempt to solve both of these problems I added some docs to the option and pointed people to the password provider auth module docs, which now have to link to known implementations in there, which includes a link to the LDAP3 module.
If there are other known implementations we can add, please suggest them.
This PR also changes `password_providers` such that it's uncommented by default, in accordance with our doc writing... docs: …
=> Add documentation to password_providers config option

changelog.d/7233.misc, synctl
We pass --daemonize on the commandline, which (since at least #4853) overrides
whatever the config file, so there is no need for it to be set in the config
file.
=> Remove redundant checks on `daemonize` from synctl

changelog.d/7237.misc, synapse/static/client/login/js/login.js, synapse/static/client/register/js/register.js
Perform a `console.warn` instead of `console.log` when informing the user they need to replace the stub.
Just makes things jump out a bit more.
=> Make it clearer to the user that they haven't overridden onLogin/Register

changelog.d/7249.bugfix, synapse/config/_base.py
I don't really remember why this was so complicated; I think it dates
back to the time when we had to instantiate the Config classes before
we could call `add_arguments` - ie before #5597. In any case, I don't
think there's a good reason for it any more, and the impact of it
being complicated is that `--help` doesn't work correctly.
=> Fix --help commandline argument

.buildkite/worker-blacklist, changelog.d/7228.misc
Tests in `tests/30rooms/60version_upgrade.pl` for worker mode doesn't seem to be flaky locally.
Let's try unblacklisting it.
=> Unblacklist /upgrade creates a new room

changelog.d/7248.doc, docs/password_auth_providers.md
I found another one!
Updates #7238 to add another example of a password provider auth module: https://github.com/devture/matrix-synapse-shared-secret-auth/
=> Add matrix-synapse-shared-secret-auth as an example password provider

changelog.d/7260.bugfix, synapse/handlers/room.py
Check on room creation if the user is allowed to publish the room to the room directory. See #7204 
`Signed-off-by: Peer Diestelhorst <signoff@spy.de>`
=> Check publishing permissions

changelog.d/7251.doc, docs/reverse_proxy.md
Nginx defaults to only allow file uploads up to 1MB while synapse allows up to 10MB by default. Added a line to the nginx configuration to increase the limit with a note about how to use the setting and having a default value to match synapse's default.
Signed-off-by: Ryan Hovland <ryan@procycle.us>
=> Add setting to nginx configuration to allow larger file uploads

changelog.d/7255.bugfix, synapse/handlers/e2e_keys.py
Fixes https://github.com/matrix-org/synapse/issues/7252
=> Only register devices edu handler on the master process

changelog.d/7274.bugfix, synapse/storage/data_stores/main/event_federation.py
We could end up looking up tens of thousands of events, which could cause large
amounts of data to be logged to the postgres log.
=> Fix a potentially-huge sql query

CHANGES.md, UPGRADE.rst
Fixes #7144.
Note that this PR is made against master, since it's updating documentation for an earlier release.
=> Add some warnings and notes about slow upgrade

changelog.d/7265.feature, docs/sample_config.yaml, synapse/config/repository.py, synapse/rest/media/v1/preview_url_resource.py, tests/rest/media/v1/test_url_preview.py
Addresses: https://github.com/matrix-org/synapse/issues/3037
Adds a config option that allows server operates to specify their preferred language when generating URL previews.
Should hopefully help fix URL previews from YouTube being in a foreign language.
Details on the Accept-Language HTTP header: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language
=> Allow specifying the value of Accept-Language header for URL previews

CHANGES.md, changelog.d/7259.bugfix
I should have updated `CHANGES.md` in #7240 to mention the additional new template. We should also mention changes to the `ModuleApi` made in that PR.
=> Add notes to the changelog about new templates and module API changes from #7240.

changelog.d/7261.misc, synapse/handlers/auth.py, synapse/handlers/device.py, synapse/handlers/register.py, synapse/handlers/set_password.py, synapse/module_api/__init__.py, tests/api/test_auth.py, tests/handlers/test_auth.py, tests/handlers/test_register.py, tests/utils.py
While working on #6705 I think some methods need to be made async, I figured this was a good opportunity to convert the `AuthHandler` to async/await. It got a little bit bigger than I expected, but is reasonable, I think.
Any uses of the async/await outside of `AuthHandler` I wrapped in `ensureDeferred`.
I'm not fully confident on the changes to the tests (wrapping each call in `ensureDeferred`).
=> Convert auth handler to async/await

changelog.d/7290.misc, synapse/replication/tcp/streams/_base.py
Some of the query functions return generators rather than lists, so we can't
index into the result. Happily we already have a copy of the results.
(think this was introduced in #7024)
=> Fix 'generator object is not subscriptable' error

changelog.d/7271.bugfix, synapse/push/push_rule_evaluator.py, tests/push/test_push_rule_evaluator.py, tox.ini
This fixes #6641 by treating display names as normal strings, not globs.
* I added an additional commit which expands the cache to handle non-globbed content.
* I tested this usually notifications in Riot.
=> Do not treat display names as globs for push rules.

changelog.d/7272.doc, docs/sample_config.yaml, synapse/config/repository.py
Update the comments for the generated configuration.
Taken from line 46-48:
https://github.com/matrix-org/synapse/blob/9dfcf47e9bb323f0597ebf8f34a1bcc9f14a02a1/synapse/config/repository.py#L46-L48
=> Fixup media_storage_providers options comments

docs/turn-howto.md
Should use quotes for turn_shared_secret value, or it will not work
Me and my firends met same problem on this spot. When  you are not familiar with software it is difficult to find why it does not work, when there are no quotes there...
=> Improve example TURN configuration

changelog.d/7291.misc, synapse/replication/tcp/streams/__init__.py, synapse/replication/tcp/streams/_base.py, synapse/replication/tcp/streams/events.py, synapse/replication/tcp/streams/federation.py
The general idea here is to get rid of the `type: ignore` annotations on all of the `current_token` and `update_function` assignments, which would have caught #7290.
After a bit of experimentation, it seems like the least-awful way to do this is to pass the offending functions in as parameters to the `Stream` constructor. Unfortunately that means that the concrete implementations no longer have the same constructor signature as `Stream` itself, which means that it gets hard to correctly annotate `STREAMS_MAP`.
I've also introduced a couple of new types, to take out some duplication.
=> Improve type checking in `replication.tcp.Stream`

changelog.d/7213.misc, snap/snapcraft.yaml
A small change to explicitly add required Python build tools to the snapcraft metadata.
This resolves an issue where setuptools-scm and wheel were not being installed during building of the Snap due to recent changes.
Adding pip, setuptools, setuptools-scm and wheel ensures these required tools are available now and in the future regardless of changes to Python requirements or the snapcraft tooling.
=> Add explicit python build tools to snapcraft

CHANGES.md, changelog.d/7279.feature, synapse/config/sso.py, synapse/handlers/auth.py, synapse/res/templates/sso_auth_success.html, synapse/rest/client/v2_alpha/auth.py
This fixes a bug from #7102 -- the steps in the SSO authentication flow have customizable templates, except the success template, which was re-used from the fallback authentication flow.
This breaks that dependency and adds a new template for a successful SSO authentication. As part of this I moved the `SUCCESS_TEMPLATE` back to where it used to belong.
I filed #7280 about treating templates better.
=> Use a template for the SSO success page to allow for customization.

changelog.d/7286.misc, synapse/replication/tcp/handler.py, synapse/util/caches/stream_change_cache.py
Other parts of the code (such as the StreamChangeCache) assume that there will
not be multiple changes with the same stream id.
This code was introduced in #7024, and I hope this fixes #7206.
=> On catchup, process each row with its own stream id

changelog.d/7268.bugfix, synapse/handlers/auth.py
This makes a tweak to the way that UI Auth sessions get created that I think will be necessary to persist UI Auth sessions (for #6705). UI auth sessions are now created explicitly when no session ID is provided (i.e. at the beginning of a UI auth negotiation).
This does have a change of behavior that clients might notice, but I think being stricter here avoids an abuse channel. Instead of lazily creating sessions if the UI Auth session is unknown (e.g. if the session ID is not found) this will now error with an unknown session.
As far as I can tell the [result is unspecced when an unknown session ID](https://matrix.org/docs/spec/client_server/r0.6.0#user-interactive-authentication-api) is provided, so the previous behavior was being generous, but does not need to be supported.
=> Explicitly create UI Auth sessions

changelog.d/7311.doc, docs/workers.md, synapse/app/generic_worker.py, synapse/rest/client/v2_alpha/account_data.py
fixes #7309 
tests at https://github.com/matrix-org/sytest/pull/855
=> Support GET account_data requests on a worker

changelog.d/7321.misc, synapse/http/matrixfederationclient.py
When we successfully transmit over federation we log the following lines:
```
2020-04-21 00:00:25,111 - synapse.http.matrixfederationclient - 442 - INFO - federation_transaction_transmission_loop-15561448 - {PUT-O-13904925} [matrix.hostname] Got response headers: 200 OK
2020-04-21 00:00:25,111 - synapse.http.matrixfederationclient - 164 - INFO - federation_transaction_transmission_loop-15561448 - {PUT-O-13904925} [matrix.hostname] Completed: 200 OK
2020-04-21 00:00:25,112 - synapse.federation.sender.transaction_manager - 150 - INFO - federation_transaction_transmission_loop-15561448 - TX [matrix.hostname] {1587140000000} got 200 response
```
Looking at this, we are logging the same data three different ways, during the successful flow. Only about 0.5% of these log lines do not contain …
=> Reduce federation logging on success

changelog.d/7295.misc, synapse/rest/media/v1/preview_url_resource.py
This task runs every 10s, so log at info only if media/urls removed, as low-volume homeservers will be very verbose for little benefit otherwise.
We already skip the "deleted X entries" line if it's zero length.
While setting log level to 'WARN' for this class could also be done, that simply silences the entire process, providing no mix of visibility between no-op actions and actions that did something.
=> Reduce verbosity of URL cache cleanup.

changelog.d/7318.misc, docs/tcp_replication.md, synapse/api/constants.py, synapse/app/generic_worker.py, synapse/handlers/events.py, synapse/handlers/initial_sync.py, synapse/handlers/presence.py, synapse/replication/tcp/commands.py, synapse/replication/tcp/handler.py, synapse/server.pyi
Long story short: if we're handling presence on the current worker, we shouldn't be sending USER_SYNC commands over replication.
In an attempt to figure out what is going on here, I ended up refactoring some bits of the presencehandler code, so the first 4 commits here are non-functional refactors to move this code slightly closer to sanity. (There's still plenty to do here :/). Suggest reviewing individual commits.
Fixes (I hope) #7257.
=> Stop the master relaying USER_SYNC for other workers

changelog.d/7315.feature, docs/sample_config.yaml, synapse/config/server.py, synapse/rest/client/v2_alpha/account.py, synapse/rest/client/v2_alpha/register.py, tests/rest/client/v2_alpha/test_account.py, tests/rest/client/v2_alpha/test_register.py
Adds a `request_token_inhibit_errors` configuration flag (disabled by default) which, if enabled, change the behaviour of all `/requestToken` endpoints so that they return a 200 and a fake `sid` if the 3PID was/was not found associated with an account (depending on the endpoint), instead of an error.
=> Config option to inhibit 3PID errors on /requestToken

changelog.d/7337.bugfix, synapse/replication/http/streams.py, synapse/replication/tcp/streams/_base.py, synapse/replication/tcp/streams/events.py, synapse/storage/data_stores/main/events_worker.py
The problem here was that the EventsStream update function could return more rows than was requested of it, which was then upsetting the `db_query_to_update_function` wrapper which didn't know how to handle this. The confusion over whether the limit was a limit or a target was introduced in #7024, but I think there are much longer-standing bugs here in the limit logic.
So, part of the fix here is to make it clear that the limit passed into the `update_function` is a target rather than a hard limit, and to avoid using `db_query_to_update_function` which is too simple for this usecase. But to get it right, we need to pull `get_ex_outlier_stream_rows` out to a separate query (to make it easier to see if we have hit the limit), and apply more intelligence about how we truncate the results …
=> Fix assertions being thrown by the EventsStream update function

changelog.d/7338.misc, synapse/handlers/federation.py
This converts some of the federation handler methods to async/await. Those not converted are called by `inlineCallbacks` code still.
=> Convert some of the federation handler methods to async/await.

changelog.d/7343.feature, docs/sample_config.yaml, synapse/config/sso.py
This adds documentation to the sample config for the templates added in the various SSO PRs.
This essentially adds the information from #7279 into a more permanent space for someone setting up a new homeserver. It expands some wonderful docs written by @babolivier.
=> Add documentation to the sample config about the templates for SSO.

changelog.d/7341.bugfix, synapse/config/_base.py
If the admin adds a `.yaml` file that's either empty or doesn't parse into a dict to a config directory (e.g. `conf.d` for debs installs), stuff like https://github.com/matrix-org/synapse/issues/7322 would happen. This PR checks that the file is correctly parsed into a dict, or ignores it with a warning if it parses into any other type (including `None` for empty files).
Fixes https://github.com/matrix-org/synapse/issues/7322
=> Don't crash when one of the configuration files is empty

changelog.d/7091.doc, docs/application_services.md
Signed-off-by: Simon Körner <git@lubiland.de>
This PR does not touch code, are linters and changelog still neccessary?
=> Add some explanation to application_services.md

changelog.d/7357.doc, docs/metrics-howto.md
It doesn't seem to be documented anywhere and means that you suddenly start losing metrics without any obvious reason when you go from monolith to workers (e.g. #7312).
=> Document monitoring workers

changelog.d/7344.bugfix, synapse/groups/attestations.py
We need to wait for the renewals to finish, so that the metrics are correctly
reported.
=> Fix incorrect metrics reporting for renew_attestations

changelog.d/7146.misc, synapse/app/generic_worker.py, synapse/replication/tcp/resource.py
Currently we never write to streams from workers, but that will change soon
=> Run replication streamers on workers

changelog.d/7359.misc, tests/utils.py
When running the UTs against a postgres database, we need to set the collation
correctly.
=> Fix collation for postgres for unit tests

changelog.d/7278.misc, tests/replication/tcp/streams/_base.py, tests/replication/tcp/streams/test_typing.py
Specifically some tests for the typing stream, which means we test streams that fetch missing updates via HTTP (rather than via the DB).
We also shuffle things around a bit so that we create two separate `HomeServer` objects, rather than trying to insert a slaved store into places.
Note: `test_typing.py` is heavily inspired by `test_receipts.py`
=> Add some replication tests

changelog.d/6881.misc, docs/admin_api/user_admin_api.rst, synapse/rest/admin/users.py, synapse/storage/data_stores/main/__init__.py, tests/rest/admin/test_user.py, tests/storage/test_main.py
=> Return total number of users and profile attributes in admin users endpoint

changelog.d/7361.doc, docs/admin_api/user_admin_api.rst
Hopefully makes the docs a bit easier for sysadmins to understand.
=> Clean up admin api docs

changelog.d/7316.bugfix, synapse/config/emailconfig.py, synapse/config/registration.py
Config option `account_threepid_delegates.email` is expected to be a URL to a identity server, *including* the protocol scheme (https://).
In part of deprecating `trusted_third_party_id_servers`, we state that if `account_threepid_delegates` has not been set, and `trusted_third_party_id_servers` is, then we use the first value from that list as the value for `account_threepid_delegates.email`.
Unfortunately, values from `trusted_third_party_id_servers` do not have a protocol scheme (ex. `example.com`), where `account_threepid_delegates.email` is expected to have a protocol scheme( ex. `https://example.com`).
So this fallback wouldn't have worked. This patch fixes things to presume `https://` for the URL.
=> Fix fallback value for account_threepid_delegates.email

changelog.d/7358.bugfix, synapse/replication/tcp/handler.py, synapse/replication/tcp/streams/events.py, synapse/server.pyi, synapse/storage/data_stores/main/events_worker.py, tests/replication/tcp/streams/_base.py, tests/replication/tcp/streams/test_events.py, tests/replication/tcp/streams/test_receipts.py, tests/replication/tcp/streams/test_typing.py, tests/rest/client/v1/utils.py, tests/test_utils/__init__.py, tests/test_utils/event_injection.py, tests/unittest.py, tox.ini
As with #7337, this is partly about fixing an assertion which was added recently, but I'm also fixing a much longer-standing bug in the replication catchup logic.
Also adds some tests. The first couple of commits are just some rejigging of the test framework: it might be helpful to review them separately.
=> Fix limit logic for EventsStream

changelog.d/7364.misc, docs/tcp_replication.md, synapse/app/_base.py, synapse/logging/opentracing.py, synapse/replication/tcp/commands.py, synapse/replication/tcp/handler.py, synapse/server.py, synapse/server.pyi, tests/replication/slave/storage/_base.py, tests/replication/tcp/test_commands.py
This is primarily for allowing us to send those commands from workers, but for now simply allows us to ignore echoed RDATA/POSITION commands that we sent (we get echoes of sent commands when using redis). Currently we log a WARNING on the master process every time we receive an echoed RDATA.
The fix to the `test.replication.slave` tests are a bit gut wrenching. I need to port the fix from `tests.replication.tcp` to actually create two separate HS instances.
=> Add instance name to RDATA/POSITION commands

changelog.d/7367.bugfix, synapse/handlers/room_list.py
Fixes: https://github.com/matrix-org/synapse/issues/7366
The `from_federation` parameter determines whether to mutate the `/publicRooms` response based on whether the request is coming from another homeserver or a local client.
Currently this is only used for determining whether to show rooms that are set to not federate. This missing parameter meant that these rooms would be shown to other servers if they providing a filter with their `/publicRooms` query.
Missed in #4736: https://github.com/matrix-org/synapse/pull/4736/files#diff-a78cb67d0a36ffde4ccd3d5c78c25a13R85
=> Apply federation check for /publicRooms with filter list

changelog.d/7378.misc, synapse/replication/tcp/streams/_base.py
Hopefully this is no worse than what we have on master...
This is a mitigation to the assertionerrors in #7340, but I'm still deeply suspicious that we're not doing the right thing here.
=> Workaround for assertion errors from db_query_to_update_function

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/BUG_REPORT.md, README.rst, changelog.d/7377.doc
This PR moves the "support is in #synapse:matrix.org" in the bug report template outside of the comment as some people seem to ignore what's in the comments, and phrase it a bit more like the support request template. It also adds a default issue template that says the same thing. It's also adding a notice about the security disclosure to both the default template and the bug report one.
It also adds a badge to the top of the README that looks like this:
With an alt text saying about the same message if the badge doesn't load (e.g. if matrix.org is slow):
I've opened this PR against master on purpose (for once) because I believe it's a good thing to have this out on master soon.
Fixes #6826
=> Make it clearer that #synapse:matrix.org is our support channel

changelog.d/7368.bugfix, synapse/federation/federation_client.py, synapse/federation/transport/client.py
Improves upon https://github.com/matrix-org/synapse/pull/6899
This PR:
* Adds nice docstrings
* Removes an unnecessary check
* Returns a more descriptive error when we request a private publicRooms list from a remote homeserver.
Why you ask? Well, I noticed the problem on my homeserver and went to fix it, and once done realized I had already fixed this in that other PR, and it still hasn't hit master. Still, the changes here should be useful.
Using the same changelog as the previous PR.
=> Further improvements to requesting the public rooms list on a homeserver which has it set to private

changelog.d/7172.misc, synapse/app/generic_worker.py, synapse/replication/slave/storage/_base.py, synapse/replication/slave/storage/account_data.py, synapse/replication/slave/storage/deviceinbox.py, synapse/replication/slave/storage/devices.py, synapse/replication/slave/storage/events.py, synapse/replication/slave/storage/groups.py, synapse/replication/slave/storage/presence.py, synapse/replication/slave/storage/push_rule.py, synapse/replication/slave/storage/pushers.py, synapse/replication/slave/storage/receipts.py, synapse/replication/slave/storage/room.py, synapse/replication/tcp/client.py, synapse/replication/tcp/handler.py, tests/replication/tcp/streams/_base.py, tests/replication/tcp/streams/test_events.py, tests/replication/tcp/streams/test_receipts.py, tests/replication/tcp/streams/test_typing.py
We move the processing of typing and federation replication traffic into their handlers so that `Stream.current_token()` points to a valid token. This allows us to remove `get_streams_to_replicate()` and `stream_positions()`.
~~Based on #7146~~
=> Use `stream.current_token()` and remove `stream_positions()`

changelog.d/7369.misc, synapse/app/generic_worker.py, synapse/replication/http/_base.py, synapse/replication/http/streams.py, synapse/replication/tcp/client.py, synapse/replication/tcp/handler.py, synapse/replication/tcp/streams/_base.py, synapse/replication/tcp/streams/events.py, synapse/replication/tcp/streams/federation.py, tests/replication/tcp/streams/_base.py, tests/replication/tcp/streams/test_receipts.py, tests/replication/tcp/streams/test_typing.py
For in memory streams when fetching updates on workers we need to query the source of the stream, which currently is hard coded to be master. This PR threads through the source instance we received via `POSITION` through to the update function in each stream, which can then be passed to the replication client for in memory streams.
=> Thread through instance name to replication client.

UPGRADE.rst, changelog.d/7387.bugfix, synapse/storage/data_stores/main/schema/delta/56/stats_separated.sql
`populate_stats_process_rooms` was added in #5971 / v1.4.0; `current_state_events_membership` was added in #5706 / v1.3.0.
Fixes #7380.
=> Wait for current_state_events_membership before populate_stats_process_rooms

changelog.d/7395.misc, synapse/notifier.py
This seemed like an easy win to convert.
=> Convert the synapse.notifier module to async/await.

changelog.d/7394.misc, synapse/server_notices/resource_limits_server_notices.py, tests/server_notices/test_resource_limits_server_notices.py
I noticed while reviewing #7363 that there was only a couple more usages of `inlineCallbacks` in `synapse.server_notices`. I figured it made sense to just finish it up while being somewhat familar with the code.
=> Convert synapse.server_notices to async/await.

changelog.d/7396.misc, synapse/handlers/room.py
I noticed in #7363 that the room handler was almost fully converted to async/await. Figured we should finish the job.
=> Convert the room handler to async/await.

MANIFEST.in, changelog.d/7404.misc
An update of check-manifest shone some light on some issues with `MANIFEST.in`, specifically that we didn't exclude/prune the contrib directory, and that we were using `prune` instead of `exclude` for files. This fixes both issues.
Fixes #7403
---
This broke in `check-manifest` v0.42 ~anoa
=> Fix MANIFEST.in

changelog.d/7374.misc, synapse/federation/send_queue.py, synapse/federation/sender/__init__.py, synapse/federation/sender/per_destination_queue.py, synapse/federation/sender/transaction_manager.py, synapse/replication/tcp/resource.py, synapse/replication/tcp/streams/_base.py, synapse/replication/tcp/streams/federation.py, tests/replication/tcp/streams/_base.py, tests/replication/tcp/streams/test_federation.py, tests/replication/tcp/streams/test_typing.py
looks like we managed to break this during the refactorathon.
=> Fix catchup-on-reconnect for the Federation Stream

changelog.d/7393.bugfix, synapse/events/snapshot.py, tests/events/test_snapshot.py, tests/test_utils/event_injection.py
This caused `prev_state_ids` to be incorrect if the state event was not
replacing an existing state entry.
=> Fix bug in EventContext.deserialize.

changelog.d/7408.misc, synapse/logging/context.py
The [synapse-s3-storage-provider](https://github.com/matrix-org/synapse-s3-storage-provider) depends on `LoggingContext.current_context` which was removed in #7120. We add this back (as a pass through to `current_context`). I'll make a separate PR for ss3sp to update the reference there too.
Note this PR is made against the release branch so it will go out with #7120.
Should we mention any changes to `LoggingContext` in the changelog?
Fixes #7400
=> Add backwards compatibility codepath to LoggingContext.

changelog.d/7421.misc, synapse/replication/tcp/handler.py
Cherry-pick of https://github.com/matrix-org/synapse/commit/105cadbc9afd89be72762160d53c9f782b9be133
Fixes https://github.com/matrix-org/synapse/issues/7412
=> Move logs about discarded RDATA to debug

changelog.d/7428.misc, synapse/storage/data_stores/main/end_to_end_keys.py
... mostly because the latter has a cache.
Also (in a separate commit), some fixes for the batching in the bulk lookup methods.
=> Make get_e2e_cross_signing_key delegate to get_e2e_cross_signing_keys_bulk

changelog.d/7420.misc, synapse/api/auth.py, synapse/api/auth_blocking.py, tests/api/test_auth.py, tests/handlers/test_auth.py, tests/handlers/test_sync.py, tests/test_mau.py
Fixes https://github.com/matrix-org/synapse/issues/7419
Polls all the config options on server setup instead of every req. `check_auth_blocking`, which used the majority of the config options, was moved to a separate class to keep `Auth` clean.
Merging to the release branch to help get this out on matrix.org.
Edit: Lots of tests needed to be updated as they modified the hs' config after the hs had been initialized, which means `check_auth_blocking`, which pulls options on hs intiialization, would be using stale values. These tests were changed such that they modify values in the new `AuthBlocking` class instead of the hs' config.
=> Stop Auth methods from polling the config on every req.

changelog.d/7439.feature, synapse/python_dependencies.py
For the record, the reason we need this is as follows:
each RDATA command comes down the redis pipe as a subscription message. txredisapi as written needs at least three reactor ticks to read each subscription message from the tcp buffer. Hence, once the process gets loaded, it starts getting behind, and eventually redis knifes the connection. it then takes ages for the master to work its way through the backlog, before it reconnects again, during which any commands from any workers are dropped.
=> Make redis go faster with hiredis

changelog.d/7442.misc, synapse/groups/attestations.py
Fixes: https://github.com/matrix-org/synapse/issues/7411
Port of https://github.com/matrix-org/synapse/commit/14bb4cff99ddd8b5eb1816c5405d52a8f13e29d6 from the `matrix-org-hotfixes` branch to mainline.
=> Port group attestation renewal slow down from matrix-org-hotfixes

changelog.d/7426.misc, synapse/logging/context.py
This reworks the code to incrementally report the resource usage of a context to a context's parent, but avoids resetting the resource usage.
Fixes #7370
=> Improve per-block CPU and DB usage metrics

changelog.d/7422.feature, docs/sample_config.yaml, synapse/config/server.py, synapse/handlers/message.py
Add `dummy_events_threshold` which allows configuring the number of forward extremities a room needs for Synapse to send forward extremities in it.
~I decided not to expose it in the sample config as the flag to enable/disable that feature is also hidden from there.~
Fixes https://github.com/matrix-org/synapse/issues/7413
=> Add a configuration setting for the dummy event threshold

changelog.d/7445.misc, synapse/handlers/saml_handler.py, tox.ini
While reviewing #7256 I realized that the SAML handler never got added to the tox config for mypy. Most of this was already typed.
=> Add more type hints to SAML handler.

changelog.d/7449.misc, synapse/res/templates/notice_expiry.html, synapse/res/templates/notice_expiry.txt
=> Fixes typo (bellow -> below)

changelog.d/7450.feature, synapse/config/redis.py, synapse/replication/tcp/handler.py
Since we only use pubsub, the dbid is irrelevant.
=> Drop support for redis.dbid

changelog.d/7435.feature, docs/sample_config.yaml, docs/spam_checker.md, synapse/config/spam_checker.py, synapse/events/spamcheck.py, tests/handlers/test_user_directory.py
Fixes: https://github.com/matrix-org/synapse/issues/6758
Allows a sysadmin to run multiple spam checker modules at once. Keeps backwards compatibility with the old config. Improves config format/documentation in the process.
=> Extend spam checker to allow for multiple modules

changelog.d/7455.bugfix, synapse/handlers/auth.py, synapse/rest/client/v2_alpha/register.py, synapse/storage/data_stores/main/ui_auth.py, tests/rest/client/v2_alpha/test_auth.py, tox.ini
This reworks the UI Auth session validation per #7452. 
* The registration endpoint is less strict on ensuring that the given parameters have changed during registration. This is a backwards compatibility path for clients.
* The client dict gets persisted at each step of the authentication for registration.
* The UI Auth tests are heavily modified to clean them up and add a few other scenarios.
It is worth comparing this code to the v1.12.4:
https://github.com/matrix-org/synapse/blob/release-v1.12.4/synapse/handlers/auth.py#L265-L278
The overall structure is much more similar now, but sometimes we validate and sometimes we persist.
=> Rework UI Auth session validation

changelog.d/7446.doc, changelog.d/7446.feature, docs/workers.md
https://github.com/matrix-org/synapse/issues/7402
=> Documentation on setting up redis

changelog.d/7448.misc, synapse/storage/data_stores/main/roommember.py
This method does not have any callers.
=> Remove unused store method get_hosts_in_room

changelog.d/7460.misc, synapse/handlers/search.py
Converts the search handler to async/await.
=> Convert search code to async/await.

changelog.d/7459.misc, synapse/handlers/federation.py, synapse/handlers/room_member.py
This converts the remaining bits of the federation handler code to async/await.
=> Convert federation handler to async/await.

changelog.d/7470.misc, synapse/app/_base.py, synapse/config/server.py, synapse/notifier.py, synapse/push/mailer.py, synapse/storage/database.py, tests/config/test_load.py
New error: https://www.flake8rules.com/rules/E741.html
=> Fix new flake8 errors

changelog.d/7482.bugfix, synapse/replication/tcp/handler.py, synapse/replication/tcp/redis.py
This does two things:
~~1. Ensures we only send a `REPLICATE` when we (re)connect *after* we successfully subscribe. This ensures we are subscribed to hear responses to `REPLICATE` (in practice this is unlikely to be an issue as we'll almost certainly finish subscribing by the time other instances have received and responded to the `REPLICATE`).~~  Actually, this is spurious. 
2. Proactively send out `POSITION` commands (as if we had just received a `REPLICATE`) when we connect to Redis. This is important as other instances won't notice we've connected to issue a `REPLICATE` command (unlike for direct TCP connections). This is only currently an issue if master process reconnects without restarting (if it restarts then it won't have written anything and so other instances probably won't …
=> Fix Redis reconnection logic

changelog.d/7492.misc, synapse/app/generic_worker.py, synapse/handlers/message.py, synapse/storage/data_stores/main/censor_events.py
This is safe as we can now write to cache invalidation stream on workers, and is required for when we move event persistence off master.
=> Allow censoring of events to happen on workers.

changelog.d/7483.bugfix, synapse/handlers/auth.py, synapse/rest/client/v2_alpha/register.py, tests/rest/client/v2_alpha/test_auth.py
Per some of our discussions we need to back-off on verifying the client dictionary since it seems these frequently change in a non-compliant way during UI authentication operations. We do still verify that the URI and method haven't been modified, but only warn loudly if the client dictionary has been.
This will not warn for the registration endpoint, but will persist the modifications to the client dict.
It is our intention in a future version to tighten this up again, but that might need some spec work.
Fixes #7471
* Do we need to always persist the modifications to the client dict?
* Do we want to log the device or anything in the warning? The log line should include the user already I think.
* Should the changelog entry be different than the original PRs now that we've done an RC?
=> Warn, instead of erroring, if the client dict changes during UI Auth.

changelog.d/7495.feature, synapse/config/workers.py, synapse/replication/http/_base.py
This will allow us, for example, to configure where instances talk to to send events.
For now this remains hidden, experimental and undocumented.
=> Add `instance_map` config and route replication calls

changelog.d/7493.misc, synapse/app/generic_worker.py, synapse/replication/tcp/client.py, synapse/server.py, synapse/server.pyi
This is so that the logic can happen on both master and workers when we move event persistence out.
=> Move EventStream handling into default ReplicationDataHandler

changelog.d/7443.bugfix, synapse/api/auth.py, synapse/rest/client/v1/logout.py, tests/rest/client/v1/test_login.py, tests/rest/client/v2_alpha/test_register.py
Fixes https://github.com/matrix-org/synapse/issues/5756
This PR prevents an `InvalidClientTokenError` or `AuthError` being raised when a user is expired for the `/logout` and `/logout/all` endpoints.
=> Allow expired accounts to logout

changelog.d/7503.bugfix, synapse/http/matrixfederationclient.py
=> Fix b'GET' in prometheus metrics

changelog.d/7473.bugfix, synapse/http/site.py
Fixes https://github.com/matrix-org/synapse/issues/7441
Checks that `reason` has been properly wrapped in a `Failure`. If not, wraps it manually.
=> Workaround for failure to wrap reason in Failure

changelog.d/7502.feature, synapse/api/room_versions.py, synapse/event_auth.py, tests/test_event_auth.py
Fixes #7501 
This adds a new flag to `RoomVersion` to specify when to enforce the additional rules on power level events, it then implements the logic to enforce this. Includes a basic test.
=> Enforce MSC2209: auth rules for notifications in power level event

changelog.d/7506.feature, synapse/api/room_versions.py, tests/events/test_utils.py, tests/handlers/test_federation.py, tests/test_event_auth.py
Fixes #7500 
This implements room version 6 and removes some experimental room versions.
=> Implement room version 6 (MSC2240).

changelog.d/7507.misc, synapse/handlers/room_member.py, synapse/handlers/room_member_worker.py
Convert the room member (and worker) handler to async/await.
This was pretty straight-forward, but the sub-class made it a little tricky. Some of the types and such a bit funky. I'll follow this up with type hints.
=> Update the room member handler to use async/await.

changelog.d/7463.doc, docs/reverse_proxy.md
The specific headers that are passed using this new configuration format are Host and X-Forwarded-For, which should be all that's required (https://caddy.community/t/v2-reverse-proxy-transparent/6480/8).
FWIW, it sounds like Caddy 1 is going to become unsupported in the very near future.
=> Add Caddy 2 example to reverse proxy doc

changelog.d/7514.doc, docs/reverse_proxy.md
also a small clarification to nginx
=> Formatting for reverse-proxy docs

changelog.d/7511.bugfix, synapse/storage/data_stores/main/profile.py
`values` is not an argument to `simple_update`, but `updatevalues` is. I believe this was an error when referencing the above function, which uses `simple_upsert`, which does have a `values` argument.
=> Fix a small typo in the arguments of simple_update in update_remote_profile_cache

changelog.d/7505.misc, synapse/event_auth.py, tox.ini
While working on #7502 I quickly added some types to the `synapse.event_auth` module.
=> Add type hints to event_auth code.

changelog.d/7491.misc, synapse/replication/slave/storage/events.py, synapse/replication/slave/storage/push_rule.py, synapse/storage/data_stores/main/__init__.py, synapse/storage/data_stores/main/cache.py, synapse/storage/data_stores/main/events_worker.py, synapse/storage/data_stores/main/push_rule.py, synapse/storage/util/id_generators.py
This allows us to have the logic on both master and workers, which is necessary to move event persistence off master.
We also combine the instantiation of ID generators from DataStore and slave stores to the base worker stores. This allows us to select which process writes events independently of the master/worker splits.
~~Based on #7490~~
=> Move event stream handling out of slave store.

changelog.d/7516.misc, synapse/app/generic_worker.py, synapse/storage/data_stores/main/search.py
This is required as both event persistence and the background update needs access to this function. It should be perfectly safe for two workers to write to that table at the same time.
=> Add a worker store for search insertion.

changelog.d/7523.bugfix, synapse/handlers/register.py, synapse/rest/admin/users.py, synapse/rest/client/v2_alpha/register.py
The registration endpoint now calculates the password hash early and passes that to all other code, including the user interactive authentication process.
=> Hash passwords earlier in the registration process

changelog.d/7497.bugfix, synapse/handlers/message.py
Per https://github.com/matrix-org/matrix-doc/issues/1436#issuecomment-410089470 they should be omitted instead of returning null or "". They aren't marked as required in the spec.
Fixes https://github.com/matrix-org/synapse/issues/7333
=> Omit displayname or avatar_url if they aren't set instead of returning null

docs/admin_api/user_admin_api.rst
Maybe a table would be even better?
=> Improve API doc readability

changelog.d/7526.misc, debian/build_virtualenv, debian/changelog, docker/Dockerfile-dhvirtualenv, scripts-dev/build_debian_packages
turns out that dh-virtualenv didn't build for focal/bullseye/sid anymore, so this was more traumatic than expected.
Fixes: #7293
=> Bump dh-virtualenv and build for focal

changelog.d/7538.bugfix, synapse/handlers/set_password.py, synapse/rest/admin/users.py, synapse/rest/client/v2_alpha/account.py, synapse/rest/client/v2_alpha/register.py
This is essentially #7523, but for the password reset process. This makes the two sets of code much more similar:
* The validation done on both is now the same.
* The validation on the new password is done *before* the UI Auth process.
* Both now hash passwords immediately.
~~I targeted this against 1.13.0 since it would be nice to include this in a 1.13.1 if one is done. It should retarget fine against develop.~~
=> Hash passwords earlier in the password reset process

changelog.d/7539.misc, scripts-dev/build_debian_packages
Per the release of v1.13.0 Ubuntu Cosmic and Disco have reached EOL in July 2019 and January 2020, respectively.
=> Remove cosmic and disco which are both EOL.

changelog.d/7548.bugfix, synapse/storage/persist_events.py
`_is_server_still_joined` will throw if it is given state updates with non-user ID state keys with local user leaves. This is actually rarely a problem since local leaves almost always get persisted by themselves.
(I discovered this on a branch that was otherwise broken, so I haven't seen this in the wild)
=> Fix bug in persist events when dealing with non member types.

changelog.d/7528.doc, docs/systemd-with-workers/system/matrix-synapse-worker@.service
Whilst working with PC-Admin to set up workers, we noticed it was too easy to typo worker names when enabling the corresponding systemd service.
This makes systemd check that the worker config file exists when starting, immediately giving an error message instead of silently failing and forever restarting the broken service.
An example error message:
```console
$ sudo systemctl start matrix-synapse-worker@federation_sender
Assertion failed on job for matrix-synapse-worker@federation_sender.service.
```
- End with either a period …
=> Ensure worker config exists in systemd service

changelog.d/7554.misc, synapse/util/patch_inline_callbacks.py
`Failure()` is more cunning than `Failure(e)`.
=> Fix stacktrace mangling in `patch_inline_callbacks`

changelog.d/7555.misc, docker/Dockerfile-dhvirtualenv
When we tried to build debs for 1.13.0, the build failed because docker used a
base docker image which had a stale apt cache.
Fixes: #7540
(This was basically caused by #7526, which meant that we had to rebuild dh-virtualenv.)
=> Refresh apt cache when building dh-virtualenv docker image

changelog.d/7556.misc, synapse/app/generic_worker.py, synapse/handlers/federation.py, synapse/http/matrixfederationclient.py
These are business as usual errors, rather than stuff we want to log at error.
=> Fix exception reporting due to HTTP request errors.

changelog.d/7547.misc, synapse/handlers/room.py
Instead of doing a complicated dance of deleting and moving aliases one
by one, which sends a canonical alias update into the old room for each
one, lets do it all in one go.
This also changes the function to move *all* local alias events to the new
room, however that happens later on anyway.
=> On upgrade room only send canonical alias once.

changelog.d/7552.bugfix, synapse/rest/client/v2_alpha/auth.py
To repeat some of #7484, it seems that some SAML identity providers (e.g. Google) require that a `RelayState` parameter is passed in, even though it is optional. We do not use a relay state for UI auth, but can provide a dummy one in that case.
Fixes #7484
=> Pass in a non-empty RelayState for user interactive authentication with SAML

changelog.d/7557.misc, synapse/handlers/identity.py, synapse/push/emailpusher.py, synapse/push/mailer.py, tests/rest/client/v2_alpha/test_account.py
Mainly because sometimes the email push code raises exceptions where the
stack traces have gotten lost, which is hopefully fixed by this.
=> Convert sending mail to async/await.

changelog.d/7542.misc, synapse/handlers/federation.py, synapse/handlers/message.py, synapse/handlers/room.py, synapse/handlers/room_member.py, synapse/handlers/room_member_worker.py, synapse/replication/http/federation.py, synapse/replication/http/membership.py, synapse/replication/http/send_event.py, synapse/replication/http/streams.py, synapse/replication/tcp/client.py, synapse/replication/tcp/handler.py, synapse/rest/admin/rooms.py, synapse/rest/client/v1/room.py, synapse/rest/client/v2_alpha/relations.py, synapse/server.py, synapse/server.pyi, synapse/server_notices/server_notices_manager.py, synapse/storage/data_stores/main/events_worker.py, synapse/storage/data_stores/main/roommember.py, tests/federation/test_complexity.py, tests/handlers/test_typing.py, tests/storage/test_cleanup_extrems.py, tests/storage/test_event_metrics.py, tests/test_federation.py
The idea here is that if an instance persists an event via the replication HTTP API it can return before we receive that event over replication, which can lead to races where code assumes that persisting an event immediately updates various caches (e.g. current state of the room).
*Most* of Synapse doesn't hit such races, so we don't do the waiting automagically, instead we do so where necessary to avoid unnecessary delays. We may decide to change our minds here if it turns out there are a lot of subtle races going on.
People probably want to look at this commit by commit.
=> Add ability to wait for replication streams

changelog.d/7534.misc, synapse/app/generic_worker.py, synapse/app/homeserver.py, synapse/http/server.py, tests/test_server.py
This is an attempt to fix #7313.  
~~For workers which don't have a `media` listener it adds dummy endpoints which return a 200 OK for `OPTIONS` requests to themselves and any leaf below them. Any other requests method (`POST`, `PUT`, `GET`, etc.) is a 404.~~
For all endpoints under the root endpoint it will return a 200 OK for `OPTIONS` requests. Other requests will act as "normal".
I do have some questions:
=> Return 200 OK for all OPTIONS requests

changelog.d/7517.feature, scripts/synapse_port_db, synapse/app/generic_worker.py, synapse/config/logger.py, synapse/config/workers.py, synapse/handlers/federation.py, synapse/handlers/message.py, synapse/handlers/presence.py, synapse/handlers/room.py, synapse/handlers/room_member.py, synapse/replication/http/__init__.py, synapse/replication/http/_base.py, synapse/replication/http/membership.py, synapse/replication/http/presence.py, synapse/replication/tcp/handler.py, synapse/rest/admin/rooms.py, synapse/storage/data_stores/__init__.py, synapse/storage/data_stores/main/devices.py, synapse/storage/data_stores/main/events.py, synapse/storage/data_stores/main/events_worker.py, synapse/storage/data_stores/main/roommember.py, synapse/storage/persist_events.py
This adds config of the form:
```yaml
writers:
events: some_worker_name
```
(Better names for config option would be appreciated).
Requires #7515 ~~and #7516~~
=> Add option to move event persistence off master

changelog.d/7558.misc, synapse/storage/data_stores/main/monthly_active_users.py
we can use `make_in_list_sql_clause` rather than doing our own half-baked
equivalent, which has the benefit of working just fine with empty lists.
(This has quite a lot of tests, so I think it's pretty safe)
=> Simplify reap_monthly_active_users

changelog.d/7565.bugfix, synapse/app/generic_worker.py, tests/replication/test_federation_ack.py
A couple of changes of significance:
* remove the `_last_ack < federation_position` condition, so that updates will still be correctly processed after restart
* Correctly wire up send_federation_ack to the right class.
Fixes #7535. See there for much more detail.
=> Fix recording of federation stream token

changelog.d/7579.bugfix, synapse/replication/tcp/handler.py
=> Ensure ReplicationStreamer is always started when replication enabled.

changelog.d/7578.bugfix, synapse/util/caches/lrucache.py, tests/config/test_cache.py
This is already correctly done when we instansiate the cache, but wasn't
when it got reloaded (which always happens at least once on startup).
Broke in #6391
=> Don't apply cache factor to event cache.

changelog.d/7581.doc, docs/sample_config.yaml, synapse/config/oidc_config.py
'client_auth_method' commented out value was erronously 'client_auth_basic',
when code and docstring says it should be 'client_secret_basic'.
=> Fix sample config docs error

changelog.d/7575.bugfix, changelog.d/7575.misc, synapse/storage/prepare_database.py
We were using `logger` syntax which isn't supported by `Exception`s.
=> Fix incorrect placeholder syntax in database prepartion code

changelog.d/7584.misc, synapse/app/generic_worker.py, synapse/replication/tcp/handler.py, synapse/util/async_helpers.py, tests/util/test_linearizer.py
Instead of storing and sending an ACK for every single row we send
synchronously, we instead do it asynchronously while batching up
updates.
=> Speed up processing of federation stream RDATA rows.

changelog.d/7597.bugfix, synapse/metrics/background_process_metrics.py
=> Make inflight background metrics more efficient.

changelog.d/7599.bugfix, synapse/handlers/room_list.py
This was throwing up exceptions in sentry.
=> Fix 'FederationGroupsRoomsServlet' API when group has room server is not in.

INSTALL.md, changelog.d/7587.doc
Synapse was added to the ports tree in Nov, 2019 by Renaud Allard (https://marc.info/?l=openbsd-ports&m=157417848805329).
With the release of OpenBSD 6.7 on May 22, 2020 a pre-compiled binary is available as well.
Update INSTALL.md accordingly.
Signed-off-by: hashashini
=> Update OpenBSD installation instructions

changelog.d/7607.bugfix, synapse/storage/data_stores/main/receipts.py
=> Use upsert when inserting read receipts

changelog.d/7609.bugfix, synapse/handlers/device.py
Without this patch, if an error happens which isn't caught by `user_device_resync`, then `_maybe_retry_device_resync` would fail, without retrying the next users in the iteration. This patch fixes this so that it now only logs an error in this case.
The reason we're logging as debug here is because if a server is consistently making this fail for a user then we'd end up flooding the logs with these errors, at a rate of one line every 30s. Though it might be fine to log it as info, and I can be convinced either way.
=> Don't fail all of an iteration of the device list retry loop on error

changelog.d/7267.bugfix, synapse/rest/admin/users.py, tests/rest/admin/test_user.py
Fixes #7135
Add `add_pusher` to `PUT "/_synapse/admin/v2/users/<user_id>"` when creating a new user
=> Email notifications for new users when creating via the Admin API.

changelog.d/7594.bugfix, synapse/handlers/device.py, synapse/handlers/e2e_keys.py, tests/test_federation.py
It looks like `user_device_resync` was ignoring cross-signing keys from the results received from the remote server. This PR fixes this, by processing these keys using the same process [`_handle_signing_key_updates`](https://github.com/matrix-org/synapse/blob/bfae0f007e0b01415471e94ca48ac3b1f277a412/synapse/handlers/e2e_keys.py#L1286) does (and effectively factor that part out of that function).
Fixes https://github.com/matrix-org/synapse/issues/7504.
Fixes https://github.com/matrix-org/synapse/issues/7521.
=> Process cross-signing keys when resyncing device lists

changelog.d/7585.bugfix, synapse/rest/client/v1/login.py, tests/rest/client/v1/test_login.py
When a previously non-existent user is authenticated with m.login.jwt (after the token has been validated), the user should be created. But a bug made checking if the user exists reset the claimed username to None, and we would see generic TypeError exceptions when we asked synapse to
process it further:
...
File "/usr/lib/python3/dist-packages/synapse/rest/client/v1/login.py", line 393, in do_jwt_login
result = await self._complete_login(
File "/usr/lib/python3/dist-packages/synapse/rest/client/v1/login.py", line 338, in _complete_login
localpart=UserID.from_string(user_id).localpart
File "/usr/lib/python3/dist-packages/synapse/types.py", line 171, in from_string
if len(s) < 1 or s[0:1] != cls.SIGIL:
TypeError: object of type 'NoneType' has no len()
This regression was introduced in …
=> Don't throw exception on m.login.jwt automatic user creation

changelog.d/7602.doc, setup.py
Synapse supports Python 3.8. We've been [using it in CI](https://github.com/matrix-org/pipelines/blob/2513aea6bf613131e4d613f7fccd780363d10eb6/synapse/pipeline.yml#L216) for a while now.
=> Advertise Python 3.8 support in setup.py

README.rst, changelog.d/7603.doc
Just in case people head straight to the troubleshooting section and find themselves at a dead end.
=> Mention #synapse:matrix.org in README troubleshooting

changelog.d/7614.misc, docs/sample_config.yaml, synapse/config/saml2_config.py, synapse/handlers/saml_handler.py, synapse/http/server.py, synapse/rest/saml2/response_resource.py, tox.ini
* Expose `return_html_error` as a public function, which can take a Jinja2 template.
* In the SAML response handler, use the existing code in `return_html_error` instead of re-implementing it (giving it a jinja2 template rather than inventing a new form of template)
* and do the exception-catching in the REST layer rather than in the handler layer, to make sure we catch all exceptions.
=> Clean up exception handling in SAML2ResponseResource

changelog.d/7621.misc, docker/Dockerfile-dhvirtualenv
Upstream have merged our changes (https://github.com/spotify/dh-virtualenv/pull/300), so let's switch back to it instead of using our fork.
=> Switch back to upstream dh-virtualenv

changelog.d/7624.bugfix, synctl
This partially reverts #6598. On reflection, not starting Synapse if it wasn't previously running is rather surprising.
=> `synctl restart` should start synapse if it wasn't running

changelog.d/7622.bugfix, synapse/handlers/federation.py
We already caught some exceptions, but not all.
This fixes exceptions such as:
```
HttpResponseException: 502: b'Bad Gateway'
File "synapse/handlers/federation.py", line 271, in on_receive_pdu
origin, pdu, prevs, min_depth
File "synapse/handlers/federation.py", line 502, in _get_missing_events_for_pdu
timeout=60000,
File "synapse/federation/federation_client.py", line 957, in get_missing_events
timeout=timeout,
File "twisted/internet/defer.py", line 1416, in _inlineCallbacks
result = result.throwExceptionIntoGenerator(g)
File "twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
return g.throw(self.type, self.value, self.tb)
File "synapse/federation/transport/client.py", line 564, in get_missing_events
timeout=timeout,
File "twisted/internet/defer.py", line 1416, in …
```
=> Fix exceptions when fetching events from a down host.

changelog.d/7625.misc, synapse/handlers/register.py
This is so the user is warned about the username not being valid as soon as possible, rather than only once they've finished UIA.
Fixes #7576
=> Check if the localpart is reserved for guests earlier in the registration flow

changelog.d/7619.misc, tests/storage/test_monthly_active_users.py, tests/test_mau.py
Calls `self.get_success` on all deferred methods instead of abusing `self.pump()`. This has the benefit of working with coroutines, as well as checking that method execution completed successfully.
There are also a few small cleanups that I made in the process.
=> Replace instances of reactor pumping with get_success.

changelog.d/7631.bugfix, synapse/rest/client/v1/login.py
Adds the token login flow (in addition to SSO) when OIDC is enabled. This was overlooked in the initial implementation.
I left the `m.login.cas` legacy login flow since it is part of r0.4.0, which Synapse reports as still being supported.
=> Enable the token login type is provided for OpenID connect.

changelog.d/7586.feature, synapse/config/repository.py, tests/rest/media/v1/test_media_storage.py
Closes #4382
I tested this by editing a file on my server directly inside the virtualenv, seems to work fine.
=> Add support for webp thumbnailing

changelog.d/7634.misc, synapse/app/homeserver.py
I'm hoping this will fix #7627 (and maybe #6676, but I don't have a RaspberryPi hooked up to test that).
=> Attempt to fix PhoneHomeStatsTestCase.test_performance_100 being flaky.

changelog.d/7645.misc, synapse/api/auth.py, synapse/rest/admin/_base.py
These things don't return Deferreds.
=> Fix type information on `assert_*_is_admin` methods

changelog.d/7630.feature, synapse/api/constants.py
Updates the UI Auth SSO flow to `m.login.sso` (from `org.matrix.login.sso`) now that the client-server API r0.6.1 was published.
Fixes #7531
It is unclear if we should keep the old `org.matrix.login.sso`.
=> Enable the standardized m.login.sso flow for UI Auth

changelog.d/7647.doc, docs/admin_api/README.rst, docs/admin_api/delete_group.md, docs/admin_api/media_admin_api.md, docs/admin_api/purge_history_api.rst, docs/admin_api/purge_remote_media.rst, docs/admin_api/room_membership.md, docs/admin_api/user_admin_api.rst
Clarify how to authenticate
path params are not the same thing as query params /cc @dklimpel
=> Clarifications to the admin api documentation

changelog.d/7640.misc, synapse/handlers/register.py, synapse/handlers/state_deltas.py, synapse/handlers/stats.py, synapse/handlers/user_directory.py, tests/handlers/test_user_directory.py
This converts:
* User directory handler
* Stats handler
* State deltas handler
Note that I did all three since the stats handler sub-classes state deltas handler...although I realized there was no reason for it to be doing that so I removed it. Kind of out of scope for this PR though.
I added a `ensureDeferred` to the register handler to limit the scope of the PR.
=> Convert user directory handler and related classes to async/await

changelog.d/7629.bugfix, synapse/static/client/login/js/login.js
This modifies the login fallback page to accept a query parameter (`device_id`) which will get passed into the login endpoint during the login process.
This also reworks some of the `login.js` code to reduce duplicated code.
Fixes #5755
MSC: https://github.com/matrix-org/matrix-doc/pull/2604
* Should we also accept an `initial_device_display_name` query parameter? It does not look any of the [other parameters](https://matrix.org/docs/spec/client_server/r0.6.1#post-matrix-client-r0-login) would be useful to accept since they're part of the login process.
=> Accept a device ID to the login fallback endpoint.

changelog.d/7649.misc, synapse/handlers/register.py, synapse/module_api/__init__.py
The registration handler had a few `defer.ensureDeferreds` in it that are gone now. I added one to the API module to keep that stable.
There was also a couple of functions that we yielded on that were just normal functions (they didn't return Deferreds), so I've removed the yield.
=> Convert the registration handler to async/await.

changelog.d/7652.doc, docs/sample_config.yaml, synapse/config/server.py
Just a simple typo fix.
Signed-off-by: wondratsch <28294257+wondratsch@users.noreply.github.com>
=> fix typo in sample_config.yaml

changelog.d/7664.misc, docs/sample_config.yaml, synapse/config/saml2_config.py
This is hopefully a partial fix for #7056. It increases the default SAML session timeout from 5m to 15m. I debated if we should add a note to the config saying "this should match your SAML IdP" or something like that?
Note that this is the time that the user has to *complete the login*, not the time that there session is active once they've completed authentication.
=> Increase the default SAML session expirary time to 15 minutes.

changelog.d/7606.bugfix, synapse/rest/client/v1/presence.py
https://matrix.org/docs/spec/client_server/r0.6.1#get-matrix-client-r0-presence-userid-status doesn't include a `user_id`, and given the request URL includes the user_id I suspect there is limited value in diverging from the spec.
=> Remove "user_id" from GET /presence

changelog.d/7689.bugfix, synapse/handlers/auth.py
This does mean that some active UI auth session will be broken when this is deployed since the comparator is changing. I'm not sure there's a good way around that. (I guess we could try comparing with the old values, but that seems a bit silly of a workaround to introduce.)
This was introduced in #7302.
=> Fix a typo when comparing the URI & method during UI Auth.

changelog.d/7688.bugfix, synapse/storage/data_stores/main/ui_auth.py
There was a missing await call causing the log context to get lost in the UI Auth code (sometimes).
This was introduced in #7455.
=> Fix warnings about losing log context

changelog.d/7648.bugfix, synapse/app/generic_worker.py, synapse/replication/tcp/commands.py, synapse/replication/tcp/handler.py, tests/replication/tcp/streams/test_events.py, tests/replication/tcp/streams/test_typing.py
When processing `RDATA` commands via replication, discard any `RDATA` that has already been seen. This is calculated via asking the stream to get the "current position" and comparing to the incoming token.
Fixes #7360
* Handle streams that can reset (e.g. `typing` and `federation`).
* Add tests for resetting the above.
=> Discard RDATA from already seen positions

changelog.d/7698.bugfix, synapse/handlers/device.py
This was due to `user_device_resync` being called from a background process
Broke in #7453.
=> Fix "There was no active span when trying to log." error

changelog.d/7685.bugfix, synapse/rest/client/v2_alpha/account.py
Looks like these endpoints made it to the r0 CS API but we never enabled them on the /r0 route.
=> Enable 3PID add/bind/unbind endpoints on r0 routes

changelog.d/7687.bugfix, synapse/rest/client/v1/login.py
The spec [states](https://matrix.org/docs/spec/client_server/r0.6.1#phone-number) that `m.id.phone` requires the field `country` and `phone`.
In Synapse, we've been enforcing `country` and `number`.
I am not currently sure whether this affects any client implementations.
This issue was introduced in #1994.
=> Update m.id.phone to use 'phone' instead of 'number'

changelog.d/7691.bugfix, synapse/handlers/e2e_room_keys.py, tests/handlers/test_e2e_room_keys.py
Thanks to sorunome for noticing.
The spec says that `etag` should be a string, but it's stored in the DB as an int, so we need to convert it before we return it.
=> make sure etag is a string for GET room_keys/version

changelog.d/7701.bugfix, synapse/push/push_rule_evaluator.py, tests/push/test_push_rule_evaluator.py
Fixes #7700 by adding a type check to ensure the body is a string before applying regular expressions.
=> Ensure the body is a string before comparing push rules

changelog.d/7684.bugfix, synapse/module_api/__init__.py, tests/module_api/test_api.py
Fixes https://github.com/matrix-org/synapse/issues/7683
Broke in: #7649
We had a `yield` acting on a coroutine. To be fair this one is a bit difficult to notice as there's a function in the middle that just passes the coroutine along.
=> Wrap register_device coroutine in an ensureDeferred

changelog.d/7681.misc, synapse/app/_base.py, synapse/app/generic_worker.py, synapse/app/homeserver.py, synapse/config/server.py, synapse/config/workers.py, synapse/http/site.py, synapse/python_dependencies.py, tests/app/test_frontend_proxy.py, tests/app/test_openid_listener.py, tests/test_server.py, tests/unittest.py, tests/utils.py
This ended up being a bit more invasive than I'd hoped for (not helped by
generic_worker duplicating some of the code from homeserver), but hopefully
it's an improvement.
The idea is that, rather than storing unstructured `dict`s in the config for
the listener configurations, we instead parse it into a structured
`ListenerConfig` object.
=> Create a ListenerConfig object

changelog.d/7678.misc, synapse/handlers/devicemessage.py, synapse/handlers/pagination.py
This is a couple of quick wins for async/await. These methods are almost entirely used internally in their own classes.
=> Convert the device message and pagination handlers to async/await

changelog.d/7677.bugfix, synapse/http/federation/matrix_federation_agent.py, synapse/http/federation/well_known_resolver.py, synapse/http/matrixfederationclient.py, tests/http/federation/test_matrix_federation_agent.py
This includes a user agent for all federation requests (both well-known requests and standard federation traffic).
This was a little annoying because I had to pipe through the user agent string through a few levels, but wasn't a huge deal. This uses the same user-agent as `synapse.http.client`, which should probably be abstracted somewhere into config?
Fixes #7653
=> Include a user agent in federation requests

changelog.d/7708.bugfix, synapse/storage/data_stores/main/receipts.py, synapse/util/async_helpers.py
Fixes #3234
Per the comment in the file this is an `ObservableDeferred` not a `Deferred` and since the former is not a subclass of the latter then the type check is not working.
I believe I've adapted the code OK, but I'm not really sure how to test this.
=> Fix "argument of type 'ObservableDeferred' is not iterable" error

changelog.d/7636.misc, synapse/handlers/presence.py, synapse/handlers/typing.py, synapse/push/pusherpool.py, synapse/replication/tcp/streams/_base.py, synapse/storage/data_stores/main/events_worker.py, synapse/storage/data_stores/main/presence.py, synapse/storage/data_stores/main/push_rule.py, synapse/storage/data_stores/main/receipts.py
The aim here is to make it easier to reason about when streams are limited and when they're not, by moving the logic into the database functions themselves. This should mean we can kill of `db_query_to_update_function` function.
You might want to look at each commit individually.
This only does a subset of the streams, and simply merges the functionality from `db_query_to_update_function` into each streams get update DB function: https://github.com/matrix-org/synapse/blob/6c1f7c722f0baade9aecf41f600fcced670c4fcb/synapse/replication/tcp/streams/_base.py#L201-L218
c.f #7340
=> Refactor getting replication updates from database.

changelog.d/7696.doc, contrib/docker/docker-compose.yml
Signed-off-by: Simon Körner git@lubiland.de
=> update to postgres to 12-alpine in example compose

changelog.d/7714.bugfix, synapse/rest/media/v1/media_repository.py, tests/rest/media/v1/test_media_storage.py
Fixes #7707
I believe this is safe to just switch to since Synapse has supported both for a very long time (since 737c4223ef25fd2856d0ff6cc111d14b19f1adec -- [v0.13.0](https://github.com/matrix-org/synapse/blob/develop/CHANGES.md#changes-in-synapse-v0130-2016-02-10)).
=> Use the r0 media path instead of the unspecced v1.

changelog.d/7706.feature, docs/workers.md, synapse/config/repository.py, synapse/rest/media/v1/preview_url_resource.py
This requires a new config option to specify which media repo should be responsible for running background jobs to e.g. clear out expired URL preview caches. 
This is a bit of an icky way of doing it, though I think somewhat consistent with how we do worker configs currently. There are a couple of other options here:
1. Use distributed lock based on Redis, this is a bit difficult due to redis not having native support for this (the documentation suggests using a thing called [Redlock](https://redis.io/topics/distlock), but the fact that [Kleppman](http://martin.kleppmann.com/2016/02/08/how-to-do-distributed-locking.html) thinks its unsound is not exactly confidence inspiring). An argument could be made that we're probably will need to do something like this at some point though.
2. Change …
=> Support running multiple media repos.

changelog.d/7697.misc, mypy.ini, synapse/logging/opentracing.py
This uses https://github.com/erikjohnston/rust-jaeger-python-client (which is published as a wheel on pypi). I'm not entirely sure we want to do this, but it does provide better performance than the pure python reporter.
FWIW the python version uses auto generated code via thrift to implement their reporter, the rust version does exactly the same and uses the auto generated thrift code.
=> Add support for using rust-python-jaeger-reporter

changelog.d/7711.bugfix, scripts/synapse_port_db
Adds the two UI auth sessions tables to the set of tables to ignore, also pulls that list of tables out as a constant (and makes it a set).
Fixes #7654
=> Ignore the UI Auth sessions when porting from sqlite to postgresql

changelog.d/7680.misc, synapse/python_dependencies.py
Older versions of `parameterized` package have no `parameterized_class` decorator.
This decorator is used in tests.
=> Require parameterized package version to be at least 0.7.0.

changelog.d/7679.misc, synapse/handlers/typing.py, tests/handlers/test_typing.py
There's a couple of odd methods in here, in particular:
* `_stopped_typing` was yielded, but wasn't a `Deferred`.
* `get_new_events` doesn't need to be a coroutine, but I think it expects to be one based on the callers.
* `get_success` need to be used in tests instead of `getSuccessOf` for old deps, I think.
=> Convert the typing handler to async/await.

changelog.d/7716.feature, synapse/push/push_tools.py, synapse/storage/data_stores/main/event_push_actions.py
* Always return an unread_count in get_unread_event_push_actions_by_room_for_user
* Don't always expect unread_count to be there so we don't take out sync entirely if something goes wrong
=> Fix unread counts in sync

changelog.d/7725.misc, synapse/state/v2.py
This line was taking up ~21% of CPU on the event persistence worker on matrix.org
=> Speed up state res v2 across large state differences.

changelog.d/7727.misc, synapse/handlers/directory.py, synapse/handlers/message.py
This one was pretty straightforward!
* `can_modify_alias` was returning `Deferreds` but for no reason, so I removed them.
* There was a single caller to `get_association` that wasn't async yet, I wrapped it in `ensureDeferred` for now.
=> Convert directory handler to async/await

changelog.d/7717.bugfix, scripts/synapse_port_db
Noticed in #7711, it seems some of the tables we ignore in `synapse_port_db` don't exist anymore. I took a try at syncing the list to the real tables.
=> Sync ignored table names in synapse_port_db to current database schema

changelog.d/7730.bugfix, synapse/metrics/_exposition.py
HTTP requires the response to contain a Content-Length header unless chunked encoding is being used.
Prometheus metrics endpoint did not set this, causing software such as prometheus-proxy to not be able to scrape synapse for metrics.
Test by cURL:ing the metrics endpoint on a patched Synapse server:
```
> GET / HTTP/1.1
> Host: [redacted]:9000
> User-Agent: curl/7.64.0
> Accept: */*
>
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Server: BaseHTTP/0.6 Python/3.7.3
< Date: Sun, 21 Jun 2020 17:15:59 GMT
< Content-Type: text/plain; version=0.0.4; charset=utf-8
< Content-Length: 270468
```
=> Set Content-Length for Metrics requests

changelog.d/7735.bugfix, synapse/handlers/federation.py, synapse/state/__init__.py, synapse/state/v2.py, tests/state/test_v2.py
State res v2 across large data sets can be very CPU intensive, and if
all the relevant events are in the cache the algorithm will run from
start to finish within a single reactor tick. This can result in
blocking the reactor tick for several seconds, which can have major
repercussions on other requests.
To fix this we simply add the occaisonal `sleep(0)` during iterations to
yield execution until the next reactor tick. The aim is to only do this
for large data sets so that we don't impact otherwise quick resolutions.
=> Yield during large v2 state res.

changelog.d/7703.misc, tox.ini
- Debian 10 ships Python 3.7, so make that basepython for all envs
- Tox 3.7.0 doesn't seem to like trailing comments on dep lines
=> Make tox actions work on Debian 10

changelog.d/7738.misc, scripts-dev/lint.sh
* `flake8` currently takes the longest to execute, so move it to the end
* prevent linting from stopped on non-0 exit code. this would require the script to be re-run to get through all of the tools
=> Move flake8 to end. Don't exit script on failure

changelog.d/7751.misc, synapse/python_dependencies.py
`jwt`, provided the the `pyjwt` module, is required by our unit tests
https://github.com/matrix-org/synapse/blob/831b31e563eb181a8bc0311a8c28519ef9f131a1/tests/rest/client/v1/test_login.py#L7
This PR adds the module to the `test` conditional requirement.
This does mean that we have to change a version number in two places if we ever want to update `pyjwt`s minimum version. Is there a way to consolidate this? (I'm aware I could define a version string outside of the `CONDITIONAL_REQUIREMENTS` dict, but is there a better way?)
EDIT: This PR has been updated to explain that `"test"` is not supposed to be all of the modules necessary to run the unit tests, but rather those modules that are exclusively required by unit test code.
=> Explain the purpose of the "tests" conditional dependency requirement

changelog.d/7755.misc, synapse/federation/federation_server.py, synapse/federation/sender/__init__.py, synapse/handlers/appservice.py, synapse/metrics/__init__.py
These metrics measure:
1. Time between event is persisted and it being queued up to be sent to the relevant remote servers, and
2. Time taken to process an event from federation
=> Add some metrics for inbound and outbound federation processing times

changelog.d/7763.feature, docs/sample_config.yaml, synapse/config/registration.py, synapse/handlers/register.py, synapse/rest/admin/rooms.py, tests/handlers/test_register.py
This adds a couple of additional configuration options for auto-join rooms:
* `autocreate_auto_join_rooms_federated` to control whether those rooms should be federated
* `autocreate_auto_join_room_preset` to control the preset when those rooms are created
* `auto_join_mxid_localpart` to help with rooms that need an invite to be sent to join (e.g. invite only rooms)
This also makes a few tangentially related changes:
* Updates some documentation in the config
* The auto-join rooms now explicitly must be aliases, not IDs (as far as I can tell providing room IDs has been broken for > 5 years)
* Uses some constants in additional places
=> Additional configuration options for auto-join rooms

changelog.d/7771.misc, synapse/federation/sender/__init__.py, synapse/handlers/appservice.py
Introduced in #7755, not yet released.
=> Fix new metric where we used ms instead of seconds

changelog.d/7770.misc, synapse/handlers/federation.py, tox.ini
fix a few things to make this pass mypy.
=> Type checking for `FederationHandler`

changelog.d/7768.misc, synapse/replication/slave/storage/account_data.py, synapse/replication/slave/storage/deviceinbox.py, synapse/replication/slave/storage/groups.py, synapse/replication/slave/storage/presence.py, synapse/replication/slave/storage/push_rule.py, synapse/replication/slave/storage/pushers.py, synapse/replication/slave/storage/receipts.py, synapse/replication/slave/storage/room.py, synapse/storage/data_stores/main/cache.py, synapse/storage/data_stores/main/events_worker.py
This makes it much easier to find where streams are referenced.
=> Use symbolic names for replication stream names

changelog.d/7769.misc, synapse/handlers/federation.py
my editor was complaining about unset variables, so let's add some early
returns to fix that and reduce indentation/cognitive load.
=> Add early returns to `_check_for_soft_fail`

changelog.d/7765.misc, synapse/push/httppusher.py, tests/push/test_http.py
I think we'd like to properly solve this at some point but that's a Hard Problem™.
This corresponds to https://github.com/matrix-org/sygnal/issues/69#issuecomment-648058504.
=> Hack to add push priority to push notifications

changelog.d/7779.bugfix, synctl
Useful when config file is fully commented. Otherwise we get error:
```
File "/opt/matrix/synapse/venv/bin/synctl", line 380, in <module>
main()
File "/opt/matrix/synapse/venv/bin/synctl", line 244, in main
config.update(yaml_config)
TypeError: 'NoneType' object is not iterable
```
=> Allow YAML config file to contain None

changelog.d/7786.misc, scripts-dev/check_signature.py, scripts-dev/lint.sh, setup.cfg, synapse/api/auth.py, synapse/config/__main__.py, synapse/config/emailconfig.py, synapse/handlers/auth.py, synapse/handlers/cas_handler.py, synapse/logging/opentracing.py, synapse/replication/tcp/client.py, synapse/replication/tcp/handler.py, synapse/replication/tcp/streams/events.py, synapse/rest/media/v1/thumbnailer.py, synapse/secrets.py, synapse/storage/data_stores/main/events.py, synapse/storage/data_stores/main/ui_auth.py, synapse/storage/types.py, synapse/types.py, tests/handlers/test_e2e_keys.py, tests/rest/media/v1/test_media_storage.py, tests/test_utils/event_injection.py, tox.ini
The CI appears to use the latest version of isort, which is a problem when isort gets a major version bump. Rather than try to pin the version, I've done the necessary to make isort5 happy with synapse.
The two flags we set on invocation are no longer required, as they have been removed and are the default behaviour. The author has also removed dont_skip, and implies it is no longer required. I am unsure if that means we should be using something else though.
https://timothycrosley.github.io/isort/CHANGELOG/#500-penny-july-4-2020
=> isort 5 compatibility 

changelog.d/7766.bugfix, synapse/push/push_rule_evaluator.py, tests/push/test_push_rule_evaluator.py
=> Don't ignore `set_tweak` actions with no explicit `value`.

changelog.d/7775.misc, synapse/appservice/api.py, synapse/handlers/appservice.py, tests/handlers/test_appservice.py
This was mostly straightforward, a couple of things to note:
* `_get_services_for_user` and `_get_services_for_3pn` were synchronous, this was changed.
* The tests were very much depending on magic mocks, so they needed a bit of work (and I ended up reformatting them a bit to use less `Mock` constructors).
* The tests are using `inlineCallbacks` which I didn't try to fix here, but I can include it if it seems useful.
=> Convert the appservice handler to async/await.

changelog.d/7793.misc, synapse/storage/data_stores/main/events.py, synapse/storage/data_stores/main/events_worker.py, synapse/storage/data_stores/main/purge_events.py, tests/rest/admin/test_room.py
This table is no longer used, so we may as well stop populating it. Removing it
would prevent people rolling back to older releases of Synapse, so that can
happen in a future release.
(It got replaced by `local_current_membership`, ftr.)
=> Stop populating unused table `local_invites`.

README.rst, changelog.d/7789.doc, docs/reverse_proxy.md
Current links points to Caddy v1 which is deprecated.
=> Change Caddy links (old is deprecated)

changelog.d/7799.misc, synapse/handlers/identity.py, synapse/http/matrixfederationclient.py, synapse/rest/client/v1/voip.py
This is the first part of #7674.
I found these by:
* Looking where @richvdh suggested in #7674 to get the voip one.
* Switching to using `json` locally in my canonicaljson package and running unit tests and then running sytests.
=> Stop passing bytes when dumping JSON

changelog.d/7800.misc, synapse/replication/tcp/commands.py, synapse/storage/data_stores/main/schema/delta/25/fts.py, synapse/storage/data_stores/main/schema/delta/27/ts.py, synapse/storage/data_stores/main/schema/delta/31/search_update.py, synapse/storage/data_stores/main/schema/delta/33/event_fields.py
There were a few instances where we directly used simplejson in Synapse, which is a little janky since we don't even technically require it (it is a transient requirement of canonicaljson).
As far as I can tell there's no need to use this is any of the locations specified.
Part of #7674
=> Do not use simplejson in Synapse.

changelog.d/7805.misc, synapse/events/builder.py, synapse/federation/federation_client.py, synapse/groups/attestations.py, synapse/groups/groups_server.py, synapse/handlers/federation.py, synapse/handlers/groups_local.py, synapse/http/matrixfederationclient.py, synapse/server.py, tests/storage/test_base.py
... instead of duplicating `config.signing_key[0]` everywhere
=> Add `HomeServer.signing_key` property

changelog.d/7804.bugfix, synapse/handlers/message.py, synapse/handlers/room_member.py, synapse/handlers/room_member_worker.py, synapse/replication/http/membership.py, synapse/storage/data_stores/main/events.py, synapse/storage/persist_events.py
Fixes #2181.
The basic premise is that, when we fail to reject an invite via the remote server, we can generate our own out-of-band leave event and persist it as an outlier, so that we have something to send to the client.
Probably easiest to review this commit-by-commit.
=> Generate real events when we reject invites

changelog.d/7797.bugfix, synapse/app/generic_worker.py
I believe that this will fix #6396 by passing the `X-Forwarded-For` and `User-Agent` headers from the worker to the main process when proxying requests.
Note that a User-Agent is usually generated, but will get overridden if provided as a header:
https://github.com/matrix-org/synapse/blob/a3f11567d930b7da0db068c3b313f6f4abbf12a1/synapse/http/client.py#L400-L406
=> Pass additional headers from the worker to the main process.

changelog.d/7810.bugfix, synapse/handlers/room_member.py
It seems auth_events can be either a list or a tuple, depending on Things.
=> Fix `can only concatenate list (not "tuple") to list` exception

changelog.d/7808.misc, synapse/metrics/background_process_metrics.py
use `Failure()` to fish out the real exception.
=> Improve stacktraces from exceptions in background processes

changelog.d/7809.bugfix, synapse/handlers/room_member.py, synapse/handlers/room_member_worker.py, synapse/rest/client/v1/room.py
as of #7804, `remote_reject_invite`, and hence everything up the stack, now always returns an event id, so we can remove some dead code.
=> Clean up `update_membership` declaration

changelog.d/7816.bugfix, synapse/storage/data_stores/main/schema/delta/58/10drop_local_rejections_stream.sql
Synapse 1.16.0, as released on pypi, incorrectly included a database schema migration which added a table `local_rejections_stream`.
This PR is intended to be part of 1.16.1, and drops the incorrectly-added table.
For reference, I've uploaded the incorrect migration at https://gist.github.com/richvdh/ca812c5eab96427b983ad7fd09f74357.
Other releases of Synapse 1.16.0, including the debian packages and docker images, were not affected, but we will release the updated version there too for consistency.
=> Drop incorrectly-added table `local_rejections_stream`.

changelog.d/7817.bugfix, synapse/event_auth.py, synapse/handlers/federation.py
When fetching the state of a room over federation we receive the event
IDs of the state and auth chain. We then fetch those events that we
don't already have.
However, we used a function that recursively fetched any missing auth
events for the fetched events, which can lead to a lot of recursion if
the server is missing most of the auth chain. This work is entirely
pointless because would have queued up the missing events in the auth
chain to be fetched already.
Let's just diable the recursion, since it only gets called from one
place anyway.
=> Fix recursion error when fetching auth chain over federation

changelog.d/7815.bugfix, synapse/handlers/federation.py
The replication client requires that arguments are given as keyword
arguments, which was not done in this case. We also pull out the logic
so that we can catch and handle any exceptions raised, rather than
leaving them unhandled.
=> Fix resync remote devices on receive PDU in worker mode.

changelog.d/7813.misc, synapse/http/server.py
This does two unrelated things, minus them being in the same code:
* Removes the `response_code_message`, which is unused.
* Adds some additional type hints.
=> Add types to the server code and remove unused parameter

changelog.d/7822.bugfix, synapse/config/room.py
Fixes https://github.com/matrix-org/synapse/issues/7821, introduced in https://github.com/matrix-org/synapse/pull/7639
Turns out PyYAML translates `off` into a `False` boolean if it's
unquoted (see https://stackoverflow.com/questions/36463531/pyyaml-automatically-converting-certain-keys-to-boolean-values),
which seems to be a liberal interpretation of this bit of the YAML spec: https://yaml.org/spec/1.1/current.html#id864510
An alternative fix would be to implement the solution mentioned in the
SO post linked above, but I'm aware it might break existing setups
(which might use these values in the configuration file) so it's
probably better just to add an extra check for this one. We should be
aware that this is a thing for the next times we do that though.
I didn't find any other …
=> Fix handling of "off" in encryption_enabled_by_default_for_room_type

changelog.d/7830.feature, synapse/handlers/deactivate_account.py, tests/replication/test_client_reader_shard.py
This is mostly just tests, but does make one change to ensure that a background process only runs on a single process. I'm not 100% sure this is necessary, but I think it is.
Fixes #7672
=> Add support for sharding the client reader.

changelog.d/7829.bugfix, synapse/push/mailer.py
We didn't do this for e.g. registration emails.
=> Correctly pass app_name to all email templates.

changelog.d/7820.misc, synapse/api/errors.py
I started doing this in #7802 and realized it was bigger than I wanted so I split it out.
It adds more type hints to `synapse.api.errors`.
=> Improve the type hints of synapse.api.errors.

changelog.d/7827.feature, docs/jwt.md, docs/sample_config.yaml, synapse/config/jwt_config.py, synapse/rest/client/v1/login.py, tests/rest/client/v1/test_login.py
Fixes #7818
This adds two optional fields to the JWT configuration to validate the `iss` and `aud` claims of a JWT. There's some more information about these at [in the PyJWT docs](https://pyjwt.readthedocs.io/en/latest/usage.html#registered-claim-names). Note that the claims are handled slightly differently if the configuration is *not* provided, `iss` claims are essentially ignored, but an `aud` claim will cause validation to fail.
Both are simple strings that are compared by comparison.
This updates the documentation  and tests, but also slightly changes error handling for JWT logins to catch any PyJWT errors and convert them to `LoginError`.
I debated about making a separate `JwtHandler`, but this didn't end up adding too much code to the login REST servlet.
=> Add the option to validate the `iss` and `aud` claims for JWT logins.

changelog.d/7846.feature, docs/sample_config.yaml, synapse/config/emailconfig.py, synapse/push/mailer.py
This PR allows a server admin to customise the subjects used by Synapse to send emails. Can be reviewed commit by commit.
Fixes https://github.com/matrix-org/synapse/issues/6112
=> Allow email subjects to be customised through Synapse's configuration

changelog.d/4850.bugfix, changelog.d/7850.bugfix, synapse/storage/data_stores/main/room.py
Fixes #7784, which was introduced in #6358 / Synapse 1.7.0.
=> Fix bug in per-room message retention policies.

changelog.d/7848.misc, synapse/storage/data_stores/main/events.py
As far as I can tell from the sentry logs, the only time this has actually done anything in the last two years is when we had two master workers running at once, and even then, it made a bit of a mess of it (see https://github.com/matrix-org/synapse/issues/7845#issuecomment-658238739).
Generally I feel like this code is doing more harm than good.
Fixes #7845.
=> remove `retry_on_integrity_error` wrapper for persist_events

changelog.d/7844.bugfix, docs/jwt.md, synapse/rest/client/v1/login.py, tests/rest/client/v1/test_login.py
As I mentioned in #7776, the JWT login mechanism returns non-standard errors (401 instead of 403). This updates that mechanism to return the same errors as the `m.login.token` mechanism.
I should mention that the reasoning for this is that 401 is generally reserved for user-interactive authentication, while 403 is meant to be used for a failed login according to [the spec for the login endpoint](https://matrix.org/docs/spec/client_server/r0.6.0#post-matrix-client-r0-login):
> Status code 403:
> 
> The login attempt failed. This can include one of the following error codes:
> 
> * `M_FORBIDDEN`: The provided authentication data was incorrect.
> * `M_USER_DEACTIVATED`: The user has been deactivated.
We probably want to mention this in the release notes, but I think it is OK to be a breaking …
=> Return the proper 403 Forbidden error during errors with JWT logins.

changelog.d/7851.misc, synapse/handlers/e2e_keys.py, synapse/handlers/e2e_room_keys.py, tests/handlers/test_e2e_keys.py, tests/handlers/test_e2e_room_keys.py
These were straightforward, I added `defer.ensureDeferred` to the tests until those are converted from using `inlineCallbacks`. The diff kind of became a disaster once `black` got a hold of it. 😢
=> Convert E2E key and room key handlers to async/await

changelog.d/7853.misc, synapse/http/client.py, synapse/server.pyi, tests/replication/_base.py, tests/replication/test_client_reader_shard.py, tests/replication/test_federation_sender_shard.py, tests/server.py
This fixes a bug in the client reader sharding tests where the register requests were always going to master instead of the workers (due to a typo in using `self.resource` rather than `resource`). Fixing that leads to timeouts as the `/register` paths try and send a HTTP replication request to master, which we didn't handle.
Currently, the tests are set up so that you need to explicitly call `self.handle_http_replication_attempt()` *after* a connection attempt has been made. This is impossible to do if sending a request, as `render` blocks until the request is completed. We could solve this by trying and making it possible to `render` call `self.handle_http_replication_attempt` at the same time, but it feels nicer to instead have the test base class automatically handle the http …
=> Fix client reader sharding tests

changelog.d/7847.feature, docs/admin_api/user_admin_api.rst, synapse/handlers/deactivate_account.py, synapse/rest/admin/users.py, tests/rest/admin/test_user.py
Fixes #7220
This allows accounts to be re-activated via the admin API. There is no effort to re-join rooms, etc. it simply sets the flag on the database to set the account as active. The API requires that the password is set as well, to allow the account to log back in.
This updates the `PUT /_synapse/admin/v2/users/<user_id>` endpoint, but there's also a `POST /_synapse/admin/v1/deactivate/<user_id>` account. We can add a `POST /_synapse/admin/v1/activate/<user_id>` endpoint, but I don't really see the point, it would essentially be identical (minus you don't pass a `"deactivated": false` in the JSON).
=> Allow accounts to be re-activated from the admin APIs

changelog.d/7856.misc, synapse/handlers/typing.py, tests/handlers/test_typing.py
This might give us a small performance improvement, since `get_users_in_room` will be cached at a higher layer (and doesn't do state res if it isn't cached).
=> Use store.get_users_in_room rather than state handler in typing for speed

changelog.d/7854.bugfix, synapse/storage/data_stores/main/state.py
When considering rooms to clean up in `delete_old_current_state_events`, skip rooms which we are creating, which otherwise look a bit like rooms we have left.
Fixes #7834.
=> Avoid brand new rooms in `delete_old_current_state_events`

changelog.d/7866.bugfix, scripts/synapse_port_db, synapse/handlers/register.py, synapse/storage/data_stores/main/registration.py, synapse/storage/data_stores/main/schema/delta/58/11user_id_seq.py, synapse/storage/data_stores/state/store.py, synapse/storage/engines/_base.py, synapse/storage/engines/postgres.py, synapse/storage/engines/sqlite.py, synapse/storage/util/id_generators.py, synapse/storage/util/sequence.py
The idea here is to use a Postgres sequence to generate guest user IDs. First do some refactoring to make the existing stuff that is backed by sequences reusable.
=> Fix guest user registration with lots of client readers

changelog.d/7869.feature, synapse/app/generic_worker.py, synapse/config/workers.py, synapse/federation/federation_server.py, synapse/handlers/typing.py, synapse/replication/tcp/handler.py, synapse/replication/tcp/streams/_base.py, synapse/rest/client/v1/room.py, synapse/server.py, synapse/server.pyi
A lot of this is various bits of rejigging, so probably worth looking at the commits.
=> Allow moving typing off master

changelog.d/7859.bugfix, synapse/handlers/federation.py
We shouldn't allow others to make_join through us if we've left the room. By analogy with the behaviour when the server has *never* been in the room, reject such attempts with a 404.
Fixes #7835. Fixes #6958.
See also https://github.com/matrix-org/matrix-doc/pull/2688.
=> Reject attempts to join empty rooms over federation

changelog.d/7861.misc, synapse/replication/tcp/handler.py
When we get behind on replication, we tend to stack up background processes behind a linearizer. Bg processes are heavy (particularly with respect to prometheus metrics) and linearizers aren't terribly efficient once the queue gets long either.
A better approach is to maintain a queue of requests to be processed, and nominate a single process to work its way through the queue.
Fixes: #7444
=> Optimise queueing of inbound replication commands

docs/reverse_proxy.md
I'm pretty sure there's no technical reason these have to be distinct server blocks, so collapse into one and go with the more terse location block.
Signed-off-by: Luke W Faraone <luke@faraone.cc>
=> Combine nginx federation server blocks

changelog.d/7849.misc, synapse/storage/_base.py, synapse/storage/background_updates.py, synapse/storage/data_stores/main/account_data.py, synapse/storage/data_stores/main/appservice.py, synapse/storage/data_stores/main/deviceinbox.py, synapse/storage/data_stores/main/devices.py, synapse/storage/data_stores/main/e2e_room_keys.py, synapse/storage/data_stores/main/end_to_end_keys.py, synapse/storage/data_stores/main/event_push_actions.py, synapse/storage/data_stores/main/events.py, synapse/storage/data_stores/main/events_bg_updates.py, synapse/storage/data_stores/main/events_worker.py, synapse/storage/data_stores/main/group_server.py, synapse/storage/data_stores/main/push_rule.py, synapse/storage/data_stores/main/pusher.py, synapse/storage/data_stores/main/receipts.py, synapse/storage/data_stores/main/room.py, synapse/storage/data_stores/main/roommember.py, synapse/storage/data_stores/main/search.py, synapse/storage/data_stores/main/tags.py, synapse/storage/data_stores/main/ui_auth.py
~~This removes the last usages of importing json from canonicaljson in order to get the simplejson package.~~
This consistently uses the `db_to_json` helper in our storage code. So a follow-on to #7836 / #7802 and related to #7674.
=> Consistently use `db_to_json` to convert from database values to JSON objects.

changelog.d/7842.feature, docs/admin_api/rooms.md, synapse/rest/admin/__init__.py, synapse/rest/admin/rooms.py, tests/rest/admin/test_room.py
Signed-off-by: Michael Albert <michael.albert@awesome-technologies.de>
=> Add room members admin endpoint

changelog.d/7868.misc, synapse/app/generic_worker.py, synapse/app/homeserver.py, synapse/federation/federation_client.py
This converts a bit of a hodgepodge of things to async/await:
* The parts of `synapse.app` that can be converted to async/await (the remaining `inlineCallbacks` get called directly from Twisted, so I think they have to remain `Deferreds`?)
* The last remaining `inlineCallabacks` in the federation client.
=> Convert synapse.app and federation client to async/await.

changelog.d/7871.misc, synapse/handlers/device.py, synapse/util/distributor.py, tests/handlers/test_device.py, tests/handlers/test_e2e_keys.py, tests/test_federation.py
A lot of this is pretty normal, but there's a few things to note:
* A couple spots we were yielding on functions that returned normal values.
* A bunch of tests were fixed to add `defer.succeed` or `defer.ensureDeferred`.
* The `Signal` / `Distributor` code was updated to properly handle receiving an awaitable (by using `defer.ensureDeferred`, which feels non-ideal, but I think we can fix this in the future?)
=> Convert device handler to async/await

changelog.d/7881.misc, synapse/storage/data_stores/main/events_worker.py
It's somewhat expected for us to have unknown room versions in the
database due to room version experiments.
=> Change "unknown room ver" logging to warning.

changelog.d/7858.misc, docs/sample_config.yaml, synapse/config/server.py, synapse/rest/client/v2_alpha/_base.py
This changes the default value of `filter_timeline_limit` from -1 (no limit) to 500. The 500 was chosen mostly arbitrarily, but could probably use some more thought of what it should be!
Fixes #7733
=> Add a default limit to get/sync operations

changelog.d/7880.bugfix, synapse/handlers/device.py
=> Fix TypeError in synapse.notifier

changelog.d/7882.misc, synapse/replication/slave/storage/deviceinbox.py, synapse/storage/data_stores/main/__init__.py, synapse/storage/data_stores/main/deviceinbox.py
It serves no purpose and updating everytime we write to the device inbox
stream means all such transactions will conflict, causing lots of
transaction failures and retries.
=> Stop using 'device_max_stream_id'

changelog.d/7839.docker, docker/Dockerfile, docker/start.py
As mentioned in https://github.com/matrix-org/synapse/pull/7397, switching to a debian base should help with multi-arch work to save time on compiling. This is unashamedly based on https://github.com/matrix-org/synapse/pull/6373, but without the extra functionality. Switch python version back to generic 3.7 to always pull the latest. Essentially, keeping this as small as possible. The image is bigger though unfortunately.
=> Switch to Debian:Slim from Alpine for the docker image

changelog.d/7872.bugfix, synapse/logging/opentracing.py
I *think* this is the proper fix for the `@trace` decorator with async functions, but I'm not 100% sure.
I think there might be an issue open for some things missing from tracing, which could be this?
The diff should be better without whitespace changes.
=> Fix the trace function for async functions.

changelog.d/7895.bugfix, contrib/experiments/test_messaging.py
=> Fix deprecation warning due to invalid escape sequences

changelog.d/7889.doc, docs/sample_config.yaml, synapse/config/database.py
The [postgres setup docs](https://github.com/matrix-org/synapse/blob/develop/docs/postgres.md#set-up-database) recommend setting up your database with user `synapse_user`.
However, uncommenting the postgres defaults in the sample config leave you with user `synapse`.
This PR switches the sample config to recommend `synapse_user`. Took a me a second to figure this out, so assume this will beneficial to others.
=> Change sample config's postgres user to synapse_user

changelog.d/7919.misc, synapse/res/templates/mail-Element.css, synapse/res/templates/notice_expiry.html, synapse/res/templates/notif_mail.html
Use Element CSS and logo in notification emails when app name is Element.
Couldn't find a branch for this so persisting from EMS.
=> Element CSS and logo in email templates

changelog.d/7912.misc, synapse/federation/transport/server.py, synapse/handlers/room_list.py
This converts the remaining `inlineCallbacks` and `cachedInlineCallbacks` in the room list handler to async / await.
It seems like the appropriate is:
```python
@cachedInlineCallbacks
def foo():
yield blah
```
becomes the following:
```python
@cached
async def foo():
await blah
```
=> Convert room list handler to async/await.

changelog.d/7927.misc, synapse/rest/client/v2_alpha/sync.py
... it's a load of work which may be entirely redundant.
=> Skip serializing /sync response if client has disconnected

changelog.d/7934.doc, docs/ACME.md
As per https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430
=> Update the dates for ACME v1 EOL

changelog.d/7884.misc, synapse/handlers/message.py, tests/events/test_snapshot.py, tests/replication/tcp/streams/test_events.py, tests/storage/test_roommember.py, tests/storage/test_state.py, tests/test_utils/event_injection.py, tests/test_visibility.py, tests/unittest.py, tests/utils.py
This is the last big piece of `synapse.handlers` to convert. It was a bit more involved since it is touch in so many places. I converted this method by method as separate commits since I had previously tried to convert this and failed.
The two interesting commits are 48c7f925edcf5c97e98235a1a7241c29c94decd6 and e76d407893509fe7e0f5469ce7bda0455508daa1. The rest are pretty mechanical.
=> Convert the message handler to async/await

changelog.d/7908.feature, synapse/handlers/deactivate_account.py, synapse/storage/data_stores/main/user_erasure_store.py
A follow-up to #7847 (which fixed #7220) to fix a couple of bugs, now the re-activated user is:
* Re-added to the user directory.
* Removed from the `erased_users` table.
=> Follow-up to admin API to re-activate accounts

changelog.d/7874.misc, synapse/http/federation/matrix_federation_agent.py, synapse/http/federation/srv_resolver.py, tests/http/federation/test_matrix_federation_agent.py, tests/http/federation/test_srv_resolver.py
This converts the federation agent and SRV resolver to async/await.
Note that `MatrixFederationAgent` was not converted since that needs to correspond to the `IAgent` interface.
=> Convert the federation agent and related code to async/await.

README.rst, changelog.d/7933.doc
At the moment, the list and the first paragraph promote sqlite, but the third paragraph says "Almost all should use postgresql".  We should encourage people to deploy postgres by ordering the text, even if sqlite is still the default on a unconfigured server.
=> Reorder database docs to promote postgresql.

changelog.d/7930.feature, synapse/federation/transport/server.py
For inbound federation requests, if a given remote server makes too many
requests at once, we start stacking them up rather than processing them
immediatedly.
However, that means that there is a fair chance that the requesting server will
disconnect before we start processing the request. In that case, if it was a
read-only request (ie, a GET request), there is absolutely no point in
building a response (and some requests are quite expensive to handle).
Even in the case of a POST request, one of two things will happen:
* Most likely, the requesting server will retry the request and we'll get the
information anyway.
* Even if it doesn't, the requesting server has to assume that we didn't get
the memo, and act accordingly.
In short, we're better off aborting the request at this point rather …
=> Abort federation requests if the client disconnects early

changelog.d/7931.feature, synapse/federation/federation_server.py
If we send out an event which refers to `prev_events` which other servers in
the federation are missing, then (after a round or two of backfill attempts),
they will end up asking us for `/state_ids` at a particular point in the DAG.
As per https://github.com/matrix-org/synapse/issues/7893, this is quite
expensive, and we tend to see lots of very similar requests around the same
time.
We can therefore handle this much more efficiently by using a cache, which (a)
ensures that if we see the same request from multiple servers (or even the same
server, multiple times), then they share the result, and (b) any other servers
that miss the initial excitement can also benefit from the work.
[It's interesting to note that `/state` has a cache for exactly this
reason. `/state` is now essentially …
=> Put a cache on `/state_ids`

changelog.d/7935.misc, docs/password_auth_providers.md, synapse/handlers/auth.py, synapse/handlers/ui_auth/checkers.py
This updates the built in auth providers to use async/await.
The callers were already converted to async/await so this shouldn't cause an issue. The third-party providers should still work (since you can `await` a `Deferred`).
I don't find the documentation here to be great:
* I've updated it to refer to `Awaitables` instead of `Deferred`
* I reformatted it so that it isn't all inside of block quotes.
This also fixes a bug I found by reading the documentation closer -- `on_logged_out` **may** return an `Awaitable`, but doesn't have to.
=> Update the auth providers to be async.

changelog.d/7939.misc, synapse/federation/sender/__init__.py, synapse/handlers/presence.py
Converts a couple of helpers to async/await and adds type info.
Not sure why I skipped this initially, but it was straightforward now (probably was a cross-dependency between modules or something).
=> Convert presence handler helpers to async/await.

changelog.d/7886.misc, synapse/http/server.py, tests/test_server.py
Fixes #7857 by returning an empty body for `OPTIONS`.
I was unsure about including the `Cache-Control` header, but it is set on JSON responses...
=> Return an empty body for OPTIONS requests.

changelog.d/7873.misc, synapse/rest/media/v1/_base.py, synapse/rest/media/v1/media_storage.py, tests/rest/media/v1/test_media_storage.py
So this converts *most* of the remaining media code to async/await. The remaining pieces after this are the `StorageProvider` and sub-classes, but I think those need changes to the S3 code at the same time? I'm not really sure about that.
I've held off on pushing these changes for a while since the code surrounding them is confusing and I was not super confident. Please review thoroughly (and also consider if any of this will affect the S3 provider or other third-party providers).
=> Convert more of the media code to async/await

changelog.d/7945.misc, synapse/handlers/admin.py, synapse/handlers/e2e_keys.py, synapse/handlers/federation.py, synapse/handlers/identity.py, synapse/handlers/room.py, synapse/handlers/search.py, synapse/handlers/sync.py, tox.ini
Some comments refer to functions returning a `Deferred` which have now been converted to async. This tries to clean those up (and some other type information).
This only touches comments and type hints.
=> Fix up types and comments that refer to Deferreds.

changelog.d/7942.misc, synapse/api/auth.py, synapse/events/builder.py, synapse/federation/sender/__init__.py, synapse/handlers/presence.py, synapse/push/bulk_push_rule_evaluator.py, synapse/state/__init__.py, synapse/state/v1.py, synapse/state/v2.py, synapse/storage/data_stores/main/push_rule.py, synapse/storage/data_stores/main/roommember.py, synapse/storage/data_stores/main/user_directory.py, synapse/storage/persist_events.py, tests/federation/test_federation_sender.py, tests/state/test_v2.py, tests/storage/test_room.py, tests/test_state.py, tests/test_utils/__init__.py
This one got larger than I wanted, but should be reviewable commit by commit.
It converts `synapse.state` to async/await.
There was still a decent number of places that hooked into this, so I ended up adding quite a few `ensureDeferred` 😢 
One question I had was that we use `clock.sleep(0)` in some of the v2 algorithm, I wonder if that should be `asyncio.sleep` instead? `clock.sleep` returns a `Deferred` so it will work OK.
=> Convert state resolution to async/await

changelog.d/7920.feature, synapse/rest/media/v1/preview_url_resource.py, tests/rest/media/v1/test_url_preview.py
Fixes #7643.
This fixes Twitter previews by querying for oEmbed information instead of the originally requested URL. It is mostly generic (so additional oEmbed endpoints can be added), but it isn't end-user configurable at the moment.
The gist of the changes to the preview algorithm is:
1. Check if the requested URL matches any of the oEmbed patterns, if so:
1. Query the oEmbed endpoint for the JSON metadata.
2. If the metadata is a photo or has a thumbnail, use that instead of the original URL and continue the normal preview code.
3. If the metadata is HTML, use the HTML directly.
A big section of `_download_url` got indented, but was otherwise unchanged.
A couple of questions I have:
* Does it make sense to make this user configurable?
* Parsing of the globs to regular expressions at …
=> Support oEmbed for media previews.

changelog.d/7950.misc, synapse/handlers/federation.py, synapse/handlers/message.py
This cleans-up some code I had ignored when converting the federation handler to async/await. I think it isn't necessary once this code got converted, but I'm not really sure. It was added in #3989 by @richvdh so I'm hoping he can confirm this shouldn't be necessary anymore!
=> Remove hacky error handling for inlineDeferreds.

changelog.d/7959.bugfix, synapse/app/generic_worker.py, synapse/replication/tcp/client.py, synapse/server.pyi
Handling of incoming typing stream updates from replication was not
hooked up on master, effecting set ups where typing was handled on a
different worker.
This is really only a problem if the master process is also handling
sync requests, which is unlikely for those that are at the stage of
moving typing off.
The other observable effect is that if a worker restarts or a
replication connect drops then the typing worker will issue a
`POSITION typing`, triggering master process to try and stream *all*
typing updates from position 0.
Fixes #7907
=> Fix typing replication not being handled on master

changelog.d/7961.bugfix, synapse/logging/opentracing.py, synapse/logging/scopecontextmanager.py
In particular `start_active_span` returns a scope, which is meant to be a context manager that returns itself, but it didn't. This fixes that.
We also clean some other stuff up, we don't actually need to set `error=True` tag manually, that happens for us, and there is no point having the if opentracing guard there given we both have it up a layer and `start_active_span` returns a null context manager anyway.
Broke in #7872 
Stack trace:
```
AttributeError: 'NoneType' object has no attribute 'span'
File "synapse/http/server.py", line 228, in _async_render_wrapper
File "synapse/http/server.py", line 399, in _async_render
File "synapse/rest/client/v2_alpha/room_keys.py", line 134, in on_PUT
ret = …
```
=> Fix error reporting when using `opentracing.trace`

changelog.d/7948.misc, synapse/push/action_generator.py, synapse/push/bulk_push_rule_evaluator.py, synapse/push/httppusher.py, synapse/push/presentable_names.py, synapse/push/push_tools.py, synapse/push/pusherpool.py, synapse/storage/data_stores/main/event_push_actions.py, tests/replication/slave/storage/test_events.py, tests/storage/test_event_push_actions.py
This was pretty straightforward, I also ended up converting a store function since it was sometimes returning `None` and sometimes a `Deferred`.
=> Convert push to async/await.

changelog.d/7951.misc, synapse/groups/attestations.py, synapse/visibility.py, tests/test_visibility.py
This was some standalone code that was easy to convert so I went ahead and did it.
=> Convert groups and visibility code to async / await.

changelog.d/7947.misc, synapse/rest/media/v1/_base.py, synapse/rest/media/v1/media_repository.py, synapse/rest/media/v1/media_storage.py, synapse/rest/media/v1/preview_url_resource.py, synapse/rest/media/v1/storage_provider.py
This converts the remaining piece of the media repo code to async / await (the storage provider classes).
Note that 3rd-party providers may still use `Deferreds` here (see #7873).
This also adds a bunch of type hints.
I didn't see any docs to update about how to implement a storage provider.
=> Finish converting the media repo code to async / await.

changelog.d/7965.misc, scripts-dev/check_line_terminators.sh
This PRs adds a script to check for unix-line terminators in the repo. It will be used to address https://github.com/matrix-org/synapse/issues/7943 by adding the check to CI.
I've changed the original script slightly as proposed in https://github.com/matrix-org/pipelines/pull/81#discussion_r460580664 by:
- changing `{`, `}` braces to `(`, `)` as the former did not seem to be correct syntax(?)
- noted `#!/bin/bash` (as opposed to `#!/bin/sh`) at the top of the file as `$'...'` [is not POSIX compliant](https://github.com/koalaman/shellcheck/wiki/SC2039#c-style-escapes)
Edit:
- Added `-I` to the `grep` invocation to ignore binary files which often had `\r` in them.
Unfortunately, upon running this script, `grep` seems to consider `*.pyc` files as having unix terminators as they contain `\r` …
=> Add script for finding files with unix line terminators

changelog.d/7967.bugfix, synapse/replication/http/__init__.py
IIRC this doesn't break tests because its only hit on reconnection, or something.
Basically, when a process needs to fetch missing updates for the `typing` stream it needs to query the writer instance via HTTP (as we don't write typing notifications to the DB), the problem was that the endpoint (`streams`) was only registered on master and specifically not on the typing writer worker.
=> Typing worker needs to handle stream update requests

changelog.d/7970.misc, scripts-dev/check_line_terminators.sh
If there are *no* files with CRLF line endings, then the xargs exits with a
non-zero exit code (as expected), but then, since that is the last thing to
happen in the script, the script as a whole exits non-zero, making the whole
thing fail.
using `if/then/fi` instead of `&& (...)` means that the script exits with a
zero exit code.
=> Fix exit code for `check_line_terminators.sh`

changelog.d/7936.misc, synapse/__init__.py, synapse/python_dependencies.py
* Updates canonicaljson minimum version to 1.2.0 ~~(currently to a branch, but we'll need to make this a release)~~.
* Calls the new API from canonicaljson to specify using the standard library JSON library (instead of simplejson).
Fixes #7674
=> Use the standard library JSON.

changelog.d/7952.misc, synapse/storage/database.py
Idea from https://github.com/matrix-org/synapse-dinsic/issues/49
It looks as if a lot more log lines in this file could be put in the SQL and transaction loggers instead of keeping them in the default logger. Apparently the 'Starting db txn ...' and 'Starting db connection ...' lines can be quite spammy, so it'd be nice to move them out of the default logger.
=> Move some log lines from default logger to sql/transaction loggers

changelog.d/7963.misc, synapse/storage/persist_events.py, synapse/storage/purge_events.py, synapse/storage/state.py, tests/storage/test_purge.py, tests/storage/test_room.py, tests/storage/test_state.py, tests/test_visibility.py, tests/utils.py, tox.ini
This converts the high-level storage interfaces to async/await:
* Purge events
* Persist events
* State helpers
Overall this is pretty straightforward, it is just the next layer down starting to be converted. Any additional `defer.ensureDeferreds` are only added to tests.
This also includes some type changes which mypy complained about once these were made async.
=> Convert storage layer to async/await.

changelog.d/7971.misc, synapse/handlers/saml_handler.py
This adds a log line which simply states when the SAML session was created. I think this will allow us to more concretely see why sessions are "unsolicited" in #7056. I think by comparing the times from this line to the unsolicited one we can hopefully determine:
* Is this a really old session someone is coming back to?
* Have we never seen this ID before?
* If it still seems valid, was there a restart? A different working? Something else?
=> Add additional logging for SAML sessions.

changelog.d/7978.bugfix, synapse/storage/data_stores/main/purge_events.py
This attempts to fix #7693 by adding the `event_relations` table to the list of table to purge events from in `PurgeEventsStore.purge_history`.
I think this is sane, but not sure how well tested this code-path is.
=> Remove from the event_relations table when purging historical events.

changelog.d/7979.misc, synapse/http/client.py, synapse/http/matrixfederationclient.py
While working on #7674 I had missed that the `phrase` property of a treq responses is bytes, not a string. This gets used to create `HttpResponseException`, which doesn't match what is expected there.
The `phrase` gets set as `HttpResponseException.msg`, which can be JSON serialized when `to_synapse_error` is called and the original error body did not have an `error` property:
https://github.com/matrix-org/synapse/blob/35450519dee869e5641cff94ed35acd3bdaa8a42/synapse/api/errors.py#L601-L602
Reported from @richvdh with the stack:
```
During handling of the above exception, another exception occurred:
File "/opt/synapse/synapse/synapse/http/server.py", line 232, in _async_render_wrapper
self._send_response(request, code, response)
File …
```
=> Ensure the msg property of HttpResponseException is a string.

changelog.d/7969.doc, docs/sample_config.yaml, docs/synctl_workers.md, docs/workers.md, synapse/app/generic_worker.py, synapse/config/federation.py, synapse/config/homeserver.py, synapse/config/logger.py, synapse/config/redis.py, synapse/config/workers.py, synapse/federation/send_queue.py, synapse/federation/sender/__init__.py, synapse/federation/sender/per_destination_queue.py, synapse/storage/data_stores/main/stream.py
We also add some of the new config options to the sample config.
This also updates the wording to recommend using Redis and removing suggestion that it is experimental.
Apologies in advance that me bad at words.
=> Update worker docs with recent enhancements 

changelog.d/7981.misc, synapse/app/generic_worker.py, synapse/push/httppusher.py
Ensure that both the main process and worker version of `remove_pusher` is awaitable.
This calls either the [main process version](https://github.com/matrix-org/synapse/blob/f2e38ca86711a8f80cf45d3182e426ed8967fc81/synapse/server.py#L597) or [the worker version](https://github.com/matrix-org/synapse/blob/84d099ae1192af0f38d26f9a32e38bd4c0ad304e/synapse/app/generic_worker.py#L631), which return different things.
Should fix https://sentry.matrix.org/sentry/synapse-matrixorg/issues/119196/
=> Ensure that remove_pusher is always async

changelog.d/7976.misc, synapse/storage/data_stores/main/event_push_actions.py, synapse/storage/data_stores/main/room.py, synapse/storage/data_stores/main/state.py, synapse/storage/data_stores/main/stats.py, synapse/storage/data_stores/state/store.py, synapse/storage/state.py, tests/storage/test_event_push_actions.py, tests/storage/test_room.py, tests/storage/test_state.py
This starts converting `synapse.storage.data_stores` to async/await.
The files converted are somewhat arbitrary, but this seemed to get enough changes that it was worth putting a PR up for it.
This doesn't quite get us deep enough to get out of `inlineCallbacks` since everything eventually hits `runInteraction`, but getting close....
=> Convert some of the data store to async

changelog.d/7973.misc, synapse/appservice/__init__.py, synapse/appservice/api.py, synapse/appservice/scheduler.py, synapse/handlers/appservice.py, tests/appservice/test_appservice.py, tests/appservice/test_scheduler.py, tests/handlers/test_appservice.py
Converts `synapse.appservice` package to async / await.
This was fairly straightforward, minus the tests which needed quite a bit of work.
=> Convert appservice to async.

changelog.d/7975.misc, contrib/cmdclient/console.py, synapse/crypto/keyring.py, synapse/federation/federation_client.py, synapse/federation/sender/__init__.py, synapse/federation/transport/client.py, synapse/handlers/groups_local.py, synapse/http/matrixfederationclient.py, tests/crypto/test_keyring.py, tests/federation/test_complexity.py, tests/federation/test_federation_sender.py, tests/handlers/test_directory.py, tests/handlers/test_profile.py, tests/http/test_fedclient.py, tests/replication/test_federation_sender_shard.py, tests/rest/admin/test_admin.py, tests/rest/key/v2/test_remote_key_resource.py, tests/test_federation.py
This converts the federation client and helper code to async/await, this code is really 3 layers:
* `federation.federation_client`
* `federation.transport.client`
* `http.matrixfederationclient`
All three are done as part of this (as well as a couple remaining methods in the `federation.sender`).
Most of this was straightforward, although the `groups_local` code was a bit tricky (and the tests took a bit to pass).
=> Convert federation client to async/await.

changelog.d/7980.bugfix, synapse/handlers/room_member.py
Thanks to some slightly overzealous cleanup in the `delete_old_current_state_events` database migration, it's possible to end up with no `event_forward_extremities` in a room where we have outstanding local invites. The user would then get a "no create event in auth events" when trying to reject the invite.
We can hack around it by using the dangling invite as the prev event.
Fixes: #7139
=> Fix invite rejection when we have no forward-extremeties

changelog.d/7998.doc, docs/admin_api/shutdown_room.md
These docs were tested successfully in production by a customer, so it's probably fine.
=> Add docs for undoing room shutdowns

changelog.d/8008.feature, docs/sample_config.yaml, synapse/config/ratelimiting.py, synapse/handlers/room_member.py, tests/utils.py
We split this up into two, one for local and one for remote joins. This is mainly because remote joins are so much more expensive (and sometimes you have server set to auto join users to a bunch of rooms).
I'm very open to bikeshedding on the defaults.
This is based off of master as we have some people that would like to apply this (and develop is currently broken).
=> Add ratelimiting on joins

changelog.d/7996.bugfix, synapse/server_notices/consent_server_notices.py, synapse/server_notices/resource_limits_server_notices.py, synapse/server_notices/server_notices_manager.py, synapse/server_notices/server_notices_sender.py, synapse/server_notices/worker_server_notices_sender.py, tox.ini
A bunch of `synapse.server_notices` still referred to Deferreds when they were already async.
This also adds some type info and does a few other things I'll call out in comments.
=> Fix some comments and types in service notices

changelog.d/7989.misc, synapse/app/homeserver.py, synapse/handlers/acme.py
This isn't terribly exciting, but is the last piece of `synapse.handlers`, so I figured we should do it for ✔️ .
=> Convert ACME code to async/await

changelog.d/7987.misc, synapse/handlers/register.py, synapse/replication/http/_base.py, synapse/replication/http/devices.py, synapse/replication/http/federation.py, synapse/replication/http/login.py, synapse/replication/http/membership.py, synapse/replication/http/presence.py, synapse/replication/http/register.py, synapse/replication/http/send_event.py, synapse/replication/http/streams.py
This converts the HTTP replication code to async/await.
The way this gets used is a little obtuse (clients get created via the `make_client` call, this now returns an async function instead of a `inlineCallbacks` function).
I also made `_serialize_payload` async since it sometimes returned a `Deferred` and sometimes did not.
=> Convert replication code to async/await.

changelog.d/8003.misc, synapse/crypto/keyring.py, tests/crypto/test_keyring.py
This converts `synapse.crypto` to async/await. I was having issues with the tests here, so there's a bunch of commits (like a function each), but the overall changes are reasonable to look at.
=> Convert the crypto module to async/await

changelog.d/7999.bugfix, synapse/http/server.py, synapse/http/servlet.py, tests/test_server.py
In order to handle `HEAD` requests properly in our `_AsyncResource` we need to handle it for `DirectServe*Resource` and then also for `JsonResource` separately.
* Adds a default `_async_render_HEAD` method which just calls `_async_render_GET` (this is essentially [Twisted's implementation](https://github.com/twisted/twisted/blob/twisted-20.3.0/src/twisted/web/resource.py#L268-L275), but made async).
* For each servlet: when register `on_GET`, also register `on_HEAD` if there isn't an override for `on_HEAD`.
* Updates the CORS headers to say they supported `HEAD`.
I debated if it made more sense to just convert the `HEAD` method to `GET` in [`JsonResource._get_handler_for_request`](https://github.com/matrix-org/synapse/blob/c4e88397bc477d41d4920b29fde96ea33f39d6f5/synapse/http/server.py#L37 …
=> Implement handling of HEAD requests

changelog.d/7977.bugfix, synapse/handlers/stats.py, synapse/storage/data_stores/main/schema/delta/58/12room_stats.sql, synapse/storage/data_stores/main/stats.py, tests/handlers/test_stats.py, tests/rest/client/v1/utils.py
Fixes https://github.com/matrix-org/synapse/issues/1294
`StatsHandler` handles updates to the `current_state_delta_stream`, and updates room stats such as the amount of state events, joined users, etc.
However, it counts every new join membership as a new user entering a room (and that user being in another room), whereas it's possible for a user's membership status to go from join -> join, for instance when they change their per-room profile information.
This PR adds a check for join->join membership transitions, and bails out early, as none of the further checks are necessary at that point.
Due to this bug, membership stats in many rooms have ended up being wildly larger than their true values. I am not sure if we also want to include a migration step which recalculates these statistics …
=> Prevent join->join membership transitions changing member count

changelog.d/8001.misc, synapse/handlers/identity.py
Fixes https://github.com/matrix-org/synapse/issues/5253
We've [decided](https://github.com/matrix-org/synapse/issues/5253#issuecomment-665976308) to remove the signature check for v1 lookups. See the below discussion:
The signature check has been removed in v2 lookups. v1 lookups are currently deprecated. As mentioned in the above linked issue, this verification was causing deployments for the vector.im and matrix.org IS deployments, and this change is the simplest solution, without being unjustified.
Implementations are encouraged to use the v2 lookup API as it has [increased privacy benefits](https://github.com/matrix-org/matrix-doc/pull/2134).
=> Remove signature check on v1 identity server lookups

changelog.d/8011.misc, synapse/app/_base.py, synapse/python_dependencies.py, synapse/util/daemonize.py
This has long been something I've wanted to do. Basically the `Daemonize` code
is both too flexible and not flexible enough, in that it offers a bunch of
features that we don't use (changing UID, closing FDs in the child, logging to
syslog) and doesn't offer a bunch that we could do with (redirecting stdout/err
to a file instead of /dev/null; having the parent not exit until the child is
running).
As a first step, I've lifted the Daemonize code and removed the bits we don't
use. This should be a non-functional change. Fixing everything else will come
later.
The reveiewer is invited to compare with https://github.com/thesharp/daemonize/blob/master/daemonize.py.
=> re-implement daemonize

changelog.d/8014.misc, synapse/handlers/initial_sync.py, synapse/handlers/pagination.py, synapse/handlers/room.py, synapse/handlers/search.py, synapse/handlers/sync.py, synapse/notifier.py, synapse/storage/data_stores/main/stream.py, synapse/streams/events.py, tests/server_notices/test_resource_limits_server_notices.py
This is a tiny PR, but it was standalone so I figure it was worth putting up.
Notable that most of these functions weren't returning a `Deferred` anymore, it seems only the `RoomEventSource.get_current_key()` does. The rest just return integers.
=> Convert streams to async.

changelog.d/8016.misc, synapse/appservice/api.py, synapse/http/client.py
This was straightforward to convert now that (almost) call callers have been converted.
=> Convert the SimpleHttpClient to async.

changelog.d/8027.misc, synapse/rest/media/v1/media_storage.py, synapse/rest/media/v1/storage_provider.py
We added some code to handle media storage providers which don't follow the interface (e.g. the S3 storage provider) in #7873. Those were necessary until the `StorageProviderWrapper` was converted, as that passed through some return values directly from each storage provider. #7947 converted the `StorageProviderWrapper`, but failed to add the same guards as #7873. This fixes all of the above code:
* The `MediaRepository` code and `MediaStorage` code are corrected to refer to `StorageProviderWrapper`, which always has proper async functions.
* The `StorageProviderWrapper` has guards added to allow underlying backends to not match the interface.
This fixes a regression from #7947, which is not yet released.
=> Fix async/await calls for broken media providers.

changelog.d/8024.misc, scripts-dev/check-newsfragment
This PR:
* Reduces the amount of noise in the `check-newsfragment` CI output by hiding the dependency installation output by default.
* Prints a link to the changelog/debian changelog section of the contributing guide if an error is found.
Previous output:
New output:
=> Spruce up the check-newsfragment CI output

.github/ISSUE_TEMPLATE/BUG_REPORT.md
apparently it was moved outside the comment in #7379. honestly, if people don't read it inside the comment, I can't see they are going to read it outside either. Meanwhile having it outside the comment means that 50% of our bug reports start with "**THIS IS NOT A SUPPORT CHANNEL!!!!1111!!one**".
=> bug report template: move comments into comment

changelog.d/8011.bugfix, changelog.d/8011.misc, changelog.d/8012.bugfix, synapse/util/daemonize.py
This solves the problem that the first few lines are logged twice on matrix.org. Hopefully the comments explain it.
~~Based on #8011.~~
=> Stop the parent process flushing the logs on exit

changelog.d/8000.doc, docs/systemd-with-workers/workers/federation_reader.yaml, docs/workers.md
This was actually part of https://github.com/matrix-org/synapse/pull/7969, but got lost in the rebase.
=> Fixup worker doc (again)

changelog.d/8009.misc, synapse/api/errors.py, synapse/handlers/auth.py, synapse/rest/client/v2_alpha/account.py, synapse/rest/client/v2_alpha/register.py, tests/rest/client/v2_alpha/test_register.py
This has a few tweaks to the register (and modify password) endpoints that should improve performance a bit:
1. Pre-stores whether registration is enabled instead of checking the config each time.
2. Only hash passwords when necessary:
1. If UI auth fails (and might be completed in a subsequent call).
2. Right before registration, if a password was provided.
It also has a couple of other changes:
1. Re-organizes some code in the register endpoint and clarifies comments.
2. Renames `AuthHandler.check_auth` to `AuthHandler.check_ui_auth` to avoid clashes with `UserInteractiveAuthChecker`.
Fixes #7956
=> Improve register performance

changelog.d/8032.misc, synapse/handlers/appservice.py, synapse/http/site.py, synapse/metrics/background_process_metrics.py
I'm not really sure if this makes sense to do or not, but this PR converts the inner function of `run_as_background_process` into an async function.
We still need to cast the returned value to a `Deferred` though since it sometimes gets used in Twisted APIs. I feel like this might cause the `run` coroutine to not always be awaited.
This also includes a couple of other minor fixes that I can move to a separate PR if we decide this doesn't make sense to do.
=> Convert run_as_background_process inner function into an async function

changelog.d/8035.misc, synapse/util/metrics.py, synapse/util/retryutils.py, tests/util/test_retryutils.py
* Converts `get_retry_limiter` to async
* Converts `measure_func` to async (this one only seems to be used to wrap async functions but maybe we don't want to lose the ability to wrap inlineDeferreds here, not sure!)
=> Convert some util functions to async

changelog.d/8048.feature, docs/reverse_proxy.md, synapse/app/generic_worker.py, synapse/app/homeserver.py, synapse/http/site.py, synapse/rest/health.py, tests/rest/test_health.py
This gets added under `/health` on *every* HTTP listener. Requests to `/health` get logged at DEBUG rather than INFO.
Question: Where is the best place to document this?
Fixes #8017
=> Add health check endpoint

changelog.d/8044.misc, synapse/rest/client/v2_alpha/register.py, synapse/rest/consent/consent_resource.py, synapse/rest/media/v1/preview_url_resource.py, synapse/util/caches/descriptors.py
This is somewhat related to the async work, but not directly.
* Cleans up an incorrect comment.
* Removes `maybeDeferred` calls around `Observable.observe`, these used to be necessary but are no longer. See #6291
* Removes a `maybeDeferred` call around `get_user_by_id`, but that always returns a `Deferred`.
=> Remove unnecessary maybeDeferred calls

changelog.d/8049.misc, synapse/http/site.py
This is to try and reduce superfluous logs. I'm not 100% sure we should do this.
Based on https://github.com/matrix-org/synapse/pull/8048
=> Don't log OPTIONS request at INFO

changelog.d/8043.misc, synapse/crypto/context_factory.py
Hopefully this makes sense. Thanks to @th3b0x for raising this.
=> Add a comment about SSLv23_METHOD

changelog.d/8010.doc, docs/admin_api/shutdown_room.md
=> Clarify that undoing a shutdown might not be possible

changelog.d/8045.misc, synapse/storage/databases/main/client_ips.py, synapse/storage/databases/main/search.py, synapse/storage/databases/main/signatures.py, synapse/storage/databases/main/user_directory.py, tests/storage/test_user_directory.py
Converts the following stores to async:
* search
* user_directory
* signatures
* client_ips
It also removes an unused method from the user_directory store: `get_rooms_in_common_for_users` (I think it has been unused since #4537, but not 100% sure).
=> Convert additional database stores to async/await

changelog.d/8041.misc, synapse/handlers/message.py, tests/storage/test_redaction.py
I think this would have caught all the cases in
https://github.com/matrix-org/synapse/issues/7642 - and I think a 500 makes
more sense here than a 403.
=> Add an assertion on prev_events in create_new_client_event

.circleci/config.yml, changelog.d/8056.docker
Note: this targets `master`, because I want to make sure that anything else taht lands on `master` before release won't trigger a `latest-py3` rebuild. I'll merge to `develop` after it lands on `master`.
Fixes #7825.
=> Stop uploading -py3 docker images

changelog.d/8052.feature, docs/sample_config.yaml, synapse/config/_util.py, synapse/config/saml2_config.py, synapse/handlers/saml_handler.py, synapse/res/templates/saml_error.html
Hopefully this mostly speaks for itself. I also did a bit of cleaning up of the
error handling.
Fixes #8047.
=> Implement login blocking based on SAML attributes

changelog.d/8040.misc, docs/sample_log_config.yaml, synapse/config/logger.py
See the comments in the config.
Fixes #8018
*Note*: I'm happy to bikeshed some of the values here.
=> Change the default log config to reduce disk I/O and storage

changelog.d/8050.misc, synapse/http/client.py, synapse/http/federation/matrix_federation_agent.py, synapse/http/matrixfederationclient.py
c.f. #8021 
A lot of the code here is to change the `Completed 200 OK` logging to include the request URI so that we can drop the `Sending request...` log line.
Some notes:
1. We won't log retries, which may be confusing considering the time taken log line includes retries and sleeps.
2. The `_send_request_with_optional_trailing_slash` will always be logged *without* the forward slash, even if it succeeded only with the forward slash.
I'm not 100% convinced that this is the right thing to do
=> Reduce INFO logging

changelog.d/8058.misc, synapse/handlers/events.py, synapse/notifier.py, synapse/server.pyi, tox.ini
This also removes an unused `only_keys` param from a function, as I couldn't quickly see what type it was
=> Add typing info to Notifier

changelog.d/8051.misc, docker/conf/log.config, docs/sample_log_config.yaml, synapse/config/logger.py
Instead of requiring people to explicitly set the filter correctly in the config, instead let's do it automatically for them. It's too easy at the moment to mess it up by e.g. setting the filter on the wrong handler when using buffering and get the wrong contexts logged.
This is backwards compatible, manually setting the filter will just result in the context being clobbered. This does mean that if you set the filter in the wrong place you'll get incorrect contexts still.
Based on https://github.com/matrix-org/synapse/pull/8040
=> Auto set logging filter

changelog.d/8061.misc, synapse/storage/databases/main/event_federation.py, synapse/storage/databases/main/registration.py, synapse/storage/databases/state/bg_updates.py, tests/handlers/test_register.py, tests/storage/test_monthly_active_users.py, tests/storage/test_registration.py
Converts two of the databases to async/await:
* event federation
* registration
It also the background updates for the state store to async/await.
=> Converts event_federation and registration databases to async/await

changelog.d/8062.misc, synapse/storage/databases/main/metrics.py, synapse/storage/databases/main/tags.py, tests/server_notices/test_resource_limits_server_notices.py
This converts the tags and metrics databases to async/await.
They were pretty standalone and straightforward. Some of the code did use standard callbacks though. That was also converted for consistency.
=> Convert tags and metrics databases to async/await

changelog.d/8064.misc, synapse/federation/sender/transaction_manager.py, synapse/notifier.py, synapse/types.py, synapse/util/metrics.py, tox.ini
The `extra_users` param accepts both `UserID` and `str` as users. This wasn't caught because we hadn't annotated `UserID.from_string` nor the `measure_func` decorators.
Introduced in #8058
=> Fix typing for notifier

changelog.d/8066.misc, synapse/storage/databases/main/appservice.py, synapse/storage/databases/main/filtering.py, synapse/storage/databases/main/group_server.py, synapse/storage/databases/main/presence.py, synapse/storage/databases/main/profile.py, synapse/storage/databases/main/relations.py, synapse/storage/databases/main/transactions.py, tests/storage/test_appservice.py
Converts the following databases to async/await:
* appservice
* filtering
* group server
* presence
* profile
* relations
* transactions
These were all pretty straightforward. Sorry for the many files, but a few of these only had a single instance in them!
=> Convert appservice, group server, profile and more databases to async

changelog.d/8063.misc, synapse/storage/databases/main/account_data.py, synapse/storage/databases/main/censor_events.py, synapse/storage/databases/main/deviceinbox.py, tests/handlers/test_typing.py
Converts the following databases:
* account data
* device inbox
* censor events
=> Convert account data, device inbox, and censor events databases to async/await

changelog.d/8070.misc, synapse/storage/_base.py, synapse/storage/databases/main/push_rule.py, synapse/storage/databases/main/roommember.py, tests/test_federation.py
In addition to converting the room member database to async/await this:
* Removes an unused `bulk_get_push_rules_for_room` method from the push_rule store (this called into the roommember store, which is how it got picked up).
* Removes an unused `was_host_joined` method.
* It adds a license header to a file that didn't have one (not sure this is really "OK", but it should be since the entire project is under that license).
=> Convert the roommember database to async/await.

changelog.d/8072.misc, tests/federation/test_complexity.py
We need to use `side_effect` here otherwise the awaitable gets created immediately and...if it is never used then you get a warning.
I wonder if we can remove some of this mocking and the tests will still pass? That might be an option.
The OIDC code has a nicer way of doing this, I'll probably want to re-do a bunch of the code using `make_awaitable` with this at some point:
https://github.com/matrix-org/synapse/blob/a3cf36f76ed41222241393adf608d0e640bb51b8/tests/handlers/test_oidc.py#L81-L88
=> Fix unawaited coroutine error in tests.

changelog.d/8081.bugfix, synapse/handlers/message.py
If we got an error persisting an event, we would try to remove the push actions
asynchronously, which would lead to a 'Re-starting finished log context'
warning.
I don't think there's any need for this to be asynchronous.
=> Run `remove_push_actions_from_staging` in foreground

changelog.d/8087.misc, synapse/storage/background_updates.py, synapse/storage/databases/main/devices.py, synapse/storage/databases/main/event_push_actions.py, synapse/storage/databases/main/presence.py, synapse/storage/databases/main/push_rule.py, synapse/storage/databases/main/pusher.py, synapse/storage/databases/main/receipts.py, synapse/storage/databases/main/roommember.py, synapse/storage/databases/main/state.py, synapse/storage/databases/main/user_erasure_store.py
Converts the background updates for the main database and code that was using `cachedList` which ignored initially.
=> Convert misc database code to async

changelog.d/8085.misc, synapse/storage/databases/main/event_federation.py, synapse/storage/databases/main/events_worker.py, synapse/storage/databases/main/presence.py, synapse/storage/databases/main/registration.py, synapse/storage/databases/main/room.py, synapse/storage/databases/main/schema/delta/58/13remove_presence_allow_inbound.sql
This removes some unused database functions. It also includes a schema migration to drop an unused table.
=> Remove some unused database functions

changelog.d/8076.misc, synapse/storage/databases/main/events.py, synapse/storage/databases/main/events_bg_updates.py, synapse/storage/databases/main/receipts.py
Converts the following to async/await:
* receipts database
* events database
* background updates for the main database
=> Convert receipts and events databases to async/await

changelog.d/8075.misc, synapse/rest/client/v1/push_rule.py, synapse/storage/databases/main/push_rule.py, synapse/storage/databases/main/pusher.py
Converts a few databases to async/await:
* push rules
* push rule
* pusher
I stayed away from event push actions since I think other PRs are touching that at the moment.
=> Convert pusher databases to async/await.

changelog.d/8092.feature, synapse/api/auth.py, synapse/handlers/register.py, synapse/replication/http/register.py, synapse/storage/databases/main/registration.py, synapse/storage/databases/main/schema/delta/58/09shadow_ban.sql, synapse/types.py, tests/storage/test_cleanup_extrems.py, tests/storage/test_event_metrics.py, tests/storage/test_roommember.py, tests/test_federation.py, tests/unittest.py
This is meant to partially replace #8028:
* Add a shadow-banned column to `users`.
* Allow it to be specified during registration (currently nothing uses this so users are never shadow-banned).
* Pipes the column into the `Requester` object which will make it available for use in various servlets / handlers.
This does not do anything with the flag yet, that will be done in follow-up PRs.
=> Add a shadow-banned flag to users

changelog.d/8100.misc, synapse/storage/database.py, synapse/storage/databases/main/appservice.py, synapse/storage/databases/main/events_worker.py, synapse/storage/databases/main/registration.py, synapse/storage/databases/main/roommember.py, tests/handlers/test_profile.py, tests/handlers/test_typing.py, tests/storage/test_appservice.py, tests/storage/test_base.py, tests/storage/test_event_push_actions.py, tests/storage/test_main.py, tests/storage/test_profile.py
* Convert some of the general database methods to async (`simple_insert`, `simple_upsert`, and `simple_select_many_batch`).
* Converts `_check_safe_to_upsert` background task to async.
Note that the results of these get passed back frequently, which is rather annoying to trace but I believe all the callers `await` them.
The various other `simple_*` functions just pipe back the result of `runInteraction`, so I want to handle that (+ `runWithConnection`) separately.
=> Convert some of the general database methods to async

changelog.d/8107.feature, synapse/config/server.py, synapse/python_dependencies.py
This conditional dependency was removed as part of https://github.com/matrix-org/synapse/pull/8037. Turns out that the codebase checks for this removed key explicitly:
https://github.com/matrix-org/synapse/blob/5c43c43240a85ca6b65ad327b6a5b1c9e29bd653/synapse/config/server.py#L1150
This was breaking Element-Web's CI and possibly other things we're unaware of.
~~Rather than remove that check, we're re-adding the option now in case anything else may break.~~ It doesn't seem like there's much else to check. We've opted to remove the check. Hopefully this is the last time it will need to be revisited.
=> Add resources.consent conditional dependency back

changelog.d/8093.bugfix, synapse/handlers/message.py
Right now we have some type-hints which are lies. If `send_nonmember_event` is called with a duplicate event, it actually returns an `EventBase` object, not an `int`. This trickles through a bunch of functions (via `create_and_send_nonmember_event`), but I don't think there's an actual bug being caused. I *think* all the callers of this that use the last stream ID end up in `create_room`, which uses it here:
https://github.com/matrix-org/synapse/blob/dc22090a6735b2366f45271178ca7a087560f520/synapse/handlers/room.py#L777-L780
This was spun out of #8071 since it isn't really related there.
=> Return the previous stream token if a non-member event is a duplicate.

CHANGES.md, changelog.d/8101.bugfix, changelog.d/8101.removal, synapse/util/stringutils.py, tests/util/test_stringutils.py
Closes: https://github.com/matrix-org/synapse/issues/6766
Equivalent Sydent PR: https://github.com/matrix-org/sydent/pull/309
I believe it's now time to remove the extra allowed `:` from `client_secret` parameters.
=> Remove : from allowed client_secret chars

changelog.d/8112.misc, synapse/handlers/message.py, synapse/storage/databases/main/stream.py
This is a follow-up to #8093. Once #8074 was merged mypy started failing due to knowing proper return types to `get_stream_token_for_event`.
This moves the innards of `get_stream_token_for_event` to another function to return the `int` stream ID. I'm unsure if this is right or not though...
=> Fix the return type of send_nonmember_events.

changelog.d/8111.doc, docs/password_auth_providers.md
Add a link to matrix-synapse-rest-password-provider. I linked to the ma1uta fork since that seems to be the active fork.
=> Add a link to the matrix-synapse-rest-password-provider.

changelog.d/8113.misc, synapse/replication/slave/storage/_slaved_id_tracker.py, synapse/replication/tcp/streams/_base.py, synapse/storage/databases/main/cache.py, synapse/storage/util/id_generators.py, tests/storage/test_id_generators.py
The function is used for two purposes: 1) for subscribers of streams to get a token they can use to get further updates with, and 2) for replication to track position of the writers of the stream.
For streams with a single writer the two scenarios produce the same result, however the situation becomes complicated for streams with multiple writers. The current `MultiWriterIdGenerator` does not correctly handle the first case (which is not an issue as its only used for the `caches` stream which nothing subscribes to outside of replication). Future PRs will flesh MultiWriterIdGenerator` out to support that case.
Note: I've added it to all ID generators for consistency, though nothing uses them currently.
=> Separate `get_current_token` into two.

changelog.d/8119.misc, synapse/util/caches/descriptors.py, tests/util/caches/test_descriptors.py
The caching code has separate code-paths for `inlineCallbacks` vs. "normal" functions (which includes async functions), this removes the `inlineCallbacks` code-paths which are now unused, meaning that `cachedInlineCallbacks` is no longer a thing and `cachedList` no longer takes an `inlineCallbacks` parameter.
I'm unsure if we want more invasive changes here to keep some of this code from becoming a `Deferred`, but regardless this clean-up can be done first.
=> Remove the unused inlineCallbacks code-paths in the caching code

changelog.d/8121.misc, synapse/metrics/background_process_metrics.py, synapse/storage/database.py
This is very small, but I don't want it to get caught up with converting `runInteraction` (since that seems like it'll be a large PR).
This does add a `ensureDeferred` which makes me wonder if it is even worth it, but... 🤷
=> Convert runWithConnection to async.

changelog.d/8106.bugfix, synapse/api/errors.py, synapse/federation/federation_server.py, synapse/federation/sender/transaction_manager.py, synapse/handlers/e2e_keys.py, synapse/handlers/identity.py, synapse/handlers/message.py, synapse/handlers/oidc_handler.py, synapse/handlers/ui_auth/checkers.py, synapse/http/client.py, synapse/http/federation/well_known_resolver.py, synapse/http/servlet.py, synapse/logging/opentracing.py, synapse/replication/tcp/commands.py, synapse/rest/client/v1/room.py, synapse/rest/client/v2_alpha/sync.py, synapse/rest/key/v2/remote_key_resource.py, synapse/storage/_base.py, synapse/storage/databases/main/events_worker.py, synapse/util/__init__.py
This disables the JSON extensions which Python supports by default (parsing of `Infinity` / `-Infinity` and `NaN`). These shouldn't be accepted since they're not technically valid JSON and other languages won't be able to interpret it properly.
I also restructured the JSON deserializing a bit to refer to a single JSON decoder with a shared implementation (kind of like #7372).
It is possible this could break due to event data in someone's database, but that event isn't actually JSON, so I think this is equivalent to somehow ending up with total garbage in the database. Synapse should error pretty clearly in this case anyway.
=> Be stricter about JSON that is accepted by Synapse

changelog.d/8120.doc, docs/federate.md
Quick docs update regarding missing `308 Permanent Redirect` support in Twisted, which can cause Federation failures. A PR has been opened ([#1376](https://github.com/twisted/twisted/pull/1376)) with Twisted to fix this issue, but may take some time to trickle up to a Synapse release. In the meantime, adding a note in the docs will save Synapse admins some headaches!
Signed-off-by: Ryan Cole <hello@ryanc.me>
=> Updated docs: Added note about missing 308 redirect support.

changelog.d/8116.feature, synapse/http/server.py, tests/rest/client/v1/test_login.py, tests/rest/client/v2_alpha/test_register.py, tests/storage/test_cleanup_extrems.py
Per some conversation with @erikjohnston and @richvdh this might be more efficient as we can hopefully fill more of the TCP buffer in the kernel before giving up control of the reactor.
The `_ByteProducer` will create HTTP chunks of 1 KB, but now it should continue writing chunks until told to stop.
=> Switch the JSON byte producer from a pull to a push producer

changelog.d/8123.misc, synapse/replication/slave/storage/push_rule.py, synapse/replication/tcp/streams/_base.py, synapse/rest/client/v1/push_rule.py, synapse/storage/databases/main/push_rule.py, synapse/storage/util/id_generators.py, synapse/streams/events.py
It's just a thin wrapper around two ID gens to make `get_current_token` and `get_next` return tuples. This can easily be replaced by calling the appropriate methods on the underlying ID gens directly.
=> Remove `ChainedIdGenerator`.

changelog.d/8131.bugfix, synapse/storage/databases/__init__.py
... otherwise it gets leaked.
I think this has been a bug forever.
=> Close the database connection we create during startup

changelog.d/8133.misc, synapse/crypto/keyring.py, synapse/module_api/__init__.py, synapse/spam_checker_api/__init__.py, synapse/storage/databases/main/group_server.py, synapse/storage/databases/main/keys.py, synapse/storage/databases/main/user_erasure_store.py
In preparation for converting `runInteraction` to async this does two changes:
* Do not try to run `addCallbacks` to the result of a `runInteraction` call.
* Ensure that public APIs return `Deferreds`.
So essentially it treats calls to `runInteraction` as `Awaitables` instead of `Deferreds`.
=> Do not assume calls to runInteraction return Deferreds.

changelog.d/8129.bugfix, synapse/rest/client/v2_alpha/groups.py
This should fix a Sentry issue which looked very easy to fix: https://sentry.matrix.org/sentry/synapse-matrixorg/issues/116599/
These requests are being made somewhat regularly, although I'm not sure why.
=> Ensure a group ID is valid before trying to get rooms for it.

changelog.d/8127.misc, synapse/storage/database.py, synapse/storage/databases/main/ui_auth.py
I realized a few of the return types in `synapse.storage.database` were incorrect. I figured while I was checking these I should just add type hints.
=> Add more types to synapse.storage.database.

changelog.d/8124.misc, synapse/handlers/devicemessage.py, synapse/logging/opentracing.py, synapse/rest/well_known.py, synapse/storage/background_updates.py, synapse/storage/databases/main/appservice.py, synapse/storage/databases/main/room.py, synapse/storage/databases/main/tags.py, synapse/storage/databases/main/ui_auth.py
This is a follow-up to #7372 that I noticed while doing #8106. It uses the JSON encoder that reduces whitespace in additional places. After this, it is used pretty much everywhere.
Most of these aren't dramatically large responses or large data stored in the database, but I like the consistency.
=> Use the JSON encoder without whitespace in more places.

changelog.d/8135.bugfix, synapse/handlers/register.py
Fixes #8125
This will help clients show a better error message to users.
=> Improve the error code when trying to register with a name reserved for guests.

changelog.d/8110.bugfix, synapse/events/__init__.py, synapse/storage/databases/main/events_worker.py
It turns out that not all out-of-band membership events are labelled as such, so we need to be more accepting here.
Fixes #7843
=> Be more tolerant of membership events in unknown rooms

changelog.d/8153.bugfix, synapse/handlers/room_member.py, tests/rest/client/v1/test_rooms.py, tests/rest/client/v1/utils.py
Fixes https://github.com/matrix-org/synapse/issues/8148 by not firing the ratelimiter if the join event isn't actually joining the user to the room (e.g. it's a profile change).
Fixes https://github.com/matrix-org/synapse/issues/8146 by not firing the ratelimiter if the join event is identical to the user's previous join event (in which case we don't actually send the event, to preserve idempotency on the join endpoints).
This fix is only targeting the ratelimiter on local joins, and not the one on remote joins, because we're sure the latter is only actually used to get a user in the room (afterwards we're already in that room and use the local one).
The main downside of this patch is that it doesn't save as many CPU cycles, and time, before ratelimiting as how it was done originally, but …
=> Fix join ratelimiter breaking profile updates and idempotency

changelog.d/8152.feature, tests/rest/client/v1/test_rooms.py
This avoids adding a delay to the request-response cycle during tests.
I tested this by modifying [a sleep call](https://github.com/matrix-org/synapse/blob/cbbf9126cbd2ace90c1c0f615b87bcec30fdcbd8/synapse/handlers/room_member.py#L317) to use `random.randint(10, 10)` (instead of a number randomly between 1 and 10). This caused the test to always fail. With this change the test will pass.
Fixes #8150
=> Fix flaky shadow ban tests -- do not add a delay in tests.

changelog.d/8147.docker, docker/Dockerfile, docker/README.md
* Updated docker readme for healthcheck related options
=> Add healthcheck for default localhost 8008 port on /health endpoint.

changelog.d/8142.feature, synapse/handlers/directory.py, synapse/handlers/message.py, synapse/handlers/room.py, synapse/rest/client/v1/room.py, synapse/rest/client/v2_alpha/relations.py, synapse/rest/client/v2_alpha/room_upgrade_rest_servlet.py, tests/rest/client/v1/test_rooms.py
This is the last (?) piece of #8028 to get spun out. I've already taken a couple of the comments from @richvdh into account here.
It blocks shadow-banned users from sending non-member events. This adds a check to `create_and_send_nonmember_event`, but I suspect the same check should be done in `send_nonmember_event`? Perhaps as a separate PR or perhaps as this one?
=> Stop shadow-banned users from sending non-member events.

changelog.d/7377.misc, changelog.d/8163.misc, docs/admin_api/user_admin_api.rst, synapse/storage/databases/main/__init__.py
Some fixes to wording I noticed after merging #7377.
=> Wording fixes to 'name' user admin api filter

changelog.d/8161.misc, synapse/storage/databases/main/account_data.py, synapse/storage/databases/main/deviceinbox.py, synapse/storage/databases/main/devices.py, synapse/storage/databases/main/end_to_end_keys.py, synapse/storage/databases/main/events.py, synapse/storage/databases/main/group_server.py, synapse/storage/databases/main/presence.py, synapse/storage/databases/main/push_rule.py, synapse/storage/databases/main/pusher.py, synapse/storage/databases/main/receipts.py, synapse/storage/databases/main/room.py, synapse/storage/databases/main/tags.py, synapse/storage/util/id_generators.py
This is mainly so that `StreamIdGenerator` and `MultiWriterIdGenerator` will have the same interface, allowing them to be used interchangeably.
=> Make StreamIdGen `get_next` and `get_next_mult` async 

changelog.d/8158.feature, synapse/handlers/message.py
This is very similar to #8142, but for `send_nonmember_event` (instead of `create_and_send_nonmember_event`). This has very few callers:
* Used when upgrading rooms (this was handled in #8142).
* Used to send dummy events.
* Used in `create_and_send_nonmember_event` but that will already have raised an exception. 😄 
All-in-all this doesn't offer much more protection with our current APIs, but means that we internally treat `create_and_send_nonmember_event` and `send_nonmember_event` the same and guards against a future misuse of `send_nonmember_event`.
=> Do not allow send_nonmember_event to be called with shadow-banned users.

changelog.d/8167.misc, tests/rest/client/v1/test_rooms.py
These tests are from 1.19.1 (#8153) and seem to be broken after the merge from `release-v1.19.1` into `develop`.
=> Fix rate limiting tests

changelog.d/8162.misc, synapse/storage/database.py, synapse/storage/databases/main/devices.py, synapse/storage/databases/main/directory.py, synapse/storage/databases/main/e2e_room_keys.py, synapse/storage/databases/main/events_worker.py, synapse/storage/databases/main/group_server.py, synapse/storage/databases/main/media_repository.py, synapse/storage/databases/main/monthly_active_users.py, synapse/storage/databases/main/profile.py, synapse/storage/databases/main/receipts.py, synapse/storage/databases/main/registration.py, synapse/storage/databases/main/rejections.py, synapse/storage/databases/main/room.py, synapse/storage/databases/main/state.py, synapse/storage/databases/main/stats.py, synapse/storage/databases/main/user_directory.py, tests/handlers/test_profile.py, tests/handlers/test_typing.py, tests/module_api/test_api.py, tests/storage/test_base.py, tests/storage/test_devices.py, tests/storage/test_profile.py, tests/storage/test_registration.py, tests/storage/test_room.py
This converts `simple_select_one` and `simple_select_one_onecol` to async/await.
It also fixes up:
* Some comments that refer to callers of these returning Deferreds.
* Some type hints.
There's a few additional places that the calls to these methods are returned instead of awaited, but there's type type info or comments so it seemed a bit silly to add an async/await on them, but I can if we'd like.
=> Convert simple_select_one and simple_select_one_onecol to async

changelog.d/8130.misc, scripts-dev/federation_client.py
Now that the server supports streaming back JSON responses, it would be nice to
show the response as it is streamed, in the test tool.
=> Update the test federation client to handle streaming responses

changelog.d/8144.docker, docker/Dockerfile
=> Add required Debian dependencies to allow docker builds on the arm platform

changelog.d/8174.misc, synapse/handlers/message.py, synapse/rest/client/v1/room.py, tests/rest/client/test_retention.py
Small cleanup PR. The `is_guest` argument wasn't used in the function anymore. Also completed logic of a conditional. Noticed during review of another PR.
=> Remove unused parameter from, and add safeguard in, get_room_data

changelog.d/8176.feature, synapse/handlers/typing.py, synapse/rest/client/v1/room.py, tests/handlers/test_typing.py, tests/replication/test_federation_sender_shard.py, tests/rest/client/test_shadow_banned.py
While testing the other shadow-banning patches I realized that when a shadow-banned user is typing you would still get the "so-and-so is typing" messages, this blocks those from appearing.
=> Do not propagate typing notifications from shadow-banned users.

changelog.d/8181.misc, tests/rest/client/test_shadow_banned.py
https://github.com/matrix-org/synapse/pull/8174 removed the `is_guest` parameter from `get_room_data`, at the same time that #8157 was merged using it, colliding together to break unit tests on develop.
This PR removes the `is_guest` parameter from the call in the broken test.
Uses the same changelog as #8174.
=> Remove remaining is_guest argument uses from get_room_data calls

debian/changelog, debian/matrix-synapse.service
This ensures systemctl start matrix-synapse returns only after synapse
is actually started, which is very useful for automated deployments.
Fixes #5761
=> Update debian systemd service to use Type=notify

changelog.d/8173.misc, synapse/handlers/room.py, synapse/storage/database.py, synapse/storage/databases/main/__init__.py, synapse/storage/databases/main/directory.py, synapse/storage/databases/main/e2e_room_keys.py, synapse/storage/databases/main/event_federation.py, synapse/storage/databases/main/group_server.py, synapse/storage/databases/main/media_repository.py, synapse/storage/databases/main/profile.py, synapse/storage/databases/main/receipts.py, synapse/storage/databases/main/registration.py, synapse/storage/databases/main/room.py, synapse/storage/databases/main/user_directory.py, tests/handlers/test_stats.py, tests/storage/test_base.py, tests/storage/test_directory.py, tests/storage/test_main.py, tests/test_federation.py
This converts `simple_select_onecol`, `simple_select_list`, `simple_update`, and `simple_update_one` to async/await.
It also converts calls to async/await and fixes some types hints / comments.
This is essentially #8162, but different database methods.
=> Convert simple_update* and simple_select* to async

changelog.d/8179.misc, synapse/storage/util/id_generators.py, tests/storage/test_id_generators.py
=> Fix missing _add_persisted_position

changelog.d/8187.misc, synapse/storage/database.py
This was noticed in https://github.com/matrix-org/synapse/pull/8127#discussion_r473211386, fixing it separately since it was unrelated.
It looks like there's only a single caller to this:
https://github.com/matrix-org/synapse/blob/30426c7063a7e5567ac21cd10267651ef1935360/synapse/storage/databases/main/__init__.py#L562-L578
Which also gets called from a single spot:
https://github.com/matrix-org/synapse/blob/97962ad17b204be0a88ef0cd3026f11c359fdb4a/synapse/rest/admin/users.py#L596-L616
The comments around that endpoint seems to be lies (and I think that that endpoint is just completely broken?)
=> simple_search_list_txn should return None, not 0.

changelog.d/8191.misc, synapse/storage/database.py, synapse/storage/databases/main/group_server.py, synapse/storage/databases/main/registration.py, tests/storage/test_event_push_actions.py
I had missed this method when doing the other database functions. This converts it to async/await and all callers to async/await.
Similar to #8162.
=> Convert simple_delete to async/await.

changelog.d/8192.misc, synapse/storage/databases/main/monthly_active_users.py, synapse/storage/databases/main/stats.py, tests/handlers/test_auth.py, tests/handlers/test_register.py, tests/rest/admin/test_user.py, tests/server_notices/test_resource_limits_server_notices.py, tests/storage/test_client_ips.py
This is spun out of #8156.
It converts the stats and monthly active users code which calls `runInteraction` to async/await.
=> Convert stats and related calls to async/await

changelog.d/8193.misc, tests/api/test_filtering.py, tests/crypto/test_keyring.py, tests/federation/test_complexity.py, tests/handlers/test_typing.py, tests/rest/client/v2_alpha/test_filter.py, tests/storage/test_appservice.py, tests/storage/test_background_update.py, tests/storage/test_end_to_end_keys.py, tests/storage/test_event_push_actions.py, tests/storage/test_main.py, tests/storage/test_registration.py, tests/storage/test_user_directory.py, tests/test_state.py, tests/test_visibility.py
As part of #8156 we'll make `runInteraction` return an `Awaitable` instead of a `Deferred`, this gets the tests to run since those are not yieldable.
This PR is large, but touches tests only.
=> Do not yield on awaitables in tests.

changelog.d/8182.misc, synapse/handlers/auth.py, synapse/rest/client/v1/login.py
This is split out from https://github.com/matrix-org/synapse/pull/7438, which had gotten rather large.
`LoginRestServlet` has a couple helper methods, `login_submission_legacy_convert` and `login_id_thirdparty_from_phone`. They're primarily used for converting legacy user login submissions to "identifier" dicts ([see spec](https://matrix.org/docs/spec/client_server/r0.6.1#post-matrix-client-r0-login)). Identifying information such as usernames or 3PID information used to be top-level in the login body. They're now supposed to be put inside an [identifier](https://matrix.org/docs/spec/client_server/r0.6.1#identifier-types) parameter instead.
#7438's purpose is to allow using the new identifier parameter during User-Interactive Authentication, which is currently handled in AuthHandler. …
=> Move and refactor LoginRestServlet helper methods

changelog.d/8195.misc, synapse/appservice/__init__.py, synapse/federation/persistence.py, synapse/handlers/federation.py, synapse/storage/databases/main/appservice.py, synapse/storage/databases/main/deviceinbox.py, synapse/storage/databases/main/e2e_room_keys.py, synapse/storage/databases/main/event_federation.py, synapse/storage/databases/main/group_server.py, synapse/storage/databases/main/keys.py, synapse/storage/databases/main/transactions.py
Spun out of #8156, this converts a variety of the database classes to async/await: transactions, appservice, group_server, deviceinbox, e2e_room_keys, keys, event_federation.
Not really any particular relation between these, but I limited myself on size.
=> Convert a grab bag of database code to async/await

changelog.d/8190.bugfix, synapse/handlers/oidc_handler.py, tests/handlers/test_oidc.py
Some OpenID Connect providers (such [as GitHub](https://docs.github.com/en/rest/reference/users#get-the-authenticated-user)) use integer IDs which get returned via the OAuth flows. This causes an error when we attempt to save the remote ID into the database.
This is worked around by casting the remote ID to a string. I debated whether we should leave this up to the `OidcMappingProvider`, but we'll probably just have to end up explaining to people that you really need to return a string from that. I could be convinced it is up to `OidcMappingProvider` to abide by the specification it is given though.
Fixes #7795
=> Ensure that the OIDC remote ID is a string.

changelog.d/8194.misc, synapse/handlers/room.py, synapse/storage/databases/main/state.py, synapse/storage/databases/main/state_deltas.py, synapse/storage/databases/main/stream.py, synapse/storage/databases/state/store.py, synapse/storage/state.py
This converts the code that deals with state and streams to async. Spun out of #8156.
=> Convert state and stream stores and related code to async

changelog.d/8197.misc, synapse/storage/databases/main/event_push_actions.py, synapse/storage/databases/main/registration.py, synapse/storage/databases/main/roommember.py
Another PR spun out of #8156, this converts the `event_push_actions`, `registration`, and `roommember` datastores to async/await.
=> Convert `event_push_actions`, `registration`, and `roommember` datastores to async

changelog.d/8196.misc, synapse/python_dependencies.py, synapse/replication/tcp/client.py
This fixes a bug where having multiple callers waiting on the same stream and position will cause it to try and compare two deferreds, which fails (due to the sorted list having an entry of `Tuple[int, Deferred]`).
=> Fix `wait_for_stream_position` for multiple waiters.

changelog.d/8205.misc, synapse/handlers/e2e_keys.py, synapse/storage/databases/main/end_to_end_keys.py, tests/storage/test_end_to_end_keys.py
... and to show that it does something slightly different to
`_get_e2e_device_keys_txn`.
`include_all_devices` and `include_deleted_devices` were never used (and
`include_deleted_devices` was broken, since that would cause `None`s in the
result which were not handled in the loop below.
Add some typing too.
=> Rename `get_e2e_device_keys` to better reflect its purpose

changelog.d/8204.misc, synapse/handlers/device.py, synapse/replication/slave/storage/devices.py, synapse/storage/databases/main/__init__.py, synapse/storage/databases/main/devices.py, synapse/storage/databases/main/end_to_end_keys.py
This is the first of (sorry) a series of PRs to clean up device key/cross-signature handling a bit.
Suggest reviewing commit-by-commit. The first commit just moves the existing method without making any changes.
=> Move and rename `get_devices_with_keys_by_user`

INSTALL.md, changelog.d/8212.bugfix, synapse/python_dependencies.py
It seems that setuptools 50.0 breaks on Python 3.5, this avoids using that configuration. See pypa/setuptools#2352
=> Do not install setuptools 50.0 on Python 3.5

changelog.d/8203.misc, synapse/storage/util/id_generators.py, tests/storage/test_id_generators.py
This is so that we can use it for the backfill events stream.
=> Make MultiWriterIDGenerator work for streams that use negative stream IDs

changelog.d/8200.misc, synapse/events/builder.py, synapse/handlers/message.py, synapse/handlers/room_member.py, synapse/storage/databases/main/client_ips.py, synapse/storage/databases/main/directory.py, synapse/storage/databases/main/filtering.py, synapse/storage/databases/main/openid.py, synapse/storage/databases/main/profile.py, synapse/storage/databases/main/push_rule.py, synapse/storage/databases/main/room.py, synapse/storage/databases/main/signatures.py, synapse/storage/databases/main/ui_auth.py, synapse/storage/databases/main/user_erasure_store.py, tests/test_utils/event_injection.py
Convert `room`, `openid`, `user_erasure_store`, `ui_auth`, `filtering`, `profile`, `client_ips`, `directory`, `push_rule`, and `signatures` to async/await.
Most of these were one or two methods. The signatures commit might be worth looking at separately as the typing got a little wild.
Spun out of #8156.
=> Convert additional databases to async/await part 2

changelog.d/8214.misc, mypy.ini, synapse/http/federation/matrix_federation_agent.py, synapse/http/federation/well_known_resolver.py, tests/http/federation/test_matrix_federation_agent.py
This was an old branch I had that was just failing tests. Got those to pass today. While I was poking at it, I added type hints to the file.
=> Convert the well known resolver to async

changelog.d/8199.misc, synapse/storage/databases/main/__init__.py, synapse/storage/databases/main/devices.py, synapse/storage/databases/main/events_worker.py, synapse/storage/databases/main/purge_events.py, synapse/storage/databases/main/receipts.py, synapse/storage/databases/main/relations.py
Convert `relations`, `devices`, `receipts`, `purge_events`, `events_worker` and the main database to async/await.
Spun out of #8156.
=> Convert additional databases to async/await

changelog.d/8207.misc, synapse/appservice/api.py
I think I skipped this because of the `ResponseCache` usage, but there's no issue there, so this converts the last remaining `inlineCallback` in the appservice code.
=> Convert an errant inlineCallbacks in appservice

changelog.d/8201.misc, synapse/storage/background_updates.py, synapse/storage/databases/main/account_data.py, synapse/storage/databases/main/end_to_end_keys.py, synapse/storage/databases/main/media_repository.py, synapse/storage/databases/main/search.py, synapse/storage/databases/main/user_directory.py
Convert `end_to_end_keys`, `user_directory`, `account_data`, `search`, `media_repo`, and `background_updates` to async/await.
Spun out of #8156.
=> Convert additional databases to async/await part 3

changelog.d/8223.bugfix, synapse/handlers/profile.py, synapse/handlers/user_directory.py, synapse/storage/databases/main/user_directory.py
* Raise (better) exceptions when setting the (local) display name or avatar URL to a non-string. (This wasn't directly related to #8220, but I noticed it while poking around.)
* If an unexpected profile name / avatar URL is received remotely we either:
* Do not update it and use the previous one.
* Replace it with `None`.
This fixes #8220.
=> Fix errors when updating the user directory with invalid data

changelog.d/8224.misc, synapse/storage/databases/main/devices.py, synapse/storage/databases/main/end_to_end_keys.py
this makes it a bit clearer what's going on.
=> Make _get_e2e_device_keys_and_signatures_txn return an attrs

changelog.d/8213.misc, synapse/app/admin_cmd.py, synapse/app/homeserver.py
There's a couple of spots we "run" the reactor and generally the calls to those need to be Deferreds. This converts the functions that get called to `async` and then uses `ensureDeferred` around the resulting `Awaitable`.
=> Convert the main methods run by the reactor to async.

changelog.d/8225.misc, synapse/storage/databases/main/end_to_end_keys.py
We can use the existing `_get_e2e_device_keys_and_signatures_txn` instead of
creating our own txn function.
=> Refactor `_get_e2e_device_keys_for_federation_query_txn`

changelog.d/8156.misc, synapse/storage/database.py
This converts `runInteraction` to async/await.
This should be the last "main" part of #7988.
=> Convert runInteraction to async/await

changelog.d/8235.misc, synapse/storage/database.py
Not sure why, but after #8232 was merged mypy was failing on develop for me:
> synapse/storage/databases/main/stream.py:614: error: Incompatible return value type (got "Optional[Any]", expected "int") [return-value]
=> Add an overload for simple_select_one_onecol_txn.

changelog.d/8231.misc, synapse/storage/databases/main/devices.py, synapse/storage/databases/main/end_to_end_keys.py
We have three things which all call `_get_e2e_device_keys_and_signatures_txn`
with their own `runInteraction`. Factor out the common code.
=> wrap `_get_e2e_device_keys_and_signatures_txn` in a non-txn method

INSTALL.md, changelog.d/8212.bugfix, changelog.d/8239.misc, synapse/python_dependencies.py
Reverts matrix-org/synapse#8212
=> Revert pinning of setuptools

changelog.d/8240.misc, mypy.ini, scripts-dev/mypy_synapse_plugin.py, synapse/handlers/federation.py, synapse/util/caches/descriptors.py
This requires adding a mypy plugin to fiddle with the type signatures a bit.
=> Fix typing for `@cached` wrapped functions

changelog.d/8233.misc, synapse/storage/databases/main/end_to_end_keys.py
I think this is simpler (and moves stuff out of the db threads)
~~based on #8231~~
=> Split fetching device keys and signatures into two transactions

changelog.d/8241.misc, synapse/storage/database.py
Technically `str` **is** an `Iterable[str]` but I don't imagine that's what was meant ;-)
=> Fix type signature in simple_select_one_onecol and friends

changelog.d/8230.misc, synapse/federation/sender/__init__.py, synapse/storage/database.py, synapse/storage/databases/main/purge_events.py, synapse/storage/databases/main/schema/delta/58/14_catchup_destination_rooms.sql, synapse/storage/databases/main/schema/delta/58/15_catchup_destination_rooms.sql, synapse/storage/databases/main/transactions.py, tests/federation/test_federation_catch_up.py
This adds and keeps updated `destination_rooms`, a table used for determining the latest messages for each (destination, room) pair.
=> Catch-up after Federation Outage (split, 1)

changelog.d/8252.feature, synapse/config/saml2_config.py
After thinking about #8248, I think we should do the quick fix to ensure we don't have a regression, then do the refactoring on top.
=> Fix a regression from calling read_templates.

changelog.d/8254.feature, synapse/push/push_tools.py, synapse/storage/databases/main/schema/delta/58/15unread_count.sql
Make the new columns nullable, because doing otherwise can wedge a
server with a big database, as setting a default value rewrites the
table.
Clients are likely to be confused if we send a push but the badge count
is the unread messages one, and not the notifications one.
=> Unread counts fixes

changelog.d/8234.misc, synapse/storage/databases/main/devices.py, synapse/storage/databases/main/end_to_end_keys.py
This is the final PR in my device-fetch cleanup epic.
Since all of the callers of `get_e2e_device_keys_and_signatures` want the signature data on the `keys` object, we may as well do that in `get_e2e_device_keys_and_signatures` itself.
Based on #8233.
=> Add cross-signing sigs to the `keys` object

changelog.d/8256.misc, synapse/storage/databases/main/schema/delta/58/15_catchup_destination_rooms.sql
This hasn't gone into a release yet so changing the delta is fine, hopefully?
=> In light of #8255, use BIGINTs for `destination_rooms`

changelog.d/8258.misc, tests/federation/test_federation_catch_up.py
Part of #2528, extension to #8247 .
=> Catch-up after Federation Outage (split, 3): Add tests for `last_successful_stream_ordering`

changelog.d/8265.bugfix, synapse/storage/prepare_database.py
=> Run database updates in a transaction

changelog.d/8262.bugfix, synapse/python_dependencies.py
The version 1.3.0 has a bug with unicode charecters:
```
>>> from canonicaljson import encode_pretty_printed_json
>>> encode_pretty_printed_json({'a': 'à'})
File "<stdin>", line 1, in <module>
File "/home/erdnaxeli/.pyenv/versions/3.6.7/lib/python3.6/site-packages/canonicaljson.py", line 96, in encode_pretty_printed_json
return _pretty_encoder.encode(json_object).encode("ascii")
UnicodeEncodeError: 'ascii' codec can't encode character '\xe0' in position 12: ordinal not in range(128)
```
Signed-off-by: Alexandre Morignot <erdnaxeli@cervoi.se>
- Use …
=> Bump canonicaljson to version 1.4.0

changelog.d/8266.misc, synapse/storage/prepare_database.py
Fixes #8006.
I'm not 100% convinced this is what we want to do (aren't we trying to get rid of the master process?) but for now this is the best thing I can think of to do.
=> Refuse to upgrade database on worker processes

changelog.d/8264.misc, synapse/storage/databases/__init__.py, synapse/storage/databases/main/__init__.py, synapse/storage/prepare_database.py, synapse/storage/util/id_generators.py
I'm hoping this will provide some pointers for debugging
https://github.com/matrix-org/synapse/issues/7968.
=> Add more logging to debug slow startup

changelog.d/8270.feature, synapse/storage/databases/main/event_push_actions.py
Fix unread counts making sync fail if the value of the `unread_count`
column in `event_push_summary` is `None`.
=> Fix unread count failing on NULL values

changelog.d/8271.bugfix, synapse/storage/databases/main/__init__.py
This takes about 10 seconds in the best case; often more.
=> Avoid table-scanning users at startup

changelog.d/8268.bugfix, synapse/config/logger.py
When stderr is redirected to a logger, it's possible to get into an infinite loop which results in a stack overflow if the logging system encounters an error.
Work around it by detecting the reentrant call and writing to the real stderr instead.
Fixes: #4202, #4240.
=> Fix stack overflow when logging system encounters an error

changelog.d/8276.misc, docs/systemd-with-workers/system/matrix-synapse-worker@.service
Now that we refuse to run schema updates on workers (#8266), it's better if the workers start after the main process when doing a whole-system restart.
=> Systemd docs: configure workers to start after main process.

changelog.d/8261.misc, tests/federation/test_complexity.py, tests/federation/test_federation_sender.py, tests/handlers/test_auth.py, tests/handlers/test_register.py, tests/handlers/test_typing.py, tests/replication/test_federation_sender_shard.py, tests/rest/admin/test_user.py, tests/server_notices/test_resource_limits_server_notices.py, tests/storage/test_client_ips.py, tests/storage/test_monthly_active_users.py, tests/test_utils/__init__.py
This cleans up the usage of `make_awaitable` in tests to make it a bit more like `defer.succeed`, namely it makes it re-usable, meaning we don't need to use `side_effect` on mocks.
This is a test-only change, so should be OK to merge as long as CI passes. 😄 
I stole this idea from @reivilibre in matrix-org/matrix-synapse-ldap3#101.
=> Allow for make_awaitable's return value to be re-used.

changelog.d/8259.misc, synapse/api/filtering.py, synapse/app/admin_cmd.py, synapse/util/__init__.py, synapse/util/frozenutils.py
Switch to the standard library json module for all remaining uses. This was partially done previously (see PRs targeting #7674), but wasn't done for a few places.
After this PR we should now consistently use `json` everywhere and never `simplejson`.
Fixes #7674
=> Switch all remaining json usage to the standard library json.

changelog.d/8257.misc, synapse/storage/util/id_generators.py, tests/storage/test_id_generators.py
It did not correctly handle IDs finishing being persisted out of order, resulting in the `current_position` lagging until new IDs are persisted.
Currently this is only used for the cache invalidation stream over replication, so this should not have had an observable impact (since we invalidate caches *all* the time). While #7986 had landed this caused flakey sytests (https://github.com/matrix-org/sytest/issues/948) as they wouldn't write anything until the stream position had advanced.
=> Fix `MultiWriterIdGenerator.current_position`.

changelog.d/8278.bugfix, synapse/logging/utils.py
Update `log_function` to use the right factory to create log records, to make
sure that they have `request` attributes.
Fixes: #8267.
=> Use the right constructor for log records

changelog.d/8275.feature, docs/sample_config.yaml, synapse/config/server.py, synapse/rest/client/v2_alpha/account.py, tests/rest/client/v2_alpha/test_account.py
This is a config option ported over from DINUM's Sydent: https://github.com/matrix-org/sydent/pull/285
They've switched to validating 3PIDs via Synapse rather than Sydent, and would like to retain this functionality.
This original purpose for this change is phishing prevention. This solution could also potentially be replaced by a similar one to https://github.com/matrix-org/synapse/pull/8004, but across all `*/submit_token` endpoint.
This option may still be useful to enterprise even with that safeguard in place though, if they want to be absolutely sure that their employees don't follow links to other domains.
=> Add a config option for validating 'next_link' parameters against a domain whitelist

changelog.d/8279.misc, synapse/handlers/sync.py, synapse/storage/databases/main/devices.py, synapse/storage/databases/main/stream.py, synapse/types.py
The intention here is to change `StreamToken.room_key` to be a `RoomStreamToken` in a future PR, but that is a big enough change without this refactoring too.
=> Add types to StreamToken and RoomStreamToken

changelog.d/8282.misc, synapse/handlers/pagination.py
Caused by #8250 and #8279 conflicting.
=> Fix mypy error on develop

changelog.d/8285.misc, sytest-blacklist
Dendrite's implementing MSC2753 over at https://github.com/matrix-org/dendrite/pull/1370 to prove the implementation for MSC purposes, and so sytest has sprouted tests for it over at https://github.com/matrix-org/sytest/pull/944. But we don't want them to run on synapse until synapse implements it.
=> blacklist MSC2753 sytests until it's implemented in synapse

changelog.d/8287.bugfix, synapse/handlers/federation.py, synapse/handlers/message.py, synapse/push/emailpusher.py, synapse/push/httppusher.py, synapse/push/pusherpool.py, synapse/replication/tcp/client.py, tests/handlers/test_typing.py
`pusher_pool.on_new_notifications` expected a min and max stream ID, however that was not what we were passing in. Instead, let's just pass it the current max stream ID and have it track the last stream ID it got passed.
I believe that it mostly worked as we called the function for every event. However, it would break for events that got persisted out of order, i.e, that were persisted but the max stream ID wasn't incremented as not all preceding events had finished persisting, and push for that event would be delayed until another event got pushed to the effected users.
=> Fixup pusher pool notifications

UPGRADE.rst, docs/workers.md
https://github.com/matrix-org/synapse/pull/7785 added some information to tell homeserver admins how to correctly update their routing to make use of the new features in MSC2666.
However, this feature is still experimental as the MSC has not yet landed. Things may change, and as such we don't want to have to amend the documentation and inform sysadmins each time it does.
Thus we're removing these docs for now, but will bring them back when the feature becomes stable.
=> Remove MSC2666 info from upgrade/workers doc as it's still experimental

changelog.d/8288.misc, synapse/handlers/federation.py, synapse/handlers/message.py, synapse/notifier.py, synapse/push/pusherpool.py, synapse/replication/tcp/client.py
Based on #8287.
The idea here is that we pass the `max_stream_id` to everything, and only use the stream ID of the particular event to figure out *when* the max stream position has caught up to the event and we can notify people about it.
This is to maintain the distinction between the position of an item in the stream (i.e. event A has stream ID 513) and a token that can be used to partition the stream (i.e. give me all events after stream ID 352). This distinction becomes important when the tokens are more complicated than a single number, which they will be once we start tracking the position of multiple writers in the tokens.
The valid operations here are:
1. Is a position before or after a token
2. Fetching all events between two tokens
3. Merging multiple tokens to get the "max", …
=> Clean up `Notifier.on_new_room_event` code path

UPGRADE.rst, changelog.d/8227.doc, docs/reverse_proxy.md, docs/workers.md
Fixes: https://github.com/matrix-org/synapse/issues/8154
This PR adds a information about forwarding `/_synapse/client` endpoints through your reverse proxy. The first of these endpoints are introduced in https://github.com/matrix-org/synapse/pull/8004.
Question: Do we need to update `workers.md` with this endpoint as well?
=> Add /_synapse/client to the reverse proxy docs

changelog.d/8208.misc, tests/http/__init__.py
Some Linux distros have begun disabling TLSv1.0 and TLSv1.1 by default
for security reasons, for example in Fedora 33 onwards:
https://fedoraproject.org/wiki/Changes/StrongCryptoSettings2
Use TLSv1.2 for the fake TLS servers created in the test suite, to avoid
failures due to OpenSSL disallowing TLSv1.0:
<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines',
'ssl_choose_client_version', 'unsupported protocol')]>
You can reproduce the failures by setting `MinProtocol = TLSv1.2` in the `[crypto_policy]` section of the system-wide OpenSSL config (`/etc/pki/tls/openssl.cnf` on Fedora, maybe elsewhere on other systems).
- Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method …
=> Use TLSv1.2 for fake servers in tests

changelog.d/8291.bugfix, synapse/http/matrixfederationclient.py, synapse/python_dependencies.py, synapse/util/__init__.py, tests/federation/test_federation_server.py, tests/http/test_fedclient.py, tests/http/test_servlet.py
One of my previous PRs (#8106) had a bug in it -- you can't easily raise a `JSONDecodeError`, so this just changes it to a `ValueError`.
While I was in there I wrote some (very simple) tests for the helpers used to deserialize JSON since I didn't see any!
I targeted the `release-v1.20.0` branch since this change was not yet released.
=> Fix error raised on invalid JSON

changelog.d/8305.feature, docs/admin_api/rooms.md, synapse/storage/databases/main/room.py, tests/rest/admin/test_room.py
=> Add topic and avatar to room details admin API

changelog.d/8272.bugfix, synapse/federation/sender/per_destination_queue.py, synapse/storage/databases/main/transactions.py, tests/federation/test_federation_catch_up.py, tests/handlers/test_typing.py
This is basically the final PR for this feature/bugfix — though as an extension I would like to check for needed catch-ups on startup and proactively deal with outstanding catchups when Synapse has just been restarted…
=> Catch-up after Federation Outage (split, 4): catch-up loop

changelog.d/8324.bugfix, synapse/federation/federation_client.py
=> Don't assume that an event has an origin field

changelog.d/8326.misc, synapse/handlers/room_member.py, synapse/replication/http/_base.py, synapse/storage/databases/main/account_data.py, synapse/storage/databases/main/push_rule.py, synapse/storage/databases/main/receipts.py, synapse/storage/databases/main/stream.py, synapse/types.py
This moves every instance of `__metaclass__ = Y` to be `class X(metaclass=Y)`-based
Fixes #7932
=> Move metaclass initialization to python3

changelog.d/8329.bugfix, synapse/rest/client/v2_alpha/register.py
> Replaced with less buggy control flow
Fixes #2832
=> Fix a potential bug of UnboundLocalError

changelog.d/8331.misc, synapse/rest/admin/__init__.py, synapse/rest/admin/_base.py, synapse/rest/admin/devices.py, synapse/rest/admin/purge_room_servlet.py, synapse/rest/admin/server_notice_servlet.py, synapse/rest/admin/users.py
This cleans up some of the admin code to use the `admin_patterns` helper instead of hard-coding the prefix repeatedly.
Found while investigating #8334.
=> Use admin_patterns for all admin APIs.

changelog.d/8342.bugfix, synapse/federation/federation_server.py, synapse/federation/transport/server.py, synapse/server.py
=> Fix ratelimiting for federation `/send` requests.

changelog.d/8335.misc, tests/test_utils/logging_setup.py
The old method simply replaced braces with parentheses before sending it off into twisted logging, this was a hack, it's now been properly fixed.
The reason why the hack is needed, and this roundabout is needed, is because twisted logging works with "new-style formatting" (PEP 3101), or simply "brace formatting" (`"{thing}".format({thing=1})`), if braces were preserved (in what is essentially the "format" string), the twisted logger will attempt to interpret them according to the new-style formatting, and produce an error.
- End …
=> Update test logging to be able to accept braces

changelog.d/8349.bugfix, synapse/handlers/federation.py, synapse/handlers/pagination.py, synapse/storage/databases/main/stream.py
Instead of just using the most recent extremities let's pick the
ones that will give us results that the pagination request cares about,
i.e. pick extremities only if they have a smaller depth than the
pagination token.
This is useful when we fail to backfill an extremity, as we no longer
get stuck requesting that same extremity repeatedly.
=> Intelligently select extremities used in backfill.

changelog.d/8350.bugfix, synapse/federation/federation_client.py
This PR is a partial fix to backfilling rooms with malformed events. It will
allow for backfilling a partial set of events in the room, but will not fix your
backfill eventually running out.
This could be cleaner, as `_check_sigs_and_hash_and_fetch` is intended
for attempting to pull an event from the database/(re)pull it from the
server that originally sent the event if checking the signature of the
event fails.
During backfill we *know* that we won't have the event in our database,
however it is still useful to be able to query the original sending
server as the server we're backfilling from may be acting maliciously.
The main benefit and reason for using this method however is that
`_check_sigs_and_hash_and_fetch` will drop an event during backfill if
it cannot be successfully …
=> Use _check_sigs_and_hash_and_fetch to validate backfill requests

changelog.d/8320.feature, synapse/api/constants.py, synapse/rest/client/v1/login.py, tests/rest/client/v1/test_login.py
This PR adds the `uk.half-shot.msc2778.login.application_service` login `type`, which allows users to login using an appservice token. This is going to be used as part of the encrypted bridges project, as we need to generate device_ids for users.
This should be ready for review now. And now with tests!
[MSC2778](https://github.com/matrix-org/matrix-doc/pull/2778)
=> Allow appservice users to /login

changelog.d/8306.feature, docs/admin_api/user_admin_api.rst, synapse/rest/admin/__init__.py, synapse/rest/admin/users.py, tests/rest/admin/test_user.py
Add a new admin API `GET /_synapse/admin/v1/users/<user_id>/rooms` to
list all rooms where a user is a member.
Fixes: #8299
=> Admin API for querying rooms where a user is a member
