changelog.d/8354.misc
synapse/handlers/pagination.py

When merging from `release-v1.20.0` to `develop` (see 00db7786de526edc9635f6a5d12f725c31d2f3f5) there was a merge conflict in `synapse/handlers/pagination.py`, I resolved it (correctly, I think) but the non-conflict parts were incompatible.
This attempts to fix that.

Fix a bad merge of release-v1.20.0 to develop

---

changelog.d/8364.bugfix
synapse/handlers/device.py
tests/handlers/test_device.py
tests/rest/admin/test_device.py

* Create a new function to verify that the length of a device name is
under a certain threshold.
* Refactor old code to use said function.
* Verify device name length during registration of device
* Add a test for the above

Create function to check for long names in devices

---

changelog.d/8375.doc
docs/reverse_proxy.md

After installing and enabling mod_security2 on my Apache web server, I noticed that Synapse users were unable to send messages. It was still possible to create and modify rooms, but all clients would only show errors to the effect of "Unable to send message" whenever users tried to send anything.
Hence, this change adds a note and a few lines of configuration settings for Apache users to disable ModSecurity for Synapse's virtual hosts. I can confirm that with this change, Synapse is fully functional again even with ModSecurity enabled by default for other virtual hosts on the same server.
I am not proficient enough with ModSecurity to diagnose the exact setting or rule that causes the issue, but disabling it altogether for the Synapse virtual host is not an issue for my use case. My …

Add note to reverse_proxy.md about disabling Apache's mod_security2

---

changelog.d/8373.bugfix
synapse/storage/databases/main/stats.py

When updating the `room_stats_state` table, we try to check for null bytes slipping in to the content for state events. It turns out we had added `guest_access` as a field to room_stats_state without including it in the null byte check.
Lo and behold, a null byte in a `m.room.guest_access` event then breaks `room_stats_state` updates.
This PR adds the check for `guest_access`, as well as adding an assert if a field is added to `room_stats_state` without being either explicitly included or not included in the null byte check.
I *think* this broke in https://github.com/matrix-org/synapse/commit/6e834e94fcc97811e4cc8185e86c6b9da06eb28e#diff-9fb8e219f876ae3f280bc88c8b9ea972R285.

Fix missing null character check on guest_access room state

---

changelog.d/8353.bugfix
synapse/api/auth.py
synapse/push/pusherpool.py
synapse/storage/databases/main/registration.py

Don't push if an user account has expired

---

changelog.d/8383.misc
synapse/storage/databases/main/account_data.py
synapse/storage/databases/main/deviceinbox.py
synapse/storage/databases/main/devices.py
synapse/storage/databases/main/end_to_end_keys.py
synapse/storage/databases/main/events.py
synapse/storage/databases/main/group_server.py
synapse/storage/databases/main/presence.py
synapse/storage/databases/main/push_rule.py
synapse/storage/databases/main/pusher.py
synapse/storage/databases/main/receipts.py
synapse/storage/databases/main/room.py
synapse/storage/databases/main/tags.py
synapse/storage/util/id_generators.py
tests/storage/test_id_generators.py

This will allow us to hit the DB after we've finished using the generated stream ID.
Split out from #8374.

Use `async with` for ID gens

---

changelog.d/8385.bugfix
synapse/storage/databases/main/events.py

Fix bug which caused failure on join with malformed membership events

---

changelog.d/8371.misc
synapse/state/__init__.py

I'd like to get a better insight into what we are doing with respect to state res. The list of state groups we are resolving across should be short (if it isn't, that's a massive problem in itself), so it should be fine to log it in ite entiretly.
I've done some grepping and found approximately zero cases in which the "shortcut" code delivered the result, so I've ripped that out too.

Improve logging of state resolution

---

changelog.d/8370.misc
synapse/handlers/message.py

this makes it possible to use from the manhole, and seems cleaner anyway.

Factor out `_send_dummy_event_for_room`

---

changelog.d/8386.bugfix
scripts/synapse_port_db

This fixes #8384, but not the underlying issue of why tests didn't fail.

Mark the shadow_banned column as boolean in synapse_port_db.

---

changelog.d/8388.misc
synapse/handlers/federation.py
synapse/handlers/message.py
synapse/handlers/sync.py
synapse/notifier.py
synapse/replication/tcp/client.py
synapse/storage/databases/main/roommember.py
synapse/storage/persist_events.py
synapse/storage/roommember.py
synapse/types.py
tests/replication/slave/storage/test_events.py

The idea is to remove some of the places we pass around `int`, where it can represent one of two things:
1. the position of an event in the stream; or
2. a token that partitions the stream, used as part of the stream tokens.
The valid operations are then:
1. did a position happen before or after a token;
2. get all events that happened before or after a token; and
3. get all events between two tokens.
(Note that we don't want to allow other operations as we want to change the tokens to be vector clocks rather than simple ints)

Add EventStreamPosition type

---

changelog.d/8387.feature
scripts/synapse_port_db

Add new sequences to port DB script

---

changelog.d/8394.bugfix
synapse/config/_base.py
synapse/config/saml2_config.py

#8037 changed the default `autoescape` option when rendering Jinja2 templates from `False` to `True`. This caused some bugs, noticeably around redirect URLs being escaped in SAML2 auth confirmation templates, causing those URLs to break for users.
This change returns the previous behaviour as it stood. We may want to look at each template individually and see whether autoescaping is a good idea at some point, but for now lets just fix the breakage.

Hotfix: disable autoescape by default when rendering Jinja2 templates

---

changelog.d/8374.bugfix
synapse/replication/slave/storage/_base.py
synapse/storage/databases/main/__init__.py
synapse/storage/databases/main/events_worker.py
synapse/storage/databases/main/schema/delta/58/18stream_positions.sql
synapse/storage/util/id_generators.py
tests/storage/test_id_generators.py

On startup `MultiWriteIdGenerator` fetches the maximum stream ID for each instance from the table and uses that as its initial "current position" for each writer. This is problematic as a) it involves either a scan of events table or adding a new index (neither of which is ideal), and b) if rows are being persisted out of order elsewhere while the process restarts then using the maximum stream ID is not correct. This could theoretically lead to race conditions where e.g. events that are persisted out of order are not sent down sync streams.
We fix this by creating a new table that tracks the current positions of each writer to the stream, and update it each time we finish persisting a new entry. This is a relatively small overhead when persisting events. However for the cache invalidation …

Fix MultiWriteIdGenerator's handling of restarts.

---

changelog.d/8396.feature
synapse/storage/databases/main/schema/delta/58/14events_instance_name.sql.postgres
synapse/storage/util/id_generators.py

Fix schema delta for servers that have not backfilled

---

changelog.d/8398.bugfix
synapse/crypto/keyring.py
tests/crypto/test_keyring.py

For various reasons, occasionally we get an event that we have already seen in a federation transaction.
When that happens, `on_receive_pdu` completes immediately, but the server-key fetching logic still has a tiny bit of housekeeping to do, which would happen under the logcontext set up for processing that PDU. Hence, we get warnings about "Re-starting finished log context".
There are two parts to this PR. The first rewrites a test that should have been testing some of this sort of stuff, but actually didn't test what it thought it was at all. (See the commit comment for a little more detail).
The second part actually fixes the problem, by delaying the callback from the keyfetcher. (As a side-effect, we can then remove a different delay elsewhere.)

Fix occasional "Re-starting finished log context" from keyring

---

changelog.d/8405.feature
synapse/res/templates/sso_error.html

We started auto-escaping all templates in #8037, but then backed this out in #8394. When merging forward into develop the fixes for #8394 were gone due to the template being merged with another template in #8248, so this essentially re-applies the fix from #8394 to the new code in develop.
The only concerning value in the template is `error_description` so it is now escaped.

Escape the error description on the sso_error template.

---

changelog.d/8410.bugfix
scripts/synapse_port_db

This table was created in #8034 (1.20.0).  It references
`ui_auth_sessions`, which is ignored, so this one should be too.
Signed-off-by: Dagfinn Ilmari Mannsåker <ilmari@ilmari.org>

Add `ui_auth_sessions_ips` table to `synapse_port_db` ignore list

---

changelog.d/8399.misc
synapse/logging/context.py
tests/crypto/test_keyring.py
tests/unittest.py

The idea here is that there ae some tests where we want to make sure that we are handling logcontexts correctly; the easiest way I could think of to do that was to hook into the logcontext system itself to say "these tests should produce no warnings".
The KeyringTestCase *used* to be logcontext-clean, but isn't any more, cf #8398. I'd like it to stay that way this time around :).

Create a mechanism for marking tests "logcontext clean"

---

changelog.d/8400.bugfix
synapse/handlers/identity.py
synapse/http/__init__.py
synapse/http/client.py
synapse/http/matrixfederationclient.py
synapse/http/proxyagent.py
synapse/util/async_helpers.py
tests/http/test_fedclient.py
tests/http/test_simple_client.py

Turns out that if we get a timeout during connection, then a different exception is raised, which wasn't always handled correctly.
To fix it, catch the exception in SimpleHttpClient and turn it into a RequestTimedOutError (which is already a documented exception).
Also add a description to RequestTimedOutError so that we can see which stage it failed at.
This PR is probably best reviewed commit-by-commit.

Fix handling of connection timeouts in outgoing http requests

---

changelog.d/8406.feature
synapse/replication/http/_base.py

One hope is that this might provide some insights into #3365.

Add metrics to track success/otherwise of replication requests

---

changelog.d/8417.feature
synapse/rest/client/v2_alpha/account.py
tests/rest/client/v2_alpha/test_account.py

Broken in https://github.com/matrix-org/synapse/pull/8275 and has yet to be put in a release. Fixes https://github.com/matrix-org/synapse/issues/8418.
`next_link` is an optional parameter. However, we were checking whether the `next_link` param was valid, even if it wasn't provided. In that case, `next_link` was `None`, which would clearly not be a valid URL.
This would prevent password reset and other operations if `next_link` was not provided, and the `next_link_domain_whitelist` config option was set.

Only assert valid next_link params when provided

---

changelog.d/8404.misc
synapse/storage/databases/main/monthly_active_users.py
tests/storage/test_monthly_active_users.py

This is an attempt to fix #8403, however i'm totally failing to find the correct join magic to make this work.

Filter out appservices from mau count

---

changelog.d/8317.feature
scripts-dev/complement.sh

This PR adds a script that:
* Builds the local Synapse checkout using our existing `docker/Dockerfile` image.
* Downloads [Complement](https://github.com/matrix-org/complement/)'s source code.
* Builds the [Synapse.Dockerfile](https://github.com/matrix-org/complement/blob/master/dockerfiles/Synapse.Dockerfile) using the above dockerfile as a base.
* Builds and runs Complement against it.
This set up differs slightly from [that of the dendrite repo](https://github.com/matrix-org/dendrite/blob/master/build/scripts/complement.sh) (`complement.sh`, `Complement.Dockerfile`), which instead stores a separate, but slightly modified, dockerfile in Dendrite's repo rather than running the one stored in Complement's repo. That synapse equivalent to that dockerfile (`Synapse.Dockerfile`) in …

Add support for running Complement against the local checkout

---

changelog.d/8422.misc
synapse/federation/federation_client.py
synapse/handlers/federation.py
synapse/storage/databases/state/store.py
synapse/storage/persist_events.py
synapse/storage/state.py

For some reason, an apparently unrelated PR upset mypy about this module. Here are a number of little fixes.
One is pulled out to a separate commit since it was a bit more difficult: it turns out that `get_state_ids_for_pdu` modifies the result returned by `get_state_groups_ids` so I've had to declare the latter to return a `MutableMapping` and chace that down a bit.

Mypy fixes for `synapse.handlers.federation`

---

changelog.d/8419.feature
synapse/storage/util/id_generators.py
tests/storage/test_id_generators.py

We previously assumed "new" writers (one's not in the `stream_positions` table) as starting with position 0. When workers got the correct position for the new writer via `POSITION` the worker would try and fetch all updates between 0 and the new position, which results in table scan of events table for the events stream. 
Broke in #8294

Don't table scan events on worker startup

---

changelog.d/8414.bugfix
synapse/rest/client/v2_alpha/account.py

This endpoint should only deal with emails that have already been approved, and are attached to the user's account. There's no need to re-check them here.
This can cause password resets to fail if a user signed up while there was one 3PID policy on the server, and then tries to reset their password after a different policy has been put in place that denies their existing email address.

Don't check whether a 3pid is allowed to register during password reset

---

changelog.d/8415.doc
docs/sample_config.yaml
synapse/config/server.py

This is an attempt to get fewer people setting up their server with a server name of matrix.whatever.tld. Any suggestions for improvements here are welcome but I think this is already much better than the current 5 year old description of `server_name`.
This also mentions that the server name should be lowercase like mentioned in #7728 but that issue should probably still be kept open until it is actually validated.

Update description of server_name config option

---

changelog.d/8423.misc
synapse/events/__init__.py
synapse/handlers/admin.py
synapse/handlers/device.py
synapse/handlers/initial_sync.py
synapse/handlers/pagination.py
synapse/handlers/room.py
synapse/handlers/sync.py
synapse/notifier.py
synapse/replication/tcp/client.py
synapse/rest/admin/__init__.py
synapse/storage/databases/main/stream.py
synapse/storage/persist_events.py
synapse/types.py
tests/rest/client/v1/test_rooms.py
tests/storage/test_purge.py

The various commits should be relatively independent. I bundled them into one PR mainly to avoid having to build PRs on PRs, but can split them up a bit more.
The idea is just to simplify the code a bit to make it easier to change the formats of the room stream tokens.

Various clean ups to room stream tokens.

---

changelog.d/8420.feature
synapse/handlers/federation.py
synapse/state/__init__.py
synapse/util/metrics.py

This aims to make it easier to see which rooms are causing the most CPU and database activity for state resolution.
We report two things:
* Every two minutes, we write an entry to the log recording listing the 10 "most expensive" rooms by each metric (CPU time and DB time). This is disabled by default: to enable, configure the `synapse.state.metrics` logger to DEBUG.
* We also expose, via prometheus, a pair of metrics (`synapse_state_res_db_for_biggest_room_seconds_total` and `synapse_state_res_cpu_for_biggest_room_seconds_total`) which keeps a *running total* of the time spent resolving the *single* most expensive room (over any given 2-minute period).
As it is a running total, it will be necessary to take the derivative (for example: …

Report metrics on expensive rooms for state res

---

changelog.d/8426.removal
synapse/metrics/_exposition.py
synapse/python_dependencies.py

Drop compatibility hacks for prometheus-client pre 0.4.0. Debian stretch and
Fedora 31 both have newer versions, so hopefully this will be ok.

Drop support for ancient prometheus_client

---

changelog.d/8413.feature
docs/sample_config.yaml
docs/sso_mapping_providers.md
docs/workers.md
synapse/config/oidc_config.py
synapse/handlers/auth.py
synapse/handlers/oidc_handler.py
synapse/rest/client/v1/login.py
tests/handlers/test_oidc.py

This adds a feature that additional SSO properties can be passed down to the client, note that this is only implemented for OpenID Connect, but I believe it is abstracted enough that it should be easily implemented for SAML/CAS.
This works by processing the OIDC response claims and storing additional information and then using Synapse's login callback mechanism to add fields to the login response. The mapping provider has gained an additional method (`get_extra_attributes`) in order to support this, but the code handles this method not existing. The built-in mapping provider (which uses Jinja2) was updated to provide this functionality via the config file.

Allow additional SSO properties to be passed to the client

---

changelog.d/8425.feature
synapse/metrics/__init__.py
synapse/metrics/_exposition.py
synapse/storage/databases/main/metrics.py
tests/storage/test_event_metrics.py

Hopefully, `(N(extremities)-1) * N(state_events)` is a more realistic approximation to "how big a problem is this room?".
In order to get there, I've replaced `BucketCollector` with something else. I think it's a bit easier to use.

Add an improved "forward extremities" metric

---

changelog.d/8427.misc
synapse/handlers/events.py
synapse/handlers/initial_sync.py
synapse/handlers/pagination.py
synapse/handlers/room.py
synapse/handlers/search.py
synapse/rest/admin/__init__.py
synapse/rest/client/v1/events.py
synapse/rest/client/v1/initial_sync.py
synapse/rest/client/v1/room.py
synapse/rest/client/v2_alpha/keys.py
synapse/rest/client/v2_alpha/sync.py
synapse/storage/databases/main/purge_events.py
synapse/streams/config.py
synapse/types.py
tests/rest/client/v1/test_rooms.py
tests/storage/test_purge.py

The idea is that in future tokens will encode a mapping of instance to position. However, we don't want to include the full instance name in the string representation, so instead we'll have a mapping between instance name and an immutable integer ID in the DB that we can use instead. We'll then do the lookup when we serialize/deserialize the token (we could alternatively pass around an `Instance` type that includes both the name and ID, but that turns out to be a lot more invasive).

Make token serializing/deserializing async

---

changelog.d/8430.feature
docs/sample_config.yaml
synapse/config/_util.py
synapse/config/federation.py
synapse/config/homeserver.py
synapse/config/tls.py
synapse/federation/federation_server.py
synapse/federation/sender/transaction_manager.py

Add a pair of federation metrics to track the delays in sending PDUs to/from particular servers.

Add prometheus metrics to track federation delays

---

changelog.d/8432.misc
mypy.ini
synapse/config/tls.py
synapse/federation/federation_server.py
synapse/handlers/directory.py
synapse/handlers/room.py
synapse/handlers/room_member.py
synapse/handlers/sync.py
synapse/http/server.py
synapse/logging/_structured.py
synapse/push/push_rule_evaluator.py
synapse/replication/tcp/protocol.py
synapse/state/__init__.py
synapse/storage/databases/main/censor_events.py
synapse/storage/databases/main/events.py
synapse/storage/databases/main/stream.py
synapse/storage/util/id_generators.py

This enables an additional check in `mypy` to tell whether code is unreachable or not. I believe that this would have caught https://github.com/matrix-org/synapse/pull/8345#discussion_r492913243, but mypy had given up checking that function since it thought the rest of it was unreachable.
This required adding some type info:
* Class attributes that start as `None` and get filled in later.
* A couple of missing / incorrect types.
* Some handling of `bytes` vs. `str` on Python 2 vs 3.

Enable mypy checking for unreachable code and fix instances.

---

changelog.d/8440.bugfix
synapse/rest/client/v1/login.py

This was breaking logins for Element iOS.
Related to #8320

Do not expose the experimental appservice login flow to clients.

---

changelog.d/8433.misc
mypy.ini
stubs/txredisapi.pyi
synapse/replication/tcp/handler.py
synapse/replication/tcp/redis.py
tests/replication/_base.py
tests/replication/test_sharded_event_persister.py
tests/unittest.py

This involves adding support in unit tests for:
1. using Redis for replication, this is done by creating a fake in memory one; and
2. allowing workers to send replication HTTP requests to other workers, rather than just master.

Add unit test for event persister sharding

---

changelog.d/8442.bugfix
synapse/federation/sender/per_destination_queue.py

logging a generator isn't terribly helpful.

Fix malformed log line in new federation "catch up" logic

---

changelog.d/8444.bugfix
synapse/config/_base.py
synapse/config/captcha.py
synapse/config/consent_config.py
synapse/config/registration.py
synapse/res/templates/auth_success.html
synapse/res/templates/recaptcha.html
synapse/res/templates/terms.html
synapse/rest/client/v2_alpha/auth.py

This converts a few more of our inline HTML templates to Jinja. This is somewhat part of #7280 and should make it a bit easier to customize these in the future.

Convert additional templates to Jinja

---

changelog.d/8447.bugfix
synapse/storage/util/id_generators.py

For negative streams we have to negate the internal stream ID before
querying the DB.
The effect of this bug was to query far too many rows, slowing start up
time, but we would correctly filter the results afterwards so there was
no ill effect.

Fix DB query on startup for negative streams.

---

changelog.d/8443.misc
demo/start.sh

This sets `public_baseurl` when using the demo `start.sh` script. I find I run into this being `None` frequently when enabling "extra" features (SSO, etc.)
Can this even be `None` in the first place? Is that a valid configuration? Should we assert that in a single place instead of many places?

Include a public_baseurl in demo script.

---

changelog.d/8438.bugfix
synapse/rest/media/v1/media_storage.py

https://github.com/matrix-org/synapse/pull/7124 changed the behaviour of remote thumbnails so that the thumbnailing method was included in the filename of the thumbnail. To support existing files, it included a fallback so that we would check the old filename if the new filename didn't exist.
Unfortunately, it didn't apply this logic to storage providers, so any thumbnails stored on such a storage provider was broken.

Fix bug in remote thumbnail search

---

changelog.d/8448.misc
scripts/synapse_port_db
synapse/app/_base.py
synapse/storage/database.py
synapse/storage/databases/__init__.py
synapse/storage/databases/main/__init__.py
synapse/storage/databases/main/event_push_actions.py
synapse/storage/databases/main/monthly_active_users.py
synapse/storage/databases/main/roommember.py
synapse/storage/databases/main/schema/delta/20/pushers.py
synapse/storage/databases/main/schema/delta/25/fts.py
synapse/storage/databases/main/schema/delta/27/ts.py
synapse/storage/databases/main/schema/delta/30/as_users.py
synapse/storage/databases/main/schema/delta/31/pushers.py
synapse/storage/databases/main/schema/delta/31/search_update.py
synapse/storage/databases/main/schema/delta/33/event_fields.py
synapse/storage/databases/main/schema/delta/33/remote_media_ts.py
synapse/storage/databases/main/schema/delta/56/unique_user_filter_index.py
synapse/storage/databases/main/schema/delta/57/local_current_membership.py
synapse/storage/prepare_database.py
synapse/storage/types.py
synapse/storage/util/id_generators.py
synapse/storage/util/sequence.py
tests/storage/test_appservice.py
tests/utils.py

This is so we can tell what is going on when things are taking a while to start up.
The main change here is to ensure that transactions that are created during startup get correctly logged like normal transactions.

Add logging on startup/shutdown

---

changelog.d/8454.bugfix
synapse/api/constants.py
synapse/handlers/room_member.py
synapse/handlers/sync.py
synapse/storage/databases/main/account_data.py
synapse/visibility.py

This looks at the few instances where we look at `"m.ignored_user_list"` account data and adds validation to ensure we don't assume the type of the data.
While I was in there I added constants for the `account_data` types.
Fixes #8357.

Do not assume that m.ignored_user_list data is of the correct form.

---

changelog.d/8462.doc
docs/manhole.md

Updates the docs to use `defer.ensureDeferred` to schedule coroutines with the reactor.
Related to #7988.

Update manhole documentation for async/await.

---

changelog.d/8452.misc
synapse/events/__init__.py
synapse/events/utils.py
synapse/federation/sender/__init__.py
synapse/federation/sender/per_destination_queue.py
synapse/handlers/federation.py
synapse/handlers/message.py
synapse/handlers/room_member.py
synapse/rest/admin/__init__.py
synapse/storage/databases/main/events.py
synapse/storage/databases/main/events_worker.py
synapse/storage/databases/main/stream.py
synapse/storage/persist_events.py

If we already have the event, we already have its stream ordering.

Remove redundant loads of stream_ordering for events

---

changelog.d/8457.bugfix
synapse/event_auth.py

This seems to handle another case of #6771, although I'm not confident it is the correct change. (It will essentially mean that if `event.redacts` is `None` than an `AuthError` will raise.)
Fixes #8397

Ensure that event.redacts exists before handling it as a string

---

changelog.d/8461.feature
docs/sample_config.yaml
synapse/config/server.py
tests/rest/client/v1/test_directory.py

Per https://github.com/matrix-org/matrix-doc/pull/2788

Update default room version to 6

---

changelog.d/8465.bugfix
synapse/http/server.py
synapse/rest/media/v1/_base.py

This PR ports the quick fix from https://github.com/matrix-org/synapse/pull/2796 to further methods which handle media, URL preview and `/key/v2/server` requests. This prevents a harmless `ERROR` that comes up in the logs when we were unable to respond to a client request when the client had already disconnected. In this case we simply bail out if the client has already done so.
This is the 'simple fix' as suggested by https://github.com/matrix-org/synapse/issues/5304#issuecomment-574740003.
Fixes https://github.com/matrix-org/synapse/issues/6700
Fixes https://github.com/matrix-org/synapse/issues/5304
I was still seeing these in my logs, hence the quick PR for them.

Don't bother responding to client requests that have already disconnected

---

changelog.d/8467.feature
synapse/events/third_party_rules.py
tests/rest/client/test_third_party_rules.py

PR #8292 tried to maintain backwards compat with modules which don't provide a
`check_visibility_can_be_modified` method, but the tests weren't being run,
and the check didn't work.

Fix third-party event modules for `check_visibility_can_be_modified` check

---

changelog.d/8468.misc
synapse/events/third_party_rules.py
tests/rest/client/test_third_party_rules.py

Additional tests for third-party event rules

---

changelog.d/8312.feature
scripts/synapse_port_db
synapse/handlers/e2e_keys.py
synapse/handlers/sync.py
synapse/rest/client/v2_alpha/sync.py
synapse/storage/databases/main/end_to_end_keys.py
synapse/storage/databases/main/schema/delta/58/11fallback.sql
tests/handlers/test_e2e_keys.py

Implements [MSC2732](https://github.com/matrix-org/matrix-doc/pull/2732)
Corresponds to https://github.com/matrix-org/matrix-js-sdk/pull/1467

Add support for olm fallback keys

---

changelog.d/8464.misc
docs/spam_checker.md
synapse/app/homeserver.py
synapse/events/spamcheck.py
synapse/events/third_party_rules.py
synapse/handlers/auth.py
synapse/module_api/__init__.py
synapse/server.py
synapse/spam_checker_api/__init__.py
tests/module_api/test_api.py

Lots of different module apis is not easy to maintain.
Rather than adding yet another `ModuleApi(hs, hs.get_auth_handler())` incantation, first add an `hs.get_module_api()` method and use it where possible.

Combine `SpamCheckerApi` with the more generic `ModuleApi`.

---

changelog.d/8463.misc
synapse/handlers/message.py
synapse/handlers/room.py
synapse/handlers/room_member.py
tests/handlers/test_register.py
tests/unittest.py

Currently there's a somewhat separate codepath for handling membership events in the C-S API. The idea here is to try to bring them somewhat in line by killing off `send_nonmember_event`.
The commits here should be reviewable independently.

Reduce inconsistencies between codepaths for membership and non-membership events.

---

changelog.d/8475.misc
scripts-dev/build_debian_packages

Also see matrix-org/pkg-repo-configs#3.

Add Ubuntu 20.10 (Groovy Gorilla) to build scripts.

---

changelog.d/8486.bugfix
synapse/handlers/sync.py

Currently passing the `prev_batch` token to `/messages` incorrectly returns the events in the sync response.
SyTest: https://github.com/matrix-org/sytest/pull/971
Broke by https://github.com/matrix-org/synapse/commit/faad233ea61cfff2c377609fa1d3c64d39f8a039 which was released in v0.16.0

Fix returning incorrect prev_batch token in incremental sync

---

changelog.d/8456.misc
synapse/storage/database.py
synapse/storage/engines/_base.py
synapse/storage/engines/postgres.py
synapse/storage/engines/sqlite.py
synapse/storage/util/id_generators.py
tests/storage/test_base.py

We call `_update_stream_positions_table_txn` a lot, which is an UPSERT
that can conflict in `REPEATABLE READ` isolation level. Instead of doing
a transaction consisting of a single query we may as well run it outside
of a transaction.

Reduce serialization errors in MultiWriterIdGen

---

changelog.d/8492.misc
synapse/util/module_loader.py

This turns:
Failed to parse config for 'myplugin': Exception('error message')
into:
Failed to parse config for 'myplugin': error message.

Clarify error message when plugin config parsers raise an error

---

README.rst
changelog.d/8493.doc

Resolves #8348 
Added shields directing to synapse-dev room, showing license, latest version on PyPi and supported Python versions.
I've moved substitution definitions to the bottom to improve readability.
Signed-off-by: Mateusz Przybyłowicz <uamfhq@gmail.com>

Add useful shields to readme

---

changelog.d/8501.bugfix
changelog.d/8501.feature
synapse/storage/databases/main/end_to_end_keys.py
tests/handlers/test_e2e_keys.py

Fixes a bug introduced in #8312.

invalidate the cache when a fallback key is uploaded

---

changelog.d/8505.misc
mypy.ini
synapse/federation/federation_server.py
synapse/handlers/account_data.py
synapse/handlers/deactivate_account.py
synapse/handlers/devicemessage.py
synapse/handlers/password_policy.py
synapse/handlers/read_marker.py
synapse/notifier.py
synapse/storage/databases/main/registration.py

This adds type hints to a few handlers that were all pretty straightforward.

Add type hints to some handlers

---

changelog.d/8489.feature
synapse/app/phone_stats_home.py
synapse/storage/databases/main/censor_events.py
synapse/storage/databases/main/devices.py
synapse/storage/databases/main/event_federation.py
synapse/storage/databases/main/event_push_actions.py
synapse/storage/databases/main/monthly_active_users.py
synapse/storage/databases/main/registration.py

Building on #8369 and #8458 -- move more tasks to the background worker. As the review from #8369 this uses `wrap_as_background_process` in more places for consistency. It cleans up a few spots missed from other PRs too.
Related to #8500.

Move additional tasks to the background worker, part 3

---

changelog.d/8496.misc
synapse/replication/tcp/streams/_base.py
synapse/replication/tcp/streams/events.py
synapse/storage/databases/main/events.py
synapse/storage/databases/main/events_worker.py
synapse/storage/databases/main/schema/delta/58/20instance_name_event_tables.sql

When pulling events out of the DB to send over replication we were not
filtering by instance name, and so we were sending events for other
instances.

Only send RDATA for instance local events.

---

changelog.d/8479.feature
synapse/handlers/message.py
synapse/module_api/__init__.py
tests/module_api/test_api.py
tests/rest/client/test_third_party_rules.py

This PR allows Synapse modules making use of the `ModuleApi` to create and send non-membership events into a room. This can useful to have modules send messages, or change power levels in a room etc. Note that they must send event through a user that's already in the room.
The non-membership event limitation is currently arbitrary, as it's another chunk of work and not necessary at the moment.
I'm expecting this to conflict with https://github.com/matrix-org/synapse/pull/8463. I'd like to get that one merged first before merging this one.

Allow modules to create and send events into rooms

---

changelog.d/8507.misc
mypy.ini
synapse/appservice/api.py
synapse/federation/federation_server.py
synapse/handlers/initial_sync.py
synapse/handlers/room.py
synapse/handlers/sync.py
synapse/replication/http/_base.py
synapse/util/caches/response_cache.py

This was a left-over branch from my async work. I never got around to converting the response cache to async/await, but I did add type hints to it.

Add type hints to response cache.

---

changelog.d/8497.misc
tests/server.py

This could, very occasionally, cause:
```
tests.test_visibility.FilterEventsForServerTestCase.test_large_room
===============================================================================
[ERROR]
File "/src/tests/rest/media/v1/test_media_storage.py", line 86, in test_ensure_media_is_in_local_cache
self.wait_on_thread(x)
File "/src/tests/unittest.py", line 296, in wait_on_thread
self.reactor.advance(0.01)
File "/src/.tox/py35/lib/python3.5/site-packages/twisted/internet/task.py", line 826, in advance
self._sortCalls()
File "/src/.tox/py35/lib/python3.5/site-packages/twisted/internet/task.py", line 787, in _sortCalls
self.calls.sort(key=lambda a: a.getTime())
builtins.ValueError: list modified during sort …
```

Fix threadsafety in ThreadedMemoryReactorClock

---

changelog.d/8514.misc
tests/server.py
tests/utils.py

I think this was left-over cruft from switching from a single datastore to multiple datastores.

Clean-up some broken code in the test framework

---

changelog.d/8390.docker
docker/README.md
docker/start.py

Updated the docker `start.py` to allow passing commandline args to the synapse process (fixes #6662).
`Signed-off-by: Samuel Philipp <codes@samuel-philipp.de>`

Docker: support passing additional commandline args to synapse

---

changelog.d/8499.misc
docs/tcp_replication.md
synapse/replication/tcp/client.py
synapse/replication/tcp/commands.py
synapse/replication/tcp/handler.py
synapse/replication/tcp/resource.py
synapse/storage/util/id_generators.py
synapse/storage/util/sequence.py
tests/storage/test_id_generators.py

Currently background proccesses stream the events stream use the "minimum persisted position" (i.e. `get_current_token()`) rather than the vector clock style tokens. This is broadly fine as it doesn't matter if the background processes lag a small amount. However, in extreme cases (i.e. SyTests) where we only write to one event persister the background processes will never make progress.
This PR changes it so that the `MultiWriterIDGenerator` keeps the current position of a given instance as up to date as possible (i.e using the latest token it sees if its not in the process of persisting anything), and then periodically announces that over replication. This then allows the "minimum persisted position" to advance, albeit with a small lag.
~~Based on #8496.~~

Make event persisters periodically announce position over replication.

---

debian/build_virtualenv
debian/changelog

After https://github.com/matrix-org/synapse/pull/8377, the deb packages no longer indirectly installed the `"test"` dependencies, causing debian packages to fail to build while carrying out the unit tests.
This PR installs `test` dependencies explicitly when building debian packages.

Explicitly install test dependencies when building deb packages

---

.circleci/config.yml
changelog.d/7921.docker

Multi arch docker support: add arm/v7 and arm64 to our docker images

---

changelog.d/8513.feature
synapse/handlers/account_validity.py
synapse/handlers/deactivate_account.py
synapse/handlers/message.py
synapse/handlers/pagination.py
synapse/handlers/profile.py
synapse/server.py
synapse/storage/databases/main/profile.py
synapse/storage/databases/main/registration.py
synapse/storage/databases/main/room.py
tests/handlers/test_typing.py

This moves the last (?) of the available tasks to the background worker.
Related to #8500

Move additional tasks to the background worker, part 4

---

changelog.d/8517.bugfix
synapse/rest/client/v1/profile.py

Add correct M_BAD_JSON error code to /profile/{userId}/displayname

---

changelog.d/8527.bugfix
synapse/events/validator.py
synapse/storage/databases/main/events.py

While this isn't a security issue, it causes Synapse to insert bogus values into the `room_retention` table which can make debugging issues more difficult.

Make sure a retention policy is a state event

---

changelog.d/8536.bugfix
synapse/app/generic_worker.py
synapse/federation/send_queue.py
synapse/federation/sender/__init__.py
synapse/handlers/appservice.py
synapse/notifier.py
synapse/push/emailpusher.py
synapse/push/httppusher.py
synapse/push/pusherpool.py
tests/handlers/test_appservice.py

The federation senders could miss events that should be sent due to incorrectly advancing their stream position before all event writers had finished writing their events. Events would be pulled in by other servers the next time an event in that room was sent by that server.
To try and prevent this we convert some functions to accept `RoomStreamToken` rather than `int`

Fix not sending events over federation when using sharded event persisters

---

changelog.d/8529.doc
docs/message_retention_policies.md

Document the changes from https://github.com/matrix-org/synapse/pull/8104

Update documentation on retention policies limits

---

changelog.d/8526.doc
docs/manhole.md

Add note to manhole.md about bind_address when using with docker

---

changelog.d/8530.bugfix
synapse/storage/util/id_generators.py

We asserted that the IDs returned by postgres sequence was greater than
any we had seen, however this is technically racey as we may update the
current positions out of order.
We now assert that the sequences are correct on startup, so the
assertion is no longer really required, so we remove them.
(I have only seen this once, so in practice I think this is rare)

Remove racey assertion in MultiWriterIDGenerator

---

changelog.d/8542.misc
synapse/storage/database.py
synapse/storage/databases/main/keys.py
synapse/storage/databases/main/transactions.py
synapse/storage/databases/main/user_directory.py

Autocommit means that we don't wrap the functions in transactions, and instead get executed directly. Introduced in #8456. This will help:
1. reduce the number of `could not serialize access due to concurrent delete` errors that we see (though there are a few functions that often cause serialization errors that we don't fix here);
2. improve the DB performance, as it no longer needs to deal with the overhead of `REPEATABLE READ` isolation levels; and
3. improve wall clock speed of these functions, as we no longer need to send `BEGIN` and `COMMIT` to the DB.
Some notes about the differences between autocommit mode and our default `REPEATABLE READ` transactions:
1. Currently `autocommit` only applies when using PostgreSQL, and is ignored when using SQLite (due to silliness with [Twisted DB …

Use autocommit mode for single statement DB functions.

---

changelog.d/8537.misc
synapse/events/builder.py
synapse/handlers/message.py
synapse/handlers/room.py
synapse/handlers/room_member.py
tests/handlers/test_message.py
tests/handlers/test_presence.py
tests/replication/test_federation_sender_shard.py
tests/storage/test_redaction.py

Update `EventCreationHandler.create_event` to accept an auth_events param, and use it in `_locally_reject_invite` instead of reinventing the wheel.
Before that, a housekeeping commit to remove the redundant `token_id` parameter to create_event.

Simplify `_locally_reject_invite`

---

changelog.d/8548.misc
synapse/replication/slave/storage/client_ips.py
synapse/storage/databases/main/client_ips.py
synapse/storage/databases/main/devices.py
synapse/storage/databases/main/events_worker.py
synapse/util/caches/deferred_cache.py
synapse/util/caches/descriptors.py
synapse/util/caches/lrucache.py
tests/storage/test__base.py
tests/test_metrics.py
tests/util/caches/test_deferred_cache.py
tests/util/caches/test_descriptors.py

The general premise here is that we have too many things called "Cache", and it's unclear what is special about `Cache`. We rename it to DeferredCache, and while we're at it, move it to a more appropriately-named module, and do a couple of other cleanups.
The diff here is going to be horrific, but that's mostly due to the move from one module to another. I suggest reviewing per-commit; 4182bb812 just lifts the implementation and tests into the new module and updates the references.

Rename Cache to DeferredCache, and related changes

---

changelog.d/8515.misc
synapse/server.py
tests/app/test_frontend_proxy.py
tests/app/test_openid_listener.py
tests/replication/_base.py
tests/replication/test_federation_ack.py
tests/utils.py

> Add `version_string` attribute to HomeServer
> Fix cache injection on tests, and make more explicit
Supersedes #8466

Remove setattr with kwargs from HomeServer class 2: Electric bungaloo

---

changelog.d/8535.feature
synapse/events/__init__.py
synapse/events/third_party_rules.py
synapse/handlers/federation.py
synapse/handlers/message.py
tests/rest/client/test_third_party_rules.py

The idea here is that a module implementing `check_event_allowed` might want to change the content of the event before allowing it. We extend the API to allow it to return a replacement event dict.
A couple of housekeeping commits first, to reduce the duplication between `check_event_allowed` calls. Suggest reviewing them separately.

Support modifying event content from ThirdPartyRules modules

---

changelog.d/8564.feature
synapse/events/builder.py
synapse/handlers/message.py

EventBuilder.build wants auth events these days
I think I forgot about this because #8535 and #8537 went through CI at the same time.

Fix modifying events in `ThirdPartyRules` modules

---

changelog.d/8561.misc
synapse/api/auth.py
synapse/push/push_rule_evaluator.py
synapse/util/caches/__init__.py
synapse/util/caches/deferred_cache.py
synapse/util/caches/dictionary_cache.py
synapse/util/caches/lrucache.py
tests/util/test_lrucache.py

rather than have everything that instantiates an LruCache manage metrics separately, have LruCache do it itself.

Make LruCache register its own metrics

---

changelog.d/8544.feature
synapse/storage/databases/main/events_worker.py

This is a minor clean-up since #8476 wasn't based on develop initially. It moves the periodic task added in that PR to be run on the background worker instead of the main process.
Related to #8500.

Clean-up old transaction IDs on the background worker.

---

changelog.d/8562.misc
synapse/api/auth.py
synapse/push/push_rule_evaluator.py
synapse/util/caches/deferred_cache.py
synapse/util/caches/dictionary_cache.py
synapse/util/caches/lrucache.py

Type annotations for LruCache

---

changelog.d/8577.misc
synapse/storage/database.py
synapse/storage/types.py

> Fix the Connection protocol according to typeshed's assertions about sqlite3.Connection
Starting with `mypy` `0.790`, `typeshed` has [updated](https://github.com/python/typeshed/commit/baaffed1ac06d14c72d8e3c621f9721e844a4580) it's assertions about [`sqlite.Connection.__exit__`'s type signature](https://github.com/python/typeshed/blob/baaffed1ac06d14c72d8e3c621f9721e844a4580/stdlib/2and3/sqlite3/dbapi2.pyi#L175), which means that in the future mypy releases, this error will show up.
This is related to #8576, as trying to fix that (by bumping the mypy release) will likely stumble across the issue this PR is fixing.
- Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from …

Pre-emptively fix synapse.storage.types.Connection for future mypy release

---

changelog.d/8563.misc
synapse/replication/slave/storage/client_ips.py
synapse/storage/_base.py
synapse/storage/databases/main/client_ips.py
synapse/storage/databases/main/devices.py
synapse/storage/databases/main/events.py
synapse/storage/databases/main/events_worker.py
synapse/util/caches/lrucache.py

Now that LruCache manages its own metrics (as of #8561), these uses don't need a full-blown DeferredCache, and LruCache is lighter and more appropriate.

Replace DeferredCache with LruCache where possible

---

changelog.d/8567.bugfix
synapse/metrics/background_process_metrics.py

This should reduce the number of `There was no active span` errors we
see.
Fixes #8510.

Start an opentracing span for background processes.

---

changelog.d/8578.misc
synmark/__init__.py

I feel like we should probably just be using the global reactor, but maybe there was a reason for importing it this way?

Support macOS in synmark

---

changelog.d/8545.bugfix
synapse/push/mailer.py
synapse/res/templates/notif.html
synapse/res/templates/notif.txt
synapse/res/templates/notif_mail.html
synapse/res/templates/notif_mail.txt
synapse/res/templates/room.html
synapse/res/templates/room.txt
tests/push/test_email.py

This does two separate things and is probably best reviewed commit by commit:
* Includes a simple message: "An encrypted message." if a notification is trigged by an encrypted message.
* Uses JInja's [whitespace control syntax](https://jinja.palletsprojects.com/en/2.10.x/templates/#whitespace-control) to avoid adding unnecessary whitespace to the email (this looks awful for the text email in particular). (An alternative to this would be to tweak how we render the templates, which would affect all templates we render.)
Note that the added test doesn't *really* test #8416 as it passes before this branch, but it seemed simple to add.
Fixes #8416.

Include a simple message in email notifications that include encrypted content

---

changelog.d/8568.misc
synapse/push/bulk_push_rule_evaluator.py
synapse/storage/databases/main/pusher.py
synapse/storage/databases/main/receipts.py
synapse/storage/databases/main/roommember.py
synapse/util/caches/deferred_cache.py
tests/util/caches/test_deferred_cache.py

A bunch of things that are currently calling `DeferredCache.get` are only really interested in the result if it's completed. We can optimise and simplify this case.
Once we do so it turns out that the `default` param to `DeferredCache.get` is unused and we can kill it off.

Add `DeferredCache.get_immediate` method

---

changelog.d/8504.bugfix
synapse/rest/client/v1/login.py

This essentially reverts #8440. Is related to #8320. 
It would be good to get confirmation that vector-im/element-ios#3711 is fixed before releasing this.

Expose the experimental appservice login flow to clients.

---

changelog.d/8569.misc
synapse/handlers/auth.py
tox.ini

> (Wants bytes, got Union[bytes, str] due to context closure inheritance)

Fix mypy error: auth handler "checkpw" internal function type mismatch

---

changelog.d/8589.removal
synapse/storage/databases/main/schema/delta/58/21drop_device_max_stream_id.sql

Closes #7887. 
Signed-off-by: Vasilis Gerakaris <vasilis.gerakaris@navarino.gr>

Drop unused `device_max_stream_id` table

---

changelog.d/8591.misc
synapse/util/caches/lrucache.py
tests/util/test_lrucache.py

We need to make sure we are readu for the `set_cache_factor` callback.
Fixes #8586. (Introduced in #8561.)

Fix 'LruCache' object has no attribute '_on_resize'

---

changelog.d/8585.bugfix
scripts/synapse_port_db

I noticed in https://github.com/matrix-org/synapse/issues/8575 that the `end_error` variable in `synapse_port_db` is set to an `Exception`, even though later we expect it to be a `str`.
This PR simply casts an exception raised to a string. I'm doing this instead of having `end_error` be of type exception as we explicitly set `end_error` to a str here:
https://github.com/matrix-org/synapse/blob/d25eb8f3709965d0face01a041d5292490bf0139/scripts/synapse_port_db#L542-L547
This whole file could probably use some heavy refactoring, but until then at least this fix will prevent exception contents from being hidden from us and users.

Cast errors generated during synapse_port_db to str

---

changelog.d/8592.misc
tests/rest/client/v2_alpha/test_account.py
tests/rest/client/v2_alpha/test_auth.py

I found some `@unittest.INFO`s lying around that seem to be accidentally included from their respective PRs. Let's axe them.

Remove some extraneous @unittest.INFOs on unit tests

---

changelog.d/8583.misc
setup.py
tox.ini

Fixes #8576
Depends on #8569 (i'll rebase this once it gets merged)

Update mypy to 0.790, and move dependencies to extras

---

changelog.d/8599.feature
synapse/handlers/account_validity.py
synapse/handlers/profile.py
synapse/storage/databases/main/events_worker.py
synapse/storage/databases/main/roommember.py

This is a bit of clean-up for the tasks running as background workers (#8500), where we weren't consistently using the `wrap_as_background_task` wrapper in all places.
In particular this updates code from #8458, #8513, and #8544 to consistently use this decorator.

Consistently use wrap_as_background_task in more places

---

changelog.d/8600.misc
setup.py

After merging #8576 I re-installed mypy and got the pip warning:
```
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.
We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.
mypy-zope 0.2.7 requires mypy==0.780, but you'll have mypy 0.790 which is incompatible.
```
Since I already had `mypy-zope` installed it did not update it. I think we should just pin it.

Pin mypy-zope for compatibility with mypy.

---

changelog.d/8587.misc
synapse/logging/_remote.py
synapse/logging/_terse_json.py
tests/logging/test_terse_json.py

This does not change any functionality but breaks the dependency between the Twisted TCP logging code and it having to do the terse JSON output. The goal was a better separation between "transport" and "formatter". I'm hoping this will help make the code a bit more readable and help with being able to enable structured logging at the same time as standard logging (although this PR does not allow that).
It is pretty much:
* Copying and pasting `LogProducer` and `TerseJSONToTCPLogObserver` (renamed to `TCPLogObserver`) from `synapse.logging._terse_json` to `synapse.logging._remote`.
* Add a wrapper to `synapse.logging._terse_json` to hook up `TCPLogObserver` with the terse JSON formatting code.
* Pass throw the `format_event` callable through `TCPLogObserver` into `LogProducer` instead of a …

Separate the TCP and terse JSON formatting code.

---

changelog.d/8606.feature
synapse/appservice/scheduler.py
tests/appservice/test_scheduler.py

Fixes https://github.com/matrix-org/synapse/issues/3536
This change imposes a 100 event limit on both the `event` and `ephemeral` sections of appservice transactions, allowing a maximum of 100 events for each.

Limit AS transactions to 100 events

---

changelog.d/8593.misc
synapse/util/caches/deferred_cache.py

Optimisation in DeferredCache.set

---

changelog.d/8594.misc
synapse/util/caches/descriptors.py

don't bother constricting a CacheContext unless we need one.
~~Based on #8572~~

Optimise CacheDescriptor

---

changelog.d/8614.misc
tests/storage/test_cleanup_extrems.py
tests/storage/test_event_metrics.py
tests/storage/test_roommember.py
tests/test_federation.py
tests/unittest.py

Using `create_requester` is easier. This is towards #6054

Don't instansiate Requester directly

---

changelog.d/8628.bugfix
synapse/handlers/groups_local.py

Fixes exceptions such as:
```
IndexError: list index out of range
File "synapse/http/server.py", line 230, in _async_render_wrapper
File "synapse/http/server.py", line 407, in _async_render
File "synapse/rest/client/v2_alpha/groups.py", line 45, in on_GET
group_id, requester_user_id
File "synapse/handlers/groups_local.py", line 31, in f
if self.is_mine_id(group_id):
File "synapse/server.py", line 300, in is_mine_id
return string.split(":", 1)[1] == self.hostname
```

Don't 500 for invalid group IDs

---

changelog.d/8621.misc
synapse/http/servlet.py
synapse/rest/client/v1/events.py
synapse/rest/client/v1/login.py
synapse/rest/client/v1/logout.py
synapse/rest/client/v1/presence.py
synapse/rest/client/v1/profile.py
synapse/rest/client/v1/push_rule.py
synapse/rest/client/v1/pusher.py
synapse/rest/client/v1/room.py
synapse/rest/client/v1/voip.py
synapse/rest/client/v2_alpha/account.py
synapse/rest/client/v2_alpha/auth.py
synapse/rest/client/v2_alpha/register.py

#7534 changed it so that all `OPTIONS` requests get responded to with a `200 "{}"`, but failed to remove some specific handlers for that response type. These are now incorrect once #7886 landed so that they all return a `204 ""`. I think we should just clean them up since they're unused anyway.
This can be tested by checking the result of `curl -vv -X OPTIONS http://localhost:8080/_matrix/client/r0/createRoom`, which is a 204 showing that this code is unused.

Remove specific OPTIONS handlers.

---

changelog.d/8627.bugfix
synapse/push/mailer.py
tests/push/test_email.py

This can happen if e.g. the room invited into is no longer on the server (or if all users left the room).
Fixes stack traces such as:
```
KeyError: ('m.room.member', '<user_id>')
File "synapse/push/emailpusher.py", line 158, in _process
await self._unsafe_process()
File "synapse/push/emailpusher.py", line 207, in _unsafe_process
await self.send_notification(unprocessed, reason)
File "synapse/push/emailpusher.py", line 322, in send_notification
self.app_id, self.user_id, self.email, push_actions, reason
File "synapse/push/mailer.py", line 238, in send_notification_mail
r, user_id, notifs_by_room[r], notif_events, state_by_room[r]
File "synapse/push/mailer.py", line 320, in get_room_vars
my_member_event_id = room_state_ids[("m.room.member", user_id)]
```

Fix email notifications for invites without local state.

---

changelog.d/8632.bugfix
synapse/api/auth.py
synapse/handlers/auth.py
synapse/handlers/cas_handler.py
synapse/handlers/oidc_handler.py
synapse/handlers/saml_handler.py
synapse/http/site.py
tests/handlers/test_oidc.py

Fixes error logs such as:
```
Failed to insert client IP ...  UnicodeEncodeError ... 'surrogates not allowed'
```

Fix handling of User-Agent headers with bad utf-8.

---

changelog.d/8640.misc
synapse/handlers/appservice.py
synapse/logging/opentracing.py
synapse/metrics/background_process_metrics.py
synapse/notifier.py
synapse/push/pusherpool.py
synapse/replication/tcp/redis.py
tests/handlers/test_appservice.py

#8567 started a span for every background process. This is good as it means all Synapse code that gets run should be in a span (unless in the sentinel logging context), but it means we generate about 15x the number of spans as we did previously.
This PR attempts to reduce that number by a) not starting one for send commands to Redis, and b) deferring starting background processes until after we're sure they're necessary.
I don't really know how much this will help.

Start fewer opentracing spans

---

changelog.d/8654.bugfix
synapse/storage/databases/main/metrics.py

Fixes #8641. Broke in #8503.
We should add a unique index here, but it appears we have duplicated entries from before this change. The table is large enough that we can't just delete duplicates during start up, so we'll have to be a bit more cunning and as such I'm punting that for now.
Targeting the release branch since this is sort of a regression.

Fix user_daily_visits to not have duplicate rows for UA.

---

changelog.d/8656.bugfix
synapse/handlers/appservice.py

This backports the bugfix in #8655 to the `release-v1.22.0` branch.
Fixes a bug introduced in #8437.

Properly handle presence events for application services.

---

changelog.d/8580.bugfix
synapse/handlers/profile.py

fixes #8520
This is a quick hack to scratch where it itches. It might make sense to have some central place to check that only allowed status codes are returned, in that case this pull request is irrelevant.
Signed-off-by: Pavel Turinsky <pavel.turinsky@matfyz.cz>

Check status codes that profile handler returns

---

changelog.d/8644.misc
docs/admin_api/user_admin_api.rst
synapse/rest/admin/devices.py
tests/rest/admin/test_device.py

Add field `total` to device list in admin API

---

changelog.d/8634.misc
docs/openid.md

The OpenID Connect install instructions suggested installing `synapse[oidc]`, but our PyPI package is called [`matrix-synapse`](https://pypi.org/project/matrix-synapse/).

Correct the package name in OpenID Connect install instructions

---

changelog.d/8648.bugfix
synapse/handlers/appservice.py
synapse/storage/databases/main/appservice.py
tests/storage/test_appservice.py

Fixes #8603 
Having taken a second look at this bit of code, it was hopelessly wrong. I've fixed the functions and added tests to ensure that they do the right thing.
(I'd like this to be included in RC2, as RC1 included the original buggy code introduced in #8437)

Fix get|set_type_stream_id_for_appservice store functions

---

changelog.d/8643.bugfix
synapse/rest/admin/users.py
tests/rest/admin/test_user.py

Whan you call `GET /users/<user_id>/joined_rooms` and user has no joined rooms, you get an error `Unknown user`.
This PR fix it, to get an empty list and adds an unit test.

Bugfix in joined_rooms admin API if user has no memberships

---

changelog.d/8657.doc
docs/openid.md

Simple typo in the OpenID connect docs.

Fix filepath of Dex example config

---

changelog.d/8519.feature
docs/admin_api/media_admin_api.md
synapse/rest/admin/media.py
synapse/rest/media/v1/filepath.py
synapse/rest/media/v1/media_repository.py
synapse/storage/databases/main/media_repository.py
tests/rest/admin/test_media.py

Related to: #6459, #3479
Add `DELETE /_synapse/admin/v1/media/<server_name>/<media_id>` to delete
a single file from server.
It is the first step. An api with timestamp (older than) is possible later. I will do small stepswith small PR.

Add an admin api to delete local media.

---

CHANGES.md
changelog.d/8582.doc
docs/openid.md

Signed-off-by: Peter Krantz <peter.krantz@gmail.com>

Added basic instructions for Azure AD to OpenId documentation

---

changelog.d/8620.bugfix
changelog.d/8620.misc
mypy.ini
synapse/handlers/account_validity.py
synapse/handlers/profile.py
synapse/storage/databases/main/profile.py
synapse/storage/databases/main/registration.py

This adds type hints to the account validity handler and bled into the profile code a bit.
It fixes a couple of things:
* Proper types for profile display name / avatar URL.
* Proper handling of an account which doesn't expire, which is a "real" bug, but can only be caused by the admin API.

Add type hints for account validity handler

---

changelog.d/8668.misc
synapse/handlers/typing.py

There's no point starting a background process when all its going to do is bail if federation isn't enabled.

Don't unnecessarily start bg process while handling typing.

---

changelog.d/8670.misc
synapse/replication/tcp/resource.py

The function ends up getting poked when we receive replication traffic, so I think we end up being poked needlessly *a lot*

Don't unnecessarily start bg process in replication sending loop.

---

changelog.d/8671.misc
synapse/handlers/message.py
synapse/storage/databases/main/events_worker.py

This is a requirement for [knocking](https://github.com/matrix-org/synapse/pull/6739), and is abstracting some code that was originally used by the invite flow. I'm separating it out into this PR as it's a fairly contained change.
For a bit of context: when you invite a user to a room, you send them [stripped state events](https://matrix.org/docs/spec/server_server/unstable#put-matrix-federation-v2-invite-roomid-eventid) as part of `invite_room_state`. This is so that their client can display useful information such as the room name and avatar. The same requirement applies to knocking, as it would be nice for clients to be able to display a list of rooms you've knocked on - room name and avatar included.
The reason we're sending membership events down as well is in the case that you are …

Abstract code for stripping room state into a separate method

---

changelog.d/8667.doc
contrib/grafana/README.md
docs/metrics-howto.md

Just so we don't confuse people who install the synapse.json dashboard and expect it to work out of the box - more interlinking will help people see the right part of this documentation.

Note where the prometheus recording rules live.

---

INSTALL.md
changelog.d/8665.doc
setup.py
tox.ini

As expected, all tests pass locally without modification.

Note support for Python 3.9

---

README.rst
changelog.d/8666.doc
tox.ini

The test runner isn't present in the `[all]` set of extras, so the
previous instructions did not work without also installing `[test]`.
Note that this does not include the `[lint]` extras, since those do not
install on all supported Python versions (specifically, isort 5.x
requires Python 3.6, while we still support 3.5). Instructions for that
are included in our pull request template, so we should be fine there.
I've also dropped the `--no-use-pep517` arg to `pip install` since it
seems to have been added to address a temporary regression in pip 19.1
which was fixed in pip 19.1.1 the following month.
Lastly, updated the example output of the test suite to set more
realistic expectations around run time.
- Be a short description of your change …

Minor updates to docs on how to run tests

---

changelog.d/8664.misc
pyproject.toml
synapse/http/client.py
synapse/storage/database.py
synapse/util/retryutils.py
tests/replication/_base.py
tests/replication/tcp/streams/test_events.py
tests/server.py
tests/storage/test_client_ips.py
tests/test_utils/event_injection.py

This allows trailing commas in multi-line arg lists.
Minor, but we might as well keep our formatting current with regard to
our minimum supported Python version.

Tell Black to format code for Python 3.5

---

changelog.d/8675.misc
synapse/federation/federation_server.py
synapse/handlers/devicemessage.py

Cross-user `m.key_share_requests` are a relatively new `to_device` message that allows user to re-request session keys for a message from another user if they were otherwise unable to retrieve them.
Unfortunately, these have had performance concerns on matrix.org. This is a temporary patch to disable them while we investigate a better solution.

Patch to temporarily drop cross-user m.key_share_requests

---

changelog.d/8669.misc
synapse/notifier.py
synapse/replication/tcp/client.py
synapse/replication/tcp/streams/events.py
synapse/storage/databases/main/events_worker.py

I was trying to make it so that we didn't have to start a background task when handling RDATA, but that is a bigger job (due to all the code in `generic_worker`). However I still think not pulling the event from the DB may help reduce some DB usage due to replication, even if most workers will simply go and pull that event from the DB later anyway.

Don't pull event from DB when handling replication traffic.

---

changelog.d/8655.misc
mypy.ini
synapse/handlers/appservice.py
synapse/handlers/auth.py
synapse/storage/databases/main/appservice.py

This adds more type hints to the AS code.
This also fixes a bug in the feature introduced in #8437.

Add type hints to application services

---

changelog.d/8678.bugfix
synapse/handlers/message.py
synapse/http/server.py
synapse/storage/databases/main/censor_events.py
synapse/storage/databases/main/events.py
synapse/util/__init__.py
synapse/util/frozenutils.py

898196f1c (part of #8535) introduced an `event.freeze()` into the dataflow, but this meant that parts of the code which did not expect frozendicts suddenly started seeing them.
Not being able to serialise `frozendicts` is fragile, and it's annoying to have
to think about which serialiser you want. There's no real downside to
supporting frozendicts, so let's just have one json encoder.

Fix serialisation errors when using third-party event rules.

---

changelog.d/8559.misc
synapse/handlers/room.py
synapse/handlers/room_member.py

By not dropping the membership lock between invites, we can stop joins from grabbing the lock when we're half-done and slowing the whole thing down.
(Is this a DoS vector? If someone invites thousands of people to a room, they will receive the invite, but won't be able to accept it until the invites have stopped churning? Though we should guard against abusive createRooms anyway.)

Optimise createRoom with multiple invites

---

changelog.d/8679.misc
synapse/events/__init__.py

otherwise non-state events get written as `<FrozenEvent ... state_key='None'>`
which is indistinguishable from state events with the actual state_key `None`.

Use `%r` rather than `%s` for stringifying events

---

changelog.d/8684.misc
scripts-dev/mypy_synapse_plugin.py
synapse/handlers/presence.py

Cached functions accept an `on_invalidate` function, which we failed to add to the type signature. It's rarely used in the files that we have typed, which is why we haven't noticed it before.

Fix cache call signature to accept `on_invalidate`.

---

changelog.d/8607.feature
changelog.d/8607.misc
changelog.d/8685.feature
synapse/logging/_remote.py
tests/logging/test_remote_handler.py

This fixes errors that would appear if Synapse was shutdown with a pending connection in the remote logger.
Without this you would get the following error until the maximum Python stack depth was reached:
```
Failure: twisted.internet.defer.CancelledError: 
```
Part of #8588, this might fix a bug in #8607 but I suspect it existed before that PR.

Gracefully handle a pending connection during shutdown.

---

changelog.d/8676.bugfix
synapse/appservice/__init__.py
synapse/storage/databases/main/roommember.py

Fixes #8673 
Before #8437, this method was not cached. To improve performance when handling presence (and to align with a similar chunk of code over at https://github.com/matrix-org/synapse/blob/develop/synapse/handlers/presence.py#L1111-L1131), a @\cached decorator was added. However because I neglected to invalidate the cache, bugs like #8673 appeared.
This change invalidates the cache on `matches_user_in_member_list` when the store layer is invalidated, which should hopefully solve the problem.

Tie together matches_user_in_member_list and get_users_in_room caches

---

changelog.d/8688.misc
synapse/storage/databases/main/events_worker.py

Missed in #8671. The parameter `membership_user_id` is meant to be optional, but functionally I forgot to make it so.
Uses the same changelog as the original PR.

Fix optional parameter in stripped state storage method

---

changelog.d/8682.bugfix
synapse/rest/media/v1/media_repository.py
synapse/rest/media/v1/media_storage.py
synapse/storage/databases/main/media_repository.py
tests/replication/test_multi_media_repo.py
tests/server.py

Fix race for concurrent downloads of remote media. 

---

changelog.d/8690.misc
tests/handlers/test_auth.py
tests/test_utils/__init__.py
tests/unittest.py

Convert warnings like `RuntimeWarning: coroutine 'AuthTestCase.test_foo.<locals>.foo' was never awaited` to test failures.
I had wanted to do this when working on #7988 and couldn't get it to work. Turns out that Python 3.8 added the needed feature: [`sys.unraisablehook`](https://docs.python.org/3/library/sys.html#sys.unraisablehook). You can combine this with turning warnings into errors to do what we need.
I got a bit nerd sniped by [a posting on the Django developers list](https://groups.google.com/u/1/g/django-developers/c/ea21KjiGiY4/m/7HTnQaS8BwAJ).
The downside is that this *might* catch other warnings outside of the awaitable ones? We could probably do a bit of filtering of the exception to catch this?

Fail tests which fail to await on awaitables

---

changelog.d/8595.misc
synapse/push/bulk_push_rule_evaluator.py
synapse/util/caches/descriptors.py
tests/util/caches/test_descriptors.py

We don't always need the full power of a DeferredCache.
~~Based on #8593 and #8594~~
The commits here should stand alone, and it might be easier to review that way.

Implement and use an @lru_cache decorator

---

changelog.d/8635.doc
docs/sample_config.yaml
synapse/config/cas.py
synapse/config/oidc_config.py
synapse/config/saml2_config.py

This has annoyed me for a while so I figured I'd fix it:
* Better follows our guidelines for the sample config for the `saml2_config` section by avoid the double `#  #`. 
* Rejiggers the generic SSO documentation out of the SAML2 docs since it applies for SAML / OIDC / CAS.
* Adds some prose to our CAS documentation.
* Standardizes some wording across SAML / OIDC / CAS.

Improve the sample config for SSO (OIDC, SAML, and CAS)

---

changelog.d/8693.misc
synapse/storage/databases/main/appservice.py

Fixes a typo introduced in https://github.com/matrix-org/synapse/pull/8655

Fix error handling around when completing an AS transaction

---

changelog.d/8694.misc
scripts/synapse_port_db
synapse/storage/databases/main/end_to_end_keys.py
synapse/storage/databases/main/schema/delta/58/23e2e_cross_signing_keys_idx.sql

We do a `SELECT MAX(stream_id) FROM e2e_cross_signing_keys` on startup.

Improve start time by adding index to e2e_cross_signing_keys

---

changelog.d/8698.misc
docker/Dockerfile

This bumps us closer to current Python without going all the way to 3.9.
Fixes #8674

Use Python 3.8 in Docker images by default

---

changelog.d/8286.feature
synapse/push/baserules.py

This could be customised to trigger a different kind of notification in the future, but for now it's a normal non-highlight one.
* <del>[ ] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)</del>

Add base pushrule to notify for jitsi conferences

---

changelog.d/8705.misc
synapse/handlers/profile.py

This PR fixes two things:
* Corrects the copy/paste error of telling the client their displayname is wrong when they are submitting an `avatar_url`.
* Returns a `M_INVALID_PARAM` instead of `M_UNKNOWN` for non-str type parameters.
Reported by @t3chguy.

Improve error messages of non-str displayname/avatar_url

---

changelog.d/8702.misc
docs/admin_api/rooms.md

Remove the "draft" status of the Room Details Admin API

---

changelog.d/8713.misc
tests/rest/admin/test_room.py

I idly noticed that these lists were out of sync with each other, causing us to miss a table in a test case (`local_invites`). Let's consolidate this list instead to prevent this from happening in the future.

Consolidate purge table lists to prevent desyncronisation

---

changelog.d/8697.misc
synapse/app/_base.py

Fixes:
```
builtins.TypeError: _reload_logging_config() takes 1 positional argument but 2 were given
```
Introduced in #8607

Fix SIGHUP handler

---

CONTRIBUTING.md
changelog.d/8714.doc

This PR adds some documentation that:
* Describes who the audience for the `docs/` and `docs/dev/` directories are, as well as Synapse's wiki page.
* Stresses that we'd like all documentation to be down in markdown.
This came out of https://github.com/matrix-org/synapse/pull/8700#discussion_r516686648.

Add documentation about documentation to CONTRIBUTING.md

---

changelog.d/8701.doc
docs/workers.md

If SSO login is used (e.g. SAML) in a multi worker setup, it should be mentioned that currently all SAML logins must run on the same worker, see https://github.com/matrix-org/synapse/issues/7530
Also, if you are using different ports (for example 443 and 8448) in a reverse proxy for client and federation, the path `/_matrix/media` on the client and federation port must point to the listener of the `media_repository` worker, otherwise you'll get a 404 on the federation port for the path `/_matrix/media`, if a remote server is trying to get the media object on federation port, see https://github.com/matrix-org/synapse/issues/8695

Notes on SSO logins and media_repository worker

---

changelog.d/8636.misc
synapse/handlers/auth.py

Catch exceptions during Initialization of `password_providers`.
Currently synapse will just fail to start with no error message if a password provider throws an exception in `__init__`.

Catch exceptions in password_providers

---

changelog.d/8719.misc
synapse/http/matrixfederationclient.py

I noticed while working on #8421 that Synapse will raise a wrapped `RuntimeError` and 500 when a remote server responds to a request with a `Content-Type` header that Synapse was not expecting.
This is a tiny PR to change it to a 502 (Bad Gateway) instead, which I think makes more sense. I also spruced up the error message text a bit.

Better error message when a remote resource uses invalid Content-Type

---

changelog.d/8728.bugfix
synapse/server_notices/server_notices_manager.py

Check support room has only two users before sending a notice

---

changelog.d/8730.bugfix
scripts/synapse_port_db

Fix port script to handle foreign key constraints

---

changelog.d/8729.bugfix
scripts/synapse_port_db

Fix port script fails when DB has no backfilled events.

---

changelog.d/8726.bugfix
synapse/storage/database.py

[`adbapi.ConnectionPool`](https://twistedmatrix.com/documents/current/api/twisted.enterprise.adbapi.ConnectionPool.html) let's you turn on auto reconnect of DB connections. This is off by default. As far as I can tell if its not enabled dead connections never get removed from the pool.
Hopefully fixes: #8574

Enable reconnection in DB pool

---

changelog.d/8752.misc
synapse/storage/databases/main/event_federation.py

This should hopefully speed up `get_auth_chain_difference` a bit in the case of repeated state res on the same rooms.
`get_auth_chain_difference` does a breadth first walk of the auth graphs by repeatedly looking up events' auth events. Different state resolutions on the same room will end up doing a lot of the same event to auth events lookups, so by caching them we should speed things up in cases of repeated state resolutions on the same room.
Related to #8622

Cache event ID to auth event IDs lookups

---

changelog.d/8755.bugfix
scripts/synapse_port_db

If the script fails (or is CTRL-C'ed) between porting some of the events table and copying of the sequences then the port script will immediately die if run again due to the postgres DB having inconsistencies between sequences and tables.
The fix is to move the porting of sequences to before porting the tables, so that there is never a period where the Postgres DB is inconsistent. To do that we need to change how we port the sequences so that it calculates the values from the SQLite DB rather than the Postgres DB.
Fixes #8619

Fix port script so that it can be run again after failure.

---

changelog.d/8712.misc
synapse/metrics/__init__.py
synapse/rest/client/v2_alpha/account.py
synapse/rest/client/v2_alpha/register.py

The main use case is to see how many requests are being made, and how
many are second/third/etc attempts. If there are large number of retries
then that likely indicates a delivery problem.
Note: the histogram metrics here is a bit counter intuitive as it is counting the number of total requests, rather how many attempts in a single session. This means that if you have an entry at 5 then you'll also have entries at 1, 2 and 3, which may make consuming this metrics a bit harder than otherwise. However, basing it on session would be quite tricky to implement.
Does part of #8709.

Add metrics for tracking 3PID /requestToken requests.

---

README.rst
changelog.d/8746.doc

Minor corrections and advice... Should help beginners.
Signed-off-by: Chagai Friedlander chagai95@gmail.com

Updating README.rst

---

changelog.d/8754.misc
synapse/handlers/federation.py
synapse/replication/http/federation.py
synapse/storage/databases/main/room.py

There's a handy function called maybe_store_room_on_invite which allows us to create an entry in the rooms table for a room and its version for which we aren't joined to yet, but we can reference when ingesting events about.
This is currently used for invites where we receive some stripped state about the room and pass it down via /sync to the client, without us being in the room yet.
There is a similar requirement for knocking, where we will eventually do the same thing, and need an entry in the rooms table as well. Thus, reusing this function works, however its name needs to be generalised a bit.
Separated out from #6739.

Generalise _maybe_store_room_on_invite

---

changelog.d/8734.doc
docs/sample_config.yaml
synapse/config/registration.py

Clarify the usecase for an msisdn delegate

---

changelog.d/8760.misc
tests/rest/client/v1/utils.py
tests/server.py
tests/storage/test_client_ips.py

Some tests want to set some custom HTTP request headers, so provide a way to do
that before calling `requestReceived()`.

Add a `custom_headers` param to `make_request`

---

changelog.d/8759.misc
tests/replication/_base.py
tests/rest/admin/test_admin.py
tests/rest/key/v2/test_remote_key_resource.py
tests/rest/test_health.py
tests/rest/test_well_known.py
tests/unittest.py

The root resource isn't necessarily a JsonResource, so rename this method
accordingly, and update a couple of test classes to use the method rather than
directly manipulating `self.resource`.

Rename `create_test_json_resource` to `create_test_resource`

---

changelog.d/8751.misc
synapse/handlers/room_member.py

`_locally_reject_invite` generates an out-of-band membership event which can be passed to clients, but not other homeservers.
This is used when we fail to reject an invite over federation. If this happens, we instead just generate a leave event locally and send it down /sync, allowing clients to reject invites even if we can't reach the remote homeserver.
A similar flow needs to be put in place for rescinding knocks. If we're unable to contact any remote server from the room we've tried to knock on, we'd still like to generate and store the leave event locally. Hence the need to reuse, and thus generalise, this method.
Separated from #6739.

Generalise _locally_reject_invite

---

changelog.d/8758.misc
tests/rest/key/v2/test_remote_key_resource.py
tests/server.py

This is simpler and more accurately models the real flow.

Move `wait_until_result` into `FakeChannel`

---

changelog.d/8757.misc
tests/app/test_frontend_proxy.py
tests/app/test_openid_listener.py
tests/http/test_additional_resource.py
tests/replication/test_client_reader_shard.py
tests/replication/test_multi_media_repo.py
tests/replication/test_sharded_event_persister.py
tests/rest/admin/test_admin.py
tests/rest/admin/test_media.py
tests/rest/client/test_consent.py
tests/rest/client/v1/utils.py
tests/rest/client/v2_alpha/test_account.py
tests/rest/media/v1/test_media_storage.py
tests/server.py
tests/storage/test_client_ips.py
tests/test_server.py
tests/unittest.py

I want to try and kill off the odd `make_request`/`render` pairs that litter the test code: it's not reflective of how things work in practice and it's not particularly easy to work with.
This is step 1: make sure we have a Site upfront, and attach it to the fake http channel by passing it into `make_request`. Later that Site will be used when rendering the request, but for now that's still a separate step.
The commits in this PR should be reviewable independently.

Pass a Site into `make_request`

---

changelog.d/8770.misc
synapse/events/spamcheck.py
synapse/handlers/presence.py
synapse/rest/client/v1/room.py

I come across these every once in a while and they annoy me. Import `TYPE_CHECKING` from `typing` instead of using the magic `MYPY` variable. We had a mixture in our code.

Use `TYPE_CHECKING` instead of magic `MYPY` variable.

---

changelog.d/8771.doc
docs/admin_api/user_admin_api.rst

Signed-off-by: Chagai Friedlander chagai95@gmail.com

a comma too much

---

changelog.d/8765.misc
synapse/handlers/oidc_handler.py
synapse/handlers/saml_handler.py
synapse/handlers/sso.py
synapse/server.py
tests/handlers/test_oidc.py

Abstract some of the shared code from SSO providers (SAML and OpenID Connect) to avoid duplication. I'd like to also make the registration algorithms the same (pretty much `SamlHandler._map_saml_response_to_user` and `OidcHandler._map_userinfo_to_user`), but this work will be done as part of #8711, I think.
The main changes are:
* Inherit from `BaseHandler` for `OidcHandler` and `SamlHandler`.
* Create an `SsoHandler` with the following methods:
* `render_error` (this code was duplicated in #8248 from the OIDC code to the SAML code).
* `get_sso_user_by_remote_user_id`, which is a bit lame, but does remove some duplicated code.

Abstract shared SSO code

---

changelog.d/8767.bugfix
docker/Dockerfile
synapse/python_dependencies.py

Fixes https://github.com/matrix-org/synapse/issues/8766

Cap the version of prometheus_client to <v0.9.0 in the dockerfile

---

changelog.d/8731.misc
docs/sample_config.yaml
synapse/config/saml2_config.py

Despite an own and reliable NTP configuration (e.g. timesyncd) the clock of the IdP may drift slightly ahead of the system clocks of your matrix-synapse server. These cases of time difference can result in `NotBefore / NotOnOrAfter` assertion fails and a SAML login will not be accepted. You can allow for a small amount of clock drift in seconds using `accepted_time_diff` in `saml2_config` of your `homeserver.yaml` config.
see docs: https://pysaml2.readthedocs.io/en/latest/howto/config.html#accepted-time-diff

SAML: allowed clock/time difference from IdP

---

changelog.d/8777.misc
tests/rest/admin/test_user.py

This was broken due to #8617 and #8761.

Fix tests on develop

---

changelog.d/8744.bugfix
synapse/handlers/appservice.py
synapse/handlers/receipts.py
synapse/storage/databases/main/receipts.py

Fixes #8743 
This changes the AS handler code so that it will appropriately handle new appservices and not hammer the database with large queries. Appservices store their stream_id for read receipts in the database, so they can keep track of how much they need to send in each transaction. However, this value will default to 0 if not found which means the first transaction of read receipts would contain every change made since the creation of the homeserver.
This change aims to make it so that it starts from a reasonable position, which is the last 100 read receipts.

Improve appservice handler to send only the most recent ephemeral events when no stream_id is stored.

---

changelog.d/8776.bugfix
synapse/federation/federation_server.py
synapse/federation/transport/server.py
synapse/handlers/federation.py
tests/handlers/test_federation.py

Some federation APIs have a redundant `room_id` path param (see
https://github.com/matrix-org/matrix-doc/issues/2330). We should make sure we
consistently use either the path param or the body param, and the body param is
easier.

Consistently use room_id from federation request body

---

INSTALL.md
changelog.d/8793.doc

When using `add_header` nginx will literally add a header. If a
`content-type` header is already configured (for example through a
server wide default), this means we end up with 2 content-type headers,
like so:
```
content-type: text/html
content-type: application/json
access-control-allow-origin: *
```
That doesn't make sense. Instead, we want the content type of that
block to only be `application/json` which we can achieve using
`default_type` instead.
Signed-off-by: Daniele Sluijters <daenney@users.noreply.github.com>
- End …

INSTALL: Fix setting content-type on well-known

---

changelog.d/8773.misc
synapse/handlers/saml_handler.py
synapse/handlers/sso.py

This grew out of a conversation in #8765.
This PR:
* Drops some `info` logs that would fire each time we check to see if an SSO remote user maps to an existing local user, and instead attempts to only log when an existing match is found. The latter is more interesting for when a user is failing to login.
* Adds some more metadata to the failure mode log line.
* Drops one line from `info` to `debug` as it was again on the happy path. I don't think it's something that needs to be logged every time a SAML login goes through.

Only log if an existing localpart was found, extend logged info

---

changelog.d/8798.bugfix
synctl

Synctl did not check if a worker thread was already running when using
`synctl start` and would naively start a fresh copy. This would
sometimes lead to cases where many duplicate copies of a single worker
would run.
This fix adds a pid check when starting worker threads and synctl will
now refuse to start individual workers if they're already running.
Signed-off-by: Waylon Cude \<waylon.cude@finzdani.net\>

Fix synctl and duplicate worker spawning

---

changelog.d/8784.misc
mypy.ini
synapse/handlers/cas_handler.py
synapse/handlers/oidc_handler.py
synapse/handlers/register.py
synapse/handlers/saml_handler.py

* Sets the `HomeServer` type on `CasHandler.__init__` and then fixes some errors that come about from that.
* Adds type hints to the register handler.
* Fixes a bug in the CAS, OIDC, and SAML handler when registering a new user (the user-agent / IP address were given to `register_user` in the wrong format). I don't expect this to have an observable impact since you need to be using SSO + a spam checker which checks for valid registrations by user-agent / IP address. I suspect these two things together is extremely rare, if not non-existent.

Add additional type hints to SSO and registration code

---

changelog.d/8795.doc
docs/admin_api/media_admin_api.md

Improve documentation of the admin list media API

---

changelog.d/8806.misc
mypy.ini
synapse/http/federation/matrix_federation_agent.py
synapse/http/federation/well_known_resolver.py
synapse/http/matrixfederationclient.py
synapse/server.py

This adds type hints for more of the federation client HTTP paths, in particular the matrix federation client, matrix federation agent, and the well known resolver.

Add type hints to matrix federation client / agent.

---

changelog.d/8801.feature
docs/sso_mapping_providers.md
synapse/handlers/oidc_handler.py
synapse/handlers/saml_handler.py
synapse/handlers/sso.py
tests/handlers/test_oidc.py

This abstracts code between the SAML and OpenID Connect code to support re-trying to generate the matrix ID localpart. This is useful if the attribute from SSO that is being used to generate the matrix ID is unique (e.g. if you're using the localpart of an email address you might have bob@foo and bob@bar, both would make to `bob`. This allows the second one to end up with `bob1` as a matrix ID.
This is done in a a similar matter to SAML, by passing a `failures` count to the mapping provider. (Note that this is *only done* for a mapping provider which supports it, i.e. it is backwards compatible.) The code changes look a bit larger than they are -- really most of the code is copied from `SamlHandler` to `SsoHandler` and then abstracted.
This should generally be reviewable commit by commit. …

Support trying multiple localparts for OpenID Connect.

---

changelog.d/8815.misc
synapse/handlers/room_member.py
synapse/storage/databases/main/roommember.py

This is another PR that grew out of #6739.
The existing code for checking whether a user is currently invited to a room when they want to leave the room looks like the following:
https://github.com/matrix-org/synapse/blob/f737368a26bb9eea401fcc3a5bdd7e0b59e91f09/synapse/handlers/room_member.py#L518-L540
It calls `get_invite_for_local_user_in_room`, which will actually query *all* rooms the user has been invited to, before iterating over them and matching via the room ID. It will then return a tuple of a lot of information which we pull the event ID out of.
I need to do a similar check for knocking, but this code wasn't very efficient. I then tried to write a different implementation using `StateHandler.get_current_state` but this actually didn't work as we haven't *joined* the room yet - …

Speed up remote invite rejection database call

---

changelog.d/8818.doc
docs/sample_config.yaml
synapse/config/push.py

This PR updates the push config's formatting to better align with our [code style guidelines](https://github.com/matrix-org/synapse/blob/develop/docs/code_style.md#configuration-file-format).

Fix the formatting of push config section

---

UPGRADE.rst
changelog.d/8785.removal
docs/admin_api/user_admin_api.rst
synapse/_scripts/register_new_matrix_user.py
synapse/rest/admin/__init__.py
synapse/rest/admin/_base.py
synapse/rest/admin/groups.py
synapse/rest/admin/media.py
synapse/rest/admin/rooms.py
synapse/rest/admin/users.py
tests/rest/admin/test_admin.py
tests/rest/admin/test_room.py
tests/rest/admin/test_user.py
tests/rest/client/v2_alpha/test_register.py
tests/storage/test_client_ips.py
tests/unittest.py

Fixes: #8177 
Remove `historical_admin_path_patterns`
Add also necessary tests for `GET /_matrix/client/r0/admin/whois/{userId}`

Remove old `/_matrix/client/*/admin` endpoints

---

changelog.d/8822.doc
contrib/prometheus/README.md
docs/metrics-howto.md

Improve documentation how to configure prometheus for workers

---

changelog.d/8823.bugfix
synapse/_scripts/register_new_matrix_user.py

When server URL provided to register_new_matrix_user includes path
component (e.g. "http://localhost:8008/"), the command fails with
"ERROR! Received 400 Bad Request". Stripping trailing slash from the
server_url command argument makes sure combined endpoint URL remains
valid.
Signed-off-by: Dmitry Borodaenko <angdraug@debian.org>

Strip trailing / from server_url in register_new_matrix_user

---

changelog.d/8817.bugfix
synapse/app/_base.py

We can get a SIGHUP at any point, including times where we are not in a
sane state. By deferring calling the handlers until the next reactor
tick we ensure that we don't get unexpected conflicts, e.g. trying to
flush logs from the signal handler while the code was in the process of
writing a log entry.
Fixes #8769.

Defer SIGHUP handlers to reactor.

---

changelog.d/8824.doc
contrib/prometheus/consoles/synapse.html

Update example prometheus console

---

changelog.d/8809.misc
synapse/replication/http/membership.py

This PR grew out of [a discussion](https://github.com/matrix-org/synapse/pull/6739#discussion_r529838745) in #6739, and tries to do two things:
1. Add typing to method arguments
2. ~~Remove unnecessary arguments on those methods~~
~~Removing unneeded arguments is fine as `_serialize_payload` is called as:~~
https://github.com/matrix-org/synapse/blob/1781bbe319ce24e8e468f0422519dc5823d8d420/synapse/replication/http/_base.py#L169
~~and `_handle_request` called as:~~
https://github.com/matrix-org/synapse/blob/1781bbe319ce24e8e468f0422519dc5823d8d420/synapse/replication/http/_base.py#L263
~~aka with the arguments `request, **kwargs`.~~ This doesn't work :)
You'll notice that there are a lot of `# type: ignores` in here. This is due to the base methods not matching the overloads here. This is …

Add typing to membership Replication class methods

---

changelog.d/8833.removal
synapse/http/server.py

This pull request removes the special-casing to pretty print JSON in HTTP responses when the request user agent contains "curl". The special-casing probably made sense when it was added, but nowadays everyone has `jq`, which means pretty printing can be done client-side. Additionally, it causes wasted bytes on apps using libcurl and not realizing synapse has this feature (e.g. Miitrix by @Sorunome).
Signed-off-by: Tulir Asokan <tulir@maunium.net>
- Start with a capital …

Remove special case of pretty printing JSON responses for curl

---

changelog.d/8565.misc
synapse/handlers/identity.py
synapse/rest/client/v2_alpha/account.py
synapse/rest/client/v2_alpha/register.py
synapse/rest/key/v2/local_key_resource.py
synapse/server.py
tests/handlers/test_auth.py
tests/replication/_base.py
tests/rest/client/v1/test_presence.py
tests/rest/client/v2_alpha/test_register.py
tests/utils.py

> also change some usages to use .get_xyz() instead of .xyz (except for some usages that explicitly set the attribute)

Change @cache_in_self to use underscore-prefixed attributes

---

changelog.d/8845.misc
synapse/storage/databases/main/purge_events.py
synapse/storage/databases/main/schema/delta/58/24drop_event_json_index.sql

matrix.org has been fine without this index for years.

Drop (almost) unused index on event_json

---

changelog.d/8799.bugfix
synapse/handlers/room_member.py

This applies even if the feature is disabled at the server level with `allow_per_room_profiles`.
The server notice not being a real user it doesn't have an user profile.

Allow per-room profile to be used for server notice user

---

changelog.d/8847.misc
synapse/rest/client/v1/login.py

we don't need to support legacy login dictionaries here.

Simplify appservice login code

---

changelog.d/8851.misc
tests/rest/admin/test_media.py

This test was broken by #8565. It doesn't need to set set `self.clock`
here anyway - that is done by `setUp`.

Fix broken testcase

---

changelog.d/8819.misc
mypy.ini
tests/handlers/test_password_providers.py

These things seemed to be completely untested, so I added a load of tests for
them. Suggestions as to better places for these tests also welcome.

Add some tests for `password_auth_providers`

---

changelog.d/8835.bugfix
synapse/handlers/auth.py
tests/handlers/test_password_providers.py

Fix a minor bug where we would offer "m.login.password" login if a custom auth provider supported it, even if password login was disabled.
(It's worth noting that the subsequent attempt to log in would correctly fail - it was just the "available flows" that were wrong.)
~Based on #8819.~

Don't offer password login when it is disabled

---

changelog.d/8804.feature
synapse/http/server.py

Hey there!
I'm Nico and I've previously worked on integrating Matrix into [Decentraland](http://decentraland.org/). We are currently using Matrix to support both our private chat & friends features. 
**The problem**
In order for users to login they must have an Ethereum wallet, and they must sign a recent timestamp. We built a [Password Auth Provider](https://github.com/decentraland/matrix-client/blob/master/providers/decentraland_password_auth_provider.py) that validates that the timestamp is recent enough, and that the signature is also valid. Now, a problem we had, is that the timestamp was generated in the client using the local machine's clock. This caused some issues for users that had it out of sync, so we started using a global API (http://worldtimeapi.org/). Recently, that API …

Allow Date header through CORS

---

changelog.d/8850.misc
synapse/storage/databases/main/schema/delta/58/07add_method_to_thumbnail_constraint.sql.postgres
synapse/storage/databases/main/schema/delta/58/12room_stats.sql
synapse/storage/databases/main/schema/delta/58/22users_have_local_media.sql
synapse/storage/databases/main/schema/delta/58/23e2e_cross_signing_keys_idx.sql

It's important that we make sure our background updates happen in a defined
order, to avoid disasters like #6923.
Add an ordering to all of the background updates that have landed since #7190.
This should mean that:
* for anybody that runs these deltas in the future, the background updates will occur in the expected order.
* for anybody that has already run the deltas, the existing background updates will complete as normal (possibly in a random order, but hey.)
* possibly more to the point, anybody cargo-culting these updates into *new* delta files will be reminded to add an `ordering`.

Add missing `ordering` to background updates

---

changelog.d/8848.bugfix
synapse/handlers/auth.py
synapse/rest/client/v1/login.py
tests/handlers/test_password_providers.py
tests/rest/client/v2_alpha/test_auth.py

The spec requires synapse to support `identifier` dicts for `m.login.password` user-interactive auth, which it did not (instead, it required an undocumented `user` parameter.)
To fix this properly, we need to pull the code that interprets `identifier` into `AuthHandler.validate_login` so that it can be called from the UIA code.
Fixes #5665.
~Based on #8835, #8847~.
Sorry about the size of this; I couldn't really figure out a way to break it down any more.

Support "identifier" dicts in UIA

---

changelog.d/8854.misc
tests/rest/client/v1/utils.py

This PR adds a `room_version` argument to the `RestHelper`'s `create_room_as` function for tests. I plan to use this for testing knocking, which currently uses an unstable room version.
I'm afraid the typing and new argument are both in the same commit, but it's so small overall that I'm hoping it doesn't matter too much :)
Placing the new argument in the middle of the function surprisingly didn't break any existing tests.

Allow specifying room version in 'RestHelper.create_room_as' and add typing

---

changelog.d/8849.misc
synapse/handlers/auth.py
tests/handlers/test_password_providers.py

The idea here is to abstract out all the conditional code which tests which
methods a given password provider has, to provide a consistent interface.
~~Based on #8835.~~

Create a `PasswordProvider` wrapper object

---

.buildkite/scripts/test_old_deps.sh
changelog.d/8800.misc
synapse/handlers/saml_handler.py
tests/handlers/test_oidc.py
tests/handlers/test_saml.py

This adds some basic tests for SAML. This specifically aims to partially test the `_map_saml_response_to_user` method.

Add basic SAML tests for mapping users.

---

changelog.d/8837.bugfix
synapse/rest/admin/users.py

The title says it all.  Before this patch, the following error was thrown when the request was missing a `mac`:
```
2020-11-27 16:04:04,764 - synapse.http.server - 79 - ERROR - POST-5 - Failed handle request via 'UserRegisterServlet': <XForwardedForRequest at 0x7fd309bbcdc0 method='POST' uri='/_synapse/admin/v1/register' clientproto='HTTP/1.1' site=8008>
File "/usr/local/lib/python3.8/site-packages/synapse/http/server.py", line 224, in _async_render_wrapper
File "/usr/local/lib/python3.8/site-packages/synapse/http/server.py", line 400, in _async_render
File "/usr/local/lib/python3.8/site-packages/synapse/rest/admin/users.py", line 423, in on_POST
got_mac = …
```

Raise 400 error for /_synapse/admin/v1/register on missing mac

---

changelog.d/8802.doc
contrib/prometheus/synapse-v2.rules

The official dashboard uses data from these rules, but they were never
added to the synapse-v2.rules. They are mentioned in
[this issue](https://github.com/matrix-org/synapse/issues/7917#issuecomment-661330409),
but never got added to the rules.
Adding them results in all graphs in the "Event persist rate" section
to function as intended.

Add missing prometheus rules for persisted events

---

changelog.d/8827.bugfix
synapse/state/v2.py
tests/state/test_v2.py
tests/storage/test_event_federation.py

We do state res with unpersisted events when calculating the new current state of the room, so that should be the only thing impacted. I don't think this is tooooo big of a deal as:
1. the next time a state event happens in the room the current state should correct itself;
2. in the common case all the unpersisted events' auth events will be pulled in by other state, so will still return the correct result (or one which is sufficiently close to not affect the result); and
3. we mostly use the state at an event to do important operations, which isn't affected by this.

Correctly handle unpersisted events when calculating auth chain difference.

---

changelog.d/8858.bugfix
synapse/federation/transport/server.py
synapse/handlers/auth.py
synapse/storage/databases/main/registration.py
synapse/storage/databases/main/schema/delta/58/25user_external_ids_user_id_idx.sql
tests/handlers/test_oidc.py
tests/handlers/test_typing.py
tests/replication/_base.py
tests/rest/client/v1/utils.py
tests/rest/client/v2_alpha/test_auth.py
tests/server.py
tests/test_utils/__init__.py
tests/unittest.py

During user-interactive auth, do not offer password auth to users with no password, nor SSO auth to users with no SSO.
Fixes #7559.

UIA: offer only available auth flows

---

changelog.d/8861.misc
tests/api/test_filtering.py
tests/handlers/test_directory.py
tests/handlers/test_profile.py
tests/handlers/test_typing.py
tests/storage/test_redaction.py
tests/storage/test_roommember.py
tests/utils.py

As far as I can tell, all this mocking out of `federation_resource`, `http_client` and `keyring` is totally unnecessary, so we may as well get rid of it.
(Advise looking at the individual commits here: the first commit removes mocking from the test classes; the others remove the support code that was used to set up those mocks and is no longer.)

Remove some unnecessary mocking from the unit tests

---

changelog.d/8867.bugfix
synapse/rest/client/v2_alpha/register.py
tests/rest/client/v2_alpha/test_register.py

The spec says we should return `M_FORBIDDEN` when someone tries to register and
registration is disabled.

Fix errorcode for disabled registration

---

changelog.d/8873.doc
docs/sso_mapping_providers.md

the constructor is called with a `module_api`.
It's a shame the OIDC equivalent isn't consistent here.

Fix a buglet in the SAML username mapping provider doc

---

changelog.d/8875.misc
docker/Dockerfile
synapse/python_dependencies.py

This removes the version pin of the `prometheus_client` dependency, in direct response to #8831. If merged, this will close #8831 
As far as I can tell, no other changes are needed, but as I'm no synapse expert, I'm relying heavily on CI and maintainer reviews for this. My very primitive test of synapse with prometheus_client v0.9.0 on my home server didn't bring up any issues, so we'll see what happens.
Signed-off-by: Jordan Bancino

Remove version pin prometheus_client dependency

---

changelog.d/8878.bugfix
docs/sso_mapping_providers.md
synapse/handlers/oidc_handler.py
synapse/handlers/sso.py
tests/handlers/test_oidc.py
tests/handlers/test_saml.py

The SAML mapping provider is able to redirect users to an additional page. This is used by [Mozilla's mapping provider](https://github.com/matrix-org/matrix-synapse-saml-mozilla) to allow users to pick their own username. Support for this was broken in #8801, so targeting `release-v1.24.0` as this is a regression in the RC.

Fix a regression that mapping providers should be able to redirect users.

---

changelog.d/8862.bugfix
synapse/rest/media/v1/upload_resource.py

See https://sentry.matrix.org/sentry/synapse-matrixorg/issues/119430/
Turns that [`getHeader` will automatically return a string](https://twistedmatrix.com/documents/current/api/twisted.web.http.Request.html#getHeader) if we request the header key as a string.

Do not error if the content-length is not provided when uploading media.

---

changelog.d/8865.bugfix
synapse/push/__init__.py
synapse/push/httppusher.py
tests/push/test_http.py
tests/replication/test_pusher_shard.py
tests/rest/admin/test_user.py

This adds validation to the URLs provided for pushers to match what the specification says (note there's some discussion on matrix-org/matrix-doc#2721 about whether this is necessary or not, but since it is currently part of the specification it seems good to enforce it).

Add additional validation to pusher URLs.

---

changelog.d/8879.misc
synapse/state/__init__.py
synapse/state/v2.py
synapse/storage/databases/main/event_federation.py
tests/state/test_v2.py
tests/storage/test_event_federation.py

This is so that we can choose which algorithm to use based on the room ID.

Pass room_id to get_auth_chain_difference

---

changelog.d/8853.feature
docs/sample_config.yaml
docs/workers.md
synapse/app/generic_worker.py
synapse/config/workers.py
synapse/replication/http/_base.py
tests/replication/test_auth.py
tests/replication/test_client_reader_shard.py

Includes a new configuration setting `worker_replication_secret` which optionally allows for a shared-secret between the replication endpoints. Note that this is only used for HTTP endpoints and not for Redis.
If this is unset or empty than it is unused.
Fixes #8788

Add basic authentication to replication endpoints.

---

changelog.d/8883.bugfix
synapse/rest/media/v1/preview_url_resource.py
tests/test_preview.py

Fixes https://sentry.matrix.org/sentry/synapse-matrixorg/issues/127534/
Pretty much we're attempting to find something in the body to preview, but the body is empty so the etree ends up being `None` and we don't check that.

Do not raise an exception when previewing empty media.

---

changelog.d/8872.bugfix
synapse/rest/admin/users.py
tests/rest/admin/test_user.py

Fixes https://github.com/matrix-org/synapse/issues/8871

Call set_avatar_url with target_user, not user_id

---

changelog.d/8881.misc
mypy.ini
synapse/handlers/_base.py
synapse/handlers/auth.py
synapse/handlers/oidc_handler.py
synapse/handlers/saml_handler.py
synapse/handlers/sso.py

We don't need to do all the magic for mapping users when we are doing UIA, so let's factor that out.
(There's a tangentially-related commit here which removes the use of BaseHandler. I can pull it out to a separate PR if desired, but I hope it's small enough.)

Simplify the flow for SSO UIA

---

changelog.d/8898.misc
synapse/python_dependencies.py

This applies a maximum version for pysaml2 for Python < 3.6 since pysaml2 6.4.0 (released today) removed compatibility with Python 3.5.

Fix installing pysaml2 on Python 3.5.

---

.circleci/config.yml
changelog.d/8906.misc

It seems that letting CircleCI use its default docker version (17.09.0-ce, apparently) did not interact well with multiarch builds: in particular, we saw weird effects where running an amd64 build at the same time as an arm64 build caused the arm64 builds to fail with:
```
Error while loading /usr/sbin/dpkg-deb: No such file or directory
```

Pin the docker version for multiarch builds

---

changelog.d/8905.misc
tests/handlers/test_saml.py

If pysaml2 isn't installed or if xmlsec1 isn't available then skip the SAML tests.

Skip the SAML tests if xmlsec1 isn't available.

---

changelog.d/8897.feature
synapse/http/server.py

this was using `canonical_json` without setting it, so when you used it as a standalone class, you would get exceptions.

Fix buglet in DirectRenderJsonResource

---

changelog.d/8900.feature
synapse/handlers/saml_handler.py
synapse/handlers/sso.py

This is a pair of preparatory changes to `SsoHandler.get_mxid_from_sso`. The first is hopefully non-functional, and just factors out a couple of helper methods.
The second moves the `mapping_lock` logic out of SamlHandler down into SsoHandler, where it will be shared with OIDC. (It's not obvious it's doing quite the right thing, but that's not a nettle I particularly want to grasp right now.)

Refactor `SsoHandler.get_mxid_from_sso`

---

changelog.d/8918.bugfix
synapse/app/_base.py

Fix deadlock on SIGHUP

---

.circleci/config.yml
changelog.d/8909.misc

Don't publish `latest` docker image until all archs are built

---

changelog.d/8921.bugfix
synapse/handlers/room.py
synapse/handlers/room_member.py
tests/rest/client/v1/test_rooms.py

Basically, we forgot to check the `ratelimit` flag before ratelimiting.
Fixes #8866

Don't ratelimit autojoining of rooms

---

changelog.d/8916.misc
tests/logging/test_terse_json.py

* Reduce the copied & pasted code in the structured logging tests.
* Adds an additional test for using a `LoggingContext` with structured logging.
Made while doing some prep work for #8683.

Improve tests for structured logging

---

changelog.d/8920.bugfix
synapse/api/auth.py
synapse/handlers/auth.py
synapse/rest/client/v1/login.py

I also fixed up some type hints here, as we do:
https://github.com/matrix-org/synapse/blob/d765e427f18ee59716db6b4e462510b8cce4a0e1/synapse/rest/client/v1/login.py#L255-L256
which would break if given non-async functions. These callbacks come from password provider code, e.g.:
https://github.com/matrix-org/synapse/blob/d765e427f18ee59716db6b4e462510b8cce4a0e1/synapse/handlers/auth.py#L1603-L1610
Fixes #8846.

Honour AS ratelimit settings for /login requests 

---

changelog.d/8937.bugfix
synapse/handlers/auth.py
tests/handlers/test_password_providers.py

Fix startup failure with localdb_enabled: False

---

changelog.d/8943.misc
synapse/push/__init__.py
synapse/push/emailpusher.py
synapse/push/httppusher.py
synapse/push/pusherpool.py
synapse/storage/databases/main/event_push_actions.py

I believe that this will fix https://sentry.matrix.org/sentry/synapse-matrixorg/issues/194902/ and https://sentry.matrix.org/sentry/synapse-matrixorg/issues/194898/, but I'm not sure this change makes sense with the underlying code in `get_unread_push_actions_for_user_in_range_for_*`.
Regression from #8880.

Fix handling of stream tokens for push

---

changelog.d/8938.feature
synapse/handlers/saml_handler.py
tests/handlers/test_oidc.py
tests/handlers/test_saml.py
tests/test_utils/__init__.py

Another episode in my occasional "preparing for a username" picker, and a follow-up to #8911. In this case my target is the `SamlHandlerTestCase`. The changes are less invasive this time - hopefully they are clear enough.

Preparatory refactoring of the SamlHandlerTestCase

---

changelog.d/8945.bugfix
synapse/api/auth.py
synapse/api/constants.py
synapse/handlers/room.py
synapse/handlers/room_list.py
synapse/handlers/user_directory.py
synapse/notifier.py
synapse/storage/databases/main/user_directory.py
synapse/visibility.py

See https://sentry.matrix.org/sentry/synapse-matrixorg/issues/194897.
The initial commit fixes the actual bug seen, the subsequent commit adds constants for `history_visibility`.

Do not assume that contents include history_visibility.

---

changelog.d/8952.misc
scripts/generate_log_config

It used to write an empty file if you gave it a -o arg. Empirically, doing a `flush` fixes it...

Fix generate_log_config script

---

changelog.d/8951.feature
tests/handlers/test_oidc.py
tests/rest/client/v1/utils.py

A few more changes to the OidcHandlerTestCase. Broken out into separate commits.
The first commit actually fixes some of the tests to test what they were trying to test. The other two just shuffle some utility functions a bit.

More preparatory refactoring of the OidcHandler tests

---

changelog.d/8940.misc
mypy.ini
synapse/push/__init__.py
synapse/push/emailpusher.py
synapse/push/httppusher.py
synapse/push/pusher.py
synapse/push/pusherpool.py
synapse/replication/slave/storage/_slaved_id_tracker.py
synapse/replication/slave/storage/pushers.py
synapse/rest/admin/users.py
synapse/rest/client/v1/pusher.py
synapse/storage/databases/main/__init__.py
synapse/storage/databases/main/pusher.py
synapse/storage/util/id_generators.py
tests/push/test_email.py
tests/push/test_http.py
tests/rest/admin/test_user.py

This builds on #8880, #8882, and #8901 to finish adding type hints to the push module and the related database. It then converts the internal datastructure from dictionaries to attrs classes. This significantly clarifies the types throughout the modules and should be more efficient (it should use less memory per pusher instance).

Convert internal pusher dicts to attrs

---

changelog.d/8954.feature
docs/sample_config.yaml
synapse/config/federation.py
synapse/config/server.py

This should have been done in #8870, we moved the `ip_range_blacklist` setting in there from federation config to server config, but failed to move `ip_range_whitelist`.
No functional changes, just updating the sample configs.

Fix the sample config location for the ip_range_whitelist setting.

---

changelog.d/8941.feature
synapse/handlers/oidc_handler.py
synapse/handlers/saml_handler.py
synapse/handlers/sso.py
tests/handlers/test_saml.py

This is another part of my work towards fixing #8876. It moves some of the logic currently in the SAML and OIDC handlers - in particular the call to `AuthHandler.complete_sso_login` down into the `SsoHandler`.
~~Based on #8938.~~

Push login completion down into SsoHandler

---

changelog.d/8931.feature
docs/admin_api/user_admin_api.rst
synapse/storage/databases/main/__init__.py
synapse/storage/databases/main/room.py
tests/rest/admin/test_room.py
tests/rest/admin/test_user.py
tests/storage/test_main.py

Fixes #8923
I do not know if this has major impact on performance.
Also change mistake in docs.
`password_hash` is not part of result.
https://github.com/matrix-org/synapse/blob/f14428b25c37e44675edac4a80d7bd1e47112586/synapse/storage/databases/main/__init__.py#L371-L374

Make search statement in List Room and User Admin API case-insensitive

---

changelog.d/8933.bugfix
synapse/handlers/user_directory.py
tests/handlers/test_user_directory.py
tests/rest/admin/test_user.py

Fixes a bug that deactivated users appear in the directory when their profile information was updated.
To change profile information of deactivated users is neccesary for example you will remove displayname or avatar.
But they should not appear in directory. They are deactivated.

Fix a bug that deactivated users appear in the directory

---

changelog.d/8959.bugfix
synapse/storage/databases/main/user_directory.py
tests/storage/test_user_directory.py

Some user directory searches would fail because PostgreSQL would ignore common English words. For example, when looking up a user with the display name "Bela":
```
$ curl -H "Authorization: Bearer [...]" https://trelawney.brendanabolivier.com/_matrix/client/r0/user_directory/search -d '{"search_term": "b"}'
{"limited":false,"results":[{"user_id":"@sometestuser:labs.abolivier.bzh","display_name":"Bela","avatar_url":null}]}
$ curl -H "Authorization: Bearer [...]" https://trelawney.brendanabolivier.com/_matrix/client/r0/user_directory/search -d '{"search_term": "be"}' 
{"limited":false,"results":[]}
```
In this example, it identifies "be" as a common English word and don't consider it for a full text search.
The fix to this is to use the "simple" dictionary which doesn't have any stop word, …

Use the simple dictionary in fts for the user directory

---

changelog.d/8964.bugfix
tests/rest/admin/test_user.py

These tests (introduced in #8933) were failing due to changes made in #8946.

Fix `UsersListTestCase`

---

changelog.d/8963.misc
mypy.ini
tox.ini

... and disable coverage tracking for `mypy` and friends.

Clean up tox.ini

---

changelog.d/8929.misc
synapse/api/constants.py
synapse/handlers/message.py
synapse/storage/persist_events.py
synapse/visibility.py
tests/storage/test_events.py

If we see stale extremities while persisting events, and notice that they don't change the result of state resolution, we drop them.
~~I need to add some tests~~ A couple of tests have been added.

Try and drop stale extremities.

---

changelog.d/8962.bugfix
synapse/api/auth_blocking.py
synapse/handlers/auth.py
synapse/handlers/register.py
synapse/replication/http/login.py
synapse/rest/client/v2_alpha/register.py
tests/test_mau.py

Don't MAU limit AS ghost users

---

changelog.d/8965.bugfix
synapse/push/mailer.py
synapse/res/templates/notif.html

Fixes a somewhat frequent Sentry error: https://sentry.matrix.org/sentry/synapse-matrixorg/issues/123367/events/2813465/
I think it is OK to just not add the URL in this case and the templates will handle it OK.

Ensure that a URL exists in the content during push.

---

changelog.d/8970.feature
docs/sample_config.yaml
synapse/config/_base.pyi
synapse/config/auth.py
synapse/config/homeserver.py
synapse/handlers/auth.py
synapse/rest/client/v2_alpha/account.py
synapse/storage/databases/main/registration.py
synapse/storage/databases/main/schema/delta/58/26access_token_last_validated.sql
tests/rest/client/v2_alpha/test_auth.py

This should be reviewable commit-by-commit:
1. Start tracking the last time that an access token was "validated" (defined as logged in or performed UI auth).
2. Rename some config files.
3. Add a configuration option for re-using UI auth sessions.
I went with the configuration option since it seemed straightforward enough to implement. If we don't like that I can back this out to just the first commit.
Questions:
* Should we warn the user about this in some way? (I'm not sure if there's a way to, but this allows the client to do any operation for a period of time.)
* Is it worth trying to backfill the validation time for access tokens? (I don't think so, but let me know if you disagree.)
I also came across #8968 while doing this, but it isn't directly related.
Fixes #8912

Allow re-using a UI auth validation for a period of time

---

changelog.d/8942.feature
docs/sample_config.yaml
docs/sso_mapping_providers.md
synapse/app/homeserver.py
synapse/config/oidc_config.py
synapse/handlers/oidc_handler.py
synapse/handlers/sso.py
synapse/res/username_picker/index.html
synapse/res/username_picker/script.js
synapse/res/username_picker/style.css
synapse/rest/synapse/client/pick_username.py
synapse/types.py
tests/handlers/test_oidc.py
tests/unittest.py

The final part (for now) of my work to implement a username picker in synapse itself. The idea is that we allow `UsernameMappingProvider`s to return `localpart=None`, in which case, rather than redirecting the browser back to the client, we redirect to a username-picker resource, which allows the user to enter a username. We *then* complete the SSO flow (including doing the client permission checks).
The static resources for the username picker itself (in https://github.com/matrix-org/synapse/tree/rav/username_picker/synapse/res/username_picker) are essentially lifted wholesale from https://github.com/matrix-org/matrix-synapse-saml-mozilla/tree/master/matrix_synapse_saml_mozilla/res. As the comment says, we might want to think about making them customisable, but that can be a follow-up. …

Implement a username picker for synapse

---

changelog.d/8971.bugfix
synapse/state/v2.py
tests/state/test_v2.py

This had two effects 1) it'd give the wrong answer and b) would iterate *all* power levels in the auth chain of each event. The latter of which can be *very* expensive for certain types of IRC bridge rooms that have large numbers of power level changes.
Also fixes a small bug in the tests, that didn't actually have any effect.

Fix mainline ordering in state res v2

---

changelog.d/8930.feature
docs/sample_config.yaml
synapse/config/emailconfig.py
synapse/handlers/identity.py

Sends an additional parameter (`web_client_location`) with the URL to use for a web client when inviting users. This allows Synapse to specify the web app to use in the invite email and is useful if you're hosting a custom Element Web somewhere.
As far as I can tell, the [identity service spec](https://matrix.org/docs/spec/identity_service/latest#post-matrix-identity-v2-store-invite) allows for sending additional arbitrary arguments:
> In addition to the request parameters specified below, an arbitrary number of other parameters may also be specified. These may be used in the invite message generation described below.
See matrix-org/sydent#326 for a corresponding sydent PR.
Fixes #8863

Send the location of the web client to the IS when inviting via 3PIDs.

---

changelog.d/8958.misc
docs/dev/cas.md
synapse/handlers/cas_handler.py
synapse/handlers/sso.py

This is part of #8856 reordered and refactored a bit. Each commit is reviewable separately, but the overview is:
* Return a `CasResponse` object instead of a tuple (this is just a convenience).
* Render errors to the user instead of raising exceptions.
* Refactor some of the methods.

Refactor the CAS handler

---

changelog.d/8986.misc
tests/rest/client/v1/test_login.py

Fixes #8985.
It seems that the APIs we use in Synapse still work, but one of the APIs we use in our tests changed from returning bytes to str. This change was done on purpose by the maintainer and is expected.

Support PyJWT v2.0.0.

---

changelog.d/8979.misc
synapse/storage/databases/main/schema/delta/58/27local_invites.sql
tests/rest/admin/test_room.py

Per #7807, I think we can drop this table since `local_invites` has been unused since v1.17.0.

Drop the local_invites table.

---

changelog.d/8992.doc
docs/sample_config.yaml
synapse/config/groups.py

Signed-off-by: Jerin J Titus <72017981+jerinjtitus@users.noreply.github.com>
I have addressed the issue mentioned in Issue #7537

Change value of group_creation_prefix in sample_config (Issue #7537)

---

changelog.d/8975.bugfix
synapse/rest/client/v2_alpha/sendtodevice.py

Properly handle if the `messages` parameter isn't provided.
See https://sentry.matrix.org/sentry/synapse-matrixorg/issues/127685/

Validate input parameters for the sendToDevice API.

---

changelog.d/8973.misc
mypy.ini
synapse/handlers/admin.py
synapse/handlers/room_list.py
synapse/storage/databases/main/client_ips.py

Nothing out of the ordinary I don't think...

Add type hints to admin and room list handlers.

---

changelog.d/8998.misc
tests/federation/transport/test_server.py

The `RoomDirectoryFederationTests` tests were not being run unless explicitly called as an `__init__.py` file was not present in `tests/federation/transport/`. Thus the folder was not a python module, and `trial` did not look inside for any test cases to run. This was found while working on #6739.
This PR adds a `__init__.py` and also fixes the test in a couple ways:
- Switch to subclassing `unittest.FederatingHomeserverTestCase` instead, which sets up federation endpoints for us.
- Supply a `federation_auth_origin` to `make_request` in order to more act like the request is coming from another server, instead of just an unauthenicated client requesting a federation endpoint.
I found that the second point makes no difference to the test passing, but felt like the right thing to do if we're …

Fix RoomDirectoryFederationTests and make them actually run

---

changelog.d/8856.misc
synapse/handlers/cas_handler.py
synapse/handlers/sso.py
tests/handlers/test_cas.py

This builds on #8801 and #8881 but for CAS. There's no mapping provider support, but everything would be ready to add one if we wanted.
Unfortunately I couldn't see a reasonable way of applying the retry logic while also allowing for grandfathering of the old data. Any thoughts would be appreciated!
This also includes some basic tests for logging in as a CAS user.
Based on #8958.

Use the abstract registration code for CAS

---

changelog.d/8999.misc
mypy.ini
synapse/crypto/context_factory.py
synapse/crypto/event_signing.py
synapse/crypto/keyring.py
synapse/federation/transport/server.py
synapse/rest/key/v2/remote_key_resource.py
synapse/storage/databases/main/keys.py
tests/crypto/test_keyring.py

#8890 added an `inineCallbacks` which I'd like to remove...unfortunately the stack gets complicated and goes through the keyring code, which is convoluted. This is an effort to add some type hints to make it more possible to get rid of the `inlineCallbacks` call.

Add type hints to the crypto module

---

changelog.d/9015.feature
synapse/handlers/cas_handler.py
synapse/handlers/oidc_handler.py
synapse/handlers/saml_handler.py
synapse/handlers/sso.py
synapse/rest/client/v1/login.py
synapse/rest/client/v2_alpha/auth.py
tests/rest/client/v1/test_login.py

This PR is some prep work for supporting multiple SSO identity providers. First of all, I've extracted a common `Protocol` class for things which implement an identity provider. Currently this is just CAS, SAML and OIDC, but the intention is to split the `OidcHandler` up a bit in future so that we have one `OidcProvider` for each OIDC IdP, each of which implements the `SsoIdentityProvider` protocol.
Then we can combine the current `*RedirectServlet`s into a single `SsoRedirectServlet` which delegates (for now) to which ever IdP has been configured.
Suggest reviewing the PR commit by commit.

Combine the SSO Redirect Servlets

---

changelog.d/9017.feature
docs/sample_config.yaml
synapse/app/homeserver.py
synapse/config/sso.py
synapse/handlers/cas_handler.py
synapse/handlers/oidc_handler.py
synapse/handlers/saml_handler.py
synapse/handlers/sso.py
synapse/res/templates/sso_login_idp_picker.html
synapse/rest/synapse/client/pick_idp.py
synapse/static/client/login/style.css

During login, if there are multiple IdPs enabled, offer the user a choice of IdPs.
This is deliberately a bit basic for now. You can see what it looks like at https://matrix.org/_matrix/media/r0/download/sw1v.org/pFnpZJJawgBgsseJuynxximd.

Add initial support for a "pick your IdP" page

---

changelog.d/8984.feature
synapse/api/room_versions.py
synapse/events/utils.py
synapse/handlers/room.py
tests/events/test_utils.py

This implements MSC matrix-org/matrix-doc#2176. As part of this I revamped the redaction tests to more fully test the algorithm.

Implement MSC2176: Updated redaction rules

---

changelog.d/8939.misc
synapse/logging/context.py
synapse/storage/database.py
synapse/util/metrics.py

A bit more prep for #8683.
* Adds additional type hints to the logging code.
* Removes an unused parameter from `nested_logging_context` (I meant for this to go into #8935, sorry about that).
Each commit is reviewable separately.

Add type hints to the logging context code.

---

.gitignore
changelog.d/9018.misc

Ignore date-rotated logs
Ex.
- `homeserver.log.2020-12-29`
- `homeserver.log.2020-12-31`
```sh
$ git status
On branch 8996-fix-sqlite-object-name-reserved-for-internal-use
Your branch is up to date with 'origin/8996-fix-sqlite-object-name-reserved-for-internal-use'.
Untracked files:
(use "git add <file>..." to include in what will be committed)
.DS_Store
homeserver.log.2020-12-29
homeserver.log.2020-12-31
nothing added to commit but untracked files present (use "git add" to track)
``` …

Ignore date-rotated logs

---

changelog.d/9020.misc
synapse/push/__init__.py
synapse/push/emailpusher.py
synapse/push/httppusher.py
synapse/push/pusherpool.py

See https://sentry.matrix.org/sentry/synapse-matrixorg/issues/196171/?query=is%3Aunresolved
Note that we can always provide a `last_stream_token` which simplifies this code quite a bit. I'm not 100% sure that this is the code path we're hitting, but I don't see how else this could be `None`.
I suspect this is another regression from #8880.

Fix-up assertions about last stream token in push

---

changelog.d/9023.bugfix
synapse/handlers/profile.py

The federation request for a profile does not have to include the display name / avatar, e.g. from [the spec](https://matrix.org/docs/spec/server_server/latest#get-matrix-federation-v1-query-profile):
> The display name of the user. May be omitted if the user does not have a display name set.
> The avatar URL for the user's avatar. May be omitted if the user does not have an avatar set.
Fixes https://sentry.matrix.org/sentry/synapse-matrixorg/issues/194164/

Handle a display name / avatar URL not returned via a federation request.

---

changelog.d/9028.bugfix
synapse/util/caches/deferred_cache.py
tests/util/caches/test_deferred_cache.py

An empty iterable added to a cache with `iterable=True` now counts as a size of 1, not 0. Previously empty iterables could be added to the cache without bound.
Fixes #9026.

Empty iterables should count towards cache usage.

---

changelog.d/9033.misc
synapse/storage/prepare_database.py

This can happen when using a split out state database and we've upgraded the schema version without there being any changes in the state schema.

Handle updating schema version without any deltas.

---

changelog.d/9031.misc
tests/handlers/test_oidc.py
tests/rest/client/v1/test_login.py
tests/rest/client/v2_alpha/test_auth.py
tests/rest/media/v1/test_url_preview.py
tests/test_preview.py
tests/unittest.py

If we are lacking an optional dependency, skip the tests that rely on it.

Skip unit tests which require optional dependencies

---

changelog.d/9030.misc
tox.ini

... for running the tests with no optional deps.
The idea here is that you can go `tox -e py36-noextras` to run with python36 and no optional dependencies.

tox: Add a -noextras factor

---

changelog.d/9043.feature
synapse/handlers/devicemessage.py

Currently `DeviceMessageHandler` only ever exists on master, but that is about to change.
This is in preparation for moving SendToDeviceServlet off master

Ensure that remote users' device list resyncing always happens on master

---

changelog.d/9042.feature
changelog.d/9042.misc
synapse/federation/federation_server.py

This is in preparation for moving SendToDeviceServlet off master

Support routing edu's to multiple instances

---

changelog.d/9051.bugfix
synapse/storage/databases/main/client_ips.py

You can't continue using a transaction once an exception has been raised, so catching and dropping the error here is pointless and just causes more errors.
This PR just removes the try/except.
The errors look like:
`2021-01-08 14:00:25,524 - synapse.storage.databases.main.client_ips - 508 - ERROR - update_client_ips-1615 - Failed to insert client IP (('<user>', '<token>', '<ip>'), ('<user_agent>', '<device_id>', <ts>)): InFailedSqlTransaction('current transaction is aborted, commands ignored until end of transaction block\n')`

Fix error handling during insertion of client IPs

---

changelog.d/9054.bugfix
synapse/config/_util.py
tests/config/test_util.py

Fix validate_config on nested objects

---

changelog.d/9036.feature
mypy.ini
synapse/rest/client/v1/login.py
tests/rest/client/v1/test_login.py
tests/rest/client/v1/utils.py

This adds some testing to the Identity-Provider picker which was added in #9017. The tests aren't amazing, but hopefully they will suffice to let us know if something completely breaks.
There are a couple of preparatory commits to clean up some stuff in the test file, which should be reviewable on their own.

Add tests for the IdP picker

---

changelog.d/9053.bugfix
changelog.d/9053.misc
synapse/notifier.py
synapse/util/metrics.py

Fix "Starting metrics collection from sentinel context" errors

---

changelog.d/9057.doc
docs/openid.md

This PR adds the missing user_mapping_provider section in [oidc.md](https://github.com/matrix-org/synapse/blob/develop/docs/openid.md#keycloak)
Signed-off-by: Christopher Rücker <chris-ruecker@protonmail.com>

Keycloak mapping_provider example (#9037)

---

changelog.d/9058.misc
synapse/app/homeserver.py

I'm not convinced this has ever worked, and either way it's unmaintained and I'm pretty sure it doesn't work right now.

Remove unused SynapseService

---

changelog.d/9055.misc
synapse/storage/databases/main/account_data.py
synapse/storage/databases/main/schema/delta/59/04drop_account_data.sql
synapse/storage/databases/main/schema/delta/59/05cache_invalidation.sql
synapse/storage/databases/main/tags.py
synapse/storage/prepare_database.py

These tables are unused, and can be dropped now the schema version has been bumped.

Remove old tables after schema version bump

---

changelog.d/9059.bugfix
synapse/app/_base.py
synapse/app/generic_worker.py
synapse/app/homeserver.py

This is probably best reviewed with whitespace hidden. The idea here is:
* Factor out a common function so that both workers and master can use the same code for registering startup functions and handling exceptions therein.
* use `traceback.print_exception` instead of `Failure.printTraceback()`, to include the details of chained exeptions
* Write the exception to `__stderr__` **and** the logs, to maximise the chances of people finding it
* Call `os._exit` instead of `sys.exit`, to fix the exit code (fixes #4640)

Clean up exception handling in the startup code

---

changelog.d/9068.feature
synapse/app/generic_worker.py
synapse/storage/databases/main/end_to_end_keys.py

These are `/keys/claim` and `/room_keys/*` APIs.

Move more encryption endpoints off master

---

changelog.d/8948.feature
docs/admin_api/user_admin_api.rst
synapse/rest/admin/users.py
tests/rest/admin/test_user.py

Make /_synapse/admin/v1/users/<user_id>/joined_rooms also work for remote users

---

changelog.d/9069.misc
synapse/api/auth.py
synapse/handlers/auth.py
synapse/handlers/sso.py
synapse/http/__init__.py
synapse/http/site.py
tests/handlers/test_cas.py
tests/handlers/test_oidc.py
tests/handlers/test_saml.py

`SynapseRequest` is in danger of becoming a bit of a dumping-ground for "useful stuff relating to `Requests`", which isn't really its intention (its purpose is to override `render`, `finished` and `connectionLost` to set up the `LoggingContext` and write the right entries to the request log).
Putting utility functions inside `SynapseRequest` means that lots of our code ends up requiring a `SynapseRequest` when there is nothing synapse-specific about the Request at all, and any old `twisted.web.iweb.IRequest` will do. This increases code coupling and makes testing more difficult.
In short: move `get_user_agent` out to a utility function.

Remove SynapseRequest.get_user_agent

---

changelog.d/9080.misc
synapse/api/auth.py
synapse/handlers/auth.py
synapse/rest/client/v2_alpha/account.py
synapse/rest/client/v2_alpha/auth.py
synapse/rest/client/v2_alpha/devices.py
synapse/rest/client/v2_alpha/keys.py
synapse/rest/client/v2_alpha/register.py
synapse/server.py

`Homeserver.get_ip_from_request()` used to be a bit more complicated, but now it is totally redundant. Let's get rid of it.
A couple of commits here - probably easiest to review separately.

Kill off `HomeServer.get_ip_from_request()`

---

changelog.d/9079.misc
debian/changelog
debian/control
docker/Dockerfile-dhvirtualenv

Debian package builds were failing for two reasons:
1. Python versions prior to 3.7 throw exceptions when attempting to print Unicode characters under a "C" locale.
2. We depended on `dh-systemd` which no longer exists in Debian Bullseye, but is necessary in Ubuntu Xenial.
Fixing the first issue is as easy as setting `LANG="C.UTF-8"` in the build environment. (See https://bugs.python.org/issue19846)
Fixing the second issue requires attempting to install `dh-systemd`, but ignoring failures when it does not exist.
Specifically, the `dh-systemd` package was merged with the main `debhelper` package as of debhelper (>= 9.20160709)` and a transitional package was left in its place.
That transitional package was removed in Debian Bullseye after being present in both Stretch and Buster. Thus, on …

Fix failures in Debian packaging

---

changelog.d/9070.bugfix
synapse/http/matrixfederationclient.py
tests/http/test_fedclient.py

This is spamming the logs on matrix.org: https://sentry.matrix.org/sentry/synapse-matrixorg/issues/194939/
I think this works OK since the server on the other end accepts the transaction OK, but returns an empty body back. The report at #9065 says that remote construct servers are doing this. We could also consider an empty body to be an empty JSON object, but that doesn't seem correct. If you're returning a response of `applicaton/json` I'd expect the body to be valid JSON.
Fixes #9065

Handle bad JSON data being returned from the federation API.

---

changelog.d/9084.bugfix
synapse/http/client.py
synapse/http/proxyagent.py
tests/http/test_proxyagent.py

don't apply blacklist to proxy connections

---

changelog.d/9081.feature
synapse/handlers/auth.py
synapse/handlers/sso.py
synapse/handlers/ui_auth/__init__.py
synapse/rest/client/v2_alpha/account.py
synapse/rest/client/v2_alpha/auth.py
synapse/rest/client/v2_alpha/register.py

If we have integrations with multiple identity providers, when the user does a UI Auth, we need to redirect them to the right one.
There are a few steps to this. First of all we actually need to store the userid of the user we are trying to validate in the UIA session, since the `/auth/sso/fallback/web` request is unauthenticated.
Then, once we get the `/auth/sso/fallback/web` request, we can fish the user id out of the session, and use it to look up the external id mappings, and hence pick an SSO provider for them.
Commits should be independently reviewable.
Part of #8927.

UI Auth via SSO: redirect the user to an appropriate SSO.

---

CHANGES.md
UPGRADE.rst

Announce Python / PostgreSQL deprecation policies

---

changelog.d/9067.feature
synapse/handlers/oidc_handler.py
tests/handlers/test_oidc.py

Some light refactoring of OidcHandler, in preparation for bigger things:
* remove inheritance from deprecated BaseHandler
* add an object to hold the things that go into a session cookie
* factor out a separate class for manipulating said cookies

Preparatory refactors of OidcHandler

---

changelog.d/9071.bugfix
synapse/types.py
tests/test_types.py

There seems to be a client attempting to join multiple rooms at once by sending a comma separated list of room aliases to the [join room API](https://matrix.org/docs/spec/client_server/latest#post-matrix-client-r0-join-roomidoralias). `roomIdOrAlias` ends up being something like `#alias:test,#another:server`, which is invalid, but gets parsed as trying to join `#test` on a server named `test,#another:server`.
Something in the stack causes the error to only see the first bit before the `#`:
> RequestSendFailedsynapse: Failed to send request: ValueError: invalid hostname: test,
Anyway, these are obviously invalid domain names when we attempt to create a `RoomAlias` object and we should reject them. We could do a lot more validation here, but it is surprisingly hard to define what a "valid" …

Add very basic domain validation for `DomainSpecificString`.

---

changelog.d/9092.feature
docs/workers.md
synapse/app/generic_worker.py
synapse/storage/databases/main/client_ips.py

This moves the `GET /devices` to workers.
Because the client IPs are inserted in batches every 5 seconds on the main process the workers only have access to the persisted client IPs in the database. I think this is a reasonable trade-off, but I'm not 100% certain when the IPs are used (besides sometimes being displayed to the user).

Register the /devices endpoint on workers.

---

changelog.d/9106.misc
synapse/http/client.py

This could potentially catch more exceptions that we want, which is bad practice.
This is related to #9098, although it turns out this code will not get called in that case.

Reduce scope of an exception handler.

---

changelog.d/9105.feature
synapse/config/oidc_config.py
synapse/handlers/oidc_handler.py

In preparation for handling more than one OIDC provider, split everything to do with OIDC providers out into a new `OidcProviderConfig` object.
Also add some jsonschema validation for it, to give better errors if somebody misses important things.
part of #8927.

Enhancements to OIDC configuration handling

---

changelog.d/9082.feature
tests/rest/client/v1/utils.py
tests/rest/client/v2_alpha/test_auth.py
tests/server.py

This adds a relatively complete test of a UI Auth operation using an OIDC IdP (it just stubs out the calls from synapse to the IdP). Most of this stuff wasn't really tested before.
Sorry the diff isn't particularly readable. The idea is to leverage some of the exiting code in `login_via_oidc` to support UIA as well as login: as such I've split out a more generic `auth_via_oidc` which can be used for either UIA or login.

Add a test for UI-Auth-via-SSO

---

changelog.d/9098.bugfix
changelog.d/9098.misc
synapse/http/federation/matrix_federation_agent.py

Currently the reactor in `MatrixFederationAgent` is being passed as the `ip_whitelist` in `BlacklistingAgentWrapper` ([src](https://github.com/matrix-org/synapse/blob/aa4d8c1f9aa32693412642650a7c626e164af286/synapse/http/client.py#L231-L242)). This PR removes this in keeping with how `BlacklistingAgentWrapper` is instantiated in `MatrixFederationHttpClient`:
https://github.com/matrix-org/synapse/blob/aa4d8c1f9aa32693412642650a7c626e164af286/synapse/http/matrixfederationclient.py#L254-L258
Signed-off-by: tzyl <tim95@hotmail.co.uk> …

Fix using reactor as ip whitelist

---

changelog.d/9107.feature
synapse/app/homeserver.py
synapse/handlers/oidc_handler.py
tests/handlers/test_oidc.py

The idea here is that we will have an instance of OidcProvider for each configured IdP, with OidcHandler just doing the marshalling of them.
For now it's still hardcoded with a single provider.
~~Based on #9105~~

Split OidcProvider out of OidcHandler

---

changelog.d/8868.misc
changelog.d/9029.misc
scripts/synapse_port_db
synapse/storage/database.py
synapse/storage/databases/main/events.py
synapse/storage/databases/main/events_bg_updates.py
synapse/storage/databases/main/schema/delta/59/06chain_cover_index.sql
tests/storage/test_event_chain.py

~~Depends on #8868~~
Still need to actually flip the bit in the rooms table

Add background update for add chain cover index

---

changelog.d/9114.bugfix
synapse/storage/databases/main/transactions.py

It was doing a sequential scan on `destination_rooms`, which took
minutes.

Fix get destinations to catch up query.

---

changelog.d/9115.misc
synapse/storage/database.py
synapse/storage/databases/main/events.py
synapse/storage/databases/main/events_bg_updates.py
synapse/storage/util/sequence.py

Fixes:
```
2021-01-14 16:41:53,667 - synapse.storage.background_updates - 120 - ERROR - background_updates-0 - Error doing update
Capture point (most recent call last):
File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/synapse/src/synapse/app/homeserver.py", line 519, in <module>
main()
File "/home/synapse/src/synapse/app/homeserver.py", line 515, in main
run(hs)
File "/home/synapse/src/synapse/app/homeserver.py", line 506, in run
logger=logger,
File "/home/synapse/src/synapse/app/_base.py", line 134, in start_reactor
run()
File "/home/synapse/src/synapse/app/_base.py", line 118, in run
run_command()
File …
```

Fix chain cover background update to work with split out event persisters

---

changelog.d/9118.misc
synapse/util/iterutils.py
tests/util/test_itertools.py

We passed in a graph to `sorted_topologically` which didn't have an
entry for each node (as we dropped nodes with no edges).

Fix event chain bg update.

---

changelog.d/9091.feature
docs/sample_config.yaml
synapse/config/sso.py
synapse/handlers/auth.py
synapse/handlers/sso.py
synapse/res/templates/sso_auth_bad_user.html
tests/rest/client/v2_alpha/test_auth.py

If a user tries to do UI Auth via SSO, but uses the wrong account on the SSO IdP, try to give them a better error.
Previously, the UIA would claim to be successful, but then the operation in question would simply fail with "auth fail". Instead, serve up an error page which explains the failure.
I've also inlined `AuthHandler.complete_sso_ui_auth` while I'm in the area. Generally I think that `AuthHandler` has too much miscellaneous stuff in, and pulling things out of it will make things cleaner.

Give the user a better error when they present bad SSO creds

---

changelog.d/9109.feature
synapse/config/oidc_config.py
synapse/handlers/oidc_handler.py
tests/handlers/test_oidc.py

Again in preparation for handling more than one OIDC provider, add a new caveat to the macaroon used as an OIDC session cookie, which remembers which OIDC provider we are talking to. In future, when we get a callback, we'll need it to make sure we talk to the right IdP.
As part of this, I'm adding an idp_id and idp_name field to the OIDC configuration object. They aren't yet documented, and we'll just use the old values by default.
~~Based on #9107.~~

Store an IdP ID in the OIDC session

---

changelog.d/9112.misc
tests/handlers/test_oidc.py
tests/rest/client/v1/test_login.py
tests/rest/client/v1/utils.py
tests/rest/client/v2_alpha/test_auth.py

* make the OIDC bits of the test work at a higher level - via the REST api instead of poking the OIDCHandler directly.
* Move it to `test_login.py`, where I think it fits better.

Improve UsernamePickerTestCase

---

changelog.d/9093.misc
synapse/rest/media/v1/_base.py
synapse/rest/media/v1/config_resource.py
synapse/rest/media/v1/download_resource.py
synapse/rest/media/v1/filepath.py
synapse/rest/media/v1/media_repository.py
synapse/rest/media/v1/media_storage.py
synapse/rest/media/v1/preview_url_resource.py
synapse/rest/media/v1/storage_provider.py
synapse/rest/media/v1/thumbnail_resource.py
synapse/rest/media/v1/thumbnailer.py
synapse/rest/media/v1/upload_resource.py
synapse/storage/databases/main/media_repository.py

I was tracking down a couple of sentry issues in the media code and figured it'd be helpful to add types throughout. This should be reviewable commit by commit.

Add type hints to media rest resources.

---

changelog.d/9125.misc
debian/changelog
debian/control
synapse/config/registration.py
synapse/events/__init__.py
synapse/util/stringutils.py

`distutils` is pretty much deprecated these days, and replaced with `setuptools`. It's also annoying because you can't `pip install` it, and it's hard to figure out which debian package we should depend on to make sure it's there.
Since we only use it for a tiny function anyway, let's just vendor said function into our codebase.
I *think* this fixes an issue on debian where upgrading `python3-distutils` could lead to `No module named 'distutils.util'`:
1. You're following Debian testing, which has recently changed the default python version from 3.7 to 3.9. Currently, you have `python3.7` installed, as well as `python3-distutils==3.7`. You also have `matrix-synapse-py3==1.24` installed (or, equivalently, the `buster` version of 1.25).
2. You upgrade `python3-distutils` on your system, …

Remove dependency on distutils

---

changelog.d/9108.bugfix
synapse/http/client.py
tests/http/federation/test_matrix_federation_agent.py
tests/http/test_client.py

Fixes #9095 by only erroring once when a file is larger than expected.
By replacing the `Deferred` we were essentially creating a `Deferred` that nothing referenced, which is why the result was unhandled.
This also includes some basic tests, although I'm not thrilled at how thorough they are.

Avoid raising the body exceeded error multiple times.

---

changelog.d/9086.feature
docs/admin_api/media_admin_api.md
synapse/rest/admin/media.py
tests/rest/admin/test_admin.py

Fixes #9083. 
I didn't add an API to unprotect since there's also not one to unquarantine? It is easy enough to add if we want though.

Add an admin API endpoint to protect media.

---

changelog.d/9117.bugfix
synapse/storage/databases/main/pusher.py

I don't think there's any need to use canonicaljson here.
Fixes: #4475.
Discuss: should we remove the `SET bytea_output TO escape` incantation?

Ensure we store pusher data as text

---

changelog.d/9124.misc
synapse/storage/databases/main/events_bg_updates.py
tests/storage/test_event_chain.py

We do this by allowing a single iteration to process multiple rooms at a time, as there are often a lot of really tiny rooms, which can massively slow things down.
Basically, instead of processing each room individually and pulling out the events in order of `(depth, stream_ordering)`, we instead pull out events in order of `(room_id, depth, stream_ordering)`, which allows us to process multiple small rooms in one go.

Make chain cover index bg update go faster

---

changelog.d/9130.feature
synapse/handlers/devicemessage.py

...instead of used as the instance name.
This was hinted at via https://sentry.matrix.org/sentry/synapse-matrixorg/issues/196403/ and the timeline lines up of when #9043 was done.
This is due to `ReplicationEndpoint.make_client` generating a callable which expects `instance_name` as the first argument, followed by keyword arguments to serialize.

Ensure the user ID is serialized in the payload during replication.

---

changelog.d/9146.misc
tox.ini

It seems that setuptools 51.0.0 [dropped support for Python 3.5](https://setuptools.readthedocs.io/en/latest/history.html#breaking-changes). This release actually broke support via pypa/setuptools#2518.

Fix the Python 3.5 old-deps build.

---

changelog.d/9127.feature
changelog.d/9128.bugfix
synapse/handlers/auth.py
synapse/handlers/oidc_handler.py
synapse/rest/synapse/client/pick_idp.py
tests/rest/client/v1/test_login.py
tests/rest/client/v1/utils.py
tests/server.py
tests/test_utils/html_parsers.py

- don't drop duplicate query-params, or params with no value (a long-standing issue which has affected all three SSO impls forever)
- in the IDP-picker, allow utf-8 in the URL (introduced in #9017)
Based on #9127

Fix bugs in handling clientRedirectUrl

---

changelog.d/9145.bugfix
synapse/http/client.py
synapse/http/matrixfederationclient.py

Properly raise the exception when the body exceeds the max size.

---

changelog.d/9144.misc
synapse/replication/http/_base.py

Should prevent https://github.com/matrix-org/synapse/pull/9130 from happening again

Enforce all replication HTTP clients calls use kwargs

---

changelog.d/9151.doc
docs/postgres.md
docs/workers.md

We did this in some places, but not all. This should avoid shells interpreting brackets. See #9141.

Quote pip install with brackets.

---

changelog.d/9153.feature
synapse/config/oidc_config.py

#9110 reshuffled the logic for parsing OIDC config, but didn't update the error messages to match.

Fix error messages from OIDC config parsing

---

changelog.d/9157.misc
docker/conf/homeserver.yaml

There is [a template](https://github.com/matrix-org/synapse/blob/ca2db5dd0c9fc430a931b4d456fea6a5300b8b42/docker/conf/homeserver.yaml) for homeserver.yaml that is used when creating a homeserver config for docker instances of Synapse. That template still contains a `perspectives` block, which has long since been deprecated and replaced by `trusted_key_servers`.
This PR switches out the old config option for the new, without changing any functionality.
The reason I'm doing this is that I would like to override (read: remove all contents of) this section in a Complement-specific docker image, and would like to override with the new option, instead of the old. (Synapse will concatenate `perspectives` and `trusted_key_servers` if it finds both).
Documentation for this option in the sample …

Replace 'perspectives' config block with 'trusted_key_servers' in docker homeserver.yaml template

---

changelog.d/9161.bugfix
synapse/rest/client/v1/room.py

The server provided to the `/publicRooms` endpoint was bogus and throwing exceptions from the HTTP client layer. We can catch this much earlier at the REST API layer though.
Fixes https://sentry.matrix.org/sentry/synapse-matrixorg/issues/119354/

Validate the server name for public rooms endpoint.

---

changelog.d/9166.feature
synapse/server_notices/resource_limits_server_notices.py
synapse/server_notices/server_notices_manager.py

Regression from #9104.
I audited the rest of the methods on the new `AccountDataHandler` and couldn't find any other callers that directly used the datastore.
See https://sentry.matrix.org/sentry/synapse-matrixorg/issues/197118/

Use the account data handler in additional places.

---

changelog.d/9159.feature
docs/sample_config.yaml
synapse/api/urls.py
synapse/config/_base.py
synapse/config/emailconfig.py
synapse/config/oidc_config.py
synapse/config/registration.py
synapse/config/saml2_config.py
synapse/config/server.py
synapse/config/sso.py
synapse/handlers/identity.py
synapse/rest/well_known.py
tests/rest/test_well_known.py
tests/utils.py

Context: #9154 adds a new template, and in the default template I want to use an `mxc_to_http` filter, but that isn't defined unless `public_baseurl` is set, so currently trying to start synapse without it set will explode with a mysterious exception about templates.

Give `public_baseurl` a default value

---

changelog.d/9129.misc
synapse/federation/federation_client.py

This was an old branch I had sitting around, I don't know why I started it, but it seems to have some improvements:
* Type hints for `FederationClient`.
* Using `async` functions with `await` instead of returning awaitables.
* Other minor clean-up.

Various improvements to the federation client

---

changelog.d/9180.misc
setup.py

This avoids a warning when using `twine check dist/*` (which we should be running in CI to avoid things like 4c37d2acd58f9cbcdc262d25a75f8b38c50ed7f9).

Avoid a warning when using `twine check`.

---

changelog.d/9181.misc
synapse/storage/database.py
synapse/storage/databases/main/events.py

`execute_batch` does fewer round trips in postgres than `executemany`, but does not give a correct `txn.rowcount` result after.

Use execute_batch instead of executemany in places 

---

changelog.d/9189.misc
docs/sample_config.yaml
synapse/config/oidc_config.py
tests/rest/client/v1/test_login.py

... to avoid clashes with other SSO mechanisms
cf https://github.com/matrix-org/synapse/pull/9184#discussion_r561228817

Prefix idp_id with "oidc-"

---

changelog.d/9045.misc
synapse/rest/admin/users.py
tests/rest/admin/test_user.py

Add tests to `test_user.UsersListTestCase` for List Users Admin API
Also fix a small bug with `next_token`. `next_token` also appears at the end of the list.
This is a preparation to add a parameter  `order_by`.

Add tests for List Users Admin API

---

changelog.d/9188.misc
synapse/storage/database.py
synapse/storage/databases/main/devices.py
synapse/storage/databases/main/event_push_actions.py
synapse/storage/databases/main/events_bg_updates.py
synapse/storage/databases/main/media_repository.py
synapse/storage/databases/main/purge_events.py
synapse/storage/databases/main/registration.py
synapse/storage/databases/main/roommember.py
synapse/storage/databases/main/schema/delta/59/01ignored_user.py
synapse/storage/databases/main/search.py
synapse/storage/databases/state/store.py

Use execute_batch in more places

---

changelog.d/9193.bugfix
synapse/storage/databases/main/account_data.py
synapse/storage/databases/main/receipts.py
synapse/storage/util/id_generators.py
synapse/storage/util/sequence.py

Introduced in #9104 
This wasn't picked up by the tests as this is all fine the first time you run Synapse (after upgrading), but then when you restart the wrong value is pulled from `stream_positions`.

Fix receipts or account data not being sent down sync

---

changelog.d/9190.misc
synapse/storage/util/id_generators.py

We have seen a failure mode here where if there are many in flight unfinished IDs then marking an ID as finished takes a lot of CPU (as calling `deque.remove` iterates over the list)

Increase perf of handling concurrent use of StreamIDGenerators.

---

changelog.d/9176.misc
synapse/storage/databases/main/events.py
synapse/storage/util/sequence.py

If we are persisting many state events, e.g. due to a join or from the background update, we ended up doing a lot of small queries for each state event. This PR batches up those queries.
Commits should be reviewable one by one.

Speed up chain cover calculation

---

changelog.d/9191.misc
scripts-dev/lint.sh
tox.ini

The lists of source directories to lint between `tox.ini` and `lint.sh` became out of sync. This PR tightens them up and adds some comments reminding any future readers to keep the list in sync.
There's certainly something to be said about maintaining two lists. Perhaps in the future `tox.ini` should just call `lint.sh` instead. For now, these directories change so rarely that I don't think it's a big deal.

Align the directories linted in CI with the defaults in scripts-dev/lint.sh

---

changelog.d/9163.bugfix
synapse/rest/media/v1/_base.py
synapse/rest/media/v1/thumbnail_resource.py
tests/rest/media/v1/test_media_storage.py

Currently the logic for choosing a thumbnail (among the already existing thumbnails -- so not when auto-generating thumbnails is turned on) errors if no matching thumbnail is found. This leads to a 500 error returned to the client when it is reasonable to return a 404.
This should be reviewable commit-by-commit
* The first two commits are just some setup/re-organization.
* The third commit is the "real" fix.
* The fourth and fifth commits are some abstracting (if these are controversial I'm OK backing them out).
Fixes at least https://sentry.matrix.org/sentry/synapse-matrixorg/issues/127518/

Return a 404 if no valid thumbnail can be found

---

changelog.d/9204.misc
synapse/python_dependencies.py
tox.ini

As we use `execute_values` with the `fetch` parameter.
Fixes https://github.com/matrix-org/synapse/issues/9187

Bump psycopg2 version

---

changelog.d/9210.bugfix
synapse/util/iterutils.py
tests/util/test_itertools.py

This was due to the fact that `sorted_topologically` didn't handle duplicate edges correctly. This is usually not a problem as I believe we've started enforcing that we don't have duplicate entries in `auth_events`(?).
Fixes #9208

Fix chain cover update to handle events with duplicate auth events

---

changelog.d/9165.bugfix
synapse/push/presentable_names.py
tests/push/test_presentable_names.py
tests/push/test_push_rule_evaluator.py

Ensure that event content has the keys we expect to see before using them to calculate presentable names.
This doesn't ensure that they content is strings.
Fixes https://sentry.matrix.org/sentry/synapse-matrixorg/issues/133489/

Avoid trusting the content when calculating presentable names.

---

.buildkite/scripts/test_old_deps.sh
changelog.d/9217.misc
tox.ini

pip 21.0 dropped support for Python 3.5.

Use an older version of pip for py35 old deps.

---

changelog.d/9209.feature
docs/admin_api/user_admin_api.rst
stubs/txredisapi.pyi
synapse/rest/admin/__init__.py
synapse/rest/admin/users.py
synapse/storage/databases/main/registration.py
tests/rest/admin/test_user.py
tests/rest/client/test_shadow_banned.py

This expands the current shadow-banning feature to be usable via the admin API and adds documentation for it.
A shadow-banned users receives successful responses to their client-server API requests, but the events are not propagated into rooms.
Shadow-banning a user should be used as a tool of last resort and may lead to confusing or broken behaviour for the client.
Most of this PR is just the mechanics of piping through from the REST servlet layer to the datastore, although invalidating the cache is a bit wobbly. I don't think we have a helper for invalidating multiple cache entries at once, but I didn't want to blow away the whole cache.
This builds on the piece of work originally done in #8028 by adding an admin API. (That PR was split up so there's a bunch of other PRs that were …

Add an admin API for shadow-banning users.

---

changelog.d/9121.bugfix
synapse/storage/databases/main/pusher.py

I believe what is happening is that the request to delete a push is occurring more than once and only one of the requests can process successfully. Other requests end up with a `StoreError 404`. I don't see any reason why we need to enforce deleting exactly one pusher here.
Fixes #5101
Fixes https://sentry.matrix.org/sentry/synapse-matrixorg/issues/194918/?query=is%3Aunresolved

Don't error if deleting a non-existant pusher.

---

changelog.d/9218.bugfix
stubs/txredisapi.pyi
synapse/replication/tcp/handler.py
synapse/replication/tcp/redis.py

Periodically send pings to detect dead Redis connections

---

changelog.d/9222.misc
setup.py

This new version no longer has the problem of adding/removing a blank line in `.pyi` files, which black disagrees with. This would cause `isort` to slightly modify `.pyi` files, before `black` would subsequently modify back directly afterwards:
```
+ isort synapse docker tests scripts-dev scripts contrib synctl setup.py synmark stubs .buildkite
Fixing /home/user/code/synapse/synapse/config/_base.pyi
Fixing /home/user/code/synapse/stubs/txredisapi.pyi
+ python3 -m black synapse docker tests scripts-dev scripts contrib synctl setup.py synmark stubs .buildkite
reformatted /home/user/code/synapse/stubs/txredisapi.pyi
reformatted /home/user/code/synapse/synapse/config/_base.pyi
```
Relevant `isort` issue: https://github.com/pycqa/isort/issues/1284

Update isort to v5.7.0

---

changelog.d/9198.misc
stubs/txredisapi.pyi
synapse/config/_base.pyi
synapse/federation/sender/__init__.py
synapse/handlers/federation.py
synapse/handlers/message.py
synapse/replication/tcp/external_cache.py
synapse/replication/tcp/handler.py
synapse/server.py
synapse/state/__init__.py
tests/replication/_base.py

This is a fairly noddy implementation, but hopefully makes sense as a first cut

Precompute joined hosts and store in Redis

---

changelog.d/9199.removal
docs/sample_config.yaml
synapse/config/cas.py
synapse/config/oidc_config.py
synapse/handlers/cas_handler.py

Since `public_baseurl` is always defined as of #9159, it becomes easy to automatically use this for CAS if `service_url` is not defined.
By default if `service_url` is defined that will be used instead.
Fixes #7198

Do not require the CAS service URL setting (use public_baseurl instead).

---

changelog.d/9223.misc
mypy.ini
synapse/handlers/acme.py
synapse/handlers/acme_issuing_service.py
synapse/handlers/groups_local.py
synapse/handlers/search.py
synapse/handlers/set_password.py
synapse/handlers/state_deltas.py
synapse/handlers/stats.py
synapse/handlers/typing.py
synapse/handlers/user_directory.py
synapse/storage/databases/main/search.py
synapse/storage/databases/main/stats.py
synapse/storage/databases/main/user_directory.py

This adds type hints to almost all the remaining handlers that don't have them (except the `e2e_*` ones, which I have in a separate branch). This should be reviewable commit-by-commit. Most of it is straightforward, but I'll mark a couple of odd spots.

Add type hints to various handlers.

---

changelog.d/9183.feature
synapse/config/_base.pyi
synapse/config/experimental.py
synapse/config/homeserver.py
synapse/config/sso.py
synapse/handlers/sso.py
synapse/http/server.py
synapse/rest/client/v1/login.py
tests/rest/client/v1/test_login.py
tests/utils.py

Fixes #8928.
Suggest reviewing commit-by-commit.

Implement MSC2858 support

---

CHANGES.md
changelog.d/9227.misc
docs/workers.md

Add a note to changelog about redis usage

---

changelog.d/9235.bugfix
synapse/rest/admin/rooms.py

Signed-off-by: Pankaj Yadav <pankaj2000.fideri@gmail.com>
Get user with the highest power level **present** in the room. Raise an error if no such user is present. ( Solves [#9175](https://github.com/matrix-org/synapse/issues/9175) )

Check if a user is in the room before sending a PowerLevel event on their behalf

---

changelog.d/9238.misc
changelog.d/9255.misc
synapse/crypto/context_factory.py

Reading from the config object is *slow*.

Cache config options in SSL verification

---

changelog.d/9254.misc
debian/build_virtualenv
debian/changelog
docker/Dockerfile-dhvirtualenv

Adds note about updating dh-virtualenv once we drop support for Xenial.
We can't update now, because it needs debhelper 12, while Xenial only
backports 10.

Fix Debian builds on Xenial

---

changelog.d/9270.misc
synapse/app/_base.py
synapse/storage/engines/__init__.py

With this applied (and psycopg2cffi 2.9), I've been running synapse 1.26.0 on PyPy 7.3.3 for several days with no observed problems.
Related to #8888.

Fixes for PyPy compatibility

---

changelog.d/9262.feature
synapse/app/homeserver.py
synapse/handlers/sso.py
synapse/http/server.py
synapse/rest/synapse/client/pick_username.py
synapse/rest/synapse/client/sso_register.py
tests/rest/client/v1/test_login.py

There are going to be a couple of paths to get to the final step of SSO reg, and I want the URL in the browser to consistent. So, let's move the final step onto a separate path, which we redirect to.
There are a couple of preparatory commits here, which should be reviewed separately.

Split out a separate endpoint to complete SSO registration

---

changelog.d/9271.bugfix
docs/workers.md
synapse/app/generic_worker.py
synapse/app/homeserver.py
synapse/rest/synapse/client/__init__.py
synapse/storage/databases/main/registration.py
tests/rest/client/v1/test_login.py
tests/rest/client/v2_alpha/test_auth.py

Fixes #8966.
~~Based on #9262.~~ Commits should be reviewable independently.

Fix SSO on workers

---

changelog.d/9272.feature
docs/sample_config.yaml
synapse/config/sso.py
synapse/handlers/auth.py
synapse/handlers/sso.py
synapse/module_api/__init__.py
synapse/res/templates/sso.css
synapse/res/templates/sso_redirect_confirm.html
tests/handlers/test_cas.py
tests/handlers/test_oidc.py
tests/handlers/test_saml.py

Improve styling and wording of SSO redirect confirm template

---

changelog.d/9265.bugfix
synapse/handlers/auth.py

Context, Fixes: https://github.com/matrix-org/synapse/issues/9263
In the past to fix an issue with old Riots re-requesting threepid validation tokens, we raised a `LoginError` during UIA instead of `InteractiveAuthIncompleteError`. This is now breaking the way Tchap logs in - which isn't standard, but also isn't disallowed by the spec.
An easy fix is just to remove the 4 year old workaround.

Prevent email UIA failures from raising a LoginError

---

changelog.d/9283.feature
synapse/app/phone_stats_home.py
synapse/storage/databases/main/metrics.py

Add phone home stats for encrypted messages.

---

changelog.d/9277.feature
synapse/handlers/register.py
synapse/handlers/sso.py
synapse/res/templates/sso_auth_account_details.html
synapse/rest/synapse/client/pick_username.py

Make importing display name and email optional

---

changelog.d/9260.misc
synapse/push/mailer.py
tests/push/test_email.py

Split out of #9257.
This is reviewable commit-by-commit. For the first commit you likely want to disable whitespace.
It has two changes:
* The second commit fixes a case where no summary text was returned.
* The use of `messages_from_person` vs. `messages_from_person_and_others` was tweaked slightly to be based on whether there was 1 sender or multiple senders, not based on if there was 1 room or multiple rooms.

Refactor email summary generation.

---

changelog.d/9276.feature
docs/sample_config.yaml
docs/workers.md
synapse/config/sso.py
synapse/handlers/register.py
synapse/handlers/sso.py
synapse/res/templates/sso_new_user_consent.html
synapse/rest/synapse/client/__init__.py
synapse/rest/synapse/client/new_user_consent.py

kinda does what it says on the tin I think?
some awfulness to make the consent registration work on workers via the existing replication APIs. We should clean this up.
~~Based on #9271 and #9275.~~
Fixes: #8896

Collect terms consent from the user during SSO registration

---

changelog.d/9168.feature
docs/admin_api/rooms.md
synapse/handlers/message.py
synapse/rest/admin/__init__.py
synapse/rest/admin/rooms.py
tests/rest/admin/test_room.py

This could arguably replace the existing admin API for `/members`, however that is out of scope of this change.
This sort of endpoint is ideal for moderation use cases as well as other applications, such as needing to retrieve various bits of information about a room to perform a task (like syncing power levels between two places). This endpoint exposes nothing more than an admin would be able to access with a `select *` query on their database.
*This is for FOSDEM's Jitsi ops syncing, for now.*
- End with either a period (.) or …

Add an admin API to get the current room state

---

changelog.d/9300.feature
synapse/res/templates/sso_new_user_consent.html

this is basically a security thing, aiui

social login: add noopener to terms link

---

changelog.d/9302.bugfix
synapse/handlers/federation.py
synapse/handlers/room_member.py
tests/handlers/test_federation.py

This was added in https://github.com/matrix-org/synapse/pull/9258

Honour ratelimit flag for application services for invite ratelimiting

---

synapse/visibility.py

There is a small typo in synapse/visibility.py.
Should read `subsequently` rather than `subequently`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, subequently -> subsequently

---

changelog.d/9291.doc
docs/sample_config.yaml
synapse/config/registration.py

config: Add detail to auto_join_rooms comment

---

changelog.d/9296.bugfix
synapse/handlers/sso.py

We seem to have a bit of a mix of error handling approaches: some happens in the `rest` layer, and some in the handler, so this feels a bit messy. I'm not really sure how to improve it though.

Fix formatting for "bad session" error during sso registration flow

---

changelog.d/9297.feature
synapse/res/templates/sso_auth_account_details.html
synapse/res/templates/sso_auth_account_details.js

this one from @bwindels could probably do with going into 1.27.0, since it's quite broken in the RC.

social login Fix username validation javascript

---

changelog.d/9307.misc
synapse/handlers/oidc_handler.py

just some improvements to the logging here, to help understand the failure modes.

Add debug for OIDC flow

---

changelog.d/9310.doc
docs/sample_config.yaml
synapse/config/sso.py

#9200 failed to update some documentation in the sample config.

Clarify documentation about escaping URLs in templates.

---

changelog.d/9317.doc
docs/sample_config.yaml
synapse/config/oidc_config.py

This escapes the braces in the OIDC sample config so they're proper Jinja2 templates.

Fix braces in OIDC sample config.

---

changelog.d/9257.bugfix
synapse/push/mailer.py
tests/push/test_email.py

~~This got a bit out of hand for how I started, I can split this into separate PRs if we would like.~~ The overall goal is to fix the sentry error from #9256 where a member is no longer in the room state (for whatever reason) when generating the push notification.
This can happen in two spots which are handled separately:
1. `get_message_vars`, where the state is used to get the member's name and avatar URL, we can provide reasonable defaults by using the MXID and no avatar.
2. `make_summary_text`, where we can provide slightly more generic summaries.
~~While working on this I ended up refactoring the `make_summary_text` method, then fixing a bug in it. I can split this out to a separate PR if that is clearer.~~ This was split out into #9260.

Handle empty rooms when generating email notifications.

---

changelog.d/9311.feature
docs/spam_checker.md
synapse/events/spamcheck.py
synapse/rest/media/v1/media_storage.py
synapse/rest/media/v1/upload_resource.py
tests/rest/media/v1/test_media_storage.py

This is to allow us to reject known bad data, or e.g. do some anti virus scanning.
Some notes:
* This responds with generic 404 for remote content, but a 400 "Bad Content" for uploads. Is that what we want?
* If we reject remote media we'll keep downloading and then deleting the data for each request.
An example usage:
https://github.com/matrix-org/synapse/blob/d71524f686315645b7c0b4de0e816cdf2410d836/tests/rest/media/v1/test_media_storage.py#L433-L437

Add `check_media_file_for_spam` spam checker hook

---

changelog.d/9299.misc
synapse/storage/database.py
synapse/storage/prepare_database.py
synapse/storage/types.py
synapse/storage/util/sequence.py

Detail typing of Connection and Cursor to further match PEP 249

---

changelog.d/9150.feature
docs/admin_api/rooms.md
synapse/handlers/room.py
synapse/rest/admin/__init__.py
synapse/rest/admin/rooms.py
synapse/rest/client/v1/room.py
synapse/visibility.py
tests/rest/admin/test_room.py

Replaces https://github.com/matrix-org/synapse/pull/9149.
Signed-off-by: David Teller <davidt@element.io>

New API /_synapse/admin/rooms/{roomId}/context/{eventId}

---

changelog.d/9333.bugfix
synapse/rest/media/v1/preview_url_resource.py
tests/test_preview.py

I'm hoping that this will fix two more errors when previewing URLs:
* https://sentry.matrix.org/sentry/synapse-matrixorg/issues/100774/ (fixed by the first commit)
* https://sentry.matrix.org/sentry/synapse-matrixorg/issues/197702/ (fixed by the third commit)
Pretty much sometimes lxml will return `None` when parsing the document, we were not handling this well.
And sometimes we were not finding the proper charset for documents, so parsing them as the fallback (UTF-8) was breaking.

Handle additional errors when previewing URLs

---

changelog.d/9321.bugfix
synapse/groups/groups_server.py
synapse/rest/client/v2_alpha/groups.py
synapse/rest/client/v2_alpha/register.py
synapse/server.py
synapse/util/stringutils.py

* Adds some type hints to the groups servlet and stringutils code.
* Assert the maximum length some input values for spec compliance.

Type hints and validation improvements

---

changelog.d/9361.bugfix
synapse/appservice/api.py

Synapse checks that the `fields` object in 3rd party protocol lookup responses from app services only includes string values, but [the spec](https://matrix.org/docs/spec/application_service/r0.1.2#get-matrix-app-v1-thirdparty-user-protocol) says there's no such constraint.

Remove unneeded type constraints on 3rd party protocol lookup responses

---

changelog.d/9326.misc
synapse/config/cas.py
synapse/config/saml2_config.py
synapse/config/sso.py
synapse/handlers/cas_handler.py
synapse/handlers/saml_handler.py
synapse/handlers/sso.py
tests/handlers/test_cas.py
tests/handlers/test_saml.py

CAS & SAML had very similar (almost identical) code for handling required attributes from the response. Also adds tests! Should be easy to add to OIDC in the future if necessary.
I think this was the last piece of code to abstract between the various SSO implementations.

Share the code for handling required attributes between CAS & SAML.

---

changelog.d/9377.misc
tests/handlers/test_auth.py
tests/handlers/test_e2e_keys.py
tests/handlers/test_e2e_room_keys.py
tests/handlers/test_profile.py
tests/rest/client/v1/test_typing.py

This converts some tests to use `HomeserverTestCase` (and stop using `inlineCallbacks`). Tests only change so should be pretty OK if tests pass. 👍 

Convert test cases to use HomeserverTestCase

---

changelog.d/9391.bugfix
synapse/replication/tcp/redis.py

Hopefully a fix for https://github.com/matrix-org/synapse/issues/9351, albeit in a truly awful way.

Ensure that we never stop reconnecting to redis

---

changelog.d/9394.misc
synapse/handlers/federation.py

This PR removes a set that was created and [initially used](https://github.com/matrix-org/synapse/commit/1d2a0040cff8d04cdc7d7d09d8f04a5d628fa9dd#diff-0bc92da3d703202f5b9be2d3f845e375f5b1a6bc6ba61705a8af9be1121f5e42R435-R436), but is no longer today.
May help cut down a bit on the time it takes to accept invites.

Remove dead handled_events set in invite_join

---

changelog.d/9405.misc
docker/Dockerfile

This is needed to build the cryptography library, since it does not
provide wheels for ARMv7.
Fixes #9403

Add rustc to Docker image build environment

---

changelog.d/9396.misc
tests/api/test_auth.py
tests/api/test_filtering.py
tests/handlers/test_appservice.py
tests/rest/client/v1/test_profile.py

Building on #9377.
The first commit is a bit different as it actually combines two classes to use a less-mocked-out version. Should be reviewable commit by commit.
Part of #7988

Convert additional test-cases to homeserver test case

---

changelog.d/9407.doc
docs/workers.md

Support was added in https://github.com/matrix-org/synapse/pull/7855
Fixes https://github.com/matrix-org/synapse/issues/9103

Document that pusher instances are shardable

---

changelog.d/9395.bugfix
synapse/handlers/room.py
tests/rest/client/v2_alpha/test_upgrade_room.py

This should fix a couple of cases of errors during room upgrades:
* If the user performing the upgrade is not listed in the `users` dictionary of the `m.room.power_levels` event.
* If there is no `ban` key in the `m.room.power_levels` event.
It also uses the `state_default` to `50` if is not there, [in accordance with the spec](https://matrix.org/docs/spec/client_server/latest#m-room-power-levels).
Fixes #9378

Handle missing data in power levels events during room upgrade.

---

changelog.d/9362.misc
synapse/handlers/oidc_handler.py
synapse/util/caches/cached_call.py
tests/handlers/test_oidc.py
tests/util/caches/test_cached_call.py

There are a few commits here, with the broad goal of cleaning up the way we construct the metadata cache. Sorry it won't be particularly easy to see what's going on - I couldn't find a way to break it down to make it much more obvious.

Clean up caching/locking of OIDC metadata load

---

changelog.d/9384.misc
synapse/handlers/oidc_handler.py

Allow OIDC config to override discovered values

---

changelog.d/9376.feature
synapse/handlers/oidc_handler.py
synapse/rest/synapse/client/oidc/callback_resource.py
tests/handlers/test_oidc.py

Apple want to POST the OIDC auth response back to us rather than using query-params; add the necessary support to make that work.
Fixes #9319.

Support for form_post in OIDC responses

---

changelog.d/9425.bugfix
synapse/handlers/presence.py

This is a small bug that I noticed while working on #8956.
We have a for-loop which attempts to strip all presence changes for each user except for the final one, as we don't really care about older presence:
https://github.com/matrix-org/synapse/blob/9e19c6aab4b5a99039f2ddc7d3120dd3b26c274b/synapse/handlers/presence.py#L368-L371
`new_states_dict` stores this stripped copy of latest presence state for each user, before it is... put into a new variable `new_state`, which is just overridden by the subsequent for loop.
I believe this was instead meant to override `new_states`. Without doing so, it effectively meant:
1. The for loop had no effect.
2. We were still processing old presence state for users.

Fix only handling the last presence state for each user

---

changelog.d/9408.misc
synapse/handlers/presence.py

This PR removes a dead method that was found while working on presence performance. It seems like the commit that added this method (https://github.com/matrix-org/synapse/commit/4e1cebd56f9688d49a51929264c095356005f9a3) didn't call it from anywhere at the time either?

Remove dead notify_for_states presence method

---

changelog.d/9400.feature
docs/admin_api/user_admin_api.rst
synapse/storage/databases/main/__init__.py
synapse/storage/databases/main/registration.py
tests/rest/admin/test_user.py
tests/storage/test_registration.py

Add the shadow-banning status to the display user admin API

---

changelog.d/9428.bugfix
synapse/handlers/user_directory.py
synapse/storage/databases/main/user_directory.py

This adds back the code removed in https://github.com/matrix-org/synapse/pull/9223/files#r564010797.
That comment is incorrect -- the call to `get_user_directory_stream_pos` will raise an error if there's no row in `get_user_directory_stream_pos`, but row itself can have a `null` value for `stream_id`.
Fixes #9420

Add back the guard against the user directory stream position being unset

---

changelog.d/9390.doc
docs/reverse_proxy.md

Add http2 to the nginx example config

---

changelog.d/9421.bugfix
synapse/http/client.py
tests/http/test_client.py

I'm hoping this will help with #9365. There's a few tangentially related fixes in here:
* Always check the `Content-Length` header before attempting to load the body. (This was only being done in 1 of the 3 callers.)
* Do not buffer responses in treq, this feature seems to exist to allow you to read a response multiple times, but we never do that so this avoids saving bodies in two places.
* Forcefully disconnect when the maximum body size is reached. See [`abortConnection`](https://twistedmatrix.com/documents/19.2.0/api/twisted.internet.interfaces.ITCPTransport.html#abortConnection) vs. [`loseConnection`](https://twistedmatrix.com/documents/19.2.0/api/twisted.internet.interfaces.ITransport.html#loseConnection):
> Discards any buffered data, stops any registered producer, and, if …

Reduce the memory usage of previewing media files

---

CHANGES.md
changelog.d/9429.removal

Deprecate old admin API `GET /_synapse/admin/v1/users/<user_id>`

---

CHANGES.md
UPGRADE.rst
changelog.d/9434.doc
synapse/rest/synapse/client/__init__.py

Fixes #9430
* Update the upgrade documentation to match OIDC bits.
* Stop mounting the old resource (which won't work).

Remove deprecated SAML2 callback URL since it does not work.

---

changelog.d/9203.feature
docs/sample_config.yaml
synapse/config/federation.py
synapse/config/server.py
synapse/federation/transport/server.py
synapse/handlers/message.py
synapse/handlers/profile.py
synapse/replication/http/federation.py
tests/handlers/test_profile.py

This adds two off-by-default settings that each restrict access to profile data (displaynames and avatars):
- **include_profile_data_on_invite**: If false, prevents invite events from including the invitee's profile data. Otherwise, all it takes for someone to access any user's profile data is to know/guess their mxid and invite them to a room.
- **allow_profile_lookup_over_federation**: If false, causes any requests for profile data over federation to respond with `M_FORBIDDEN`.
I've had these tweaks on my own server for quite some time now, and felt it would be helpful to share them. …

Add some configuration settings to make profile data more private

---

changelog.d/9383.feature
docs/sample_config.yaml
synapse/config/user_directory.py
synapse/storage/databases/main/user_directory.py
tests/handlers/test_user_directory.py

This PR adds a homeserver config option, `user_directory.prefer_local_users`, that when enabled will show local users higher in user directory search results than remote users. This option is off by default.
Note that turning this on doesn't necessarily mean that remote users will always be put below local users, but they should be assuming all other ranking factors (search query match, profile information present etc) are identical.
This is useful for, say, University networks that are openly federating, but want to prioritise local students and staff in the user directory over other random users.

Add a config option to prioritise local users in user directory search results

---

changelog.d/9402.bugfix
synapse/federation/sender/__init__.py
synapse/handlers/presence.py
tests/handlers/test_presence.py

Addresses #8956. Does not address "we should also only send presence updates when this is the first time a remote server shares a room with the local user". I'd like to tackle that in a separate PR as it will likely involve tracking which presence updates we've sent out in some form.
This PR attempts to eliminate unnecessary presence sending work when your local server joins a room, or when a remote server joins a room your server is participating in by processing state deltas in chunks rather than individually.
---
When your server joins a room for the first time, it requests the historical state as well. This chunk of new state is passed to the presence handler which, after filtering that state down to only membership joins, will send presence updates to homeservers for each join …

Be smarter about which hosts to send presence to when processing room joins

---

changelog.d/9440.bugfix
synapse/res/templates/sso_auth_account_details.html

`idp_icon` is an optional field so we shouldn't assume it exists.
Fixes #9439

Support not providing an IdP icon when choosing a username.

---

changelog.d/9432.misc
synapse/config/_base.py

I needed to grok `parse_duration` to review #9426, figured I should add documentation / type hints while I was there.

Add documentation and type hints to parse_duration.

---

changelog.d/9438.feature
synapse/rest/media/v1/media_repository.py
synapse/rest/media/v1/media_storage.py
synapse/rest/media/v1/thumbnail_resource.py
synapse/storage/databases/main/media_repository.py
tests/rest/media/v1/test_media_storage.py

This doesn't re-fetch remote media if we have also deleted that, but I think that's something we can add in the future if we want

Regenerate exact thumbnails if missing

---

changelog.d/9385.feature
docs/sample_config.yaml
synapse/config/user_directory.py

The user directory sample config section was a little messy, and didn't adhere to our [recommended config format guidelines](https://github.com/matrix-org/synapse/blob/develop/docs/code_style.md#configuration-file-format).
This PR cleans that up a bit.
~~Based on #9383, which this code was separated out from.~~ This PR has now been rebased.
Uses the same changelog text as #9383.

Clean up the user directory sample config section

---

changelog.d/9416.bugfix
synapse/storage/databases/main/user_directory.py
tests/rest/client/v2_alpha/test_shared_rooms.py

This PR remove the cache for the `get_shared_rooms_for_users` storage method (the db method driving the experimental "what rooms do I share with this user?" feature: [MSC2666](https://github.com/matrix-org/matrix-doc/pull/2666)). Currently subsequent requests to the endpoint will return the same result, even if your shared rooms with that user have changed.
The cache was added in https://github.com/matrix-org/synapse/pull/7785, but we forgot to ensure it was invalidated appropriately.
Upon attempting to invalidate it, I found that the cache had to be entirely invalidated whenever a user (remote or local) joined or left a room. This didn't make for a very useful cache, especially for a function that may or may not be called very often. Thus, I've opted to remove it instead of invalidating …

Remove cache for get_shared_rooms_for_users

---

changelog.d/9463.doc
docs/systemd-with-workers/system/matrix-synapse-worker@.service
docs/systemd-with-workers/system/matrix-synapse.service

It should be possible to reload `synapse.target` to have the reload propagate to all the synapse units.

example systemd config: propagate reloads to units

---

changelog.d/9462.misc
docker/README.md
docker/conf/homeserver.yaml
synapse/config/repository.py
tests/utils.py

`uploads_path` was a thing that was never used; most of it was removed in #6628 but a few vestiges remained.

Remove vestiges of uploads_path config

---

changelog.d/9465.bugfix
docs/tcp_replication.md
synapse/app/generic_worker.py
synapse/push/httppusher.py
synapse/push/pusherpool.py
synapse/replication/http/__init__.py
synapse/replication/http/push.py
synapse/replication/tcp/commands.py
synapse/replication/tcp/handler.py
synapse/server.py

`remove_pushers_by_access_token` has the following check:
https://github.com/matrix-org/synapse/blob/0a00b7ff14890987f09112a2ae696c61001e6cf1/synapse/push/pusherpool.py#L178-L179
The intent here was that we should ignore attempts to delete pushers on workers not responsible for that user's push. This is incorrect, as deleting pushers must happen on master. However, unless the `pusher_instances` config is set and non-empty `ShardedWorkerHandlingConfig.should_handle(..)`  will always return true (for silly backwards compat reasons, which is fixed in a separate PR), and so the method ends up doing the right thing in that case.
Since our integration tests for workers doesn't use `pusher_instances` all the tests passed, even though they broke if that option was set. 
We fix this by a) removing …

Fix deleting pushers when using sharded pushers.

---

changelog.d/9449.bugfix
scripts/synapse_port_db
synapse/storage/databases/__init__.py
synapse/storage/databases/main/events.py

Fixes #9344 and fixes #9382.
This adds additional sequences to the port db script:
* `account_data_sequence`
* `receipts_sequence`
* `event_auth_chain_id`
It also calls `check_consistency` for `event_auth_chain_id`.
#9344 also talks about `account_data_sequence` being unported, but that is in the script. There was a slight bug in that function though where we didn't await the call to restart the sequence. Maybe that was the issue.
I'm not 100% confident this is doing the correct thing, but I *think* it is.
Should we be checking the consistency of the other sequences, by the way?

Include newly added sequences in the port DB script

---

changelog.d/9464.misc
synapse/python_dependencies.py

Add a comment about systemd-python.

---

changelog.d/9474.misc
synapse/rest/synapse/client/__init__.py

Partially reverts #9434, fixes #9452.
This can be removed in a future version.

Add back the deprecated SAML endpoint.

---

changelog.d/9358.misc
synapse/handlers/sync.py
synapse/util/caches/response_cache.py

This fixes #8518 by adding a conditional check on `SyncResult` in a function when `prev_stream_token == current_stream_token`, as a sanity check. In `CachedResponse.set.<remove>()`, the result is immediately popped from the cache if the conditional function returns "false".
This prevents the caching of a timed-out `SyncResult` (that has `next_key` as the stream key that produced that `SyncResult`). The cache is prevented from returning a `SyncResult` that makes the client request the same stream key over and over again, effectively making it stuck in a loop of requesting and getting a response immediately for as long as the cache keeps those values.
- Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." …

Fix #8518 (sync requests being cached wrongly on timeout)

---

changelog.d/9479.bugfix
synapse/storage/databases/main/schema/delta/59/08delete_stale_pushers.sql

The select for this took ~8s on matrix.org. I think we could turn this into a background job, but I'm not sure it's worth it.
This a clean up after the fix in https://github.com/matrix-org/synapse/pull/9465

Add SQL delta for deleting stale pushers

---

changelog.d/9472.feature
docs/reverse_proxy.md
synapse/http/site.py

rewrite XForwardedForRequest to set `isSecure()` based on `X-Forwarded-Proto`. Also implement `getClientAddress()` while we're here.

Add support for X-Forwarded-Proto

---

changelog.d/9436.bugfix
synapse/http/__init__.py
synapse/rest/client/v1/login.py
tests/rest/client/v1/test_login.py
tests/rest/client/v1/utils.py
tests/rest/client/v2_alpha/test_auth.py
tests/server.py

... otherwise, we don't get the cookie back.

SSO: redirect to public URL before setting cookies

---

.gitignore
changelog.d/9502.misc
debian/build_virtualenv
debian/changelog
debian/synctl.1
debian/synctl.ronn
synapse/app/__init__.py
synctl

In #75, bytecode was disabled (from a bit of FUD back in `python<2.4` days, according to dev chat), I think it's safe enough to enable it again.
Added in `__pycache__/` and `.pyc`/`.pyd` to `.gitignore`, to extra-insure compiled files don't get committed.

Allow bytecode again

---

changelog.d/9515.misc
synapse/handlers/auth.py
synapse/handlers/sso.py
synapse/replication/http/membership.py
synapse/rest/admin/media.py
synapse/rest/client/v2_alpha/groups.py
synapse/rest/media/v1/_base.py
synapse/rest/media/v1/config_resource.py
synapse/rest/media/v1/download_resource.py
synapse/rest/media/v1/media_repository.py
synapse/rest/media/v1/preview_url_resource.py
synapse/rest/media/v1/thumbnail_resource.py
synapse/rest/media/v1/upload_resource.py
synapse/rest/synapse/client/new_user_consent.py
synapse/rest/synapse/client/password_reset.py
synapse/rest/synapse/client/pick_username.py
synapse/rest/synapse/client/sso_register.py
tox.ini

Twisted comes with `twisted.web.http.Request` and `twisted.web.server.Request`, we were using the former in some situations when we should always be using the latter.
This is work towards #9513, it also pins Twisted for the mypy check in the meantime, so that we can continue working in parallel to this.
This reduces the mypy errors from 196 to 129.

Use the proper Request in type hints.

---

changelog.d/9497.bugfix
synapse/http/client.py
tests/http/test_client.py

I think this fixes #9488 (leaking of file descriptors in the media repo). It seems that in the case where we rejected the response due to the headers returning a content size that the response is never rejected and sits around until it is garbage collected. There doesn't seem to be a way to abort a connection directly from the response so this adds another protocol which immediately errors with a `BodyExceededMaxSize` exception.
I'm not positive this will fix the issue, but I'm hopeful!
Note that the first two commits here are just munging some test code so we can add a new test.

(Hopefully) stop leaking file descriptors in media repo

---

changelog.d/9519.misc
synapse/rest/admin/devices.py
synapse/rest/admin/event_reports.py

Add type hints to device and event report admin API

---

changelog.d/9516.bugfix
scripts/synapse_port_db
synapse/storage/databases/main/pusher.py
synapse/storage/databases/main/schema/delta/59/08delete_pushers_for_deactivated_accounts.sql

Fix SQL delta file taking a long time to run

---

changelog.d/9530.bugfix
synapse/handlers/presence.py

Prevent presence background jobs from running when presence is disabled

---

changelog.d/9512.feature
docs/reverse_proxy.md

Turns out nginx overwrites the Host header by default.

Update nginx reverse-proxy docs

---

changelog.d/9529.misc
setup.py
synapse/replication/tcp/streams/_base.py
synapse/storage/roommember.py

Tangentially related to #9513 as I want to use a newer mypy-zope which gets some bits about superclasses more accurate.

Bump the mypy versions.

---

changelog.d/9521.misc
synapse/rest/admin/users.py
synapse/storage/databases/main/__init__.py
synapse/storage/databases/main/media_repository.py

Add type hints to user admin API

---

changelog.d/9537.bugfix
synapse/storage/databases/main/events_bg_updates.py

Turns out matrix.org has an event that has duplicate auth events (which really isn't supposed to happen, but here we are). This caused the background update to fail due to `UniqueViolation`.
This was added in v1.28.0, but we only just noticed on matrix.org due to #9503.
Sentry link: https://sentry.matrix.org/sentry/synapse-matrixorg/issues/200948/

Fix 'rejected_events_metadata' background update

---

changelog.d/9518.misc
synapse/http/federation/matrix_federation_agent.py
synapse/http/matrixfederationclient.py
synapse/http/server.py
synapse/http/site.py
synapse/logging/_remote.py
synapse/metrics/__init__.py
synapse/module_api/__init__.py
synapse/push/httppusher.py
synapse/replication/tcp/client.py
synapse/server.py
tests/rest/client/v1/test_login.py

Part of #9513, this is a grab bag of different improvements, but should be reviewable commit-by-commit. I think most of them are self-explanatory, but a couple are funkier. I'll try to mark the ones I think are questionable.

Fix additional type hints from Twisted upgrade

---

changelog.d/9511.feature
synapse/handlers/register.py
synapse/handlers/sso.py
synapse/rest/client/v1/login.py

Add prom metrics for number of users successfully registering and logging in, by SSO provider. 
Fixes #9431.
Based on #9510.

Prometheus metrics for logins and registrations

---

UPGRADE.rst
changelog.d/9550.doc

Add additional SAML2 upgrade notes

---

changelog.d/9528.misc
synapse/handlers/acme.py
synapse/http/client.py
synapse/http/federation/matrix_federation_agent.py
synapse/http/matrixfederationclient.py
synapse/replication/tcp/redis.py
synapse/server.py
synapse/types.py

This allows passing around the proper interface instead of pretending that `ReactorBase` has the proper methods.
Part of #9513, fixes ~10 issues.

Create ISynapseReactor interface which incorporates the necessary reactors

---

changelog.d/9541.bugfix
changelog.d/9541.misc
tests/storage/test_purge.py

This adds a basic storage layer test for purging rooms, doesn't offer too much more than the ones using the admin API, but I find it quite a bit clearer.
Related to #9498 / #9481.

Add a basic test for purging rooms

---

changelog.d/9520.misc
synapse/rest/admin/purge_room_servlet.py
synapse/rest/admin/server_notice_servlet.py

Add type hints to purge room and server notice admin API

---

changelog.d/9562.misc
scripts-dev/config-lint.sh

I noticed that I'd occasionally have `scripts-dev/lint.sh` fail when messing about with config options in my PR. The script calls `scripts-dev/config-lint.sh`, which attempts some validation on the sample config.
It does this by using `sed` to edit the sample_config, and then seeing if the file changed using `git diff`.
The problem is: if you changed the sample_config as part of your commit, this script will error regardless.
This PR attempts to change the check so that existing, unstaged changes to the sample_config will not cause the script to report an invalid file.

Prevent the config-lint script erroring out on any sample_config changes

---

changelog.d/9567.bugfix
synapse/http/matrixfederationclient.py

Retry 5xx errors in federation client

---

changelog.d/9571.doc
docs/admin_api/media_admin_api.md

Earlier [I was convinced](https://github.com/matrix-org/synapse/issues/9565) that we didn't have an Admin API for listing media uploaded by a user. Foolishly I was looking under the Media Admin API documentation, instead of the User Admin API documentation.
I thought it'd be helpful to link to the latter so others don't hit the same dead end :)

Link to the List user's media admin API from media Admin API docs

---

changelog.d/9583.bugfix
synapse/storage/databases/main/events_bg_updates.py

One of my refactors slightly broke #9542. We need to pass a list of tuples, not just a list to `executemany`.

Fix a bug in the background task for purging chain cover

---

changelog.d/9580.doc
docs/spam_checker.md

A parse_config method is mandatory on spam checked modules.
This relates to #8944 as well.

Fix spam checker modules documentation example

---

changelog.d/9586.misc
synapse/handlers/auth.py
synapse/rest/media/v1/media_repository.py
synapse/storage/databases/main/registration.py
synapse/types.py

... because namedtuples suck
Also fix up a couple of other annotations to keep mypy happy.

Convert Requester to attrs

---

changelog.d/9587.bugfix
synapse/rest/admin/users.py

Re-Activating account when local passwords are disabled

---

changelog.d/9563.misc
synapse/http/client.py
tests/http/test_client.py

Related to #9513, this:
* Adds tests for the blacklisting agent and reactor (we didn't seem to have any?)
* Fixes some type hint errors related to those classes.
I broke it into a few commits that should be standalone, hopefully they make sense!

Add tests for blacklisting reactor/agent.

---

changelog.d/9590.misc
stubs/txredisapi.pyi
synapse/replication/tcp/redis.py

This makes it write logs like:
```
2021-03-11 12:29:02,800 - synapse.replication.tcp.redis - 264 - INFO - None - Connecting to redis server localhost:6379
2021-03-11 12:29:02,802 - synapse.replication.tcp.redis - 270 - INFO - None - Connection to redis server localhost:6379 failed: Connection was refused by other side: 111: Connection refused.
```
It's an attempt to get more insight into what is happening with redis connections, as well as mitigating the issue where requests mysteriously block when the redis server is down.

Add logging for redis connection setup

---

changelog.d/9596.misc
synapse/federation/federation_server.py
synapse/handlers/federation.py

Put the room id in the logcontext, to make it easier to understand what's going on.

Improve logging when processing incoming transactions

---

changelog.d/9597.bugfix
synapse/federation/federation_server.py

If more transactions arrive from an origin while we're still processing the first one, reject them.
Hopefully fixes #9489

Reject concurrent transactions

---

changelog.d/9601.feature
synapse/handlers/federation.py
synapse/storage/databases/main/events_worker.py

Background: When we receive incoming federation traffic, and notice that we are missing prev_events from the incoming traffic, first we do a `/get_missing_events` request, and then if we still have missing prev_events, we set up new backwards-extremities. To do that, we need to make a `/state_ids` request to ask the remote server for the state at those prev_events, and then we may need to then ask the remote server for any events in that state which we don't already have, as well as the auth events for those missing state events, so that we can auth them.
This PR attempts to optimise the processing of that state request. The `state_ids` API returns a list of the state events, as well as a list of all the auth events for *all* of those state events. The optimisation comes from the …

Optimise missing prev_event handling

---

changelog.d/9561.misc
synapse/federation/sender/per_destination_queue.py
synapse/federation/sender/transaction_manager.py
synapse/storage/databases/main/transactions.py
tests/federation/test_federation_catch_up.py

Federation catch up mode is very inefficient if the number of events
that the remote server has missed is small, since handling gaps can be
very expensive, c.f. #9492.
Instead of going into catch up mode whenever we see an error, we instead
do so only if we've backed off from trying the remote for more than an
hour (the assumption being that in such a case it is more than a
transient failure).

Don't go into federation catch up mode so easily

---

changelog.d/9608.misc
stubs/txredisapi.pyi
synapse/http/client.py
synapse/replication/tcp/handler.py
synapse/replication/tcp/protocol.py
synapse/replication/tcp/redis.py
tests/replication/_base.py
tests/server.py

Fixes the remaining type issues, re #9513.
Note that this does not re-upgrade Twisted in the mypy check yet, I'll handle that separately.

Fix remaining mypy issues due to Twisted upgrade.

---

changelog.d/9618.misc
tox.ini

This removes the pin on Twisted in the tox mypy check (originally added in #9515.

Revert requiring a specific version of Twisted for mypy checks.

---

changelog.d/9617.feature
docs/openid.md
docs/sample_config.yaml
synapse/config/oidc_config.py
synapse/handlers/cas_handler.py
synapse/handlers/oidc_handler.py
synapse/handlers/saml_handler.py
synapse/handlers/sso.py
synapse/rest/client/v1/login.py
tests/rest/client/v1/test_login.py

Now that MSC2858 has completed FCP, we can add support for the stable API documented therein.
There are two parts to this: (1) listing the available identity providers under `identity_providers` rather than `org.matrix.msc2858.identity_providers` (with different brand identifiers; (2) supporting requests to `/_matrix/client/unstable/org.matrix.msc2858/login/sso/redirect/{idp_id}` as well as `/_matrix/client/r0/login/sso/redirect/{idp_id}`.
Since we now have to support two potential brand identifiers for each IdP, the "unstable" ones are shifted to a separate configuration key. So note that we'll have to reconfigure `matrix.org` when we deploy this.

Add support for stable MSC2858 API

---

changelog.d/9620.bugfix
synapse/handlers/oidc_handler.py

Fixes https://sentry.matrix.org/sentry/synapse-matrixorg/issues/199800/
It seems that the cookie retrieved is empty, causing the pymacaroon library to raise a different exception than we expect.

Handle an empty cookie as an invalid macaroon.

---

changelog.d/9626.feature
docs/spam_checker.md
synapse/events/spamcheck.py
synapse/handlers/register.py
tests/handlers/test_register.py

Fixes https://github.com/matrix-org/synapse/issues/9572
When a SSO user logs in for the first time, we create a local Matrix user for them. This goes through the register_user flow, which ends up triggering the spam checker. Spam checker modules don't currently have any way to differentiate between a user trying to sign up initially, versus an SSO user (whom has presumably already been approved elsewhere) trying to log in for the first time.
This PR passes `auth_provider_id` as an argument to the `check_registration_for_spam` function. This argument will contain an ID of an SSO provider (`"saml"`, `"cas"`, etc.) if one was used, else `None`.

Pass SSO IdP information to spam checker's registration function

---

changelog.d/9588.bugfix
synapse/handlers/auth.py
synapse/rest/client/v2_alpha/capabilities.py
tests/rest/client/v2_alpha/test_capabilities.py

Return `m.change_password` `enabled:false` if local database not used for authentication
Fixes: #9456
I had to remove a part of the test. Because I do not know how to create an `access_token` for an user who uses SSO.
What is the best config switch for this situation? `password_config.enabled` or `password_config.localdb_enabled`?
https://github.com/matrix-org/synapse/blob/1baab2035265cf2543fe3c0ef5412c1ac0740c7e/synapse/handlers/set_password.py#L37-L45
`set_password` uses `password_config.localdb_enabled`
https://github.com/matrix-org/synapse/blob/a7a379006651ea219c2618c0a47e8f4053a9e769/docs/sample_config.yaml#L2211-L2220
The documentation says that `localdb_enabled` is ignored if `password_config.enabled` is `false`. But I can not find the code where `localdb_enabled` becomes unset or …

Return m.change_password.enabled=false if local database is disabled

---

changelog.d/9499.misc
setup.cfg
setup.py
synapse/app/__init__.py
synapse/config/key.py
synapse/config/metrics.py
synapse/config/oidc_config.py
synapse/config/repository.py
synapse/config/saml2_config.py
synapse/config/tracer.py
synapse/crypto/context_factory.py
tests/unittest.py

Adds `flake8-bugbear` to the test suite, and immediately ignores it in the `setup.cfg`, to be fixed later (see #9366)
Part of #9366

Add bugbear, add B00 to ignored checks, and fix 2 violation codes

---

changelog.d/9631.misc
synapse/handlers/register.py
synapse/handlers/room_member.py
synapse/handlers/room_member_worker.py
synapse/server.py

This is spun out of #9374 as that got messy. This adds a return type to `get_room_member_handler`, which enables additional type checking.
As part of this, it complained that `forget` didn't exist on the worker version. I implemented a stub which just raises an error, which seems "wrong", but at least makes it explicit. Instead we could make a call over replication to do this. Is that the right thing to do? (Note that the endpoints that use this don't have any "GET" method so I'm not sure there's benefit to running this on workers which just call back to main. Beyond ease of deployment, that is.)

Add type hints to the room member handler.

---

changelog.d/9411.misc
synapse/events/__init__.py
synapse/events/utils.py
synapse/replication/http/federation.py
synapse/replication/http/send_event.py
synapse/storage/databases/main/events.py
synapse/storage/databases/main/events_worker.py

I realised that, for every event, we were storing a second copy of the `outlier` flag in `internal_metadata`. That's 15 bytes per event. FIFTEEN!
Well anyway it feels a bit redundant, and I'd quite like to remove it. I think we can do this in two phases:
* First (this one): stop relying on the data in the `internal_metadata` column. This should be backwards-compatible.
* Later: stop storing `outlier` in the `internal_metadata` column. That will break rollback to older synapse versions.

Prep work for removing `outlier` from `internal_metadata`

---

changelog.d/9634.misc
synapse/handlers/device.py

There seems to be a feedback loop where, if a remote user has a master signing key but no self-signing key, synapse will try to re-fetch that user's keys, which it will blindly treat as a device update, which will notify local users about the device change, which will cause them to fetch the remote user's keys, which will cause synapse to notice that they have a master key but no self-signing key, and will try to re-fetch again.  This change will only update the local cached keys after refetching the remote user's keys if anything actually changed, which breaks the loop.

only save remote cross-signing keys if they're different from the current ones

---

changelog.d/9638.misc
synapse/replication/tcp/streams/_base.py
synapse/rest/client/v1/room.py
synapse/server.py

More split off from #9374, this handles just the typing handler. I used a different approach from #9631 that is a bit more explicit. 🤷

Fix up types for the typing handler.

---

changelog.d/9585.bugfix
synapse/events/utils.py
tests/rest/client/test_third_party_rules.py
tests/rest/client/v2_alpha/test_relations.py
tests/unittest.py

This bug was discovered by DINUM. We were modifying `serialized_event["content"]`, which - if you've got `USE_FROZEN_DICTS` turned on or are [using a third party rules module](https://github.com/matrix-org/synapse/blob/17cd48fe5171d50da4cb59db647b993168e7dfab/synapse/events/third_party_rules.py#L73-L76) - will raise a 500 if you try to a edit a reply to a message.
`serialized_event["content"]` could be set to the edit event's content, instead of a copy of it, which is bad as we attempt to modify it. Instead, we also end up modifying the original event's content. DINUM uses a third party rules module, which meant the event's content got frozen and thus an exception was raised.
To be clear, the problem is not that the event's content was frozen. In fact doing so helped us uncover the fact …

Ensure we use a copy of the event content dict before modifying it in serialize_event

---

changelog.d/9640.misc
synapse/federation/federation_server.py
synapse/federation/sender/per_destination_queue.py
tests/federation/test_federation_catch_up.py

Currently federation catchup will send the last *local* event that we failed to send to the remote. This can cause issues for large rooms where lots of servers have sent events while the remote server was down, as when it comes back up again it'll be flooded with events from various points in the DAG.
Instead, let's make it so that all the servers send the most recent events, even if its not theirs. The remote should deduplicate the
events, so there shouldn't be much overhead in doing this. Alternatively, the servers could only send local events if they were also extremities and hope that the other server will send the event over, but that is a bit risky.
c.f. https://github.com/matrix-org/synapse/issues/9490 and https://github.com/matrix-org/synapse/pull/9621

Make federation catchup send last event from any server.

---

changelog.d/9636.bugfix
synapse/handlers/set_password.py
synapse/rest/admin/users.py
synapse/storage/databases/main/registration.py
tests/rest/admin/test_user.py

Follow up of #9587 
Based on #9588
Check `password_config.enabled` and `password_config.localdb_enabled` before set a new password.
Add unit tests to admin API
Add needed cache invalidation

Update the check whether a password may be set

---

changelog.d/9643.feature
synapse/api/constants.py
synapse/config/experimental.py
synapse/handlers/space_summary.py
synapse/rest/client/v1/room.py
synapse/server.py

This is very bare-bones for now: federation will come soon, while pagination is descoped for now but will come later.
Unfortunately there is no good reference to the API that it's implementing yet. It's vaguely based on MSC2946, but there are various differences, and reading MSC2946 may well be more confusing than helpful. Writing a doc is on my todo list but I wanted to get this up for review.
Fixes: #9446

Initial spaces summary API

---

changelog.d/9645.misc
scripts-dev/federation_client.py

this is just a dev script so I don't think we need to announce the change particularly.

federation_client: stop adding URL prefix

---

changelog.d/9647.misc
scripts-dev/federation_client.py

Synapse itself seems to have gained support for inline signing_keys in #4889. It's then quite annoying if `federation_client` doesn't work with them.
Also there's a load of code here which is copied from `signedjson`. We already import `signedjson.types`, so I can't see why we're copying it in here.

federation_client: handle inline signing_keys in hs.yaml

---

changelog.d/9644.feature
synapse/api/constants.py
synapse/app/generic_worker.py
synapse/config/experimental.py
synapse/handlers/presence.py
synapse/rest/client/versions.py
tests/handlers/test_presence.py

This PR implements [MSC3026](https://github.com/matrix-org/matrix-doc/pull/3026), which introduces a busy presence state. This state means that the user is online and active in the app, but might not generate new presence events (e.g. the user is in a call and the window's not in focus) and therefore shouldn't get their presence changed to unavailable if no new event have been received in some time.

Implement MSC3026: busy presence state

---

changelog.d/9649.misc
scripts/move_remote_media_to_new_store.py
synapse/push/httppusher.py
synapse/util/frozenutils.py

Hey 👋 , I'm member of the Developer Outreach team at DeepSource and ran DeepSource analysis on my fork of the repo. It found some interesting [code quality improvements](https://deepsource.io/gh/ankitdobhal/synapse/issues) to consider.
This PR fixes a few of the issues detected for you to assess if it is right for you.
Happy to provide the tweaks separately otherwise :)
- Consider merging 'isinstance' calls
- Remove 'redundant' call
- Use 'sys.exit()' calls

chore: Refactor code quality issues

---

changelog.d/9612.docker
docker/Dockerfile

Cf. https://github.com/opencontainers/image-spec/blob/master/annotations.md#pre-defined-annotation-keys
Fixes #9611
Ideally, `org.opencontainers.image.version` would be set in CircleCI. But I am not entirely certain how the release workflow is.

Include opencontainers labels in Docker image

---

changelog.d/9657.feature
synapse/http/connectproxyclient.py
synapse/http/proxyagent.py
tests/http/test_proxyagent.py

Addresses https://github.com/matrix-org/synapse-dinsic/issues/70
This PR causes `ProxyAgent` to attempt to extract credentials from an `HTTPS_PROXY` env var. If credentials are found, a `Proxy-Authorization` header ([details](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Proxy-Authorization)) is sent to the proxy server to authenticate against it. The headers are *not* passed to the remote server.
Also added some type hints.

Allow providing credentials to HTTPS_PROXY

---

changelog.d/8675.misc
synapse/federation/federation_server.py

We patched `matrix-org-hotfixes` a little while ago in #8675 to drop any cross-user key share requests while they were being accidentally spammed by a client. This was a temporary fix until we had some rate-limiting in place.
Rate-limiting landed in https://github.com/matrix-org/synapse/pull/8957. Note that the rate-limit can't be configured, but has what appear to be [sensible defaults](https://github.com/matrix-org/synapse/blob/db2efa9c50569adbfab102b1f447f5a8312b95f3/synapse/config/ratelimiting.py#L105-L113).
Note that the original patch was already actually overridden partially when the rate-limit PR landed, as they conflicted. So we've already lifted the restriction between local devices on matrix.org, but requests were still blocked from being sent over federation. This PR cleans up …

Revert "Patch to temporarily drop cross-user m.key_share_requests (#8675)"

---

changelog.d/9652.feature
synapse/federation/transport/server.py
synapse/handlers/space_summary.py

Builds on the work done in #9643 to add a federation API for space summaries.
There's a bit of refactoring of the existing client-server code first, to avoid too much duplication.

Federation API for Space summary

---

changelog.d/9639.bugfix
synapse/federation/sender/__init__.py
synapse/storage/databases/main/transactions.py

This PR fixes #9635 by ensuring that the `store_destination_rooms_entries` db interaction gets retried indefinitely when it fails with `psycopg2.errors.SerializationFailure`.
This is fine, as this failure is simply a [rollback of the transaction if another transaction had changed the view of the table concurrently](https://www.postgresql.org/docs/10/transaction-iso.html#XACT-SERIALIZABLE), which means the "other" transaction has succeeded, and this one has failed, thus, this is infinitely retry-able until this transaction "succeeds" while the other "loses". In the very worst case, this blocks until the `destinations` table is less congested.
~~And to relieve some of that congestion, the second fix this PR gives is making sure every `handle_room_events` background task only instructs it's …

Fix federation stall on concurrent access errors

---

changelog.d/9674.misc
docs/sample_config.yaml
synapse/config/ratelimiting.py

It's legitimate behaviour to try and join a bunch of rooms at once.
c.f. https://github.com/matrix-org/synapse/issues/9409

Increase default join burst ratelimiting

---

changelog.d/9675.misc
synapse/handlers/sync.py
synapse/rest/client/v2_alpha/sync.py
synapse/server.py
synapse/server_notices/consent_server_notices.py
synapse/server_notices/resource_limits_server_notices.py
synapse/server_notices/server_notices_manager.py
synapse/server_notices/server_notices_sender.py
synapse/server_notices/worker_server_notices_sender.py
synapse/storage/databases/main/deviceinbox.py
synapse/storage/databases/main/monthly_active_users.py

More stuff split off of #9374. The second commit trickled a bit in terms of causing additional type hints in many places.

Add a type hints for service notices to the HomeServer object.

---

changelog.d/9678.misc
setup.py

This fixes the "Cannot determine consistent method resolution order (MRO)" error when running mypy a second time with Twisted 21.2.0.

Bump mypy-zope to 0.2.13.

---

changelog.d/9679.doc
docs/workers.md

I tried routing `^/_matrix/client/(r0|unstable)/auth/.*/fallback/web$` to a generic worker as per the current worker docs, but when attempting to remove devices on a SAML configure instance I got 400 `M_UNRECOGNISED` to `/_matrix/client/r0/auth/m.login.sso/fallback/web`
There is some discussion in https://github.com/matrix-org/synapse/issues/7530#issuecomment-718990782 about routing this to a single worker, but I believe the problem is that `synapse.rest.client.v2_alpha.auth.AuthRestServlet` isn't mounted on workers (and so won't work for any stage type not just `m.login.sso`). I don't feel qualified to say whether it could be mounted on worker(s), so the best I can do is to make the docs reflect what I think the situation is
- Be a short description of your change which makes sense to …

docs: fallback/web endpoint does not appear to be mounted on workers

---

changelog.d/9653.feature
synapse/federation/federation_client.py
synapse/federation/transport/client.py
synapse/handlers/space_summary.py

When we hit an unknown room in the space tree, see if there are other servers that we might be able to poll to get the data.
~~Based on #9652~~.  Fixes: #9447

Spaces summary: call out to other servers

---

changelog.d/9659.misc
setup.cfg
synapse/crypto/context_factory.py
synapse/logging/context.py
synapse/storage/database.py
synapse/util/async_helpers.py
synapse/util/caches/__init__.py
tests/server.py

Part of #9366 
Adds in more test codes except `B006`-`B008`.

Add more bugbear codes

---

changelog.d/9664.misc
synapse/federation/sender/per_destination_queue.py

Fixed undefined variable error in catchup

---

changelog.d/9650.misc
synapse/storage/database.py
synapse/storage/databases/main/presence.py

Split off from https://github.com/matrix-org/synapse/pull/9491
Adds a storage method for getting the current presence of all local users, optionally excluding those that are offline. This will be used by the code in #9491 when a PresenceRouter module informs Synapse that a given user should have `"ALL"` user presence updates routed to them. Specifically, it is used here: https://github.com/matrix-org/synapse/blob/b588f16e391d664b11f43257eabf70663f0c6d59/synapse/handlers/presence.py#L1131-L1133
Note that there is a `get_all_presence_updates` function just above. That function is intended to walk up the table through stream IDs, and is primarily used by the presence replication stream. I could possibly make use of it in the PresenceRouter-related code, but it would be a bit of a bodge.

Add a storage method for returning all current presence from all users

---

INSTALL.md
changelog.d/9667.doc

Make it clearer in the source install step that the platform specific
prerequisites must be installed first.

platform specific prerequisites in source install

---

.buildkite/scripts/test_old_deps.sh
.buildkite/scripts/test_synapse_port_db.sh
changelog.d/9689.misc
contrib/purge_api/purge_history.sh
contrib/purge_api/purge_remote_media.sh
debian/build_virtualenv
demo/clean.sh
demo/start.sh
demo/stop.sh
docker/build_debian.sh
docker/run_pg_tests.sh
scripts-dev/check-newsfragment
scripts-dev/config-lint.sh
scripts-dev/generate_sample_config
scripts-dev/lint.sh
scripts-dev/make_full_schema.sh
scripts-dev/next_github_number.sh
test_postgresql.sh

On NixOS, `bash` isn't under `/bin/bash` but rather in some directory in `$PATH`. Locally, I've been patching those scripts to make them work.
`/usr/bin/env` seems to be the only [portable way](https://unix.stackexchange.com/questions/29608/why-is-it-better-to-use-usr-bin-env-name-instead-of-path-to-name-as-my) to use binaries from the PATH as interpreters.

Use interpreter from $PATH instead of absolute paths in various scripts using /usr/bin/env

---

UPGRADE.rst
docs/reverse_proxy.md

Fixes redirect loop
This is only a short documentation change which I did on github web ui.

Preserve host in example apache config

---

changelog.d/9697.docker
changelog.d/9697.misc
docker/Dockerfile
synapse/python_dependencies.py

This is to ensure that we have an `openssl` version with the latest security patches.
(Apologies for the reformatting, but vscode *really* wants to reformat the dockerfile)

Explicitly upgrade openssl in docker file and enforce new version of cryptography

---

changelog.d/9692.misc
mypy.ini
synapse/api/auth.py
synapse/config/cache.py
synapse/handlers/oidc_handler.py
synapse/logging/opentracing.py
synapse/replication/tcp/protocol.py
synapse/rest/admin/rooms.py
synapse/rest/admin/users.py
synapse/rest/client/v2_alpha/sync.py
synapse/rest/media/v1/preview_url_resource.py
synapse/rest/synapse/client/pick_username.py
synapse/util/caches/__init__.py
tests/replication/tcp/streams/test_typing.py
tests/replication/test_multi_media_repo.py
tests/server.py

Running `dmypy run` will do a `mypy` check while spinning up a daemon that makes rerunning `dmypy run` a lot faster.
`dmypy` doesn't support `follow_imports = silent` and has `local_partial_types` enabled, so this PR enables those options and fixes the issues that were newly raised. Note that `local_partial_types` will be enabled by default in upcoming mypy releases.

Make it possible to use dmypy

---

changelog.d/9698.misc
synapse/app/_base.py
synapse/app/generic_worker.py
synapse/app/homeserver.py

This warning is somewhat confusing to users, so let's suppress it

Suppress CryptographyDeprecationWarning

---

changelog.d/9699.bugfix
synapse/python_dependencies.py

If you have the wrong version of `cryptography` installed, synapse suggests:
```
To install run:
pip install --upgrade --force 'cryptography>=3.4.7;python_version>='3.6''
```
However, the use of ' inside '...' doesn't work, so when you run this, you get
an error.

Fix the suggested pip incantation for cryptography

---

changelog.d/9709.misc
tests/replication/_base.py

Looks like this is the workaround(?) we use in other places where we need to test whether a module exists.
Why this only broke now, I couldn't tell you. Perhaps we configured mypy to only start checking this file recently?

Fix CI by ignore type for None module import

---

changelog.d/9695.doc
docs/sample_config.yaml
synapse/config/oidc_config.py

I've reiterated the advice about using `oidc` to migrate, since I've seen a few
people caught by this.
I've also removed a couple of the examples as they are duplicating the OIDC
documentation, and I think they might be leading people astray.

Update the OIDC sample config

---

changelog.d/9681.misc
synapse/app/generic_worker.py
synapse/federation/send_queue.py
synapse/federation/sender/__init__.py
synapse/replication/tcp/commands.py
synapse/replication/tcp/handler.py
synapse/replication/tcp/streams/federation.py
synapse/server.py

This adds an abstract-class for the `FederationSender` and `FederationRemoteSendQueue` to ensure they implement the same interface, we then return this interface from the `HomeServer` object.
Split out of #9374

Add type hints to for the federation sender.

---

INSTALL.md
changelog.d/9074.doc

…
* [N/A] Pull request includes a [changelog file](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#changelog). The entry should:
* [N/A] Code style is correct (run the [linters](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#code-style))
Signed-off-by: blakehawkins <blake.hawkins.11@gmail.com>

Clarify that register_new_matrix_user is present also when installed via non-pip package

---

changelog.d/9701.misc
scripts-dev/lint.sh

For it's obvious performance benefits. `dmypy` support landed in #9692 (~~although it appear that it doesn't actually work on develop atm...~~ Twisted just needed an upgrade :)

Use 'dmypy run' in lint.sh instead of 'mypy'

---

changelog.d/9711.bugfix
synapse/api/ratelimiting.py
synapse/federation/federation_server.py
synapse/handlers/_base.py
synapse/handlers/auth.py
synapse/handlers/devicemessage.py
synapse/handlers/federation.py
synapse/handlers/identity.py
synapse/handlers/register.py
synapse/handlers/room_member.py
synapse/replication/http/register.py
synapse/rest/client/v1/login.py
synapse/rest/client/v2_alpha/account.py
synapse/rest/client/v2_alpha/register.py
synapse/server.py
tests/api/test_ratelimiting.py

This should fix a class of bug where we forget to check if e.g. the appservice shouldn't be ratelimited.
We also check the `ratelimit_override` table to check if the user has ratelimiting disabled. That table is really only meant to override the event sender ratelimiting, so we don't use any values from it (as they might not make sense for different rate limits), but we do infer that if ratelimiting is disabled for the user we should disabled all ratelimits.
Fixes #9663

Make RateLimiter class check for ratelimit overrides

---

changelog.d/9700.feature
docker/conf/homeserver.yaml
docs/code_style.md
docs/sample_config.yaml
synapse/config/api.py
synapse/handlers/message.py
synapse/storage/databases/main/events_worker.py
tests/utils.py

`room_invite_state_types` was inconvenient as a configuration setting, because
anyone that ever set it would not receive any new types that were added to the
defaults. Here, we deprecate the old setting, and replace it with a couple of
new settings under `room_prejoin_state`.
This is part of fixing #9448.

Replace `room_invite_state_types` with `room_prejoin_state`

---

changelog.d/9685.misc
scripts-dev/complement.sh

This PR rewrites the original complement.sh script with a number of improvements:
* We now use a local checkout of Complement (configurable with `COMPLEMENT_DIR`), instead of downloading the master branch.
* You can now specify a regex of test names to run, or just run all tests.
* We now use the Synapse test blacklist tag (so all tests will pass).

Rewrite complement.sh

---

changelog.d/9720.misc
scripts-dev/lint.sh

This reverts commit f380bb77d19e7dd4ee6f61cd489e240ee4aa8fc2.
Reverting since it gives errors that running `mypy` directly doesn't give. So the `lint.sh` script fails for me every time.
I can merge this across branches after it merges.

Revert "Use 'dmypy run' in lint.sh instead of 'mypy' (#9701)"

---

changelog.d/9717.feature
synapse/api/constants.py
synapse/api/room_versions.py
synapse/config/experimental.py
synapse/event_auth.py
tests/test_event_auth.py

* Creates an experimental room version for a new join rule: `restricted`.
* Implements the `restricted` join rule as the same as `public` for that experimental room version.
* Adds a bunch of unit tests for the `_is_membership_change_allowed`.
Fixes #9712

Add an experimental room version to support restricted join rules.

---

changelog.d/9686.misc
synapse/federation/sender/per_destination_queue.py
synapse/handlers/devicemessage.py
synapse/handlers/sync.py
synapse/handlers/typing.py
synapse/logging/opentracing.py
synapse/notifier.py

This is to try and help track down to device messages that are getting delayed or lost.

Improve tracing for to device messages

---

changelog.d/9734.misc
setup.py

Bugbear [added new checks](https://github.com/PyCQA/flake8-bugbear/releases/tag/21.4.1), however, because we're both not actively ignoring new checks (to a degree) or fixing the bugbear version, these got auto-updated in CI, breaking it because `flake8` is now disapproving of the codebase.

Fix version for bugbear

---

changelog.d/9742.misc
mypy.ini
synapse/handlers/account_validity.py
synapse/handlers/e2e_keys.py
synapse/http/client.py
synapse/notifier.py
synapse/replication/tcp/redis.py
synapse/storage/databases/main/group_server.py
synapse/util/caches/deferred_cache.py
tests/rest/client/v2_alpha/test_auth.py

cc @richvdh, because you spoke about this in `#synapse-dev`
Borne from #9682
Added `no_implicit_optional = True`, and fixed some subsequent lint errors.

Set `no_implicit_optional = True`

---

changelog.d/9736.misc
tests/storage/test_devices.py
tests/storage/test_directory.py
tests/storage/test_end_to_end_keys.py
tests/storage/test_event_push_actions.py
tests/storage/test_profile.py
tests/storage/test_redaction.py
tests/storage/test_registration.py
tests/storage/test_room.py
tests/storage/test_state.py
tests/storage/test_user_directory.py

This converts a bunch of test-cases to use `HomeserverTestCase`.

Convert storage test cases to HomeserverTestCase.

---

changelog.d/9743.misc
synapse/federation/federation_server.py
synapse/federation/transport/server.py
synapse/handlers/federation.py

Adds some missing type hints to the `FederationHandler` and `FederationServer`. It also removes an unused method which should have been removed in #7026.
Some pre-work for #9715.

Add type hints to the federation handler and server.

---

INSTALL.md
README.rst
changelog.d/9723.doc
docs/deprecation_policy.md

Lifts the conclusions from https://github.com/matrix-org/synapse/issues/8782 to be in repo.
This is a bit of a straw man, so please feel free to quibble with the wording.

Add deprecation policy doc

---

changelog.d/9753.misc
tests/config/test_load.py

This reported issue was breaking develop for me. And to be fair, it's a valid issue to fix. The issue is well-described in the error:
>tests/config/test_load.py:40:9: B017 assertRaises(Exception): should be considered evil. It can lead to your test passing even if the code being tested is never executed due to a typo. Either assert for a more specific exception (builtin or custom), use assertRaisesRegex, or use the context manager form of assertRaises.
This issue was blocking #6739's CI from passing.

Fix reported bugbear: too broad exception assertion

---

changelog.d/9730.misc
synapse/federation/federation_client.py
synapse/handlers/device.py
synapse/handlers/e2e_keys.py
synapse/handlers/sync.py
synapse/rest/media/v1/preview_url_resource.py
synapse/state/__init__.py
synapse/util/caches/expiringcache.py

Following up on #9442 this adds some type hints to the expiring cache.

Add type hints to expiring cache.

---

README.rst
changelog.d/9491.feature
docs/presence_router_module.md
docs/sample_config.yaml
synapse/app/generic_worker.py
synapse/config/server.py
synapse/events/presence_router.py
synapse/federation/sender/__init__.py
synapse/handlers/presence.py
synapse/module_api/__init__.py
synapse/server.py
tests/events/test_presence_router.py
tests/handlers/test_sync.py
tests/module_api/test_api.py

Based on https://github.com/matrix-org/synapse/pull/9650
At the moment, if you'd like to share presence between local or remote users, those users must be sharing a room together. This isn't always the most convenient or useful situation though.
This PR adds a module to Synapse that will allow deployments to set up extra logic on where presence updates should be routed. The module must implement two methods, `get_users_for_states` and `get_interested_users`. These methods are given presence updates or user IDs and must return information that Synapse will use to grant passing presence updates around.
A method is additionally added to `ModuleApi` which allows triggering a set of users to receive the current, online presence information for all users they are considered interested in. This …

Add a Synapse Module for configuring presence update routing

---

changelog.d/9654.feature
synapse/http/site.py
synapse/logging/context.py
synapse/metrics/background_process_metrics.py
synapse/replication/tcp/protocol.py
tests/crypto/test_keyring.py
tests/logging/test_terse_json.py
tests/unittest.py
tests/util/caches/test_descriptors.py
tests/util/test_logcontext.py

This was some work I had going towards #8683, it adds some basic request information to the structured logs (similar to information available in the [processed log lines](https://github.com/matrix-org/synapse/wiki#what-do-all-those-fields-in-the-processed-line-mean)).
In particular this should allow pivoting on things like IP address or user ID in structured logs.
In order to do this there was a bit of refactoring necessary to `LoggingContext`. Each commit should be separately reviewable.

Record more information into structured logs

---

changelog.d/9735.feature
scripts-dev/complement.sh
synapse/handlers/room_member.py

Expands the support for [MSC3083](https://github.com/matrix-org/matrix-doc/pull/3083) by checking membership in a space when joining a restricted room.
Fixes #9714

Check for proper membership during a local join of restricted rooms.

---

changelog.d/9765.docker
docker/Dockerfile

The opencontainers labels included in #9612 don't make any sense on the intermediate builder image. The final
images needs them to be of use for anyone.

Put opencontainers labels to the final image

---

changelog.d/9770.bugfix
synapse/federation/sender/__init__.py

We pull all destinations requiring catchup from the DB in batches.
However, if all those destinations get filtered out (due to the
federation sender being sharded), then the `last_processed` destination
doesn't get updated, and we keep requesting the same set repeatedly.

Fix sharded federation sender sometimes using 100% CPU.

---

.buildkite/scripts/test_old_deps.sh
changelog.d/9769.misc
tox.ini

These are the changes needed to be able to run the `olddeps` build on bionic instead of xenial:
* tweak the script and tox env names so that it will run on whatever version of python3 is available, rather than 3.5 specifically.
* bionic has tox 2.5 (instead of 2.3), and apparently on tox 2.5, `usedevelop` overrides `skip_install`, so we end up trying to install the full dependencies even for the `-old` environment..

Fix incompatibility with bionic

---

.buildkite/scripts/test_old_deps.sh
changelog.d/9766.feature
scripts-dev/build_debian_packages
setup.py
synapse/storage/database.py
synapse/storage/databases/main/client_ips.py
synapse/storage/databases/main/devices.py
synapse/storage/databases/main/events_bg_updates.py
synapse/storage/engines/_base.py
synapse/storage/engines/postgres.py
synapse/storage/engines/sqlite.py
tests/storage/test_database.py
tox.ini

Require py36, Postgres 9.6, and sqlite 3.22

---

.github/workflows/tests.yml
changelog.d/9661.misc

Compare to https://github.com/matrix-org/pipelines/blob/master/synapse/pipeline.yml
Per discussion in https://github.com/matrix-org/synapse/discussions/9622
(I _think_ this is complete, aside from double-checking logs to and log uploading from the Buildkite pipeline)

Proof of concept for GitHub Actions

---

changelog.d/9771.misc
scripts-dev/complement.sh

Fixes #9756 by providing the additional tag. This depends on matrix-org/complement#101 and will need a corresponding pipelines PR.

Enable complement tests for MSC2946.

---

changelog.d/9780.bugfix
synapse/federation/transport/server.py

There's no point logging this twice.

Fix duplicate logging of exceptions in transaction processing

---

changelog.d/9793.misc
debian/build_virtualenv
debian/changelog
scripts-dev/build_debian_packages

Add option to skip unit tests when building debs

---

changelog.d/9648.feature
docs/admin_api/user_admin_api.rst
synapse/rest/admin/__init__.py
synapse/rest/admin/users.py
synapse/rest/client/v1/room.py
synapse/storage/databases/main/room.py
tests/rest/admin/test_user.py

Fixes: #6286
A few questions:
1. Is the `RoomWorkerStore` the right class for `get_ratelimit_for_user`, `set_ratelimit_for_user`, and `delete_ratelimit_for_user`?
Should I move it to `RegistrationWorkerStore` or anywhere else?
2. Is the best solution to delete a custom ratelimit with http `DELETE`. Or do you prefer to set to `null` with http `POST`?
3. When get status with http `GET` and no custom ratelimit is set, do you prefer return an empty dict (`{}`) or values with `null` (`      "messages_per_second": null, "burst_count": null`)
- Use markdown where necessary, mostly for `code …

Add an admin API to manage ratelimit for a specific user

---

changelog.d/9781.misc
pyproject.toml
synapse/config/tls.py
synapse/handlers/presence.py
synapse/http/matrixfederationclient.py
synapse/http/site.py
synapse/storage/database.py
tests/replication/slave/storage/test_events.py
tests/test_state.py
tests/test_utils/event_injection.py
tests/utils.py

Bump black configuration to target py36

---

changelog.d/9713.misc
scripts-dev/release.py
setup.py

This does everything up to tagging the actual release.
Sample run:
```
$ ./scripts-dev/release.py
Updating git repo...
RC [Y/n]: 
Release type (major, hotfix) [major]: 
Create new version: 1.31.0rc1? [Y/n]: 
Which branch should release be based off of? [develop]: 
Loading template...
Finding news fragments...
Rendering news fragments...
Writing to newsfile...
Staging newsfile...
Removing news fragments...
I want to remove the following files:
... < list of changelog files > ...
Is it okay if I remove those files? [Y/n]: 
Done!
... < displays diff > ...
Edit changelog? [y/N]: y
Push branch to github? [Y/n]: 
```

Add release helper script

---

changelog.d/9801.doc
docker/README.md

Context is in https://github.com/matrix-org/synapse/issues/9764#issuecomment-818615894.
I struggled to find a more official link for this. The problem occurs when using WSL1 instead of WSL2, which some Windows platforms (at least Server 2019) still don't have. Docker have updated their documentation to paint a much happier picture now given WSL2's support.
The last sentence here can probably be removed once WSL1 is no longer around... though that will likely not be for a very long time.

Add note to docker docs explaining platform support

---

changelog.d/9788.bugfix
synapse/config/repository.py
synapse/rest/media/v1/media_repository.py
synapse/rest/media/v1/preview_url_resource.py

This PR solves thumbnail generation in previews for some sites that use not quite standard Content-Type headers as described in #2853.

More robust handling of the Content-Type header for thumbnail generation

---

changelog.d/9796.misc
synapse/app/generic_worker.py
synapse/handlers/presence.py
synapse/replication/tcp/client.py
synapse/server.py
tests/replication/_base.py

This is in preparation for moving presence off master.

Move some replication processing out of generic_worker

---

changelog.d/9815.misc
synapse/app/generic_worker.py
synapse/app/homeserver.py
synapse/crypto/keyring.py
synapse/federation/federation_server.py
synapse/federation/sender/transaction_manager.py
synapse/rest/media/v1/config_resource.py
synapse/server.py
tests/app/test_openid_listener.py

Every single time I want to access the config object, I have to remember
whether or not we use `get_config`. Let's just get rid of it.

remove `HomeServer.get_config`

---

changelog.d/9825.misc
synapse/storage/databases/main/events.py

There are a couple of points in `persist_events` where we are doing a query per event in series, which we can replace.

Small speed up joining large remote rooms

---

changelog.d/9821.misc
synapse/handlers/user_directory.py
synapse/storage/databases/main/roommember.py

Fixes: #9797.
Updates the user directory handling code to use `current_state_events` and `room_membership` tables to determine the membership state of a room, instead of calculating it from scratch. It does this by making use of the `get_users_in_room` storage method. I also needed to add a method that produced user profile information without state calculation.
I used the `room_membership` table for this, which has profile information, unlike `current_state_events` which would require pulling the event itself. I'm not totally sure if `room_memberships` is as up to date as `current_state_events` but tests pass???
Should help reduce CPU usage on the user directory, especially when memberships change in rooms with lots of state history.

User directory: use calculated room membership state instead

---

changelog.d/9828.feature
synapse/federation/send_queue.py
synapse/federation/sender/__init__.py
synapse/handlers/presence.py
synapse/module_api/__init__.py

Instead we can read from the presence replication stream.
Split out from #9819

Don't send normal presence updates over federation replication stream

---

changelog.d/9802.bugfix
synapse/handlers/identity.py
synapse/util/stringutils.py

Signed-off-by: Denis Kasak <dkasak@termina.org.uk>

Sanity check identity server passed to bind/unbind.

---

changelog.d/9838.misc
scripts-dev/definitions.py
scripts-dev/list_url_patterns.py
setup.cfg
synapse/event_auth.py
synapse/federation/send_queue.py
synapse/handlers/auth.py
synapse/handlers/device.py
synapse/handlers/federation.py
synapse/logging/_remote.py
synapse/rest/key/v2/remote_key_resource.py
synapse/storage/databases/main/events.py
tests/handlers/test_federation.py
tests/replication/tcp/streams/test_events.py
tests/rest/admin/test_device.py
tests/rest/admin/test_event_reports.py
tests/rest/admin/test_room.py
tests/rest/admin/test_statistics.py
tests/rest/admin/test_user.py
tests/rest/client/v1/test_rooms.py
tests/storage/test_event_metrics.py
tests/unittest.py
tests/utils.py

Part of #9366
Fixes `B007` BugBear violations, the last one.

Fix (final) Bugbear violations

---

changelog.d/9850.feature
synapse/federation/sender/__init__.py
synapse/handlers/presence.py

Broke in #9828.
The reason for filtering the presence state in `maybe_send_presence_to_interested_destinations` is that otherwise we'd do it at each call site.

Fix bug where we sent remote presence states to remote servers

---

changelog.d/9829.bugfix
synapse/logging/context.py
synapse/metrics/background_process_metrics.py
synapse/replication/tcp/protocol.py
synapse/util/metrics.py
tests/logging/test_terse_json.py
tests/test_federation.py
tests/util/caches/test_descriptors.py

As far as I can tell our logging contexts are meant to log the request ID, or sometimes the request ID followed by a suffix (this is generally stored in the `name` field of `LoggingContext`). There's also code to log the name@memory location, but I'm not sure this is ever used.
This simplifies the code paths to require every logging context to have a name and use that in logging. For sub-contexts (created via `nested_logging_contexts`, `defer_to_threadpool`, `Measure`) we use the current context's str (which becomes their name or the string "sentinel") and then potentially modify that (e.g. add a suffix).
Fixes #9824

Always use the name as the log ID.

---

UPGRADE.rst

Fixes https://github.com/matrix-org/synapse/issues/9846.
Adds important removal information from the top of https://github.com/matrix-org/synapse/releases/tag/v1.32.0rc1 into UPGRADE.rst.

Add Application Service registration type requirement + py35, pg95 deprecation notices to v1.32.0 upgrade notes

---

changelog.d/9854.bugfix
synapse/metrics/background_process_metrics.py
synapse/replication/tcp/protocol.py

This undoes part of b076bc276e881b262048307b6a226061d96c4a8d.

Stop BackgroundProcessLoggingContext making new prometheus timeseries

---

changelog.d/9857.bugfix
synapse/logging/context.py

Fixes https://github.com/matrix-org/synapse-s3-storage-provider/issues/55

Make LoggingContext's name optional

---

CHANGES.md
UPGRADE.rst

1.32.0 also introduced an incompatibility with Synapse modules that make use of `synapse.logging.context.LoggingContext`, such as [synapse-s3-storage-provider](https://github.com/matrix-org/synapse-s3-storage-provider).
This PR adds a note to the 1.32.0 changelog and upgrade notes about it.

Note LoggingContext signature change incompatibility in 1.32.0

---

changelog.d/9856.misc
synapse/config/oidc.py
synapse/events/spamcheck.py
synapse/federation/sender/__init__.py
synapse/handlers/appservice.py
synapse/handlers/device.py
synapse/handlers/presence.py
synapse/handlers/sso.py
synapse/handlers/sync.py
synapse/notifier.py
synapse/replication/tcp/protocol.py
synapse/state/__init__.py
synapse/state/v2.py
synapse/storage/_base.py
synapse/storage/database.py
synapse/storage/databases/main/devices.py
synapse/storage/databases/main/event_federation.py
synapse/storage/databases/main/events_worker.py
synapse/storage/databases/main/roommember.py
synapse/storage/databases/main/search.py
synapse/storage/databases/main/stream.py
synapse/storage/persist_events.py
synapse/storage/prepare_database.py
synapse/types.py
synapse/util/caches/stream_change_cache.py
synapse/util/iterutils.py

This is no longer required, since we have dropped support for Python 3.5.

Remove `synapse.types.Collection`

---

changelog.d/9867.bugfix
synapse/handlers/device.py
synapse/storage/databases/main/devices.py

Clear the resync bit after resyncing device lists

---

changelog.d/9858.misc
demo/start.sh

The `--no-rate-limit` parameter should disable, or make useless, any rate limiting.
I updated start.sh with the list available in sample_config.yaml

Handle all new rate limits in demo scripts

---

changelog.d/9871.misc
tests/utils.py

I was hitting room invite rate limits in [this test](https://github.com/matrix-org/synapse-dinsic/blob/0060eb332c307887ca0a911f91940de0cea2bdef/tests/rest/client/test_room_access_rules.py#L851-L977). With the `prepare` statement and the invites in the test itself I was finding 429's failing the test.
I think it may just be a matter of time before we run into a similar issue in a future unit test. So raising the rate limit for tests by default seemed like the thing to do.

Remove room and user invite ratelimits in default unit test config

---

changelog.d/9875.misc
synapse/handlers/oidc.py
synapse/rest/synapse/client/new_user_consent.py
synapse/types.py

Mostly because if you try and do `asizeof(user)` it'll try and iterate (since it has an `__iter__`), but then it'll fail as `__iter__` raises. Plus, this easily allows us to add type hints.

Make DomainSpecificString an attrs class

---

changelog.d/9876.misc
synapse/api/auth.py
synapse/api/auth_blocking.py
synapse/event_auth.py

I was poking in this code and got annoyed with not having auto-complete.
I think it is all pretty straightforward, there's a second commit which removes an unused method.

Add types to auth and auth_blocking.

---

changelog.d/9874.misc
synapse/app/generic_worker.py
synapse/app/homeserver.py
synapse/http/site.py
tests/replication/_base.py
tests/test_server.py
tests/unittest.py

It turns out that `Site` takes a `reactor` argument. Then it attaches that reactor's `callLater` to any `HTTPChannel`s that the site creates (via a bit of hackery in [`HTTPFactory.buildProtocol`](https://github.com/twisted/twisted/blob/fc76fcbeb9e8b96eed30761a5bfca6e9be115f5c/src/twisted/web/http.py#L3167)).
This is particularly important to get right in test code, because otherwise `HTTPChannel` ends up setting timeouts on the *default* reactor, which then makes trial complain about a dirty reactor; but since some tests use the homeserver's default site, we need to get it right for that code too.

pass a reactor into SynapseSite

---

changelog.d/9817.misc
synapse/api/constants.py
synapse/app/_base.py
synapse/app/admin_cmd.py
synapse/app/generic_worker.py
synapse/app/homeserver.py
synapse/config/logger.py
synapse/event_auth.py
synapse/http/site.py
synapse/rest/media/v1/upload_resource.py
synapse/server.py
tests/http/test_site.py
tests/replication/_base.py
tests/test_server.py
tests/unittest.py

There's a couple of commits here. Hopefully each one is clear enough.
Fixes: #1610

Improved validation for received requests

---

changelog.d/9887.misc
synapse/handlers/presence.py

This should be a lot quicker than asking the state handler.

Use current state table for `presence.get_interested_remotes`

---

changelog.d/9886.misc
synapse/util/caches/lrucache.py

This removes the set we store in each node, and replaces it with either `None` if empty or a list. Since we expect there to be only a couple of callbacks per entry the cost of deduplicating the list is likely the same (or faster!) than maintaining a set, and has a smaller memory footprint.
The size of storing `None` is basically 0, an empty list is 56 bytes, and an empty set is 248 bytes. 
It doesn't look like it's had much effect on jki.re, but that might be because my caches aren't that large :shrug:

Reduce memory footprint of caches

---

changelog.d/9895.bugfix
synapse/storage/database.py

Fixes #9893 hopefully. This should now log the connection ID for log lines.
I audited places where we create `LoggingContext` (again), but the rest seemed OK? Would appreciate a double checking though.

Use the parent's logging context name for runWithConnection.

---

changelog.d/9900.bugfix
synapse/handlers/presence.py
tests/handlers/test_presence.py

Only affects workers. Introduced in #9819.
Fixes #9899.

Fix tight loop handling presence replication.

---

changelog.d/9889.feature
changelog.d/9889.removal
docs/admin_api/rooms.md
synapse/rest/admin/rooms.py
tests/rest/admin/test_room.py

Fix #9032 by marking as deprecated the previous endpoint and add a new DELETE endpoint for a room

Delete room endpoint

---

changelog.d/9896.bugfix
changelog.d/9896.misc
synapse/events/spamcheck.py
synapse/handlers/directory.py
synapse/handlers/identity.py
synapse/handlers/message.py
synapse/handlers/room_member.py
synapse/handlers/ui_auth/checkers.py

With #9885 I think that all of `synapse.handlers` has type hints now.
Should be reviewable commit by commit, I'll leave some inline comments.

Add missing type hints to handlers.

---

changelog.d/9904.misc
synapse/replication/tcp/external_cache.py

It looks like on matrix.org this can take a surprisingly long time.

Time external cache response time

---

changelog.d/9919.feature
synapse/rest/client/v2_alpha/sync.py
tests/rest/client/v2_alpha/test_sync.py
tests/server_notices/test_resource_limits_server_notices.py

This leaves out all optional keys from /sync. This should be fine for all clients tested against conduit already, but it may break some clients, as such we should check, that at least most of them don't break horribly and maybe back out some of the individual changes. (We can probably always leave out groups for example, while the others may cause more issues.)
Clients I have tested:
This also needs an updated sytest, see https://github.com/matrix-org/sytest/pull/1040
In my testing this decreases the sync json response to about half, which saves about 30% of data on every /sync. It also makes debugging a lot easier, since the response json is easier to read. :3
Tell me if the news entry is descriptive enough, since some people may want to be aware of this change, if they are client …

Leave out optional keys from /sync

---

changelog.d/9913.docker
docker/Dockerfile
docker/README.md

Docker healthcheck timings - add startup delay and changed interval

---

changelog.d/9905.feature
changelog.d/9905.misc
synapse/handlers/federation.py
synapse/handlers/message.py

This may shave some time off event sending and make Redis less busy.

Don't set the external cache if its been done recently

---

changelog.d/9902.feature
docs/sample_config.yaml
synapse/app/generic_worker.py
synapse/app/homeserver.py
synapse/config/server.py
synapse/metrics/__init__.py

Synapse can be quite memory intensive, and unless care is taken to tune
the GC thresholds it can end up thrashing, causing noticable performance
problems for large servers. We fix this by limiting how often we GC a
given generation, regardless of current counts/thresholds.
This does not help with the reverse problem where the thresholds are set
too high, but that should only happen in situations where they've been
manually configured.
Adds a `gc_min_seconds_between` config option to override the defaults.
Fixes #9890.

Limit how often GC happens by time.

---

changelog.d/9915.feature
synapse/api/constants.py
synapse/handlers/space_summary.py

Blocked on FCP matrix-org/matrix-doc#1772.
Also see matrix-org/matrix-js-sdk#1679, matrix-org/complement#107.

Support stable MSC1772 spaces identifiers.

---

changelog.d/9928.bugfix
synapse/handlers/space_summary.py

Per updates the [MSC2946](https://github.com/matrix-org/matrix-doc/pull/2946), this is necessary for clients to sort rooms (as specified in MSC1772).

Include the origin_server_ts of the create event in Spaces Summary.

---

changelog.d/9919.feature
synapse/rest/client/v2_alpha/sync.py
tests/rest/client/v2_alpha/test_sync.py
tests/server_notices/test_resource_limits_server_notices.py

This reverts commit e9eb3549d32a6f93d07de8dbd5e1ebe54c8d8278 / #9919
The PR breaks Element iOS push, as its handling expects some of the keys to be there. We revert while they fix it and put out a new release.

Revert "Leave out optional keys from /sync (#9919)"

---

changelog.d/9931.misc
scripts-dev/make_full_schema.sh

A couple of things here:
* If we're running against a postgres whose default collation is UTF-8, we would create a postgres database which synapse would refuse to use, so set the right options to fix that.
* We didn't use the collected postgres password when trying to drop the redundant tables. We might as well set the magic PGHOST, PGUSER and PGPASSWORD env vars to save having to set them on each command.

Fix make_full_schema to create the db with the right options and user

---

changelog.d/9950.feature
synapse/handlers/message.py

Fixes regression in send PDU times introduced in #9905.

Always cache 'event_to_prev_state_group'

---

changelog.d/9961.bugfix
synapse/api/constants.py
synapse/federation/federation_server.py
synapse/handlers/devicemessage.py

Fix `m.room_key_request` to-device messages

---

changelog.d/9959.misc
synapse/federation/sender/per_destination_queue.py
synapse/logging/__init__.py
synapse/notifier.py
synapse/replication/tcp/client.py
synapse/storage/databases/main/deviceinbox.py

Hopefully this will help us track down where to-device messages are getting lost/delayed in #9533, #9564, etc.

Add debug logging for issue #9533

---

changelog.d/9951.feature
synapse/handlers/message.py

This is because sometimes redis can take a 50ms to respond, and there's no point blocking the request waiting for the responses.

Run cache_joined_hosts_for_event in background

---

changelog.d/9978.feature
docs/opentracing.md
docs/sample_config.yaml
synapse/api/auth.py
synapse/config/tracer.py

Add a config option which allows enabling opentracing by user id, eg for
debugging requests made by a test user.

Support enabling opentracing by user

---

changelog.d/9984.misc
synapse/util/stringutils.py

Functionally identical, but more obviously cryptographically secure.
...Explicit is better than implicit?
Avoids needing to know that SystemRandom() implies a CSPRNG, and
complies with the big scary red box on the documentation for random:
> Warning:
>   The pseudo-random generators of this module should not be used for
>   security purposes. For security or cryptographic uses, see the
>   secrets module.
https://docs.python.org/3/library/random.html
- End with either a period (.) or …

Use Python's secrets module instead of random

---

changelog.d/9985.misc
synapse/util/stringutils.py

We can get away with just catching UnicodeError here.
⋮
+-- ValueError
|    +-- UnicodeError
|         +-- UnicodeDecodeError
|         +-- UnicodeEncodeError
|         +-- UnicodeTranslateError
⋮
https://docs.python.org/3/library/exceptions.html#exception-hierarchy

Simplify exception handling in is_ascii.

---

changelog.d/9986.misc
synapse/config/registration.py

Our strtobool already returns a bool, so no need to re-cast here

Remove superfluous call to bool()

---

changelog.d/9987.misc
synapse/storage/_base.py
synapse/storage/databases/main/registration.py

It's not obvious that instances of SQLBaseStore each need their own
instances of random.SystemRandom(); let's just use random directly.
Introduced by 52839886d664576831462e033b88e5aba4c019e3

Remove unnecessary SystemRandom from SQLBaseStore

---

changelog.d/9975.misc
synapse/storage/databases/main/devices.py
synapse/storage/databases/main/end_to_end_keys.py
synapse/storage/databases/main/user_erasure_store.py
synapse/util/caches/descriptors.py
tests/util/caches/test_descriptors.py

- use a tuple rather than a list for the iterable that is passed into the
wrapped function, for performance
- test that we can pass an iterable and that keys are correctly deduped.

Minor `@cachedList` enhancements

---

changelog.d/9981.misc
scripts-dev/build_debian_packages
scripts-dev/lint.sh
scripts/export_signing_key
scripts/generate_config
scripts/hash_password
scripts/synapse_port_db
tox.ini

Turns out these scripts weren't getting linted.

Run `black` on the scripts

---

changelog.d/9974.misc
synapse/handlers/space_summary.py

Just adds some docstrings / updates some comments. I pulled this out of #9922 to reduce that diff and highlight the changes from that PR better.

Additional comments for space summary handler

---

changelog.d/10002.bugfix
synapse/handlers/space_summary.py

Per matrix-org/matrix-doc#3195.

Fix the allowed range of valid ordering characters for spaces.

---

changelog.d/10007.feature
synapse/handlers/event_auth.py
synapse/handlers/federation.py
synapse/handlers/room_member.py

Based on the conversation from https://github.com/matrix-org/synapse/pull/9922/files#r634207554 and a discussion between @erikjohnston and I.
This modifies the checks against the `restricted` join rules to raise an `AuthError` directly, instead of returning a boolean.

Refactor checking restricted join rules

---

changelog.d/9958.feature
mypy.ini
synapse/federation/federation_client.py
synapse/federation/transport/client.py
synapse/http/client.py
synapse/http/matrixfederationclient.py
synapse/python_dependencies.py

Instead of parsing the full response to `/send_join` into Python objects (which can be huge for large rooms) and *then* parsing that into events, we instead use ijson to stream parse the response directly into `EventBase` objects.
Question: Do we want to make this an optional dependency? It should be easy (just a case of adding a `JsonParser` subclass), though does mean we have more things to test

Use ijson to parse the response to `/send_join`, reducing memory usage.

---

changelog.d/10018.misc
synapse/crypto/keyring.py
synapse/federation/federation_base.py

Also add support for giving a callback to generate the JSON object to
verify. This should reduce memory usage, as we no longer have the event
in memory in dict form (which has a large memory footprint) for extend
periods of time.

Add `Keyring.verify_events_for_server` and reduce memory usage

---

changelog.d/10017.misc
synapse/util/batching_queue.py
tests/util/test_batching_queue.py

This will be used during for the rewrite of the `KeyRing`.

Add a batching queue implementation.

---

changelog.d/10014.bugfix
synapse/storage/databases/main/presence.py

Signed-off-by: Marek Matys <themarcq@gmail.com>
https://github.com/matrix-org/synapse/issues/9962
This is a fix for above problem.
I fixed it by swaping the order of insertion of new records and deletion of old ones. This ensures that we don't delete fresh database records as we do deletes before inserts.

Fixed removal of new presence stream states

---

changelog.d/10038.feature
synapse/handlers/space_summary.py

Follow-up to #9922 to remove (now) unused properties on the handler.

Remove unused properties on SpaceSummaryHandler

---

changelog.d/10029.bugfix
synapse/rest/media/v1/media_repository.py
synapse/rest/media/v1/thumbnailer.py

Fixes https://github.com/matrix-org/synapse/issues/10028

Fix /upload 500'ing when presented a very large image

---

changelog.d/10050.misc
synapse/storage/state.py

Fix `get_state_ids_for_event` return type typo to match what the function actually does
Split out from https://github.com/matrix-org/synapse/pull/9247
It looks like a typo copy/paste from `get_state_for_event` above.

Fix `get_state_ids_for_event` return type typo to match what the function actually does

---

changelog.d/10043.doc
docs/admin_api/rooms.md

Add missing entry to the table of contents of room admin API

---

changelog.d/10011.feature
docs/sample_config.yaml
synapse/config/experimental.py
synapse/config/homeserver.py

This enables the experimental spaces flag by default.
* Do we want to do this for the multi-SSO providers and busy presence?
* Are there things we want to move behind a different flag (maybe the restricted rooms parts)?

Enable spaces by default.

---

changelog.d/9993.misc
synapse/replication/slave/storage/client_ips.py
synapse/storage/databases/main/client_ips.py
synapse/storage/databases/main/devices.py
synapse/storage/databases/main/events_worker.py
synapse/util/caches/deferred_cache.py
synapse/util/caches/descriptors.py
synapse/util/caches/lrucache.py
synapse/util/caches/treecache.py
tests/util/test_lrucache.py
tests/util/test_treecache.py

`keylen` seems to be a thing that is frequently incorrectly set, and we don't really need it.
The only time it was used was to figure out if we had removed a subtree in `del_multi`, which we can do better by changing `TreeCache.pop` to return a different type (`TreeCacheNode`).
Commits should be independently reviewable.

Remove `keylen` from `LruCache`.

---

.buildkite/postgres-config.yaml
.buildkite/scripts/test_synapse_port_db.sh
.buildkite/sqlite-config.yaml
changelog.d/9991.bugfix
scripts/synapse_port_db

Also, run it twice in CI, in an attempt to stop us having these problems.
fixes #9979

Fix off-by-one-error in synapse_port_db

---

changelog.d/9995.bugfix
synctl

while I'm here, I'm merging `start` and `start_worker`.

Fix --no-daemonize for synctl with workers

---

changelog.d/10045.docker
docker/conf/log.config

Fixes #9970 
Signed-off-by: Sergio Miguéns Iglesias <lonyelon@lony.xyz>

Fix docker image to not log at `/homeserver.log`

---

changelog.d/9982.misc
mypy.ini
synapse/config/saml2.py
synapse/storage/databases/main/keys.py
synapse/util/hash.py
synapse/util/iterutils.py
synapse/util/module_loader.py
synapse/util/msisdn.py
tests/util/test_itertools.py

Some of the files in `synapse.util` had type hints, but weren't in `mypy.ini` so weren't being checked. 😢

Partially add type hints to synapse.util

---

changelog.d/10039.misc
docker/configure_workers_and_start.py
scripts-dev/complement.sh

This attempts to be able to run complement with Synapse worker mode via the `complement.sh` script. Adding a `WORKERS=1` will cause them to be used.
It also fixes a couple of minor things necessary to get this to work.
Corresponding complement PR: matrix-org/complement#116.

Run complement with Synapse workers manually.

---

changelog.d/10046.doc
docs/CAPTCHA_SETUP.md

Update CAPTCHA documentation to mention turning off verify origin feature

---

changelog.d/10040.feature
docs/admin_api/media_admin_api.md
synapse/rest/admin/media.py
synapse/storage/databases/main/media_repository.py
tests/rest/admin/test_media.py

Add an admin API for unprotecting local media from quarantine

---

.circleci/config.yml
changelog.d/9906.misc

The `only` field takes a string or list of strings per the Circle docs:
https://circleci.com/docs/2.0/configuration-reference/#branches

Tell CircleCI to build Docker images from `main`

---

INSTALL.md
changelog.d/10057.doc

Tweak wording of database recommendation in INSTALL.md

---

changelog.d/10063.removal
docs/sample_config.yaml
synapse/api/room_versions.py
synapse/config/experimental.py
synapse/federation/transport/server.py
synapse/rest/client/v1/room.py

...to always enable the Spaces features (under unstable endpoints).
Fixes #10061

Remove the experimental spaces flag.

---

changelog.d/10054.misc
changelog.d/10054.removal
synapse/app/_base.py
synapse/config/tls.py
tests/config/test_tls.py

we don't need to reload the tls cert if we don't have any tls listeners.
Follow-up to #9280.

Remove redundant code to reload tls cert

---

README.rst
changelog.d/9221.doc

The intent is to make it clearer that running Synapse on the same domain as another sensitive web application is not a good idea due to possibility of XSS.
Signed-off-by: Denis Kasak <dkasak@termina.org.uk>

Clarify security note regarding the domain Synapse is hosted on.

---

changelog.d/10079.bugfix
synapse/federation/transport/server.py

This fixes a bug caused by the combination of #9922 and #9947 merging separately. The former added an additional parameter to `federation_space_summary` while the latter added an additional call to `federation_space_summary`. 😢 
I found this while brushing off a branch to add some type hints to the `synapse/federation/transport/server.py`, but those were too invasive to put into a release branch.

Pass the origin when calculating the spaces summary over GET.

---

changelog.d/10078.misc
synapse/util/batching_queue.py
tests/util/test_batching_queue.py

Fix up `BatchingQueue`

---

changelog.d/10077.feature
docs/admin_api/event_reports.md
synapse/rest/client/v2_alpha/report_event.py
synapse/storage/databases/main/room.py
tests/rest/admin/test_event_reports.py
tests/rest/client/v2_alpha/test_report_event.py

Implements MSC2414: https://github.com/matrix-org/matrix-doc/pull/2414
See #8551 
Signed-off-by: Callum Brown <callum@calcuode.com>

Make reason and score optional for report_event

---

changelog.d/10092.bugfix
synapse/api/auth.py
synapse/federation/transport/server.py
synapse/logging/opentracing.py
synapse/metrics/background_process_metrics.py

... because tags on spans which aren't being sampled get thrown away.

Set opentracing priority before setting other tags

---

changelog.d/10074.misc
synapse/logging/opentracing.py

Was running into exceptions attempting to use the opentracing support with another exporter (Datadog) and found this.
`opentracing.tracer.inject` is documented to take a `SpanContext`, not a `Span`: https://github.com/opentracing/opentracing-python/blob/master/opentracing/tracer.py#L199. Perhaps different implementations handle passing the wrong object in some way, but this seemed more correct. Luckily `Span`s have an easy-to-access `context` property for us to use: https://github.com/opentracing/opentracing-python/blob/master/opentracing/span.py#L76
This change resolved our issue with the datadog exporter, but unfortunately I don't have a Jaegar setup to test against so I haven't done that testing.
- Be a short description of your change which makes sense to users. "Fixed a bug that …

Fix opentracing inject to use the SpanContext, not the Span

---

changelog.d/10109.bugfix
synapse/handlers/space_summary.py

This fixes #10104 to not show invite-only rooms to everyone in a space.
This was due to a bug in the refactoring done in #9922 where we called a method expecting an exception to be raised, but the function bailed early if the restricted join rules weren't used. To fix it, I called some lower-level functions which seems clearer.

Do not show invite-only rooms in spaces summary (unless joined/invited).

---

.github/workflows/tests.yml
changelog.d/10094.misc

... using the script from https://github.com/matrix-org/sytest/pull/1052.

github actions: summarize Sytest results in an easy-to-read format

---

changelog.d/10044.feature
docs/admin_api/media_admin_api.md
synapse/rest/admin/media.py
synapse/storage/databases/main/room.py
tests/rest/admin/test_media.py

Related to: #6681, #5956, #10040

Add new admin APIs to remove media by media ID from quarantine.

---

changelog.d/10111.misc
synapse/notifier.py

The existing tracing reports an error each time there is a timeout, which isn't
really representative.
Additionally, we log things about the way `wait_for_events` works
(eg, the result of the callback) to the *parent* span, which is confusing.

Improve opentracing annotations for Notifier
